### ISSUE TITLE
[Setup Wizard] - Math on Product Types doesn't add up

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#32227] opened 2021-10-13 23:33 UTC
### Describe the bug
Toggling between the monthly and yearly pricing on the Product Types step of the Setup Wizard produces different pricing (because of rounding, and you can't have partial cents).

For example, Subscriptions are $16.58 per month.  $16.58 * 12 = $198.96 but the displayed yearly pricing is $199.  

### To Reproduce

1. Go to /wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=product-types
2. Note the monthly prices.  One would expect the yearly price to be this number * 12
3. Click toggle
4. Compare prices

### Actual behavior:
The pricing is out by a few cents for Subscriptions, Memberships, Bundles and Customizable Products ($4.08 * 12 = $48.96)

### Expected behavior
It's clear that this is a rounding issue.  The price for each service is billed annually, so the monthly prices are just an approximation -- but the default is to display the approximation, not the actual price -- which is a little misleading.  

### Desktop (please complete the following information):

* OS: MacOS
* Browser: Chrome
* Version: 94

### Additional context

It's not a huge deal financially, but if one price is displayed and a different price is charged, that's a bit misleading.  What if people don't notice the toggle, and just assume that the price will be $monthly * 12?

**Comment by jacob-sewell** [comment] 2021-10-19 21:53
Thanks for bringing this to our attention, @lanej0. We'll need to consider how best to address the discrepancy, so I'll flag this for our team to follow up on in a future release.

Watch this space for future developments.

**Comment by moon0326** [comment] 2021-12-24 02:46
not stale

**Comment by adrianduffell** [comment] 2022-03-02 07:43
I'm still able to reproduce this. I'm going to give it a high priority due to the price discrepancy.

**Comment by adrianduffell** [comment] 2023-09-07 09:45
Closing this out as product types are no longer displayed in the new setup wizard.

**Closed as completed by adrianduffell** 2023-09-07 09:45 UTC
Labels: Bug, Enhancement, needs: design, plugin: woocommerce, Onboarding
