### ISSUE TITLE
Failed perform Post and Put operation using C#

### ISSUE THREAD

**Issue by shahshyam** [woothemes/woocommerce#8955] opened 2015-08-26 02:49 UTC
Dear client 
I am consuming your Woocommerce REST API in C# using RESTSharp. It does not accept API key and secret token in C#.

    var client = new RestClient("https://fishbowlstaging.com/woocommerce/");
            client.Authenticator = new HttpBasicAuthenticator("ck_b4fea53dfd8cbd2c02d78bdab282bccda3004cfc",
                                                          "cs_5959a198c52012aa61ff5e1c991433c0067b0573");
            var requestv1 = new RestRequest("wc-api/v3/products", Method.GET);
            requestv1.RequestFormat = DataFormat.Json;           
            var queryResultv1 = client.Execute(requestv1);

Error

{"errors":[{"code":"woocommerce_api_authentication_error","message":"Consumer Secret is invalid"}]}

**Comment by claudiosmweb** [comment] 2015-08-26 04:16
The problem is not the language, but how authentication is done.
Are you sure that this is passing the headers for basic authentication?
Have you tested this with other API?

The error message is right, especially if you are not sending the correct headers.

I don't see here any issue with our API, so I'm closing it.

**Closed by claudiosmweb** 2015-08-26 04:16 UTC

**Comment by shahshyam** [comment] 2015-08-26 04:23
yes 

 var client = new RestClient("https://fishbowlstaging.com/woocommerce/");
             client.Authenticator = new HttpBasicAuthenticator("ck_b4fea53dfd8cbd2c02d78bdab282bccda3004cfc",
                                                         "cs_5959a198c52012aa61ff5e1c991433c0067b0573");            
            var request = new RestRequest("wc-api/v3/products", Method.GET);
            request.RequestFormat = DataFormat.Json;
            request.AddParameter("Accept", "application/json", ParameterType.HttpHeader);
            request.RequestFormat = DataFormat.Json;           
            var queryResultv1 = client.Execute(request);

**Comment by shahshyam** [comment] 2015-08-26 04:23
There are many people comment about Woocommerce API,  it is not working

**Comment by claudiosmweb** [comment] 2015-08-26 04:33
@shahshyam Because they are not aware using or reading the docs, it's quite simple.
In two days I did wrappers for WooCommerce API in 4 different programmming languages. 
All about understanding the forms of authentication... In addition twe corrected various standards in WooCommerce 2.4 and now everything is following the standards. So it's no excuse not to know do authentication.

You can test it before in your browser too!

Try: https://fishbowlstaging.com/woocommerce/wc-api/v3/products

I do not know if you changed these your keys, but they're wrong.

**Comment by claudiosmweb** [comment] 2015-08-26 04:34
Another thing, need to see if your server is updated. 
If PHP is able to set the `PHP_AUTH_USER` and `PHP_AUTH_PW`.

**Comment by shahshyam** [comment] 2015-08-26 04:35
i am testing first via rest api tool. then back to you

**Comment by shahshyam** [comment] 2015-08-26 04:54
i am using post man it also give same error

**Comment by claudiosmweb** [comment] 2015-08-26 04:56
https://github.com/woothemes/woocommerce/issues/8955#issuecomment-134825721

**Comment by shahshyam** [comment] 2015-08-26 05:27
It is working for Get operation when i changed http and use api version 2. It is not working for post operation with same code.

**Comment by claudiosmweb** [comment] 2015-08-26 05:40
@shahshyam because version 2 does not work strictly with standards such as version 3 works.

As I said to you:

> Another thing, need to see if your server is updated.
> If PHP is able to set the PHP_AUTH_USER and PHP_AUTH_PW.

Now on POST you have other factors... Like, the server is receiving external POST? There's something blocking it?

The server where everything has been installed must be working well and updated so that everything works as expected.

**Comment by shahshyam** [comment] 2015-09-06 02:37
I have done thanks for your help

**Comment by appmarcosilva** [comment] 2015-10-06 00:51
Hello, i have the same problem.
shahshyam, can you help me how can do it?
