### ISSUE TITLE
jquery error on checkout page verision 2.50

### ISSUE THREAD

**Issue by serveds** [woothemes/woocommerce#10144] opened 2016-01-22 18:50 UTC
Hi,

On checkout page the page is not refreshing when order complete

All plugins deactivated but woocommerce

Error is coming up on:

Checkout.min.js?ver=2.50

Uncaught TypeError: Cannot read property 'reload' of null

jQuery(function(a){if("undefined"==typeof wc_checkout_params)return!1;a.blockUI.defaults.overlayCSS.cursor="default";var b={updateTimer:!1,dirtyInput:!1,xhr:!1,$order_review:a("#order_review"),$checkout_form:a("form.checkout"),init:function(){a(document.body).bind("update_checkout",this.update_checkout),a(document.body).bind("init_checkout",this.init_checkout),this.$order_review.on("click","input[name=payment_method]",this.payment_method_selected),this.$checkout_form.on("submit",this.submit),this.$checkout_form.on("blur change",".input-text, select",this.validate_field),this.$checkout_form.on("change","select.shipping_method, input[name^=shipping_method], #ship-to-different-address input, .update_totals_on_change select, .update_totals_on_change input[type=radio]",this.trigger_update_checkout),this.$checkout_form.on("change",".address-field select",this.input_changed),this.$checkout_form.on("change",".address-field input.input-text, .update_totals_on_change input.input-text",this.maybe_input_changed),this.$checkout_form.on("keydown",".address-field input.input-text, .update_totals_on_change input.input-text",this.queue_update_checkout),this.$checkout_form.on("change","#ship-to-different-address input",this.ship_to_different_address),this.$order_review.find("input[name=payment_method]:checked").trigger("click"),this.$checkout_form.find("#ship-to-different-address input").change(),"1"===wc_checkout_params.is_checkout&&a(document.body).trigger("init_checkout"),"yes"===wc_checkout_params.option_guest_checkout&&a("input#createaccount").change(this.toggle_create_account).change()},toggle_create_account:function(){a("div.create-account").hide(),a(this).is(":checked")&&a("div.create-account").slideDown()},init_checkout:function(){a("#billing_country, #shipping_country, .country_to_state").change(),a(document.body).trigger("update_checkout")},maybe_input_changed:function(a){b.dirtyInput&&b.input_changed(a)},input_changed:function(a){b.dirtyInput=a.target,b.maybe_update_checkout()},queue_update_checkout:function(a){var c=a.keyCode||a.which||0;return 9===c?!0:(b.dirtyInput=this,b.reset_update_checkout_timer(),void(b.updateTimer=setTimeout(b.maybe_update_checkout,"1000")))},trigger_update_checkout:function(){b.reset_update_checkout_timer(),b.dirtyInput=!1,a(document.body).trigger("update_checkout")},maybe_update_checkout:function(){var c=!0;if(a(b.dirtyInput).size()){var d=a(b.dirtyInput).closest("div").find(".address-field.validate-required");d.size()&&d.each(function(){""===a(this).find("input.input-text").val()&&(c=!1)})}c&&b.trigger_update_checkout()},ship_to_different_address:function(){a("div.shipping_address").hide(),a(this).is(":checked")&&a("div.shipping_address").slideDown()},payment_method_selected:function(){if(a(".payment_methods input.input-radio").length>1){var b=a("div.payment_box."+a(this).attr("ID"));a(this).is(":checked")&&!b.is(":visible")&&(a("div.payment_box").filter(":visible").slideUp(250),a(this).is(":checked")&&a("div.payment_box."+a(this).attr("ID")).slideDown(250))}else a("div.payment_box").show();a(this).data("order_button_text")?a("#place_order").val(a(this).data("order_button_text")):a("#place_order").val(a("#place_order").data("value"))},reset_update_checkout_timer:function(){clearTimeout(b.updateTimer)},validate_field:function(){var b=a(this),c=b.closest(".form-row"),d=!0;if(c.is(".validate-required")&&""===b.val()&&(c.removeClass("woocommerce-validated").addClass("woocommerce-invalid woocommerce-invalid-required-field"),d=!1),c.is(".validate-email")&&b.val()){var e=new RegExp(/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i);e.test(b.val())||(c.removeClass("woocommerce-validated").addClass("woocommerce-invalid woocommerce-invalid-email"),d=!1)}d&&c.removeClass("woocommerce-invalid woocommerce-invalid-required-field").addClass("woocommerce-validated")},update_checkout:function(){b.reset_update_checkout_timer(),b.updateTimer=setTimeout(b.update_checkout_action,"5")},update_checkout_action:function(){if(b.xhr&&b.xhr.abort(),0!==a("form.checkout").size()){var c=[];a("select.shipping_method, input[name^=shipping_method][type=radio]:checked, input[name^=shipping_method][type=hidden]").each(function(){c[a(this).data("index")]=a(this).val()});var d,e,f,g,h,i,j=a("#order_review").find("input[name=payment_method]:checked").val(),k=a("#billing_country").val(),l=a("#billing_state").val(),m=a("input#billing_postcode").val(),n=a("#billing_city").val(),o=a("input#billing_address_1").val(),p=a("input#billing_address_2").val();a("#ship-to-different-address").find("input").is(":checked")?(d=a("#shipping_country").val(),e=a("#shipping_state").val(),f=a("input#shipping_postcode").val(),g=a("#shipping_city").val(),h=a("input#shipping_address_1").val(),i=a("input#shipping_address_2").val()):(d=k,e=l,f=m,g=n,h=o,i=p),a(".woocommerce-checkout-payment, .woocommerce-checkout-review-order-table").block({message:null,overlayCSS:{background:"#fff",opacity:.6}});var q={security:wc_checkout_params.update_order_review_nonce,shipping_method:c,payment_method:j,country:k,state:l,postcode:m,city:n,address:o,address_2:p,s_country:d,s_state:e,s_postcode:f,s_city:g,s_address:h,s_address_2:i,post_data:a("form.checkout").serialize()};b.xhr=a.ajax({type:"POST",url:wc_checkout_params.wc_ajax_url.toString().replace("%%endpoint%%","update_order_review"),data:q,success:function(b){if(b&&b.fragments&&a.each(b.fragments,function(b,c){a(b).replaceWith(c),a(b).unblock()}),"failure"===b.result){var c=a("form.checkout");if("true"===b.reload)return void window.location.reload();a(".woocommerce-error, .woocommerce-message").remove(),b.messages?c.prepend(b.messages):c.prepend(b),c.find(".input-text, select").blur(),a("html, body").animate({scrollTop:a("form.checkout").offset().top-100},1e3)}0===a(".woocommerce-checkout").find("input[name=payment_method]:checked").size()&&a(".woocommerce-checkout").find("input[name=payment_method]:eq(0)").attr("checked","checked"),a(".woocommerce-checkout").find("input[name=payment_method]:checked").eq(0).trigger("click"),a(document.body).trigger("updated_checkout")}})}},submit:function(){b.reset_update_checkout_timer();var c=a(this);if(c.is(".processing"))return!1;if(c.triggerHandler("checkout_place_order")!==!1&&c.triggerHandler("checkout_place_order_"+a("#order_review").find("input[name=payment_method]:checked").val())!==!1){c.addClass("processing");var d=c.data();1!==d["blockUI.isBlocked"]&&c.block({message:null,overlayCSS:{background:"#fff",opacity:.6}}),a.ajax({type:"POST",url:wc_checkout_params.checkout_url,data:c.serialize(),dataType:"json",success:function(c){try{if("success"!==c.result)throw"failure"===c.result?"Result failure":"Invalid response";-1===c.redirect.indexOf("https://")||-1===c.redirect.indexOf("http://")?window.location=c.redirect:window.location=decodeURI(c.redirect)}catch(d){if("true"===c.reload)return void window.location.reload();"true"===c.refresh&&a(document.body).trigger("update_checkout"),c.messages?b.submit_error(c.messages):b.submit_error('<div class="woocommerce-error">'+wc_checkout_params.i18n_checkout_error+"</div>")}},error:function(a,c,d){b.submit_error('<div class="woocommerce-error">'+d+"</div>")}})}return!1},submit_error:function(c){a(".woocommerce-error, .woocommerce-message").remove(),b.$checkout_form.prepend(c),b.$checkout_form.removeClass("processing").unblock(),b.$checkout_form.find(".input-text, select").blur(),a("html, body").animate({scrollTop:a("form.checkout").offset().top-100},1e3),a(document.body).trigger("checkout_error")}},c={init:function(){a(document.body).on("click","a.showcoupon",this.show_coupon_form),a(document.body).on("click",".woocommerce-remove-coupon",this.remove_coupon),a("form.checkout_coupon").hide().submit(this.submit)},show_coupon_form:function(){return a(".checkout_coupon").slideToggle(400,function(){a(".checkout_coupon").find(":input:eq(0)").focus()}),!1},submit:function(){var b=a(this);if(b.is(".processing"))return!1;b.addClass("processing").block({message:null,overlayCSS:{background:"#fff",opacity:.6}});var c={security:wc_checkout_params.apply_coupon_nonce,coupon_code:b.find("input[name=coupon_code]").val()};return a.ajax({type:"POST",url:wc_checkout_params.wc_ajax_url.toString().replace("%%endpoint%%","apply_coupon"),data:c,success:function(c){a(".woocommerce-error, .woocommerce-message").remove(),b.removeClass("processing").unblock(),c&&(b.before(c),b.slideUp(),a(document.body).trigger("update_checkout"))},dataType:"html"}),!1},remove_coupon:function(b){b.preventDefault();var c=a(this).parents(".woocommerce-checkout-review-order"),d=a(this).data("coupon");c.addClass("processing").block({message:null,overlayCSS:{background:"#fff",opacity:.6}});var e={security:wc_checkout_params.remove_coupon_nonce,coupon:d};a.ajax({type:"POST",url:wc_checkout_params.wc_ajax_url.toString().replace("%%endpoint%%","remove_coupon"),data:e,success:function(b){a(".woocommerce-error, .woocommerce-message").remove(),c.removeClass("processing").unblock(),b&&(a("form.woocommerce-checkout").before(b),a(document.body).trigger("update_checkout"),a("form.checkout_coupon").find('input[name="coupon_code"]').val(""))},error:function(a){wc_checkout_params.debug_mode&&console.log(a.responseText)},dataType:"html"})}},d={init:function(){a(document.body).on("click","a.showlogin",this.show_login_form)},show_login_form:function(){return a("form.login").slideToggle(),!1}};b.init(),c.init(),d.init()});

Justin

**Comment by mikejolley** [comment] 2016-01-22 18:55
See what you're getting back on the network tab http://mikejolley.com/2015/11/12/debugging-unexpected-token-in-woocommerce-2-4/

**Comment by serveds** [comment] 2016-01-22 19:01
nothing under checkout

update_order_review

{"result":"success","messages":"","reload":"false","fragments":{".woocommerce-checkout-review-order-table":"<table class=\"shop_table woocommerce-checkout-review-order-table\">\n\t<thead>\n\t\t<tr>\n\t\t\t<th class=\"product-name\">Product<\/th>\n\t\t\t<th class=\"product-total\">Total<\/th>\n\t\t<\/tr>\n\t<\/thead>\n\t<tbody>\n\t\t\t\t\t\t\t<tr class=\"cart_item\">\n\t\t\t\t\t\t<td class=\"product-name\">\n\t\t\t\t\t\t\tStructural Bolts 1\/2\" A325 Galvanized&nbsp;\t\t\t\t\t\t\t <strong class=\"product-quantity\">&times; 50<\/strong>\t\t\t\t\t\t\t<dl class=\"variation\">\n\t\t\t<dt class=\"variation-Length\">Length:<\/dt>\n\t\t<dd class=\"variation-Length\"><p>2\"<\/p>\n<\/dd>\n\t<\/dl>\n\t\t\t\t\t\t<\/td>\n\t\t\t\t\t\t<td class=\"product-total\">\n\t\t\t\t\t\t\t<span class=\"amount\">&#36;472.40<\/span>\t\t\t\t\t\t<\/td>\n\t\t\t\t\t<\/tr>\n\t\t\t\t\t\t<\/tbody>\n\t<tfoot>\n\n\t\t<tr class=\"cart-subtotal\">\n\t\t\t<th>Subtotal<\/th>\n\t\t\t<td><span class=\"amount\">&#36;472.40<\/span><\/td>\n\t\t<\/tr>\n\n\t\t\n\t\t\n\t\t\t\n\t\t\t<tr class=\"shipping\">\n\t<th>Shipping<\/th>\n\t<td data-title=\"Shipping\">\n\t\t\t\t\tFlat Rate: <span class=\"amount\">&#36;10.00<\/span> <input type=\"hidden\" name=\"shipping_method[0]\" data-index=\"0\" id=\"shipping_method_0\" value=\"flat_rate\" class=\"shipping_method\" \/>\t\t\n\t\t\n\t\t\t<\/td>\n<\/tr>\n\n\t\t\t\n\t\t\n\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr class=\"tax-rate tax-rate-ca-bc-gst-5-1\">\n\t\t\t\t\t\t<th>GST 5%<\/th>\n\t\t\t\t\t\t<td><span class=\"amount\">&#036;24.12<\/span><\/td>\n\t\t\t\t\t<\/tr>\n\t\t\t\t\t\t\t\t\t<tr class=\"tax-rate tax-rate-ca-bc-pst-7-2\">\n\t\t\t\t\t\t<th>PST 7%<\/th>\n\t\t\t\t\t\t<td><span class=\"amount\">&#036;33.07<\/span><\/td>\n\t\t\t\t\t<\/tr>\n\t\t\t\t\t\t\t\t\t\n\t\t\n\t\t<tr class=\"order-total\">\n\t\t\t<th>Order Total CAD<\/th>\n\t\t\t<td><strong><span class=\"amount\">&#36;539.59<\/span><\/strong> <\/td>\n\t\t<\/tr>\n\n\t\t\n\t<\/tfoot>\n\n<\/table>\n",".woocommerce-checkout-payment":"<div id=\"payment\" class=\"woocommerce-checkout-payment\">\n\t\t\t<ul class=\"wc_payment_methods payment_methods methods\">\n\t\t\t<li class=\"wc_payment_method payment_method_cheque\">\n\t<input id=\"payment_method_cheque\" type=\"radio\" class=\"input-radio\" name=\"payment_method\" value=\"cheque\"  checked='checked' data-order_button_text=\"\" \/>\n\n\t<label for=\"payment_method_cheque\">\n\t\tCheque Payment \t<\/label>\n\t\t\t<div class=\"payment_box payment_method_cheque\" >\n\t\t\t<p>Please send your cheque to Store Name, Store Street, Store Town, Store State \/ County, Store Postcode.<\/p>\n\t\t<\/div>\n\t<\/li>\n\t\t<\/ul>\n\t\t<div class=\"form-row place-order\">\n\t\t<noscript>\n\t\t\tSince your browser does not support JavaScript, or it is disabled, please ensure you click the <em>Update Totals<\/em> button before placing your order. You may be charged more than the amount stated above if you fail to do so.\t\t\t<br\/><input type=\"submit\" class=\"button alt\" name=\"woocommerce_checkout_update_totals\" value=\"Update totals\" \/>\n\t\t<\/noscript>\n\n\t\t    <p class=\"form-row terms wc-terms-and-conditions\">\n\t\t<input type=\"checkbox\" class=\"input-checkbox\" name=\"terms\"  id=\"terms\" \/>\n        <label for=\"terms\" class=\"checkbox\">I&rsquo;ve read and accept the <a href=\"http:\/\/s9124.p261.sites.pressdns.com\/terms-and-conditions\/\" target=\"_blank\">terms &amp; conditions<\/a> <span class=\"required\">*<\/span><\/label>\n        <input type=\"hidden\" name=\"terms-field\" value=\"1\" \/>\n    <\/p>\n\n\t\t\n\t\t<input type=\"submit\" class=\"button alt\" name=\"woocommerce_checkout_place_order\" id=\"place_order\" value=\"Place order\" data-value=\"Place order\" \/>\n\t\t\n\t\t<input type=\"hidden\" id=\"_wpnonce\" name=\"_wpnonce\" value=\"8488bc1899\" \/><input type=\"hidden\" name=\"_wp_http_referer\" value=\"\/checkout\/?wc-ajax=update_order_review\" \/>\t<\/div>\n<\/div>\n"}}


Get_refrshed_fragments


{"fragments":{"div.widget_shopping_cart_content":"<div class=\"widget_shopping_cart_content\">\n\n<ul class=\"cart_list product_list_widget \">\n\n\t\n\t\t\t\t\t\t\t<li class=\"mini_cart_item\">\n\t\t\t\t\t\t<a href=\"http:\/\/s9124.p261.sites.pressdns.com\/cart\/?remove_item=5eb8c13b07b0562505f7c9b0f7435b10&#038;_wpnonce=1eed36967b\" class=\"remove\" title=\"Remove this item\" data-product_id=\"46998\" data-product_sku=\"SBG008032A325\">&times;<\/a>\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"https:\/\/s9124.p261.sites.pressdns.com\/shop\/structural-bolts-12-a325-galvanized\/?attribute_length=2%22\">\n\t\t\t\t\t\t\t\t<img width=\"200\" height=\"200\" src=\"\/\/s9124.p261.sites.pressdns.com\/wp-content\/uploads\/2015\/03\/Structural-Bolts-A325-Galvanized-200x200.jpg\" class=\"attachment-shop_thumbnail size-shop_thumbnail wp-post-image\" alt=\"Structural Bolts A325 Galvanized\" srcset=\"\/\/s9124.p261.sites.pressdns.com\/wp-content\/uploads\/2015\/03\/Structural-Bolts-A325-Galvanized-150x150.jpg 150w, \/\/s9124.p261.sites.pressdns.com\/wp-content\/uploads\/2015\/03\/Structural-Bolts-A325-Galvanized-300x300.jpg 300w, \/\/s9124.p261.sites.pressdns.com\/wp-content\/uploads\/2015\/03\/Structural-Bolts-A325-Galvanized-200x200.jpg 200w, \/\/s9124.p261.sites.pressdns.com\/wp-content\/uploads\/2015\/03\/Structural-Bolts-A325-Galvanized-400x400.jpg 400w, \/\/s9124.p261.sites.pressdns.com\/wp-content\/uploads\/2015\/03\/Structural-Bolts-A325-Galvanized-500x500.jpg 500w, \/\/s9124.p261.sites.pressdns.com\/wp-content\/uploads\/2015\/03\/Structural-Bolts-A325-Galvanized.jpg 648w\" sizes=\"(max-width: 200px) 100vw, 200px\" \/>Structural Bolts 1\/2\" A325 Galvanized&nbsp;\t\t\t\t\t\t\t<\/a>\n\t\t\t\t\t\t\t\t\t\t\t\t<dl class=\"variation\">\n\t\t\t<dt class=\"variation-Length\">Length:<\/dt>\n\t\t<dd class=\"variation-Length\"><p>2\"<\/p>\n<\/dd>\n\t<\/dl>\n\n\t\t\t\t\t\t<span class=\"quantity\">50 &times; <span class=\"amount\">&#36;9.45<\/span><\/span>\t\t\t\t\t<\/li>\n\t\t\t\t\t\n\t\n<\/ul>\n\n\n\t<p class=\"total\"><strong>Subtotal:<\/strong> <span class=\"amount\">&#36;472.40<\/span><\/p>\n\n\t\n\t<p class=\"buttons\">\n\t\t<a href=\"http:\/\/s9124.p261.sites.pressdns.com\/cart\/\" class=\"button wc-forward\">View Cart<\/a>\n\t\t<a href=\"https:\/\/s9124.p261.sites.pressdns.com\/checkout\/\" class=\"button checkout wc-forward\">Checkout<\/a>\n\t<\/p>\n\n\n<\/div>","a.cart-contents":"\t<a class=\"cart-contents\" href=\"http:\/\/s9124.p261.sites.pressdns.com\/cart\/\" title=\"View your shopping cart\">\n\t\t\t\t<span class=\"count\">50 items<\/span> - &#036;472.40\t\t\t<\/a>\n"},"cart_hash":"4f9ba44784b95e5f938e8824640d9786"}

**Comment by serveds** [comment] 2016-01-22 19:02
Get_refrshed_fragments


{"fragments":{"div.widget_shopping_cart_content":"<div class=\"widget_shopping_cart_content\">\n\n<ul class=\"cart_list product_list_widget \">\n\n\t\n\t\t\t\t\t\t\t<li class=\"mini_cart_item\">\n\t\t\t\t\t\t<a href=\"http:\/\/s9124.p261.sites.pressdns.com\/cart\/?remove_item=5eb8c13b07b0562505f7c9b0f7435b10&#038;_wpnonce=1eed36967b\" class=\"remove\" title=\"Remove this item\" data-product_id=\"46998\" data-product_sku=\"SBG008032A325\">&times;<\/a>\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"https:\/\/s9124.p261.sites.pressdns.com\/shop\/structural-bolts-12-a325-galvanized\/?attribute_length=2%22\">\n\t\t\t\t\t\t\t\t<img width=\"200\" height=\"200\" src=\"\/\/s9124.p261.sites.pressdns.com\/wp-content\/uploads\/2015\/03\/Structural-Bolts-A325-Galvanized-200x200.jpg\" class=\"attachment-shop_thumbnail size-shop_thumbnail wp-post-image\" alt=\"Structural Bolts A325 Galvanized\" srcset=\"\/\/s9124.p261.sites.pressdns.com\/wp-content\/uploads\/2015\/03\/Structural-Bolts-A325-Galvanized-150x150.jpg 150w, \/\/s9124.p261.sites.pressdns.com\/wp-content\/uploads\/2015\/03\/Structural-Bolts-A325-Galvanized-300x300.jpg 300w, \/\/s9124.p261.sites.pressdns.com\/wp-content\/uploads\/2015\/03\/Structural-Bolts-A325-Galvanized-200x200.jpg 200w, \/\/s9124.p261.sites.pressdns.com\/wp-content\/uploads\/2015\/03\/Structural-Bolts-A325-Galvanized-400x400.jpg 400w, \/\/s9124.p261.sites.pressdns.com\/wp-content\/uploads\/2015\/03\/Structural-Bolts-A325-Galvanized-500x500.jpg 500w, \/\/s9124.p261.sites.pressdns.com\/wp-content\/uploads\/2015\/03\/Structural-Bolts-A325-Galvanized.jpg 648w\" sizes=\"(max-width: 200px) 100vw, 200px\" \/>Structural Bolts 1\/2\" A325 Galvanized&nbsp;\t\t\t\t\t\t\t<\/a>\n\t\t\t\t\t\t\t\t\t\t\t\t<dl class=\"variation\">\n\t\t\t<dt class=\"variation-Length\">Length:<\/dt>\n\t\t<dd class=\"variation-Length\"><p>2\"<\/p>\n<\/dd>\n\t<\/dl>\n\n\t\t\t\t\t\t<span class=\"quantity\">50 &times; <span class=\"amount\">&#36;9.45<\/span><\/span>\t\t\t\t\t<\/li>\n\t\t\t\t\t\n\t\n<\/ul>\n\n\n\t<p class=\"total\"><strong>Subtotal:<\/strong> <span class=\"amount\">&#36;472.40<\/span><\/p>\n\n\t\n\t<p class=\"buttons\">\n\t\t<a href=\"http:\/\/s9124.p261.sites.pressdns.com\/cart\/\" class=\"button wc-forward\">View Cart<\/a>\n\t\t<a href=\"https:\/\/s9124.p261.sites.pressdns.com\/checkout\/\" class=\"button checkout wc-forward\">Checkout<\/a>\n\t<\/p>\n\n\n<\/div>","a.cart-contents":"\t<a class=\"cart-contents\" href=\"http:\/\/s9124.p261.sites.pressdns.com\/cart\/\" title=\"View your shopping cart\">\n\t\t\t\t<span class=\"count\">50 items<\/span> - &#036;472.40\t\t\t<\/a>\n"},"cart_hash":"4f9ba44784b95e5f938e8824640d9786"}

**Comment by mikejolley** [comment] 2016-01-22 19:04
> On checkout page the page is not refreshing when order complete

Can you explain what exactly is happening a bit more clearer?

**Comment by serveds** [comment] 2016-01-22 19:14
You know when you hit the place order button and the form locks as it is waiting for a response back from your processor.  then when it succeeds in moves to the order confirmation screen.  Well it is not going to that screen and is stock in the lock mode.  The order does process though

Hope that was clear

**Comment by mikejolley** [comment] 2016-01-22 19:57
There should be a XHR request in your network tab. Look for it again please. Keep console open when you hit place order.

**Comment by serveds** [comment] 2016-01-22 20:11
?wc-ajax=checkout

under XHR - repsonse 
no response


![checkout screen shot](https://cloud.githubusercontent.com/assets/3769929/12521732/3ab1e6a6-c101-11e5-84dc-3a0da9636e74.jpg)
 data

**Comment by mikejolley** [comment] 2016-01-22 20:21
That would be your issue. Check server error logs/rule out plugins/rule out theme.

**Comment by serveds** [comment] 2016-01-22 20:49
2016 theme and no plugins running but woocommerce.  I will check the logs closer.  

Could this be a problem at the host level?

**Comment by mikejolley** [comment] 2016-01-22 23:29
Unsure. Since there was no response, what was on headers tab?

**Comment by serveds** [comment] 2016-01-23 00:06
both the ajax=checkout and update_order_review have status code 200 ok

**Comment by mikejolley** [comment] 2016-01-23 00:17
Can I take a look?

**Comment by serveds** [comment] 2016-01-23 00:19
http://s9124.p261.sites.pressdns.com/

Fly at it.  All plugins off and 2016 theme enabled

**Comment by mikejolley** [comment] 2016-01-23 12:00
So even failed requests return content but your checkout one does not.

There has to be something in your error logs, or something custom here - it looks like it's just exiting rather than returning any content. That means our ajax handlers are not being called.

**Comment by serveds** [comment] 2016-01-23 21:08
I am going to start over again fresh copy of our live site and try again just in case something something was adjusted.  There was an issue with the paypal express plugin last week that required a woothemes support and I believe they plugin developers where also included to fix the issue.  So now I am wondering if during their investigating that something was done.

**Comment by mikejolley** [comment] 2016-01-25 10:31
Possibly. I'm closing for now as its non-reproducable our side. You can still comment here.

**Closed by mikejolley** 2016-01-25 10:31 UTC

**Comment by sivasri0406** [comment] 2017-01-24 13:07
Hi,
 i have created payment gateway in woocommerce, my result display only console,but my checkout page error this "Error processing checkout. Please try again."

below my console result:
<br>ResponseType=2<br>LPS_transaction_id=65239737<br>Merchant_ref_number=258<br>Lpsid=test<br>Lpspwd=test<br>VBV_URL=https://testcustomer34.cardinalcommerce.com/V3DSStart?osb=visa-3<br>amp;VAA=B<br>PAReq=eNpVUstuwjAQvPsrUNVz7MSBULRYCqWoqEqLIKUVt8hZIAUCcRIe+fra4dXedmbX49mxIVwqxP4EZalQQIB5Hi2wkcTdh4xxxTIeTN5OHob53F+8sAcBI3+MmYA9qjzZpsK2mOUAvUKiJZRcRmkhIJJZb/guXNflnAO9QAIbVMO+sB3uNlte+wnomSCQRhsUIeZF4yoCtOYIyG2ZFuok2i4DegUESrUWy6LYdSg9HA7WLjrtE+PDktsNUNMlQO+ORqWpcr3oMYmFDP1K/vSOAbPDCV/x2XRczVaDdBz6XaBmgkAcFSgcZnvMdtyG7XSaXsdtAa15AtHGWBGPjsW0rwsisDP3+GfkmM5fQi9TKoWpPAnGtdQNEcDjbpuiOQT0VusN7r6fX02ustB57YtB1ZbVahJ+fM+DduZmmE+/1oEXf5qw65laMtFRaRd2rZnUuVGjQy9PSS+vrqt/v+EXoHGwlQ==<br>{"result":"failure","messages":"","refresh":"false","reload":"false"}

How do i solve this please help me.
thanks
siva
