### ISSUE TITLE
Coupons not correctly checking user account and billing emails anymore

### ISSUE THREAD

**Issue by JeremiahTolbert** [woothemes/woocommerce#48746] opened 2024-06-24 05:27 UTC
https://github.com/woocommerce/woocommerce/blob/3b00882aed0056df5c18d3eefbf0d85f98d55d2b/plugins/woocommerce/includes/class-wc-discounts.php#L973C3-L973C75

I am new to reporting bugs, so I apologize if this format is incorrect.  In the referenced line above, it attempts to construct an array calling methods on the default $user which don't exist, causing an empty array to be constructed, which results in the coupon validation not actually running against the user email like it did previously. 

I believe the addition of this line:
`$user = new WC_Customer( $user->id ) `
after the initial declaration of $user will correctly build the array, and fix email validation to the way it was working prior to 3 months ago.

**Comment by tammullen** [comment] 2024-06-24 18:00
I believe this might be a duplicate of https://github.com/woocommerce/woocommerce/issues/48459 can you confirm the that existing issue is what you are reporting?

**Comment by JeremiahTolbert** [comment] 2024-06-24 18:32
Yes, I believe so. Sorry!

**Comment by tammullen** [comment] 2024-06-26 10:45
Thanks for confirming.

**Closed as completed by tammullen** 2024-06-26 10:45 UTC
Labels: needs: triage feedback, type: community contribution
