### ISSUE TITLE
DB error after adding the On Sale Products block in a page

### ISSUE THREAD

**Issue by Chrystll** [woothemes/woocommerce#31402] opened 2021-12-09 09:34 UTC
**Plugins activated & WordPress version**
WooCommerce  6.0.0-rc.1
WooCommerce Beta Tester 2.0.4
WordPress 5.8.2

**Issue description**
I get a database error when adding the On Sale Products block in a page.

`[WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND meta_key LIKE 'attribute\\_%'' at line 1 for query SELECT post_id as variation_id, meta_key as attribute_key, meta_value as attribute_value FROM wp_postmeta WHERE post_id IN () AND meta_key LIKE 'attribute\\_%' made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_REST_Server->respond_to_request, WP_REST_Block_Renderer_Controller->get_item, render_block, WP_Block->render, Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback, Automattic\WooCommerce\Blocks\BlockTypes\AbstractProductGrid->render, Automattic\WooCommerce\Blocks\BlockTypes\AbstractProductGrid->get_products, Automattic\WooCommerce\Blocks\BlockTypes\AbstractProductGrid->prime_product_variations`

**Steps to reproduce**
Go to Pages > Add New > then add the "On sale Products" block. This action triggers the database error mentioned above.

**Comment by rodelgc** [comment] 2021-12-09 13:05
Hi @Chrystll,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

I my first test:
1. I started with WooCommerce 5.9.0
2. I imported some on-sale products using the `sample_products.csv` file.
3. I upgraded WooCommerce to 6.0.0-rc.1 using the WC Beta Tester
4. I updated the WooCommerce database when I was prompted to. I waited for it to finish
5. I went to Pages > Add New > added the "On sale Products" block. I did not encounter any DB errors. 

Here's the screen video of my test:

https://user-images.githubusercontent.com/4509348/145401352-59266d39-9502-43f7-9db9-8122f78b1c40.mov

In my second test, I started with a fresh install of WC 6.0.0-rc.1 and repeated the same steps I enumerated above. Still, I did not encounter the DB error.

Were you able to complete the DB update when you upgraded to 6.0.0 RC1?
Also, could you please provide us the system status report to see if you've got other plugins enabled that causes this behavior? Feel free to redact any sensitive information that they may contain.

Please provide us with more details about the issue which may help us to evaluate it further.

**Comment by rodelgc** [comment] 2021-12-09 13:09
Here's the setup that I used in my test by the way:

WordPress 5.8.2
WooCommerce 5.9.0 in my first test, 6.0.0 RC1 on my 2nd test
Theme: Twenty Twenty-Two
PHP 7.4.1
MySQL 5.7.28
Server: Apache/2.4.43

**Comment by Chrystll** [comment] 2021-12-09 13:54
Hello @rodelgc,
I tested on a fresh install. Here are the steps that I run:
_Without updating the WooCommerce database_
1. on a fresh install I activate only WooCommerce 5.9.0 and WooCommerce Beta Tester 2.0.4
2. I swicth on the 6.0.0-rc.1
3. I create 2 simple products as here:
![screenshot-mysite com-2021 12 09-14_42_04](https://user-images.githubusercontent.com/19824724/145407210-5c3af207-a41e-475f-a31e-3a8e43dd933d.png)
4. I go to Pages > Add New > then add the "On sale Products" block. This action triggers the DB error.
![screenshot-mysite com-2021 12 09-14_52_44](https://user-images.githubusercontent.com/19824724/145408978-ea44e1d4-65fa-4a2a-9b0b-1a017ababbc3.png)


_Second test with on the same installation but with the WooCommerce database updated_
1. I delete the page containing the On Sale Products block. 
2. I update the WooCommerce database. I confirm that I waited for it to finish
3. I add a new page > then add the "On sale Products" block. I still get the DB error.

Here is the system status report 
[system status report.zip](https://github.com/woocommerce/woocommerce/files/7685568/system.status.report.zip)

**Comment by rodelgc** [comment] 2021-12-14 07:50
Hi @Chrystll,

Thank you very much for your feedback. I see from your system status report and screenshot that you used Twenty Twenty-Two as the theme. And I also noticed that I erroneously mentioned "Twenty Twenty-Two" as the theme I used in my [earlier comment](#issuecomment-989837794). While in fact, I meant to say "Twenty Twenty-One" as my screen recording shows. Apologies for the confusion!

We are still in the process of making WooCommerce compatible with the new TT2 theme. I'll close this issue for now since TT2 support is still being worked on.

**Closed as completed by rodelgc** 2021-12-14 07:50 UTC
Labels: type: support request

**Comment by vralle** [comment] 2021-12-17 19:50
Same error after upgrading to WooCommerce 6.0
Config:
WordPress 5.9Beta2
WooCommerce 6.0
WooCommerce Blocks: 6.3.3
PHP 7.4.14
MySQL 5.7.29
Windows 11

Quick debugging `AbstractProductGrid->prime_product_variations()`:
```php
// phpcs:disable WordPress.DB.PreparedSQL.NotPrepared
$product_variations      = $wpdb->get_results( "SELECT ID as variation_id, post_parent as product_id from {$wpdb->posts} WHERE post_parent IN ( " . implode( ',', $prime_product_ids ) . ' )', ARRAY_A );
$prime_variation_ids     = array_column( $product_variations, 'variation_id' );
$variation_ids_by_parent = array_column( $product_variations, 'product_id', 'variation_id' );

do_action( 'qm/debug', $product_variations );
```
Result:
```php
$product_variations = array()
```
```SQL
SELECT post_id as variation_id, meta_key as attribute_key, meta_value as attribute_value FROM wp_postmeta WHERE post_id IN () AND meta_key LIKE 'attribute\\_{e8c1ae45e29c0e2cafb318f302e015d2eadc9fa15117758f9e6af346bc2849b2}'
```

**Comment by vg-robin** [comment] 2021-12-18 15:27
I'm getting this too, using a Best-Sellers grid. In prime_product_variations($product_ids) none of the products are variable, so $product_variations is assigned an empty array. It should be checked there, but isn't, and that inevitably causes the DB error since `WHERE post_id IN () ` is invalid SQL. I don't know the ins and outs of the code, but seems pretty simple?

**Comment by wuspum** [comment] 2021-12-21 12:34
@rodelgc 
Experiencing the same issue since 6.0

https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5417

**Comment by vg-robin** [comment] 2021-12-21 22:50
This needs opening ASAP...

**Comment by sirion89** [comment] 2021-12-23 14:11
I have the same issue with 6.0.0

Edit:

I killed it temporarly going into wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/AbstractProductGrid.php inside function prime_product_variations and simply doing this:


```
	    /**
	     * Prime query cache of product variation meta data.
	     *
	     * Prepares values in the product_ID_variation_meta_data cache for later use in the ProductSchema::get_variations()
             * method. Doing so here reduces the total number of queries needed.
	     *
             * @param int[] $product_ids Product ids to prime variation cache for.
	     */
	    protected function prime_product_variations( $product_ids ) {
		$cache_group       = 'product_variation_meta_data';
		$prime_product_ids = $this->get_non_cached_ids( wp_parse_id_list( $product_ids ), $cache_group );

		if ( ! $prime_product_ids ) {
			return;
		}

		global $wpdb;

		// phpcs:disable WordPress.DB.PreparedSQL.NotPrepared
		$product_variations      = $wpdb->get_results( "SELECT ID as variation_id, post_parent as product_id from {$wpdb->posts} WHERE post_parent IN ( " . implode( ',', $prime_product_ids ) . ' )', ARRAY_A );
		$prime_variation_ids     = array_column( $product_variations, 'variation_id' );
		// Added to avoid query errors
		if (empty($prime_variation_ids)){
			return;
		}
		[....] rest of the code
```

**Comment by ArneSaknussemm** [comment] 2022-01-01 18:44
Hi! I get the same error, but only in MySQL 10.5.13
The @sirion89 fix works.
EDIT:
Or you can do the following on your child theme:
```
add_filter('query', 'return_fake_variation_id');
function return_fake_variation_id($sql){
	if (str_contains(wp_debug_backtrace_summary(),"prime_product_variations")) {
		return "SELECT '' as variation_id FROM DUAL";
	}
    return $sql;
}
```
(PHP 8.0)
