### ISSUE TITLE
Tweak currency placement in the price fields

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#35180] opened 2022-10-19 11:20 UTC
**Description:** the price input field is so large that it can create a disconnection between the value and the currency, considering that the currency is placed in the right margin of the field. 

**Acceptance criteria:**
- [ ] Move the currency to the left margin of the list and sales price input field

**Comment by mdperez86** [comment] 2022-10-21 19:31
@pmcpinto I think this is not require since the currency symbol is currently sitting on the left side of both input fields


![Image](https://user-images.githubusercontent.com/13334210/197274884-80fdd490-a8a4-4667-86e4-61ef4a49e21c.png)

**Comment by mattsherman** [comment] 2022-10-23 12:00
@mdperez86 This is not true. The currency symbol position is dynamically set based on the WooCommerce > Settings > General > Currency options > Currency position setting. 

Code reference where we set prefix vs suffix:
https://github.com/woocommerce/woocommerce/blob/64ee20ff0f47fc69c546eefeaa421536c4fa3a4a/plugins/woocommerce-admin/client/products/sections/utils.ts#L49

@pmcpinto @jarekmorawski If we are changing this placement, we should also consider changing the placement of other input field adornments, such as the search field magnifying glass icon (suffix) and the date time picker calendar icon (suffix) for consistency. If so, we should open up separate issues for those.

Also, it should be noted that the reason for this symbol being so disconnected from the value is that we are making the input fields 100% width in the sections, which does not match the original design. So, before we make this change, I just want to double-check that we actually don't want to change the width of the input fields to match the original design.

**Comment by pmcpinto** [comment] 2022-10-24 09:44
> @pmcpinto @jarekmorawski If we are changing this placement, we should also consider changing the placement of other input field adornments, such as the search field magnifying glass icon (suffix) and the date time picker calendar icon (suffix) for consistency. If so, we should open up separate issues for those.
> Also, it should be noted that the reason for this symbol being so disconnected from the value is that we are making the input fields 100% width in the sections, which does not match the original design. So, before we make this change, I just want to double-check that we actually don't want to change the width of the input fields to match the original design.

Good point. The input field width should be 50%. @jarekmorawski what do you think?

**Comment by mdperez86** [comment] 2022-10-24 16:28
@pmcpinto 

> The input field width should be 50%. @jarekmorawski what do you think?

This can introduce responsive problems. The size of the field could not be the solution for this because we have different number sizes and different screen sizes so it's very possible we never fit the right input size across all configs.

A possible solution (from @octaedro) could be the alignment of the number inside the field. If the currency symbol is on the right then the number align could be also right, same for the left alignment.

**Comment by jarekmorawski** [comment] 2022-10-25 10:30
> If we are changing this placement, we should also consider changing the placement of other input field adornments, such as the search field magnifying glass icon (suffix) and the date time picker calendar icon (suffix) for consistency

I see what you're getting at. However, the magnifying glass in the search field is an affordance—much like the downward chevron in a regular dropdown. It indicates the action and lets the user know how they can interact with the field. In this case, the currency symbol is part of the field's content.

It gets even more complicated when you take locale into account. In the US, the currency symbol should be placed before the number. In Europe, on the other hand, it should _follow_ the amount. Having it in the front is acceptable, but slightly weird. Is there a way we could automate that?

> The input field width should be 50%. @jarekmorawski what do you think?

I agree. Let's make these fields 50% on the desktop and 100% on tablet and mobile.

> The size of the field could not be the solution for this because we have different number sizes and different screen sizes so it's very possible we never fit the right input size across all configs.

We could add conditions, so the field is only 50% when the form's width is 1032px or larger. What do you think?

> If the currency symbol is on the right then the number align could be also right, same for the left alignment.

Interesting idea. The currency symbol definitely has more to do with the field's content, rather than the field itself. Is it possible to treat it as the input's prefix or suffix instead of part of the field's composition?

**Comment by mdperez86** [comment] 2022-10-25 13:14
@jarekmorawski 

> Is it possible to treat it as the input's prefix or suffix instead of part of the field's composition?

Yes it's possible for us to do it. But that introduces more complexity here. First we need to format the number the user is typing to show it back in a `currency format` way `('1234' -> '$1,234')`. This process is the same when optaining the value from the server because the server only store the raw number. Second we need to parse the number `('$1,234' -> '1234')` because now it's possible for the user to type something like `$8999` or `2342EUR` because the server only supports the raw number. 

Or maybe we can use a mask input.

cc: @mattsherman @octaedro Any other idea?

**Comment by jarekmorawski** [comment] 2022-10-25 16:54
As we agreed during the team call, let's keep the current setup (with the currency symbol fixed inside the input field and synced with the store's locale) and make the field 50% wide on desktop and 100% on mobile. Thank you!

**Comment by AnnaMag** [comment] 2022-11-10 10:28
closing in favor of https://github.com/woocommerce/woocommerce/issues/35538

**Comment by AnnaMag** [comment] 2022-11-10 12:30
Reopening after retesting: the placement of the currency seem to depend on the locale, which by design should not affect it.

**Comment by mattsherman** [comment] 2022-11-12 01:45
> Reopening after retesting: the placement of the currency seem to depend on the locale, which by design should not affect it.

No, it *should* affect it. This was by design. As @jarekmorawski mentioned above:

> As we agreed during the team call, let's keep the current setup (with the currency symbol fixed inside the input field and synced with the store's locale) and make the field 50% wide on desktop and 100% on mobile. Thank you!

Re-closing.

**Closed as completed by mattsherman** 2022-11-12 01:45 UTC

**Comment by jarekmorawski** [comment] 2022-11-12 08:45
My apologies for the back-and-forth and confusing communication on this one. Anna reopened this issue on my request after I explored the problem a bit more during the meetup. We could simplify maintenance (and introduce a more rigid component structure) by fixing the currency symbol's position within the field.

I opened another issue with all the details (#35558), so we can keep this one closed.
