### ISSUE TITLE
Fiter by Attribute is not working

### ISSUE THREAD

**Issue by soniverma1** [woothemes/woocommerce#32065] opened 2022-03-14 08:22 UTC
Hi Team,

The sidebar widget “Filter Products by Attribute” Is not showing.
I have attributes; like color, frame shape, frame weight, frame size, frame type, gender etc
But when I add the widget on defalt sidebar option or custom sidebar option, it does not show, even though other items like product categories, search bar, navigation are showing in sidebar.

Would be great if you can help me solving this issue.

Thank You

**Comment by wayheming** [comment] 2022-03-14 10:44
same issue after update

**Comment by stuart-lambon** [comment] 2022-03-14 17:11
Also having the same issue here. Happy to provide more details if required since this issue report does not give much detail.

**Comment by roykho** [comment] 2022-03-14 19:04
Hi [soniverma1](https://github.com/soniverma1),

Thank you for submitting the issue. However, you didn't fill out the details of the bug report template that we ask for. Without these details, we can't fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by bashgeek** [comment] 2022-03-15 04:55
Same for us, our "Filter Products by Attribute" widgets in the sidebar are not showing anymore since the last WC update.

Edit: Nevermind, using the "Regenerate the product attributes lookup table" tool fixed it for us.

**Comment by sergiomxdh** [comment] 2022-03-15 20:58
Same issue

**Comment by stuart-lambon** [comment] 2022-03-16 21:54
As @bashgeek recommended, I can confirm that running the ‘Regenerate the product attributes lookup table’ with a full table regeneration worked for me to fix this issue. I’m not sure many users will be able to easily know to do this though.

**Comment by Spiranjas** [comment] 2022-03-21 10:18
Same issue !!

**Comment by raifd** [comment] 2022-03-29 09:35
34850661-hc and 4859437-zd-woothemes both had this issue and it was solved by regenerating the product attributes lookup table and clearing the transients!

**Comment by raifd** [comment] 2022-03-29 11:56
Another report here after the update: 4902964-zd-woothemes

**Comment by jonathansadowski** [comment] 2022-03-29 22:31
Thanks for the reports. I'm adding the developer reproduction label, as there are several hc and zd reports that might require access that only developers have for reproduction.

**Comment by sitoagency** [comment] 2022-03-30 11:33
Same issue here, plus the "Regenerate product attribute lookup table" fix is only temporary

https://wordpress.org/support/topic/woocommerce-6-3-1-breaks-attribute-filters/#post-15487103

**Comment by raifd** [comment] 2022-03-30 11:34
@frafor1988 Have you tried clearing the transients as well? 

1.  Regenerate product attribute lookup table
2. Clear the transients!

**Comment by sitoagency** [comment] 2022-03-30 11:35
1. Yes I've literally written that
2. Yes I've cleaned everything

**Comment by sitoagency** [comment] 2022-03-30 11:42
So far, the only solution is to disable the use of the product attribute lookup table, as mentioned here: https://wordpress.org/support/topic/filter-by-attribute-is-no-longer-working/

This applies to YITH Ajax Product Filter plugin, I don't know if regenerating the table is enough for the standard WC filter widgetblock.

**Comment by thuautp** [comment] 2022-03-31 10:30
AT site at 4893317-zen. Regenerating Product lookup tables and flushing cache fixed the issue.

**Comment by paoloromano** [comment] 2022-04-12 18:01
I still have this issue.
I delete the transient and i regenerate the lookup table.
Any other solutions?
Thanks

**Comment by raifd** [comment] 2022-04-13 13:27
4944160-zd-woothemes

**Comment by paoloromano** [comment] 2022-04-13 13:33
> I still have this issue. I delete the transient and i regenerate the lookup table. Any other solutions? Thanks

In my website we have two langs. For default lang disabling plugin "Product Visibility by User Role for WooCommerce" solve the issue. But I still have the issue on english lang.

**Comment by ldr2273** [comment] 2022-04-18 17:35
4956278-zd as well.

Resolved by regenerating the product attributes lookup table and clearing the transients, though this might only be temporary?

**Comment by sitoagency** [comment] 2022-04-18 17:57
You've got to disabile the product attribuite lookup tablet in Woocommerce - settings - products - advanced. The 1st checkbox must be unchecked, those tables have issues.

**Comment by csmcneill** [comment] 2022-04-19 22:10
4944160-zen

Disabling the `Enable table usage` option at **WooCommerce > Settings > Products > Advanced** resolved the issue.

**Comment by peterfabian** [comment] 2022-04-29 08:40
Hi all, 

Can you please help us reproduce the issue? 

Ideally, it would be great if you could create a minimal example with one or two attributes and the product and share 
1. A screenshot of how you have the attributes set up
2. A screenshot of how you have the product set up
3. Description/screenshot of how you have the filtering set up (is it a widget added through customizer?)
4. Your system status report

If you can reproduce this problem only with WooCommerce and Storefront without other plugins, that would be the best.

Otherwise, it's difficult for us to guess how you have things set up. 

Thanks!

**Comment by gigitux** [comment] 2022-04-29 15:10
I reproduced this issue while working on https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/6322.

It seems that the problem is caused by the way we import products (via REST API) in our test E2E env. I prepared a script that simulate our script to reproduce in a fast way the bug.

1. Clone [this repo](https://github.com/gigitux/woocommerce-import-product-rest-api-reprosteps) that contains the script for importing products via REST API.
2. In the cloned project, run:
```
npm install
npm run wp-env start
npm run import-products 
```

If you see some errors, don't worry :) 

3. Now, go on `localhost:8889/shop/?filter_capacity=128gb&query_type_capacity=or`.
4. You can see that WooCommerce doesn't render any product. This is a bug because the script imports a product that has the attribute: Capacity-128gb.
5. Disabling the Enable table usage option at WooCommerce > Settings > Products > Advanced resolved the issue.


In my case, I think that this behavior it doesn't strictly dependent on WooCommerce. I suspect that the root of the problem is that on the env that wp-env generates, the loopback request fails. https://github.com/WordPress/gutenberg/issues/20569.

![image](https://user-images.githubusercontent.com/4463174/165971914-e85206d1-ceac-4b7d-ab7e-a913c4257b57.png)

Maybe we should display a warning message because the site health is pretty hidden and finding a correlation can be difficult, especially for a common user.

**Comment by gigitux** [comment] 2022-05-03 16:21
With @Konamiman, we find that this problem is caused by the table `product_attribute_lookup` that is not regenerated. In our tests, this happens in two cases:
1) when the user upgrades to WC 6.3, the table usage' flag is enabled, but the table is empty. (to fix the problem, the user should click the button `Update WooCommerce Database` on the alert WooCommerce database update required - check the image).
2) when the user adds the product via `POST /wp-json/wc/v3/products/batch` endpoint, the action `woocommerce_run_product_attribute_lookup_regeneration_callback` is not triggered.

![image](https://user-images.githubusercontent.com/4463174/166493206-ab83a0c1-8dc7-45bc-b2d1-015e61ded06d.png)

The proposals to fix these two cases are:
1) the `table usage` shouldn't be activated after the update to WC 6.3 until the user updates the DB.
2) the `POST /wp-json/wc/v3/products/batch` endpoint should trigger the action `woocommerce_run_product_attribute_lookup_regeneration_callback`.

**Comment by Konamiman** [comment] 2022-05-04 07:02
To add more context: the lookup table being empty (while in use) causes the widget to keep hidden, because the widget only shows attributes for existing products, and if it thinks that there are no products then it thinks there are no attributes to filter by at all and thus it simply doesn't show up.

We'll work on a fix for this ASAP, but in the mean time, the workaround is indeed to use the "Regenerate the product attributes lookup table" tool and to flush any caches/transients that might interfere.

**Closed as completed** 2022-05-06 16:58 UTC
Labels: plugin: woocommerce, status: developer reproduction

**Comment by alptarik** [comment] 2023-03-07 12:39
> I reproduced this issue while working on [woocommerce/woocommerce-blocks#6322](https://github.com/woocommerce/woocommerce-blocks/issues/6322).
> 
> It seems that the problem is caused by the way we import products (via REST API) in our test E2E env. I prepared a script that simulate our script to reproduce in a fast way the bug.
> 
> 1. Clone [this repo](https://github.com/gigitux/woocommerce-import-product-rest-api-reprosteps) that contains the script for importing products via REST API.
> 2. In the cloned project, run:
> 
> ```
> npm install
> npm run wp-env start
> npm run import-products 
> ```
> 
> If you see some errors, don't worry :)
> 
> 3. Now, go on `localhost:8889/shop/?filter_capacity=128gb&query_type_capacity=or`.
> 4. You can see that WooCommerce doesn't render any product. This is a bug because the script imports a product that has the attribute: Capacity-128gb.
> 5. Disabling the Enable table usage option at WooCommerce > Settings > Products > Advanced resolved the issue.
> 
> In my case, I think that this behavior it doesn't strictly dependent on WooCommerce. I suspect that the root of the problem is that on the env that wp-env generates, the loopback request fails. [WordPress/gutenberg#20569](https://github.com/WordPress/gutenberg/issues/20569).
> 
> ![image](https://user-images.githubusercontent.com/4463174/165971914-e85206d1-ceac-4b7d-ab7e-a913c4257b57.png)
> 
> Maybe we should display a warning message because the site health is pretty hidden and finding a correlation can be difficult, especially for a common user.

There was no method that I had not tried for a long time. Especially after the translation of the wpml plugin, it started not seeing any of the widgets in the original language in the same way. 5.Disabling the Enable table usage option at WooCommerce > Settings > Products > Advanced resolved the issue. Part solved the problem completely, thank you very much.
