### ISSUE TITLE
2 quantity of products is added when we click add to cart.

### ISSUE THREAD

**Issue by doublezed2** [woothemes/woocommerce#43501] opened 2024-01-11 10:54 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

A quantity of 2 is added to the cart when I click on the Add to Cart button.
This happens we I use Query Loop block with Post Type set to Products.
The Add to Cart button is not present in the Query Block and needs to be added manually.
Link to ZD Ticket: https://a8c.zendesk.com/agent/tickets/7530763
Link to Slack: https://a8c.slack.com/archives/C014E5VH9HC/p1704693708399629

### Expected behavior

Expected behavior is 1 quantity product added to the cart.

### Actual behavior

When I click on the Add to Cart button, 2 quantities of the clicked product are added to the cart.

### Steps to reproduce

Here are the steps to reproduce the issue:
1- Create a Query Loop Block
2- Change the Post Type to Products.
3- Add an "Add To Cart" button in the Query Block (Ref: https://prnt.sc/81SX5f5LMkki)
4- Visit the page and add a product to the cart.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://staging6.mundogeekstore.com.mx
Site address (URL): http://staging6.mundogeekstore.com.mx
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: –
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 8.2.1
OpenSSL/3.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.44-48-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: nol_
Tamaño total de la base de datos: 40.67MB
Tamaño de los datos de la base de datos: 37.53MB
Tamaño del índice de la base de datos: 3.14MB
nol_woocommerce_sessions: Datos: 0.08MB + Índice: 0.02MB + Motor InnoDB
nol_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nol_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nol_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
nol_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nol_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nol_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
nol_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nol_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
nol_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nol_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
nol_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nol_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nol_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nol_actionscheduler_actions: Datos: 0.17MB + Índice: 0.16MB + Motor InnoDB
nol_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nol_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nol_actionscheduler_logs: Datos: 0.13MB + Índice: 0.13MB + Motor InnoDB
nol_aioseo_cache: Datos: 0.03MB + Índice: 0.03MB + Motor InnoDB
nol_aioseo_notifications: Datos: 0.06MB + Índice: 0.06MB + Motor InnoDB
nol_aioseo_posts: Datos: 1.52MB + Índice: 0.05MB + Motor InnoDB
nol_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nol_comments: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
nol_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nol_options: Datos: 26.30MB + Índice: 0.08MB + Motor InnoDB
nol_postmeta: Datos: 3.52MB + Índice: 0.63MB + Motor InnoDB
nol_posts: Datos: 4.52MB + Índice: 0.28MB + Motor InnoDB
nol_sgs_log_events: Datos: 0.06MB + Índice: 0.02MB + Motor InnoDB
nol_sgs_log_visitors: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nol_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nol_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nol_term_relationships: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
nol_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nol_usermeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nol_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
nol_wc_admin_notes: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
nol_wc_admin_note_actions: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
nol_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
nol_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nol_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nol_wc_orders: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
nol_wc_orders_meta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nol_wc_order_addresses: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
nol_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nol_wc_order_operational_data: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nol_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
nol_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
nol_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nol_wc_product_attributes_lookup: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nol_wc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nol_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
nol_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nol_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
nol_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nol_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nol_wpforms_payments: Datos: 0.02MB + Índice: 0.14MB + Motor InnoDB
nol_wpforms_payment_meta: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
nol_wpforms_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
nol_wpf_filters: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
nol_wpf_meta_keys: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nol_wpf_meta_values: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nol_wpf_meta_values_bk: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB

### Post Type Counts ###

attachment: 631
custom_css: 1
customize_changeset: 95
nav_menu_item: 7
page: 14
post: 11
product: 85
revision: 157
shop_order: 7
wp_block: 1
wp_global_styles: 1
wp_navigation: 1
wpforms: 1
yith_wcan_preset: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: por Automattic – 8.4.0

### Inactive Plugins (14) ###

All in One SEO: por All in One SEO Team – 4.5.3.1
Google Analytics for WordPress by MonsterInsights: por MonsterInsights – 8.23.1
Openpay Cards Plugin: por Openpay – 2.8.0
Openpay Stores Plugin: por Openpay – 1.11.3
OptinMonster: por OptinMonster Popup Builder Team – 2.15.3
Security Optimizer: por SiteGround – 1.4.9
SiteGround Central: por SiteGround – 3.0.2
Social Chat: por QuadLayers – 7.2.1
Spectra: por Brainstorm Force – 2.11.2
Speed Optimizer: por SiteGround – 7.4.5
Starter Templates: por Brainstorm Force – 4.0.1
WordPress Importer: por wordpressdotorg – 0.8.1
WPForms Lite: por WPForms – 1.8.5.4
YITH WooCommerce Ajax Product Filter: por YITH – 4.29.0

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: MXN ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### WC Pages ###

Base de la tienda: ❌ Página sin definir
Carrito: #2150 - /carrito/
Finalizar compra: #2157 - /finalizar-compra/
Mi cuenta: ❌ Página sin definir
Términos y condiciones: #1192 - /terminos-y-condiciones/

### Theme ###

Name: Storefront
Version: 4.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-11-26 22:47:20 +00:00
Options: ✔
Notes: 63
Onboarding: completed

### Action Scheduler ###

Completo: 409
Oldest: 2023-12-07 22:36:01 +0000
Newest: 2024-01-07 22:24:12 +0000

Fallida: 15
Oldest: 2023-11-29 18:58:13 +0000
Newest: 2024-01-03 01:09:03 +0000

Pendiente: 4
Oldest: 2024-01-07 22:32:57 +0000
Newest: 2024-01-08 22:17:57 +0000

### Status report information ###

Generated at: 2024-01-07 22:25:51 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by gigitux** [comment] 2024-01-11 13:30
Hi @doublezed2,
Thanks for opening this issue! We are aware of this issue, and we already fixed it: https://github.com/woocommerce/woocommerce/pull/43325. This fix will be shipped with WooCommerce Core 8.6.
I will close this issue, but feel free to reply if you can reproduce it with a nightly build of WooCommerce 8.6 (you can download it from: https://github.com/woocommerce/woocommerce/tags)

In the meantime, I would suggest using an alternative block or switching to a block theme where the issue is not present.

**Closed as completed by gigitux** 2024-01-11 13:30 UTC
Labels: Bug, type: community contribution, Kirigami, Blocks/Patterns/Templates
