### ISSUE TITLE
PHP Fatal error: Uncaught ValueError: Path cannot be empty in woocommerce/includes/wc-template-functions.php:53

### ISSUE THREAD

**Issue by JimDaou** [woothemes/woocommerce#40207] opened 2023-09-15 09:35 UTC

**Comment by lsinger** [comment] 2023-09-15 10:05
Hello @JimDaou,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs in WooCommerce Core only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [[WooCommerce Community Slack](https://woocommerce.com/community-slack/)](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by lsinger** 2023-09-15 10:05 UTC
Labels: type: community contribution

**Comment by JimDaou** [comment] 2023-09-15 10:09
ok thank you . can you please provide me with a new link because this said is no longer available

**Comment by lsinger** [comment] 2023-09-18 10:33
@JimDaou could you clarify what kind of link you need that is not available anymore?
