### ISSUE TITLE
gettext reviews filter killing dashboard performance

### ISSUE THREAD

**Issue by brianmurphy** [woothemes/woocommerce#35586] opened 2022-11-14 22:19 UTC
https://github.com/woocommerce/woocommerce/blob/932b3386c3100f60607fb8b74c0cad2ccfb2f6cc/plugins/woocommerce/src/Internal/Admin/ProductReviews/Reviews.php#L52

I was code profiling our wordpress dashboard and the Automattic\WooCommerce\Internal\Admin\ProductReviews\Reviews->edit_comments_screen_text method is the number one thing slowing down our website.

We have product reviews disabled in the woocommerce settings.

The culprit appears to be from woocommerce enqueuing the edit_comments_screen_text Reviews method on the gettext filter.

Removing self::add_filter( 'gettext', [ $this, 'edit_comments_screen_text' ], 10, 2 ); from the Reviews constructor fixes our problem.

**Comment by Oremaker** [comment] 2023-01-10 10:34
This filter alone is adding 0.2seconds to my woocommerce site, huge performance issue

**Comment by lkraav** [comment] 2023-01-10 11:10
> I was code profiling our wordpress dashboard and the Automattic\WooCommerce\Internal\Admin\ProductReviews\Reviews->edit_comments_screen_text method is the number one thing slowing down our website.

Can you post some more specific profiling result numbers?

**Comment by alexanderaltendorfer** [comment] 2023-06-27 16:41
We are seeing the same issue on our sites. Shouldn't it be possible to completely skip loading this class, if product reviews are disabled in the woocommerce settings?

**Comment by barryhughes** [comment] 2023-06-27 23:08
Agree, this filter should not be running on all requests (and it may be worth checking to see if there is a better approach then a gettext filter in any case).

**Comment by rrennick** [comment] 2023-10-24 18:33
This is. duplicate of #35372 . We'll address this issue in the other issue.

**Closed as completed by rrennick** 2023-10-24 18:33 UTC
Labels: Bug, Product/Inventory Management, type: community contribution, Performance
