### ISSUE TITLE
Review and rating UI Issue

### ISSUE THREAD

**Issue by samkh63** [woothemes/woocommerce#41390] opened 2023-11-12 13:37 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have noticed that even customers rate the product 5 starts, the UI still Show the Star rating 4.5 stars ,
i have investigate the code and find out it is related to css andd html structure 

### Expected behavior

if customer rate 5 stars it show show 5 rated stars and show the indication of 5/5

### Actual behavior

When Users Rate an products 5 stars, UI shows 4.5 stars instead and the indicator of 5/5 is missing 

### Steps to reproduce

go to shop page
click on any product with review
review in top under price and the rest of review on the bottom of the page
![wc-review0](https://github.com/woocommerce/woocommerce/assets/42343901/3b38fa8f-08aa-42f5-80d0-52b28ad0017c)
![wc-review1](https://github.com/woocommerce/woocommerce/assets/42343901/f6b798dd-cc14-42b4-8120-c287c5e751b3)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://aafiyalife.com
Site address (URL): https://aafiyalife.com
WC Version: 8.2.2
REST API Version: ✔ 8.2.2
WC Blocks Version: ✔ 11.1.3
Action Scheduler Version: ✔ 3.6.3
Log Directory Writable: ✔
WP Version: ❌ 6.3.2 - There is a newer version of WordPress available (6.4.1)
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.25
PHP Post Max Size: 512 MB
PHP Time Limit: 90
PHP Max Input Vars: 5000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 8.0.35
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.2
WC Database Prefix: wpaj_
Total Database Size: 427.47MB
Database Data Size: 339.62MB
Database Index Size: 87.85MB
wpaj_woocommerce_sessions: Data: 4.24MB + Index: 0.17MB + Engine MyISAM
wpaj_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpaj_woocommerce_order_items: Data: 0.83MB + Index: 0.56MB + Engine MyISAM
wpaj_woocommerce_order_itemmeta: Data: 7.26MB + Index: 4.94MB + Engine MyISAM
wpaj_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_woocommerce_payment_tokenmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpaj_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_actionscheduler_actions: Data: 4.48MB + Index: 2.29MB + Engine MyISAM
wpaj_actionscheduler_claims: Data: 0.50MB + Index: 1.74MB + Engine MyISAM
wpaj_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpaj_actionscheduler_logs: Data: 5.05MB + Index: 4.04MB + Engine MyISAM
wpaj_affiliate_wp_affiliatemeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpaj_affiliate_wp_affiliates: Data: 0.31MB + Index: 0.23MB + Engine MyISAM
wpaj_affiliate_wp_campaigns: Data: 0.00MB + Index: 0.00MB + Engine
wpaj_affiliate_wp_connections: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpaj_affiliate_wp_coupons: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_affiliate_wp_creativemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpaj_affiliate_wp_creatives: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_affiliate_wp_custom_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpaj_affiliate_wp_customermeta: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wpaj_affiliate_wp_customers: Data: 0.06MB + Index: 0.05MB + Engine MyISAM
wpaj_affiliate_wp_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpaj_affiliate_wp_notifications: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpaj_affiliate_wp_payouts: Data: 0.04MB + Index: 0.03MB + Engine MyISAM
wpaj_affiliate_wp_referralmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_affiliate_wp_referrals: Data: 0.21MB + Index: 0.03MB + Engine MyISAM
wpaj_affiliate_wp_rest_consumers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_affiliate_wp_sales: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wpaj_affiliate_wp_visits: Data: 0.47MB + Index: 0.13MB + Engine MyISAM
wpaj_aioseo_cache: Data: 0.11MB + Index: 0.01MB + Engine MyISAM
wpaj_aioseo_notifications: Data: 0.13MB + Index: 0.01MB + Engine MyISAM
wpaj_aioseo_posts: Data: 2.18MB + Index: 0.06MB + Engine MyISAM
wpaj_aioseo_revisions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wpaj_aioseo_search_statistics_objects: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_aioseo_terms: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpaj_bfw: Data: 0.32MB + Index: 0.24MB + Engine MyISAM
wpaj_cartflows_ca_cart_abandonment: Data: 4.45MB + Index: 0.44MB + Engine MyISAM
wpaj_cartflows_ca_email_history: Data: 1.96MB + Index: 1.71MB + Engine MyISAM
wpaj_cartflows_ca_email_templates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_cartflows_ca_email_templates_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpaj_comments: Data: 6.99MB + Index: 2.98MB + Engine MyISAM
wpaj_css_js_manager: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_e_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_e_submissions: Data: 0.08MB + Index: 0.09MB + Engine MyISAM
wpaj_e_submissions_actions_log: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wpaj_e_submissions_values: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wpaj_expm_hiiden_content: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpaj_expm_maker: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpaj_expm_maker_pages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpaj_find_and_replace: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpaj_gamipress_logs: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
wpaj_gamipress_logs_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wpaj_gamipress_user_earnings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpaj_gamipress_user_earnings_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpaj_ld_notifications_delayed_emails: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_learndash_pro_quiz_category: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_learndash_pro_quiz_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_learndash_pro_quiz_lock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_learndash_pro_quiz_master: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wpaj_learndash_pro_quiz_prerequisite: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_learndash_pro_quiz_question: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wpaj_learndash_pro_quiz_statistic: Data: 0.20MB + Index: 0.08MB + Engine MyISAM
wpaj_learndash_pro_quiz_statistic_ref: Data: 0.12MB + Index: 0.16MB + Engine MyISAM
wpaj_learndash_pro_quiz_template: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_learndash_pro_quiz_toplist: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_learndash_user_activity: Data: 5.71MB + Index: 10.76MB + Engine MyISAM
wpaj_learndash_user_activity_meta: Data: 4.81MB + Index: 4.03MB + Engine MyISAM
wpaj_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_mailchimp_carts: Data: 0.18MB + Index: 0.02MB + Engine MyISAM
wpaj_mailchimp_jobs: Data: 4.06MB + Index: 0.13MB + Engine MyISAM
wpaj_options: Data: 13.54MB + Index: 0.99MB + Engine MyISAM
wpaj_postmeta: Data: 170.06MB + Index: 25.70MB + Engine MyISAM
wpaj_posts: Data: 46.16MB + Index: 7.36MB + Engine InnoDB
wpaj_smush_dir_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_snc_file_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpaj_snc_post_relationship: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpaj_stock_log: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wpaj_tc_course_access: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpaj_term_relationships: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wpaj_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpaj_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpaj_terms: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wpaj_tm_taskmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_tm_tasks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_ulike: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_ulike_activities: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_ulike_comments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_ulike_forums: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_ulike_meta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpaj_uotincan_quiz: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpaj_uotincan_reporting: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpaj_uotincan_resume: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpaj_usermeta: Data: 32.43MB + Index: 13.84MB + Engine MyISAM
wpaj_users: Data: 1.17MB + Index: 1.25MB + Engine MyISAM
wpaj_vxcf_mailchimp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_vxcf_mailchimp_accounts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_vxcf_mailchimp_log: Data: 15.18MB + Index: 0.06MB + Engine MyISAM
wpaj_wc_admin_note_actions: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wpaj_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine MyISAM
wpaj_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_wc_customer_lookup: Data: 0.86MB + Index: 0.81MB + Engine MyISAM
wpaj_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpaj_wc_order_coupon_lookup: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wpaj_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpaj_wc_order_product_lookup: Data: 1.40MB + Index: 1.19MB + Engine MyISAM
wpaj_wc_order_stats: Data: 1.08MB + Index: 0.72MB + Engine MyISAM
wpaj_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpaj_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpaj_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpaj_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpaj_wc_rate_limits: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpaj_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpaj_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_wooup_offers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_wooup_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_wooup_view_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_wpforms_payment_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_wpforms_payments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_wpforms_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpaj_wpmailsmtp_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_wpr_rocket_cache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpaj_wpr_rucss_used_css: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpaj_wt_iew_action_history: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wpaj_wt_iew_cron: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_wt_iew_ftp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_wt_iew_mapping_template: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_yoast_indexable: Data: 0.21MB + Index: 0.07MB + Engine MyISAM
wpaj_yoast_indexable_hierarchy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpaj_yoast_primary_term: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpaj_yoast_seo_links: Data: 0.02MB + Index: 0.01MB + Engine MyISAM

### Post Type Counts ###

achievement-type: 1
attachment: 813
basic: 3
branda_email_log: 100
custom_css: 3
elementor_icons: 1
elementor_library: 33
elementor-hf: 3
groups: 73
ld-notification: 19
mc4wp-form: 1
nav_menu_item: 24
oembed_cache: 65
page: 37
points-type: 1
popup: 9
popup_theme: 9
popupbuilder: 7
post: 12
product: 40
product_variation: 13
sfwd-courses: 20
sfwd-essays: 3392
sfwd-lessons: 459
sfwd-question: 61
sfwd-quiz: 46
sfwd-topic: 2
shop_coupon: 22
shop_order: 14790
shop_order_refund: 17
testimonial: 12
viwec_template: 14
wc_afrsm_zone: 1
woocustomemails: 1
wp_global_styles: 1
wp_navigation: 1
wpcf7_contact_form: 5
wpcf7r_action: 3
wpforms: 2
zoom-meetings: 30

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (53) ###

CAPTCHA 4WP: by Melapress – 7.3.1
AffiliateWP: by AffiliateWP – 2.17.0
AffiliateWP - Affiliate Area Tabs: by Sandhills Development
LLC – 1.4

AIOSEO - Image SEO: by All in One SEO Team – 1.1.10
AIOSEO - Local Business: by All in One SEO Team – 1.2.18
All in One SEO Pro: by All in One SEO Team – 4.5.0
Astra Pro: by Brainstorm Force – 4.4.0
Billplz for WooCommerce: by Billplz Sdn Bhd – 3.28.1
Branda: by WPMU DEV – 3.4.13
WP Contact Form and Mailchimp: by CRM Perks. – 1.1.3
CHIP for WooCommerce: by Chip In Sdn Bhd – 1.4.5
Cloudflare: by Cloudflare
Inc. – 4.12.2

Contact Form 7: by Takayuki Miyoshi – 5.8.2
CSS JS Manager, Async JavaScript, Defer Render Blocking CSS: by Pi Websolution – 2.4.49.19
Custom Fonts: by Brainstorm Force – 2.1.0
Disable Cart Fragments: by LittleBizzy – 1.3.0
Elementor Pro: by Elementor.com – 3.17.1
Elementor: by Elementor.com – 3.17.3
Email Template Customizer for WooCommerce: by VillaTheme – 1.2.0
Facebook for WooCommerce: by Facebook – 3.1.3
Elementor Header & Footer Builder: by Brainstorm Force
Nikhil Chavan – 1.6.17

ShopBack PayLater - buy now, pay later: by ShopBack PayLater – 2.3.65
Inactive Logout: by Deepen Bajracharya – 3.2.3
LearnDash LMS - Course Grid: by LearnDash – 2.0.8
LearnDash LMS - Elementor: by LearnDash – 1.0.4
LearnDash Licensing & Management: by LearnDash – 1.3
LearnDash LMS - Notifications: by LearnDash – 1.6.3
LearnDash LMS - WooCommerce Integration: by LearnDash – 1.9.7
Mailchimp for WooCommerce: by Mailchimp – 3.2
MC4WP: Mailchimp for WordPress: by ibericode – 4.9.9
Maintenance: by WebFactory Ltd – 4.08
MouseWheel Smooth Scroll: by KubiQ – 6.4
myGDEX Prime for Woocommerce: by GDEX – 1.0.4
Meta pixel for WordPress: by Facebook – 3.0.13
Payment Methods by Product & Country for WooCommerce: by WPFactory – 1.7.8
Print-O-Matic: by twinpictures – 2.1.10
Restrict Elementor Widgets: by Codexpert – 1.4
LearnDash LMS: by LearnDash – 4.10.0
SVG Support: by Benbodhi – 2.5.5
Uncanny Toolkit for LearnDash: by Uncanny Owl – 3.6.4.6
Uncanny Toolkit Pro for LearnDash: by Uncanny Owl – 4.1.3.1
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.25
Advanced Order Export For WooCommerce: by AlgolPlus – 3.4.2
WooCommerce Custom Thank You Pages: by Jeroen Sormani – 1.0.4
WooCommerce iPay88 Payment Gateway: by  –
WooCommerce Google Analytics Integration: by WooCommerce – 1.8.9
Quick Buy For WooCommerce: by Varun Sridharan – 2.8.4
Stock Manager for WooCommerce: by StoreApps – 3.0.0
WooCommerce: by Automattic – 8.2.2
WP Rocket: by WP Media – 3.15.0.1
WP Rollback: by GiveWP.com – 1.7.3
Redirection for Contact Form 7: by Qube One – 3.0.1
WPForms Lite: by WPForms – 1.8.4.1

### Inactive Plugins (3) ###

Instantio - Instant Checkout for WooCommerce: by Themefic – 3.1.5
Instantio Pro: by Themefic – 3.1.0
Tin Canny Reporting for LearnDash: by Uncanny Owl – 4.0.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: MYR (RM)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: course (course)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: ❌ Page visibility should be public
Cart: #26195 - /cart/
Checkout: #26196 - /checkout/
My account: #26197 - /my-account/
Terms and conditions: #25420 - /terma-syarat/

### Theme ###

Name: astra child
Version: 1.0.0
Author URL: http://wpastra.com/about/
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 4.4.0 – 4.4.1 is available
Parent Theme Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-11-13 04:47:04 +08:00
Options: ✔
Notes: 194
Onboarding: completed

### Action Scheduler ###

Canceled: 18
Oldest: 2023-10-14 02:01:44 +0000
Newest: 2023-11-12 13:26:47 +0000

Complete: 5,613
Oldest: 2023-10-12 13:43:54 +0000
Newest: 2023-11-12 13:32:19 +0000

Failed: 847
Oldest: 2021-10-19 15:21:46 +0000
Newest: 2023-10-20 14:24:41 +0000

In-progress: 1
Oldest: –
Newest: –

Pending: 55
Oldest: 2023-11-12 13:30:46 +0000
Newest: 2023-11-29 13:22:14 +0000

### Status report information ###

Generated at: 2023-11-12 21:32:42 +08:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment] 2023-11-15 16:43
> i have investigate the code and find out it is related to css andd html structure

@samkh63 I was not able to reproduce this with the Twenty Twenty-Two theme. You will need to look at your theme CSS or customizations added via the customizer of FSE editor. I'll close the issue.

<img width="408" alt="Screenshot 2023-11-15 at 12 39 17 PM" src="https://github.com/woocommerce/woocommerce/assets/343847/410733df-8591-4af9-9a3e-17f93fd51068">

**Closed as completed by rrennick** 2023-11-15 16:43 UTC
Labels: Bug, status: can't reproduce, type: community contribution
