### ISSUE TITLE
WooCommerce Account Creation and Password Reset Emails Not Delivered (to mailbox) from Frontend Pages

### ISSUE THREAD

**Issue by shohanhossainnab** [woothemes/woocommerce#45466] opened 2024-03-09 19:19 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Customers are unable to receive account creation and password reset emails when these actions are initiated from the WooCommerce "My Account" or checkout pages. Plugins like Email Log are able to log the emails, but emails are not being received in the primary inbox or the Junk/Spam folders. Conversely, when a password reset email is sent by an administrator from the WP-Admin interface, the email is successfully delivered to the customer's mailbox. Tested with Gmail and Live email addresses. https://github.com/woocommerce/woocommerce/issues/45120 tests might seem to confirm there's something off.

### Expected behavior

Customers should receive the emails in their mailbox.

### Actual behavior

Currently, the customers are not getting the account creation and password reset emails when initiated from the frontend.

### Steps to reproduce

1. Enable account creation on checkout and my-account page.
2. Now, create a new customer account either via my-account or from the checkout page.
3. After successfully registering, the account creation email never arrives. However, you can see the email being logged if the Email Log is active.
4. Now, try to reset the password. Again, the email never arrives.
5. Now, try to send a reset password email from WP-Admin; the email arrives in the customer mailbox.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://testwoopay.mystagingwebsite.com
Site address (URL): https://testwoopay.mystagingwebsite.com
WC Version: 8.6.1
REST API Version: ✔ 8.6.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.3.3
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.6.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Total Database Size: 17.07MB
Database Data Size: 11.53MB
Database Index Size: 5.54MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.17MB + Index: 0.19MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.02MB + Index: 0.91MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 0.45MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
wp_email_log: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.03MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 2.30MB + Index: 0.92MB + Engine InnoDB
wp_posts: Data: 0.28MB + Index: 0.14MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_mnm_child_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.03MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_generator_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woo_shippment_provider: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 284
aw_workflow: 2
bookable_person: 16
bookable_resource: 8
conditional-checkout: 1
kilb-pd-config: 1
kilb-pd-design: 1
kilb-pd-design-group: 1
kilb-pd-migrations: 1
kilb-pd-render-file: 1
page: 16
pdr_my_designs: 1
pdr_orders: 1
pdr_product_base: 16
post: 1
prl_engine: 1
product: 91
product_variation: 86
revision: 13
shop_coupon: 3
shop_order: 126
shop_order_refund: 9
shop_subscription: 19
wcpf_item: 4
wcpf_project: 1
wc_booking: 1
wc_pickup_location: 1
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Email Log: by Sudar – 2.4.9
WooCommerce Bookings: by WooCommerce – 2.0.8 (update to version 2.0.9 is available)
WooPayments: by Automattic – 7.3.0
Woo Subscriptions: by WooCommerce – 5.9.1 (update to version 6.0.0 is available)
WooCommerce: by Automattic – 8.6.1

### Inactive Plugins (52) ###

Advanced Shipment Tracking for WooCommerce: by zorem – 3.6.5
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
AutomateWoo: by WooCommerce – 6.0.15 (update to version 6.0.16 is available)
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.7.12 (update to version 2.7.15 is available)
Bookings Helper: by WooCommerce – 1.0.3
Classic Editor: by WordPress Contributors – 1.6.3
Code Snippets: by Code Snippets Pro – 3.6.2
Customize My Account Page For Woocommerce: by WPEverest – 0.4.8
Enhancer for WooCommerce Subscriptions: by Flintop – 4.2.0
Import Export Suite for WooCommerce: by WebToffee – 1.2.3 (update to version 1.2.5 is available)
Jetpack: by Automattic – 13.2-beta
KILB Product Designer: by Christian Kilb – 2.3.1
Loco Translate: by Tim Whitlock – 2.6.6
Product Designer for WooCommerce: by Flintop – 5.2.0
Product Filters for WooCommerce: by WooCommerce – 1.4.16 (update to version 1.4.21 is available)
SnapScan Online Payments: by  – 1.5.16
User Switching: by John Blackbourn & contributors – 1.7.3
WooCommerce 360° Image: by Themesquad – 1.2.1 (update to version 1.4.0 is available)
WooCommerce Additional Variation Images: by WooCommerce – 2.3.0 (update to version 2.3.2 is available)
WooCommerce Admin: by WooCommerce – 3.3.2
WooCommerce All Products For Subscriptions: by WooCommerce – 3.2.2 (update to version 5.0.1 is available)
WooCommerce All Products For Subscriptions: by WooCommerce – 4.1.2 (update to version 5.0.1 is available)
WooCommerce Amazon S3 Storage: by WooCommerce – 2.1.22 (update to version 2.7.0 is available)
WooCommerce Australia Post Shipping: by WooCommerce – 2.5.1 (update to version 2.5.7 is available)
WooCommerce Blocks: by Automattic – 11.7.0
WooCommerce Bookings Availability: by WooCommerce – 1.1.19
WooCommerce Box Office: by WooCommerce – 1.1.35 (update to version 1.2.4 is available)
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.12
WooCommerce Composite Products: by WooCommerce – 8.6.1 (update to version 9.0.1 is available)
WooCommerce Conditional Shipping and Payments: by WooCommerce – 1.13.0 (update to version 1.15.6 is available)
WooCommerce Deposits: by WooCommerce – 1.5.9 (update to version 2.2.6 is available)
WooCommerce Distance Rate Shipping: by WooCommerce – 1.3.5 (update to version 1.4.0 is available)
WooCommerce FedEx Shipping: by WooCommerce – 3.4.40 (update to version 3.9.1 is available)
WooCommerce Force Sells: by WooCommerce – 1.1.29 (update to version 1.4.0 is available)
WooCommerce Gift Cards: by WooCommerce – 1.15.0 (update to version 1.16.10 is available)
WooCommerce Local Pickup Plus: by SkyVerge – 2.10.0 (update to version 2.11.2 is available)
WooCommerce Mix and Match Products: by Kathy Darling – 2.6.1
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Pre-Orders: by WooCommerce – 1.7.0 (update to version 2.1.0 is available)
WooCommerce Price Based on Country: by Oscar Gare – 3.4.3
WooCommerce Product Add-ons: by WooCommerce – 6.2.0 (update to version 6.7.0 is available)
WooCommerce Product Bundles: by WooCommerce – 6.17.3 (update to version 7.0.1 is available)
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.46 (update to version 1.10.69 is available)
WooCommerce Product Recommendations: by WooCommerce – 3.0.3 (update to version 3.0.6 is available)
WooCommerce Shipment Tracking: by WooCommerce – 2.4.1 (update to version 2.4.5 is available)
WooCommerce Shipping & Tax: by WooCommerce – 2.5.2
WooCommerce Shipping Per Product v2: by WooThemes – 2.2.8
WooCommerce SnapScan Gateway: by WooCommerce – 1.1.12
WooCommerce Stripe Gateway: by WooCommerce – 8.0.0
WooCommerce Subscription Downloads: by WooCommerce – 1.3.0 (update to version 1.4.1 is available)
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.36 (update to version 3.1.6 is available)
WooCommerce UPS Shipping: by WooCommerce – 3.5.8

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #787 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.4
Author URL: https://woo.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 7.3.0
Connected to WPCOM: Yes
WPCOM Blog ID: 197395189
Account ID: acct_1JXHVB2H2GgGSRAX
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card,giropay,sofort,bancontact,eps,ideal,p24
WooPay: Disabled
WooPay Incompatible Extensions: Yes
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://testwoopay.mystagingwebsite.com
Subscriptions-core Library Version: 6.7.1
Subscription Statuses: wc-active: 11
wc-expired: 2
wc-pending-cancel: 2
wc-pending: 1
wc-on-hold: 2
wc-cancelled: 1

WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — New York

### Subscriptions by Payment Gateway ###

WooPayments: wc-active: 11
wc-cancelled: 1
wc-expired: 2
wc-on-hold: 1
wc-pending-cancel: 2

### Payment Gateway Support ###

WooPayments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

WooPayments (Bancontact): products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

WooPayments (giropay): products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

WooPayments (Sofort): products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

WooPayments (Przelewy24 (P24)): products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

WooPayments (iDEAL): products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

WooPayments (EPS): products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-10 03:20:46 +06:00
Options: ✔
Notes: 203
Onboarding: completed

### Action Scheduler ###

Complete: 2,514
Oldest: 2024-02-08 02:03:58 +0000
Newest: 2024-03-09 19:17:35 +0000

Pending: 18
Oldest: 2024-03-09 19:19:19 +0000
Newest: 2024-12-31 21:00:00 +0000

Failed: 14
Oldest: 2023-04-02 05:55:43 +0000
Newest: 2024-03-06 14:58:13 +0000

Canceled: 21
Oldest: 2024-02-11 15:20:14 +0000
Newest: -0001-11-30 00:00:00 +0000

### Status report information ###

Generated at: 2024-03-10 01:18:29 +06:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment] 2024-03-18 10:55
Re-opening as this was an issue requested to be created here p1709813763885109-slack-C7U3Y3VMY

**Comment by vedanshujain** [comment] 2024-03-21 08:49
Marking this normal prio for now as this seems like a setup issue, but will increase the priority and impact if we get more reports about this same issuel.

**Comment by barryhughes** [comment] 2024-03-26 20:23
I can basically replicate this when testing with Gmail (noting that I have no special email config in place on my test site). 

However, I still don't think this is a bug: WooCommerce seems to be doing all it can here and there are no obvious errors or bugs (tracing along, I can verify the email is actually sent in the sense it is ultimately passed to `wp_mail` and a `(bool) true` is generated). This is what we expect, given the note that email logging plugins also observe the email being dispatched.

📰 [woo.com/posts/email-sender-requirements](https://woo.com/posts/email-sender-requirements/)

@shohanhossainnab can you confirm everything needed to satisfy the recent Gmail/Yahoo email changes described in the above link have been put in place? I think that is a good starting point here (because it seems like the problem is happening at a level we do not control and cannot see).

**Comment by shohanhossainnab** [comment] 2024-03-27 08:17
>can you confirm everything needed to satisfy the recent Gmail/Yahoo email changes described in the above link have been put in place?

Nope. I tested with all the default settings and not the special email config, but I agree with what you mentioned here. This indeed seems like the problem is at a level we do not control.

**Comment by barryhughes** [comment] 2024-03-27 16:33
Cool.

In that case I think I'll close this issue: if it's apparent that there is still an active problem even if all those requirements (in terms of sender domain and address, SPF, DKIM etc) are in place that we can absolutely re-open and think about what else we might do.

Right now, though, this looks like an email config issue.

**Closed as completed by barryhughes** 2024-03-27 16:33 UTC
Labels: Bug, Email, Shopper Account/Management, needs: triage feedback
