### ISSUE TITLE
[Enhancement]: Extend recalculate_coupons method

### ISSUE THREAD

**Issue by 2mkabir** [woothemes/woocommerce#38509] opened 2023-05-29 23:03 UTC
### Describe the solution you'd like

Hi
In file:
`woocommerce/includes/abstracts/abstract-wc-order.php`
In method:
`recalculate_coupons`

Probably recalculate_coupons() method has needed to use in this actions:
```
'woocommerce_order_before_calculate_totals'
'woocommerce_order_after_calculate_totals'
```
But it gives infinite loop error because at the end of it calling calculate_totals().
For solving this problem i think this method need an argument like this:
```
public function recalculate_coupons( $calculate_totals = true ) {
 .
 .
 .
 if($calculate_totals) {
  $this->calculate_totals(true);
 }
}
```

**Comment by rrennick** [comment] 2023-09-25 18:18
Hi @2mkabir, thanks for creating the issue. Could you provide us with the steps necessary to reproduce the infinte loop?

**Comment by 2mkabir** [comment] 2023-09-25 23:39
Hi @rrennick 
I have infinite loop error with a thing like this:
```
add_action('woocommerce_order_before_calculate_totals', 'on_update_order', 10, 2);

function on_update_order($and_taxes, $order) {
    $discounts = new WC_Discounts( $order );
    $order->recalculate_coupons($order, $discounts);
}
```
I have created a plugin for Woocommerce which led me to find this problem. You can see this in here:
https://github.com/2mkabir/auto-coupon-for-woocommerce/blob/7cb8c0f1e400daeb0f878afe2550e400d3ec354a/woocommerce-auto-coupon.php#L117
If you look carefully at my code, Anyway I solved the problem in an unconventional way.

It is better to solve this problem in the right way
For solving this problem I think `recalculate_coupons` method need an argument like this:

```
public function recalculate_coupons( $calculate_totals = true ) {
 .
 .
 .
 if($calculate_totals) {
  $this->calculate_totals(true);
 }
}
```
If my solution is ok please let me for create a pull request for it.

**Comment by rrennick** [comment] 2023-09-26 13:56
@2mkabir Thanks for providing the snippet. This kind of endless loop can be created by adding a hook that calls a function that leads to that hook being called. You can avoid yours with the following changes:

```
add_action('woocommerce_order_before_calculate_totals', 'on_update_order', 10, 2);

function on_update_order($and_taxes, $order) {
    remove_action( 'woocommerce_order_before_calculate_totals', 'on_update_order', 10, 2 );
    $discounts = new WC_Discounts( $order );
    $order->recalculate_coupons($order, $discounts);
    add_action('woocommerce_order_before_calculate_totals', 'on_update_order', 10, 2);
}
```

I'll close this as a question because given the nature of the way the WP hooks & filters system works, endless loops can be created with most hooks/filters. If you have any questions, let us know.

**Closed as completed by rrennick** 2023-09-26 13:56 UTC
Labels: Store Marketing, needs: triage feedback, type: question, type: community contribution
