### ISSUE TITLE
pasting to product info

### ISSUE THREAD

**Issue by kwarren1086** [woothemes/woocommerce#7707] opened 2015-03-12 18:49 UTC
Every time I try to us paste since new word press update now it deletes all my product description and wont return it. Any guidance? As it leave me with lots of repetitive typing to do now.

**Comment by mikejolley** [comment] 2015-03-12 18:54
I have no idea what you're explaining here. Can you explain with screenshots perhaps?

**Comment by kwarren1086** [comment] 2015-03-12 19:04
[image: Inline image 1]
[image: Inline image 2]
[image: Inline image 3]
[image: Inline image 4]

**Comment by mikejolley** [comment] 2015-03-12 19:06
No images come though - come to github and upload the images..

**Comment by kwarren1086** [comment] 2015-03-12 19:09
![image](https://cloud.githubusercontent.com/assets/11446216/6625949/c2dafae4-c8c9-11e4-8ca2-84882f92fdec.png)

**Comment by kwarren1086** [comment] 2015-03-12 19:09
![image](https://cloud.githubusercontent.com/assets/11446216/6625960/d3f70282-c8c9-11e4-82b1-0fe13d988d45.png)

**Comment by kwarren1086** [comment] 2015-03-12 19:10
![image](https://cloud.githubusercontent.com/assets/11446216/6625963/de16a57e-c8c9-11e4-9e88-39b7f844bd28.png)

**Comment by kwarren1086** [comment] 2015-03-12 19:11
![image](https://cloud.githubusercontent.com/assets/11446216/6625992/08b00ac8-c8ca-11e4-9d94-50a7c581f700.png)

**Comment by kwarren1086** [comment] 2015-03-12 19:12
As you can see it is now gone and when I click undo it deletes all info.

**Comment by mikejolley** [comment] 2015-03-12 19:13
Still not really clear what you're doing, but I'm going to guess the same thing happens when you edit a 'post'?

**Comment by kwarren1086** [comment] 2015-03-12 19:16
The highlighted you see in picture 2 is on 1,300 products under the product description I have loaded on there. I am trying to copy and paste the correct paragraph to each product but since the new WordPress update for some reason when I do the same process I have been using for a year now it just erases it.

**Comment by kwarren1086** [comment] 2015-03-12 19:17
Picture 1 shows screen just opened
Picture 2 highlight text
Picture 3: select Paste (to paste info from notepad)
Picture 4: selected area now gone and if you click undo it erases all information

**Comment by mikejolley** [comment] 2015-03-12 19:22
When you paste, it will paste whats on your clipboard over whatever is selected. Thats normal behaviour, and not something unique to WordPress or WooCommerce.

Closing as this is not a WooCommerce issue.

**Comment by kwarren1086** [comment] 2015-03-12 19:22
The issue is only happening in woocommerce

**Comment by mikejolley** [comment] 2015-03-12 19:24
That description box is powered by WordPress. Its the same for posts and pages.

**Comment by kwarren1086** [comment] 2015-03-12 19:26
Im not sure I understand you as the issue is only happening to my woocommerce products via the woocommerce plug in

**Comment by kwarren1086** [comment] 2015-03-12 19:27
I clicked help for the woocommerce issue and it directed me here.

**Comment by kwarren1086** [comment] 2015-03-12 19:28
* Page Yield is an estimated number of standard pages that can be printed with one cartridge, usually measured at 5% page usage. 5% usage is described as a standard 8.5 x 11 inch page with a light letterhead, address and three paragraphs of text double spaced. If your print is mixed with graphics or webpage information your page coverage is closer to 15% and will affect the number of pages printed on Epson printers with each cartridge producing much less. If you are printing photos on your Epson printer your page coverage is closer to 150% and the number of printed photos will be much less than the amount of pages you would be able to print if you were just printing standard text style documents.

**Comment by kwarren1086** [comment] 2015-03-12 19:29
That is what is on my clipboard

**Comment by mikejolley** [comment] 2015-03-12 19:29
The editor is part of WordPress, not WooCommerce. Create a post/page and you will see its identical.

**Comment by kwarren1086** [comment] 2015-03-12 19:29
I am under Woocommerce products editing my woocommmerce product description and when I paste from my clipboard it deletes the information

**Comment by kwarren1086** [comment] 2015-03-12 19:30
I understand that but why is it only deleting it on my products and not blogs

**Comment by mikejolley** [comment] 2015-03-12 19:31
Switch to the 'text' editor if you think the visual editor is breaking this. This is not a WooCommerce issue either way, because as I said, WordPress powers the content editor.

**Comment by ChromeOrange** [comment] 2015-03-12 23:10
Hi @kwarren1086 

Just to expand on what Mike has been saying. If this was an issue with WooCommerce we would be swamped with tickets and issues, there are over 1,000,000 active WooCommerce installs out there.

WooCommerce products are a standard WordPress custom post type. The chances are this issue is being caused by a conflict somewhere or by a hosting issue

Step 1. Deactivate all of your plugins except WooCommerce and swap your theme to Twenty Twelve. Does the issue still happen?

Step 2. Open the console and re-edit a product, do any errors show up? 

How to use the Google Chrome console : 
https://developers.google.com/chrome-developer-tools/docs/console
How to use FireBug for FireFox : 
https://addons.mozilla.org/en-us/firefox/addon/firebug/
https://getfirebug.com/faq/

Step 3. Look at your server error logs - are there any error in there that match the time you tried to update?

If you are still having the issue after all this and have not found out why then install this https://wordpress.org/plugins/wp-max-submit-protect/ and re-edit a product to see if there are any warnings (they will popup when you hit update)

**Closed** 2015-03-13 09:50 UTC
