### ISSUE TITLE
error activating the plugin

### ISSUE THREAD

**Issue by osmarycarrillo** [woothemes/woocommerce#35504] opened 2022-11-07 13:28 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

when I activate the plugin, I can't edit my pages
I use the divi builder

### Expected behavior

I would like help on what to do about it

### Actual behavior

when I try to edit I get the page not found message, error 404, and it redirects me to the entries section

### Steps to reproduce

1. activate the plugin
2. I go to pages section
3. I click on edit
4. the 404 error appears

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://inefrancisconi.com
Site address (URL): https://inefrancisconi.com
WC Version: 7.0.1
REST API Version: ✔ 7.0.1
WC Blocks Version: ✔ 8.5.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.11
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.71.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.7.39-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.1
WC Database Prefix: wp_
Tamaño total de la base de datos: 37.06MB
Tamaño de los datos de la base de datos: 34.18MB
Tamaño del índice de la base de datos: 2.88MB
wp_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_actions: Datos: 0.05MB + Índice: 0.11MB + Motor InnoDB
wp_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_logs: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wp_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_comments: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_gla_budget_recommendations: Datos: 0.22MB + Índice: 0.14MB + Motor InnoDB
wp_gla_merchant_issues: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_gla_shipping_rates: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_gla_shipping_times: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_mailpoet_custom_fields: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_mailpoet_dynamic_segment_filters: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_mailpoet_feature_flags: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_mailpoet_forms: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_mailpoet_log: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_mailpoet_newsletters: Datos: 0.03MB + Índice: 0.03MB + Motor InnoDB
wp_mailpoet_newsletter_links: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_mailpoet_newsletter_option: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_mailpoet_newsletter_option_fields: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_mailpoet_newsletter_posts: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_mailpoet_newsletter_segment: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_mailpoet_newsletter_templates: Datos: 2.52MB + Índice: 0.00MB + Motor InnoDB
wp_mailpoet_scheduled_tasks: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_mailpoet_scheduled_task_subscribers: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_mailpoet_segments: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_mailpoet_sending_queues: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_mailpoet_settings: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_mailpoet_statistics_bounces: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_mailpoet_statistics_clicks: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_mailpoet_statistics_forms: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_mailpoet_statistics_newsletters: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_mailpoet_statistics_opens: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
wp_mailpoet_statistics_unsubscribes: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_mailpoet_stats_notifications: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_mailpoet_subscribers: Datos: 0.02MB + Índice: 0.13MB + Motor InnoDB
wp_mailpoet_subscriber_custom_field: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_mailpoet_subscriber_ips: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_mailpoet_subscriber_segment: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_mailpoet_subscriber_tag: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_mailpoet_tags: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_mailpoet_user_agents: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_mailpoet_user_flags: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_options: Datos: 3.02MB + Índice: 0.08MB + Motor InnoDB
wp_postmeta: Datos: 1.31MB + Índice: 0.11MB + Motor InnoDB
wp_posts: Datos: 25.41MB + Índice: 0.22MB + Motor InnoDB
wp_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_term_relationships: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_usermeta: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
wp_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_admin_notes: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
wp_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_product_attributes_lookup: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB

### Post Type Counts ###

attachment: 92
custom_css: 1
customize_changeset: 19
et_footer_layout: 2
et_pb_layout: 21
et_template: 3
et_theme_builder: 3
mailpoet_page: 1
nav_menu_item: 9
page: 22
post: 2
product: 7
revision: 933
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

UpdraftPlus - Backup/Restore: por UpdraftPlus.Com
DavidAnderson – 1.22.23

Mercado Pago payments for WooCommerce: por Mercado Pago – 6.3.1
WooCommerce PayPal Payments: por WooCommerce – 1.9.5
WooCommerce: por Automattic – 7.0.1

### Must Use Plugins (1) ###

WordPress automation by Installatron: por  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: ARS ($)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Base de la tienda: #1191 - /escuela/
Carrito: ❌ La página no contiene el shortcode [woocommerce_cart] o el bloque woocommerce/cart.
Finalizar compra: #540 - /finalizar-compra/
Mi cuenta: #541 - /mi-cuenta/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Divi
Version: 4.19.0
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: AR
WooCommerce currency supported: –
Advanced Card Processing available in country: –
Pay Later messaging available in country: –
Webhook status: –
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-07 21:04:49 +00:00
Options: ✔
Notes: 45
Onboarding: completed

### Action Scheduler ###

Completo: 70
Oldest: 2022-10-10 21:04:52 +0000
Newest: 2022-11-07 13:25:47 +0000

Pendiente: 2
Oldest: 2022-11-07 13:26:46 +0000
Newest: 2022-11-07 14:00:36 +0000

Cancelada: 1
Oldest: 2022-10-28 12:36:40 +0000
Newest: 2022-10-28 12:36:40 +0000

### Status report information ###

Generated at: 2022-11-07 13:26:36 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment] 2022-11-08 13:21
Hi @osmarycarrillo,
Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using the WooCommerce 7.0.1 version, PHP 8.0.25 version, and WordPress 6.1 version. 

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/200512806-33c38597-f98a-4ee6-a4a6-11a5742bcbd4.mp4


Please provide us with more details and any additional steps required to repro this issue which may help us evaluate it further.

**Comment by lsinger** [comment] 2023-03-27 09:08
We have not been able to reproduce this issue and have not heard from you. We are closing this issue for now. If we missed something, please leave a comment and we will take a second look.

**Closed as completed by lsinger** 2023-03-27 09:08 UTC
Labels: Bug, plugin: woocommerce, type: community contribution
