### ISSUE TITLE
wc_logout_url() problem

### ISSUE THREAD

**Issue by ghost** [woothemes/woocommerce#49750] opened 2024-07-22 08:17 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I want redirect the user after logout.
According to the documentation, I created the following code:
```
$current_url = esc_url( home_url( $_SERVER['REQUEST_URI'] ) );
<a href="<?php echo esc_url( wc_logout_url( $current_url ) ); ?>">logout</a>
```
And this code created a link like this: https://site.com/product/hi/customer-logout/?_wpnonce=03350da55b

But by clicking on it, the user is not logged out of the site and goes to the 404 page!
I think this function has a bug.

### Expected behavior

logout and redirect

### Actual behavior

Just a 404 error, didn't even logout

### Steps to reproduce

-

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.1.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.6
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.17-MariaDB-cll-lve
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 12
eos_dyn_content: 1
page: 9
post: 2
product: 8
product_variation: 2
revision: 15
shop_coupon: 1
shop_order: 153
wp_global_styles: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

Query Monitor: by John Blackbourn – 3.16.3
افزونه All In One WP Security: by تیم All In One WP Security & Firewall – 5.3.1
کاپیتان هوکس: by dbeja – 1.0.1
Content No Cache: by Jose Mortellaro – 0.1.1
احراز: by مسعود مهدیان – 3.2.1
درگاه پرداخت پیمنت ۴: by Payment4.com
امیرحسین تقی زاده – 2.2.1

ووکامرس فارسی: by ووکامرس فارسی – 7.1.6
کیف پول: by StandaloneTech – 1.5.5
ووکامرس: by اتوماتیک – 9.1.2
WP Crontrol: by John Blackbourn – 1.16.3
آرش کمانگیر - درگاه های ووکامرس - همه درگاه ها یکجا: by گروه برنامه نویسی آرش کمانگیر – 3.0.7

### Inactive Plugins (6) ###

Advanced Database Cleaner PRO: by Younes JFR. – 3.2.9
Custom Permalinks: by Sami Ahmed Siddiqui – 2.5.2
Permalink Manager Lite: by Maciej Bis – 2.4.3.4
Protect external download links: by Javad Ehteshami – 3.5.6
RTL license management: by RTL-Theme – 1.7.7
User Switching: by John Blackbourn & contributors – 1.7.3

### Dropin Plugins () ###

db.php: Query Monitor Database Class (Drop-in)
maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: IRT (تومان)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: ✔

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 901 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0 (update to version 1.2 is available)
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: twentytwentyfour/woocommerce/content-single-product.php
/home3/sitiii/public_html/wp-content/plugins/woocommerce/templates/block-notices/error.php
/home3/sitiii/public_html/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/home3/sitiii/public_html/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 1403-05-01 09:33:08 +03:30
Options: ✔
Notes: 84
Onboarding: skipped

### Action Scheduler ###

Complete: 119
Oldest: 2024-06-21 12:41:25 +0000
Newest: 2024-07-22 02:34:51 +0000

Failed: 13
Oldest: 2024-02-16 09:45:49 +0000
Newest: 2024-07-12 05:08:29 +0000

Pending: 1
Oldest: 2024-07-22 09:28:54 +0000
Newest: 2024-07-22 09:28:54 +0000


### Status report information ###

Generated at: 2024-07-22 11:37:14 +03:30
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment] 2024-07-22 13:28
Hi @themonoor 

This one will be fixed by https://github.com/woocommerce/woocommerce/pull/49605 and I think is a duplicate of https://github.com/woocommerce/woocommerce/issues/25288 so I'll close this.

Thanks for the report.

**Closed as completed by mikejolley** 2024-07-22 13:28 UTC
Labels: Bug, Shopper Account/Management, type: community contribution, Rubik
