### ISSUE TITLE
Product Collection blocks extends beyond the canvas when the Responsive toggle is enabled

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#47789] opened 2024-05-24 07:23 UTC
I noticed the PC block in the Grid layout extends well beyond the canvas when the Responsive toggle is enabled and the block is placed inside a Row. Turning it off fixes the layout issue.

**Toggle on**

<img width="1377" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/2e678c8d-d2c5-45b8-956e-ff4d751a3bc2">

**Toggle off**

<img width="1373" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/d0fbcfb1-c58f-4c18-80bb-c92d1131c6e9">

cc @kmanijak

**Comment by kmanijak** [comment] 2024-05-24 09:15
@jarekmorawski, mind sharing a **list view** of the blocks structure? I can't reproduce it and I'm wondering if that's because of some specific block combination (e.g. nested Group / Column / Row and not Row by itself).

**Comment by jarekmorawski** [comment] 2024-05-24 13:47
Sure thing! Here's a video. While recording it, I realized the problem is really about the relationship between the `Responsive` and the `Inner blocks use content width` toggles. When one works, the other doesn't.

There is also something wrong with the block's bottom edge. As you can see in the video, it overlaps with the footer template part. This is the first time I'm experiencing this problem, so it could be a recent change.

https://github.com/woocommerce/woocommerce/assets/79307566/d6add5e4-d0bb-4b87-b959-bcf1326d6613

**Comment by ObliviousHarmony** [comment] 2024-09-17 01:05
Hello @jarekmorawski,

I am unable to reproduce this. I've tried the following with different variations of columns, the responsive checkbox, and the inner block width.

- Row > Stack > Product Collection
- Group > Product Collection
  - I also tested different variations of pairing with the Group's inner block width setting.

**Comment by imanish003** [comment] 2024-09-22 09:49
I was unable to reproduce this issue as well. It's possible that it may have been resolved while working on other tasks. To help us investigate further, could you please provide a specific code snippet or block configuration that consistently reproduces the issue? This would allow us to examine any particular parent block settings or combinations that might be causing the problem.

Given that we currently can't reproduce the issue, I am closing this issue for now. However, we can always reopen it if we will be able to reproduce it again 🙇‍♂️

**Closed as completed by imanish003** 2024-09-22 09:49 UTC
Labels: Bug, Kirigami, block: product collection
