### ISSUE TITLE
[GlobalStep] “Critical error” notification displayed on clicking “Import products” button on “Personalize my store” page.

### ISSUE THREAD

**Issue by gglobalstep** [woothemes/woocommerce#33350] opened 2022-06-08 14:44 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

“Critical error” notification displayed on clicking “Import products” button on “Personalize my store” page.

### Expected behavior

After clicking “Import products” button 18 Sample products should be imported without any critical error.

### Actual behavior

“Critical error” notification displayed on clicking “Import products” button on “Personalize my store” page.

### Steps to reproduce

1. Create any test site using JN site.
2. Install and activate WooCommerce 6.6.0-rc.3.
3. Install WooCommerce Admin Test Helper
4. Go to Tools > WCA Test Helper > Experiments
5. Disable both woocommerce_products_task_layout_stacked and woocommerce_products_task_layout_card experiment
6. Make sure there are no products in store (if there are in trash, empty them)
7. Go to Appearance task "/wp-admin/admin.php?page=wc-admin&task=appearance"
8. Click on "Import products" button
5. Observe that “Critical error” notification displayed on clicking “Import products” button on “Personalize my store” page.

### Note:
1. After clicking “Import products” button “Critical error” notification displayed and 18 Sample products are imported.

### Instruction Link:
https://github.com/woocommerce/woocommerce/wiki/Release-Testing-Instructions-WooCommerce-6.6#add-experimental-sample-products-task-32960-32977-32815

### Screenshot:

![#33350](https://user-images.githubusercontent.com/41110392/172646406-e7368e1b-30d8-46ee-8d7e-a20904176367.jpg)

### WordPress Environment

Woocommerce Version: 
WooCommerce: 6.6.0-rc.3
Wordpress version: 6.0

PC:
Windows 10
Chrome(Version 102.0.5005.63) 
Firefox(Version 101.0)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 6.6.0
REST API Version: ✔ 6.6.0
WC Blocks Version: ✔ 7.6.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.53 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.29
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.6.0
WC Database Prefix: wp_
Total Database Size: 5.18MB
Database Data Size: 3.68MB
Database Index Size: 1.50MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.44MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 33
page: 7
post: 2
product: 18
product_variation: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.9.0
Companion Plugin: by Osk – 1.26
Jetpack: by Automattic – 11.0
WooCommerce Admin Test Helper: by WooCommerce – 0.7.5
WooCommerce: by Automattic – 6.6.0-rc.3

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.2.4
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Two
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-06-09 10:57:51 +00:00
Options: ✔
Notes: 37
Onboarding: skipped

### Action Scheduler ###

Complete: 212
Oldest: 2022-06-08 10:59:16 +0000
Newest: 2022-06-08 14:38:09 +0000

Pending: 1
Oldest: 2022-06-09 10:59:16 +0000
Newest: 2022-06-09 10:59:16 +0000

### Status report information ###

Generated at: 2022-06-08 14:45:11 +00:00
`

</details>

**Comment by tammullen** [comment] 2022-06-08 16:01
Just noting I was only able to reproduce this so far with Query Monitor installed.

It also is happening with 6.5.1 & Query Monitor

Full error is

2022-06-08T13:20:55+00:00 CRITICAL Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /public/wp-content/plugins/query-monitor/classes/Backtrace.php on line 487

Failed to load resource: the server responded with a status of 500 ()
/wp-json/wc-admin/onboarding/tasks/import_sample_products?_locale=user

**Comment by chihsuan** [comment] 2022-06-09 04:25
> Just noting I was only able to reproduce this so far with Query Monitor installed.

I was also able to reproduce this with `Query Monitor` installed.

> 2022-06-08T13:20:55+00:00 CRITICAL Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /public/wp-content/plugins/query-monitor/classes/Backtrace.php on line 487

It looks like it's not something we could fix because it works fine when we load a few products in new product experiments or deactivate `Query Monitor`.

**Comment by chihsuan** [comment] 2022-06-09 04:48
I found a similar issue reported in query-monitor.
- https://github.com/johnbillion/query-monitor/issues/663

> Yeah this is due to the amount of data that QM collects and causes memory exhaustion. You can get around this problem though: https://wordpress.org/plugins/query-monitor/#can%20i%20prevent%20query%20monitor%20from%20collecting%20data%20during%20long-running%20requests%3F

**Comment by chihsuan** [comment] 2022-06-09 04:58
I'm going to close this since there isn't really anything we can do to resolve it.

**Closed as not planned by chihsuan** 2022-06-09 04:58 UTC
Labels: Bug, plugin: woocommerce
