### ISSUE TITLE
 Wordpress and the Source Code ACSII Problem

### ISSUE THREAD

**Issue by JuliusCassy** [woothemes/woocommerce#30720] opened 2021-09-16 02:24 UTC
Hello Github :) (Im a Noob)
I have the problem that I cannot display an ACSII Art on my source code
i have tried a lot for over 10 hours i search and find nothing

i was heavily inspired by other websites

I have the acsii Art (Its A Hamster) but how do I blend it into my source codes? better said where exactly?

I have
Tried /home/WebsiteName/wp-content/themes/astra/header.php with no success
put the code in diffrent places with no success

and even try some options like
"<-- hamster -->"
<-- hamster -->
`
    `

nothing really works :( pls help me guys

**Comment by sanzeeb3** [comment] 2021-09-16 09:29
Add in your theme's functions.php


```
add_action( 'wp_head', function() {
	?>
		<art>
				          
		    (>\---/<)
		    ,'     `.
		   /  q   p  \
		  (  >(_Y_)<  )
		   >-' `-' `-<-.
		  /  _.== ,=.,- \
		 /,    )`  '(    )
		; `._.'      `--<

		</art>
	<?php
}, -100 );
```

**Comment by juliaamosova** [comment] 2021-09-18 19:33
Hi @JustJiggi,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by juliaamosova** 2021-09-18 19:33 UTC
