### ISSUE TITLE
MariaDB Galera Issue

### ISSUE THREAD

**Issue by rsidhaarth** [woothemes/woocommerce#30744] opened 2021-09-21 02:54 UTC
Hi Team,

I have used ProxySQL and MariaDB Galera Cluster to connect the DB. Whereas when we connect the DB via proxy SQL, the site is not working as intended.

All the pages are working well, except the checkout page. As soon we click to proceed to checkout, nothing happens. It just moves to the header of the page. And in the admin orders sections, we just see the order number and no other info is being entered.

Is this a known issue? Does WooCommerce support MariaDB cluster with ProxySQL?

Thanks

**Comment by rodelgc** [comment] 2021-09-23 11:50
Hi @rsidhaarth ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by rodelgc** 2021-09-23 11:50 UTC
Labels: type: support request
