### ISSUE TITLE
Disabling Telemetry

### ISSUE THREAD

**Issue by szepeviktor** [woothemes/woocommerce#31093] opened 2021-11-05 15:21 UTC
Hello! I have sad news. Unused features get disabled in my WC installations.

Is it the proper way to use `woocommerce_rest_api_get_rest_namespaces` filter to disable Telemetry?

**Comment by tammullen** [comment] 2021-11-05 21:40
Hi @szepeviktor ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by tammullen** 2021-11-05 21:40 UTC

**Comment by szepeviktor** [comment] 2021-11-05 23:32
I agree Tim.
A yes or no aswer would make me happy.
