### ISSUE TITLE
WooCommerce plugin update shutting down website

### ISSUE THREAD

**Issue by Nubianqween4** [woothemes/woocommerce#48691] opened 2024-06-20 16:30 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

My website shuts down after woocommerce  plugin update. Bigscoots recommended I reach out to you and provided the info you needed. Please resolve so Ican get access again. Thank you

### Expected behavior

Website should still be available after update

### Actual behavior

Website unavailable unless bigscoots reverts back to previous update. 

### Steps to reproduce

.

### WordPress Environment

PHP Fatal error:  Uncaught Error: Class 'WC_Legacy_API' not found in /home/promisei/public_html/wp-content/plugins/woocommerce/includes/class-wc-api.php:19
Stack trace:
#0 /home/promisei/public_html/wp-content/plugins/woocommerce/includes/class-wc-autoloader.php(54): include_once()
#1 /home/promisei/public_html/wp-content/plugins/woocommerce/includes/class-wc-autoloader.php(98): WC_Autoloader->load_file('/home/promisei/...')
#2 [internal function]: WC_Autoloader->autoload('wc_api')
#3 [internal function]: spl_autoload_call('WC_API')
#4 /home/promisei/public_html/wp-content/plugins/woocommerce/src/Internal/Utilities/LegacyRestApiStub.php(61): class_exists('WC_API')
#5 [internal function]: Automattic\WooCommerce\Internal\Utilities\LegacyRestApiStub::parse_legacy_rest_api_request(Object(WP))
#6 /home/promisei/public_html/wp-content/plugins/woocommerce/src/Internal/Traits/AccessiblePrivateMethods.php(178): call_user_func_array(Array, Array)
#7 /home/promisei/public_html/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\In in /home/promisei/public_html/wp-content/plugins/woocommerce/includes/class-wc-api.php on line 19

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment] 2024-06-21 20:56
Duplicate of https://github.com/woocommerce/woocommerce/issues/48587

**Closed as completed by tammullen** 2024-06-21 20:56 UTC
Labels: Bug, type: community contribution
