### ISSUE TITLE
[COT] Cancelling an order does not restock the products

### ISSUE THREAD

**Issue by AleedaGS** [woothemes/woocommerce#38401] opened 2023-05-22 19:36 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After upgrading to COT and using the new orders table, when the order status is changed to Cancelled the products are not returned to inventory

### Expected behavior

In our current live store, when an order is cancelled the products are returned to stock

### Actual behavior

After upgrading the HPOS: When an order is changed from any status to cancelled the products are not returned to inventory

### Steps to reproduce

Create a new order in Processing or On Hold status
Change the order to Cancelled

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://woocommerce-933860-3492637.cloudwaysapps.com
Site address (URL): https://woocommerce-933860-3492637.cloudwaysapps.com
WC Version: 7.7.0
REST API Version: ✔ 7.7.0
WC Blocks Version: ✔ 10.0.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: ❌ 6.2 - There is a newer version of WordPress available (6.2.2)
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.57 (Debian)
PHP Version: 8.0.28
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.20-MariaDB-1:10.4.20+maria~buster-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.7.0
WC Database Prefix: wp_
Total Database Size: 5211.89MB
Database Data Size: 2654.72MB
Database Index Size: 2557.17MB
wp_woocommerce_sessions: Data: 44.56MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 71.61MB + Index: 36.61MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 636.00MB + Index: 573.98MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 204.77MB + Index: 159.33MB + Engine InnoDB
wp_ajaxsearchpro: Data: 1.48MB + Index: 0.00MB + Engine InnoDB
wp_ajaxsearchpro_priorities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ajaxsearchpro_statistics: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_asp_index: Data: 24.58MB + Index: 54.23MB + Engine InnoDB
wp_asp_synonyms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.19MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 1.52MB + Index: 1.91MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.16MB + Index: 0.25MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 13.52MB + Index: 18.55MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 47.58MB + Index: 39.16MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.27MB + Index: 0.14MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bv_ip_store: Data: 0.48MB + Index: 0.36MB + Engine InnoDB
wp_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwf_contact: Data: 1.52MB + Index: 0.72MB + Engine InnoDB
wp_bwf_contact_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwf_wc_customers: Data: 2.52MB + Index: 0.17MB + Engine InnoDB
wp_cart_notices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cocart_carts: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 186.73MB + Index: 94.33MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_submissions: Data: 2.52MB + Index: 3.69MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.44MB + Index: 0.88MB + Engine InnoDB
wp_e_submissions_values: Data: 1.52MB + Index: 1.86MB + Engine InnoDB
wp_facetwp_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_facetwp_index: Data: 0.42MB + Index: 0.55MB + Engine InnoDB
wp_gs_bin_category_map: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_gs_quick_shop_lists: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jet_smart_filters_indexer: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mpesa_trx: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 15.03MB + Index: 4.34MB + Engine InnoDB
wp_pmxe_exports: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_files: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 685.91MB + Index: 603.89MB + Engine InnoDB
wp_posts: Data: 137.36MB + Index: 23.06MB + Engine InnoDB
wp_re_lat_lng: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.19MB + Index: 0.25MB + Engine InnoDB
wp_terms: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 167.69MB + Index: 188.55MB + Engine InnoDB
wp_users: Data: 2.52MB + Index: 2.55MB + Engine InnoDB
wp_usin_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usin_user_data: Data: 1.52MB + Index: 0.55MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_orders: Data: 22.56MB + Index: 22.61MB + Engine InnoDB
wp_wc_orders_meta: Data: 283.86MB + Index: 675.98MB + Engine InnoDB
wp_wc_order_addresses: Data: 15.55MB + Index: 23.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 12.52MB + Index: 7.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 3.22MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.34MB + Index: 0.33MB + Engine InnoDB
wp_wdr_rules: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wfco_report_views: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfob_stats: Data: 0.42MB + Index: 0.61MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
wp_woocommerce_pesapal_order_tracking_data: Data: 1.52MB + Index: 2.52MB + Engine InnoDB
wp_wpfb_post_templates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfb_reviews: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wpfb_total_averages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpie_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_action_history: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_xsg_sitemap_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcbm_badge_rules_associations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 18.42MB + Index: 5.42MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.36MB + Index: 0.55MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.28MB + Index: 0.36MB + Engine InnoDB
wp_yoast_seo_links: Data: 1.44MB + Index: 0.30MB + Engine InnoDB
wp_ywcdd_calendar: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_ywf_user_fund_log: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp__mpesa_data: Data: 4.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 32
acf-field-group: 9
astra-advanced-hook: 9
attachment: 8601
autosearch_template: 3
aw_workflow: 25
br_notice: 1
br_product_filter: 1
bsf-sidebar: 9
custom_css: 1
customize_changeset: 56
elementor_icons: 3
elementor_library: 61
gift_card: 60
itsec-dash-card: 14
itsec-dashboard: 2
jet-smart-filters: 1
nav_menu_item: 81
oembed_cache: 2
page: 50
post: 645
product: 5114
product_variation: 3005
product-feed: 1
re_preview_popup: 1
reactive_builder: 1
reactive_category: 2
reactive_grid: 17
reactive_layouts: 1
reactive_map_info: 1
reactive_map_marker: 1
revision: 24211
rmp_menu: 1
search-filter-widget: 1
shop_coupon: 2801
shop_order: 67285
shop_order_refund: 5917
usin_note: 676
view-template: 3
wc_order_status: 10
wfob_bump: 1
wp_global_styles: 1
wp-types-group: 1
wpzoom_rcb: 411
yith_carrier: 4
yith_proc_method: 5
yith_wcan_preset: 11
yith-wcbm-badge: 79
ywdpd_discount: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (80) ###

GS Stock Count Dashboard: by Greenspoon – 3.0.11
Greenspoon Back In Stock: by Greenspoon – 1.0.0
Greenspoon Quick Shop: by Greenspoon – 1.0.0
Registration Order Link for WooCommerce: by SkyVerge – 1.0.0
Admin Menu Editor Pro: by Janis Elsts – 2.19.3
Advanced Custom Fields PRO: by WP Engine – 6.1.6
Astra Pro: by Brainstorm Force – 4.1.4
AutomateWoo: by WooCommerce – 5.5.4
Caddy - Premium Edition: by Tribe Interactive – 1.6.6
Caddy - Smart Side Cart for WooCommerce: by Tribe Interactive – 1.8.2
CoCart - Headless ecommerce: by Sébastien Dumont – 3.8.1
Custom Fonts: by Brainstorm Force – 1.3.7
Disable Cart Fragments: by Optimocha – 2.2
Disable Bloat for WordPress & WooCommerce: by Disable Bloat – 3.2.4
Duplicate Page: by mndpsingh287 – 4.5.2
Dynamic.ooo - Dynamic Content for Elementor: by Dynamic.ooo – 2.9.3
Login/Signup Popup: by XootiX – 2.3
Ele Custom Skin Pro: by Dudaster.com – 3.2.4
Ele Custom Skin: by Dudaster.com – 3.1.7
Elementor Pro: by Elementor.com – 3.12.3
Elementor: by Elementor.com – 3.13.2
WooCommerce Headless with Vue.js: by Greenspoon – 1.0.0
Greenspoon Custom Functions: by Greenspoon – 1.0.0
Greenspoon Backorders: by Greenspoon – 1.0.6
Greenspoon JIT Order Dashboard: by Greenspoon – 1.0
Greenspoon Order Linking: by Greenspoon – 1.0.1
Greenspoon Split Orders - Integrations: by Greenspoon – 2.0
Greenspoon Mobile App Connector: by Greenspoon Development – 1.0
Heartbeat Control by WP Rocket: by WP Rocket – 2.0
Include Klaviyo for Elementor pro: by Thong Nguyen – 1.1.3
Instagram Feed Pro Developer: by Smash Balloon – 5.12.9
WooCommerce iPay/eLipa Payment Gateway Free: by iPay – 3.0.2
JetTabs For Elementor: by Crocoblock – 2.1.21
Klaviyo: by Klaviyo
Inc. – 3.0.12

MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall: by MalCare Security – 4.86
Metorik Helper: by Metorik – 1.6.2
PowerPack Pro for Elementor: by Team IdeaBox - PowerPack Elements – 2.9.18
Product Filter for WooCommerce: by XforWooCommerce – 8.3.0
Recipe Card Blocks for Gutenberg & Elementor: by WPZOOM – 3.2.2
Responsive Menu: by ExpressTech – 4.2.3
Sidebar Manager: by Brainstorm Force – 1.1.7
Simple-JWT-Login: by Nicu Micle – 3.5.0
WooCommerce Split Orders: by Vibe Agency – 1.5.0
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.39
SVG Support: by Benbodhi – 2.5.5
TheBunch KE Pesapal Woocommerce: by rixeo – 3.0.0
Ultimate Addons for Elementor: by Brainstorm Force – 1.36.15
User Switching: by John Blackbourn & contributors – 1.7.0
Users Insights: by Pexeto – 4.4.1
WooCommerce M-PESA Payments: by Digital Tangent – 2.2
WooCommerce Better Usability: by Moises Heberle – 1.0.55
Woo Discount Rules PRO 2.0: by Flycart – 2.5.4
Woo Discount Rules: by Flycart – 2.5.4
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.31
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.10.0
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.24
WooCommerce Multiple Customer Addresses: by Lagudi Domenico – 19.1
WooCommerce Order Status Manager: by SkyVerge – 1.14.0
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.5.2
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.46
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.18.1
WooCommerce Smart Coupons: by StoreApps – 7.6.0
WooCommerce: by Automattic – 7.7.0
Yoast SEO: by Team Yoast – 20.6
WP All Export Pro: by Soflyy – 1.8.3
WP Crontrol: by John Blackbourn & crontributors – 1.15.2
WP Google Review Slider: by LJ Apps – 12.3
WP Mail SMTP: by WP Mail SMTP – 3.8.0
WP Rollback: by GiveWP.com – 1.7.3
WP Search with Algolia Pro: by Pluginize – 1.0.0
WP Search with Algolia: by WebDevStudios – 2.5.1
WP All Export - WooCommerce Export Add-On Pro: by Soflyy – 1.0.6
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.9.8

YITH Infinite Scrolling Premium: by YITH – 1.5.1
YITH WooCommerce Account Funds Premium: by YITH – 1.4.10
YITH WooCommerce Badge Management Premium: by YITH – 2.9.0
YITH WooCommerce Checkout Manager: by YITH – 1.6.3
YITH WooCommerce Customize My Account Page Premium: by YITH – 3.20.0
YITH WooCommerce Delivery Date Premium: by YITH – 2.1.33
YITH WooCommerce Gift Cards Premium: by YITH – 3.3.8

### Inactive Plugins (32) ###

Advanced Database Cleaner PRO: by Younes JFR. – 3.1.7
Advanced Order Export For WooCommerce: by AlgolPlus – 3.4.0
Ajax Search Pro: by Ernest Marcinko – 4.22.4
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.5.7
Cellulant Tingg Checkout: by Cellulant Corporation – 1.1.0
Cloudflare: by Cloudflare
Inc. – 4.11.0

FacetWP: by FacetWP
LLC – 4.1.9

FacetWP - Cache: by FacetWP
LLC – 1.5.1

FacetWP - Elementor: by FacetWP
LLC – 1.6.7

FacetWP - Flyout menu: by FacetWP
LLC – 0.8.1

FunnelKit Order Bumps: by WooFunnels – 1.14.1
Greenspoon Bulk PDF: by Greenspoon – 1.0.0
Greenspoon D365 Business Central Integration: by Greenspoon – 1.0
Greenspoon DB table creation: by Greenspoon – 1.0.0
Greenspoon SMS Notifications: by Susan Maswili – 0.0.1
GS Bulk SMS: by gs – 1.0.0
GS Stock Count Dashboard: by Greenspoon – 3.0.10
Imagify: by Imagify – Optimize Images & Convert WebP – 2.1.1
ManageWP - Worker: by GoDaddy – 4.9.17
Query Monitor: by John Blackbourn – 3.12.2
Search Exclude: by QuadLayers – 2.0.0
Shipday Integration for WooCommerce: by  – 1.1.1
Woocommerce Add to cart Ajax for variable products: by Rishi Mehta - Rcreators Websolutions – 2.2
WooCommerce Google Analytics Pro: by SkyVerge – 2.0.1
WooCommerce Google Product Feed: by Ademti Software Ltd. – 10.6.0
WooCommerce Product Table: by Barn2 Plugins – 2.9.2
WooCommerce Quick View Pro: by Barn2 Plugins – 1.6.8
WP All Import - User Import Add-On Pro: by Soflyy – 1.1.6
WP All Import - WooCommerce Import Add-On Pro: by Soflyy – 3.3.0
WP All Import Pro: by Soflyy – 4.7.2
YITH WooCommerce Quick View Premium: by YITH – 1.7.3
Zones Plugin: by Greenspoon – 1.0

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: db.php
object-cache.php: Object Cache Pro (Drop-in)

### Must Use Plugins (1) ###

Object Cache Pro (MU): by Rhubarb Group – 1.18.2

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: KES (KShs)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: ❌ Page not set
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Astra Child Theme
Version: 1.0.0
Author URL: http://wpastra.com/about/
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 4.1.3 – 4.1.5 is available
Parent Theme Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce Support: ✔

### Templates ###

Overrides: astra-child-theme/woocommerce/emails/customer-on-hold-order.php version 3.7.0 is out of date. The core version is 7.3.0
astra-child-theme/woocommerce/emails/customer-processing-order.php
astra-child-theme/woocommerce/emails/email-addresses.php
astra-child-theme/woocommerce/emails/email-customer-details.php
astra-child-theme/woocommerce/emails/email-footer.php version 3.7.0 is out of date. The core version is 7.4.0
astra-child-theme/woocommerce/emails/email-header.php version 4.0.0 is out of date. The core version is 7.4.0
astra-child-theme/woocommerce/emails/email-order-details.php
astra-child-theme/woocommerce/emails/email-order-items.php
astra-child-theme/woocommerce/emails/email-styles.php version 4.0.0 is out of date. The core version is 7.4.0
/home/933860.cloudwaysapps.com/pcpxvqgdsu/public_html/wp-content/plugins/easy-login-woocommerce//templates//xoo-el-wc-form-login.php version 4.1.0 is out of date. The core version is 7.0.1
astra-child-theme/woocommerce/loop/add-to-cart.php version - is out of date. The core version is 3.3.0
/home/933860.cloudwaysapps.com/pcpxvqgdsu/public_html/wp-content/plugins/easy-login-woocommerce//templates//xoo-el-wc-form-login.php version 4.1.0 is out of date. The core version is 7.0.1
astra-child-theme/woocommerce/myaccount/orders.php version 3.7.0 is out of date. The core version is 7.0.1

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-05-03 19:32:58 +03:00
Options: ✔
Notes: 105
Onboarding: completed

### Action Scheduler ###

Complete: 84
Oldest: 2023-05-22 15:57:07 +0000
Newest: 2023-05-22 19:34:02 +0000

Pending: 2
Oldest: 2023-05-22 19:35:06 +0000
Newest: 2023-05-23 12:00:19 +0000

Failed: 29
Oldest: 2023-02-22 12:54:03 +0000
Newest: 2023-05-20 08:01:47 +0000

### CoCart ###

Version: 3.8.1
Database Version: 3.8.1
Install Date: May 20
2023

Carts in Session: 3
Carts Active: 3 out of 3 in session.
Carts Expiring Soon: 0 out of 3 in session.
Carts Expired: 0 out of 3 in session.
Carts Source (by CoCart): 1
Carts Source (by Web): 1
Carts Source (by Other): 1

### Smart Coupons related settings ###

Number of coupons to show: 2
Number of characters in auto-generated coupon code: 
Valid order status for auto-generating coupon: processing
dispatch
completed
invoiced

Include tax in the amount of the generated gift card: no
Deduct credit/gift before doing tax calculations: no
Gift Card discount is inclusive of tax: no
Automatic deletion: no
Coupon emails: no
Printing coupons: yes
Sell gift cards at less price?: no
Use gift card applied in first subscription order for subsequent renewals until credit reaches zero: yes
Renewal orders should not generate coupons even when they include a product that issues coupons: no
Allow sending of coupons to others: no
Allow schedule sending of coupons?: no
Combine emails: no
Auto generated coupon email: no
Combined auto generated coupons email: no
Acknowledgement email: no
Enable taxes: yes
Prices entered with tax: yes
Rounding: yes
Display prices in the shop: incl
Display prices during cart and checkout: incl
Display tax totals: single
Enable the use of coupon codes: yes
Calculate coupon discounts sequentially: no
Account endpoints > Coupons: wc-smart-coupons

### Status report information ###

Generated at: 2023-05-22 22:34:09 +03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by AleedaGS** [comment] 2023-05-23 07:54
Managed to reproduce this again on a completely new install of WordPress with Woocommerce 7.7.0. The restock works before you turn on the HPOS feature. Once you turn on HPOS and migrate the orders and then set the data store to the Orders Table the restocking no longer works. My suspicion is that it has something to do with wc_reduce_stock_levels in wc-stock-functions.php

After HPOS:
<img width="293" alt="Screenshot 2023-05-23 at 11 04 36" src="https://github.com/woocommerce/woocommerce/assets/104348173/9b7defcf-d8e9-455d-97cb-b8de14b50270">

Before HPOS:
<img width="311" alt="Screenshot 2023-05-23 at 11 05 36" src="https://github.com/woocommerce/woocommerce/assets/104348173/12e02501-3e0a-4717-acb1-9d23cbb7b3c5">

**Comment by thisissandip** [comment] 2023-08-11 16:53
I cannot reproduce this with the version 8.1.0-dev

Screenshot:

![oiidX9.png](https://github.com/woocommerce/woocommerce/assets/69596988/8ce0792d-bbb9-4074-9ba5-ba179b45dcb9)

**Comment by jorgeatorres** [comment] 2023-10-10 11:10
Similar to @thisissandip, I can't replicate this with the latest WooCommerce. As such, I'm closing for now. Feel free to re-open @AleedaGS if this is still an issue or I've missed something.

**Closed as completed by jorgeatorres** 2023-10-10 11:10 UTC
Labels: Bug, type: community contribution
