### ISSUE TITLE
Schedule sales is not fliping back when the sale is over 

### ISSUE THREAD

**Issue by John-Schuster22** [woothemes/woocommerce#33186] opened 2022-05-25 00:16 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

 When the expiration date happens on a sale item instead of it going back to the retail price it stays on the sale price beyond the expiration. Meaning customers are getting on sale items well after they should be. We are able to fix it by removing the sales price and the dates and hitting upload but it should be automatic.

### Expected behavior

If we set up a sales price for same-day 5/24/22 and set it to end 5/24/22 we expect at midnight for the price to change back to the retail price

### Actual behavior

It does not switch over after the expiration date is hit

### Steps to reproduce

1.) Setup sales price
2.) Schedule it to end on the same day.
3.) Check product is showing the same price
4.) We do have a test product https://www.sarda.com/product/test-product/Schedule

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.sarda.com
Site address (URL): https://www.sarda.com
WC Version: 6.5.1
REST API Version: ✔ 6.5.1
WC Blocks Version: ✔ 7.4.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: ❌ 5.9.3 - There is a newer version of WordPress available (6.0)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.28
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.37-40-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.1
WC Database Prefix: 58n7nj1Ym_
Total Database Size: 733.95MB
Database Data Size: 515.61MB
Database Index Size: 218.34MB
58n7nj1Ym_woocommerce_sessions: Data: 4.02MB + Index: 0.08MB + Engine InnoDB
58n7nj1Ym_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
58n7nj1Ym_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
58n7nj1Ym_woocommerce_order_items: Data: 3.17MB + Index: 1.23MB + Engine InnoDB
58n7nj1Ym_woocommerce_order_itemmeta: Data: 15.16MB + Index: 11.42MB + Engine InnoDB
58n7nj1Ym_woocommerce_tax_rates: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
58n7nj1Ym_woocommerce_tax_rate_locations: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
58n7nj1Ym_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
58n7nj1Ym_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
58n7nj1Ym_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_actionscheduler_actions: Data: 33.08MB + Index: 28.27MB + Engine InnoDB
58n7nj1Ym_actionscheduler_claims: Data: 0.22MB + Index: 0.13MB + Engine InnoDB
58n7nj1Ym_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_actionscheduler_logs: Data: 16.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_ac_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_admin_columns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_aws_cache: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_aws_index: Data: 10.36MB + Index: 9.41MB + Engine InnoDB
58n7nj1Ym_berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_bv_activities_store: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_bv_ip_store: Data: 0.19MB + Index: 0.16MB + Engine InnoDB
58n7nj1Ym_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_commentmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
58n7nj1Ym_comments: Data: 13.52MB + Index: 11.06MB + Engine InnoDB
58n7nj1Ym_dppp_plugin_deactivation_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_gf_entry: Data: 1.52MB + Index: 0.19MB + Engine InnoDB
58n7nj1Ym_gf_entry_meta: Data: 2.52MB + Index: 2.28MB + Engine InnoDB
58n7nj1Ym_gf_entry_notes: Data: 1.52MB + Index: 0.20MB + Engine InnoDB
58n7nj1Ym_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_gf_form_meta: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
58n7nj1Ym_gf_form_view: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
58n7nj1Ym_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
58n7nj1Ym_iconic_was_fees: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_itsec_bans: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
58n7nj1Ym_itsec_dashboard_events: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_itsec_distributed_storage: Data: 17.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
58n7nj1Ym_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
58n7nj1Ym_itsec_lockouts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
58n7nj1Ym_itsec_logs: Data: 11.02MB + Index: 7.97MB + Engine InnoDB
58n7nj1Ym_itsec_mutexes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_itsec_temp: Data: 0.13MB + Index: 0.23MB + Engine InnoDB
58n7nj1Ym_itsec_user_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_login_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_nf_objectmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_nf_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_nf_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_ninja_forms_fav_fields: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_ninja_forms_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_ninja_forms_uploads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_options: Data: 21.42MB + Index: 1.09MB + Engine InnoDB
58n7nj1Ym_pmxe_exports: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_pmxe_posts: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_pmxi_files: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_pmxi_hash: Data: 1.14MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_pmxi_images: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_pmxi_imports: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_pmxi_posts: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_pmxi_templates: Data: 0.27MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_popover_ip_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_postmeta: Data: 267.77MB + Index: 98.27MB + Engine InnoDB
58n7nj1Ym_posts: Data: 21.42MB + Index: 8.77MB + Engine InnoDB
58n7nj1Ym_realmedialibrary_debug: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
58n7nj1Ym_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
58n7nj1Ym_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
58n7nj1Ym_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
58n7nj1Ym_signups: Data: 0.19MB + Index: 0.13MB + Engine InnoDB
58n7nj1Ym_smush_dir_images: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
58n7nj1Ym_snippets: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
58n7nj1Ym_taxonomymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
58n7nj1Ym_termmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
58n7nj1Ym_terms: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
58n7nj1Ym_term_relationships: Data: 3.50MB + Index: 2.45MB + Engine InnoDB
58n7nj1Ym_term_taxonomy: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
58n7nj1Ym_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
58n7nj1Ym_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_usermeta: Data: 8.52MB + Index: 6.02MB + Engine InnoDB
58n7nj1Ym_users: Data: 0.23MB + Index: 0.20MB + Engine InnoDB
58n7nj1Ym_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wc_customer_lookup: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
58n7nj1Ym_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
58n7nj1Ym_wc_order_coupon_lookup: Data: 0.13MB + Index: 0.20MB + Engine InnoDB
58n7nj1Ym_wc_order_product_lookup: Data: 2.30MB + Index: 1.31MB + Engine InnoDB
58n7nj1Ym_wc_order_stats: Data: 1.52MB + Index: 0.69MB + Engine InnoDB
58n7nj1Ym_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
58n7nj1Ym_wc_product_attributes_lookup: Data: 1.47MB + Index: 1.44MB + Engine InnoDB
58n7nj1Ym_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_wc_product_meta_lookup: Data: 1.52MB + Index: 2.78MB + Engine InnoDB
58n7nj1Ym_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_wdr_order_discounts: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wdr_order_item_discounts: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wdr_rules: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wfBlocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
58n7nj1Ym_wfConfig: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wfFileMods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wfHits: Data: 2.52MB + Index: 0.25MB + Engine InnoDB
58n7nj1Ym_wfHoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_wfIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
58n7nj1Ym_wfKnownFileList: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wfLogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
58n7nj1Ym_wfNotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wfPendingIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
58n7nj1Ym_wfReverseCache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wfSNIPCache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
58n7nj1Ym_wfStatus: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
58n7nj1Ym_wfTrafficRates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wfwafconfig: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wpmailsmtp_debug_events: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
58n7nj1Ym_wpr_rucss_resources: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
58n7nj1Ym_wpr_rucss_used_css: Data: 0.30MB + Index: 0.38MB + Engine InnoDB
58n7nj1Ym_yith_wcan_filter_sessions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
58n7nj1Ym_yith_wcwl: Data: 0.48MB + Index: 0.16MB + Engine InnoDB
58n7nj1Ym_yith_wcwl_lists: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
58n7nj1Ym_yoast_indexable: Data: 21.55MB + Index: 14.67MB + Engine InnoDB
58n7nj1Ym_yoast_indexable_hierarchy: Data: 1.50MB + Index: 1.05MB + Engine InnoDB
58n7nj1Ym_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
58n7nj1Ym_yoast_primary_term: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
58n7nj1Ym_yoast_prominent_words: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
58n7nj1Ym_yoast_seo_meta: Data: 0.42MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

acf-field: 5
acf-field-group: 3
ajde_events: 1
aoc_popup: 4
attachment: 19442
blocks: 1
custom_css: 4
customize_changeset: 1
es_template: 2
et_body_layout: 9
et_footer_layout: 1
et_header_layout: 1
et_pb_layout: 16
et_template: 22
et_theme_builder: 1
guarded-page: 1
inc_popup: 1
itsec-dash-card: 24
itsec-dashboard: 3
mc4wp-form: 1
nav_menu_item: 136
nf_sub: 989
o-discount: 1
o-list: 1
oembed_cache: 40
page: 33
popup_theme: 6
popups: 1
post: 28
postman_sent_mail: 250
product: 3785
product_variation: 4782
responsive_accordion: 1
seedprod: 3
shop_coupon: 108
shop_order: 6615
shop_order_refund: 449
wp_global_styles: 1
wp_stream_alerts: 4
wpsm_faq_r: 1
yith_wcan_preset: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (53) ###

ManageWP - Worker: by GoDaddy – 4.9.13
Gravity Forms: by Gravity Forms – 2.6.3
Admin Columns Pro - Advanced Custom Fields (ACF): by AdminColumns.com – 3.0.2
Admin Columns Pro - WooCommerce: by AdminColumns.com – 3.7.1
Admin Columns Pro - Yoast SEO: by AdminColumns.com – 1.2
Admin Columns Pro: by AdminColumns.com – 5.7.1
Advanced Custom Fields: by Delicious Brains – 5.12.2
Advanced Woo Search: by ILLID – 2.54
Afterpay Gateway for WooCommerce: by Afterpay – 3.4.1
Akismet Anti-Spam: by Automattic – 4.2.4
WordPress Backup & Security Plugin - BlogVault: by Backup by BlogVault – 4.78
Cloudflare: by Cloudflare
Inc. – 4.9.1

Code Snippets: by Code Snippets Pro – 3.1.0
Divi Carousel: by DiviGear – 2.0.22
Divi Social Sharing Buttons: by Pee Aye Creative – 2.1
Gravity Forms Drip Add-On: by gravity+ for Drip – 2.1.2
Drip for WooCommerce: by Drip – 1.1.2
Google Tag Manager for WordPress: by Thomas Geiger – 1.15.1
Gravity Forms Akismet Add-On: by Gravity Forms – 1.0
Gravity Forms User Registration Add-On: by Gravity Forms – 5.0
Header and Footer Scripts: by Digital Liberation – 2.2.1
WooCommerce Attribute Swatches by Iconic: by Iconic  – 1.3.4
iThemes Security Pro: by iThemes – 7.1.2
Judge.me Product Reviews for WooCommerce: by Judge.me – 1.3.16
Max Mega Menu - Pro Addon: by Tom Hemsley – 1.7
Max Mega Menu: by megamenu.com – 2.9.6
reCaptcha for WooCommerce: by I Thirteen Web Solution – 2.32
Redirection: by John Godley – 5.2.3
Transients Manager: by WPBeginner – 2.0.2
User Role Editor: by Vladimir Garagulya – 4.62
User Switching: by John Blackbourn & contributors – 1.5.8
CTX Feed: by WebAppick – 4.4.60
Woo Discount Rules PRO 2.0: by Flycart – 2.4.0
Woo Discount Rules: by Flycart – 2.4.1
Woocommerce Ebizcharge Gateway: by EBizCharge – 5.8.0
WooCommerce Affirm Gateway: by WooCommerce – 1.2.2
WooCommerce Stripe Gateway: by WooCommerce – 6.4.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.9
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.27.1
WooCommerce Wholesale Prices: by Rymera Web Co – 2.1.2
WooCommerce: by Automattic – 6.5.1
Yoast SEO Premium: by Team Yoast – 18.5
Yoast SEO: by Team Yoast – 18.9
WP All Import Pro: by Soflyy – 4.7.2
WP Crontrol: by John Blackbourn & crontributors – 1.12.1
WP Rocket: by WP Media – 3.11.0.4
Smush Pro: by WPMU DEV – 3.9.10
WP All Import - WooCommerce Import Add-On Pro: by Soflyy – 3.3.1
WPMU DEV Dashboard: by WPMU DEV – 4.11.12
YITH WooCommerce Ajax Product Filter Premium: by YITH – 4.10.0
YITH WooCommerce Frequently Bought Together Premium: by YITH – 1.17.0
YITH WooCommerce Quick View Premium: by YITH – 1.17.0
YITH WooCommerce Wishlist: by YITH – 3.9.0

### Inactive Plugins (5) ###

Admin Columns: by AdminColumns.com – 4.4.5
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.48
WP All Export - WooCommerce Export Add-On Pro: by Soflyy – 1.0.4
WP All Export Pro: by Soflyy – 1.7.4
WP Mail SMTP Pro: by WPForms – 3.2.1

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php
object-cache.php: Memcached Redux

### Must Use Plugins (9) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
installatron_hide_status_test.php: by  –
wp-fix-it-plugin-filter.php: by  – 1.13.2
wp-hide-loader.php: by  –
WPE ElasticPress Autosuggest Logger: by WP Engine – 1.0.0
WP Engine Cache Plugin: by WP Engine – 1.0.9
WP Engine Seamless Login Plugin: by WP Engine – 1.5.5
WP Engine Security Auditor: by wpengine – 1.0.10
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
visible (visible)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #77 - /shop/
Cart: #78 - /cart/
Checkout: #79 - /checkout/
My account: #80 - /my-account/
Terms and conditions: #982 - /terms-conditions/

### Theme ###

Name: Divi Child
Version: 1.0.0
Author URL: https://www.elegantthemes.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.17.4
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: divi-child/woocommerce/cart/cart-totals.php

### Action Scheduler ###

Complete: 62,813
Oldest: 2022-04-23 17:17:47 -0700
Newest: 2022-05-24 17:16:16 -0700

Failed: 8
Oldest: 2022-03-28 13:24:14 -0700
Newest: 2022-04-12 13:06:03 -0700

Pending: 4
Oldest: 2022-05-24 17:16:25 -0700
Newest: 2022-05-27 10:08:41 -0700

### Status report information ###

Generated at: 2022-05-24 17:16:33 -07:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment] 2022-05-25 04:39
Thanks for the bug report @John-Schuster22. Before moving this forward, can you confirm you've done conflict testing? In other words, deactivated all other plugins to see if this behaviour persists?

**Comment by John-Schuster22** [comment] 2022-05-25 18:35
Hello, we have not done conflict testing but we are working on the test on a staging site now. However, it's very hard to test because it seems to only happen when the scheduled date is passed.

Current date is 5/25/22

In other words if we set the date to a product of 5/23/22 and have the sales price the sale will not show on the page because the date is already over when it is set.

However, if we set it to a future date 5/26/22 it will show the product on sale but after the date passes on the backend everything looks correct on the front end the sales badge disappears and the crossed-out price disappears but the sales price is the only thing that is showing and when you add to cart it does not go back to the retail price.

It would be nice to figure out how to consistently test this

**Comment by swatipawarGS** [comment] 2022-05-26 15:00
Hi @John-Schuster22,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using WooCommerce 6.5.1 version and WordPress 6.0 version. 

Please find below screencast for reference :

https://user-images.githubusercontent.com/94531721/170445463-3dbd079e-5d44-4838-903a-845eab91b713.mp4

Please provide us more detailed and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by John-Schuster22** [comment] 2022-05-26 17:48
@swatipawarGS Ok looks like it is a plugin conflict but how can we test deactivating our plugins quickly on this issue.

We have quite a few plugins on the site and are not sure about deactivating them one by one and testing them every day is the best solution.

Thanks!

**Comment by John-Schuster22** [comment] 2022-05-26 18:01
I noticed on our live site the woocommerce_scheduled_sales cron is missing is it ok to just readd?

![image](https://user-images.githubusercontent.com/106205288/170548237-179357df-6a11-4250-b5cb-d01f0180d093.png)

**Comment by ObliviousHarmony** [comment] 2022-06-13 19:12
@John-Schuster22 Yes, that should be fine.

**Closed as completed** 2022-06-13 19:12 UTC
Labels: Bug, status: can't reproduce, plugin: woocommerce
