### ISSUE TITLE
Cancel unpaid orders

### ISSUE THREAD

**Issue by tothang** [woothemes/woocommerce#43442] opened 2024-01-10 06:47 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

According to what I have learned, the function below `$unpaid_orders = $data_store->get_unpaid_orders( strtotime( '-' . absint( $held_duration ) . ' MINUTES', current_time( 'timestamp' ) ) );` is in the file
`wp-content/plugins/woocommerce/includes/wc-order-functions.php`
This code is to handle the cancellation of orders in pending status and beyond the waiting time. This logic is related to datetime and querying the database. As far as I can see the database datetime is stored in UTC (GMT +0) But the above function is handling getting the current unix time according to the server's time zone. This is causing an error on my system because my current posting server is located in AU. Is there any way that can help me solve this problem?

### Expected behavior

current_time( 'timestamp' ) should be replaced by current_time( 'timestamp' , true)

### Actual behavior

current_time( 'timestamp' ) this get unix time of server

### Steps to reproduce

1 create an ofer via after pay or paypal
2 leave payment window

### WordPress Environment

6.1.4

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Konamiman** [comment] 2024-01-15 09:57
Hi, I'm closing this because the issue is fixed by https://github.com/woocommerce/woocommerce/pull/43641, which will be included in WooCommerce 8.6. Please follow [the WooCommerce developer blog](https://developer.woo.com/blog/) for release announcements.

**Closed as completed by Konamiman** 2024-01-15 09:57 UTC
Labels: Bug, Order Management, type: community contribution
