### ISSUE TITLE
Our customers are creating order in which we have very specific tax rates applied, but when they pay a deposit leaving a pending payment, the balance amount is then getting additional standard tax applied on that already included.  This was not happening just a couple of weeks ago.

### ISSUE THREAD

**Issue by GregMcTS** [woothemes/woocommerce#30528] opened 2021-08-18 16:23 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

Our customers are creating order in which we have very specific tax rates applied, but when they pay a deposit leaving a pending payment, the balance amount is then getting additional standard tax applied on that already included.  This was not happening just a couple of weeks ago.

**Expected behavior**
The tax should not be being re-applied to balances

**Actual behavior**
additional tax at a standard rate is being applied to remaining balances after client has paid a deposit.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to any pending order in our /main subdomain 
2. Click on a pending order and look at the VAT added at the end of the line.
3. This additional VAT should not be being applied as all taxes were calculated at the point of the order being made and were displayed correctly to the client at the checkout.

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
`
### WordPress Environment ###

WordPress address (URL): https://placentaplus.co.uk/main
Site address (URL): https://placentaplus.co.uk/main
WC Version: 5.5.2
REST API Version: ✔ 5.5.2
WC Blocks Version: ✔ 5.3.3
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.0
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.22
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.29.0
NSS/3.36

SUHOSIN Installed: –
MySQL Version: 5.5.65-MariaDB
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: placenta_4_
Total Database Size: 42.22MB
Database Data Size: 27.98MB
Database Index Size: 14.24MB
placenta_4_woocommerce_sessions: Data: 6.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_4_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
placenta_4_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
placenta_4_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.39MB + Engine InnoDB
placenta_4_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
placenta_4_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_4_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_4_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_4_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_actionscheduler_actions: Data: 0.19MB + Index: 0.22MB + Engine InnoDB
placenta_4_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_actionscheduler_logs: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
placenta_4_commentmeta: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
placenta_4_comments: Data: 0.28MB + Index: 0.31MB + Engine InnoDB
placenta_4_enjoy_instagram_hashtags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_enjoy_instagram_media: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
placenta_4_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
placenta_4_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_4_groups_capability: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_4_groups_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_groups_group_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_groups_user_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_groups_user_group: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
placenta_4_hustle_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_4_hustle_entries_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
placenta_4_hustle_modules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_hustle_modules_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_4_hustle_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
placenta_4_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_options: Data: 5.02MB + Index: 0.17MB + Engine InnoDB
placenta_4_pmxe_exports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
placenta_4_pmxe_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_pmxi_imports: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
placenta_4_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_postmeta: Data: 2.50MB + Index: 4.02MB + Engine InnoDB
placenta_4_posts: Data: 0.42MB + Index: 0.34MB + Engine InnoDB
placenta_4_redirects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
placenta_4_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_revslider_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_4_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_4_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_4_vxc_zoho_accounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_vxc_zoho_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
placenta_4_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_wc_customer_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
placenta_4_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_4_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_4_wc_order_product_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
placenta_4_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
placenta_4_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_4_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
placenta_4_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_woocommerce_bundled_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
placenta_4_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_4_wpforms_entries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_wpforms_entry_fields: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
placenta_4_wpforms_entry_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_4_yoast_indexable: Data: 0.28MB + Index: 0.33MB + Engine InnoDB
placenta_4_yoast_indexable_hierarchy: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
placenta_4_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_4_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_4_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_4_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
placenta_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
placenta_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
placenta_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
placenta_sitemeta: Data: 1.05MB + Index: 0.03MB + Engine InnoDB
placenta_usermeta: Data: 7.47MB + Index: 5.81MB + Engine InnoDB
placenta_users: Data: 0.27MB + Index: 0.23MB + Engine InnoDB

### Post Type Counts ###

attachment: 48
customize_changeset: 1
elementor_library: 3
nav_menu_item: 11
page: 7
post: 3
product: 29
product_variation: 24
revision: 41
shop_coupon: 4
shop_order: 240
shop_order_refund: 3
sumo_pp_cron_jobs: 97
sumo_pp_masterlog: 637
sumo_pp_payments: 97
us_header: 1
us_page_block: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (48) ###

Klarna Order Management for WooCommerce: by klarna
krokedil – 1.6.7

Mailchimp for WooCommerce: by Mailchimp – 2.5.2
WPMU DEV Dashboard: by WPMU DEV – 4.11.2
Akismet Anti-Spam: by Automattic – 4.1.10
Contact Form 7: by Takayuki Miyoshi – 5.4.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Loco Translate: by Tim Whitlock – 2.5.3
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Shipping Method Display Style for WooCommerce: by theDotstore – 3.7.2
Slider Revolution: by ThemePunch – 6.2.4
Smush Pro: by WPMU DEV – 3.8.8
UpSolution Core: by UpSolution – 7.8.4
WooCommerce: by Automattic – 5.5.2 (update to version 5.6.0 is available)
WooCommerce Admin: by WooCommerce – 2.5.0
WooCommerce Stripe Gateway: by WooCommerce – 5.3.0
WordPress Importer: by wordpressdotorg – 0.7
WPBakery Page Builder: by Michael M - WPBakery.com – 6.2.0
WPForms: by WPForms – 1.6.8.1
Media Sync: by Erol Živina – 1.2.5
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.4.8
Simple Custom CSS and JS: by SilkyPress.com – 3.37
SUMO Payment Plans: by Fantastic Plugins – 7.0
301 Redirects: by WebFactory Ltd – 2.70
WooCommerce Product Dependencies: by SomewhereWarm – 1.2.7
Enjoy Instagram: by Mediabeta Srl – 6.2.0
WooCommerce Product Bundles: by SomewhereWarm – 6.3.3 (update to version 6.11.1 is available)
Yoast SEO: by Team Yoast – 16.9
WooCommerce Composite Products: by SomewhereWarm – 7.0.6 (update to version 8.2.0 is available)
Envato Market: by Envato – 2.0.6
WP Cerber Security, Anti-spam & Malware Scan: by Cerber Tech Inc. – 8.9
Hustle: by WPMU DEV – 7.4.4
Code Snippets: by Code Snippets Pro – 2.14.1
Elementor: by Elementor.com – 3.3.1
Elementor Pro: by Elementor.com – 3.3.7
GA Google Analytics: by Jeff Starr – 20210719
Visibility Logic for Elementor: by StaxWP – 2.1.7
Cart Upsell for WooCommerce: by SKROTRON – 1.0.6
YITH WooCommerce Gift Cards Premium: by YITH – 3.3.3
WPForms Mailchimp: by WPForms – 2.1.0
Yoast Duplicate Post: by Enrico Battocchi and Team Yoast – 4.1.2
WooCommerce Zoho Pro: by CRM Perks – 1.2.2
Export WooCommerce Shipping zones data: by Rynaldo Stoltz – 1.0.1
WP Hotjar: by Thiago Guimarães – 0.0.3
Hotjar: by Hotjar – 1.0.11
Screets Live Chat: by Screets – 2.9.5
Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 2.2.0

Klarna Order Management for WooCommerce: by klarna
krokedil – 1.6.7

Klarna On-Site Messaging for WooCommerce: by krokedil
klarna – 1.4.3


### Inactive Plugins (6) ###

Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.18.0
WP All Export Pro: by Soflyy – 1.5.4
WP All Import - WooCommerce Add-On Pro: by Soflyy – 3.2.1
WP All Import Pro: by Soflyy – 4.4.8
WP Crontrol: by John Blackbourn & crontributors – 1.10.0
WPForms Form Abandonment: by WPForms – 1.5.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #53 - /
Basket: #45 - /basket/
Checkout: #47 - /checkout/
My account: #49 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Impreza Child
Version: 1.0
Author URL: http://us-themes.com/
Child Theme: ✔
Parent Theme Name: Impreza
Parent Theme Version: 7.8.4
Parent Theme Author URL: http://us-themes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Composite Products ###

Database Version: 7.0.6
Loopback Test: ✔
Template Overrides: –

### Product Bundles ###

Database Version: 6.3.3
Loopback Test: ✔
Template Overrides: –

### Action Scheduler ###

Canceled: 1
Oldest: 2021-08-15 23:04:45 +0100
Newest: 2021-08-15 23:04:45 +0100

Complete: 509
Oldest: 2021-07-19 11:54:33 +0100
Newest: 2021-08-18 17:06:58 +0100

Pending: 5
Oldest: 2021-08-19 03:51:43 +0100
Newest: 2021-08-24 14:49:55 +0100


### Status report information ###

Generated at: 2021-08-18 17:23:15 +01:00
`

**Comment by tammullen** [comment] 2021-08-20 16:47
Hi @GregMcTS 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by tammullen** 2021-08-20 16:47 UTC
Labels: Bug, type: support request
