### ISSUE TITLE
Unexpected behavior of WC_Order::get_meta 

### ISSUE THREAD

**Issue by smazur** [woothemes/woocommerce#31140] opened 2021-11-11 12:57 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
```
$o = wc_get_order(...)
$o->get_meta('_shipping_phone'); // Returns empty string and no doing it wrong error
$o->get_shipping_phone(); // Returns phone number.
```

**Expected behavior**
```
$o->get_meta('_shipping_phone'); 
```
Should return phone number and doing it wrong message in error log.

**Actual behavior**
```
$o->get_meta('_shipping_phone'); 
```
Returns empty string and no doing it wrong in error log.

**Comment by DavidAnderson684** [comment] 2021-11-11 22:42
If `$o->get_meta('_shipping_phone');` returns an empty string, then that means no programmer out there can be using it, since it doesn't do anything. The proposal to add a capability to make it do something, and also announce that same capability to be deprecated at the same time, makes no sense.

**Comment by smazur** [comment] 2021-11-12 08:09
@DavidAnderson684 
The `_shipping_phone` is considered as internal meta key and when you call `$o->get_meta('_shipping_phone');` it should throw deprecated notice and call `get_shipping_phone` method. But it doesn't do that, because it searched for `get__shipping_phone` which not exists and here we have logic collision. That problem also appears for other internal meta fields.

Consider following line. What will happen if `$key` starts with underscore?
https://github.com/woocommerce/woocommerce/blob/fd3dfdbf3e05ce87138831d2f8eff3734eeb4572/plugins/woocommerce/includes/abstracts/abstract-wc-data.php#L308

**Comment by smazur** [comment] 2021-11-12 08:11
Consider following line. What will happen if `$key` starts with underscore?
https://github.com/woocommerce/woocommerce/blob/fd3dfdbf3e05ce87138831d2f8eff3734eeb4572/plugins/woocommerce/includes/abstracts/abstract-wc-data.php#L308

**Comment by juliaamosova** [comment] 2021-11-14 22:43
Hi @smazur,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment] 2021-12-03 19:48
Thanks for the report, @smazur. I think I see what you mean. 

Just to confirm we're on the same page and breaking it down one more time (focusing on `_shipping_phone`, though I understand this applies for all internal keys):

1. We start with an order where the shipping phone number is `'100 200 3000'`.
2. Next we call `$order->update_meta_data( '_shipping_phone', '999 999 9999' )` (and then save the order meta data). This appears to succeed and no error or warning is made (and, in fact, a *new* entry is added to the post meta table with this key and value).
3. If we subsequently call `$order->get_shipping_phone()` we get back `'100 200 3000'`.
4. If we subsequently call `$order->update_meta_data( '_shipping_phone' )` then we get back an empty string, as you observed.

I agree this sort of 'masking' is potentially problematic, as is allowing an additional entry using the same internal meta key to be added to the table. The only thing I'm just a little unsure of is if your suggested expected behavior is the best path:

| Your suggestion | An alternative ('separate worlds') |
| --- | --- |
| <ul><li>`$o->get_shipping_phone()` → `'100 200 3000'`</li><li>`$o->update_meta_data( '_shipping_phone' )` → `'100 200 3000'` <em>(plus doing it wrong notice)</em></li></ul> | <ul><li>`$o->get_shipping_phone()` → `'100 200 3000'`</li><li>`$o->update_meta_data( '_shipping_phone' )` → `'999 999 9999'`</li></ul> |

However, we don't need to decide on the solution here and now. Marking as a bug.

**Closed as completed** 2022-03-30 21:15 UTC
Labels: Bug, plugin: woocommerce
