### ISSUE TITLE
WooCommerce Mini Cart: "Save %" String not being Translated in Mini Cart

### ISSUE THREAD

**Issue by druesome** [woothemes/woocommerce#44754] opened 2024-02-19 07:19 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The "Save %" string in the mini cart isn't translating properly, despite being translated here:

https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/tr/default/?filters%5Bterm%5D=save+%25&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

Ticket: 7737834-zen

### Expected behavior

I expect the string to be translated

### Actual behavior

It's not translated.  The string remains as "Save %"

### Steps to reproduce

1. Go to https://uykulukahve.com/shop/
2. Add a product to the cart
3. Wait for the mini cart to slide in

### WordPress Environment

NA

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment] 2024-02-19 21:32
Working fine for me
<img width="475" alt="image" src="https://github.com/woocommerce/woocommerce/assets/6165348/9077ef16-4717-4b72-8226-54dc85898122">

**Comment by tammullen** [comment] 2024-02-19 22:10
Possible duplicate of https://github.com/woocommerce/woocommerce/issues/43185 however that issue is currently closed

**Comment by inaikem** [comment] 2024-02-25 07:58
@tammullen, would you suggest reopening that issue or having Woo devs focus on this report instead? Thanks!

**Comment by nielslange** [comment] 2024-03-06 11:41
@druesome As @senadir mentioned in https://github.com/woocommerce/woocommerce/issues/44754#issuecomment-1953181579, this issue is no longer reproducible. Can you inform the customer accordingly?

> @tammullen, would you suggest reopening that issue or having Woo devs focus on this report instead? Thanks!

@inaikem I'd say it's best to open an issue whenever you're seeing something not working. Currently, all reported issues appear to be working fine. I cannot see any translation problems. I'll close this issue for now, but please create another one, if you spot something that seems broken.

**Closed as completed by nielslange** 2024-03-06 11:41 UTC
Labels: Bug, focus: i18n, Cart, Rubik
