### ISSUE TITLE
__experimentalSelectControl: Add suffix prop

### ISSUE THREAD

**Issue by mattsherman** [woothemes/woocommerce#35426] opened 2022-10-31 17:52 UTC
## Description

A `suffix` prop should be added to the [`__experimentalSelectControl`](https://github.com/woocommerce/woocommerce/tree/trunk/packages/js/components/src/experimental-select-control), similar to the `suffix` prop on the [`__experimentalInputControl`](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/input-control).

The `suffix` prop can be used by consumers for a number of scenarios:
    - To provide an alternate indicator, such as a dropdown arrow, if the select control is being used as a dropdown
    - To provide a "loading" indicator icon when results are being fetched asynchronously

## API

- Prop: `suffix`
    - Type: `React.ReactNode`
    - Required: No
    - Default: a search icon (magnifying glass)

- A `SelectControlSuffixWrapper` should ideally be provided, much like `__experimentalInputControl` handles things. It would be nice to have consistency in how suffixes are handled between the `__experimentalSelectControl` and the `__experimentalInputControl`. But, if this proves to be too complex at this point in time, it could be pushed off for a future enhancement.

## Acceptance criteria

- [ ] The `suffix` should be rendered on the right hand side of the select control's input field
- [ ] If no `suffix` is set, a search icon should be shown as the suffix
- [ ] If a `suffix` is set, it should be used instead of the default

**Comment by mattsherman** [comment] 2022-10-31 18:13
I've estimated this as a `2`. Mainly because of the potential complication of providing a `SuffixWrapper`.

The modification of existing code to make use of the `suffix` prop will be handled in follow up PRs.

**Comment by joshuatf** [comment] 2022-11-23 19:18
I like the idea of `suffix` but just for the sake of curiosity, was this to make more open-ended than `icon`?

My only (minor) concern is that if someone were to add a button here, that button might not work as intended since clicking the current icon area also focuses the input.  But this could be resolved in a couple of different ways if we choose to go this route.

**Comment by mattsherman** [comment] 2022-11-29 14:38
> I like the idea of suffix but just for the sake of curiosity, was this to make more open-ended than icon?

Suffix is consistent with how `__experimentalInputControl` handles things.

> My only (minor) concern is that if someone were to add a button here, that button might not work as intended since clicking the current icon area also focuses the input. But this could be resolved in a couple of different ways if we choose to go this route.

Good point, we will want to make sure we handle/understand interaction issues with the suffix. I don't believe this to be a major concern.

**Closed as completed** 2022-12-02 16:53 UTC
Labels: package: @woocommerce/components, Settings
