### ISSUE TITLE
[Enhancement]: Add modified_before and modified_after parameters to the Customers endpoint 

### ISSUE THREAD

**Issue by Dimi727** [woothemes/woocommerce#41371] opened 2023-11-10 17:13 UTC
### Describe the solution you'd like

As for the other important endpoints like Orders and Products, please add the modified_before and modified_after parameters to the [Customers endpoint](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-customers).

Retrieving Customers and their updates takes otherwise too long because we need to fetch all customers every time.

**Comment by Dimi727** [comment] 2024-01-30 09:16
Wondering about the priority here and that the topic was never (?) raised? @coreymckrill 

The missing of a working filter function of the endpoint means that no incremental loading of customers data is possible. 
Meaning: the more customers, the longer does the data load take - this blocks the create-update-speed of anything related to customers data. 

With the current priority, how long is the time horizon here? Months? Years?

**Comment by coreymckrill** [comment] 2024-01-30 22:35
Hey @Dimi727, unfortunately I have no time estimate for this right now. Your re-surfacing of this issue is timely, though, because we're currently seeking exactly this sort of feedback about the REST API:

https://developer.woo.com/2024/01/30/woocommerces-web-api-we-want-to-hear-from-you/

**Comment by coreymckrill** [comment] 2024-06-03 23:44
Closing this as a duplicate of #31482

**Closed as not planned by coreymckrill** 2024-06-03 23:44 UTC
Labels: Enhancement, REST/Store API/Webhooks, Performance
