### ISSUE TITLE
Fix Product Search's width options

### ISSUE THREAD

**Issue by jarekmorawski** [woothemes/woocommerce#47888] opened 2024-05-28 12:59 UTC
The Product Search block currently uses an input field and a segmented button for choosing the block's width. Surprisingly, the input field doesn't really work and any custom values don't take effect. Choosing one of the pre-defined values populates the input field, which feels redundant.

<img width="325" alt="image" src="https://github.com/woocommerce/woocommerce/assets/79307566/381f8d1a-07e8-4119-bbaf-e8ba4f8c627d">

Also, it doesn't seem that the setting is respected on the canvas. No matter what value I choose, the size remains unchanged.

**Comment by octaedro** [comment] 2024-08-26 19:19
Hi @jarekmorawski,

I couldn't reproduce this error. The value I set in the input is successfully applied to the block afterward.

https://github.com/user-attachments/assets/8ce37cdf-b1a3-4dde-bd53-d073f6d25758

**Comment by j111q** [comment] 2024-08-29 08:01
Checked on my own test store and it works for me too. Guess we can close this one 👍

**Comment by octaedro** [comment] 2024-08-29 16:40
Thank you @j111q! I'm closing this issue.

**Closed as completed by octaedro** 2024-08-29 16:40 UTC
Labels: Kirigami, Blocks/Patterns/Templates, block: product search
