### ISSUE TITLE
Banner notifications need margin top and bottom

### ISSUE THREAD

**Issue by elizaan36** [woothemes/woocommerce#39274] opened 2023-06-29 00:50 UTC
## Describe the bug

During a user flow review we noticed that the shopper notices need more space from other elements to prevent any potential overlap and to feel integrated in the store experience on all themes.

## To reproduce

1. Go to any store.
2. Click on Add to Cart from the product page.
3. See that notice needs more margin from elements on the page.

## Expected behavior

Create a top margin above the product image and sale badge to prevent overlap with other elements. 

## Screenshots
<img width="2179" alt="Screen Shot 2023-06-27 at 10 37 05 AM" src="https://github.com/woocommerce/woocommerce-blocks/assets/5121465/1d3fedb0-0bf7-428f-9b29-91f8bb885fef">

**Comment by mikejolley** [comment] 2023-07-17 15:41
This is caused by the `on-sale` badge having negative positioning of `-1rem`. The actual notices have a top/bottom border of 16px. It might be possible to work around using something fancy CSS such as:

```
.woocommerce-notices-wrapper + .product:has(.onsale) {
	margin-top: 2rem;
}
```

But it would be better to address this in core either by changing how sale badges appear (e.g. top left of the product image but no negative margins), or by applying extra margins/padding above products which contain sale badges.

Moving this issue upstream for feedback.

**Comment by rrennick** [comment] 2023-07-27 14:42
@mikejolley Are you still planning on addressing this?

**Comment by mikejolley** [comment] 2023-07-27 15:43
@rrennick I don't think this is a decision I can make?

**Comment by rrennick** [comment] 2023-07-28 13:39
@mikejolley Thanks, I removed you as the assignee.

**Comment by pmcpinto** [comment] 2023-11-02 16:49
> But it would be better to address this in core either by changing how sale badges appear (e.g. top left of the product image but no negative margins), or by applying extra margins/padding above products which contain sale badges.

@mikejolley are there any risks associated with these changes? Which one do you recommend?

**Comment by mikejolley** [comment] 2023-11-03 11:15
@pmcpinto design decision/problem really. I think it would be better to keep the sale badge within the bounds of the product image by default.

**Comment by pmcpinto** [comment] 2023-11-07 14:53
>  I think it would be better to keep the sale badge within the bounds of the product image by default.

@elizaan36 @jarekmorawski do you have any preferences about the sale badge placement?

**Comment by jarekmorawski** [comment] 2023-11-07 16:21
Yeah, I'd put it inside within the image frame. Same left- and top-padding as the zoom icon on the right. Later on, the badge's position will be customizable in the site editor, anyway.

**Comment by ralucaStan** [comment] 2023-11-08 09:58
How do you feel about starting a discussion about this? From my interactions, I know people do some customizations to this sale badge, so we need to be careful we aren't introducing anything that can impact their catalogs in ways we might not be aware of

**Comment by mikejolley** [comment] 2023-11-08 11:40
A discussion is not guaranteed to reach the people affected by such a change so personally I don't feel worthwhile. If there are CSS overrides in place (theme, custom css etc) I would have expected them to work regardless. From a code perspective we should only be adjusting margins/padding which are already defined our side.

**Comment by elizaan36** [comment] 2023-11-10 12:07
I think moving the sale badge inside the image is fine, but it doesn't fully solve the problem if the position of the sale badge will be customizable. I'd lean towards adding the extra top padding to the image as it seems that would prevent the overlap with the banner in all cases.

**Comment by pmcpinto** [comment] 2023-11-17 06:26
> I'd lean towards adding the extra top padding to the image as it seems that would prevent the overlap with the banner in all cases.

Let's move forward with this option, unless something has concerns about this. Thanks

**Comment by ralucaStan** [comment] 2024-02-14 13:08
>  I'd lean towards adding the extra top padding to the image as it seems that would prevent the overlap with the banner in all cases.

@elizaan36 Outside of this solution, is there anything else to adjust on the notices? 
If not, I'd update the ticket description and title to reflect the change and leave this ticket to the Store Editing teams.

**Comment by elizaan36** [comment] 2024-02-15 03:40
> @elizaan36 Outside of this solution, is there anything else to adjust on the notices?

Not at this time! 

> I'd update the ticket description and title to reflect the change and leave this ticket to the Store Editing teams.

Sounds good.

**Comment by pmcpinto** [comment] 2024-02-15 11:38
> If not, I'd update the ticket description and title to reflect the change and leave this ticket to the Store Editing teams.

@ralucaStan do you plan to change the team label?

**Comment by ralucaStan** [comment] 2024-02-15 11:46
I changed the team label but I think @elizaan36 has a better understanding of the expected result and can update the ticket details accordingly.

**Comment by elizaan36** [comment] 2024-02-16 03:19
Updated the description.

**Comment by ralucaStan** [comment] 2024-08-16 09:32
<img width="969" alt="Screenshot 2024-08-16 at 11 31 40" src="https://github.com/user-attachments/assets/0a79229b-6bc3-4a26-b461-b10a56bea0cc">
closing as the issue was fixed outside of this ticket as seen in the image above

**Closed as completed by ralucaStan** 2024-08-16 09:32 UTC
Labels: Bug, Store Frontend, Kirigami
