### ISSUE TITLE
Minicart height - too large on Safari - cannot checkout

### ISSUE THREAD

**Issue by kimclow** [woothemes/woocommerce#42084] opened 2023-11-20 09:08 UTC
## Describe the bug

When viewing products in the minicart on Safari, the CTAs are falling below the fold and you're unable to scroll to them, prohibiting customers from checking out. 

## To reproduce

1. Go to HelloYumi.com 
2. Add a product to your cart
3. Click on the cart icon to open the mini cart 

## Expected behaviour

I would expect the CTAs for "Checkout" and "View my Cart" to be visible and clickable. 
## Screenshots

<img width="1722" alt="Screenshot 2023-11-20 at 11 00 39" src="https://github.com/woocommerce/woocommerce-blocks/assets/83212200/ee25221a-ce7a-4d48-820c-dea2f294751a">

<img width="1720" alt="Screenshot 2023-11-20 at 11 00 12" src="https://github.com/woocommerce/woocommerce-blocks/assets/83212200/3f989234-270e-470d-8243-976d80074696">

### WordPress (please complete the following information):

-   WordPress version: 6.4.1
-   WooCommerce version: 8.3.0
-   WooCommerce Blocks version: 11.5.4
-   Site language: English
-   Any other plugins installed: I've tested this across a variety of sites, and don't think it's related to plugins, as they've all got different ones. 

### Desktop (please complete the following information):

-   OS: macOS
-   Browser Safari
-   Version 15.6.1 

## Additional context

You can test this on: 
HelloYumi.com 
NearlyNewKids.co.za

**Comment by kimclow** [comment] 2023-11-20 10:44
I've also picked up on this on the Yarnnakarn site: https://yarnnakarn.com/  

<img width="1722" alt="Screenshot 2023-11-20 at 12 12 46" src="https://github.com/woocommerce/woocommerce-blocks/assets/83212200/4f9d790c-bdb8-49ed-ba9b-5a13d2add7f9">

**Comment by senadir** [comment] 2023-11-20 12:23
I'm not able to reproduce that on a couple of sites or even helloyumi.com, running Safari 17 on Sonoma 14

**Comment by kimclow** [comment] 2023-11-20 14:35
Hey @senadir 
It looks like the issue is only presented on Safari Version 15.6.1

**Comment by mikejolley** [comment] 2023-12-12 10:46
@ralucaStan do we need to work on this? It's affecting older versions of Safari not current.

**Comment by ralucaStan** [comment] 2023-12-12 15:51
If it's not a big time investment I think we should as it's impacting the checkout flow. On that site the buttons are used to go to the checkout page, as there is no cart page

**Comment by mikejolley** [comment] 2023-12-13 16:39
I had a brief search and there doesn't appear to be a good/safe way to install older versions of Safari. This one is over a year old. I've confirmed the issue is fixed with the latest release however. For that reason I will close this out.

**Closed as completed by mikejolley** 2023-12-13 16:39 UTC
Labels: Bug, status: won't fix, type: community contribution, Rubik, block: mini-cart
