### ISSUE TITLE
WC_REMOVE_ALL_DATA did not work

### ISSUE THREAD

**Issue by withsalah** [woothemes/woocommerce#33126] opened 2022-05-19 23:44 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am on a local test website trying to completely remove WooCommerce. I used the `define( 'WC_REMOVE_ALL_DATA', true );` code in the right place, as explained on [this page](https://woocommerce.com/document/installing-uninstalling-woocommerce/#uninstalling-woocommerce).

When I click on Delete, I face the following Error: **Deletion failed: There has been a critical error on this website.Learn more about troubleshooting WordPress.**

![image](https://user-images.githubusercontent.com/13615909/169420530-ac838dce-61fb-4e2d-8a5a-a4267e5b6e2b.png)

### Expected behavior

I expected the plugin to be completely deleted from the hosting and the database.

### Actual behavior

![image](https://user-images.githubusercontent.com/13615909/169420571-31e767ed-f276-4989-ad8f-f0ced0e5485e.png)

As can be seen from the picture above, I strictly followed the recommended steps to delete the WooCommerce extension completely, but this error occurred.

The Error: Deletion failed: There has been a critical error on this website.Learn more about troubleshooting WordPress.

### Steps to reproduce

1. I installed a new fresh local WordPress website using [local](https://localwp.com/) on Windows.
2. I installed & activate WooCommerce plugin from the plugins page > Add New > Popular > WooCommerce.
3. I opened wp-config.php file, and added the code `define( 'WC_REMOVE_ALL_DATA', true );` before "/* That's all, stop editing! Happy publishing. */" line directly as seen in the next image:
![image](https://user-images.githubusercontent.com/13615909/169421302-406d326b-6177-41fc-bb3d-7d0406bf3d3e.png)

4. I went back to the plugins page, and deactivated the plugin.
5. When I click on the delete button, It gives me the error "**Deletion failed: There has been a critical error on this website.Learn more about troubleshooting WordPress.**"
![image](https://user-images.githubusercontent.com/13615909/169421509-f19e5350-3258-4275-9c5a-1088ceb38141.png)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://test2.local
Site address (URL): http://test2.local
WC Version: 6.5.1
REST API Version: ✔ 6.5.1
WC Blocks Version: ✔ 7.4.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.4.1
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.67.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.1
WC Database Prefix: wp_
Total Database Size: 3.83MB
Database Data Size: 2.40MB
Database Index Size: 1.43MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.47MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
revision: 4

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 6.5.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: ❌ Page visibility should be public
Cart: ❌ Page visibility should be public
Checkout: ❌ Page visibility should be public
My account: ❌ Page visibility should be public
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Two
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2022-05-19 23:11:44 +0000
Newest: 2022-05-19 23:11:44 +0000

Pending: 1
Oldest: 2022-05-19 23:42:22 +0000
Newest: 2022-05-19 23:42:22 +0000

### Status report information ###

Generated at: 2022-05-19 23:41:38 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment] 2022-05-26 14:59
Hi @withsalah,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using WooCommerce 6.5.1 version and WordPress 6.0 version. 

Please find below screencast for reference :

https://user-images.githubusercontent.com/94531721/170447582-4844b6bd-3702-45c7-a0b2-2b9f1606c64a.mp4

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by withsalah** [comment] 2022-05-26 17:40
Hi @swatipawarGS 

No problem at all, just wanted to help. The goal is to improve the WooCommerce.

**Comment by XVII** [comment] 2022-05-27 06:10
+1. Can't delete plugin with WC_REMOVE_ALL_DATA  enabled.

**Comment by JPry** [comment] 2022-05-27 17:33
This is a duplicate of #32915.

**Closed as not planned by JPry** 2022-05-27 17:33 UTC
Labels: Bug, plugin: woocommerce

**Comment by peterforensys** [comment] 2023-04-14 11:16
The code define( 'WC_REMOVE_ALL_DATA', true ); still not working...
