### ISSUE TITLE
[Enhancement]: Improve slow queries

### ISSUE THREAD

**Issue by cristian-dan-f** [woothemes/woocommerce#39821] opened 2023-08-21 10:43 UTC
### Describe the solution you'd like

I am testing the latest Woocommerce update v8, main site still on v7. And it is obvious that Woocommerce does not care about site speed, because now every page load takes around 10-12 seconds when it used to be under 1 second. It doesn't matter if there is no Woocommerce related element on the page, or if it is the frontpage or the dashboard, Woocommerce will always be there to slowww things dowwwn.

These are the two SQL queries that are slowing things down. Maybe more have been added, haven't checked all of them.

SELECT post_status, COUNT( * ) AS num_posts
FROM cat_posts
WHERE post_type = 'product'
GROUP BY post_status

It adds 0,6234 seconds. It might not look like much but it can be the difference between a buyer or a leaver.

Now the second slow query:

SELECT cat_posts.ID
FROM cat_posts
LEFT JOIN cat_term_relationships
ON (cat_posts.ID = cat_term_relationships.object_id)
WHERE 1=1
AND ( cat_term_relationships.term_taxonomy_id IN (2,3,4,5) )
AND cat_posts.post_type = 'product'
AND ((cat_posts.post_status = 'publish'))
GROUP BY cat_posts.ID
ORDER BY cat_posts.post_date DESC
LIMIT 0, 1

It adds **9 to 11 seconds** to each page load. This is definitely a shop killer, and for what reason? Just because someone didn't care to properly code this so instead of running on each page load, it could run on cron, cache the result, and use the cached data.

For v7 we had to remove a bunch of queries, and now for v8 again, and this is why I am writing this, maybe there is a small chance that you start caring about speed.

Every query that on a normal shop with 100 products takes more then 0,0001 seconds should be moved to cron, and cached. Because on bigger shops that can quickly escalate. Is a simple strategy, maybe hard to implement when everything is designed in a totally opposite direction.

**Comment by rrennick** [comment] 2023-08-21 19:09
> It adds 9 to 11 seconds to each page load.

@cristian-dan-f Could you provide us with details on your shop as this performance isn't typical?

**Comment by vijayhardaha** [comment] 2023-10-10 23:47
Hello @rrennick,

I've come across a similar slow query on one of our websites. Here's the SQL in question:

```sql
SELECT
    wp_posts.ID
FROM
    wp_posts
    LEFT JOIN wp_term_relationships ON (wp_posts.ID = wp_term_relationships.object_id)
WHERE
    1 = 1
    AND (wp_term_relationships.term_taxonomy_id IN(2, 3, 4, 5, 525))
    AND wp_posts.post_type = 'product'
    AND ((wp_posts.post_status = 'publish'))
GROUP BY
    wp_posts.ID
ORDER BY
    wp_posts.post_date DESC
LIMIT 0,1
```

The call stack looks like this:

```php
WP_Query->get_posts()
wp-includes/class-wp-query.php:3219
WP_Query->query()
wp-includes/class-wp-query.php:3800
WP_Query->__construct()
wp-includes/class-wp-query.php:3932
WC_Product_Data_Store_CPT->query()
wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:2042
WC_Data_Store->__call()
wp-content/plugins/woocommerce/includes/class-wc-data-store.php:224
WC_Product_Query->get_products()
wp-content/plugins/woocommerce/includes/class-wc-product-query.php:76
Automattic\W\B\BlockPatterns->register_block_patterns()
wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockPatterns.php:181
do_action('init')
wp-includes/plugin.php:517
```

The time I see in Query Monitor is `0.0748`, which is significantly slower compared to another website where it's `0.006`, and there's no such slow query issue.

While I'm not primarily concerned about the speed impact, I am curious about why **`WC_Product_Query->get_products()`** is being called within the **`register_block_patterns()`** function. Is this expected behavior, or is it potentially something that shouldn't be happening in this context? 🤔

Your insights would be greatly appreciated.

**Comment by vijayhardaha** [comment] 2023-10-10 23:50
Additionally, please note that `525` for `term_taxonomy_id` corresponds to another `product_type`, specifically **gift-card,** created by the YITH Gift Cards plugin.

**Comment by rrennick** [comment] 2023-10-11 16:56
> Your insights would be greatly appreciated.

@vijayhardaha Thanks for the additional info.  I'm not involved in the blocks development so I can't provide any insight on this. But this info will help the team that works on blocks.

**Comment by gigitux** [comment] 2024-04-26 09:18
Thanks for opening this issue! 

Reading the call stack shared by @vijayhardaha, this issue refers to a query that we removed with https://github.com/woocommerce/woocommerce-blocks/pull/11138.


I'm going to close this issue, but feel free to continue this discussion if you have some concerns!

**Closed as completed by gigitux** 2024-04-26 09:18 UTC
Labels: Enhancement, Store Frontend, type: community contribution, Rubik
