### ISSUE TITLE
Incorrect currency symbol is display within orders section of WooCommerce > Home

### ISSUE THREAD

**Issue by thisissandip** [woothemes/woocommerce#41562] opened 2023-11-18 08:00 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Incorrect currency symbol (USD $)  is displayed for the order within the Orders section of WooCommerce > Home

### Expected behavior

The correct currency should be displayed for the order within the Orders section of WooCommerce > Home

### Actual behavior

Incorrect currency symbol (USD $)  is displayed for the order within the Orders section of WooCommerce > Home

### Steps to reproduce

1. Set Store Currency to INR
2. Place an order within the site
3. Check the order from WooCommerce > Orders, the correct currency is displayed here
4. Check the order from the Orders section of WooCommerce > Home
5. Incorrect currency symbol will be displayed (USD $) 

Screenshot:

![8qGQxu.png](https://github.com/woocommerce/woocommerce/assets/69596988/0575cdd8-9a5f-4703-9071-baa3ed23a255)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://conservative-fox.jurassic.ninja
Site address (URL): https://conservative-fox.jurassic.ninja
WC Version: 8.3.0
REST API Version: ✔ 8.3.0
WC Blocks Version: ✔ 11.4.8
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Unix) OpenSSL/1.0.2g
PHP Version: 8.0.30
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.0
WC Database Prefix: wp_
Total Database Size: 5.33MB
Database Data Size: 3.54MB
Database Index Size: 1.79MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.44MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
global_product_addon: 1
page: 8
post: 2
product: 4
shop_order_placehold: 1
wp_global_styles: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

Companion Plugin: by Osk – 1.30
WooCommerce: by Automattic – 8.3.0

### Inactive Plugins (6) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 12.8
WooCommerce Brands: by WooCommerce – 1.6.62
WooCommerce Composite Products: by WooCommerce – 8.10.4
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.65

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/users/usere4389e1d/apps/usere4389e1d/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/srv/users/usere4389e1d/apps/usere4389e1d/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/srv/users/usere4389e1d/apps/usere4389e1d/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-11-18 10:51:24 +00:00
Options: ✔
Notes: 66
Onboarding: completed

### Action Scheduler ###

Complete: 18
Oldest: 2023-11-13 10:51:35 +0000
Newest: 2023-11-18 07:55:38 +0000

Failed: 3
Oldest: 2023-11-13 10:54:10 +0000
Newest: 2023-11-18 07:57:39 +0000

Pending: 1
Oldest: 2023-11-19 07:45:40 +0000
Newest: 2023-11-19 07:45:40 +0000

### Status report information ###

Generated at: 2023-11-18 07:59:58 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by thisissandip** [comment] 2023-11-18 08:10
7328833-zen

**Comment by garysmurray** [comment] 2023-11-24 12:43
Another merchant with the same issue here: 7328777-zen

**Comment by psealock** [comment] 2024-01-31 23:44
I'm unable to reproduce this according to instructions. The Orders section and rest of the homescreen show currency in Indian Rupees. However, if I place an order in one currency, then switch to another, the Orders section reflects the currency at the time of the order was made.

For instance, my store is set to Brazilian Real, and order is made, then store currency switched to Indian Rupee and finally another order made my store Homescreen looks like so:

<img width="1221" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1922453/4d6777d9-1b52-4a73-90ae-26d08ca27896">

If I look at WooCommerce > Orders, the same is reflected:

<img width="973" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1922453/aa36825a-c553-4edd-a4ab-468dfff748e1">


@thisissandip is it possible the merchant in 7328833-zen received orders while the store was set to USD? I am going to close this issue because the behaviour I'm seeing is consistent with WooCommerce > Orders. However, please reopen in the case that I'm missing something.

**Closed as completed by psealock** 2024-01-31 23:44 UTC
Labels: Bug, Wayfinding
