### ISSUE TITLE
Settings > Tax Tab < Won’t HOLD Selections....

### ISSUE THREAD

**Issue by EFFETTI** [woothemes/woocommerce#31540] opened 2022-01-02 00:57 UTC
update2: BlueHost #37746158 = ACTIVE; reDirect to completely useless instructionS, plural TO OPERATE supposed OPTIONS [in] BOXES THAT DO NOT actually FUNCTION. [01/03/2022]
 
update: BlueHost #37746158 = ACTIVE;....

Our site [VNY.life] will Not show the tax line upon checkout; the form WILL NOT HOLD optional configurations to INCLUDE TAX info. on checkout; AND, instead recurrently reverts to EXCLUDE TAX settings; We’ve tried three, 3 different themes and tried multiple Times to adjust ALL TAX RELATED settings in ALL TAX RELATED locations correctly with no success.

 * the managed site host says all is fine? 
 
   << meanwhile: recurrently;
      >> General = Tax Enabled
         ^>> Tax = Auto Calculate
             ^>> Show = EXCLUDED & stuck
             ^>> Show = EXCLUDED & stuck
             ^>> Calc = SINGLE LINE & stuck

stuck = ONLY CHANGEABLE by TOGGLE OF automated to Not automated to both SEE AND USE the pulldown menu as intended = SETTINGS ARE EITHER STUCK OR RENDERED USELESS BY REVERSION = BUG = OUTside OF USER CONTROL TO OPERATE.

**Comment by swatipawarGS** [comment] 2022-01-04 12:47
Hi @EFFETTI ,

Could you please confirm and clarify exactly which settings is this defect related to?

**Comment by rodelgc** [comment] 2022-01-05 04:27
Hi @EFFETTI,

You didn’t fill out the details of the bug report template that we ask for. We're a bit confused about which exact settings in the UI you were referring to here:

> ^>> Tax = Auto Calculate
> ^>> Show = EXCLUDED & stuck
> ^>> Show = EXCLUDED & stuck
> ^>> Calc = SINGLE LINE & stuck

For us to be able to take a closer look, please provide us with:

- the exact steps we should undertake in the UI to reproduce the issue
- your system status report (feel free to hide all sensitive information they might contain)
- relevant screenshots that describe the bug (also feel free to hide all sensitive information they might contain)

These details are all in the bug report template that we asked for. Without these details, I'm afraid we won't be able to evaluate this issue further.

**Comment by EFFETTI** [comment] 2022-01-05 11:04
Screen Shots of TAX Tab: Three critical Pull Down Menus relating to [Display] ARE BOTH Non-Functional AND STUCK;

![239E2205-A8B0-4FB7-A583-98701395DBC5](https://user-images.githubusercontent.com/18757473/148207166-c0a5230d-a868-42fa-aba8-8f26f7ff6db4.png)

![1B5D09B4-164F-4C42-B123-4EC4B6E14EE2](https://user-images.githubusercontent.com/18757473/148207179-8aed61f4-dece-4ea6-bcd7-b43ec6e3e507.png)

![86B4A1E5-8204-4A80-9185-6CC9F5622E3E](https://user-images.githubusercontent.com/18757473/148207182-0f7d6e97-7c78-4db1-b350-9a7f5dbed146.png)

**Comment by EFFETTI** [comment] 2022-01-05 11:18
System Report:
`
### WordPress Environment ###

WordPress address (URL): https://vny.life
Site address (URL): https://vny.life
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: ❌ 5.8.1 - There is a newer version of WordPress available (5.8.2)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.27
PHP Post Max Size: 1 GB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 5.7.36-39-log
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: vnylife_wp_eeb_
Total Database Size: 8.63MB
Database Data Size: 5.97MB
Database Index Size: 2.66MB
vnylife_wp_eeb_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vnylife_wp_eeb_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vnylife_wp_eeb_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vnylife_wp_eeb_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vnylife_wp_eeb_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_actionscheduler_actions: Data: 0.17MB + Index: 0.19MB + Engine InnoDB
vnylife_wp_eeb_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_actionscheduler_logs: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
vnylife_wp_eeb_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
vnylife_wp_eeb_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
vnylife_wp_eeb_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vnylife_wp_eeb_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_options: Data: 1.28MB + Index: 0.06MB + Engine InnoDB
vnylife_wp_eeb_postmeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
vnylife_wp_eeb_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vnylife_wp_eeb_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
vnylife_wp_eeb_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vnylife_wp_eeb_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vnylife_wp_eeb_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vnylife_wp_eeb_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vnylife_wp_eeb_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
vnylife_wp_eeb_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vnylife_wp_eeb_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vnylife_wp_eeb_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 10
customize_changeset: 1
mailpoet_page: 1
page: 8
post: 1
product: 7
product_variation: 6
revision: 14
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Akismet Anti-Spam: by Automattic – 4.2.1
Bluehost: by Bluehost – 2.8.3
Google Listings and Ads: by WooCommerce – 1.9.0
Jetpack: by Automattic – 10.4
MailPoet 3 (New): by MailPoet – 3.75.1
Redis Object Cache: by Till Krüss – 2.0.22
WooCommerce Payments: by Automattic – 3.5.0
WooCommerce Shipping & Tax: by WooCommerce – 1.25.20
WooCommerce: by Automattic – 6.0.0
WPForms Lite: by WPForms – 1.7.1.2

### Inactive Plugins (1) ###

OptinMonster: by OptinMonster Team – 2.6.9

### Dropin Plugins (1) ###

object-cache.php: Redis Object Cache Drop-In

### Must Use Plugins (3) ###

Endurance Page Cache: by Mike Hansen – 2.1.2
SSO: by Garth Mortensen
Mike Hansen – 0.3

Update Manager: by  – 0.1

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #21 - /
Cart: #22 - /cart/
Checkout: #23 - /checkout/
My account: #24 - /my-account/
Terms and conditions: ❌ Page visibility should be public

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce Payments ###

Version: 3.5.0
Connected to WPCOM: Yes
Blog ID: 198626392
Account ID: acct_1K6lS62H1pad368h

### Action Scheduler ###

Complete: 485
Oldest: 2021-12-14 23:13:47 +0000
Newest: 2022-01-05 10:31:13 +0000

Pending: 6
Oldest: 2022-01-05 12:31:13 +0000
Newest: 2022-01-10 19:16:26 +0000


### Status report information ###

Generated at: 2022-01-05 11:15:24 +00:00
`

**Comment by EFFETTI** [comment] 2022-01-05 11:28
STEPS:

Under GENERAL tax calculation has been enabled.

Under TAX auto calculation has been enabled.
   ^>> Three, 3 Display pulldowns are Not functional:
   * Display prices in the shop
   * Display prices during cart and checkout
   * Display tax totals

**Comment by EFFETTI** [comment] 2022-01-05 11:32
note: There is NO obvious and simple way to UPDATE the version of WordPress the site is using.  BlueHost has been paid in advance for a ‘managed build’ site.  WHAT, exactly is being ‘managed’ is completely unclear.

**Comment by EFFETTI** [comment] 2022-01-05 16:30
note2: there are two, 2 issues;

1) described above and illustrated by the conditions presented in cart and on checkout for a [Dress] taxable item.

2) has Not yet been described, will be described here; the second product [Red Envelope] is Not taxable and can STILL NOT BE PURCHASED THROUGH THE SITE.

**Comment by rodelgc** [comment] 2022-01-06 06:51
Hi @EFFETTI,

Thank you for the feedback. 

Regarding the disabled tax options, that is the intended behavior whenever you use automatic tax calculation by the WooCommerce Shipping & Tax plugin as mentioned here: https://woocommerce.com/document/setting-up-taxes-in-woocommerce/#why-tax-options-are-greyed-out; and in here - https://woocommerce.com/document/woocommerce-shipping-and-tax/woocommerce-tax/#automated-tax-calculation

Regarding this one:
> Our site [VNY.life] will Not show the tax line upon checkout

I can see from your site that the tax line actually shows up just fine, it's just that it's showing $0.00. 

<img width="872" alt="Screen Shot 2022-01-06 at 2 43 16 PM" src="https://user-images.githubusercontent.com/4509348/148340846-2aeba7fa-e8f7-4cd8-ab78-242d4206ca52.png">


Please read this documentation to see why: 
 https://woocommerce.com/document/woocommerce-shipping-and-tax/woocommerce-tax/#automated-taxes-do-not-appear-to-be-calculating

I tried setting up a test site using a UK store address with Automated Taxes enabled via the WooCommerce Shipping & Tax plugin, and I see the VAT line (equivalent of the Tax line in US stores) showing up properly as you can see here:
<img width="716" alt="Screen Shot 2022-01-06 at 2 24 10 PM" src="https://user-images.githubusercontent.com/4509348/148340090-2daa1974-a9c0-4a28-a6b7-de9453c3f3a7.png">

I'm closing this issue for now because it seems that the behaviors you experienced are all expected. They're not bugs. If you have further questions about how automated taxes work, please reach our support channels instead.

- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

Please open a different issue regarding the Red Envelope not being purchasable, as I believe it's a totally different issue from the ones you've raised earlier. Thanks!

**Closed as completed by rodelgc** 2022-01-06 06:51 UTC
Labels: type: support request
