### ISSUE TITLE
Mandatory field “state” in checkout page didn’t work

### ISSUE THREAD

**Issue by AriannaIT** [woothemes/woocommerce#30547] opened 2021-08-20 10:04 UTC
Hi!
the mandatory field “state” in checkout page didn’t work.

I added the code to the child Theme.
<img width="1050" alt="code" src="https://user-images.githubusercontent.com/89250564/130217142-b7b19497-8cbb-416d-a6af-9fb3f45e1049.png">

I turn off all plugins, except woo commerce.
<img width="1070" alt="plugin" src="https://user-images.githubusercontent.com/89250564/130217193-33d3b440-40d5-488e-8f9d-fca0a99cf450.png">

I switch to Twenty twenty-one theme.
<img width="980" alt="checkout" src="https://user-images.githubusercontent.com/89250564/130217221-e2a892fb-e233-4b7e-8c82-1cfa32ff6740.png">

But the field remains optional. Any reason why?

In the last website (made 3 months ago) with the same theme and same plugins the code works. Maybe the cause is the new update of woo commerce?
Thanks for your support,
Ari

**Comment by tammullen** [comment] 2021-08-20 12:02
Duplicate of https://github.com/woocommerce/woocommerce/issues/30546

**Closed as completed by tammullen** 2021-08-20 12:02 UTC

**Comment by AriannaIT** [comment] 2021-08-20 12:22
I published the same message in two different place. Anyone answer. Except you... for closing.

**Comment by tammullen** [comment] 2021-08-20 12:37
Hi @AriannaIT this issue was closed because it is identical to https://github.com/woocommerce/woocommerce/issues/30546 which was posted 4 minutes prior to this issue. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
