### ISSUE TITLE
data.coupon_code undefined in checkout.js

### ISSUE THREAD

**Issue by froger-me** [woothemes/woocommerce#31477] opened 2021-12-18 23:41 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

`data.coupon_code` is `undefined` in `woocommerce/assets/js/frontend/checkout.js` line 671:

```JavaScript
$( document.body ).trigger( 'removed_coupon_in_checkout', [ data.coupon_code ] );
```

### Expected behavior

When `removed_coupon_in_checkout` is triggered, a `data` parameter contains the removed coupon code.

### Actual behavior

When `removed_coupon_in_checkout` is triggered, the `data` parameter is always `undefined`.

### Steps to reproduce

When removing a coupon on Checkout page:

1. Add the following in a script or console:

```JavaScript
jQuery(document.body).on( 'removed_coupon_in_checkout', function(e, data) {
	console.log(data);
});
```
2. See `undefined` in console
3. change `coupon_code` into `coupon`  in `woocommerce/assets/js/frontend/checkout.js` line 671
4. Start from 1. and see the actual coupon code in console

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://test.froger.me
Site address (URL): https://test.froger.me
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.26
PHP Post Max Size: 1,000 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.36-0ubuntu0.18.04.1
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: wp_
Total Database Size: 24.93MB
Database Data Size: 21.02MB
Database Index Size: 3.91MB
wp_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.09MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.22MB + Index: 0.11MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.16MB + Index: 0.13MB + Engine MyISAM
wp_admin_columns: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.07MB + Index: 0.03MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_matomo_access: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2012_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2013_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2014_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2015_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2016_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2017_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2018_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2019_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2020_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_01: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_02: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_03: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_04: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_05: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_06: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_07: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_08: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_09: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_10: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_11: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_blob_2021_12: Data: 0.17MB + Index: 0.05MB + Engine InnoDB
wp_matomo_archive_blob_2022_01: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_invalidations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_archive_numeric_2012_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2013_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2014_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2015_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2016_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2017_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2018_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2019_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2020_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_02: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_03: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_04: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_05: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_06: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_07: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_08: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_09: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_10: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_11: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2021_12: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_matomo_archive_numeric_2022_01: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_brute_force_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_custom_dimensions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_goal: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_locks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_logger_message: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_log_action: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_log_conversion: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_log_conversion_item: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_log_link_visit_action: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_log_profiling: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_log_visit: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_matomo_option: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_matomo_plugin_setting: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_privacy_logdata_anonymizations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_report: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_report_subscriptions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_segment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_sequence: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_session: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_shortcode: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_site: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_site_setting: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_site_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_tagmanager_container: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_tagmanager_container_release: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_tagmanager_container_version: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_matomo_tagmanager_tag: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_tagmanager_trigger: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_matomo_tagmanager_variable: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_matomo_tracking_failure: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_twofactor_recovery_code: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_user: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_user_dashboard: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_user_language: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_matomo_user_token_auth: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.46MB + Index: 0.06MB + Engine MyISAM
wp_postmeta: Data: 1.00MB + Index: 0.31MB + Engine MyISAM
wp_posts: Data: 1.95MB + Index: 0.05MB + Engine MyISAM
wp_simple_login_log: Data: 12.96MB + Index: 0.92MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.96MB + Index: 0.33MB + Engine MyISAM
wp_users: Data: 0.07MB + Index: 0.07MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_wc_order_stats: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 65
nav_menu_item: 14
page: 14
post: 1
product: 3
product_variation: 39
revision: 107
shop_coupon: 1
shop_order: 163
shop_order_refund: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Query Monitor: by John Blackbourn – 3.7.1
Adminimize: by Frank Bültge – 1.11.7
Classic Editor: by WordPress Contributors – 1.6.2
Admin Columns: by AdminColumns.com – 4.4.4
Simple Custom CSS and JS: by SilkyPress.com – 3.38.1
Disable WooCommerce Bloat: by ospiotr – 2.6.1
Duplicate Page: by mndpsingh287 – 4.4.7
Health Check & Troubleshooting: by The WordPress.org community – 1.4.5
Loco Translate: by Tim Whitlock – 2.5.5
Matomo Analytics - Ethical Stats. Powerful Insights.: by Matomo – 4.5.0
Simple Login Log: by Max Chirkov – 1.1.3
Advanced Editor Tools (previously TinyMCE Advanced): by Automattic – 5.6.0
Transients Manager: by WPBeginner – 2.0.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.66

Url Rewrite Analyzer: by DevlopEr – 1.3.1
User Role Editor: by Vladimir Garagulya – 4.60.2
WooCommerce Admin: by WooCommerce – 2.9.4
Direct Checkout for WooCommerce: by QuadLayers – 2.5.7
WooCommerce: by Automattic – 6.0.0
WP Crontrol: by John Blackbourn & crontributors – 1.12.0
WP Options Editor: by Mike Selander – 1.1

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #94 - /shop/
Cart: #95 - /cart/
Checkout: #96 - /checkout/
My account: #97 - /my-account/
Terms and conditions: /toc/

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Outdated Templates: ✔

### Action Scheduler ###

Complete: 807
Oldest: 2021-11-30 13:56:37 +0800
Newest: 2021-12-18 13:09:47 +0800

### Status report information ###

Generated at: 2021-12-19 07:34:18 +08:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment] 2021-12-20 07:24
Hi @froger-me,

Thank you for logging this issue. However, I couldn't reproduce the behavior you're expecting. 

In the screenshot below, notice that I've already changed `coupon_code` to `coupon` in the `checkout.js` file:
<img width="851" alt="Screen Shot 2021-12-20 at 3 17 07 PM" src="https://user-images.githubusercontent.com/4509348/146727727-f4ecaa1c-2570-4c2a-9bc2-f41e2f06e947.png">

Afterwards, I hard-refreshed the checkout page, re-applied the coupon, and then removed it (see video below). Notice that I still get `undefined` after removing the coupon.


https://user-images.githubusercontent.com/4509348/146727934-f9f3c92d-2d5e-4577-b0f0-198bd69cfa1b.mov

Maybe there's a step you missed to tell us? Please provide the complete steps to replicate both the actual and the expected behaviors.

**Comment by froger-me** [comment] 2021-12-24 08:15
Here are the steps I took, after making sure to re-download WooCommerce from the WordPress repository - they don't seem to be much different from what I can see in the video.

Steps to get the actual behavior:
- refresh the page
- enter the following code in the console
```javascript
jQuery(document.body).on( 'removed_coupon_in_checkout', function(e, data) {
	console.log(data);
});
```
- click the "Click here to enter your code" link
- enter a valid coupon code
- click "Apply Coupon"
- see the coupon applied in the "Your order" section
- click the "Remove" link
- see `undefined` in the console

Whether the expected behavior with the steps below provided as a potential solution can be reproduced or not, isn't getting `undefined` instead of the coupon code from the `data` parameter of the callback of the `removed_coupon_in_checkout` event an issue regardless?

Steps to get the expected behavior:
- edit `checkout.js` on line 671 and change `data.coupon_code` to `data.coupon` to match the `coupon` attribute of the `data` variable initialized on line 657
- refresh the page
- enter the following code in the console
```javascript
jQuery(document.body).on( 'removed_coupon_in_checkout', function(e, data) {
	console.log(data);
});
```
- click the "Click here to enter your code" link
- enter a valid coupon code
- click "Apply Coupon"
- see the coupon applied in the "Your order" section
- click the "Remove" link
- see the coupon code in the console

**Comment by lanej0** [comment] 2022-01-11 19:38
Hi @froger-me,

Thanks for the added info, but I'm having the same results as @rodelgc -- I can't seem to reproduce this issue when I follow your steps.  I noticed that you have a number of plugins installed.  I wonder if any of those are affecting the JS that's being rendered in the browser.  Any chance you could try disabling those and seeing if you can still reproduce this issue?

**Comment by froger-me** [comment] 2022-01-12 02:39
```
### WordPress Environment ###

WordPress address (URL): https://test.froger.me
Site address (URL): https://test.froger.me
WC Version: 6.1.0
REST API Version: heavy_check_mark 6.1.0
WC Blocks Version: heavy_check_mark 6.5.1
Action Scheduler Version: heavy_check_mark 3.4.0
WC Admin Version: heavy_check_mark 3.0.3
Log Directory Writable: heavy_check_mark
WP Version: 5.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: heavy_check_mark
WP Cron: heavy_check_mark
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.34
PHP Post Max Size: 516 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.80.0
OpenSSL/1.1.1m

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 512 MB
Default Timezone is UTC: heavy_check_mark
fsockopen/cURL: heavy_check_mark
SoapClient: heavy_check_mark
DOMDocument: heavy_check_mark
GZip: heavy_check_mark
Multibyte String: heavy_check_mark
Remote Post: heavy_check_mark
Remote Get: heavy_check_mark

### Database ###

WC Database Version: 6.1.0
WC Database Prefix: wp_
Total Database Size: 1.51MB
Database Data Size: 1.19MB
Database Index Size: 0.32MB
wp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 0.90MB + Index: 0.06MB + Engine MyISAM
wp_postmeta: Data: 0.09MB + Index: 0.06MB + Engine MyISAM
wp_posts: Data: 0.09MB + Index: 0.02MB + Engine MyISAM
wp_signups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 12
page: 24
post: 4
product: 1
revision: 93
shop_coupon: 1
shop_order: 26
um_directory: 1
um_form: 4
wp_stream_alerts: 1

### Security ###

Secure connection (HTTPS): heavy_check_mark
Hide errors from visitors: xError messages should not be shown to visitors.

### Active Plugins (2) ###

Cloudflare: by Cloudflare
Inc. – 4.7.0

WooCommerce: by Automattic – 6.1.0

### Inactive Plugins (34) ###

// irrelevant - no impact on js or woocommerce

### Must Use Plugins (2) ###

// irrelevant - no impact on js or woocommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: CNY (¥)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #120 - /shop/
Cart: #121 - /cart/
Checkout: #122 - /checkout/
My account: #123 - /my-account/
Terms and conditions: x Page not set

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: x – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: heavy_check_mark

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 54
Oldest: 2022-01-12 06:08:55 +0800
Newest: 2022-01-12 09:56:36 +0800

### Status report information ###

Generated at: 2022-01-12 10:18:17 +08:00
```

See the list of active plugins above - Cloudflare (that's only to get `https`) & WooCommerce only.  
The behavior is still happening:  

https://user-images.githubusercontent.com/3622456/149055454-2dc4efd0-a0e1-40fd-94e1-8c0c60a1ca03.mp4


@lanej0 please note the comment:

> Whether the expected behavior with the steps below provided as a potential solution can be reproduced or not, isn't getting undefined instead of the coupon code from the data parameter of the callback of the removed_coupon_in_checkout event an issue regardless?

What @rodelgc refers to is not being able to use the proposed solution in the OP.
The expected behavior is for the coupon code `data.coupon_code` to be logged in the console, and right now the *untouched* code as shipped logs `undefined`.

**Comment by froger-me** [comment] 2022-01-12 02:50
https://user-images.githubusercontent.com/3622456/149055117-94773d5b-4e8d-44d6-b702-d612f599ea9e.mp4

**Comment by lanej0** [comment] 2022-01-12 22:57
Hi @froger-me,

I appreciate you working with us on this.  The reason we're pushing so hard to be able to get steps to reproduce it is that it really helps the development team track down whether there is an issue here, or whether things are working as intended.  Additionally, it helps them to isolate the issue in case a fix is needed.

Both @rodelgc and I are able to see the `undefined` you're reporting, the part we're having trouble with is the fix you proposed -- we're still getting `undefined` returned when `data.coupon_code` is changed to `data.coupon`.

It might be useful to take a step back for a second and just ask -- what are you trying to accomplish in retrieving the coupon code this way? There are alternatives (such as the API) that might be a bit more future-proof and simpler to implement.  Is this for an existing integration/theme/plugin?

**Comment by froger-me** [comment] 2022-01-13 00:04
Hi @lanej0 ,

Taking a step back, I have looked at the entire function as a whole and added my comments where the issue is, purely from a logical standpoint.

I have specific coupons automatically added to the cart in my business logic ; when one of these is applied, the coupon form is hidden by my custom code. However, when the user removes that specific coupon, my application needs to re-enable access to the form, and log the event with a third party analytics tool (and that's where the removed coupon code is needed, because my custom logic passes it to the tool).

How my integration is planning to use a built-in feature does not seem that relevant - I already found a workaround in my own code base, I am merely reporting an issue ;).

```javascript
		remove_coupon: function( e ) {
			e.preventDefault();

			var container = $( this ).parents( '.woocommerce-checkout-review-order' ),
				coupon    = $( this ).data( 'coupon' );

			container.addClass( 'processing' ).block({
				message: null,
				overlayCSS: {
					background: '#fff',
					opacity: 0.6
				}
			});
			// This is the definition of the "data" object passed to the event ; it has 2 properties:
			// - "security"
			// - "coupon"
			// Please note how it does not have a "coupon_code" property defined, neither here nor at any point below
			var data = {
				security: wc_checkout_params.remove_coupon_nonce,
				coupon:   coupon
			};

			$.ajax({
				type:    'POST',
				url:     wc_checkout_params.wc_ajax_url.toString().replace( '%%endpoint%%', 'remove_coupon' ),
				data:    data,
				success: function( code ) {
					$( '.woocommerce-error, .woocommerce-message' ).remove();
					container.removeClass( 'processing' ).unblock();

					if ( code ) {
						$( 'form.woocommerce-checkout' ).before( code );

						// This is the event ; its argument is an array containing the item "data.coupon_code"
						// The "coupon_code" property of the "data" object is never defined anywhere, but there is a "coupon" property defined above
						$( document.body ).trigger( 'removed_coupon_in_checkout', [ data.coupon_code ] );
						$( document.body ).trigger( 'update_checkout', { update_shipping_method: false } );

						// Remove coupon code from coupon field
						$( 'form.checkout_coupon' ).find( 'input[name="coupon_code"]' ).val( '' );
					}
				},
				error: function ( jqXHR ) {
					if ( wc_checkout_params.debug_mode ) {
						/* jshint devel: true */
						console.log( jqXHR.responseText );
					}
				},
				dataType: 'html'
			});
		}
```

I admit it was a mistake to try and provide a fix here because it creates confusion, and should have kept the OP clean and report the issue only, so that the development team can take care of it without assumptions. Please disregard the suggestion in the OP. My apologies.

**Comment by froger-me** [comment] 2022-01-13 04:28
If this helps, please see the contrast with this other function found in the same file:

```javascript
		submit: function() {
			var $form = $( this );

			if ( $form.is( '.processing' ) ) {
				return false;
			}

			$form.addClass( 'processing' ).block({
				message: null,
				overlayCSS: {
					background: '#fff',
					opacity: 0.6
				}
			});
			// This is the definition of the "data" object passed to the event ; it has 2 properties:
			// - "security"
			// - "coupon_code"
			// Please note the "coupon_code" property is defined, and used below
			var data = {
				security:		wc_checkout_params.apply_coupon_nonce,
				coupon_code:	$form.find( 'input[name="coupon_code"]' ).val()
			};

			$.ajax({
				type:		'POST',
				url:		wc_checkout_params.wc_ajax_url.toString().replace( '%%endpoint%%', 'apply_coupon' ),
				data:		data,
				success:	function( code ) {
					$( '.woocommerce-error, .woocommerce-message' ).remove();
					$form.removeClass( 'processing' ).unblock();

					if ( code ) {
						$form.before( code );
						$form.slideUp();
						// This is the event ; its argument is an array containing the item "data.coupon_code"
						// The "coupon_code" property of the "data" object is defined
						$( document.body ).trigger( 'applied_coupon_in_checkout', [ data.coupon_code ] );
						$( document.body ).trigger( 'update_checkout', { update_shipping_method: false } );
					}
				},
				dataType: 'html'
			});

			return false;
		},
```

**Comment by barryhughes** [comment] 2022-03-10 01:22
Agreed, marking as a bug. @froger-me if you wish to submit a PR please do and/or the core team will get to this in due course.

**Closed as completed** 2022-04-18 19:18 UTC
Labels: Bug, Checkout, plugin: woocommerce
