### ISSUE TITLE
Blocks-related assets versioning suffixed with "-dev"

### ISSUE THREAD

**Issue by asafm7** [woothemes/woocommerce#44319] opened 2024-02-02 16:05 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello.

Is there a reason the version is suffixed with "-dev" here?

https://github.com/woocommerce/woocommerce/blob/5937b3dec1651fd8f9d2eb7d9dd33a4a636bb9ce/plugins/woocommerce/src/Blocks/Package.php#L112

### Expected behavior

Version without a suffix.

### Actual behavior

Version with a suffix.

### Steps to reproduce

See the code link.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://hobbies4.life
Site address (URL): https://hobbies4.life
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.2.15
PHP Post Max Size: 64 MB
PHP Time Limit: 1800
PHP Max Input Vars: 1800
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.16-MariaDB-cll-lve
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: whHhGW_
Total Database Size: 62.21MB
Database Data Size: 44.29MB
Database Index Size: 17.92MB
whHhGW_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
whHhGW_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
whHhGW_ahrefs_seo_content: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
whHhGW_ahrefs_seo_snapshots: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_aryo_activity_log: Data: 1.52MB + Index: 3.36MB + Engine InnoDB
whHhGW_blc_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_blc_instances: Data: 1.52MB + Index: 0.23MB + Engine InnoDB
whHhGW_blc_links: Data: 6.52MB + Index: 0.86MB + Engine InnoDB
whHhGW_blc_synch: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_bwt_failed_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_bwt_passed_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_cmplz_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
whHhGW_indexnow_failed_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_indexnow_passed_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_litespeed_avatar: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_litespeed_crawler: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_litespeed_crawler_blacklist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_litespeed_url: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
whHhGW_litespeed_url_file: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
whHhGW_options: Data: 3.34MB + Index: 0.19MB + Engine InnoDB
whHhGW_postmeta: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
whHhGW_posts: Data: 2.48MB + Index: 0.20MB + Engine InnoDB
whHhGW_relevanssi: Data: 3.52MB + Index: 6.52MB + Engine InnoDB
whHhGW_relevanssi_log: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
whHhGW_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_termmeta: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
whHhGW_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
whHhGW_term_relationships: Data: 0.13MB + Index: 0.08MB + Engine InnoDB
whHhGW_term_taxonomy: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
whHhGW_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_usermeta: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
whHhGW_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_vrts_alerts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_vrts_tests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
whHhGW_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
whHhGW_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_orders: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
whHhGW_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_product_attributes_lookup: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
whHhGW_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
whHhGW_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wfblockediplog: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_wfconfig: Data: 0.48MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wffilemods: Data: 10.52MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfhits: Data: 1.11MB + Index: 0.23MB + Engine InnoDB
whHhGW_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_wfknownfilelist: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
whHhGW_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wflogins: Data: 0.41MB + Index: 0.16MB + Engine InnoDB
whHhGW_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
whHhGW_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfnotifications: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
whHhGW_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_yith_wcwl: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
whHhGW_yith_wcwl_lists: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
whHhGW_yoast_indexable: Data: 0.19MB + Index: 0.09MB + Engine InnoDB
whHhGW_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_yoast_prominent_words: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_yoast_seo_links: Data: 0.14MB + Index: 0.09MB + Engine InnoDB

### Post Type Counts ###

acf-field: 85
acf-field-group: 4
attachment: 256
feedback: 13
oembed_cache: 75
page: 16
post: 18
product: 76
revision: 198
wp_block: 3
wp_global_styles: 7
wp_navigation: 2
wp_template: 11
wp_template_part: 3
wpcode: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

ManageWP - Worker: by GoDaddy – 4.9.19
Query Monitor: by John Blackbourn – 3.15.0
ACF Content Analysis for Yoast SEO: by Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 3.1

Advanced Custom Fields PRO: by WP Engine – 6.2.5
Activity Log: by Activity Log Team – 2.9.0
Bing Webmaster Url Submission: by Bing Webmaster – 1.0.13
Broken Link Checker: by WPMU DEV – 2.2.4
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 6.5.6
Create Block Theme: by WordPress.org – 1.13.8
Dominant Color Images: by WordPress Performance Team – 1.0.1
Site Kit by Google: by Google – 1.119.0
hCaptcha for WordPress: by hCaptcha – 3.8.1
IndexNow: by Microsoft Bing – 1.0.1
Instant Images: by Darren Cooney – 6.1.1
Jetpack: by Automattic – 13.0
LiteSpeed Cache: by LiteSpeed Technologies – 6.0.0.1
Loco Translate: by Tim Whitlock – 2.6.6
Mailgun: by Mailgun – 1.9.7
Performance Lab: by WordPress Performance Team – 2.8.0
Relevanssi: by Mikko Saari – 4.22.0
Rollbar: by Rollbar – 2.7.1
Tidio Chat: by Tidio Ltd. – 6.0.13
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.23.16

VRTs – Visual Regression Tests: by Bleech – 1.7.1
WooCommerce: by Automattic – 8.5.2
Wordfence Security: by Wordfence – 7.11.1
Yoast SEO: by Team Yoast – 21.9.1
WP Crontrol: by John Blackbourn & crontributors – 1.16.1
YITH WooCommerce Wishlist: by YITH – 3.29.0

### Inactive Plugins (2) ###

Cloudflare: by Cloudflare
Inc. – 4.12.4

WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.3.0

### Dropin Plugins (3) ###

db.php: Query Monitor Database Class (Drop-in)
maintenance.php: maintenance.php
object-cache.php: Performance Lab Server Timing Object Cache Drop-In

### Must Use Plugins (2) ###

H4L MU Plugin: by  –
ManageWP - Worker Loader: by GoDaddy – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #653 - /
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: #656 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Loudness Child Theme
Version: 0.0.1
Author URL: 
Child Theme: ✔
Parent Theme Name: Loudness
Parent Theme Version: 1.0.5
Parent Theme Author URL: https://automattic.com
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-03 14:56:39 +00:00
Options: ✔
Notes: 93
Onboarding: skipped

### Action Scheduler ###

Complete: 75
Oldest: 2024-01-04 12:58:33 +0000
Newest: 2024-02-02 15:15:02 +0000

Failed: 12
Oldest: 2023-04-12 15:59:56 +0100
Newest: 2024-02-01 19:47:15 +0000

Pending: 1
Oldest: 2024-02-03 15:15:02 +0000
Newest: 2024-02-03 15:15:02 +0000

### Status report information ###

Generated at: 2024-02-02 16:03:04 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment] 2024-02-05 19:59
Hi @asafm7 

Thanks for asking this.

This is because the last released WooCommerce Blocks standalone plugin version was 11.7.0; after this the code for Blocks was added to this monorepo.
When we released a WooCommerce Blocks standalone plugin, after the release, the plugin’s version was automatically bumped to the next one up to release with a -dev suffix. In this case 11.8.0-dev.

It needs to remain for backward compatibility in case anyone is checking for a version of Blocks for compatibility

I'm going to close this for now as it is working as intended. Free feel to comment if there is anything else you want to add.

**Closed as completed by tammullen** 2024-02-05 19:59 UTC
Labels: Bug, type: community contribution
