### ISSUE TITLE
WordPress "Thank you" button links to JavaScript snippet (open in new tab)

### ISSUE THREAD

**Issue by strarsis** [woothemes/woocommerce#32193] opened 2022-01-21 16:35 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When the `href` (= `https://www.example.com/wp/wp-admin/?service-worker&wc-hide-notice=update&_wc_notice_nonce=[...]`) of the `Thank you` button after a successful database update/maintenance task is followed (e.g. when opening it in a new tab), a JavaScript snippet is sent as response (a white page with the JavaScript text only).

````
/* global self */

// https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/skipWaiting
self.addEventListener( 'install', function ( event ) {
	event.waitUntil( self.skipWaiting() );
} );

// https://developer.mozilla.org/en-US/docs/Web/API/Clients/claim
self.addEventListener( 'activate', function ( event ) {
	event.waitUntil( self.clients.claim() );
} );

// Necessary for Chrome to show the install button.
self.addEventListener( 'fetch', function () {} );
````

### Expected behavior

The `Thank you` button `href` returns back to the original page on which this message was shown, dismissing it on the server-side.

### Actual behavior

A JavaScript snippet is sent as response, the backend is missing (white page with the JavaScript text only).

### Steps to reproduce

1. Trigger a database update/maintenance task and let it complete successfully.
2. Follow the `href` of the `Thank you` button (e.g. by open the link in a new tab).
Note the response with a JavaScript snippet (JavaScript text on a white page).

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.example.com/wp
Site address (URL): https://www.example.com
WC Version: 6.1.1
REST API Version: ✔ 6.1.1
WC Blocks Version: ✔ 6.5.2
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ✔
WP Version: 5.8.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: de_DE_formal
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.19.4
PHP Version: 7.4.21
PHP Post Max Size: 150 MB
PHP Time Limit: 600
PHP Max Input Vars: 6000
cURL Version: 7.68.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.6-MariaDB-1:10.5.6+maria~focal
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.1
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 10.36MB
Datenbank-Datengröße: 6.36MB
Datenbank-Indexgröße: 4.00MB
wp_woocommerce_sessions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lockdowns: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_login_fails: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Daten: 2.17MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Daten: 0.39MB + Index: 0.09MB + Engine InnoDB
wp_posts: Daten: 1.47MB + Index: 0.06MB + Engine InnoDB
wp_redirection_404: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_stream: Daten: 0.13MB + Index: 0.13MB + Engine InnoDB
wp_stream_meta: Daten: 0.42MB + Index: 0.67MB + Engine InnoDB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsal_metadata: Daten: 0.28MB + Index: 0.47MB + Engine InnoDB
wp_wsal_occurrences: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Daten: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 27
page: 14
post: 1
product: 9
revision: 40
woovouchers: 6
wp_global_styles: 2
wp_navigation: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

WP Activity Log for Yoast SEO: von WP White Security – 1.2.0
Adminimize: von Frank Bültge – 1.11.7
PublishPress Blocks: von PublishPress – 2.11.3
EditorsKit: von Munir Kamal – 1.33.3
Disable Blog: von Joshua Nelson – 0.4.10
Disable Comments: von WPDeveloper – 2.3.2
Dublin Core Title Metatag: von Web Design Hosting Agentur – 1.3.0
Favicon by RealFaviconGenerator: von Philippe Bernard – 1.3.29
Gosign — Gallery Box Block: von Gosign.de – 2.0.1
Gutenberg: von Gutenberg-Team – 12.4.0
Jetpack: von Automattic – 10.5
Login LockDown: von Michael VanDeMar – v1.8.1
Meta Tag Manager: von Marcus Sykes – 3.0.2
PayPal for WooCommerce: von Angell EYE – 2.5.19
Preferred Languages: von Pascal Birchler – 1.8.0
Redirection: von John Godley – 5.2.1
Reusable Blocks Extended: von audrasjb – 0.8
Simple Page Ordering: von Jake Goldman
10up – 2.3.4

Stream: von XWP – 3.8.2
SVG dimensions fix: von Web Design Hosting Agentur GbR – 2.0.1
SVG Support: von Benbodhi – 2.3.21
Under Construction: von WebFactory Ltd – 3.92
User Role Editor: von Vladimir Garagulya – 4.61
Germanized für WooCommerce: von vendidero – 3.8.0
WooCommerce PDF Vouchers - Multi Language Characters Support: von WPWeb – 1.0.6
WooCommerce - PDF Vouchers - Roles fix: von WDHA – 1.0.1
WooCommerce - PDF Vouchers - Translations: von WDHA – 2.1.0
WooCommerce - PDF Vouchers: von WPWeb – 4.3.2
WooCommerce: von Automattic – 6.1.1
Yoast SEO: von Team Yoast – 17.9
WP Activity Log for WooCommerce: von WP White Security – 1.3.1
WP Mail SMTP: von WPForms – 3.2.1
WP Redis: von Pantheon
Josh Koenig
Matthew Boynes
Daniel Bachhuber
Alley Interactive – 1.1.4

WP Activity Log: von WP White Security – 4.3.4
wp-Typography: von Peter Putzer – 5.7.2

### Inactive Plugins (1) ###

Gosign — Google Maps Block: von Gosign.de – 2.0.1

### Dropin Plugins (1) ###

object-cache.php: object-cache.php

### Must Use Plugins (2) ###

Bedrock Autoloader: von Roots – 1.0.3
Register Theme Directory: von Roots – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: woocommerce/woocommerce#50 - /shop/
Warenkorb: woocommerce/woocommerce#51 - /shop/warenkorb/
Kasse: woocommerce/woocommerce#52 - /shop/kasse/
Mein Konto: woocommerce/woocommerce#53 - /shop/mein-konto/
Allgemeine Geschäftsbedingungen: woocommerce/woocommerce#62 - /shop/agb/

### Theme ###

Name: Some Site Theme
Version: 1.0.0
Author URL: https://www.example2.com
Child Theme: ❌ – Wenn Sie WooCommerce mit einem Theme
das Sie nicht selbst entwickelt haben
an eigene Bedürfnisse anpassen
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie Sie ein Child-Theme erstellen (engl.)

WooCommerce Support: ❌ Nicht deklariert

### Templates ###

Overrides: –

### Action Scheduler ###

Abgeschlossen: 81
Oldest: 2022-01-09 14:50:02 +0000
Newest: 2022-01-21 03:06:03 +0000

Ausstehend: 3
Oldest: 2022-01-22 02:04:03 +0000
Newest: 2022-01-22 03:04:03 +0000

### Status report information ###

Generated at: 2022-01-21 17:36:28 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lanej0** [comment] 2022-01-21 18:16
Hi @strarsis,

Thank you for reporting the issue. This issue looks really similar to this issue: woocommerce/woocommerce#32241 which is being handled over in the `woocommerce-admin` repository. 

I am going to move your bug report there so that the right team could take a look further.

**Comment by rrennick** [comment] 2023-09-29 19:33
I'll close this as a duplicate of #32241.

**Closed as completed by rrennick** 2023-09-29 19:33 UTC
Labels: Bug, plugin: woocommerce, Wayfinding
