### ISSUE TITLE
prime_caches_for_orders and MetaBoxes\CustomerHistory cause huge queries for high volume customer orders

### ISSUE THREAD

**Issue by liamidentify** [woothemes/woocommerce#44105] opened 2024-01-25 22:55 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We operate a trade based WooCommerce website where a single user can place several hundred orders per day.

We are noticing performance issues for our largest customers causing memory exhaustion when:

a) the customer places an order via the front-end (due to prime_caches_for_orders)
The query below in the function generates large, unmanageable queries:
![image](https://github.com/woocommerce/woocommerce/assets/6523572/a7994832-279b-45e3-b05d-9f0fb3e6f4dd)
![image](https://github.com/woocommerce/woocommerce/assets/6523572/b251cd23-2aca-477f-843d-641ee9caa28e)

b) the admin view a customer order on the back-end (due to the CustomerHistory Metabox)
Similarly to the above, this generates a similar query.

### Expected behavior

Customers regardless of number of orders should not be impacted by these operations on the front-end.

### Actual behavior

Memory exhaustion causing the order placing to fail, or unable to view in the admin area.

### Steps to reproduce

Generate approx 15k orders for 1 customer, attempt to place a new order / view an order in the admin

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://[removed].com
Site address (URL): https://[removed].com
WC Version: 8.5.1
REST API Version: ✔ 8.5.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 16 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.1.27
PHP Post Max Size: 192 MB
PHP Time Limit: 300
PHP Max Input Vars: 8192
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.5.23-MariaDB
Max Upload Size: 192 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.1
WC Database Prefix: wp_
Total Database Size: 1672.56MB
Database Data Size: 1242.24MB
Database Index Size: 430.32MB
wp_woocommerce_sessions: Data: 2.31MB + Index: 0.13MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 19.46MB + Index: 10.71MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 252.60MB + Index: 86.88MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 9.89MB + Index: 2.64MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 4.89MB + Index: 3.53MB + Engine MyISAM
wp_aryo_activity_log: Data: 3.02MB + Index: 0.00MB + Engine InnoDB
wp_cf7dbplugin_st: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cf7dbplugin_submits: Data: 0.12MB + Index: 0.03MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_comments: Data: 103.16MB + Index: 38.25MB + Engine MyISAM
wp_cron_logs: Data: 6.02MB + Index: 1.56MB + Engine InnoDB
wp_custom_skus: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_dgwt_wcas_index: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wp_dgwt_wcas_invindex_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_dgwt_wcas_invindex_doclist: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_dgwt_wcas_invindex_wordlist: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_dgwt_wcas_var_index: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_ewwwio_images: Data: 195.12MB + Index: 71.11MB + Engine MyISAM
wp_ewwwio_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_groups_capability: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wp_groups_group: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_groups_group_capability: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_groups_user_capability: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_groups_user_group: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_litespeed_img_optm: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_litespeed_img_optming: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 2.17MB + Index: 0.15MB + Engine MyISAM
wp_postmeta: Data: 579.06MB + Index: 183.31MB + Engine MyISAM
wp_posts: Data: 36.12MB + Index: 10.98MB + Engine MyISAM
wp_termmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_usermeta: Data: 0.77MB + Index: 0.43MB + Engine MyISAM
wp_users: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp_wcsp_global_discount_rule_mapping: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wcsp_group_category_pricing_mapping: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wcsp_role_category_pricing_mapping: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wcsp_user_category_pricing_mapping: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_addresses: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 1.80MB + Index: 2.91MB + Engine MyISAM
wp_wc_order_operational_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 12.27MB + Index: 8.73MB + Engine MyISAM
wp_wc_order_stats: Data: 8.51MB + Index: 3.95MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 4.23MB + Index: 4.47MB + Engine MyISAM
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wdr_order_discounts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wdr_order_item_discounts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wdr_rules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfpklist_template_data: Data: 0.06MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_table_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wt_iew_action_history: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wt_iew_mapping_template: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wusp_group_product_price_mapping: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wusp_role_pricing_mapping: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_wusp_rules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wusp_subrules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wusp_user_pricing_mapping: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yikes_easy_mc_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_indexable: Data: 0.10MB + Index: 0.03MB + Engine MyISAM
wp_yoast_indexable_hierarchy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_primary_term: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM

### Post Type Counts ###

acf-field: 169
acf-field-group: 12
afreg_fields: 7
attachment: 50713
case_study: 3
def_reg_fields: 10
nav_menu_item: 39
news: 5
page: 17
post: 3
product: 110
product_variation: 148
revision: 136
shop_coupon: 18
shop_order: 98109
shop_order_refund: 69
testimonial: 4
testimonials: 3
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment] 2024-02-01 11:12
Hi @liamidentify!

Thanks for the report. We've tagged this high priority and will be looking into ways to make this more performant.

**Comment by lkraav** [comment] 2024-02-03 09:36
Yes, there is still a lot of database size naivete left both in WC core, but also in marketplace plugins.

Developers just don't test their ideas with large datasets like 10+M row post table, 40+M row postmeta table etc. Naive joins can take hours to resolve there, completely killing the site for the users. Fortunately HPOS and smaller efforts elsewhere are now being made to address such.

Regardless of the outcome here @liamidentify, you might be interested in https://wordpress.org/plugins/index-wp-mysql-for-speed/

Cluster indexing on modern MySQL/MariaDB should provide a significant performance boost vs the current overly conservative backwards compatibility approach by WP and WC core.

**Comment by vedanshujain** [comment] 2024-02-05 10:12
Note that if we are loading `prime_caches_for_orders` with this many orders, it's probably coming from unnecessary loading very large number of orders in the first place. Looks like this particular issue is the same as #44318, while we work on a fix, disabling order attribution feature could be used as a workaround.

**Comment by vedanshujain** [comment] 2024-05-06 16:27
Closing this since underlying issue #44318 was fixed. This query appearing for a large number of orders is just a symptom of loading very large number of order in the first place. Even if we fix it, this query will just turn into n+1 queries down the line. Closing this issue, but if this reported again, we will want to find the callee function that is loading large number of orders and fix it.

**Comment by KIKOmanasijev** [comment] 2024-05-25 20:34
We are having the same issue on our website as well. This query is killing our website when we are trying to open an order from a customer with a lot of sales. In this example, our customer has over 7000 orders and this causes ~6500 queries to be executed & memory usage goes up to 1GB.

<img width="221" alt="image" src="https://github.com/woocommerce/woocommerce/assets/34198639/82d22b54-90fa-4d4e-a8a8-70030f77f146">

We definitely don't need the Customer History metabox (which we think it's causing the issue), so is there an action to maybe completely disable it, and prevent the huge amount of SQL queries to be executed?

**Comment by trajche** [comment] 2024-05-25 20:36
We are having this issue as well! The problem is happening due to the same customer having a large history of orders (1mln+ worth).

**Comment by vedanshujain** [comment] 2024-05-27 10:32
@KIKOmanasijev @trajche would you be able to share more details about this? Atleast the WC version you are using + if possible the callee graph of this query. @KIKOmanasijev seems to be using query monitor, which would have this callee graph.

**Comment by KIKOmanasijev** [comment] 2024-05-27 13:09
<img width="1509" alt="image" src="https://github.com/woocommerce/woocommerce/assets/34198639/a3e1cfa1-c9eb-4066-8287-eedb02f1f216">

Of course @vedanshujain. 

We are using:
- WC version: 8.5.1
- PHP version: 8.1.28

**Comment by vedanshujain** [comment] 2024-05-27 15:37
@KIKOmanasijev I see, there was an issue in 8.5.1 for this, which was fixed in 8.6 (See PR https://github.com/woocommerce/woocommerce/pull/44318). Can you try upgrading, it should fix this issue

**Comment by vedanshujain** [comment] 2024-06-04 09:12
Closing the issue based on above for repo gardening, but don't hesitate to reach and will re-open again.

**Closed as completed by vedanshujain** 2024-06-04 09:12 UTC
Labels: Bug, Order Management, type: community contribution, Performance
