### ISSUE TITLE
Number field is missing on the Woo-order-->Screen Option-->"Number of items per page" (Mobile view).

### ISSUE THREAD

**Issue by apeksha10** [woothemes/woocommerce#31501] opened 2021-12-23 06:11 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Number field is missing on the Woo-order-->Screen Option-->"Number of items per page" (Mobile view).

### Expected behavior

Number field should be present on the Woo-order-->Screen Option-->"Number of items per page" (Mobile view).

### Actual behavior

When I tried to change the number field then it's not working in the mobile view. 

### Steps to reproduce

1. Go to  WooCommerce --> Order Page
2. Click on the Screen option
3. Mobile view, Number field is missing on the "Number of items per page"

See the video: https://www.screencast.com/t/IwtOHuoZpr

![LWR_Recording](https://user-images.githubusercontent.com/20852893/147196255-ce42eebc-a478-423c-8834-aa4a35971be5.png)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://orderdeliverydate.local
Site address (URL): http://orderdeliverydate.local
WC Version: 6.1.0
REST API Version: ✔ 6.1.0
WC Blocks Version: ✔ 6.5.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.0-rc.1
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.64.0
OpenSSL/1.1.1b

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.0
WC Database Prefix: wp_
Total Database Size: 34.23MB
Database Data Size: 32.16MB
Database Index Size: 2.07MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_abandoned_cart_aelia_currency: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_abandoned_cart_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ac_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_atc_rules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ac_connector_sync: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ac_email_templates: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_ac_email_templates_lite: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_ac_guest_abandoned_cart_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ac_guest_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_link_clicked_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_notifications_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_opened_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_sent_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ac_sent_history_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_statistics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ac_tiny_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.14MB + Index: 0.19MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wp_booking_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_booking_order_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 30.05MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.34MB + Index: 0.25MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
bkap_booking: 12
page: 7
post: 2
product: 18
product_variation: 7
revision: 1
shop_order: 47
wc_pickup_location: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

WooCommerce: by Automattic – 6.1.0-beta.1
WP Mail SMTP: by WPForms – 3.2.1

### Inactive Plugins (10) ###

Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 5.10.0
Abandoned Cart Pro for WooCommerce: by Tyche Softwares – 8.17.0
Booking & Appointment Plugin for WooCommerce: by Tyche Softwares – 5.10.1
Order Delivery Date Pro for WooCommerce: by Tyche Softwares – 9.27.3
Pickup Date Addon: by Tyche Softwares – 1.2
Product Delivery Date Pro for WooCommerce: by Tyche Softwares – 3.10.3
WooCommerce Beta Tester: by WooCommerce – 2.0.5
WooCommerce Local Pickup Plus: by SkyVerge – 2.9.3
WooCommerce Table Rate Shipping: by Bolder Elements – 4.2.1
WPForms Lite: by WPForms – 1.7.1.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: storefront/woocommerce/emails\admin-new-order.php

### Action Scheduler ###

Complete: 502
Oldest: 2021-12-22 04:50:56 +0000
Newest: 2021-12-23 05:57:22 +0000

Pending: 3
Oldest: 2021-12-23 06:12:22 +0000
Newest: 2021-12-27 08:30:00 +0000

### Status report information ###

Generated at: 2021-12-23 11:36:13 +05:30
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment] 2021-12-27 09:33
Hi @apeksha10 ,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using WooCommerce 6.0.0 version and WordPress 5.8.2 version. 

Please find below screencast for reference :


https://user-images.githubusercontent.com/94531721/147442738-0d00cfab-ff17-489c-8df4-339e2125125f.mp4


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by apeksha10** [comment] 2021-12-28 04:52
@swatipawarGS, thanks for letting me know.

**Comment by barryhughes** [comment] 2022-05-19 22:27
Thanks for reporting, @apeksha10.

To make sure I am understanding: the problem here is not that the number input is *missing,* as such, it's that the arrow buttons have gone?

<img width="290" alt="android-chrome-items-per-page" src="https://user-images.githubusercontent.com/3594411/169414450-499312b7-133c-4707-9b5e-c8a41e5aea1a.png">

I'm not sure this should be regarded as a bug; I think the browser is making an intelligent choice about how to render the input (arrow buttons perhaps being less useful in this situation than the numeric input it provides).

Am I misunderstanding? I'm going to provisionally close this, but do reply if you disagree and we can certainly re-evaluate.

**Closed as completed by barryhughes** 2022-05-19 22:27 UTC
Labels: Bug, plugin: woocommerce

**Comment by apeksha10** [comment] 2022-05-24 04:56
Thanks for your quick reply @barryhughes,

>To make sure I am understanding: the problem here is not that the number input is missing, as such, it's that the arrow buttons have gone?

True 

>I'm not sure this should be regarded as a bug; I think the browser is making an intelligent choice about how to render the input (arrow buttons perhaps being less useful in this situation than the numeric input it provides).

I think it's better if we have a button option too, with the help of an arrow users can easily increase or decrease the number or order items in per page.

**Comment by barryhughes** [comment] 2022-05-24 17:05
Hi—thanks for the update.

> I think it's better if we have a button option too, with the help of an arrow users can easily increase or decrease the number or order items in per page.

Yes, I see your point, but I think it's best we leave this closed:

- I don't see this as a bug:
    - We are using a native control, and so we are deliberately delegating responsibility for how it renders/behaves to the user agent.
    - It works, it's fully functional—nothing stops a user from using it.
- It's possibly an enhancement:
    - I'm not convinced, though, because going against decisions the browser has made about rendering this sort of input within smaller viewports may be bad UI/UX.
    - It's also a piece of WordPress UI that we inherit (the same screen option exists for regular WP posts, and behaves in a similar way within various mobile browsers) ... so probably it makes sense to start a conversation upstream, if a change is desirable.
