### ISSUE TITLE
WooCommerce Category Product sorting not working only on Atomic sites

### ISSUE THREAD

**Issue by joshuatf** [woothemes/woocommerce#31389] opened 2021-12-07 21:14 UTC
Issue originally created by @AtrumGeost and moved from the https://github.com/automattic/wc-calypso-bridge repo.

### Steps to Reproduce

1. Create/publish some products and assign a category to them
2. Head over to **WooCommerce > Categories**, click on the number next to the category
3. Once you are on the category products dashboard, click on the **Sorting** link at the top
4. Drag products to reorder them
5. Refresh the page and notice the changes are not saved

https://user-images.githubusercontent.com/3696121/131747478-a50fe0aa-e117-48a6-a34e-5fe5fc267090.mp4

### What I expected to happen

For the sorting order to be saved, just like on a WordPress.org site

### What actually happened

None of the sorting changes are preserved

### Context

User report: 30458597-hc

### Operating System

macOS

### OS Version

11.5.2 (20G95)

### Browser

Chrome/Chromium

### Browser Version(s)

Version 92.0.4515.159 (Official Build) (x86_64)

### Simple/Atomic

Atomic

### Number of Users Impacted

All users

### Reproducibility

Consistent

### Other information

Follow-up ticket:

4266401-zd-woothemes

**Comment by peterfabian** [comment] 2021-12-13 08:48
The feature is probably not used very often, but affects our other products, so marking as high for now.

**Comment by nicdwilson** [comment] 2022-07-12 03:04
In 5366789-zen we see this behaviour also affecting the product sorting screen. Confirmed that it is not working on Atomic sites, but is working on regular installs. Updated title to reflect this.

**Comment by barryhughes** [comment] 2022-08-03 20:35
Taking a look at this, it seems to be a conflict with `Advanced_Post_Cache` (which is present on Atomic sites). In these cases, the main query normally generated by `WP_Post_List_Table` is intercepted and a set of cached post IDs are returned—these do not appear to respect the newly established menu_order.

**Closed as completed** 2022-08-15 14:28 UTC
Labels: Bug, plugin: woocommerce
