### ISSUE TITLE
[Fatal] Uncaught Error: Call to undefined function wc_get_container() | OrderUtil.php:36

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#53518] opened 2024-12-06 15:29 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We observed this fatal error from WooCommerce 9.4.2.

[link to code](https://github.com/woocommerce/woocommerce/blob/a1ea4258250b0b434508fbfb027be5ac65718eb1/plugins/woocommerce/src/Utilities/OrderUtil.php#L36)

```
PHP Fatal error:  Uncaught Error: Call to undefined function Automattic\WooCommerce\Utilities\wc_get_container() in/../plugins/woocommerce/9.4.2/src/Utilities/OrderUtil.php:36
Stack trace:
#0/../wp-content/plugins/gtm-ecommerce-woo/src/Util/WooCommerceFeaturesUtil.php(9): Automattic\WooCommerce\Utilities\OrderUtil::custom_orders_table_usage_is_enabled()
#1/../wp-content/plugins/gtm-ecommerce-woo/src/Service/OrderMonitorService.php(85): GtmEcommerceWoo\Lib\Util\WooCommerceFeaturesUtil::isHposEnabled()
#2/../wp-content/plugins/gtm-ecommerce-woo/gtm-ecommerce-woo.php(41): GtmEcommerceWoo\Lib\Service\OrderMonitorService->initialize()
#3/../core/6.7.1/wp-settings.php(526): include_once('/srv/htdocs/wp-...')
#4/../wp-config.php(84): require_once('/wordpress/core...')
#5/../core/6.7.1/wp-load.php(55): require_once('/srv/htdocs/wp-...')
#6/../core/6.7.1/wp-blog-header.php(13): require_once('/wordpress/core...')
#7/../core/6.7.1/index.php(17): require('/wordpress/core...')
#8 {main}
  thrown in/../plugins/woocommerce/9.4.2/src/Utilities/OrderUtil.php on line 36
--



``` 

### Expected behavior

No fatal error 

### Actual behavior

Fatal error witnessed

### Steps to reproduce

We don’t have steps to reproduce, but observed 3922 Fatals of this type were observed on Fri Nov 29, 2024 across 10 sites. 
Hopefully, someone can dig in and apply a defensive check if appropriate. – To be updated after investigation

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment] 2024-12-09 00:50
Hi @nigeljamesstevenson probably a duplicate of https://github.com/woocommerce/woocommerce/issues/53434? I'll close this one for the meantime, but feel free to comment and reopen if you think this is a different fatal error. Thanks! 

> We don’t have steps to reproduce, but observed 3922 Fatals of this type were observed on Fri Nov 29, 2024 across 10 sites.
Hopefully, someone can dig in and apply a defensive check if appropriate. – To be updated after investigation

I'll add this part into the Steps to reproduce of https://github.com/woocommerce/woocommerce/issues/53434 since these stats are good to mention but I haven't included it there.

**Closed as completed by rodelgc** 2024-12-09 00:50 UTC
Labels: Bug, type: fatal, env: internal
