### ISSUE TITLE
Cart Block: Translations not loaded from JSON when the plugins folder has been renamed

### ISSUE THREAD

**Issue by wpml-compatibility** [woothemes/woocommerce#44781] opened 2024-02-19 17:30 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have a WooCommerce instance that has the plugin folder renamed with these constants in `wp-config.php`:
```
define( 'WP_PLUGIN_DIR', '/var/www/html/wp-content/mods' );
define( 'WP_PLUGIN_URL', 'https://localhost/wp-content/mods' );
```
When you use the cart in a non-english language, you will see that the strings with translations are displayed in english, instead of the site language.

After some debugging, I found out the JSON files are correctly downloaded to `wp-content/languages/plugins` folder. 
But renaming the plugins folder has the side-effect of changing the languages folder too. 
You can confirm this because when you rename the folder to `wp-content/languages/mods` things start working again.

### Expected behavior

I would expect WooCommerce to use the JSON files from the `wp-content/languages/plugins` folder.

### Actual behavior

WooCommerce is trying to use JSON files from `wp-content/languages/mods` folder that doesn't exist.

### Alternative behaviour

It would also work if WooCommerce downloaded the JSON files to the updated folder. in either case, they should match so it works.

### Steps to reproduce

1. Create a WP site, for example, with Spanish as the site language in General settings.
2. Add these constants to `wp-config.php`. Adjust them according to your setup.
```
define( 'WP_PLUGIN_DIR', '/var/www/html/wp-content/mods' );
define( 'WP_PLUGIN_URL', 'https://localhost/wp-content/mods' );
```
3. Install WC and complete the wizard.
4. Make sure MO/JSON file are created in the language folder for the current site language.
5. Create a product and add it to the cart, check cart page
6. The cart page will be in English instead of Spanish.

### WordPress Environment ###

WordPress address (URL): https://localhost
Site address (URL): https://localhost
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: –
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: nginx/1.22.1
PHP Version: 8.1.2-1ubuntu2.14
PHP Post Max Size: 800 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.16-MariaDB-0ubuntu0.22.04.1
Max Upload Size: 800 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: wp_
Tamaño total de la base de datos: 6.99MB
Tamaño de los datos de la base de datos: 4.74MB
Tamaño del índice de la base de datos: 2.25MB
wp_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_actions: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
wp_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_logs: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_comments: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_icl_content_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_icl_core_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_icl_flags: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_icl_languages: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_icl_languages_translations: Datos: 0.20MB + Índice: 0.17MB + Motor InnoDB
wp_icl_locale_map: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_icl_message_status: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_icl_node: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_icl_reminders: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_icl_strings: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
wp_icl_string_batches: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_icl_string_positions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_icl_string_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_icl_string_translations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_icl_translate: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_icl_translate_job: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_icl_translations: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_icl_translation_batches: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_icl_translation_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_options: Datos: 3.08MB + Índice: 0.06MB + Motor InnoDB
wp_postmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_posts: Datos: 0.05MB + Índice: 0.06MB + Motor InnoDB
wp_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_term_relationships: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_usermeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_admin_notes: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp_wc_admin_note_actions: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
wp_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_orders: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
wp_wc_orders_meta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_addresses: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_operational_data: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_product_attributes_lookup: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wpfm_backup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1
shop_order_placehold: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Query Monitor: por John Blackbourn – 3.15.0
Database Management tool - Adminer: por Pexle Chris – 2.2.1
WooCommerce: por Automattic – 8.5.2 (la actualización a la versión 8.6.0 está disponible)
Administrador de archivos WP: por mndpsingh287 – 7.2.2

### Inactive Plugins (3) ###

Multilingual Tools: por OnTheGoSystems – 2.2.3
WooCommerce Blocks: por Automattic – 11.7.0
WooCommerce Multilingual & Multicurrency: por OnTheGoSystems – 5.3.3.1

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Must Use Plugins (2) ###

autologin.php: por  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Base de la tienda: #7 - /tienda/
Carrito: #8 - /carrito/
Finalizar compra: #9 - /finalizar-compra/
Mi cuenta: #10 - /mi-cuenta/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Twenty Twenty-One
Version: 2.1
Author URL: https://es.wordpress.org/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-15 11:33:38 +01:00
Options: ✔
Notes: 64
Onboarding: completed

### Action Scheduler ###

Completo: 24
Oldest: 2024-02-14 12:34:40 +0100
Newest: 2024-02-19 08:53:23 +0100

Fallida: 1
Oldest: 2024-02-14 12:35:52 +0100
Newest: 2024-02-14 12:35:52 +0100

Pendiente: 1
Oldest: 2024-02-20 08:52:14 +0100
Newest: 2024-02-20 08:52:14 +0100

### Status report information ###

Generated at: 2024-02-19 18:29:07 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment] 2024-03-27 22:08
Thanks for the report @wpml-compatibility. I'm wondering if this problem is specific to WooCommerce or if it's farther upstream. Does it happen with any other plugins? Also, are only the block JSON files affected, or are other translation file types impacted as well?

**Comment by wpml-compatibility** [comment] 2024-03-28 10:07
@coreymckrill, according to the ticket description and the steps provided, it can be reproduced with WooCommerce only and it does not depend on 3rd party plugins.

>Also, are only the block JSON files affected, or are other translation file types impacted as well?

I think it's affecting all JSON translation files (for blocks or not).

**Comment by coreymckrill** [comment] 2024-03-28 16:55
@wpml-compatibility Ok, but what I'm wondering is if this can be reproduced with other plugins _besides_ WooCommerce. As in, is this specific to WooCommerce, or is it a problem in WordPress itself? And, does this affect non-JSON translation files (.po/.mo) as well?

**Comment by wpml-compatibility** [comment] 2024-03-28 18:33
@coreymckrill, as far as I can see, the problem seems located in `load_script_textdomain`. So it might be indeed a general issue in WordPress. And thus it should not have impact on PO/MO files.

[Here you can find the original ticket from our client](https://wpml.org/forums/topic/mo-polish-translation-file-for-woocommerce-isnt-working/).

**Comment by coreymckrill** [comment] 2024-04-03 00:37
I opened a ticket for this in WP Core: https://core.trac.wordpress.org/ticket/60891

Since this is an upstream issue, I'm going to close this issue.

**Closed as not planned by coreymckrill** 2024-04-03 00:37 UTC
Labels: Bug, focus: i18n, type: community contribution

**Comment by coreymckrill** [comment] 2024-04-04 16:14
@wpml-compatibility Looks like this will be fixed in the next version of WordPress!

**Comment by wpml-compatibility** [comment] 2024-04-04 16:17
Thanks for your great help @coreymckrill!
