### ISSUE TITLE
[Spike] Implement data store MVP for custom order tables

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#31598] opened 2022-01-10 06:18 UTC
This issue scopes implementation of an MVP of the custom order table data store to explore the solution space better. We want to start with an MVP first to uncover hidden problems and dependencies that we may need to resolve or workaround.

#30228

**Comment by vedanshujain** [comment] 2022-01-10 15:34
We should make sure that the MVP can:
- [ ] Process simple checkout
- [ ] Can show orders in admin view
- [ ] Manage caches
- [ ] Can support atomic transactions - for coupon usages, product count etc.

**Comment by TheRealSimpleSimon** [comment] 2022-01-17 10:20
One specific thing I see is in the developer announcement is wp_wc_orders.billing_email.
At best, it should be renamed to a non-conflicting one. Even tho there is no DB entity in addresses of this name, it does exist in public functions (and should). What is the purpose of this email address being in the base record? I can see that a "billing_address" row may not exist for an order, but that still doesn't mean this email address is "billing". Possibly it is "customer_email"? And commonly a duplicate of the WP email address (if so, it should not exist in this table!)???

**Comment by TheRealSimpleSimon** [comment] 2022-01-17 10:35
Food for thought: As WooCommerce has gained in popularity, it has penetrated markets well beyond "selling T-shirts". These markets (notably business-to-business) often require alternate payment processing. Also, subscriptions require recurring payments. Neither of these are easy to implement in the current DB model.

Thought should be given to implementing wp_wc_order_payments with associated modifications to wp_wc_orders.
The _payments table should be flexible enough to support deposit, partial, recurring, and delayed (ie. invoice billing), payments. 
This table would at a minimum contain payment_method, transaction_id, payment_status, and so forth. Note that "currency" in the orders table should not be the "payment" currency, but the currency used when the order was placed, and there should be a payment currency field. It's late, I haven't considered how to handle "balance remaining"(that request popped in slack just a few days ago). Of course, With multiple payment transactions AND multiple currencies, the "value of payment" needs to be as of the transaction date, along with a means of tracking same in the payments table.

I am NOT saying that Woo should implement these optional payment types,, just have the common foundation in place. Right now, if you want to do more than "one thing", you constantly butt up against conflicting plugin implementations that a stable foundation will minimize. Finally, refund transactions would also be tracked in this table as opposed to a separate "pseudo-order" as is currently done - although order_items would possibly need some help with such - I haven't looked at how that is currently being done.

**Comment by peterfabian** [comment] 2022-10-05 09:40
This has been done via other issues.

**Closed as completed by peterfabian** 2022-10-05 09:40 UTC
Labels: Enhancement, plugin: woocommerce
