### ISSUE TITLE
Variable product shows in stock when out of stock if backorder is allowed

### ISSUE THREAD

**Issue by Buzut** [woothemes/woocommerce#32011] opened 2022-03-02 10:33 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On a variable product, one can get an array of variations with information on each one with `$product->get_available_variations()`.

For each variation, you have a key named `is_in_stock` which value is a boolean.
When Manage stock? is checked at the variation level, `is_in_stock` reflects the real stock status as long as Allow backorders? is set to "Do not allow". When backorders are allowed, `is_in_stock` is always true.

### Expected behavior

`is_in_stock` should be false when stock is at zero or below regardless of backorders behaviour. 

### Actual behavior

`is_in_stock` is always true when backorders are allowed

### Steps to reproduce

Create a variable product and some variations, set the stock management at variation level, allow backorders and set stock at zero for a variation. 
Printing the `$product->get_available_variations()` array will show that `is_in_stock` is off. 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost:8080/wp
Site address (URL): http://localhost:8080
WC Version: 6.1.1
REST API Version: ✔ 6.1.1
WC Blocks Version: ✔ 6.5.2
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ✔
WP Version: ❌ 5.9 - There is a newer version of WordPress available (5.9.1)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: PHP 7.3.29-to-be-removed-in-future-macOS Development Server
PHP Version: 7.3.29-to-be-removed-in-future-macOS
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.1
(SecureTransport) LibreSSL/2.8.3

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.4-MariaDB
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.1
WC Database Prefix: wpmto_
Total Database Size: 7.09MB
Database Data Size: 5.19MB
Database Index Size: 1.90MB
wpmto_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmto_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmto_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmto_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpmto_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmto_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmto_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpmto_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmto_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmto_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmto_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmto_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmto_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmto_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmto_acfw_virtual_coupons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmto_actionscheduler_actions: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
wpmto_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmto_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmto_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wpmto_cart_notices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmto_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmto_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpmto_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmto_fbv_attachment_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmto_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmto_lockdowns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmto_login_fails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmto_options: Data: 3.52MB + Index: 0.08MB + Engine InnoDB
wpmto_postmeta: Data: 0.31MB + Index: 0.31MB + Engine InnoDB
wpmto_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wpmto_relevanssi: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wpmto_relevanssi_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmto_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmto_seopress_significant_keywords: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmto_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmto_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmto_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpmto_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmto_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmto_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpmto_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpmto_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmto_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmto_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmto_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmto_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmto_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpmto_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpmto_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpmto_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpmto_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmto_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpmto_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpmto_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 29
acf-field-group: 5
attachment: 35
customize_changeset: 4
nav_menu_item: 26
page: 27
polylang_mo: 2
post: 2
product: 70
product_variation: 6
revision: 46

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (19) ###

Polylang Pro: by WP SYNTEX – 3.0.6
Advanced Coupons for WooCommerce Free: by Rymera Web Co – 3.1.2
Advanced Coupons for WooCommerce Premium: by Rymera Web Co – 3.1
Advanced Custom Fields PRO: by Delicious Brains – 5.11.4
Classic Editor: by WordPress Contributors – 1.6.2
Easy Auto SKU Generator for WooCommerce: by Dan Zakirov – 1.1.0
FileBird: by Ninja Team – 4.9.9
HTML Editor Syntax Highlighter: by James Bradford – 2.4.4
Kadence WooCommerce Email Designer: by Kadence WP – 1.4.10
Login LockDown: by Michael VanDeMar – v1.8.1
PayPlug pour WooCommerce (Officiel): by PayPlug – 1.3.0
Polylang for WooCommerce: by WP SYNTEX – 1.5.5
Relevanssi: by Mikko Saari – 4.14.7
WooCommerce Weight Based Shipping: by weightbasedshipping.com – 5.3.19
WooCommerce Cart Notices: by SkyVerge – 1.13.2
WooCommerce: by Automattic – 6.1.1 (update to version 6.2.1 is available)
Asset CleanUp Pro: Page Speed Booster: by Gabe Livan – 1.2.0.5
SEOPress PRO: by SEOPress – 5.4.2
SEOPress: by SEOPress – 5.4.4

### Inactive Plugins (6) ###

MyRewards: by Long Watch Studio – 4.2.5
Query Monitor: by John Blackbourn – 3.8.2
ShortPixel Adaptive Images: by ShortPixel – 3.2.1
Users Insights: by Pexeto – 4.0.1
Vosfactures: by VosFactures – 1.1.11
WP Super Cache: by Automattic – 1.7.7

### Must Use Plugins (1) ###

Asset CleanUp Pro: Plugin Filtering: by Gabriel Livan – 1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Steroids
Version: 3.0
Author URL: https://buzut.net
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: steroids/woocommerce/archive-product.php
steroids/woocommerce/content-product.php
steroids/woocommerce/loop/orderby.php
steroids/woocommerce/loop/pagination.php
steroids/woocommerce/single-product/title.php
steroids/woocommerce/single-product.php

### WC Pages Translations ###

Shop base: ✔
Cart: ✔
Checkout: ✔
My account: ✔

### Action Scheduler ###

Complete: 246
Oldest: 2022-02-02 05:49:48 +0100
Newest: 2022-03-02 11:08:02 +0100

### Status report information ###

Generated at: 2022-03-02 11:31:01 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment] 2022-03-10 18:32
Hello @Buzut,

> is_in_stock is always true when backorders are allowed.

This is really the expected behavior for products and variations, you can make a test by enabling stock management at product level and allowing backorders for a single product and it will produce the same result when calling `$product->is_in_stock()`.

You can see the code here:

https://github.com/woocommerce/woocommerce/blob/ef015f740f89c35cebf34bc0c39a971be6723b68/plugins/woocommerce/includes/abstracts/abstract-wc-product.php#L1619-L1627

This method/parameter works only to say if products are in stock or not to properly display on the front-end, even on backorder an order is still in stock since we can keep purchasing it, even with negative inventory, changing it will for sure break compatibility and cause many issues.

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed as completed** 2022-03-10 18:35 UTC
Labels: Bug, type: question, plugin: woocommerce

**Comment by Buzut** [comment] 2022-03-11 08:01
Hello @claudiosanches 

If it's a feature and not a bug, then all right. But it's pretty confusing!

I confess that I hadn't checked the code. On the other hand, the doc doesn't specify this behaviour and you gotta admit that one can be expecting `is_in_stock` to return `false` when a product is out of stock, regardless of whether it is allowed to go negative or not.

Hopefully, checking the stock on the product variation object leads to the right information.

```php
if ($product->is_type('variable')) {
    $available_variations = $product->get_available_variations();

    foreach ($available_variations as $variation) {
        $variation_product = new WC_Product_variation($variation['variation_id']);

        if ($variation_product->get_stock_status() !== 'instock') {
            …
        }
    }
}
```
