### ISSUE TITLE
'WooCommerce Payments' marketplace suggestion overrides the top payment method

### ISSUE THREAD

**Issue by jrick1229** [woothemes/woocommerce#31123] opened 2021-11-10 15:44 UTC
### Prerequisites (mark completed items with an [x]):
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When **Marketplace Suggestions > 'Display suggestions within WooCommerce'** is enabled AND the 'WooCommerce Payments' suggestion is displayed: https://d.pr/i/kVvPdq – the top payment method is not displayed.

### Expected behavior

The 'WooCommerce Payments' suggestion should be added as the first item in the list, not override the previous first item.

### Actual behavior

With marketplace suggestions **disabled**: https://d.pr/i/Ilw4ew
With marketplace suggestions **enabled**: https://d.pr/i/MeyGb4

Notice that 'Direct bank transfer' is not shown when the marketplace suggestion is not enabled, since 'WooCommerce Payments' overrides it.

### Steps to reproduce the bug

This is a little iffy, since simply enabling marketplace suggestions doesn't necessarily trigger that WooCommerce Payments suggestion.

On the client site, I was able to disable/enable marketplace suggestions in: `WooCommerce > Settings > Advanced > 'WooCommerce.com'` to show/hide the marketplace suggestion and original top-level payment method.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### WordPress Environment

<details>

```
### WordPress Environment ###

WordPress address (URL): ------
Site address (URL): ------
WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.1.0
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.8.0
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.24
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.35-38-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0

### Active Plugins ###

WooCommerce Stripe Gateway: by WooCommerce – 5.7.0
WooCommerce: by Automattic – 5.9.0

### Settings ###

API Enabled: ✔
Force SSL: –

Connected to WooCommerce.com: ✔

### Action Scheduler ###

Canceled: 1
Oldest: 2021-10-11 15:44:03 +0000
Newest: 2021-10-11 15:44:03 +0000

Complete: 16,934
Oldest: 2021-10-11 03:47:04 +0000
Newest: 2021-11-10 15:13:04 +0000

Pending: 4
Oldest: 2021-11-10 20:40:03 +0000
Newest: 2021-11-27 01:19:04 +0000


### Status report information ###

Generated at: 2021-11-10 10:30:21 -05:00
```
</details>

**Comment by jrick1229** [comment] 2021-11-16 21:06
Here's another: 4460225-zen

**Comment by swatipawarGS** [comment] 2021-11-18 09:03
Hi  @jrick1229  ,


Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end using WooCommerce 5.9.0 version.


Below are  the screenshots confirming the issue on my end:


With marketplace suggestions enabled: 


![#31123(Enable)](https://user-images.githubusercontent.com/94531721/142384141-c5d4121c-a837-4232-bb5f-cc986e7b0226.jpg)

With marketplace suggestions disabled:


![#31123(Disable)](https://user-images.githubusercontent.com/94531721/142384205-6dc0e8c6-b03a-42d4-ae35-9e4d0ecac397.jpg)

**Comment by nicdwilson** [comment] 2021-11-20 02:49
4461052-zen

**Comment by tammullen** [comment] 2021-11-22 12:02
Adding `needs developer feedback` to confirm if this is a core issue or a duplicate of WooCommerce Admin issue https://github.com/woocommerce/woocommerce-admin/issues/7942

**Comment by mattsherman** [comment] 2021-11-22 16:26
> woocommerce/woocommerce-admin#7942

This is a duplicate of https://github.com/woocommerce/woocommerce-admin/issues/7942

**Comment by barryhughes** [comment] 2022-03-12 00:31
Closing, given it is a duplicate :-)

**Closed as completed by barryhughes** 2022-03-12 00:31 UTC
Labels: Bug, Payments, needs: developer feedback, plugin: woocommerce
