### ISSUE TITLE
Attribute terms not editable after renaming attribute slug

### ISSUE THREAD

**Issue by jSpork** [woothemes/woocommerce#31547] opened 2022-01-04 00:49 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After creating an Attribute and adding Terms to it, those Terms are not longer editable if you change the name of the Attribute Slug.

### Expected behavior

Terms remain editable after changing the slug of the Attribute.

### Actual behavior

After changing the Slug of an Attribute, click on Configure terms for that Attribute. Instead of each Term having a checkbox next to it, a hyperlink for the name, and options to edit, all you get is a View option.

### Steps to reproduce

1. Create a new Attribute. Name: "Location", Slug: "location"
2. Add a Term to the Attribute: Name: "Oregon", Slug: "oregon"
3. You'll notice Oregon is hyperlinked, has a checkbox next to it, and gives you edit options when you hover over it
3. Change the Slug of the Attribute from "location" to "state"
4. Go back to your list of Terms for the Attribute
5. Notice there is no longer a checkbox next to Oregon, it's not hyperlinked, and you only have a View option when hovering over it

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://foundadventure.com
Site address (URL): https://foundadventure.com
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.27
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1l-fips

SUHOSIN Installed: –
MySQL Version: 5.7.32-35-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: rlm_
Total Database Size: 10.11MB
Database Data Size: 6.19MB
Database Index Size: 3.92MB
rlm_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
rlm_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rlm_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
rlm_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rlm_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
rlm_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rlm_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rlm_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rlm_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rlm_actionscheduler_actions: Data: 0.05MB + Index: 0.13MB + Engine InnoDB
rlm_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rlm_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rlm_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_bwf_contact: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
rlm_bwf_contact_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rlm_bwf_funnelmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_bwf_funnels: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rlm_bwf_optin_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_bwf_wc_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
rlm_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rlm_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_gf_entry_meta: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
rlm_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rlm_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rlm_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rlm_mepr_events: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
rlm_mepr_jobs: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
rlm_mepr_members: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
rlm_mepr_rule_access_conditions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
rlm_mepr_subscriptions: Data: 0.02MB + Index: 0.30MB + Engine InnoDB
rlm_mepr_subscription_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_mepr_tax_rates: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
rlm_mepr_tax_rate_locations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
rlm_mepr_transactions: Data: 0.02MB + Index: 0.33MB + Engine InnoDB
rlm_mepr_transaction_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_omnisend_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rlm_options: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
rlm_postmeta: Data: 1.45MB + Index: 0.19MB + Engine InnoDB
rlm_posts: Data: 1.30MB + Index: 0.06MB + Engine InnoDB
rlm_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rlm_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
rlm_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
rlm_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
rlm_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rlm_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rlm_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
rlm_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
rlm_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
rlm_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rlm_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rlm_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rlm_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rlm_wfacp_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
rlm_wfco_report_views: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
rlm_wfob_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
rlm_wfocu_event: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
rlm_wfocu_event_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rlm_wfocu_session: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_woof_query_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rlm_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rlm_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rlm_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rlm_yoast_indexable: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
rlm_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
rlm_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rlm_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rlm_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 138
custom_css: 1
et_body_layout: 3
et_pb_layout: 1
et_template: 13
et_theme_builder: 2
memberpressproduct: 1
memberpressrule: 1
nav_menu_item: 15
oembed_cache: 3
page: 15
post: 2
product: 12
revision: 5
seedprod: 1
shop_coupon: 1
shop_order: 2
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Gravity Forms: by Gravity Forms – 2.5.15
WooFunnels Funnel Builder Pro: by BuildWooFunnels – 1.14.2
WooFunnels Funnel Builder: by BuildWooFunnels – 1.11.1
Omnisend for Woocommerce: by Omnisend – 1.8.1
Paywall for WooCommerce: by TIV.NET INC – 3.3.1
Post Type Switcher: by Triple J Software
Inc. – 3.2.1

Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
SiteGround Optimizer: by SiteGround – 6.0.5
Surbma | Divi & Gravity Forms: by Surbma – 4.1
User Role Editor: by Vladimir Garagulya – 4.61
WooCommerce Stripe Gateway: by WooCommerce – 5.9.0
WOOF - WooCommerce Products Filter: by realmag777 – 1.2.6.3
WooCommerce: by Automattic – 6.0.0
WP Mail SMTP: by WPForms – 3.2.1

### Inactive Plugins (5) ###

Coming Soon Page, Maintenance Mode & Landing Pages by SeedProd: by SeedProd – 6.6.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.69

WordPress Starter: by SiteGround – 1.1.4
WPForms Lite: by WPForms – 1.7.1.2
Yoast SEO: by Team Yoast – 17.8

### Dropin Plugins (1) ###

object-cache.php: Memcached

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
paywall (paywall)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #668 - /shop/
Cart: #263 - /cart/
Checkout: #255 - /checkout/
My account: #270 - /my-account/
Terms and conditions: #632 - /terms-of-service/

### Theme ###

Name: Divi
Version: 4.14.4
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 90
Oldest: 2021-12-06 21:52:05 +0000
Newest: 2022-01-04 00:13:05 +0000

### Paywall ###

add_to_cart_action: checkout
admin_email: support@foundadventure.com
alter_add_to_cart_text_available: paywall_text
alter_add_to_cart_text_in_cart: paywall_text
alter_add_to_cart_text_out_of_stock: paywall_text
alter_add_to_cart_text_paid: paywall_text
alter_add_to_cart_url_available: url_product
alter_add_to_cart_url_in_cart: url_checkout
alter_add_to_cart_url_out_of_stock: url_product
alter_add_to_cart_url_paid: url_product
alter_price_html_in_cart: paywall_text
alter_price_html_out_of_stock: paywall_text
alter_price_html_paid: paywall_text
downloads_show_on_product_page: yes
expiration_show_at_checkout: yes
expiration_show_on_single_product: yes
expiration_units: days
expiration_value: -
log_level: error
myaccount_purchased_products_endpoint: purchased-products
reporter_email: admin@foundadventure.com
reporter_name: WordPress Admin
store_country_state: US:OR

### Status report information ###

Generated at: 2022-01-04 00:47:33 +00:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment] 2022-01-05 14:27
Hi @jSpork ,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using WooCommerce 6.0.0 version and WordPress 5.8.2 version.

Please find below screencast for reference :

https://user-images.githubusercontent.com/94531721/148175353-d4b202f9-f3b3-428d-ab95-75a502e2816d.mp4


Please provide us more detailed and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by jSpork** [comment] 2022-01-06 00:09
Oh weird, I must have some kind of caching going on in my Admin area. I
previously tested with multiple browsers and private mode but there must be
something within my WordPress install doing it. I've been doing further
testing and it seems to clear up overnight, further supporting your finding
that it's working as expected. Thanks for reviewing; I think you can close
this one out as not being an issue.

**Comment by rodelgc** [comment] 2022-01-10 07:14
@jSpork thank you for the feedback! Closing this issue now.

**Closed as completed by rodelgc** 2022-01-10 07:14 UTC
Labels: Bug, type: support request
