### ISSUE TITLE
REST API not generate in woocommerce 7.4.

### ISSUE THREAD

**Issue by amshirazy** [woothemes/woocommerce#36880] opened 2023-02-17 20:38 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

REST API not generate in woocommerce 7.4.

### Expected behavior

reload page and no action created.

### Actual behavior

reload page and no action created.

### Steps to reproduce

-

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by samueljseay** [comment] 2023-02-20 03:54
Hi @amshirazy I think we'll need more details than this to understand the problem here. Did you add some code that is not working in 7.4?

Could you please provide some steps to reproduce your issue?

**Comment by Glebkas** [comment] 2023-02-22 13:51
I have the same issue, after updating to 7.4, it's impossible to generate new REST API keys.  
Going to settings / advanced / REST API, after pressing "add key" and adding the description, pressing "generate API key" simply reloads the page without generating an API key.

**Comment by tammullen** [comment] 2023-02-22 13:54
@amshirazy @Glebkas I am unable to reproduce this. It will be great if you could share your current System Status Report. You can get it by navigating to the `WooCommerce / Status` section of your site. Once there, click on the `Get system report` button and then copy it by clicking on the `Copy for support` button. Then paste it here in a comment.

**Comment by Glebkas** [comment] 2023-02-22 14:16
ok, so I figured it out.
I couldn't create copy for support, the button won't respond.
But, my website language was Hebrew, and after switching to English all problems were resolved.

**Comment by tammullen** [comment] 2023-02-22 16:14
Thanks, this may be related to https://github.com/woocommerce/woocommerce/issues/36474 . The fix of that is due to be included in the upcoming WooCommerce 7.5 release.

**Comment by samueljseay** [comment] 2023-02-24 01:08
I'm going to close this for now, it sounds like the RTL issue will be resolved in 7.5 and resolve this for users with RTL language. Please re-open if you think me closing this is a mistake. 🙇🏻

**Closed as completed by samueljseay** 2023-02-24 01:08 UTC
Labels: Bug, needs: author feedback, type: community contribution

**Comment by raifd** [comment] 2023-03-13 11:40
@samueljseay @tammullen Does this happen with RTL only? We have a new report here: https://github.com/woocommerce/woocommerce/issues/37171 and this looks to be the same issue.

**Comment by samueljseay** [comment] 2023-03-16 09:33
@raifd It looks like the issue was possibly addressed by https://github.com/woocommerce/woocommerce/pull/36854 and the fix doesn't look like its strictly limited to RTL languages but a fix of some kind for some strings not being translated. But I'm not an expert on this one.

https://github.com/woocommerce/woocommerce/issues/37171 is for 7.4.1 so I'm wondering if 7.5 will fix their problem?

@peterfabian you worked on the fix, do you know more to explain here?

**Comment by peterfabian** [comment] 2023-03-20 11:36
I haven't investigated https://github.com/woocommerce/woocommerce/issues/37171 closely yet, but I think there's a high probability it will be fixed by  https://github.com/woocommerce/woocommerce/pull/36854. 

It's not actually only RTL languages that are affected. Any languages where the screen ID is translated from non-latin characters (and we sometimes load assets based on screen ID), so I'd assume https://github.com/woocommerce/woocommerce/issues/37171 would be solved with the 7.5 fix as well.

**Comment by amshirazy** [comment] 2023-03-23 19:07
Hello to all friends and thanks for the help and messages. I don't know where the problem is. I even deleted all the plugins and templates. With WordPress only and WooCommerce only, the api was not created. I solved this problem in this way: I installed the old version of WooCommerce, for example 5, and created the api. Then I updated WooCommerce.

**Comment by amshirazy** [comment] 2023-03-23 19:19
by updating in new version of woocommerce the problem SOLVED. thanks
