### ISSUE TITLE
RTL bug in woocommerce settings (Very important)

### ISSUE THREAD

**Issue by 79ho3ein** [woothemes/woocommerce#36474] opened 2023-01-17 13:03 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi woocommerce team.

After updating WooCommerce to version 7.3.0, WooCommerce settings styling is broken on RTL websites. In version 7.2.2 everything is displayed well.

**in 7.2.2**

![Screenshot (991)](https://user-images.githubusercontent.com/77163248/212904589-c80e6215-c22b-4faa-b400-f333e7fabb38.png)

in 7.3.0

![Screenshot (992)](https://user-images.githubusercontent.com/77163248/212904695-268a9fe2-51f5-47e8-b107-9a77c9d57dc4.png)

**Please check this bug in other settings such as general. It seems that the settings section is affected by this bug.**

thank you

### Expected behavior

-

### Actual behavior

-

### Steps to reproduce

1- Make sure WooCommerce version is 7.3.0
2- The language of the website is RTL
3- See the WooCommerce settings, especially the Payment section. Everything is broken.

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by 79ho3ein** [comment] 2023-01-17 13:08
Most importantly, in the Shipping lines section, all settings are removed. After changing to LTR, settings are displayed again. It seams. All sections need to be checked to determine if they are affected by this bug or not.

**Comment by MMTE** [comment] 2023-01-18 00:24
I believe the problem is that **admin-rtl.css** file (the equivalent of admin.css) is not loading in the RTL version anymore. 
you can achieve this by checking loaded CSS files and blocking admin.css file from loading. the same result will happen.

![Screenshot from 2023-01-18 03-44-24](https://user-images.githubusercontent.com/6337624/213043329-5b72121e-7920-4345-b6d7-7686c19e3d01.png)

also, I checked the WooCommerce 7.2.3 2023-1-9 and 7.2.2 2022-12-21  and there wasn't anything wrong. this is probably happened in = 7.3.0 2023-01-10.

I don't know if there is an automated procedure or something like CI/CD to find the breakpoint of versions in WooCommerce but at least I hope this comment help find the problem.

**Comment by khalilr2k** [comment] 2023-01-18 10:53
A quick fix i do in my functions.php
`	add_filter( 'woocommerce_screen_ids',function($screens){
					$screens[]='woocommerce_page_wc-settings';
					return $screens;
				} );`

**Comment by swatipawarGS** [comment] 2023-01-18 12:56
Hi @79ho3ein,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the  WooCommerce 7.3.0 version and WordPress 6.1.1 version. 

Please find below the screenshot for reference : 

![#36474](https://user-images.githubusercontent.com/94531721/213104434-0159b8db-63c6-4fec-91c0-3e6a08b89c9e.jpg)

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by themefour** [comment] 2023-01-18 17:15
Version 7.3 has many problems in RTL sites, especially in settings. Various JS and CSS errors appear in the browser console.

The styles of selectors, buttons, etc. are not displayed correctly in WooCommerce Settings (*in RTL).

![Snap2](https://user-images.githubusercontent.com/111493071/213248204-8dca64ee-2cbf-4370-84cc-d542d9102a4f.jpg)

**Comment by Michaelgimii** [comment] 2023-01-22 10:40
Hello WooCommerce team!

is it clear when this bug will be fixed? Will this be fixed with the next version?

**Comment by 79ho3ein** [comment] 2023-01-25 06:42
Another bug in this version...

In WooCommerce settings > Advanced > Page setup, the search option to find the cart, checkout pages and etc. is not displayed. 
**Please note that this bug only occurs in RTL.**

**Comment by xue28** [comment] 2023-02-01 06:30
https://wordpress.org/support/topic/woocommerce-cant-edit-shipping-methods/

**Comment by xue28** [comment] 2023-02-02 04:34
https://wordpress.org/support/topic/version-7-3-0-seriously-interferes-with-rtl-websites/

**Comment by majidempire** [comment] 2023-02-05 17:26
This problem effected on other Skyverge plugin called "WooCommerce Customer/Order/Coupon Export" and the above fix not working on it

**Comment by xue28** [comment] 2023-02-07 05:15
https://wordpress.org/support/topic/bug-in-persian-language-section-restapi/

**Comment by xue28** [comment] 2023-02-14 13:47
Persian Language: https://wordpress.org/support/topic/add-shipping-zone-does-not-load-completely-in-persian/

**Comment by peterfabian** [comment] 2023-02-16 13:04
This seems to be the result of the following PR: https://github.com/woocommerce/woocommerce/pull/35695

The screen IDs e.g. when called via `wc_get_screen_ids()` are (using Farsi as an example):
```
"toplevel_page_%d9%88%d9%88%da%a9%d8%a7%d9%85%d8%b1%d8%b3"
"%d9%88%d9%88%da%a9%d8%a7%d9%85%d8%b1%d8%b3_page_wc-orders"
"%d9%88%d9%88%da%a9%d8%a7%d9%85%d8%b1%d8%b3_page_wc-reports"
"%d9%88%d9%88%da%a9%d8%a7%d9%85%d8%b1%d8%b3_page_wc-shipping"
"%d9%88%d9%88%da%a9%d8%a7%d9%85%d8%b1%d8%b3_page_wc-settings"
"%d9%88%d9%88%da%a9%d8%a7%d9%85%d8%b1%d8%b3_page_wc-status"
"%d9%88%d9%88%da%a9%d8%a7%d9%85%d8%b1%d8%b3_page_wc-addons"
```

and screen ID matches those correctly in 7.2.3. 

After applying the fix from https://github.com/woocommerce/woocommerce/pull/35695 in 7.3.0, the screen IDs are hardcoded to `woocommerce_` prefix and `woocommerce_page_wc-settings` no longer matches the options from `wc_get_screen_ids()`.

(My assumption is that) most languages don't translate `WooCommerce`, so it's working most of the time, but for languages that do translate it, they fail to load some JS assets as the screen name isn't matched correctly since 7.3.0. 

It seems to make more sense to NOT translate the screen IDs, which is the behavior we enforced in https://github.com/woocommerce/woocommerce/pull/35695. However, this needs to be accompanied by a similar change in other code that might expect translated screen ID. 

One problem with this approach is that any plugins that might have used the translated screen ID will stop working. But arguably, using the translated WooCommerce approach meant we were doing it wrong, so it hints towards us doing the fix proposed in https://github.com/woocommerce/woocommerce/pull/36854, and publishing a dev advisory rather than rolling back https://github.com/woocommerce/woocommerce/pull/35695.

**Comment by Michaelgimii** [comment] 2023-02-16 19:12
Oh, WooCommerce team. Can anyone hear us? The new version is released but these bugs still exist!!!

**Comment by peterfabian** [comment] 2023-02-16 19:20
Hi @Michaelgimii . Apologies for the delay. We have a PR in the process of being reviewed (https://github.com/woocommerce/woocommerce/pull/36854) now and are considering doing a fix release for it. Worst case, it should land in WC 7.5 on March 8th.

**Comment by Michaelgimii** [comment] 2023-02-16 19:27
thank you @peterfabian🙏

**Comment by Michaelgimii** [comment] 2023-02-16 19:37
In the general section, even the width of the fields is out of the ordinary. (I hope you have no problem with the translation in the image below)

![woocommerce](https://user-images.githubusercontent.com/88034902/219469094-8e226e41-79e4-4de7-a3c1-f5f7b726363f.png)

**Comment by 79ho3ein** [comment] 2023-02-16 20:01
Some colleagues have reported that there are bugs in the ui during the initial quick installation of WooCommerce. I think it's better to review all parts of WooCommerce in one RTL website. This bug can exist anywhere.

![a](https://user-images.githubusercontent.com/77163248/219474713-938b535d-d32f-4cc4-ac47-1f3752b6df29.jpg)

**Comment by raifd** [comment] 2023-02-17 10:17
5966612-zen

**Comment by peterfabian** [comment] 2023-02-17 11:27
@Michaelgimii thanks for reporting. As far as I can see, this has also been fixed after applying the PR mentioned above, as you can see below
<img width="1728" alt="Screenshot 2023-02-17 at 12 24 06" src="https://user-images.githubusercontent.com/2207451/219639613-0b62f6fa-4039-41e7-99f2-56e4a5199b76.png">

**Comment by Michaelgimii** [comment] 2023-02-17 15:14
@peterfabian , Great! Thank you

**Closed as completed** 2023-02-17 21:31 UTC
Labels: Bug, plugin: woocommerce, type: community contribution
