### ISSUE TITLE
Unable to display Payments tab (backend) and/or complete payments (frontend)

### ISSUE THREAD

**Issue by frenchcharly** [woothemes/woocommerce#36397] opened 2023-01-12 15:20 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When:
- clicking on “Payments” tab on backend ( __/wp-admin/admin.php?page=wc-settings&tab=checkout__)
- trying to complete purchase ( __/checkout/__)
WordPress throws a fatal error.

**Temporary fix** has been found (https://wordpress.org/support/topic/woocommerce-setting-payment-tab-showing-an-error/) :
In `wp-content/plugins/woocommerce/src/Internal/Admin/WCPayPromotion/Init.php`, change the method `set_gateway_top_of_list`, within the last if statement (the short-handed one):

change this →  `$ordering [ $id ] = $is_empty ? 0 : ( min( $ordering ) - 1 )`
to this →  `$ordering [ $id ] = $is_empty ? 0 : ( min( $ordering ) )`

I have had to apply this fix at least for the last 3 WC updates I did.

I am not in a situation where I can deactivate all plugins/themes, so it's more about creating an issue to make sure others are not impacted by this rather than finding a solve for my current situation.

### Expected behavior

Displaying the payments tab / completing and order.

### Actual behavior

Fatal error

### Steps to reproduce

1. Add any product to cart
2. View basket
3. Confirm Order
4. Crash

(for backend, simple clic on "Payments" does the job)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://*
Site address (URL): https://*
REST API Version: ✔ 7.2.3
WC Blocks Version: ✔ 8.9.4
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Ubuntu)
PHP Version: 8.1.11
PHP Post Max Size: 28 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 10.1.48-MariaDB-0ubuntu0.18.04.1
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.2.3
WC Database Prefix: wp_
Total Database Size: 100.86MB
Database Data Size: 73.51MB
Database Index Size: 27.35MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.25MB + Index: 0.27MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.63MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.34MB + Index: 0.30MB + Engine InnoDB
wp_aiowps_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_failed_logins: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_activity: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_lockdown: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cdi: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.23MB + Index: 0.25MB + Engine InnoDB
wp_gpf_feeds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lpc_inward_label: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_lpc_label: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lpc_outward_label: Data: 15.52MB + Index: 0.03MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailjet_wc_abandoned_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailjet_wc_abandoned_cart_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailjet_wc_guests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 6.05MB + Index: 0.20MB + Engine InnoDB
wp_pmxe_exports: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 8.30MB + Index: 4.06MB + Engine InnoDB
wp_posts: Data: 4.09MB + Index: 0.64MB + Engine InnoDB
wp_relevanssi: Data: 2.50MB + Index: 4.58MB + Engine InnoDB
wp_relevanssi_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_relevanssi_stopwords: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 1.52MB + Index: 0.48MB + Engine InnoDB
wp_users: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.13MB + Index: 0.17MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 2.27MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.02MB + Index: 0.20MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 1.02MB + Index: 0.14MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsal_metadata: Data: 7.27MB + Index: 12.44MB + Engine InnoDB
wp_wsal_occurrences: Data: 3.22MB + Index: 0.63MB + Engine InnoDB
wp_wsal_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_campaign: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_campaign_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_custom_field: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_email: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wysija_email_user_stat: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_email_user_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wysija_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wysija_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_url_mail: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_user: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wysija_user_field: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_user_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_user_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Data: 1.50MB + Index: 0.52MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1870
efbl_skins: 6
mc4wp-form: 1
mif_skins: 2
nav_menu_item: 216
oembed_cache: 4
page: 18
post: 3
product: 564
product_variation: 41
revision: 448
shop_coupon: 1
shop_order: 176
shop_order_refund: 8
tbay_brand: 8
tbay_footer: 2
tbay_megamenu: 3
tbay_testimonial: 2
wpcf7_contact_form: 2
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

ManageWP - Worker: by GoDaddy – 4.9.16
CMB2: by CMB2 team – 2.10.1
Colissimo shipping methods for WooCommerce: by Colissimo – 1.7.4
Contact Form 7: by Takayuki Miyoshi – 5.7.2
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.4.4
Duplicate Menu: by Jonathan Christopher – 0.2.2
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
ELEX WooCommerce Google Shopping (Google Product Feed) - Basic: by ELEXtensions – 1.3.5
Facebook for WooCommerce: by Facebook – 3.0.8
GA Google Analytics: by Jeff Starr – 20221016
GDPR Data Request Form: by audrasjb – 1.6
WPBakery Page Builder: by Michael M - WPBakery.com – 6.10.0
Loco Translate: by Tim Whitlock – 2.6.3
Mailjet for WordPress: by Mailjet SAS – 5.3.2
Relevanssi: by Mikko Saari – 4.18.2
Slider Revolution: by ThemePunch – 6.4.11
Tbay Framework: by Team TbayTheme – 2.2.4
User Role Editor: by Vladimir Garagulya – 4.63.2
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.35

Variation Swatches for WooCommerce: by Emran Ahmed – 2.0.17
WooCommerce Shipping & Tax: by WooCommerce – 2.1.1
WooCommerce: by Automattic – 7.2.3
Wordfence Security: by Wordfence – 7.8.2
Yoast SEO: by Team Yoast – 19.14
YITH WooCommerce Wishlist: by YITH – 3.17.0

### Must Use Plugins (1) ###

ManageWP - Worker Loader: by GoDaddy – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #2638 - /shop/
Cart: #7 - /panier/
Checkout: #2640 - /checkout/
My account: #9 - /mon-compte/
Terms and conditions: #1662 - /cgv/

### Theme ###

Name: GreenMart Child
Version: 1.0
Author URL: https://thembay.com/
Child Theme: ✔
Parent Theme Name: GreenMart
Parent Theme Version: 4.0.14
Parent Theme Author URL: https://thembay.com
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: greenmart/woocommerce/cart/cart.php
greenmart/woocommerce/cart/cross-sells.php
greenmart/woocommerce/cart/mini-cart.php
greenmart/woocommerce/checkout/form-checkout.php
greenmart/woocommerce/content-product-cat.php
greenmart/woocommerce/content-product.php
greenmart/woocommerce/content-single-product.php
greenmart/woocommerce/global/breadcrumb.php
greenmart/woocommerce/global/quantity-input.php version 4.0.0 is out of date. The core version is 7.2.1
greenmart/woocommerce/loop/add-to-cart.php
greenmart/woocommerce/loop/loop-end.php
greenmart/woocommerce/loop/loop-start.php
greenmart/woocommerce/loop/orderby.php
greenmart/woocommerce/loop/pagination.php
greenmart/woocommerce/loop/rating.php
greenmart/woocommerce/myaccount/form-login.php
greenmart/woocommerce/myaccount/my-address.php
greenmart/woocommerce/myaccount/my-orders.php
greenmart/woocommerce/single-product/product-image.php
greenmart/woocommerce/single-product/product-thumbnails.php
greenmart/woocommerce/single-product/rating.php
greenmart/woocommerce/single-product/related.php
greenmart/woocommerce/single-product/review.php
greenmart/woocommerce/single-product/tabs/additional-information.php
greenmart/woocommerce/single-product/tabs/description.php
greenmart/woocommerce/single-product/tabs/tabs.php
greenmart/woocommerce/single-product/up-sells.php
greenmart/woocommerce/single-product-reviews.php

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-13 13:31:47 +01:00
Options: ✔
Notes: 7
Onboarding: completed

### Action Scheduler ###

Complete: 1,544
Oldest: 2022-12-12 16:59:19 +0100
Newest: 2023-01-12 16:12:04 +0100

Pending: 3
Oldest: 2023-01-12 23:36:30 +0100
Newest: 2023-01-12 23:36:35 +0100

### Status report information ###

Generated at: 2023-01-12 16:12:12 +01:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment] 2023-01-17 12:48
Hi @frenchcharl,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using the WooCommerce 7.3.0 version, PHP 8.0.27 version, and WordPress 6.1.1 version. 

Please find below the screencast for reference :


https://user-images.githubusercontent.com/94531721/212828942-9628f0ec-1c02-41a5-bc65-e85243ce30cc.mp4


Please provide us with more details and any additional steps required to repro this issue which may help us evaluate it further.

**Comment by barryhughes** [comment] 2023-03-06 20:16
Specific error:

```
Uncaught TypeError: Unsupported operand types: string - int in /.../wp-content/plugins/woocommerce/src/Internal/Admin/WCPayPromotion/Init.php:108
```

Updated the focus labels as the history suggests this may be a better fit for Ghidorah (feel free to change back if I'm wrong).

**Comment by lsinger** [comment] 2023-03-27 09:56
Sounds like @barryhughes was able to reproduce, so labeling this a confirmed bug.

**Comment by adrianduffell** [comment] 2023-05-02 04:45
Hey @louwie17, it looks like you worked on this feature previously (not Ghidorah). Can you advise a bit on the proposed solution to remove the `- 1`?

**Comment by adrianduffell** [comment] 2023-05-02 04:49
I'm not sure if this is truly an onboarding feature, but will apply the label to keep Ghidorah involved. I think it's more accurately a wcpay focus area.

**Comment by louwie17** [comment] 2023-05-02 07:39
> Hey @louwie17, it looks like you worked on this feature previously (not Ghidorah). Can you advise a bit on the proposed solution to remove the `- 1`?

I mimicked (mostly copied) this function from WooCommerce Payments: https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments.php#L711-L727 given they were doing something similar. So the same issue would happen with WooCommerce Payments enabled.

The `-1` is to make sure it is always at the top of the list, we could parse what `min` returns to an integer always. But it looks like another payment plugin might be setting the order value as a string instead of an integer.

@barryhughes were you able to reproduce this on a site with WooCommerce only? Or with several plugins?

**Comment by barryhughes** [comment] 2023-05-03 18:58
Sorry for any confusion: I was not indicating that I could reproduce. 

This came up during our triage process, because it originally had a Proton focus label, however it's not related to code we typically manage. All I really wanted to do was update the focus labels so the correct team would see it (and then took a moment to cite the actual error in case that was useful to the next folks working on this).

**Comment by louwie17** [comment] 2023-05-04 10:54
Gotcha, thanks for the clarification @barryhughes, I will add the `can't reproduce` tag. I am not sure what the follow up process for that is. @lsinger do we close this and re-open if we do get more detailed testing instructions to consistently reproduce this?

**Comment by adrianduffell** [comment] 2023-05-11 05:23
@frenchcharly, to help with reproducing the issue are you able to provide the value for the `woocommerce_gateway_order` option on your site?

**Comment by lsinger** [comment] 2023-05-19 11:00
@louwie17 that's one option, yes -- but as @adrianduffell had another idea as to what information might help reproduction, I'm going to assign `needs author response` now.

**Comment by rrennick** [comment] 2023-09-11 19:30
Closing for lack of author feedback.

**Closed as completed by rrennick** 2023-09-11 19:30 UTC
Labels: Bug, needs: author feedback, status: can't reproduce, Payments, plugin: woocommerce, Settings, type: community contribution
