### ISSUE TITLE
[HPOS]: Documentation on `save_post` alternative hook

### ISSUE THREAD

**Issue by dominic-p** [woothemes/woocommerce#35814] opened 2022-12-02 00:50 UTC
### Describe the solution you'd like

I've been working through updating my plugins for HPOS compatibility following the [guide here](https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book). In general, it's been going smooth, but I'm hitting a snag as I try to update meta boxes on the admin order page.

I see instructions for everything but the `save_post` hook. Presumably that hook will no longer fire since orders will no longer be WP posts, but I can't seem to find any documentation on what to replace it with. The guide just says:

> If it’s a filter or an action, then we will implement a similar filter in the new WooCommerce screen as well

### Describe alternatives you've considered

I found what [woocommerce-subscriptions-core](https://github.com/Automattic/woocommerce-subscriptions-core/compare/2.4.1...2.5.0) did to solve the problem, but I'm really hoping there's a simpler way for smaller scale projects.

**Comment by dominic-p** [comment] 2022-12-19 21:58
Friendly bump. I have a bit of time to work on this, and I would love to get HPOS compatibility nailed down if possible. Any suggestions for replacing the `save_post` hook at this point?

**Comment by barryhughes** [comment] 2022-12-20 01:10
Hi @dominic-p,

We're going to work on the documentation side of things. In the meantime, do either of these action hooks fit your use-case?

- `woocommerce_new_order` (fires when a new order is created)
- `woocommerce_update_order` (fires when an existing order is updated)

Callbacks for either hook receive the same parameters:

- `int $order_id`
- `WC_Order $order`

In this regard, they are very similar to the `save_post` action which supplies the `$post_id` and post object.

**Comment by dominic-p** [comment] 2022-12-20 01:40
Hi @barryhughes, thanks for the response. I wasn't aware of those hooks. In particular, `woocommerce_update_order` should be great. A couple follow up questions:

1. Do you know roughly when it was introduced (i.e. do I have to support both `save_post` and the new hook or can I just switch)?
2. Do you know what kind of authentication data is available? For example, on `save_post` I'm able to use `check_admin_referer()` at the top of my function. Will this "Just Work" using the new hook?

Of course, I can just test both of these things, but if you know off the top of your head that saves me a bit of time. :) Thanks again for helping get me unstuck.

**Comment by barryhughes** [comment] 2022-12-20 11:53
> Do you know roughly when it was introduced

Neither hook is brand new—both have been in use with CPT-based orders for a long time (they are documented as having been introduced in 2.7.0). So, in general, they are a great choice if you need a datastore-agnostic way of hooking into these events.

> Do you know what kind of authentication data is available?

In the context of the order editor, when an order is updated, you can call `check_admin_referer()` or `wp_verify_nonce()` and test for one of the following standard actions:

- `update-order_<ORDER_ID>` (HPOS/custom order tables)
- `update-post_<POST_ID>` (WP post editor)

However, it's worth calling out that [`check_admin_referer()`](https://developer.wordpress.org/reference/functions/check_admin_referer/) will exit if the check fails so, if you need this, it may make more sense to use [`wp_verify_nonce()`](https://developer.wordpress.org/reference/functions/wp_verify_nonce/) within your callback—unless you first perform a conditional check of some kind.

More generally, of course—and just as with the core WordPress `save_post` hook—the longer answer is that it depends on the context. For example, if an order is updated via the REST API, then using `check_admin_referer()` won't work and one would want to be careful if their callback also executes in that context.

**Comment by dominic-p** [comment] 2022-12-20 17:49
Thanks @barryhughes, that info is super helpful. I really appreciate it. :)

**Comment by barryhughes** [comment] 2022-12-20 18:05
Welcome!

**Comment by dominic-p** [comment] 2022-12-20 22:57
Ok, one last snag, if you have a moment. I need to localize some scripts that's I'm enqueuing in `admin_enqueue_scripts`. To do that I need access to the order object for the current page.

Right now, I'm using `global $post` and then `wc_get_order( $post->ID )`. Of course, `global $post` probably won't work with HPOS. I haven't been able to find a good substitute for that in the context of the `admin_enqueue_scripts` hook.

__Update:__ I just found `global $theorder` which looks promising, but I'm not sure if that's meant to be an internal API or something stable that I can use.

**Comment by barryhughes** [comment] 2022-12-21 21:00
Great question—please also refer to [this issue](https://github.com/woocommerce/woocommerce/issues/35561). It has been possible to call `wc_get_order()` (without a parameter) before now, but HPOS does not currently support this pattern. I'm afraid we have not yet worked on a fix. 

I think a reasonable interim solution would be to determine if you are within the order editor screen—checking the global screen object may be one way—then simply inspecting value of the `id` URL parameter (if it is not set, then a new order is being created). That's perhaps not ideal, but on the other hand it will also continue to work into the foreseeable future.

**Comment by dominic-p** [comment] 2022-12-21 23:54
Thanks again for the helpful info. That should be a good workaround for now.

**Comment by barryhughes** [comment] 2022-12-22 00:51
Welcome, this was mutually useful and should help us as we add more documentation/work on improving what we have.

**Comment by webdados** [comment] 2023-01-18 12:59
Hi there,

I assume `woocommerce_update_order` runs when calling `$order->save()`, right?
So if I need to save some data to the order, how can I avoid a loop?

Isn't there some hook that runs at the end of everything saved, ONLY when editing an order via the wp-admin edit order screen, that we can use to process our stuff without going into loops? save_post was greater for that, but if called with HPOS active, we get into a loop also.

**Comment by barryhughes** [comment] 2023-01-18 16:32
Hi @webdados,

> I assume woocommerce_update_order runs when calling $order->save(), right?

Yes—except for new orders, in which case `woocommerce_new_order` will be triggered.

> So if I need to save some data to the order, how can I avoid a loop?

The principle would be the same as if you were using `save_post` with a post type object (since hooking into this and calling `wp_update_post()` will result in effectively the same thing). There is however an existing dynamic hook that exists to allow object props to be adjusted before save:

`woocommerce_before_<OBJECT_TYPE>_object_save`

For orders, that becomes:

`woocommerce_before_order_object_save`

Callbacks can receive upto two parameters, the first being the order object and the second being the active data store. In this case, the relevant source code [is here](https://github.com/woocommerce/woocommerce/blob/7.3.0/plugins/woocommerce/includes/abstracts/abstract-wc-order.php#L190-L196).

> Isn't there some hook that runs at the end of everything saved, ONLY when editing an order via the wp-admin edit order screen

Depending on the work you are doing, you could also consider using the following action hook which will be fired following order save operations made via the admin order editor:

```
woocommerce_process_shop_order_meta
```

The source for this hook can be [found here](woocommerce_process_shop_order_meta). In this case, callbacks will receive the object ID as the first param and the order object itself as the second param.

**Comment by ninetyninew** [comment] 2023-07-11 14:10
@barryhughes 

We did find a potential issue here due to not being able to use `save_post_shop_order` any more.

In one of our extensions we have some custom fields added into the add/edit order screen with checkboxes which the user can select, we then used to use `save_post_shop_order` to run a save function, if the checkboxes are selected then it would add an order note by getting the order object and using `$order->add_order_note`

On non-HPOS it works fine. However by changing it to `woocommerce_update_order` we found the order note gets added multiple times - it appears that when saving from the add/edit product page `woocommerce_update_order` gets fired multiple times, whereas `save_post_shop_order` only occurs once.

This was discussed over Slack with @vedanshujain recently

**Comment by barryhughes** [comment] 2023-07-11 19:11
I can't immediately find the discussion, is it the one referencing https://github.com/woocommerce/woocommerce/pull/39165 (now merged)? That is, where you were looking for an analog to `edit_form_top` with which to save data in certain contexts?

**Comment by ninetyninew** [comment] 2023-07-11 19:54
@barryhughes no thats a separate issue, this one is discussed here: https://woocommercecommunity.slack.com/archives/C043X91E72M/p1685711253180439

**Comment by barryhughes** [comment] 2023-07-11 19:59
Thank you.

Fwiw, I could envision a scenario where `save_post_<POST_TYPE>` is also triggered twice, or more than twice, in the same request for the same post. Not to say it is common, or that it would happen by default when a post is updated via the post editor—but I wanted to note it even so.

We should definitely still look into the difference we see here between CPT and HPOS.

**Comment by webdados** [comment] 2023-07-12 10:49
Sorry for the delay. I'm using `woocommerce_process_shop_order_meta` now.

**Comment by ninetyninew** [comment] 2023-07-12 15:57
@barryhughes yes, this is a difficult one - the problem is anyone adding anything via those `woocommerce_new_order` or `woocommerce_update_order` hooks are having that functionality run multiple times, you don't notice it if you are just doing something like saving custom meta (but would be causing a performance hit). In my scenario where I am adding an order note its repeatedly doing it, with `save_post_shop_order` we haven't had any users raising issues of notes getting added multiple times, I appreciate its possible that gets run multiple times, but it seems theres minimal risk of this compared to the WooCommerce hooks. 

Not sure really how to work around this, any ideas would be appreciated. I'm not really understanding how WooCommerce core is managing to add order notes without this occurring, I guess it's because they don't get added from any function hooked from `woocommerce_new_order` or `woocommerce_update_order`.

**Comment by ninetyninew** [comment] 2023-07-14 08:20
Just as an update I discussed this further with @vedanshujain and found that replacing `save_post_shop_order` with `woocommerce_process_shop_order_meta` for my adding an order note scenario worked without any duplicates across both HPOS and non-HPOS.

**Comment by jorgeatorres** [comment] 2024-06-04 15:03
Hey everyone! 👋 

Thanks for the input here. I've taken note of this discussion in #40699, where we're tracking other documentation enhancements related to HPOS. As such, I'm going to close this issue and update the other one as we make progress. Thanks again!

**Closed as completed by jorgeatorres** 2024-06-04 15:03 UTC
Labels: Bug, Enhancement, Documentation, plugin: woocommerce, type: community contribution
