### ISSUE TITLE
e2e-environment throws when npm linked

### ISSUE THREAD

**Issue by tomalec** [woothemes/woocommerce#33811] opened 2022-07-11 14:52 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

To test the latest version and debug I use (p)`npm link` flow. When I linked `@woocommerce/e2e-environment` it throws:
```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '@woocommerce/e2e-environment'
Require stack:
- /home/tomalec/repos/woocommerce/packages/js/e2e-environment/utils/app-root.js
```

I guess it's because the package assumes that it's located "above" the app folder.https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/e2e-environment/utils/app-root.js#L12

BTW, to me guessing the application folder by the location of the package itself seems to me unreliable either way.

### Expected behavior

(p)npm linked package should work exactly the same as the locally installed one.

### Actual behavior

package thorws an error.

### Steps to reproduce

1. Clone this repo
2. 
   ```
   cd woocommerce/packages/js/e2e-environment
   pnpm link --global
   ```
3. `cd` to your extension repo, for example [GLA](https://github.com/woocommerce/google-listings-and-ads) 
4. `npm link @woocommerce/e2e-environment`
5. `npx wc-e2e docker:up`

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ObliviousHarmony** [comment] 2022-07-11 18:15
Hello @tomalec,

This is a duplicate of https://github.com/woocommerce/woocommerce/issues/33684. Thank you for reporting it!

**Closed as completed by ObliviousHarmony** 2022-07-11 18:15 UTC
Labels: Bug, package: @woocommerce/e2e-environment
