### ISSUE TITLE
[Enhancement]: In-app guidance - step guidance component

### ISSUE THREAD

**Issue by becdetat** [woothemes/woocommerce#32463] opened 2022-04-04 07:35 UTC
### Describe the solution you'd like

This is part of an internal project - see (pbIJXs-1qT-p2) for more context.

There is a WordPress.com step guidance component which should be used to implement this. We will need to add further functionality to the component.

- We should attempt to add hook points so that consumers can add their own tracks events
- Any changes we make should be done upstream in the WP.com libraries where possible, or at least we should have plans and the ability to make this happen in the future

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by adrianduffell** [comment] 2023-05-01 23:05
Duplicate of https://github.com/woocommerce/woocommerce/issues/32892

**Closed as completed by adrianduffell** 2023-05-01 23:05 UTC
Labels: Enhancement, plugin: woocommerce
