### ISSUE TITLE
When add product in the group, it appear also in other group without I selected.

### ISSUE THREAD

**Issue by nebojsa-ed** [woothemes/woocommerce#31325] opened 2021-11-29 12:22 UTC
During add the product into selected group, after Update, it appear also in one other group. I made all known testing, rebuild keys in DB, but nothing help.
When try edit and change my Group name and Slug, got message: You need a higher level of permission. Sorry, you are not allowed to edit this item.
I suppose it should be bug, or I made some wrong.

**Comment by tammullen** [comment] 2021-12-02 11:47
Hi @nebojsa-ed ,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by nebojsa-ed** [comment] 2021-12-02 20:28
Hi,

Describe the bug
I guess  database of my woocommerce site is corrupted. Strange things happens. More time after defined some attributes and configure terms, after some days (can't define when) Terms list was empty. Cannot detect the cause.
If add again terms, and try edit one of the terms I got Error: 'Need higher level of permission' After that when again select this term, look tvice same term. It is always reproduce.

Second problem I seen is Categorry, when add ne subcategory (parrent existing) and try add product into added subcategory, after assigh subcategory and press Update product, after finished look my prodict also assigned in unwanted subcategory of different parrent. Deselecting from this subcategory and make Product update, again back into same subcategory. Always appear same situation and add always in same category.

Some product in product list has assigned tvice same category.
After remove product from this category, category dissapear from category list. Add again same category and try edit, get again 'Need higher level of permission', Back to category list see tvice same category, one automatic linked 8 products inside...

Regarding I gues DB MySql is maybe corrupted, I cannot know if others can reproduce it.

This appearances make total unusuable system

I made some service options from Woocommerce -> Status -> Tools

I exclude all Plug-ins one per one, nothing help.

I use theme: StoreFront
WordPress:  5.8.2
![Img 6409](https://user-images.githubusercontent.com/95222779/144497886-76cb8413-aab0-4288-8efa-556f2a9285df.jpg)
![Img 6408](https://user-images.githubusercontent.com/95222779/144497894-ecaeaf05-7115-4d00-9653-9241a832234b.jpg)
![Img 6407](https://user-images.githubusercontent.com/95222779/144497896-628b5209-61f2-44ed-a9c1-0f1635e6d9f7.jpg)
![Img 6406](https://user-images.githubusercontent.com/95222779/144497898-c23063b0-12a9-4b25-b1ed-8163803fcc47.jpg)
![Img 6405](https://user-images.githubusercontent.com/95222779/144497899-7f24f634-e96a-4a08-b299-db8f082fde89.jpg)
![Img 6404](https://user-images.githubusercontent.com/95222779/144497900-10dfed52-6463-4a4a-83df-feeeea5a59d7.jpg)

**Comment by AashikP** [comment] 2021-12-18 07:51
Hi @nebojsa-ed,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by AashikP** 2021-12-18 07:51 UTC
Labels: status: can't reproduce
