### ISSUE TITLE
Store "core/interface" is already registered. c	@	data.min.js?ver=7c62e39…:2

### ISSUE THREAD

**Issue by uniweb31** [woothemes/woocommerce#53239] opened 2024-11-27 08:25 UTC
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi,
I have this error on my website on plugin/order/products pages admin
Store "core/interface" is already registered. c	@	data.min.js?ver=7c62e39…:2

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce

Just open console in admin pages (products/orders)

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.4.2
Legacy REST API Package Version: L’extension Legacy REST API n’est pas installée sur ce site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 512 Mo
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 130 Mo
PHP Time Limit: 165
PHP Max Input Vars: 16000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 8.0.36
Max Upload Size: 128 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 91
acf-field-group: 8
acf-post-type: 3
acf-taxonomy: 5
attachment: 236
flamingo_contact: 5571
flamingo_inbound: 174
formations: 6
language_switcher: 4
mailpoet_page: 1
nav_menu_item: 19
page: 18
point-de-vente: 10
post: 4
praticien: 4
product: 79
revision: 287
shop_coupon: 2
shop_order: 2727
shop_order_refund: 17
site-review: 2
therapeute: 138
wp_navigation: 1
wpcf7_contact_form: 1
ywpi-pdf-template: 8

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (44) ###

ACF Content Analysis for Yoast SEO: par Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
équipe Yoast – 3.1

Advanced Custom Fields: Extended: par ACF Extended – 0.9.0.9
Advanced Custom Fields: Font Awesome: par Matt Keys – 4.1.1
Advanced Custom Fields PRO: par WP Engine – 6.3.11
FiboSearch - AJAX Search for WooCommerce: par L’équipe FiboSearch – 1.29.0
Activity Log: par L’équipe d’Activity Log – 2.11.2
ATUM Inventory Management for WooCommerce: par Stock Management Labs™ – 1.9.43.1
Bank Slip for WooCommerce: par N.O.U.S. Ouvert Utile et Simple – 1.0.2
Bopo - WooCommerce Product Bundle Builder Premium: par VillaTheme – 1.1.3
Boxtal Connect: par Boxtal – 1.3.0
Colissimo shipping methods for WooCommerce: par Colissimo – 2.3.0
Contact Form 7: par Takayuki Miyoshi – 6.0
Copy & Delete Posts: par Inisev – 1.4.9
Delivengo: par delivengo – 1.3.0
Duplicator Pro: par Duplicator – 4.5.19.3
Fenêtre de connexion/inscription: par XootiX – 2.8.2
Flamingo: par Takayuki Miyoshi – 2.5
Fluid Checkout pour WooCommerce - Lite: par Fluid Checkout – 3.2.6
Newsletter, SMTP, Email marketing and Subscribe forms by Brevo: par Brevo – 3.1.90
Password Protected: par Password Protected – 2.7.5
Performance Lab: par WordPress Performance Team – 3.6.1
Plugins de paiement pour PayPal WooCommerce: par Plugins de paiement
support@paymentplugins.com – 1.0.53

Side Cart WooCommerce: par XootiX – 2.5.5
Site Reviews: par Paul Ryley – 7.2.3
WooCommerce Advanced Bulk Edit Products, Orders, Coupons, Any WordPress Post Type - Smart Manager: par StoreApps – 8.50.0
TranslatePress - Business: par Cozmoslabs
Razvan Mocanu
Madalin Ungureanu – 1.4.8

TranslatePress - Multilingual: par Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.9.0

User Switching: par John Blackbourn – 1.9.0
Récupération d’abandon de panier WooCommerce: par CartFlows Inc – 1.3.0
Discount Rules PRO 2.0: par Flycart – 2.6.5
Discount Rules Core: par Flycart – 2.6.6
Scellius for WooCommerce: par Lyra Network – 1.14.2
Brevo - WooCommerce Email Marketing: par Brevo – 4.0.31
WooCommerce: par Automattic – 9.4.2
Wordfence Security: par Wordfence – 8.0.1
Yoast SEO: par L’équipe Yoast – 23.9
WP Custom Admin Interface: par Martin Gibson – 7.37
WP Umbrella: par WP Umbrella - Backup & Manage WordPress – 2.16.4
WP Mail SMTP Pro: par WP Mail SMTP – 4.1.0
WP Rocket: par WP Media – 3.12.3.3
Custom Product Tabs for WooCommerce: par Code Parrots – 1.8.5
YITH WooCommerce Account Funds Premium: par YITH – 2.1.0
YITH WooCommerce Affiliates Premium: par YITH – 3.12.0
YITH WooCommerce PDF Invoices & Packing Slips Premium: par YITH – 4.24.1

### Inactive Plugins (1) ###

Uniweb Custom - Thérapeute L'oiseau vert: par Uniweb (David Granier) – 1

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Performance Lab Server Timing Object Cache Drop-In

### Must Use Plugins (2) ###

WP Umbrella: par WP Umbrella – 1.0.0
_WPHealthHandlerMU.php: par  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bopobb (bopobb)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
ywf_deposit (ywf_deposit)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 jours
Level threshold: –
Log directory size: 2 Mo

### WC Pages ###

Base de la boutique: #1753 - /boutique/
Panier: #13 - /panier/ -  Contient le code court [woocommerce_cart]
Commander: #14 - /commander/ -  Contient le code court [woocommerce_checkout]
Mon compte: #15 - /mon-compte/
Conditions générales de vente et d’utilisation: #1781 - /conditions-dutilisations/

### Theme ###

Name: Bootstrap 5 Child
Version: 3.3.5.1681976597
Author URL: https://them.es/
Child Theme: ✔
Parent Theme Name: Bootstrap 5
Parent Theme Version: 3.3.5
Parent Theme Author URL: https://them.es/
WooCommerce Support: ❌ Non déclaré

### Templates ###

Overrides: loiseauvert-child/woocommerce/content-product.php version 3.6.0 est obsolète. La version du noyau est 9.4.0
loiseauvert-child/woocommerce/content-single-product.php
/home/campiws/loiseauvert/www/wp-content/plugins/easy-login-woocommerce//templates//xoo-el-wc-checkout-form-login.php
loiseauvert-child/woocommerce/myaccount/dashboard.php
/home/campiws/loiseauvert/www/wp-content/plugins/easy-login-woocommerce//templates//xoo-el-wc-form-login.php
loiseauvert-child/woocommerce/myaccount/navigation.php
loiseauvert-child/woocommerce/single-product/tabs/description.php
loiseauvert-child/woocommerce/single-product/title.php
loiseauvert-child/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Apprenez comment mettre à jour					 |
					
						
					
					
						Supprimer le cache des informations sur le thème de l’état système

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2024-11-28 07:45:49 +01:00
Options: ✔
Notes: 124
Onboarding: completed

### Action Scheduler ###

Terminé: 9 416
Oldest: 2024-11-20 09:22:59 +0100
Newest: 2024-11-27 09:22:12 +0100

Échoué: 2 825
Oldest: 2023-04-20 11:15:25 +0200
Newest: 2024-11-26 16:37:55 +0100

En attente: 11
Oldest: 2024-11-27 09:23:12 +0100
Newest: 2025-02-20 11:53:21 +0100


### Status report information ###

Generated at: 2024-11-27 09:22:28 +01:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment] 2024-11-28 06:02
Hi @uniweb31! Thanks for reporting the issue - it seems to be a duplicate of https://github.com/woocommerce/woocommerce/issues/46771 - please add your feedback and follow the progress there. I am closing this issue since it is already being worked on/discussed in https://github.com/woocommerce/woocommerce/issues/46771.

**Closed as completed by juliaamosova** 2024-11-28 06:02 UTC
Labels: Bug, type: community contribution
