### ISSUE TITLE
[5.8 RC-1]: coupon restrictions

### ISSUE THREAD

**Issue by artprojectgroup** [woothemes/woocommerce#30833] opened 2021-09-29 08:30 UTC
Tested in version 5.7.1 with the same result. This issue was reported here too: https://github.com/woocommerce/woocommerce/issues/26289.

In a coupon add one or more products in coupon restrictions. Everything works fine.

Then add an email to allowed emails. Doesn't work. The coupon can be used by a guest user or anybody without that email restricted. 

Until press complete order button the coupon isn't cleared. The coupon must be cleared when the user add it not in the order complete action.

Tested with Storefront theme.

Kind regards.

**Comment by zhongruige** [comment] 2021-09-29 19:23
Hi {username},

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

* On a new install of WooCommerce (tested on both 5.7.1 and 5.8 RC1) I created a coupon with the code `restricted` and limited to a specific email address, `test@email.com`:

<img width="1311" alt="Screen Shot 2021-09-29 at 13 20 31" src="https://user-images.githubusercontent.com/71906536/135334654-e03c5085-b577-4740-96c5-8e2da4d43247.png">

* I then placed an order, using a different email address, `fake@email.com`:

<img width="668" alt="Screen Shot 2021-09-29 at 13 18 12" src="https://user-images.githubusercontent.com/71906536/135334732-6c1451ba-16fc-4a44-b6d3-6dfb52209e89.png">

* I was properly restricted when I tried to place an order using the `restricted` coupon code:

<img width="1345" alt="Screen Shot 2021-09-29 at 13 18 18" src="https://user-images.githubusercontent.com/71906536/135334781-896339f5-0642-4805-b9ea-45aaadf576fd.png">

Please provide us with more details about the issue which may help us to evaluate it further. 

* Can you provide some more detail on how you're entering the emails to be restricted? Are you using wildcards, or specific email addresses?
* Can you provide some more details around this:

> Until press complete order button the coupon isn't cleared. The coupon must be cleared when the user add it not in the order complete action.

Just wanted to clarify this, is it the coupon is removed when the order is placed, as expected, but the ask here would be once the email address is added the coupon code is removed immediately without needing to hit the complete order button?

Additionally, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

Thanks in advance!

**Comment by artprojectgroup** [comment] 2021-09-30 09:59
This is the coupon:
![image](https://user-images.githubusercontent.com/6569259/135430637-c2e20b4e-e2ca-42e5-b032-ea37266777a9.jpeg)

This is what happens in checkout:
![image](https://user-images.githubusercontent.com/6569259/135431081-d62f6677-3762-4143-a349-5aae83dc1f28.jpeg)

The coupon can be used by a guest user, for example and it isn't removed until you press "Realizar el pedido" button:
![image](https://user-images.githubusercontent.com/6569259/135431271-b0721f43-0571-473c-ae3b-fbc4b46f1b6c.jpeg)

Kind regards.

**Comment by AashikP** [comment] 2021-10-23 09:34
Hello @artprojectgroup 

Can you please confirm if this can be replicated in the final release of WooCommerce 5.8?

I'm asking because this is not something I could replicate with the following set-up:

![https://d.pr/i/xfAaxP+](https://d.pr/i/xfAaxP+)

![https://d.pr/i/wEOiqp+](https://d.pr/i/wEOiqp+)

Cart page:

![https://d.pr/i/U9Jv5X+](https://d.pr/i/U9Jv5X+)

If you can still replicate this, can you please confirm the coupon type you're using?

Along with that, please also share your System Status Report. You can find it via WooCommerce > Status. Select “Get system report” and then “Copy for support”.  Once you’ve done that, paste it here in your response.

**Comment by artprojectgroup** [comment] 2021-10-25 07:36
Tested on WooCommerce version 5.9 Beta 1 and it doesn't work properly yet.

Coupon configuration:
![image](https://user-images.githubusercontent.com/6569259/138653064-896ceee7-b21e-400f-adc5-2df719d24fb8.jpeg)
![image](https://user-images.githubusercontent.com/6569259/138653110-92e9bbec-902e-4bcf-92aa-6fe22c84323f.jpeg)
![image](https://user-images.githubusercontent.com/6569259/138653134-bb99a601-ba13-4a06-b9ce-b3d435a0bfe8.jpeg)

Coupon applied in the cart and checkout without problems:
![image](https://user-images.githubusercontent.com/6569259/138653359-370c42ea-203a-42c4-bf9c-7e4a40453d87.jpeg)
![image](https://user-images.githubusercontent.com/6569259/138653516-f84f8b1d-09f2-4942-bbbb-81f722a764ab.jpeg)

System Status Report:
`
### WordPress Environment ###

WordPress address (URL): http://localhost:8888/wordpress
Site address (URL): http://localhost:8888/wordpress
WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.1.0
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.8.0-rc.2
Log Directory Writable: ✔
WP Version: 5.9-alpha-51929
WP Multisite: –
WP Memory Limit: 40 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2u PHP/7.4.21 mod_wsgi/3.5 Python/2.7.13 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.30.1
PHP Version: 7.4.21
PHP Post Max Size: 8 MB
PHP Time Limit: 380
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.7.34
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: ev4iro_
Tamaño total de la base de datos: 7.34MB
Tamaño de los datos de la base de datos: 5.83MB
Tamaño del índice de la base de datos: 1.51MB
ev4iro_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ev4iro_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ev4iro_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ev4iro_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
ev4iro_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ev4iro_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ev4iro_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
ev4iro_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ev4iro_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
ev4iro_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ev4iro_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
ev4iro_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ev4iro_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ev4iro_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ev4iro_actionscheduler_actions: Datos: 0.02MB + Índice: 0.13MB + Motor InnoDB
ev4iro_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ev4iro_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ev4iro_actionscheduler_logs: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ev4iro_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ev4iro_comments: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
ev4iro_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ev4iro_options: Datos: 3.03MB + Índice: 0.06MB + Motor InnoDB
ev4iro_postmeta: Datos: 1.52MB + Índice: 0.11MB + Motor InnoDB
ev4iro_posts: Datos: 0.45MB + Índice: 0.06MB + Motor InnoDB
ev4iro_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ev4iro_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ev4iro_term_relationships: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ev4iro_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ev4iro_usermeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ev4iro_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
ev4iro_wc_admin_notes: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
ev4iro_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ev4iro_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
ev4iro_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ev4iro_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ev4iro_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ev4iro_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
ev4iro_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
ev4iro_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ev4iro_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
ev4iro_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
ev4iro_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ev4iro_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB

### Post Type Counts ###

attachment: 23
page: 7
post: 2
postman_sent_mail: 46
product: 18
product_variation: 7
shop_coupon: 1
shop_order: 1
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ❌
					Tu tienda no está usando HTTPS. Aprende más sobre HTTPS y los certificados SSL.
Hide errors from visitors: ✔

### Active Plugins (14) ###

Query Monitor: por John Blackbourn – 3.7.1
Advanced Custom Fields: Extended: por ACF Extended – 0.8.8.6
Advanced Custom Fields PRO: por Delicious Brains – 5.10.2
Cookie Notice & Compliance for GDPR / CCPA: por Hu-manity.co – 2.1.5
Loco Translate: por Tim Whitlock – 2.5.5
Post SMTP: por Yehuda Hassine – 2.0.23
WC - APG myGESTIÓN: por Art Project Group – 0.7.3.1
WC - APG Campo NIF/CIF/NIE: por Art Project Group – 1.7
WC - Pasarela de pago Cetelem: por Banco Cetelem S.A.U. – 2.5
WC - Pasarela de pago eCredit Moto: por Banco Cetelem S.A.U. – 1.0.5
WC - APG Notificaciones SMS: por Art Project Group – 2.24.1
WooCommerce Beta Tester: por WooCommerce – 2.0.4
WooCommerce: por Automattic – 5.9.0-beta.1
WordPress Beta Tester: por Peter Westwood
Andy Fragen – 3.1.4


### Inactive Plugins (187) ###

0$ Woocommerce Product Feed: por Victor Ciobanu & Art Project Group – 0.35
ADning: por Tunafish – 1.4.1
Advanced Custom Fields Multilingual: por OnTheGoSystems – 1.8.2
Advanced Order Export For WooCommerce: por AlgolPlus – 3.1.9
Advanced Product Fields for WooCommerce: por StudioWombat – 1.4.1
Akismet Anti-Spam: por Automattic – 4.2.1
allow-reinstalls: por bobbingwide – 0.0.2
Amount Left for Free Shipping for WooCommerce: por WPFactory – 2.1.0
Anti-Malware Security and Brute-Force Firewall: por Eli Scheetz – 4.20.92
APG - Lista de atributos: por Art Project Group – 0.1
APG - Oculta enlaces telefónicos: por Art Project Group – 0.1
APG Buscador de Dispositivos: por Art Project Group – 0.1
APG Dolça Catalunya: por Art Project Group – 0.1
APG Elha FormCraft: por Art Project Group – 0.1
APG Elha WhatsApp: por Art Project Group – 0.2
APG Espacio de disco - 20 Comunicación: por Art Project Group – 0.2
APG Mediñà Boat Sharing: por Art Project Group – 0.1
APG Multiple Sitemaps: por Art Project Group – 0.1
APG Partition Booster: por Art Project Group – 0.1
APG Pórtico Sport: por Art Project Group – 0.1.5
AWS Price Calculator: por Altos Web Solutions Italia – 2.2.0
Better Search Replace: por Delicious Brains – 1.3.4
Booster for WooCommerce: por Pluggabl LLC – 5.4.7
Booster Plus for WooCommerce: por Algoritmika Ltd – 3.8.0
Checkout Field Editor for WooCommerce: por ThemeHigh – 1.5.0
Classic Editor: por WordPress Contributors – 1.6.2
Classic Widgets: por WordPress Contributors – 0.2
Comefruta Mixins: por Jose Angel Parra – 1.0
Conditional Menus: por Themify – 1.1.9
Contact Form 7: por Takayuki Miyoshi – 5.5.2
Contact Listing for WP Job Manager: por Astoundify – 1.4.1
Cookie Information | Free WP GDPR Consent Plugin: por Cookie Information – 2.0.2
CrossPress 2: por Art Project Group – 2.0.3
Custom Base Terms: por Art Project Group – 1.0.2.1
Custom Payment Gateways for WooCommerce: por Imaginate Solutions – 1.6.6
Custom Post Type UI: por WebDevStudios – 1.10.0
Deliverea Shipping: por Deliverea Shipping Solutions S.L – 1.0.6
Disable Emails: por WebAware – 1.7.0
Diweb - Salesforce: por Art Project Group – 0.2
DOMINATION! Let WooCommerce take control of your dashboard: por Claudio Sanches – 1.2.0
Donaciones: por Art Project Group – 1.0.2
Download After Email: por MK-Scripts – 2.1.1
Easy Image Gallery - 20 Comunicación: por Andrew Munro
Sumobi
Art Project Group – 2.0

Elementor: por Elementor.com – 3.4.6
Elementor Pro: por Elementor.com – 3.3.8
Enable jQuery Migrate Helper: por The WordPress Team – 1.3.0
Envato Market: por Envato – 2.0.6
Extendons: Woocommerce Registration Plugin - Add Custom Registration Fields: por Extendons – 2.0.1
Extra Product Options (Product Addons) for WooCommerce: por ThemeHigh – 3.0.8
Fusion Builder: por ThemeFusion – 2.1.2
Fusion Core: por ThemeFusion – 4.1.2
Google Image Sitemap Feed With Multisite Support: por Art Project Group – 1.2.0.4
Google Mobile Sitemap Feed With Multisite Support: por Art Project Group – 1.0.1.1
Google News Sitemap Feed With Multisite Support: por Tim Brandon – 3.3
Google Video Sitemap Feed With Multisite Support: por Art Project Group – 1.8.2
Gravity Forms: por Gravity Forms – 2.4.23
Gravity Forms Multilingual: por OnTheGoSystems – 1.6.0
Health Check & Troubleshooting: por The WordPress.org community – 1.4.5
If Menu - Visibility control for menu items: por Layered – 0.16.2
LayerSlider WP: por Kreatura Media – 6.8.4
Members: por MemberPress – 3.1.5
Multi Order for WooCommerce: por WP Wham – 1.4.4
Multiple Shipping Address Woocommerce: por Ocean Infotech – 1.0
Nextend Social Login: por Nextendweb – 3.1.2
optimizador.io: por David Noguera (webempresa.com) – 1.0.22
Optimize Database after Deleting Revisions: por CAGE Web Design | Rolf van Gelder
Eindhoven
The Netherlands – 5.0.9

Order Splitter for WooCommerce: por Fahad Mahmood – 4.2.6
Perfmatters: por forgemedia – 1.6.6
PPOM for WooCommerce by N-MEDIA: por Najeeb Ahmad – 23.5
Price Matrix for Woocommerce: por AzMarket – 1.2.1
Product GTIN (EAN, UPC, ISBN) for WooCommerce: por Emanuela Castorina – 1.1.1
Product Open Pricing (Name Your Price) for WooCommerce: por WP Wham – 1.7.0
Product Options and Price Calculation Formulas for WooCommerce – Uni CPO: por MooMoo Agency – 4.9.12
Product Quantity for WooCommerce Pro: por Algoritmika Ltd – 1.3.0-dev
Push Syndication: por Automattic – 1.0
Regenerate Thumbnails: por Alex Mills (Viper007Bond) – 3.1.5
Regions for WP Job Manager: por Astoundify – 1.18.0
Restrict Content Pro: por Sandhills Development
LLC – 3.3.10

Restrict Content Pro - Bank Transfer Gateway (3rd-Party Addon): por KryptoniteWP – 1.0.0
Role Based Price For WooCommerce: por Varun Sridharan – 3.3.7
Salon Booking Redsys Payment Plugin: por Salon Booking team – 0.1
Salon Booking Wordpress Plugin - Free Version: por Salon Booking System – 7.1
Salon Booking Wordpress Plugin - PRO COD: por Wordpress Chef / Plugins – 3.20
Send PDF for Contact Form 7: por Florent Maillefaud – 0.8.6
Slider Revolution: por ThemePunch – 6.5.5
Star CloudPRNT for WooCommerce: por lawrenceowen
athompson1
gcubero
fmahmood – 2.0.3

States, Cities, and Places for WooCommerce: por Kingsley Ochu – 1.3.2
SUMO Reward Points: por Fantastic Plugins – 21.2
themesFor.me Google Product Feed for WooCommerce: por Themes For Me – 1.0.7
Ultimate Addons for WPBakery Page Builder: por Brainstorm Force – 3.19.10
UpdraftPlus - Backup/Restore: por UpdraftPlus.Com
DavidAnderson – 2.16.60.25

WC - APG AEON Libros: por Art Project Group – 0.1
WC - APG City: por Art Project Group – 1.1.0.1
WC - APG Comefruta: por Art Project Group – 0.7.1
WC - APG Cont4: por Art Project Group – 0.3.4
WC - APG En Suelo Firme: por Art Project Group – 0.1
WC - APG Free Shipping: por Art Project Group – 2.6.0.1
WC - APG Harit Ayurveda: por Art Project Group – 0.1
WC - APG Kamuabu: por Art Project Group – 0.1
WC - APG Makito: por Art Project Group – 0.1
WC - APG MODDO: por Art Project Group – 0.6
WC - APG myGESTIÓN TEST: por Art Project Group – 0.1
WC - APG Navision: por Art Project Group – 0.1
WC - APG Navision Arranzeramica: por Art Project Group – 0.1
WC - APG Notification: por Art Project Group – 0.2
WC - APG Opening hour by User role: por Art Project Group – 0.1
WC - APG Order management: por Art Project Group – 0.2
WC - APG Paack: por Art Project Group – 0.1
WC - APG Powergreen: por Art Project Group – 0.2
WC - APG Privilegiis: por Privilegiis & Art Project Group – 0.1
WC - APG Qapla: por Art Project Group – 0.1
WC - APG Suministros Orduña: por Art Project Group – 0.1.1
WC - APG temporizador: por Art Project Group – 0.1
WC - APG Viacompras payment gateway: por Art Project Group – 0.1.2.5
WC - APG Weight Shipping: por Art Project Group – 2.4.0.5
WC - Tapervaper: por Art Project Group – 0.6.1
WC - Tapervaper Pedidos: por Art Project Group – 0.2
WC Duplicate Order: por Jamie Gill – 1.7
WC Vendors Marketplace: por WC Vendors – 2.3.2
Win Wheel For Wordpress - APG: por <a href="https://codecanyon.net/user/superduper-plugins">Jure Hajdinjak</a> – 3.2.2
Woo Checkout Editor: por Themeco – 2.0.0
WooCommerce: por WooThemes – 2.6.14
WooCommerce - APG Free Postcode/State/Country Shipping: por Art Project Group – 2.2.0.12
WooCommerce - APG Google Merchant Center: por Art Project Group – 0.1
WooCommerce - APG Google Merchant Center: por Art Project Group – 0.1
WooCommerce Address Book: por Hall Internet Marketing – 1.7.5
WooCommerce Advance Order Status: por AppZab – 1.0.2
WooCommerce Blocks: por Automattic – 6.1.0
WooCommerce Bookings: por Automattic – 1.10.11
WooCommerce Checkout Field Editor: por WooCommerce – 1.5.13
WooCommerce Customer/Order/Coupon CSV Import Suite: por SkyVerge – 3.9.1
Woocommerce customer delivery date time selection: por raficsedu – 1.1
WooCommerce Custom Payment Gateway: por WPRuby – 1.3.4
WooCommerce Custom Product Addons (Free): por Acowebs – 2.5.5
WooCommerce Deposits: por Automattic – 1.3.1
WooCommerce Google Merchant Center Feed: por claudiosanches – 1.0.6
WooCommerce Gravity Forms Product Add-Ons: por Element Stark – 3.3.18
WooCommerce Measurement Price Calculator: por SkyVerge – 3.12.4
WooCommerce Multilingual: por OnTheGoSystems – 4.12.1
WooCommerce Order Delivery: por Themesquad – 1.7.1
WooCommerce Order Status & Actions Manager: por Actuality Extensions – 2.2.3
WooCommerce Order Status Manager: por SkyVerge – 1.12.1
WooCommerce PayPal Checkout Gateway: por WooCommerce – 2.1.3
WooCommerce PDF Invoices & Packing Slips: por Ewout Fernhout – 2.10.1
WooCommerce PDF Invoices & Packing Slips Premium Templates: por Ewout Fernhout – 2.5.7
WooCommerce PDF Invoices & Packing Slips Professional: por Ewout Fernhout – 2.2.4
Woocommerce Poor Guys Swiss Knife: por Uli Hake – 2.2.4
WooCommerce Prices By User Role: por Festi-Team – 4.3
WooCommerce Product Add-ons: por WooCommerce – 3.3.1
WooCommerce Product Bundles: por SomewhereWarm – 5.7.1
WooCommerce Product Tables Feature Plugin: por Automattic – 1.0.0-dev
WooCommerce Quick Order One Page Shop: por SolverCircle – 2.1
WooCommerce Redsys payment gateway: por Jesús Ángel del Pozo Domínguez – 1.2.10
WooCommerce Shipping Tracking: por Lagudi Domenico – 22.4
WooCommerce Stripe Gateway: por WooCommerce – 5.7.0
WooCommerce Subscriptions: por WooCommerce – 3.0.10
WooCommerce Super Shipping: por Woodemia – 1.2.7
WooCommerce TM Extra Product Options: por themeComplete – 4.7.1
WooCommerce Variation Swatches and Photos: por Lucas Stark – 3.0.3
WooSidebars: por WooCommerce – 1.4.5
WordPress Importer: por wordpressdotorg – 0.7
WordPress User Extra Fields: por Lagudi Domenico – 12.9
WP All Export Pro: por Soflyy – 1.5.10
WP All Import - ACF Add-On: por Soflyy – 3.0.7
WP All Import - WooCommerce Add-On Pro: por Soflyy – 3.2.5
WP All Import Pro: por Soflyy – 4.6.5
WPBakery Page Builder: por Michael M - WPBakery.com – 6.7.0
WP Crontrol: por John Blackbourn & crontributors – 1.10.0
WP Job Manager: por Automattic – 1.35.2
WPML All Import: por OnTheGoSystems – 2.2.0
WPML CMS Nav: por OnTheGoSystems – 1.5.5
WPML Media: por OnTheGoSystems – 2.6.4
WPML Multilingual CMS: por OnTheGoSystems – 4.4.10
WPML Page Builders: por OnTheGoSystems – 1.1.3
WPML Sticky Links: por OnTheGoSystems – 1.5.4
WPML String Translation: por OnTheGoSystems – 3.1.8
WPML Translation Management: por OnTheGoSystems – 2.10.6
WP Reset: por WebFactory Ltd – 1.93
Wpresidence -Theme Core Functionality: por wpestate – 3.9.1
WpResidence Elementor Widgets: por WpEstate – 3.9
WP User Frontend: por weDevs – 3.5.21
YITH WooCommerce Brands Add-on: por YITH – 1.7.0
YITH WooCommerce Product Add-ons & Extra Options: por YITH – 2.2.6
YITH WooCommerce Product Add-ons Premium: por YITH – 1.5.34
YITH WooCommerce Role Based Prices Premium: por YITH – 1.1.17
YITH WooCommerce Wishlist: por YITH – 3.2.0
Zuiton Mosch: por Zuiton – 0.1

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: #6 - /shop
Carrito: #7 - /cart
Finalizar compra: #8 - /checkout
Mi cuenta: #9 - /my-account
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Completo: 18
Oldest: 2021-09-29 11:31:30 +0200
Newest: 2021-10-25 09:08:13 +0200


### Status report information ###

Generated at: 2021-10-25 09:35:00 +02:00
`

Best regards.

**Comment by swatipawarGS** [comment] 2021-11-26 13:49
Hi @artprojectgroup ,

Thank you for the updated information, we really appreciate your help. We are able to reproduce the issue on our end using WooCommerce 5.9.0 version and WordPress 5.8.2 version.


Please find below  screenshots for reference :

Coupon configuration:


![#30833(setting1)](https://user-images.githubusercontent.com/94531721/143553485-4fce114f-b53f-4a26-96e5-fad216fbff64.jpg)

![#30833(setting2)](https://user-images.githubusercontent.com/94531721/143553487-caf0805b-9a6d-44b3-8a28-d451bd53c872.jpg)


Coupon applied in the cart and checkout : 

![#30833(Cart)](https://user-images.githubusercontent.com/94531721/143553614-7064cd38-cfb3-4a23-970d-3009d9cba9d4.jpg)

![#30833(Checkout1)](https://user-images.githubusercontent.com/94531721/143553620-302413e9-aee0-4bf0-815f-ad70829b4e3a.jpg)

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by artprojectgroup** [comment] 2021-11-26 16:46
Thank you!

**Comment by artprojectgroup** [comment] 2021-11-30 18:55
Tested in WordPress 5.9 Alpha 52262 and WooCommerce 6.0 Beta 1 with the same result.

Best regards.

**Comment by barryhughes** [comment] 2022-05-27 18:21
Closing; we'll use existing issue #26289 to track this problem.

**Closed as completed by barryhughes** 2022-05-27 18:21 UTC
Labels: Bug, plugin: woocommerce
