### ISSUE TITLE
Download links redirect to yahoo.com

### ISSUE THREAD

**Issue by QbicFox** [woothemes/woocommerce#11916] opened 2016-09-14 09:16 UTC
Hi,

if a user buy a product from my shop and use yahoo email, after payment is done and click on download link, go to yahoo.com instead of download link.

if user use gmail has no error and download file without problems.

**Comment by afshinnajafi** [comment] 2016-09-14 10:38
hi everyone
i have same problem 
pls fix this bug

**Comment by claudiosmweb** [comment] 2016-09-15 04:53
Can you guys show me the System Status report for each installation?
I'm trying to reproduce it, but without any success.

**Comment by QbicFox** [comment] 2016-09-15 05:18
This problem only happens with Iran IP and if I use a proxy everything works very well.
Is there anyway to remove email address from downloads link ?

**Comment by shamloo** [comment] 2016-09-15 10:08
if problem comes from URL strings that contains "yahoo.com" , so its can be solved by encrypting email address.
although this problem is not related to WC but can be fix.

**Comment by onlinehazard** [comment] 2016-09-15 11:44
Hi, I have exactly the same problem with Iran IP and Yahoo emails.

**Comment by fardinla96** [comment] 2016-09-15 14:58
HI
I have faced with this problem alot.
please fix this problem

**Comment by claudiosmweb** [comment] 2016-09-16 02:07
This only happens on Iran?

**Comment by afshinnajafi** [comment] 2016-09-16 07:12
hi
yes exactly

**Comment by afshinnajafi** [comment] 2016-09-18 12:11
Wating...

**Comment by QbicFox** [comment] 2016-09-18 14:26
By enabling the force ssl setting under WooCommerce > Settings > Checkout > Checkout Options > Force secure checkout, problem will be solve.

**Comment by ezoji** [comment] 2016-09-18 17:06
hi
I have this problem too, and Force secure not solve it.

**Comment by opportus** [comment] 2016-09-18 18:44
@QbicFox @afshinnajafi @ezoji @fardinla96 @onlinehazard 

Could you guys please past your status report here ?
WooCommerce > System Status

**Comment by ezoji** [comment] 2016-09-18 19:06
hi @opportus

WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.26
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.45 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 8 MB
Default Timezone is UTC: ❌ Default timezone is Asia/Tehran - it should be UTC
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔


WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔


this problem only with Iran IP and Yahoo emails!
http://site.com/?download_file=1569&order=wc_order_57de8d6b667a1&email=karim@yahoo.com&key=d04f94399fdf2a46b7f83eca93152ff1

redirect to https://us.yahoo.com

**Comment by opportus** [comment] 2016-09-18 20:28
I have been able to replicate the issue with an Iranian proxy: 151.243.107.14:8080

This will redirect to us.yahoo.com:
http://site.net/?download_file=99&order=wc_order_57def612ea9&email=hassan%40yahoo.com&key=f7d0bf2d3bc4e0e7402d5d9835ea7467

This will redirect on the shop as expected:
http://site.net/?download_file=99&order=wc_order_57def612ea9&email=hassan%40gmail.com&key=f7d0bf2d3bc4e0e7402d5d9835ea7467

Anyway, other links containing email addresses such as "%40free.fr" get redirected to some strange Iranian sites.

Looks like an Iranian DNS issue or something, not a WooCcommerce issue...

**Comment by justinshreve** [comment] 2016-09-27 17:31
@opportus Thanks for digging. Closing as invalid since this is not a WC issue.

**Closed by justinshreve** 2016-09-27 17:31 UTC

**Comment by hannanstd** [comment] 2016-09-28 06:46
install this plugin for fix problem : 
http://up.persianscript.ir/uploads2/5936-wc-yahoo-redirect.zip
