### ISSUE TITLE
Geo IP lookup performance

### ISSUE THREAD

**Issue by sanchothefat** [woothemes/woocommerce#10590] opened 2016-03-22 11:50 UTC
## EXPLANATION OF THE ISSUE

Using the latest version of WC on a multisite site with a fair amount of traffic I found that the geo IP lookup requests caused a huge slow down due to timeouts and perhaps rate limitations. I couldn't dig too deeply as I had to disable the plugin quickly.

In the following image the web external time in green revealed that the various IP location APIs in use were where all the time was being spent.

<img width="681" alt="screenshot 2016-03-21 10 24 00" src="https://cloud.githubusercontent.com/assets/23417/13950522/669d88d2-f023-11e5-81f7-00d668add799.png">

<img width="628" alt="screenshot 2016-03-21 10 27 02" src="https://cloud.githubusercontent.com/assets/23417/13950532/791fe842-f023-11e5-8f75-811b3f98a74c.png">

## STEPS TO REPRODUCE THE ISSUE

1. Activate WC
2. Throw lots of concurrent traffic at it from different locations

## SYSTEM STATUS REPORT

I wasn't able to fetch this as the site was unresponsive at the time of deactivation. If there's a persistent log I can fetch it from let me know and I'll update.

## ADDITIONAL

Apologies for the sparse amount of information. In terms of resolution the current system obviously works for most people but perhaps it'll be possible to enable a feature that listens for a `$_SERVER` header provided by Nginx's built in geo IP features. Or if there isn't already it'd be cool to have a way to disable Geo IP location by default, rate limit it, or significantly reduce the request timeout.

**Comment by mikejolley** [comment] 2016-03-22 12:05
Will be closing this as its not a bug, but I can definitely steer you.

From your breakdown I can see your server is using the fallback - this is slower because it makes external calls per user.

https://github.com/woothemes/woocommerce/blob/e09613d7da4c7ffed7c7f989373caa8c29d611f8/includes/class-wc-geolocation.php#L137-L140

So you must be missing the maxmind .dat file which is usually downloaded automatically: https://github.com/woothemes/woocommerce/blob/e09613d7da4c7ffed7c7f989373caa8c29d611f8/includes/class-wc-geolocation.php#L164

You can download theme manually and upload it to the correct location if you wish. If the directory is not writeable or cron jobs are disabled it may explain why its not there already.

To disable geolocation completely, change the 'default customer address' option in settings to 'shop base'.

Thanks

**Closed by mikejolley** 2016-03-22 12:05 UTC

**Comment by sanchothefat** [comment] 2016-03-22 12:08
@mikejolley ace, thanks Mike! Dat file sounds like something we can roll into the app. Wasn't aware of that not having a lot of experience with WC directly. And yeah file system isn't writeable as you suggest.

**Comment by sanchothefat** [comment] 2016-03-22 13:02
@mikejolley apologies, one question. Is there a way to change the location of the `.dat` files. Would prefer not to replicate them on a multisite for all uploads folders if poss. Will look into why they couldn't download if it's in the uploads folder.

**Comment by mikejolley** [comment] 2016-03-22 13:07
It's not filterable right now. Feel free to submit a PR if you need one.

**Comment by sanchothefat** [comment] 2016-03-22 13:28
@mikejolley :+1:
