### ISSUE TITLE
E_DEPRECATED: Creation of dynamic property WC_Order_Item_Shipping::$legacy_package_key is deprecated

### ISSUE THREAD

**Issue by mondalaci** [woothemes/woocommerce#44621] opened 2024-02-14 17:17 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I'm using PHP 8.2 and Rollbar to log errors. The following error was captured:

```
E_DEPRECATED: Creation of dynamic property WC_Order_Item_Shipping::$legacy_package_key is deprecated
(/var/www/ultimatehackingkeyboard.com/wordpress/wp-content/plugins/woocommerce/includes/class-wc-checkout.php:607)

WC_Checkout::create_order_shipping_lines(/var/www/ultimatehackingkeyboard.com/wordpress/wp-content/plugins/woocommerce/includes/class-wc-checkout.php:501)

WC_Checkout::set_data_from_cart(/var/www/ultimatehackingkeyboard.com/wordpress/wp-content/plugins/woocommerce/includes/class-wc-checkout.php:442)

WC_Checkout::create_order(/var/www/ultimatehackingkeyboard.com/wordpress/wp-content/plugins/woocommerce/includes/class-wc-checkout.php:1264)

WC_Checkout::process_checkout(/var/www/ultimatehackingkeyboard.com/wordpress/wp-content/plugins/woocommerce/includes/class-wc-ajax.php:508)

WC_AJAX::checkout(/var/www/ultimatehackingkeyboard.com/wordpress/wp-includes/class-wp-hook.php:324)

WP_Hook::apply_filters(/var/www/ultimatehackingkeyboard.com/wordpress/wp-includes/class-wp-hook.php:348)

WP_Hook::do_action(/var/www/ultimatehackingkeyboard.com/wordpress/wp-includes/plugin.php:517)

do_action(/var/www/ultimatehackingkeyboard.com/wordpress/wp-content/plugins/woocommerce/includes/class-wc-ajax.php:96)

WC_AJAX::do_wc_ajax(/var/www/ultimatehackingkeyboard.com/wordpress/wp-includes/class-wp-hook.php:324)

WP_Hook::apply_filters(/var/www/ultimatehackingkeyboard.com/wordpress/wp-includes/class-wp-hook.php:348)

WP_Hook::do_action(/var/www/ultimatehackingkeyboard.com/wordpress/wp-includes/plugin.php:517)

do_action(/var/www/ultimatehackingkeyboard.com/wordpress/wp-includes/template-loader.php:13)

require_once(/var/www/ultimatehackingkeyboard.com/wordpress/wp-blog-header.php:19)

require(/var/www/ultimatehackingkeyboard.com/wordpress/index.php:17)
```

### Expected behavior

WooCommerce shouldn't exhibit such errors.

### Actual behavior

WooCommerce exhibits this error.

### Steps to reproduce

I don't have the exact steps, but this error gets triggered about a hundred times daily, and ours is a low-volume webshop.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://ultimatehackingkeyboard.com/wordpress
Site address (URL): https://ultimatehackingkeyboard.com
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.24.0
PHP Version: 8.2.10-2ubuntu1
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 8.2.1
OpenSSL/3.0.10

SUHOSIN Installed: –
MySQL Version: 8.0.36-0ubuntu0.23.10.1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: wp_
Total Database Size: 922.61MB
Database Data Size: 533.66MB
Database Index Size: 388.95MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items: Data: 4.50MB + Index: 2.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 147.16MB + Index: 46.05MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 6.02MB + Index: 8.69MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 5.02MB + Index: 4.02MB + Engine InnoDB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aelia_exchange_rates_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 2.52MB + Index: 0.34MB + Engine InnoDB
wp_comments: Data: 17.55MB + Index: 14.09MB + Engine InnoDB
wp_contact_form_log: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_dhl_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fusion_form_entries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fusion_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fusion_form_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fusion_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_iconic_was_fees: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jckpc_inventory: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_knowledgebase_auto: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_knowledgebase_log: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 14.36MB + Index: 1.08MB + Engine InnoDB
wp_postmeta: Data: 134.38MB + Index: 111.69MB + Engine InnoDB
wp_posts: Data: 53.45MB + Index: 7.80MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_shortpixel_folders: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_shortpixel_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_shortpixel_postmeta: Data: 4.52MB + Index: 4.22MB + Engine InnoDB
wp_shortpixel_queue: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.22MB + Index: 0.25MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 50.44MB + Index: 41.92MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 1.14MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 1.50MB + Index: 0.73MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 4.52MB + Index: 7.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 3.52MB + Index: 1.91MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 9.52MB + Index: 9.47MB + Engine InnoDB
wp_wc_order_stats: Data: 4.38MB + Index: 3.44MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.47MB + Index: 0.28MB + Engine InnoDB
wp_wc_orders: Data: 5.52MB + Index: 9.53MB + Engine InnoDB
wp_wc_orders_meta: Data: 41.58MB + Index: 109.58MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_saferpaycw_customer_contexts: Data: 0.14MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_saferpaycw_documents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_saferpaycw_ecc: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_saferpaycw_schema_version: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_saferpaycw_storage: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_saferpaycw_transactions: Data: 11.44MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_attachment_files: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_email_attachments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpmailsmtp_emails_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1289
custom_css: 1
customize_changeset: 2
cwginstocknotifier: 2
e-landing-page: 1
elementor_library: 6
mc4wp-form: 4
nav_menu_item: 6
oembed_cache: 4
page: 220
post: 174
product: 53
product_variation: 9
revision: 4352
shop_coupon: 1277
shop_order: 17315
shop_order_placehold: 128
shop_order_refund: 827
stc: 2
vpc-config: 1
wcct_countdown: 1
wp_global_styles: 1
wpcode: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: by codewoogeek – 5.1.0
Cardinity Payment Gateway: by Cardinity – 3.2.2
Elementor Pro: by Elementor.com – 3.19.2
Elementor: by Elementor.com – 3.19.2
Avada Builder: by ThemeFusion – 3.11.5
Avada Core: by ThemeFusion – 5.11.5
WooCommerce Attribute Swatches by Iconic: by Iconic  – 1.17.3
WooCommerce Product Configurator by Iconic: by Iconic – 1.21.2
Integration for Szamlazz.hu & WooCommerce: by Viszt Péter – 5.9
mame Saferpay for WooCommerce: by mame webdesign hüttig – 1.7.1
Rollbar: by Rollbar – 2.7.1
ShortPixel Image Optimizer: by ShortPixel - Convert WebP/AVIF & Optimize Images – 5.5.5
Theme Switcha: by Jeff Starr – 3.3.2
Aelia Foundation Classes for WooCommerce: by Aelia – 2.4.22.240109
Aelia Currency Switcher for WooCommerce: by Aelia – 5.1.3.240205
WooCommerce EU VAT Number: by WooCommerce – 2.9.1
WooCommerce Nested Category Layout: by SkyVerge – 1.20.1
Sequential Order Numbers for WooCommerce: by SkyVerge – 1.10.1
Aelia Tax Display by Country for WooCommerce: by Aelia – 1.20.10.240205
WooCommerce: by Automattic – 8.5.2
WordSnippets: by László Monda – 1.0.0
WP Fastest Cache Premium: by Emre Vona – 1.7.0
WP Fastest Cache: by Emre Vona – 1.2.3
WP Mail SMTP Pro: by WP Mail SMTP – 3.11.1
UGL DHL Shipping: by UGL – 1.0.0
UGL Knowledgebase: by UGL – 1.0.0
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.9.13.2

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #4622 - /shop
Cart: #4623 - /cart
Checkout: #4624 - /checkout
My account: #4625 - /my-account
Terms and conditions: #5610 - /terms-of-service

### Theme ###

Name: Avada-UHK
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 7.11.5
Parent Theme Author URL: https://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
avada-uhk/woocommerce/emails/customer-invoice.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### Számlázz.hu ###

PRO version: ✔
Path: /var/www/ultimatehackingkeyboard.com/wordpress/wp-content/uploads/wc_szamlazz
IPN URL: https://ultimatehackingkeyboard.com/?wc_szamlazz_ipn_url=9c2528199f4c0913de58c68d96b
Payment methods: Array
(
    [paypal] => Array
        (
            [deadline] => 
            [complete] => 1
            [proform] => 
            [deposit] => 1
            [name] => 
            [auto_disabled] => 
        )

    [mame_sp_creditcard] => Array
        (
            [deadline] => 
            [complete] => 1
            [proform] => 
            [deposit] => 1
            [name] => 
            [auto_disabled] => 
        )

    [cardinity] => Array
        (
            [deadline] => 
            [complete] => 1
            [proform] => 
            [deposit] => 1
            [name] => 
            [auto_disabled] => 
        )

    [sb_test] => Array
        (
            [deadline] => 
            [complete] => 1
            [proform] => 
            [deposit] => 1
            [name] => 
            [auto_disabled] => 
        )

)

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-14 21:32:00 +01:00
Options: ✔
Notes: 127
Onboarding: completed

### Action Scheduler ###

Complete: 19,293
Oldest: 2024-01-14 18:23:13 +0100
Newest: 2024-02-14 18:14:18 +0100

Failed: 17
Oldest: 2019-05-28 19:17:32 +0200
Newest: 2024-01-21 16:19:01 +0100

Pending: 13
Oldest: 2024-02-14 18:19:18 +0100
Newest: 2024-02-19 13:19:17 +0100

### Status report information ###

Generated at: 2024-02-14 18:16:04 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by wavvves** [comment] 2024-02-16 16:29
Hi @mondalaci, thank you for reporting this. The issue is already being tracked on https://github.com/woocommerce/woocommerce/issues/38857

I'm closing this one to avoid duplicate efforts.

**Closed as completed by wavvves** 2024-02-16 16:29 UTC
Labels: Bug, Checkout, type: technical debt, type: community contribution, Rubik
