### ISSUE TITLE
Bug in WooCommerce Status Display (WordPress Dashboard)

### ISSUE THREAD

**Issue by 79ho3ein** [woothemes/woocommerce#30812] opened 2021-09-24 17:14 UTC
hi
After the recent update, the status of WooCommerce is slightly displayed. It seems that something is missing.
![Screenshot (156)](https://user-images.githubusercontent.com/77163248/134714927-b5edf0ff-3940-42c0-bdd6-e3e9be6861cd.png)

please check, thank you

**Comment by tammullen** [comment] 2021-10-01 10:45
Hi @79ho3ein 

The number of details you provided is not enough for us to work with and identify what could be going on.

Please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Finally, it will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.

**Comment by 79ho3ein** [comment] 2021-10-02 10:42
hi @tammullen 
This issue has been resolved. In fact, there was no problem. I diagnosed it as a problem. thank you

**Closed as completed** 2021-10-02 10:42 UTC
Labels: needs: triage feedback
