### ISSUE TITLE
`Set up additional payments`page  

### ISSUE THREAD

**Issue by rogermattic** [woothemes/woocommerce#33625] opened 2022-06-27 14:44 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There are a few issues with the current version of the `Set up additional...` page, all listed below.

### Expected behavior

[As in this Figma design](e428PXC0QyEwYqtX48lLq0-fi-12830%3A95418): 
- [x] The title should say `Set up additional payment options` 
- [ ] The payment options displayed should be aligned with the _additional payment options_ listed [here](https://docs.google.com/spreadsheets/d/1cb4M2oa9C6H6I287JSM_oc_s_IP8VzipnTb1TMI8FbY/edit#gid=1885198834).
- [x] `See more` should link users to the external Marketplace with BNPL filter applied (https://woocommerce.com/product-category/woocommerce-extensions/payment-gateways/wallets/?categoryIds=28681&collections=product&page=1)

### Actual behavior

<img width="1161" alt="Screenshot 2022-06-27 at 15 33 24" src="https://user-images.githubusercontent.com/94967682/175968011-1d32336b-1cb3-4a78-8838-2ad3c5b13ff6.png">

1. Page title is wrong
2. Wrong options displayed
3. Link directs users to a wrong place

### Steps to reproduce

1. Onboard to WooCommerce from a WCPay eligible country 
2. Install WCPay
3. Set up WCPay
4. Go to WooCommerce Home

### WordPress Environment

WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by chihsuan** [comment] 2022-07-05 07:29
> The payment options displayed should be aligned with the additional payment options listed [here](https://docs.google.com/spreadsheets/d/1cb4M2oa9C6H6I287JSM_oc_s_IP8VzipnTb1TMI8FbY/edit#gid=1885198834).

Hey @rogermattic, Which country did you choose? I was not able to reproduce this. The following screenshot is what I saw in my local. As you can see, the additional payment list is displayed correctly for the US.

![Image](https://user-images.githubusercontent.com/4344253/177273320-3ecb0828-1985-4cdc-8938-f536552b7e09.png)

**Comment by rogermattic** [comment] 2022-07-05 19:25
@chihsuan thanks for checking this. 
Apologies, but when I try to reproduce this I get the same version as you did. Maybe I was checking this on an outdated version or something.

**Comment by chihsuan** [comment] 2022-07-06 01:57
No worries. 🙂  I'm going to close this. Free feel to reopen it if you encounter the issue again. Thanks!

**Closed as completed by chihsuan** 2022-07-06 01:57 UTC
Labels: Bug, Payments, needs: triage feedback, plugin: woocommerce, Onboarding
