### ISSUE TITLE
Product Collection: attribute filter behaving erraticly

### ISSUE THREAD

**Issue by sunyatasattva** [woothemes/woocommerce#42122] opened 2023-11-07 06:12 UTC
## Describe the bug

Selecting attributes on the Inspector Controls on the Product Collection block sometimes leads to unexpected results.

## To reproduce

1. Add a Product Collection block with the standard test products.
2. Open the Inspector Controls and add an Attributes filter.
3. Click on “Blue”.
4. You should see “Large”, “Medium”, “Small” being added to the input.

## Expected behavior

In this case, “Blue” should be added to the input, as it is for other colors.

## Video

https://github.com/woocommerce/woocommerce-blocks/assets/1847066/6b691f97-3a7c-4646-8a8b-5231bb095a84

**Comment by kmanijak** [comment] 2023-12-28 13:46
I'm not able to reproduce it anymore. @imanish003, do you mind double-checking it before I close it?

**Comment by imanish003** [comment] 2023-12-29 06:55
@kmanijak  I also attempted to replicate this issue but was unable to do so. Consequently, I will proceed to close this issue.

**Closed as completed by imanish003** 2023-12-29 06:55 UTC
Labels: Bug, Kirigami, block: product collection
