### ISSUE TITLE
Error after update to 5.9

### ISSUE THREAD

**Issue by ADIAProject** [woothemes/woocommerce#31124] opened 2021-11-10 15:46 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
2021-11-10T15:31:01+00:00 CRITICAL require(): Failed opening required '/home/***/public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Telemetry/class-wc-rest-telemetry-controller.php' (include_path='.:/opt/remi/php74/root/usr/share/pear:/opt/remi/php74/root/usr/share/php:/usr/share/pear:/usr/share/php') в /home/***/public_html/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-php-autoloader.php на строке 87

**Expected behavior**
Update to 5.9

**Actual behavior**

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
Update to 5.9.
I did not find the error immediately, only the next day. No more updates were made. Jetpack was present on the system at the time of installation, but was turned off because it stopped using. Removing Jetpack didn't help 

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [-] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [-] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>

The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.

the report cannot be generated, this button is missing due to a message about a critical WP error 
</details>

**Comment by ADIAProject** [comment] 2021-11-11 17:23
Reinstall WP and WC solved this problem.

**Comment by tammullen** [comment] 2021-11-11 19:42
Thanks @ADIAProject for raising this and for the update.

Glad to hear a reinstall helped solve it. We have looked into this and couldn't reproduce the error.

It's likely the install process has somehow got corrupted. We haven't had any other reports of this with WC 5.9.0 so hopefully it was just a one off.

I'm going to close this issue for now as it seems to be resolved. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed as completed by tammullen** 2021-11-11 19:42 UTC
Labels: Bug
