### ISSUE TITLE
Variation ''Any colour'' is not working

### ISSUE THREAD

**Issue by Crystella17** [woothemes/woocommerce#31255] opened 2021-11-19 10:28 UTC
Good afternoon, please I need your help with the below.

On the backend, on variations, I put as an attribute a specific size and as second attribute ”Any Door Colour”, on the frontend when I choose a colour and size it doesn’t work. It says ”Door colour is a required field” even when I am choosing the colour.

Please use the link I give you, then choose size and colour and try to add it to cart . Then if you will se your cart you will see it is empty.

thank you in advance.

https://onlineworktops.co.uk/product/luzzi-kitchen-door-copy

**Comment by Crystella17** [comment] 2021-11-19 10:29
![257381855_10220259612655717_6696576378052398689_n](https://user-images.githubusercontent.com/94683596/142607802-d63dec0b-b4a6-42e8-ba79-23ec953dde39.jpg)

**Comment by Crystella17** [comment] 2021-11-19 10:29
![257132037_10220259612855722_157495613980504454_n](https://user-images.githubusercontent.com/94683596/142607825-d5096e43-9702-4942-bbbe-306e31d94cfd.jpg)

**Comment by rodelgc** [comment] 2021-11-22 09:18
Hi @Crystella17,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by rodelgc** 2021-11-22 09:18 UTC
Labels: type: support request
