### ISSUE TITLE
External Affiliate Product button is adding a = at the end of the url

### ISSUE THREAD

**Issue by ianmko** [woothemes/woocommerce#49740] opened 2024-07-21 02:15 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I added a product on WooCommerce core using the External/Affiliate product option from the Product Data drop down menu. The page the product is listed on is: `https://ro-ranch.us/product/cookbook/`

The button titled "Buy on IngramSpark" should take the user to the url for the external product, which is: `https://shop.ingramspark.com/b/084?UMhPtFiQeYLEn6V0thKS1aKKnmkGghh3iTVhVCB3fn8`

However, when the button is clicked on the front end, the actual url the user goes to is: `https://shop.ingramspark.com/b/084?UMhPtFiQeYLEn6V0thKS1aKKnmkGghh3iTVhVCB3fn8=` This url gives a 404 error.

Somehow, a = symbol is being added. Deleting the = from the url takes the user to the correct checkout page. When inspecting the button, there is nothing I see that indicates a = should be added to the url.
![image](https://github.com/user-attachments/assets/dd1a4fc5-e110-4dd1-9f48-dbf9d5cc913e)

### Expected behavior

I expect the button to direct the user to `https://shop.ingramspark.com/b/084?UMhPtFiQeYLEn6V0thKS1aKKnmkGghh3iTVhVCB3fn8`

### Actual behavior

The user is misdirected to `https://shop.ingramspark.com/b/084?UMhPtFiQeYLEn6V0thKS1aKKnmkGghh3iTVhVCB3fn8=`

### Steps to reproduce

1. Go to https://ro-ranch.us/product/cookbook/
2. Click on the button titled "BUY ON INGRAMSPARK"
3. User is directed to https://shop.ingramspark.com/b/084?UMhPtFiQeYLEn6V0thKS1aKKnmkGghh3iTVhVCB3fn8=
4. Delete the = from the end of the url
5. Arrive at the correct url that shows the olive oil cookbook
6. Go back to step 2, right click the button and select the Inspect option from the menu
7. Verify the url the button is linked to https://shop.ingramspark.com/b/084?UMhPtFiQeYLEn6V0thKS1aKKnmkGghh3iTVhVCB3fn8

### WordPress Environment

[SystemStatusReport_ro-ranch.us_2024-07-21T02-12-20.txt](https://github.com/user-attachments/files/16322855/SystemStatusReport_ro-ranch.us_2024-07-21T02-12-20.txt)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by dinhtungdu** [comment] 2024-08-15 06:46
Hi @ianmko,

I tested on a fresh site and I can't reproduce the issue following your steps. I noticed the add-to-cart form on your store has been updated and doesn't have the issue anymore.

Since I can't reproduce the issue on a fresh site, I'm closing this issue. But feel free to continue the discussion.

**Closed as completed by dinhtungdu** 2024-08-15 06:46 UTC
Labels: Bug, type: community contribution, Kirigami
