### ISSUE TITLE
Incorrect product prices 

### ISSUE THREAD

**Issue by ASNUAirCon** [woothemes/woocommerce#31357] opened 2021-12-03 02:12 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I have an issue where I have put the prices I want my products to be sold at on my site with Wordpress/WooCommerce and they have changed the price down. Order number on my ASNU Air-COnditioning Warehouse Site for this bug is 2255 the product is the Mitsubishi Heavy Industries 1.7kw Air Con Unit at $519 on my site but when order 2255 came through it sold the 2 units at $459 which is $120 loss on this product which needs to be sorted out by Wordpress as we have lost money on these items. This has also happened on my Pair Coil prices, Air Conditioning Duct so is a consistent theme of issues on my website. 

**Expected behavior**
A clear and concise description of what you expected to happen. I expect that the shopping cart function does not sell my products below the prices I have put on the website.

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible;  The order came through $120 less than we should have received from the sale of these 2 units.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to '...' asnuairconditioningwarehouse.com
2. Click on '....' Air Con Units 
3. Scroll down to '....' Split Systems 
4. See error Find the Mitsubishi Heavy Industries 1.7kw and add 2 units to the cart and see what price comes up.

**Comment by juliaamosova** [comment] 2021-12-06 22:19
Hi @ASNUAirCon,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by juliaamosova** 2021-12-06 22:19 UTC
Labels: Bug, type: support request
