### ISSUE TITLE
Translation error bug

### ISSUE THREAD

**Issue by rodolphebertozzo** [woothemes/woocommerce#31047] opened 2021-10-28 17:27 UTC
Hello, why this part of Woocommerce is not translated into French?
![trad](https://user-images.githubusercontent.com/56270626/139305369-eaab7b69-f2ad-4b2f-bea9-a6263b97ecb3.PNG)

**Comment by rodelgc** [comment] 2021-10-29 06:26
Hi @rodolphebertozzo,

I believe you're referring to the Login section in the Checkout page? If so, I'm not able to reproduce this issue on my end. When I logged in to WP Admin and navigated to Settings > General and then set the Language Site to "Français", I am able to see the French translation on the login form just fine:
<img width="588" alt="Screen Shot 2021-10-29 at 2 17 18 PM" src="https://user-images.githubusercontent.com/4509348/139386256-f2c59c19-c815-4280-b21d-f3ae1a9daef8.png">
<img width="810" alt="Screen Shot 2021-10-29 at 2 17 41 PM" src="https://user-images.githubusercontent.com/4509348/139386319-02a92a68-3b7c-4572-aee0-afda2f8d901e.png">

I'm closing this issue for now, as it doesn't seem like a bug. Feel free to log another one with clear steps to replicate if you still encounter this issue.

**Closed as completed** 2021-10-29 06:28 UTC
Labels: type: support request

**Comment by rodolphebertozzo** [comment] 2021-10-29 12:50
It looks like this is happening with the new Elementor Pro widgets, available early next week, I will try to open an issue with them
