### ISSUE TITLE
Mini Cart Widget for Elementor no longer working

### ISSUE THREAD

**Issue by rob1998** [woothemes/woocommerce#38735] opened 2023-06-15 08:04 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We're using the menu cart widget in Elementor, which uses WooCommerce's mini cart widget.
When opening the cart, the content is not loaded.
We already tested other versions of Elementor, setting Elementor's Mini Cart Template to both disabled & enabled and testing on other sites we manage.
On all sites the issue was solved by rolling back WooCommerce to 7.7.2 from 7.8.0

### Expected behavior

The DOM content for the cart is loaded

### Actual behavior

The cart widget remains empty, no DOM content is loaded

### Steps to reproduce

1. Install Elementor with Hello Elementor theme and WooCommerce 7.8.0
2. Add some products
3. Add the Menu Cart Widget to a page or header
4. Click the cart button in the frontend (view in editor works)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://chineesrestaurantchi.nl
Site address (URL): https://chineesrestaurantchi.nl
WC Version: 7.7.2
REST API Version: ✔ 7.7.2
WC Blocks Version: ✔ 10.0.6
Action Scheduler Version: ✔ 3.6.0
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: ✔
WP Cron: –
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 768 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.86.0
NSS/3.79

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.28-MariaDB-cll-lve
Max Upload Size: 768 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.0
WC Database Prefix: J9WO64wLl_
Totale database grootte: 125.01MB
Database gegevens grootte: 95.25MB
Database index grootte: 29.76MB
J9WO64wLl_woocommerce_sessions: Data: 2.02MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
J9WO64wLl_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
J9WO64wLl_woocommerce_order_items: Data: 1.52MB + Index: 0.20MB + Engine InnoDB
J9WO64wLl_woocommerce_order_itemmeta: Data: 6.52MB + Index: 6.03MB + Engine InnoDB
J9WO64wLl_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
J9WO64wLl_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
J9WO64wLl_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
J9WO64wLl_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
J9WO64wLl_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_actionscheduler_actions: Data: 1.02MB + Index: 0.42MB + Engine InnoDB
J9WO64wLl_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_actionscheduler_logs: Data: 1.02MB + Index: 0.22MB + Engine InnoDB
J9WO64wLl_aryo_activity_log: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
J9WO64wLl_comments: Data: 1.52MB + Index: 0.77MB + Engine InnoDB
J9WO64wLl_easywpsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_easywpsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
J9WO64wLl_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
J9WO64wLl_e_submissions: Data: 0.05MB + Index: 0.27MB + Engine InnoDB
J9WO64wLl_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
J9WO64wLl_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
J9WO64wLl_jet_post_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_jet_smart_filters_indexer: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_jet_taxonomies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_mailchimp_carts: Data: 0.28MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_mailchimp_jobs: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_mo_campaign_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_mo_campaign_logmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_mo_conversions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_mo_email_campaignmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_mo_email_campaigns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_mo_optin_campaignmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_mo_optin_campaigns: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
J9WO64wLl_options: Data: 6.03MB + Index: 1.16MB + Engine InnoDB
J9WO64wLl_postmeta: Data: 34.52MB + Index: 16.03MB + Engine InnoDB
J9WO64wLl_posts: Data: 9.50MB + Index: 1.02MB + Engine InnoDB
J9WO64wLl_rank_math_analytics_objects: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_rank_math_internal_links: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_redirection_404: Data: 0.19MB + Index: 0.05MB + Engine InnoDB
J9WO64wLl_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
J9WO64wLl_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
J9WO64wLl_redirection_logs: Data: 1.02MB + Index: 0.05MB + Engine InnoDB
J9WO64wLl_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
J9WO64wLl_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
J9WO64wLl_term_relationships: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
J9WO64wLl_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
J9WO64wLl_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
J9WO64wLl_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
J9WO64wLl_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_wc_customer_lookup: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
J9WO64wLl_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
J9WO64wLl_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
J9WO64wLl_wc_order_product_lookup: Data: 1.52MB + Index: 0.63MB + Engine InnoDB
J9WO64wLl_wc_order_stats: Data: 1.52MB + Index: 0.28MB + Engine InnoDB
J9WO64wLl_wc_order_tax_lookup: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
J9WO64wLl_wc_product_attributes_lookup: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
J9WO64wLl_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_wc_product_meta_lookup: Data: 0.13MB + Index: 0.17MB + Engine InnoDB
J9WO64wLl_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
J9WO64wLl_wfconfig: Data: 2.30MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_wffilemods: Data: 12.55MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_wfhits: Data: 1.02MB + Index: 0.05MB + Engine InnoDB
J9WO64wLl_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
J9WO64wLl_wfknownfilelist: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_wflogins: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
J9WO64wLl_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
J9WO64wLl_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
J9WO64wLl_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
J9WO64wLl_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
J9WO64wLl_wfstatus: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
J9WO64wLl_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
J9WO64wLl_wpr_rocket_cache: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
J9WO64wLl_wpr_rucss_used_css: Data: 0.02MB + Index: 0.09MB + Engine InnoDB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 237
elementor_library: 26
elementor_snippet: 1
jet-smart-filters: 1
nav_menu_item: 32
oembed_cache: 3
page: 11
post: 1
product: 189
product_variation: 725
revision: 531
seedprod: 1
shop_order: 3530
viwec_template: 14

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

ManageWP - Worker: door GoDaddy – 4.9.17
Activity Log: door Team activiteiten log – 2.8.6
Classic Editor: door WordPress Contributors – 1.6.3
WooCommerce Delivery & Pickup Date Time Pro: door CodeRockz – 1.4.9
Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd: door SeedProd – 6.15.7
Easy WP SMTP Export Import Settings: door wp.insider – 1.1
Easy WP SMTP: door Easy WP SMTP – 2.1.0
Elementor Pro: door Elementor.com – 3.13.2
Elementor: door Elementor.com – 3.13.4
ElementsKit Lite: door Wpmet – 2.8.8
Flexible Shipping: door Octolize – 4.21.3
GA Google Analytics: door Jeff Starr – 20230306
Google Language Translator: door Translate AI Multilingual Solutions – 6.0.19
Sitemap by BestWebSoft: door BestWebSoft – 3.2.8
JetEngine: door Crocoblock – 3.1.6.1
JetSearch: door Crocoblock – 3.0.3
JetSmartFilters: door Crocoblock – 3.1.2
JetWooBuilder For Elementor: door Crocoblock – 2.1.4
Mailchimp for WooCommerce: door Mailchimp – 2.8.3
MailOptin - Lite: door MailOptin Popup Builder Team – 1.2.59.0
Redirection: door John Godley – 5.3.10
SEO Booster 043WEB: door 043WEB – 1.3
Rank Math SEO: door Rank Math – 1.0.116
WooCommerce Sisow betaalmethoden: door Sisow – 5.5.8
Tijdelijke login zonder wachtwoord: door StoreApps – 1.8.2
WooCommerce: door Automattic – 7.7.2 (update naar versie 7.8.0 is beschikbaar)
Wordfence Security: door Wordfence – 7.9.3
WP Rocket: door WP Media – 3.13.4

### Inactive Plugins (5) ###

Akismet Anti-Spam: door Automattic – 5.1
CoDesigner: door Codexpert – 3.11
Delivery & Pickup Date Time for WooCommerce: door CodeRockz – 1.3.55
Email Template Customizer for WooCommerce: door VillaTheme – 1.1.22
Hello Dolly: door Matt Mullenweg – 1.7.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Must Use Plugins (1) ###

ManageWP - Worker Loader: door GoDaddy – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Winkelbasis: #118 - /bestellen/
Winkelwagen: ❌ Pagina heeft geen [woocommerce_cart] shortcode of het woocommerce/cart blok.
Afrekenen: ❌ Pagina heeft geen [woocommerce_checkout] shortcode of het woocommerce/checkout blok.
Mijn account: ❌ De pagina moet als Openbaar zijn ingesteld
Algemene voorwaarden: ❌ Pagina niet ingesteld

### Theme ###

Name: Hello Elementor
Version: 2.7.1
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een sub thema aan. Zie: Hoe maak je eensub thema

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-06-15 10:49:11 +02:00
Options: ✔
Notes: 138
Onboarding: completed

### Action Scheduler ###

Canceled: 1
Oldest: 2023-06-11 12:55:42 +0200
Newest: 2023-06-11 12:55:42 +0200

Complete: 1.038
Oldest: 2023-05-15 14:51:31 +0200
Newest: 2023-06-15 10:02:45 +0200

Failed: 33
Oldest: 2022-09-15 12:20:03 +0200
Newest: 2023-06-01 03:46:06 +0200

Pending: 2
Oldest: 2023-06-15 10:03:45 +0200
Newest: 2023-06-16 09:47:02 +0200

### Status report information ###

Generated at: 2023-06-15 10:03:09 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by SuperHanss** [comment] 2023-06-15 09:00
I'm guessing this is related to #35530

See [comment](https://github.com/woocommerce/woocommerce/pull/35530#issuecomment-1554497784) for the fix. Elementor will need to include this going forward but can be enqueued manually in the mean time.

**Comment by nerrad** [comment] 2023-06-15 10:54
@rob1998, are you an employee with Elementor? If so, WooCommerce announced this change through the release process as a dev note:

- [WooCommerce 7.8 Beta 1](https://developer.woocommerce.com/2023/05/24/woocommerce-7-8-beta-1-released/)
- [WooCommerce 7.8](https://developer.woocommerce.com/2023/06/13/woocommerce-7-8-released/)

It is definitely preferable that this change is made by plugins/themes relying on the cart-fragments script since that is more in line with the WordPress script dependency system and allows them to have finer control over when the script is actually enqueued. 

We intentionally merged this change because of the performance impact on stores by having the script load everywhere on a WordPress site by default.

We do have a potential fix that is being discussed in #38736 but we might not release it because it potentially wouldn't resolve all cases.

**Comment by rob1998** [comment] 2023-06-15 11:48
Thanks for the info! I looked through all the changes and did find this change, but didn't know that Elementor had to make a change because of it.
Unfortunately, I am not an employee for Elementor and also do not have a great support history with them when it comes to fixing bugs... Let's hope for the best 🤞 In the meantime, I will look at implementing the fix temporary.

**Comment by 319heads** [comment] 2023-06-15 17:28
This issue looks to occur with any theme except Storefront. Hello, Twenty Twenty-Two, Twenty Twenty-One, etc... all have blank empty mini-carts.

Have to rollback from Woocommerce 7.8.0 to 7.7.2 or switch to Storefront theme.

**Comment by nerrad** [comment] 2023-06-15 18:29
> This issue looks to occur with any theme except Storefront. Hello, Twenty Twenty-Two, Twenty Twenty-One, etc... all have blank empty mini-carts.

Hey @319heads, could you clarify what mini-carts are being added to those themes and how you reproduce? Are you referring to using the Elementor mini-cart with those themes?

**Comment by ppwebox** [comment] 2023-06-18 12:13
I'm using the Elementor mini-cart widget in the header and suddenly have this Woo bug with a blank page in the cart sidebar.  

On the local dev site, Elementor Pro and Woo are at their latest version. On the live site, Woo is also at the latest version (7.8.0) but EM is quite old (3.7.7 vs 3.13.1). So Woocommerce must be the culprit.

Tried all suggestions found when googling Woo mini cart problem, including deactivating all other plugins and changing the theme, but nothing has fixed this critical usability bug. But even downgrading Woo to version 7.0.0, clearing cache and repairing/updating the database has been futile. 

It's great that Woo is finally addressing the performance issues caused by their cart fragments approach, but not like this in breaking e-commerce functionality of live sites!

**Comment by vandevo** [comment] 2023-06-19 11:38
Hello, I already updated the new release from Elementor Fix: Mini cart template appears as empty in various scenarios in Menu Cart widget ([#22789](https://github.com/elementor/elementor/issues/22789))

But the issue still has not been fixed. What should I do?

**Comment by nicholaszein** [comment] 2023-06-19 13:51
Hello, this is Nick from Elementor!

We have released a fix for this issue with the latest release **v3.14.0** for both Elementor and Elementor Pro.

You can find out more about it [here](https://github.com/elementor/elementor/issues/22789#issuecomment-1597226893).

We want to extend our gratitude to our WooCommerce partners for helping us troubleshoot this issue!

Kind regards 🙏

**Comment by nerrad** [comment] 2023-06-19 17:50
Thanks for the update @nicholaszein! Since this has been resolved by Elementor on their end, I'm going to go ahead and close this issue.

**Closed as completed by nerrad** 2023-06-19 17:50 UTC
Labels: Bug, type: community contribution

**Comment by xue28** [comment] 2023-06-24 17:04
6408735-zen
