### ISSUE TITLE
Enable navigation setting: fix Tracks event

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#33145] opened 2022-05-20 14:42 UTC
**Description:** the Tracks event introduced when the user enables/disables the navigation (
WooCommerce - Settings - Advanced - Features) is broken. This event should be fixed in order to understand how many users are enabling or disabling the navigation. And the same should be applied to the analytics feature.

**Acceptance criteria:**
- [ ] Fire `wcadmin_settings_change` (settings: woocommerce_navigation_enabled) when the user enables the navigation
- [ ] Fire `wcadmin_settings_change` (settings: woocommerce_navigation_disabled) when the user disables the navigation
- [ ] Fire `wcadmin_settings_change` (settings: woocommerce_analytics_enabled) when the user enables analytics
- [ ] Fire `wcadmin_settings_change` (settings: woocommerce_analytics_disabled) when the user disables analytics

**Comment by mattsherman** [comment] 2022-05-24 21:09
Closing this as a duplicate of the pre-existing #33128 (I've updated that issue to include the more detailed acceptance criteria from here).

**Closed as completed by mattsherman** 2022-05-24 21:09 UTC
Labels: Settings
