### ISSUE TITLE
Spec is invalid because a rule is invalid in feed

### ISSUE THREAD

**Issue by erikdemarco** [woothemes/woocommerce#34777] opened 2022-09-22 10:05 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Following error in Woocommerce Status Log/s.

The error because 'wcadmin_active_for' rule doesnt have 'days' key. so the validation fail. see this lines:

https://github.com/woocommerce/woocommerce/blob/c4628b966be16218a99d093cf3672ad79a4f235e/plugins/woocommerce/src/Admin/RemoteInboxNotifications/DataSourcePoller.php#L144

https://github.com/woocommerce/woocommerce/blob/c4628b966be16218a99d093cf3672ad79a4f235e/plugins/woocommerce/src/Admin/RemoteInboxNotifications/WCAdminActiveForRuleProcessor.php#L54

```
httpswoocommerce.comwp-jsonwccominbox-notifications1.0notifications.json-2022-09-13-a81dc66affef0c40c08187abdd1f0e31.log (13/09/2022 at 5:37 pm NZST) View
2022-09-13T05:37:48+00:00 ERROR Spec is invalid because a rule is invalid in feed
2022-09-13T05:37:48+00:00 ERROR stdClass Object
(
    [type] => wcadmin_active_for
    [operation] => >
    [months] => 11
)

2022-09-13T05:37:48+00:00 ERROR stdClass Object
(
    [slug] => googlelistings_signals2022_hasGLA
    [type] => marketing
    [status] => unactioned
    [is_snoozable] => 0
    [source] => woocommerce.com
    [locales] => Array
        (
            [0] => stdClass Object
                (
                    [locale] => en_US
                    [title] => Show off your products with Ads on Google
                    [content] => You’re ready to grow with ads. Google optimizes for performance across your products; you only pay for results. If you’re new to Google, you can earn up to $500 in ad credits (T&Cs apply). <a href="https://woocommerce.com/my-account/create-a-ticket/">Contact support</a> if you need guidance with Google Listings & Ads.
                )

        )

    [actions] => Array
        (
            [0] => stdClass Object
                (
                    [name] => googlelistings_signals2022_hasGLA_click
                    [locales] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [locale] => en_US
                                    [label] => Connect Google Listings & Ads
                                )

                        )

                    [url] => admin.php?page=wc-admin&path=marketing
                    [url_is_admin_query] => 1
                    [is_primary] => 1
                    [status] => unactioned
                )

        )

    [rules] => Array
        (
            [0] => stdClass Object
                (
                    [type] => publish_after_time
                    [publish_after] => 2022-09-12 07:23:39
                )

            [1] => stdClass Object
                (
                    [type] => publish_before_time
                    [publish_before] => 2022-10-12 23:59:00
                )

            [2] => stdClass Object
                (
                    [type] => plugins_activated
                    [plugins] => Array
                        (
                            [0] => google-listings-and-ads
                        )

                )

            [3] => stdClass Object
                (
                    [type] => wcadmin_active_for
                    [operation] => >
                    [months] => 11
                )

            [4] => stdClass Object
                (
                    [type] => product_count
                    [operation] => >
                    [value] => 76
                )

            [5] => stdClass Object
                (
                    [type] => order_count
                    [operation] => >
                    [value] => 38
                )

            [6] => stdClass Object
                (
                    [type] => total_payments_value
                    [days] => last_year
                    [value] => 3700
                    [operation] => >
                )

        )

)

2022-09-13T05:37:48+00:00 ERROR Spec is invalid because a rule is invalid in feed
2022-09-13T05:37:48+00:00 ERROR stdClass Object
(
    [type] => wcadmin_active_for
    [operation] => >
    [months] => 11
)

2022-09-13T05:37:48+00:00 ERROR stdClass Object
(
    [slug] => googlelistings_signals2022_noGLA
    [type] => marketing
    [status] => unactioned
    [is_snoozable] => 0
    [source] => woocommerce.com
    [locales] => Array
        (
            [0] => stdClass Object
                (
                    [locale] => en_US
                    [title] => Show off your products with Ads on Google
                    [content] => You’re ready to grow with ads. Google optimizes for performance across your products; you only pay for results. If you’re new to Google, you can earn up to $500 in ad credits (T&Cs apply). <a href="https://woocommerce.com/my-account/create-a-ticket/">Contact support</a> if you need guidance with Google Listings & Ads.
                )

        )

    [actions] => Array
        (
            [0] => stdClass Object
                (
                    [name] => googlelistings_signals2022_noGLA
                    [locales] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [locale] => en_US
                                    [label] => Connect Google Listings & Ads
                                )

                        )

                    [url] => https://woocommerce.com/products/google-listings-and-ads/?utm_medium=product&utm_source=inbox_note&utm_campaign=googlelistings_signals2022_noGLA
                    [url_is_admin_query] => 
                    [is_primary] => 1
                    [status] => unactioned
                )

        )

    [rules] => Array
        (
            [0] => stdClass Object
                (
                    [type] => publish_after_time
                    [publish_after] => 2022-09-12 07:27:46
                )

            [1] => stdClass Object
                (
                    [type] => publish_before_time
                    [publish_before] => 2022-10-12 23:59:00
                )

            [2] => stdClass Object
                (
                    [type] => not
                    [operand] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [type] => plugins_activated
                                    [plugins] => Array
                                        (
                                            [0] => google-listings-and-ads
                                        )

                                )

                        )

                )

            [3] => stdClass Object
                (
                    [type] => wcadmin_active_for
                    [operation] => >
                    [months] => 11
                )

            [4] => stdClass Object
                (
                    [type] => product_count
                    [operation] => >
                    [value] => 76
                )

            [5] => stdClass Object
                (
                    [type] => order_count
                    [operation] => >
                    [value] => 38
                )

            [6] => stdClass Object
                (
                    [type] => total_payments_value
                    [days] => last_year
                    [value] => 3700
                    [operation] => >
                )

        )

)
```

### Expected behavior

no error

### Actual behavior

error

### Steps to reproduce

-

### WordPress Environment ###

WordPress address (URL): https://storeonline.link
Site address (URL): https://storeonline.link
WC Version: 6.9.2
REST API Version: ✔ 6.9.2
WC Blocks Version: ✔ 8.3.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.30
PHP Post Max Size: 1 GB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.71.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.7.39
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.2
WC Database Prefix: yts_
Total Database Size: 26.01MB
Database Data Size: 17.25MB
Database Index Size: 8.76MB
yts_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yts_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yts_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yts_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
yts_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yts_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yts_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
yts_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yts_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yts_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yts_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yts_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yts_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yts_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yts_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
yts_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yts_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yts_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yts_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yts_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
yts_ff_scheduled_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yts_fluentform_entry_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yts_fluentform_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yts_fluentform_form_analytics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yts_fluentform_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yts_fluentform_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yts_fluentform_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yts_fluentform_submission_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yts_fsmpt_email_logs: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
yts_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yts_options: Data: 3.27MB + Index: 0.23MB + Engine InnoDB
yts_postmeta: Data: 7.52MB + Index: 4.03MB + Engine InnoDB
yts_posts: Data: 1.52MB + Index: 0.55MB + Engine InnoDB
yts_signups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yts_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yts_termmeta: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
yts_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
yts_term_relationships: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
yts_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
yts_tm_taskmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
yts_tm_tasks: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
yts_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
yts_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
yts_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
yts_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yts_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yts_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yts_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yts_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yts_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
yts_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
yts_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yts_wc_product_attributes_lookup: Data: 0.20MB + Index: 0.16MB + Engine InnoDB
yts_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yts_wc_product_meta_lookup: Data: 0.25MB + Index: 0.33MB + Engine InnoDB
yts_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yts_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yts_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yts_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yts_yoast_indexable: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
yts_yoast_indexable_hierarchy: Data: 0.25MB + Index: 0.34MB + Engine InnoDB
yts_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yts_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yts_yoast_seo_links: Data: 0.23MB + Index: 0.14MB + Engine InnoDB

### Post Type Counts ###

attachment: 848
custom_css: 1
customize_changeset: 43
easyimageslider: 1
nav_menu_item: 177
page: 29
post: 1
product: 94
product_variation: 1862
ris_gallery: 5
soliloquy: 2
wmpc-trash: 386
wp_global_styles: 5
wpcode: 9

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

Advanced Database Cleaner PRO: by Younes JFR. – 3.2.1
Block Visibility: by Nick Diego – 2.4.3
FluentSMTP: by FluentSMTP & WPManageNinja Team – 2.2.0
Fluent Forms: by Contact Form - WPManageNinja LLC – 4.3.12
Heartbeat Control by WP Rocket: by WP Rocket – 2.0
WPCode - Insert Headers, Footers, and Code Snippets: by WPCode – 2.0.2
Max Mega Menu: by megamenu.com – 2.9.8
Printful Integration for WooCommerce: by Printful – 2.1.34
Product Category Tree: by AWESOME TOGI – 2.5
Profile Builder: by Cozmoslabs – 3.7.9
PW WooCommerce Bulk Edit Pro: by Pimwick
LLC – 2.335

WOOCS - WooCommerce Currency Switcher: by realmag777 – 2.3.8
WooCommerce Menu Cart: by WP Overnight – 2.12.0
WooCommerce PayPal Payments: by WooCommerce – 1.9.3
WooCommerce Product Variations Swatches Premium: by VillaTheme – 1.0.11.1
WooCommerce: by Automattic – 6.9.2
Yoast SEO: by Team Yoast – 19.6.1
WP Crontrol: by John Blackbourn & crontributors – 1.14.0
WP-DBManager: by Lester 'GaMerZ' Chan – 2.80.8
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.7

### Inactive Plugins (1) ###

Imsanity: by Exactly WWW – 2.8.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: NZD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #7245 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Astra
Version: 3.9.2
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Pimwick Plugins ###

PW WooCommerce Bulk Edit Pro: License key: PW-62d9dbb8e6cab
Result: success
Cached: 2022-09-19

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: NZ
WooCommerce currency supported: ✔
PayPal card processing available in country: –
Pay Later messaging available in country: –
Webhook status: –
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-09-20 04:16:56 +12:00
Options: ✔
Notes: 49
Onboarding: completed

### Action Scheduler ###

Complete: 13
Oldest: 2022-09-19 10:42:23 +1200
Newest: 2022-09-19 16:16:50 +1200

Pending: 1
Oldest: 2022-09-20 10:42:23 +1200
Newest: 2022-09-20 10:42:23 +1200

### Status report information ###

Generated at: 2022-09-20 06:32:23 +12:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mattsherman** [comment] 2022-09-22 21:29
@erikdemarco Thanks for reporting this issue. I have reproduced the issue and determined the root cause of it. This is due to a misconfiguration of the remote inbox notifications feed that is sent to WooCommerce installations. It will be updated soon and once it is updated stores will get the updated version within a day or so. At that point, the error will no longer appear in the logs.

**Comment by mattsherman** [comment] 2022-09-22 22:49
I have verified that the updates to the remote inbox notifications feed have been made and are delivered to new stores. Existing stores will receive the updated feed within a day or so (a store checks every 24 hours for an updated feed).

I'm closing this issue now that the issue is resolved.

**Closed as completed by mattsherman** 2022-09-22 22:49 UTC
Labels: Bug, Wayfinding
