### ISSUE TITLE
[Enhancement]: Incorrect woocommerce notices message when updating cart quantity to zero

### ISSUE THREAD

**Issue by bonniec0** [woothemes/woocommerce#37618] opened 2023-04-07 13:22 UTC
### Describe the solution you'd like

When an item is removed from the cart using the remove  ("x") anchor, a woocommerce notices message appears stating that "[product name] removed. Undo?" This is very useful as it allows the user to re add the item to the cart if a mistake was made. 

However, when the cart quantity is changed to zero using the quantity input field, and the update cart button is pressed, while the expected behaviour occurs and the product is removed from the cart, the woocommerce notice simply states "Cart updated". This is the same behaviour as changing the quantity to any other number.

I believe that it would be much more useful to the user to display the ‘product removed’ message & associated undo button in the case of updating the quantity to 0, rather than simply the 'updated cart' notice.

**Comment by jorgeatorres** [comment] 2023-04-28 20:04
Hi @bonniec0!

Thanks for reaching out! After some discussion, we believe this is working as intended. Removing an item by updating the cart involves various steps so it is more intentional than, as you said, clicking the `[x]`.
Also, several items can be updated/removed when updating the cart, and we probably don't want to display various notices and/or a list of all altered products with the choice to undo the action.

I'm going to close this for now, but feel free to re-open if I've misinterpreted something or if you think there's workflow that is impacted by the current implementation.

Thanks again.

**Closed as completed by jorgeatorres** 2023-04-28 20:04 UTC
Labels: Enhancement, Cart, needs: developer feedback, plugin: woocommerce, type: community contribution
