### ISSUE TITLE
[Launch Your Store] Add visual indicator to admin bar

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#45112] opened 2024-02-26 07:07 UTC
### Issue description

We’ll go with the Woo Home badge only for the MVP, and we’ll pivot this later in case it’s needed.

**Comment by adrianduffell** [comment] 2024-03-24 23:44
Duplicate of https://github.com/woocommerce/woocommerce/issues/45111

**Closed as completed by adrianduffell** 2024-03-24 23:44 UTC
Labels: status: on hold, Wayfinding
