### ISSUE TITLE
Currency symbol of Kyrgyzstani Som

### ISSUE THREAD

**Issue by canybec** [woothemes/woocommerce#11928] opened 2016-09-15 06:49 UTC
## EXPLANATION OF THE ISSUE
Improper Currency Signage for Kyrgyzstani Som. Currently Kyrgyzstani Som is displayed as "лв" which is incorrect. Proper ISO 4217 Code for Kyrgyzstani Som is "KGS"

## STEPS TO REPRODUCE THE ISSUE

Go to the settings and Select Currency for Kyrgyzstani Som

**Comment by claudiosmweb** [comment] 2016-09-15 08:53
Please don't use UperCase and "URGENT", is not even polite. It's like you are screaming in fury...

Well I pick this symbol from: http://www.xe.com/currency/kgs-kyrgyzstani-som

**Comment by claudiosmweb** [comment] 2016-09-15 08:54
> Proper ISO 4217 Code for Kyrgyzstani Som is "KGS"

I agree the CODE is "KGS", but checking http://www.xe.com/currency/kgs-kyrgyzstani-som shows that the symbol is "лв".
So we are using the correct symbol and code.

**Comment by canybec** [comment] 2016-09-20 19:43
no one in Kyrgyzstan knows what "лв" symbol means. I think your reference website has mistake.

**Comment by hemnathmouli** [comment] 2016-09-20 22:07
@canybec This is the currency symbol for Kyrgyzstani Som - http://www.flaticon.com/free-icon/kyrgyzstan-som-currency-symbol_38263

**Comment by claudiosmweb** [comment] 2016-09-21 01:26
@hemnathmouli so `лв` it's really the correct one?
At least for me render both equal.

**Comment by opportus** [comment] 2016-09-21 09:12
@claudiosmweb 

I'd rather trust Wikipedia instead: https://en.wikipedia.org/wiki/Kyrgyzstani_som
They never speak about лв but KGB...

Sites like  www.flaticon.com might be inclined to pick up wrong reference from www.xe.com also...

**Comment by opportus** [comment] 2016-09-21 10:37
@claudiosmweb 

It might worth having a look at: https://en.wikipedia.org/wiki/Currency_symbol
Wikipedia claims Kyrgystan money symbol to be **COM** which can be translated SOM.

Furthermore we don't see any лв on the Kyrgyzstan bank notes but COM: http://www.banknotes.com/kg21.htm

"лв" stands for latin initials "LV". I don't see any logic in symbolizing this money with these initials...
Sites like www.flaticon.com might be inclined to pich up wrong references from www.xe.com
@canybec seems to know what he speaks about, maybe he's from Kyrgyzstan ?

Just my 2p...

**Comment by claudiosmweb** [comment] 2016-09-21 15:59
@opportus 

> It might be worth having a look at https://en.wikipedia.org/wiki/Currency_symbol...
Wikipedia claims Kyrgyzstan currency symbol to be сом which can be translated SOM.

Wikipedia usually tends to be the wrong place for this type of information, since it may not always be reliable.

> Furthermore, we don't see any лв symbol on the Kyrgyzstan bank notes but сом: https://en.wikipedia.org/wiki/Kyrgyzstani_som#/media/File:100_som_1994_ob.jpg

Not an currencies have symbols in the bank notes.
And this information is not the same from what @canybec is talking about.

> Sites like www.flaticon.com might also be inclined to pick up wrong references from www.xe.com.

Well, this don't really proves anything.

But the problem is, each one is saying something different.
That's why I prefer to wait for more feedback in this one.

**Comment by opportus** [comment] 2016-09-21 16:59
@claudiosmweb 

> > Furthermore, we don't see any лв symbol on the Kyrgyzstan bank notes but сом: https://en.wikipedia.org/wiki/Kyrgyzstani_som#/media/File:100_som_1994_ob.jpg

> Not an currencies have symbols in the bank notes.

True, I've confused myself...

> > Sites like www.flaticon.com might also be inclined to pick up wrong references from www.xe.com.

> Well, this don't really proves anything.

I didn't mean to prove anything with my intervention, just to point out that there **might** be something wrong with xe.com...

**Comment by claudiosmweb** [comment] 2016-09-21 17:55
@opportus 

> I didn't mean to prove anything with my intervention, just to point out that there might be something wrong with xe.com...

The same way that might be something wrong with Wipikedia too.

I'm trying to check in other places.

**Comment by opportus** [comment] 2016-09-21 18:00
@claudiosmweb 

> > It might be worth having a look at https://en.wikipedia.org/wiki/Currency_symbol...
Wikipedia claims Kyrgyzstan currency symbol to be сом which can be translated SOM.

> Wikipedia usually tends to be the wrong place for this type of information, since it may not always be reliable.

About symbol currency I'd rather trust Wikipedia... I spend 6 months on 12 in Russia, the official ruble symbol is **₽** like Wikipedia says: https://en.wikipedia.org/wiki/Currency_symbol
Meanwhile, xe.com is not updated: http://www.xe.com/currency/rub-russian-ruble

I'd also trust local Wikipedia contributor: https://ky.wikipedia.org/wiki/%D0%9A%D1%8B%D1%80%D0%B3%D1%8B%D0%B7_%D1%81%D0%BE%D0%BC%D1%83

Символдор = Symbol = сом

**Comment by claudiosmweb** [comment] 2016-09-21 18:02
@opportus I still don't trust in anyone, I'm looking in http://www.nbkr.kg/index.jsp?lang=ENG

**Comment by claudiosmweb** [comment] 2016-09-21 18:18
@opportus now I found prove that is really `сом`.

Closing in favor of #11957

**Closed by claudiosmweb** 2016-09-21 18:18 UTC

**Comment by schrmh** [comment] 2022-03-08 18:10
Just to add some updated info on this: 
The new currency sign is ⃀ (U+20C0) since 2017 but good luck finding a font that supports that since the unicode symbol was introduced in Unicode 14.0 which was released in September and isn't supported on most systems yet anyways.
