### ISSUE TITLE
WordPress 6.6 regression - settings button in New Product Editor Description section is not appearing for smaller mobile resolutions

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#49697] opened 2024-07-18 22:33 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Using 9.1.2 or trunk:
Enable the new product editor at /wp-admin/admin.php?page=wc-settings&tab=advanced&section=features
Go to Products > Add
Simulate a mobile device in portrait mode through developer tools
Go to Description and press "Full editor"
Settings button does not appear in certain mobile resolutions

### Expected behavior

Settings button should display and be functional in all resolutions

### Actual behavior

Settings button does not appear in these mobile resolutions:
![image](https://github.com/user-attachments/assets/8ec7e307-407a-4a02-a587-9a0d47ae2352)

regular non mobile resolution:
![image](https://github.com/user-attachments/assets/fb1c03d2-a2f3-4409-94a9-cb69d503621d)

Ipad larger resolution looks good:
![image](https://github.com/user-attachments/assets/e549062c-9aca-4fe9-949c-9d6a4867bc02)

Iphone and other smaller resolutions as listed in bug description do not show settings:

![image](https://github.com/user-attachments/assets/cb9696a5-b86d-4c1a-8ebd-db9f0397d32a)

### Steps to reproduce

See bug description...

added info:
The rest of the mobile devices with higher resolution seem to display fine

the lower resolutions with WP6.5.5 look good:
![image](https://github.com/user-attachments/assets/9c613681-0ca7-4d20-ba66-89d921ea54e6)

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.1.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.6
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 10.6.18-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 2
page: 7
post: 3
product: 5
product_variation: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Code Snippets: by Code Snippets Pro – 3.6.5.1
Jetpack: by Automattic – 13.7-a.3
WooCommerce: by Automattic – 9.1.2
WP Downgrade | Specific Core Version: by Reisetiger – 1.2.6

### Inactive Plugins (0) ###


### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 19 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-19 13:54:42 +00:00
Options: ✔
Notes: 58
Onboarding: -

### Action Scheduler ###

Complete: 11
Oldest: 2024-07-18 13:56:47 +0000
Newest: 2024-07-18 22:29:00 +0000

Failed: 1
Oldest: 2024-07-18 13:57:55 +0000
Newest: 2024-07-18 13:57:55 +0000

Pending: 1
Oldest: 2024-07-19 13:56:47 +0000
Newest: 2024-07-19 13:56:47 +0000


### Status report information ###

Generated at: 2024-07-18 22:31:28 +00:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by gigitux** [comment] 2024-08-06 10:51
@louwie17 is this a duplicate of https://github.com/woocommerce/woocommerce/issues/50058?

**Comment by louwie17** [comment] 2024-08-06 12:49
> @louwie17 is this a duplicate of #50058?

No it is a different issue.
Although I actually couldn't reproduce it with Gutenberg Trunk, so maybe this will get fixed by GB

**Closed as completed** 2024-08-08 17:41 UTC
Labels: Bug, Kirigami
