### ISSUE TITLE
[GlobalStep] [WP 6.1.1] Blank page is display after navigating to "Page > Add new" and "Post > Add new" page.

### ISSUE THREAD

**Issue by gglobalstep** [woothemes/woocommerce#37953] opened 2023-04-24 14:20 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

For WP 6.1.1, Blank page is display after navigating to "Page > Add new" and "Post > Add new" page.

### Expected behavior

For WP 6.1.1, All content should be display after navigating to "Page > Add new" and "Post > Add new" page.

### Actual behavior

For WP 6.1.1, Blank page is display after navigating to "Page > Add new" and "Post > Add new" page.

### Steps to reproduce

1. Create any test site.
2. Install and activate all the required plugins.
3. Install and activate Woocommerce.
4. Complete OBW.
5. Go to o "Page > Add new" page or "Post > Add new" page.
6. Observe that For WP 6.1.1, Blank page is display after navigating to "Page > Add new" and "Post > Add new" page.

### Screencast:
https://user-images.githubusercontent.com/41110392/234025643-5630c0c7-506a-4663-bcfc-bf7addeadfee.mp4

![#37953(2)](https://user-images.githubusercontent.com/41110392/234025631-d5795094-7168-4fc2-b2d7-ef79e9356c0b.jpg)

### WordPress Environment

Woocommerce Version: WooCommerce  7.7.0-beta.1
WordPress version: 6.1.1

PC:
Windows 10
Chrome(Version 112.0.5615.138)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

<details>
`
### WordPress Environment ###
WC Version: 7.7.0
REST API Version: ✔ 7.7.0
WC Blocks Version: ✔ 10.0.1
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: ❌ 6.1.1 - There is a newer version of WordPress available (6.2)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.56 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.7.0
WC Database Prefix: wp_
Total Database Size: 6.08MB
Database Data Size: 4.55MB
Database Index Size: 1.53MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.47MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 20
post: 7
product: 22
product_variation: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 3.12.1
Code Snippets: by Code Snippets Pro – 3.3.0
Companion Plugin: by Osk – 1.29
WooCommerce Payments: by Automattic – 5.7.0
WooCommerce: by Automattic – 7.7.0-beta.1
WP Downgrade | Specific Core Version: by Reisetiger – 1.2.5

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 5.1
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 12.0

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #10 - /shop/
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My account: #13 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://present-catshark.jurassic.ninja
Subscriptions-core Library Version: 5.5.0
Subscription Statuses: –
WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-25 11:47:17 +00:00
Options: ✔
Notes: 56
Onboarding: completed

### WooCommerce Payments ###

Version: 5.7.0
Connected to WPCOM: Yes
Blog ID: 218225676
Account ID: acct_1N0NuaCO23JZRMd2

### Action Scheduler ###

Complete: 32
Oldest: 2023-04-24 11:48:21 +0000
Newest: 2023-04-24 11:55:07 +0000

Failed: 1
Oldest: 2023-04-24 11:55:07 +0000
Newest: 2023-04-24 11:55:07 +0000

Pending: 1
Oldest: 2023-04-25 11:48:21 +0000
Newest: 2023-04-25 11:48:21 +0000

### Status report information ###

Generated at: 2023-04-24 14:25:47 +00:00
`

</details>

**Comment by lanej0** [comment] 2023-04-25 09:18
Noting that the issue is also present with WordPress 6.0.3 (L-2) but is not present with WordPress 6.2.

**Comment by rrennick** [comment] 2023-05-19 16:40
@gglobalstep Could you confirm that this issue is resolved for you with WordPress 6.2 and WooCommerce 7.7.0?

**Comment by lanej0** [comment] 2023-05-19 20:19
This issue was resolved by a subsequent Blocks release (as of 7.7 Beta 2): https://github.com/woocommerce/woocommerce-blocks/pull/9090

**Closed as completed by lanej0** 2023-05-19 20:19 UTC
Labels: Bug, Store Frontend, plugin: woocommerce, type: community contribution
