### ISSUE TITLE
Variable product cannot be added to cart unless user is logged in

### ISSUE THREAD

**Issue by ejgoodlocal** [woothemes/woocommerce#30507] opened 2021-08-16 14:14 UTC
Actual

- user cannot add a variable product to cart unless the user has logged in

Expected

- non logged in users should be able to add variable product to cart

Steps to reproduce

1. go to variable product page. make sure you are not logged in.
2. try to add the product to cart. it will not add it

notes
- you may try to reproduce it here https://goodlocal.ca/product/custom-engraved-brumate-hopsulator-trio-3-in-1-carrara-marble-insulated-stainless-for-wine-beer-cocktails/

![image](https://user-images.githubusercontent.com/77361197/129577587-41f6af89-8e9c-4034-b216-ce953cae31a9.png)

**Comment by tammullen** [comment] 2021-08-19 11:35
Hi @ejgoodlocal 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by tammullen** 2021-08-19 11:35 UTC
Labels: type: support request
