### ISSUE TITLE
Price Filter Widget

### ISSUE THREAD

**Issue by bitmakers** [woothemes/woocommerce#35663] opened 2022-11-21 22:44 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The Price Filter widget doesn’t work anymore if the Shop is displayed on the Homepage, this was working in the previous version (7.0.1).

### Expected behavior

Shop catalog should display products withing the selected range.

### Actual behavior

Redirected to the default Posts page (this only happens when using the Price Filter from the Homepage).

### Steps to reproduce

1. Set the default WooCommerce shop page as the WordPress Homepage via "Settings > Reading".
2. Add the Price Filter widget via "Appearance > Widgets" (if not already added).
3. Try using the Price Filter from the Home/Shop page.

### WordPress Environment

WordPress v6.1.1
WooCommerce v7.1.0
Theme: Storefront v4.2.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment] 2022-11-23 13:03
Hi @bitmakers,
Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the  WooCommerce 7.1.0 version and WordPress 6.1.1 version. 

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/203491228-6551cc7d-af7d-477f-a26d-e6f79093e346.mp4


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by bitmakers** [comment] 2022-12-14 15:25
After today's update (7.2.0) this is now also happening with the "Filter Products by Attribute" widget - please fix this ASAP, it breaks a ton of sites.

**Comment by jorgeatorres** [comment] 2022-12-28 23:24
Hi @bitmakers,

I'm marking this as a duplicate of #35983, as it's the result of the same issue.
We're already working on a fix, and will be updating the other issue shortly.

Thanks again for the report!

**Closed as not planned by jorgeatorres** 2022-12-28 23:24 UTC
Labels: Bug, plugin: woocommerce, type: community contribution

**Comment by bitmakers** [comment] 2023-01-02 15:10
Hi @jorgeatorres - sure, thanks for the update.
