### ISSUE TITLE
Product page not visible to not logged in users on WooCommerce v8.6.0

### ISSUE THREAD

**Issue by rakshitwesley** [woothemes/woocommerce#44798] opened 2024-02-20 12:00 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The product details are missing when a non-logged-in user opens a product page. Only the title appears.
![v6hLJN.png](https://github.com/woocommerce/woocommerce/assets/95758851/47b7040b-2ec9-4826-833e-323a67fbd511)

### Expected behavior

Product details including image, price, description, add to cart etc should appear for all site visitors, regardless they're logged in or not.

### Actual behavior

Product details including image, price, description, add to cart etc is missing for the site visitors who are not logged in.

### Steps to reproduce

1. Create a product and make it public.
2. Add one of these classic themes (Colinear, Ixion) (Note: The issue is not reproducible with all the themes. It works with Storefront theme)
3. Visit the product page on a private/incognito window without logging-in to the site.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://woorotation.wpcomstaging.com
Site address (URL): https://woorotation.wpcomstaging.com
WC Version: 8.6.0
REST API Version: ✔ 8.6.0
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.27
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.4.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.15-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.0
WC Database Prefix: wp_
Total Database Size: 22.31MB
Database Data Size: 12.74MB
Database Index Size: 9.57MB
wp_woocommerce_sessions: Data: 0.31MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
vp_backup_wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_options: Data: 0.19MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_actionscheduler_actions: Data: 3.16MB + Index: 2.52MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.33MB + Index: 1.77MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.08MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.38MB + Index: 0.23MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.08MB + Index: 0.14MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_xyz_ips_short_code: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_options: Data: 0.38MB + Index: 0.06MB + Engine InnoDB
__wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
__wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
__wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 29
aw_workflow: 5
bookable_resource: 4
mailpoet_page: 1
page: 12
post: 2
product: 40
product_variation: 32
revision: 8
shop_coupon: 4
shop_order_placehold: 33
wpcode: 3
wp_global_styles: 2
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.7.14
AutomateWoo: by WooCommerce – 6.0.13
Bookings Helper: by WooCommerce – 1.0.7
Crowdsignal Forms: by Automattic – 1.7.0
YayPricing Pro - WooCommerce Dynamic Pricing And Discounts: by YayCommerce – 2.5.0
Estimated Delivery Date for WooCommerce: by Plugify – 2.0.7
WordPress.com Editing Toolkit: by Automattic – 4.13440
Google Listings and Ads: by WooCommerce – 2.5.17
Gutenberg: by Gutenberg Team – 17.7.0
hCaptcha for WordPress: by hCaptcha – 3.9.0
WPCode Lite: by WPCode – 2.1.8
Jetpack: by Automattic – 13.2-a.7
Layout Grid: by Automattic – 1.8.4
MailPoet Premium: by MailPoet – 4.42.0
MailPoet: by MailPoet – 4.43.1
Page Optimize: by Automattic – 0.5.5
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.1.1

Price By Country: by HighAddons – 1.0.6
Product Bundles - Bulk Discounts: by SomewhereWarm – 1.4.0
WooCommerce Bookings: by WooCommerce – 2.0.8
WooCommerce Box Office: by WooCommerce – 1.2.3
WooCommerce GoCardless Gateway: by WooCommerce – 2.6.1
Braintree for WooCommerce Payment Gateway: by WooCommerce – 3.1.3
WooCommerce Stripe Gateway: by WooCommerce – 7.9.3
WooCommerce Payments Dev Tools: by Automattic –
WooPayments: by Automattic – 7.2.0
WooCommerce PayPal Payments: by WooCommerce – 2.5.3
Woo Product Add-ons: by Woo – 6.6.0
Woo Product Bundles: by Woo – 6.22.6
WooCommerce Product Vendors: by WooCommerce – 2.2.5
WooCommerce USPS Shipping: by WooCommerce – 4.7.6
WooCommerce Square: by WooCommerce – 4.5.0
WooCommerce Subscription Downloads: by WooCommerce – 1.4.1
Woo Subscriptions: by WooCommerce – 5.9.0
WooCommerce Table Rate Shipping: by WooCommerce – 3.1.6
WooCommerce: by Automattic – 8.6.0
WP Rollback: by WP Rollback – 2.0.6

### Inactive Plugins (6) ###

Classic Editor: by WordPress Contributors – 1.6.3
Insert PHP Code Snippet: by xyzscripts.com – 1.3.5
Query Monitor: by John Blackbourn – 3.15.0
Search Exclude: by QuadLayers – 2.0.7
WooCommerce All Products For Subscriptions: by WooCommerce – 4.1.4
WP Post Hide: by Xfinity Soft – 1.0.8

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #36 - /shop/
Cart: #37 - /cart/
Checkout: #38 - /checkout/
My account: #39 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Colinear
Version: 1.1.0-wpcom
Author URL: https://wordpress.com/themes/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### WooPayments ###

Version: 7.2.0
Connected to WPCOM: Yes
WPCOM Blog ID: 227593391
Account ID: acct_1OUP57Fd14H8NaZx
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Disabled
WooPay Incompatible Extensions: Yes
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://woorotation.wpcomstaging.com
Subscriptions-core Library Version: 6.7.0
Subscription Statuses: wc-active: 3
wc-expired: 1
wc-on-hold: 2
wc-pending: 1

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

other: wc-active: 3
wc-expired: 1
wc-on-hold: 1

### Payment Gateway Support ###

WooPayments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

### Product Bundles ###

Database Version: 6.22.6
Loopback Test: ✔
Template Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: –
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: vaulting_api

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-21 08:25:33 +04:00
Options: ✔
Notes: 83
Onboarding: -

### MailPoet ###

Sending Method: MailPoet
Send all site's emails with: Default WordPress sending method
Task Scheduler method: Action Scheduler
Cron ping URL: https://woorotation.wpcomstaging.com?mailpoet_router&endpoint=cron_daemon&action=ping

### Action Scheduler ###

Canceled: 3
Oldest: 2024-01-29 07:01:08 +0400
Newest: 2024-02-12 06:51:55 +0400

Complete: 4,666
Oldest: 2024-01-21 07:00:01 +0400
Newest: 2024-02-20 15:32:11 +0400

Failed: 2
Oldest: 2024-01-03 10:26:30 +0400
Newest: 2024-01-03 15:23:24 +0400

Pending: 20
Oldest: 2024-02-20 15:34:11 +0400
Newest: 2024-03-14 07:03:22 +0400

### Status report information ###

Generated at: 2024-02-20 15:32:58 +04:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rakshitwesley** [comment] 2024-02-20 12:06
Reported here:
(Self-hosted sites)
- 7754425-zd-a8c 
- 7754935-zd-a8c

Atomic sites: 
- 7759301-zd-a8c

**Comment by rakshitwesley** [comment] 2024-02-20 12:07
Workaround: Rollback WooCommerce to v8.5.2

**Comment by barryhughes** [comment] 2024-02-20 12:22
- Possible duplicate of https://github.com/woocommerce/woocommerce/issues/44679
- Fix for the above already has already been merged https://github.com/woocommerce/woocommerce/pull/44698

**Closed as completed** 2024-02-20 12:22 UTC
Labels: Bug
