### ISSUE TITLE
Last access time for API key gets updated 10 times for every REST API call

### ISSUE THREAD

**Issue by siliconforks** [woothemes/woocommerce#31511] opened 2021-12-25 05:07 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

For every WooCommerce REST API request using a WooCommerce API key, the key's last access time (stored in the database field `wp_woocommerce_api_keys.last_access`) gets updated 10 times.  This is obviously sub-optimal for performance.

### Expected behavior

I would expect the last access time to be updated only once (with one single SQL `UPDATE` query) per API request.

### Actual behavior

The last access time gets updated 10 times (with 10 separate SQL `UPDATE` queries) per API request.

### Steps to reproduce

1. First, I recommend using Firefox for testing this since it's going to be necessary to make REST API calls in a web browser and Firefox automatically formats JSON to make viewing much easier.  So you should start by logging in to WordPress with an Administrator account using Firefox.

2. In the WordPress admin section, click "WooCommerce", then "Settings".  Click the "Advanced" tab and then "REST API".

3. Click the "Add key" button to create a new API key.  Enter anything in the "Description" field; the "User" field should be pre-filled with your (Administrator) user account. For "Permissions", read-only access will be enough for testing purposes.  Click "Generate API key".  Copy the "Consumer key" and "Consumer secret" values and record them somewhere for future use.

4. Install the [Query Monitor](https://wordpress.org/plugins/query-monitor/) plugin.  We will use this for [analyzing REST API requests](https://querymonitor.com/blog/2021/05/debugging-wordpress-rest-api-requests/).

5. In your web browser (while you are still logged in as WordPress administrator - you need to be logged in for Query Monitor to work), visit the following URL:

```
https://example.com/path/to/wordpress/wp-json/wc/v3?consumer_key=ck_...&consumer_secret=cs_...&_envelope
```

Change `example.com`, `/path/to/wordpress`, `ck_...` and `cs_...` to match your site's URL and the API credentials you generated in step 3.  You should NOT change `https://` to `http://` because the REST API requires SSL to work.  If you only have an `http://` URL set up, as a quick hack you can edit your `wp-config.php` and add `$_SERVER['HTTPS'] = 'on';` somewhere before the "stop editing" line.  This will trick WordPress and WooCommerce into thinking that the site is being served over SSL, which is sufficient for testing the REST API.

In the JSON output you should see a `qm` key.  The duplicate SQL queries are under `qm.db_queries.dupes.queries`.  This should contain a query which looks something like:

```
UPDATE wp_woocommerce_api_keys SET last_access = '2021-12-25 04:14:03' WHERE key_id = 1
```

If your server is slow you might see some queries with one timestamp and other queries with a timestamp one second later, etc.  If your server is incredibly slow - suppose that it takes 10 seconds or more to handle the API request - then it's theoretically possible that you might not see any duplicate queries because each query could get a different timestamp.  But if your server handles the API request in a reasonable time (less than 10 seconds), you should see the duplicate queries there.

![screenshot](https://user-images.githubusercontent.com/1156399/147377290-e521adf7-c2c9-47e2-9690-f69249703973.png)

### WordPress Environment ###

WordPress address (URL): https://host.test/wordpress-woocommerce-git
Site address (URL): https://host.test/wordpress-woocommerce-git
WC Version: 6.1.0
REST API Version: ✔ 6.1.0
WC Blocks Version: ✔ 6.5.1
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.0-rc.1
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Ubuntu)
PHP Version: 7.4.3
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.27-0ubuntu0.20.04.1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.0
WC Database Prefix: wp_
Total Database Size: 4.35MB
Database Data Size: 2.92MB
Database Index Size: 1.43MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 3
product: 6
shop_order: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Query Monitor: by John Blackbourn – 3.7.1
WooCommerce: by Automattic – 6.1.0-dev

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 14
Oldest: 2021-12-23 18:13:16 +0000
Newest: 2021-12-25 04:11:15 +0000

### Status report information ###

Generated at: 2021-12-25 04:33:45 +00:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by zhongruige** [comment] 2021-12-27 16:23
Hi @siliconforks,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment] 2022-01-07 15:24
Thanks for the report and detailed steps to reproduce. Marking it as a bug to repro and investigate the root cause.

**Comment by siliconforks** [comment] 2022-01-07 15:53
The actual root cause seems to be the [Automattic\WooCommerce\Admin\API\Reports\PerformanceIndicators\Controller](https://github.com/woocommerce/woocommerce-admin/blob/main/src/API/Reports/PerformanceIndicators/Controller.php) class in the [woocommerce-admin](https://github.com/woocommerce/woocommerce-admin) project.  It has a `register_routes` method which ultimately leads to a call to `get_analytics_report_data` which makes a bunch of REST API requests in a `foreach` loop.  Each one of these requests updates the last access time.

So maybe this is actually a bug in the woocommerce-admin project?  On the other hand, arguably WooCommerce core should make it possible to perform "internal" REST API requests like this without updating the last access field unnecessarily.

**Comment by c7nj7n** [comment] 2023-02-15 13:13
I also have an issue with [Automattic\WooCommerce\Admin\API\Reports\PerformanceIndicators\Controller](https://github.com/woocommerce/woocommerce-admin/blob/main/src/API/Reports/PerformanceIndicators/Controller.php), which breaks inside `get_analytics_report_data`. I can reproduce locally, it's a combination of plugins and actions that triggers this error, I have dozens of them every day in my WooCommerce log files. Is there a way to filter the report endpoints?

**Closed as completed** 2024-05-31 10:44 UTC
Labels: Bug, REST/Store API/Webhooks, plugin: woocommerce, Performance
