### ISSUE TITLE
Stop “Customize your deposit schedule” banner in WC dashboard

### ISSUE THREAD

**Issue by indysigner** [woothemes/woocommerce#34708] opened 2022-09-16 06:02 UTC
Please stop the “Customize your deposit schedule” banner at the top of the dashboard (/wp-admin/admin.php?page=wc-admin and other WC pages in the dashboard).

![banner-wc](https://user-images.githubusercontent.com/4224281/190567214-3bcadfb2-dc7b-4017-b3ac-220ac4fbe31f.JPG)

It’s extremly annoying and it cannot even disabled via the customizer. It's *overriding the settings in the customizer* to NOT display any notices AKA banner ads by WooCommerce. It's really gross that **there isn't even a close button** or any other way to hide the ad.

![wc-notice-disabled](https://user-images.githubusercontent.com/4224281/190567451-8b9bc1db-1e1f-48d7-a900-6793706d27f1.JPG)

Please respect my choice to not see these banner ads. Thanks!

**Comment by piinthecloud** [comment] 2022-09-16 15:04
Hi @indysigner, thank you for flagging this. The issue is in progress and is being tracked [here](https://github.com/woocommerce/woocommerce/issues/34698)

Duplicate of #34698

**Comment by piinthecloud** [comment] 2022-09-16 15:05
Duplicate of #34698

**Closed as completed by piinthecloud** 2022-09-16 15:05 UTC
