### ISSUE TITLE
[CYS Woo Express] Footer with three menus

### ISSUE THREAD

**Issue by verofasulo** [woothemes/woocommerce#40947] opened 2023-10-23 08:38 UTC
Please review `Footer with three menus`.

How it currently looks like:

<img width="1727" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/0f613e70-2e1e-4e97-8be9-808436404fd4">

<img width="1728" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/e6c4c5a3-4f38-4733-a568-e46f586ad86b">

<img width="1728" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/32642d7f-a1f6-44df-bb13-0606e8e4e4ac">

---

How it's supposed to look like:

[Figma - Large screens](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2283-33973&mode=design&t=qkpAGsXW7rY6XBmF-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/f764b07d-57f7-4a21-bba5-37f047f653b5)

[Figma - Small screens](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2242-35939&mode=design&t=qkpAGsXW7rY6XBmF-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/ac1ad7fc-1ba8-4ea0-9a42-d7837c5066dc)

**Comment by nefeline** [comment] 2023-10-23 13:02
@verofasulo regarding the size of the icon:

<img width="1232" alt="Screenshot 2023-10-23 at 14 42 43" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/155df765-138b-4dab-8697-5d2a2e472667">

Patterns inherit whatever is set as the default on the Assembler: I would recommend reaching out to Guidorah to fix this as patterns are wireframed.

Also, regarding the alignment, @albarin mentioned last week that this is due to how the menus were created (the texts have a space at the beginning): https://github.com/woocommerce/woocommerce-blocks/issues/11333#issuecomment-1770819542

Do you mind confirming if that's still the case here @albarin ? 🙏

**Comment by verofasulo** [comment] 2023-10-23 14:29
> Patterns inherit whatever is set as the default on the Assembler: I would recommend reaching out to Guidorah to fix this as patterns are wireframed.

Thanks, @nefeline! @adrianduffell, @chihsuan could you please have a look into it? Thank you! 🙏

**Comment by albarin** [comment] 2023-10-23 14:43
@verofasulo @nefeline Yes, that's the issue, you can see here, that can be changed from the admin: <img width="372" alt="Screenshot 2023-10-23 at 16 42 55" src="https://github.com/woocommerce/woocommerce-blocks/assets/186112/e1b38e9b-cf22-48f3-b3e2-02d3f1b672d9">

**Comment by nefeline** [comment] 2023-10-23 15:15
> Yes, that's the issue, you can see here, that can be changed from the admin:

Gotcha, thanks for confirming @albarin! I'm going ahead and moving this issue to the core of Woo so @chihsuan and @adrianduffell can work on addressing Veronica's feedback regarding the icon size.

I have also created a brand-new Woo Express install and confirmed that this oddity we see with extra spaces in the footer menu resulted from manual user intervention: new installs come with the menus aligned correctly. Visit https://woo-delightfully-luminous-kryptonite.wpcomstaging.com/ as a reference:

<img width="1216" alt="Screenshot 2023-10-23 at 17 14 40" src="https://github.com/woocommerce/woocommerce-blocks/assets/15730971/4e60d085-c5f5-4b1d-adcb-c8f321d38847">

**Comment by chihsuan** [comment] 2023-10-24 06:48
Thanks for the ping! @verofasulo @nefeline I confirmed it's our side. I'll look into it.

**Comment by adrianduffell** [comment] 2023-10-24 14:31
@nefeline @albarin Can you please advise on what a tolerable range of image sizes would be? e.g. say 100-200px. At the moment, the user can set the image size to a much larger amount in the pattern assembler and break the design.

**Closed as completed** 2023-10-25 04:20 UTC

**Comment by nefeline** [comment] 2023-10-25 07:12
> Can you please advise on what a tolerable range of image sizes would be? e.g. say 100-200px. At the moment, the user can set the image size to a much larger amount in the pattern assembler and break the design.

I'll forward this question to @verofasulo as this sounds more like a design decision rather than an engineering decision.

**Comment by verofasulo** [comment] 2023-10-25 12:32
Thanks for tagging me, @nefeline! 

I'm having a look at the settings in the Editor, and it looks like 1450px is the max size.

<img width="271" alt="image" src="https://github.com/woocommerce/woocommerce/assets/98944206/cd2c823e-5e2f-4441-b22f-0b8cd066225b">

Could we please set the default to 60px and the max. to 200px? 200px is already insanely big but people like being creative.
