### ISSUE TITLE
[Enhancement]: A filter to remove email verification on order checkout success page of non-guest orders same like we have for guest orders.

### ISSUE THREAD

**Issue by shyam100379** [woothemes/woocommerce#41086] opened 2023-10-30 10:00 UTC
### Describe the solution you'd like

In the file: class-wc-shortcode-checkout.php, Woocommerce brought a new email verification feature for guest and non-guest orders in the order success page. 

```
// For non-guest orders, require the user to be logged in before showing this page.
if ( $order_customer_id && get_current_user_id() !== $order_customer_id ) {
			wc_get_template( 'checkout/order-received.php', array( 'order' => false ) );
			wc_print_notice( esc_html__( 'Please log in to your account to view this order.', 'woocommerce' ), 'notice' );
			woocommerce_login_form( array( 'redirect' => $order->get_checkout_order_received_url() ) );
			return;
		}

// For guest orders, request they verify their email address (unless we can identify them via the active user session).
if ( self::guest_should_verify_email( $order, 'order-received' ) ) {
			wc_get_template( 'checkout/order-received.php', array( 'order' => false ) );
			wc_get_template(
				'checkout/form-verify-email.php',
				array(
					'failed_submission' => ! empty( $_POST['email'] ), // phpcs:ignore WordPress.Security.NonceVerification.Missing
					'verify_url'        => $order->get_checkout_order_received_url(),
				)
			);
			return;
		}
```

In the latest version, we got ability to override/remove email verification for guest orders as you have introduced below:
`if ( self::guest_should_verify_email( $order, 'order-received' ) ) {`

But this condition is added only for guests. No matter what, the non-guest orders have no option to override/remove this verification process. Please introduce some filter for non-guest orders as well on the success page so that we could filter/remove it. 
Our suggestion is to put/bring this condition for non-guest orders as well.

**Comment by shyam100379** [comment] 2023-10-31 10:34
fyi: Closed by mistake.

**Comment by coreymckrill** [comment] 2023-11-01 21:40
@shyam100379 thanks for the suggestion. This looks like a duplicate of #39598, so I'm going to close this in favor of the older one.

**Closed as not planned by coreymckrill** 2023-11-01 21:40 UTC
Labels: Enhancement, Shopper Account/Management, type: community contribution
