### ISSUE TITLE
Variable Product - Main Image is not changed when selecting a variation

### ISSUE THREAD

**Issue by stormit** [woothemes/woocommerce#52518] opened 2024-11-02 11:27 UTC
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello,

I have found a bug with variable product. It does not change image when selecting a variation.  Follow the steps below:

- Add a variable product. Gallery images and variation images are the same.
- Go to frontend. Select a gallery image. Main image changed to gallery image
- Select a variation. Main image is not changed.

It seems that the **flexslider-click** trigger does not work correctly after selecting a gallery image.

`slideToImage.trigger( 'flexslider-click' );`

Please check and fix this issue soon.

Best regards,

### Expected behavior

In description

### Actual behavior

In description

### Steps to reproduce

In description

### WordPress Environment

Version 6.x

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by gigitux** [comment] 2024-11-20 08:34
This issue is a duplicate of https://github.com/woocommerce/woocommerce/issues/51242. I'm going to close this one.

**Closed as completed by gigitux** 2024-11-20 08:34 UTC
Labels: Bug, Product/Inventory Management, type: community contribution, Kirigami
