### ISSUE TITLE
Mac iOS 15 and Menus

### ISSUE THREAD

**Issue by Diesirae9** [woothemes/woocommerce#51743] opened 2024-09-27 18:13 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I go into a page to adjust information, many of the menus that are usually located on the left half of the screen are overlapping the menus on the right. When I try to adjust the menus, as thought I am customizing the system, they are not moving.  The dotted line that shows where these menus can go also only shows on half if the screen.  This appears only to happen in Safari, on a system that has been updated to Mac iOS 15.
<img width="2240" alt="Screenshot 2024-09-27 at 10 44 12 AM" src="https://github.com/user-attachments/assets/a58f4baf-815d-458f-b072-bc80b7ce773c">

### Expected behavior

When in 2 panel mode, usually the menu are laid out so I can access them.
<img width="2236" alt="Screenshot 2024-09-27 at 10 43 53 AM" src="https://github.com/user-attachments/assets/7d30c785-1c9c-4a7b-bf34-a702e28bb6a4">

### Actual behavior

The menus on the left are overlapping on the right.  This makes it so many features are not visible or usable.  
<img width="2236" alt="Screenshot 2024-09-27 at 10 43 53 AM" src="https://github.com/user-attachments/assets/a82ac21b-4f43-440a-8927-8551d2c97a5b">

### Steps to reproduce

1. Click on products
2. Select a product
3. Error is on any item loaded

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://zeppomerch.com
Site address (URL): https://zeppomerch.com
WC Version: 9.3.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.23
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.37-29
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.3.3
WC Database Prefix: wp_
Total Database Size: 134.80MB
Database Data Size: 79.88MB
Database Index Size: 54.92MB
wp_woocommerce_sessions: Data: 2.38MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 3.52MB + Index: 0.34MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 7.02MB + Index: 11.66MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 6.02MB + Index: 5.41MB + Engine InnoDB
wp_aws_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aws_index: Data: 11.48MB + Index: 10.36MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ewwwio_images: Data: 2.52MB + Index: 1.86MB + Engine InnoDB
wp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 4.52MB + Index: 0.81MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.44MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 15.44MB + Index: 10.02MB + Engine InnoDB
wp_posts: Data: 3.52MB + Index: 2.58MB + Engine InnoDB
wp_redirection_404: Data: 7.02MB + Index: 0.53MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_term_relationships: Data: 2.52MB + Index: 2.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.39MB + Index: 0.39MB + Engine InnoDB
wp_termmeta: Data: 0.39MB + Index: 0.48MB + Engine InnoDB
wp_terms: Data: 0.36MB + Index: 0.41MB + Engine InnoDB
wp_usermeta: Data: 2.52MB + Index: 4.03MB + Engine InnoDB
wp_users: Data: 0.22MB + Index: 0.22MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 1.06MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wdr_rules: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_woof_front_builder: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woof_sd: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woof_sd_presets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 3892
custom_css: 1
customize_changeset: 17
elementor_library: 14
nav_menu_item: 50
page: 16
post: 7
product: 1957
product_variation: 2695
revision: 25
shop_coupon: 1
shop_order_placehold: 9
wp_font_face: 33
wp_font_family: 12
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

XT Ajax Add To Cart for WooCommerce: by XplodedThemes – 1.1.3
Advanced Woo Search: by ILLID – 3.16
Autoptimize: by Frank Goossens (futtta) – 3.1.12
Child Themify: by John P. Bloch – 2.0.1
Elementor Pro: by Elementor.com – 3.24.2
Elementor: by Elementor.com – 3.24.4
EWWW Image Optimizer: by Exactly WWW – 7.9.0
Faire for WooCommerce: by Faire – 1.7.3
Mailchimp for WooCommerce: by Mailchimp – 4.4
Redirection: by John Godley – 5.5.0
Ultimate Infinite Scroll: by Ultimate Infinite Scroll – 1.0.5
Discount Rules PRO 2.0: by Flycart – 2.6.4
Discount Rules Core: by Flycart – 2.6.6
WooCommerce Square: by WooCommerce – 4.8.1
WooCommerce: by Automattic – 9.3.3

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (5) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
WP Engine Cache Plugin: by WP Engine – 1.3.1
WP Engine Seamless Login Plugin: by WP Engine – 1.6.1
WP Engine Security Auditor: by wpengine – 1.1.1
WP Engine System: by WP Engine – 5.0.1

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 20 MB

### WC Pages ###

Shop base: #279 - /full-catalog/
Cart: #261 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #262 - /checkout-2/ -  Contains the [woocommerce_checkout] shortcode
My account: #263 - /my-account/
Terms and conditions: #260 - /legal-privacy/

### Theme ###

Name: Profit Nexus
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Hello Elementor
Parent Theme Version: 3.1.1
Parent Theme Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Square ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-09-27 23:33:56 +00:00
Options: ✔
Notes: 71
Onboarding: completed

### Action Scheduler ###

Canceled: 16
Oldest: 2024-09-06 14:36:36 +0000
Newest: 2024-09-24 18:05:37 +0000

Complete: 22,761
Oldest: 2024-08-28 13:11:54 +0000
Newest: 2024-09-27 17:50:49 +0000

Failed: 1
Oldest: 2024-09-05 15:33:07 +0000
Newest: 2024-09-05 15:33:07 +0000

Pending: 4
Oldest: 2024-09-27 18:13:04 +0000
Newest: 2024-10-02 23:00:40 +0000

### Status report information ###

Generated at: 2024-09-27 18:09:59 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by elmarko** [comment] 2024-09-30 15:45
I am also having this issue in Safari version 18 on Sequoia. Chrome displays as expected

**Comment by orchidcode** [comment] 2024-10-01 12:53
Same problem in Safari 18.0 on MacOS Sequoia.

**Comment by peterwilsoncc** [comment] 2024-10-03 00:58
This is related to a bug introduced in Safari 18, see [Webkit#280063](https://bugs.webkit.org/show_bug.cgi?id=280063).

For the Classic Editor plugin, a workaround has been introduced to target Safari browsers. The intention is to remove it once a patch is released for Safari. https://github.com/WordPress/classic-editor/commit/ebd9da7f389d7ab18852d49e26463a8aafa21a12

I've been talking to a member of the Apple Developer Experience team via social media but they don't have an ETA on the next Safari release as yet.

**Comment by tammullen** [comment] 2024-10-04 11:51
Duplicate of https://github.com/woocommerce/woocommerce/issues/51684 
WooCommerce fix in https://github.com/woocommerce/woocommerce/pull/51734

**Comment by dinhtungdu** [comment] 2024-10-15 07:14
I'm closing this issue as https://github.com/woocommerce/woocommerce/pull/51734 is now merged.

**Closed as completed by dinhtungdu** 2024-10-15 07:14 UTC
Labels: Bug, type: community contribution, Kirigami
