### ISSUE TITLE
shipping-calculator-form block scroll

### ISSUE THREAD

**Issue by GrzegorzNecka** [woothemes/woocommerce#31098] opened 2021-11-08 08:37 UTC
Hi everyone

I use:
-  wooocmmerce 5.8.0
-  wordress 5.8.1 
- own theme with turn off support to woocommerce styles

I have a problem with the implementation of the shipping country selection mechanism. After switching the country. skroll is blocked. I don't know why. I deleted all plugins (with simplebar.js) and bug is exist still.

I will be grateful for any hint

![image](https://user-images.githubusercontent.com/34622107/140709259-4cddf5c3-08ee-427d-868d-957606c48eaa.png)

![image](https://user-images.githubusercontent.com/34622107/140709732-71d1622b-2358-4604-86ac-23b6400b915f.png)

**Comment by juliaamosova** [comment] 2021-11-14 23:13
Hi @GrzegorzNecka,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code-related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by juliaamosova** 2021-11-14 23:13 UTC
Labels: type: support request

**Comment by GrzegorzNecka** [comment] 2021-11-15 07:53
Hi, thanks for explains. I will remember about slack community
