### ISSUE TITLE
cant validate cart items when customer has specific role

### ISSUE THREAD

**Issue by DeanForde** [woothemes/woocommerce#30707] opened 2021-09-13 14:19 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
was using code to separate products at a checkout in order to prevent certain products being purchased together, lately we started using multiple user roles, the code works fine except for one specific user role? the code is straight forward, should be a straight forward process, ay help appreciated 

**Expected behavior**
cart validation for all roles

**Actual behavior**
no cart validation for wholesale_user role specifically 

**Basic code**

```
/*** Prevent mixture of gas and other prods in same cart ***//
function dont_add_gas_to_cart_containing_other($validation, $product_id) {

// Set flag false until we find a product in gas
    $cart_has_gas = false;

// Set $cat_check true if a cart item is in gas cat
    foreach (WC()->cart->get_cart() as $cart_item_key => $cart_item) {

        $product = $cart_item['data'];

        if (has_term('gas-tanks', 'product_cat', $product->id)) {
            $cart_has_gas = true;
            // break because we only need one "true" to matter here
            break;
        }
    }

    $product_is_gas = false;
    if (has_term('gas-tanks', 'product_cat', $product_id)) {
        $product_is_gas = true;
    }

// Return true if cart empty
    if (!WC()->cart->get_cart_contents_count() == 0) {
        // If cart contains gas and product to be added is not gas, display error message and return false.
        if ($cart_has_gas && !$product_is_gas) {
            wc_add_notice( 'Sorry, you can only purchase Helium Gas products on their own. To purchase this product, please checkout your current cart or empty your cart and try again', 'error');
            $validation = false;
        }
        // If cart contains a product that is not gas and product to be added is gas, display error message and return false.
        elseif (!$cart_has_gas && $product_is_gas) {
            wc_add_notice('Sorry, you can only purchase Helium Gas products on their own. To purchase this product, please checkout your current cart or empty your cart and try again', 'error');
            $validation = false;
        }
    }
    // Otherwise, return true.
    return $validation;
}

add_filter('woocommerce_add_to_cart_validation', 'dont_add_gas_to_cart_containing_other', 200, 5);
```

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://tofballoons.ie
Site address (URL): https://tofballoons.ie
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 384 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.23
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.78.0
OpenSSL/1.1.1l

SUHOSIN Installed: –
MySQL Version: 5.7.35
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: UqWku_
Total Database Size: 620.69MB
Database Data Size: 399.68MB
Database Index Size: 221.01MB
UqWku_woocommerce_sessions: Data: 4.02MB + Index: 0.05MB + Engine InnoDB
UqWku_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UqWku_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UqWku_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
UqWku_woocommerce_order_items: Data: 11.52MB + Index: 3.52MB + Engine InnoDB
UqWku_woocommerce_order_itemmeta: Data: 88.61MB + Index: 61.14MB + Engine InnoDB
UqWku_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
UqWku_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UqWku_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UqWku_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UqWku_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UqWku_woocommerce_payment_tokens: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
UqWku_woocommerce_payment_tokenmeta: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
UqWku_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UqWku_actionscheduler_actions: Data: 6.02MB + Index: 8.78MB + Engine InnoDB
UqWku_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UqWku_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UqWku_actionscheduler_logs: Data: 3.02MB + Index: 3.02MB + Engine InnoDB
UqWku_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UqWku_aelia_exchange_rates_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UqWku_bp_groups_groupmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UqWku_bp_groups_members: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
UqWku_bp_user_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UqWku_bp_user_blogs_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UqWku_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UqWku_comments: Data: 18.55MB + Index: 9.09MB + Engine InnoDB
UqWku_e_submissions: Data: 0.19MB + Index: 0.36MB + Engine InnoDB
UqWku_e_submissions_actions_log: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
UqWku_e_submissions_values: Data: 0.50MB + Index: 0.11MB + Engine InnoDB
UqWku_itsec_bans: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UqWku_itsec_dashboard_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UqWku_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UqWku_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UqWku_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UqWku_itsec_lockouts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
UqWku_itsec_logs: Data: 8.02MB + Index: 7.16MB + Engine InnoDB
UqWku_itsec_mutexes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UqWku_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UqWku_itsec_temp: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
UqWku_itsec_user_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UqWku_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UqWku_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UqWku_litespeed_url_file: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
UqWku_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UqWku_mw_wc_qbo_sync_customer_pairs: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
UqWku_mw_wc_qbo_sync_log: Data: 0.41MB + Index: 0.00MB + Engine InnoDB
UqWku_mw_wc_qbo_sync_paymentmethod_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UqWku_mw_wc_qbo_sync_payment_id_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UqWku_mw_wc_qbo_sync_product_pairs: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
UqWku_mw_wc_qbo_sync_qbo_customers: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
UqWku_mw_wc_qbo_sync_qbo_items: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
UqWku_mw_wc_qbo_sync_real_time_sync_history: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
UqWku_mw_wc_qbo_sync_real_time_sync_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UqWku_mw_wc_qbo_sync_shipping_product_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UqWku_mw_wc_qbo_sync_tax_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UqWku_mw_wc_qbo_sync_variation_pairs: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
UqWku_mw_wc_qbo_sync_wq_cf_map: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
UqWku_options: Data: 23.05MB + Index: 2.23MB + Engine InnoDB
UqWku_postmeta: Data: 164.70MB + Index: 81.20MB + Engine InnoDB
UqWku_posts: Data: 15.52MB + Index: 8.06MB + Engine InnoDB
UqWku_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
UqWku_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
UqWku_termmeta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
UqWku_terms: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
UqWku_term_relationships: Data: 3.52MB + Index: 2.52MB + Engine InnoDB
UqWku_term_taxonomy: Data: 1.52MB + Index: 1.95MB + Engine InnoDB
UqWku_tm_taskmeta: Data: 4.52MB + Index: 0.75MB + Engine InnoDB
UqWku_tm_tasks: Data: 3.52MB + Index: 0.28MB + Engine InnoDB
UqWku_um_metadata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
UqWku_usermeta: Data: 11.52MB + Index: 6.03MB + Engine InnoDB
UqWku_users: Data: 0.52MB + Index: 0.27MB + Engine InnoDB
UqWku_wcpdf_invoice_number: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
UqWku_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
UqWku_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UqWku_wc_category_lookup: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
UqWku_wc_customer_lookup: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
UqWku_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UqWku_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
UqWku_wc_order_product_lookup: Data: 12.52MB + Index: 10.06MB + Engine InnoDB
UqWku_wc_order_stats: Data: 1.52MB + Index: 0.61MB + Engine InnoDB
UqWku_wc_order_tax_lookup: Data: 1.52MB + Index: 0.44MB + Engine InnoDB
UqWku_wc_product_meta_lookup: Data: 2.52MB + Index: 5.75MB + Engine InnoDB
UqWku_wc_reserved_stock: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
UqWku_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UqWku_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
UqWku_woocommerce_bolt_checkout_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 15494
bp-email: 15
br_labels: 3
cf7_style: 12
custom_css: 1
customize_changeset: 6
cwginstocknotifier: 2275
elementor_library: 13
flamingo_contact: 2237
flamingo_inbound: 2
forum: 1
iksm: 2
itsec-dash-card: 16
itsec-dashboard: 2
nav_menu_item: 22
page: 17
popup_theme: 8
post: 3
product: 6698
product_variation: 786
revision: 117
shop_order: 9357
shop_order_refund: 1021
sp_wps_shortcodes: 1
topic: 1
um_directory: 1
um_form: 3
wa-order-numbers: 1
wcps: 1
wcps_layout: 1
woocarousel: 1
wpautoterms_page: 2
wpt_product_table: 1
yith_wcps_type: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

WooCommerce Advanced Product Labels: by BeRocket – 1.2.3.1
FiboSearch - AJAX Search for WooCommerce: by FiboSearch Team – 1.13.0
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: by codewoogeek – 2.3.2
Code Snippets: by Code Snippets Pro – 2.14.1
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.1.3
Elementor Pro: by Elementor.com – 3.3.8
Elementor: by Elementor.com – 3.4.2
Iks Menu: by IksStudio – 1.9.0
iThemes Security Pro: by iThemes – 7.0.3
LiteSpeed Cache: by LiteSpeed Technologies – 4.4
Min and Max Quantity for WooCommerce: by BeRocket – 1.3.2.1
WooCommerce Sync for QuickBooks Online - by MyWorks Software: by MyWorks Software – 2.4.0
OneClick Chat to Order: by Walter Pinem – 1.0.4.1
Qty Increment Buttons for WooCommerce: by taisho – 2.7.5
Ultimate Member: by Ultimate Member – 2.2.4
Visibility Logic for Elementor: by StaxWP – 2.1.7
WooCommerce Custom Add To Cart Button: by Barn2 Plugins – 1.1.2
XT WooCommerce Floating Cart: by XplodedThemes – 2.4.6
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.9.5
WooCommerce EU VAT Assistant: by Aelia – 2.0.20.210817
WooCommerce Stripe Gateway: by WooCommerce – 5.4.1
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.9.3
WooCommerce PDF Invoices & Packing Slips Premium Templates: by Ewout Fernhout – 2.10.1
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.18.0
WooCommerce Shipment Tracking: by WooCommerce – 1.6.28
Wholesale For WooCommerce: by wpexpertsio – 1.7.1
WooCommerce: by Automattic – 5.6.0

### Inactive Plugins (0) ###


### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #51 - /shop/
Basket: #52 - /cart/
Checkout: #53 - /checkout/
My account: #76 - /account/
Terms and conditions: #15264 - /terms-conditions/

### Theme ###

Name: Storefront
Version: 3.8.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 23,094
Oldest: 2021-08-19 13:53:09 +0100
Newest: 2021-09-13 14:59:02 +0100

Failed: 1
Oldest: 2021-03-03 12:42:24 +0000
Newest: 2021-03-03 12:42:24 +0000

Pending: 2
Oldest: 2021-09-14 03:26:02 +0100
Newest: 2021-09-14 14:56:02 +0100


### Status report information ###

Generated at: 2021-09-13 15:00:43 +01:00
`
```
</details>

**Comment by juliaamosova** [comment] 2021-09-18 19:43
Hi @DeanForde,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code-related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by juliaamosova** 2021-09-18 19:43 UTC
Labels: Bug, type: support request
