### ISSUE TITLE
Product import is using wrong attribute with same name

### ISSUE THREAD

**Issue by RVandenbussche** [woothemes/woocommerce#37184] opened 2023-03-12 15:56 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I export a product with the attribute "colour" (slug "shirt-colour") and value "black" (slug "shirt-black") it looks like the unique slug is not exported but the name. So what happens on import is that it uses the first "colour" attribute (slug "coat-black") with the value "black" (slug "coat-black"). Which results in a different image in the colour picker. So right now the product import feature seems pretty useless for most e-commerce stores with multiple types of "Colour" attributes.

Is there a workaround for this bug?

### Expected behavior

On import/export use attribute slug instead of name.

### Actual behavior

On import/export attribute name is used

### Steps to reproduce

Create attribute "colour" and add value black with image.
Create attribute "colour" with a different slug and add the value black with a different image

1. Go to products
2. Press export
3. Select variable product to export
4. Open .CSV file
5. Go to name attribute and see value attribute
6. Import product

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment] 2023-03-13 15:27
Hi @RVandenbussche,

Thanks for the report. Your report was missing the system status report. We need the system status report in order to try and reproduce the issue. Please reply to this message with the status report.

You can find the report from **WooCommerce > System Status** in WordPress admin. Click on "Get system report" and then "Copy for support".

**Comment by RVandenbussche** [comment] 2023-03-20 17:43
I don't think it's relevant at all but ok here you go:

`
### WordPress Environment ###

WordPress address (URL): https://x.com
Site address (URL): https://x.com
WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.7.2
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33.2
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.40-43-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.1
WC Database Prefix: 0_
Totale database grootte: 541.88MB
Database gegevens grootte: 296.76MB
Database index grootte: 245.12MB
0_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
0_woocommerce_order_items: Data: 3.52MB + Index: 1.52MB + Engine InnoDB
0_woocommerce_order_itemmeta: Data: 29.56MB + Index: 30.09MB + Engine InnoDB
0_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
0_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_actionscheduler_actions: Data: 3.02MB + Index: 6.84MB + Engine InnoDB
0_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_actionscheduler_logs: Data: 3.02MB + Index: 3.03MB + Engine InnoDB
0_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_aelia_exchange_rates_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
0_automatewoo_customers: Data: 1.52MB + Index: 3.11MB + Engine InnoDB
0_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
0_automatewoo_guests: Data: 1.52MB + Index: 1.27MB + Engine InnoDB
0_automatewoo_guest_meta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
0_automatewoo_logs: Data: 2.52MB + Index: 4.55MB + Engine InnoDB
0_automatewoo_log_meta: Data: 10.52MB + Index: 10.03MB + Engine InnoDB
0_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
0_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_commentmeta: Data: 1.52MB + Index: 2.02MB + Engine InnoDB
0_comments: Data: 31.56MB + Index: 26.09MB + Engine InnoDB
0_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_duplicator_pro_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_ee_products_sync_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_ee_product_sync_call: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_ee_product_sync_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_fooevents_check_in: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_mywebtonetperfstatsresults: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_mywebtonetqtest: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_nf3_action_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_nf3_field_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
0_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_nf3_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_nf3_objects: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
0_nf3_object_meta: Data: 9.52MB + Index: 0.00MB + Engine InnoDB
0_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_nf3_upgrades: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_options: Data: 4.47MB + Index: 0.25MB + Engine InnoDB
0_postmeta: Data: 150.69MB + Index: 121.30MB + Engine InnoDB
0_posts: Data: 7.52MB + Index: 5.98MB + Engine InnoDB
0_redirection_404: Data: 1.02MB + Index: 0.19MB + Engine InnoDB
0_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
0_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
0_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
0_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_revslider_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_revslider_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_rg_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_rg_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_rg_lead: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_rg_lead_detail: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
0_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
0_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_rg_userregistration: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
0_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_term_relationships: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
0_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_usermeta: Data: 15.55MB + Index: 21.06MB + Engine InnoDB
0_users: Data: 1.52MB + Index: 0.84MB + Engine InnoDB
0_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wcpdf_invoice_number_2022: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
0_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wc_customer_lookup: Data: 1.52MB + Index: 0.53MB + Engine InnoDB
0_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
0_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_wc_order_product_lookup: Data: 1.52MB + Index: 0.94MB + Engine InnoDB
0_wc_order_stats: Data: 0.50MB + Index: 0.48MB + Engine InnoDB
0_wc_order_tax_lookup: Data: 0.31MB + Index: 0.28MB + Engine InnoDB
0_wc_product_attributes_lookup: Data: 1.52MB + Index: 0.41MB + Engine InnoDB
0_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_wc_product_meta_lookup: Data: 0.22MB + Index: 0.38MB + Engine InnoDB
0_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
0_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wpml_mails: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
0_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wysija_campaign: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wysija_campaign_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wysija_custom_field: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wysija_email: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
0_wysija_email_user_stat: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wysija_email_user_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wysija_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wysija_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wysija_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_wysija_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wysija_url_mail: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wysija_user: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_wysija_user_field: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wysija_user_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_wysija_user_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0_yith_wcgeoip_rules: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_yoast_indexable: Data: 2.09MB + Index: 0.09MB + Engine InnoDB
0_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
0_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0_yoast_seo_links: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
0_yoast_seo_meta: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 516
aw_workflow: 24
custom_css: 1
event_magic_tickets: 122
gift_card: 185
gmpf: 1
mc4wp-form: 1
nav_menu_item: 26
nf_sub: 748
page: 21
portfolio: 8
post: 15
product: 71
product_variation: 1437
revision: 4
shop_coupon: 583
shop_order: 18765
shop_order_refund: 139
tablepress_table: 5
user_request: 1
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

Akismet Anti-Spam: door Automattic – 5.0.2
AutomateWoo: door WooCommerce – 5.6.6
WooCommerce Waardebon Generator: door Jeroen Sormani – 1.2.0
Duplicate Post Page Menu & Custom Post Type: door Inqsys Technology – 2.3.1
Conversios.io - All-in-one Google Analytics, Pixels and Product Feed Manager for WooCommerce: door Conversios – 5.3.2
FooEvents for WooCommerce: door FooEvents – 1.12.36
GPLVault Update Manager: door GPL Vault – 4.0.3
Head, Footer and Post Injections: door Stefano Lissa – 3.2.5
WPBakery Page Builder: door Michael M - WPBakery.com – 6.7.0
Maintenance: door WebFactory Ltd – 4.07
Mollie Payments for WooCommerce: door Mollie – 7.3.5
Ninja Forms: door Saturday Drive – 3.6.19
Redirection: door John Godley – 5.3.9
Shopkeeper Deprecated Features: door GetBowtied – 1.1.7
TablePress: door Tobias Bäthge – 2.0.4
Tidio Chat: door Tidio Ltd. – 6.0.3
TinyPNG - JPEG, PNG & WebP image compression: door TinyPNG – 3.4.1
WooCommerce NL Postcode Checker: door Ewout Fernhout – 2.8.1
WooCommerce Blocks: door Automattic – 9.7.2
WooCommerce Zettle Integration: door BjornTech AB – 7.8.2
WooCommerce Chained Products: door StoreApps – 2.9.9
WooCommerce Customer/Order/Coupon Export: door SkyVerge – 5.3.2
WooCommerce EU VAT Number: door WooCommerce – 2.3.26
WooCommerce Header Category Image: door Get Bowtied – 1.0.0
WooCommerce PayPal Payments: door WooCommerce – 2.0.2
PDF Invoices & Packing Slips for WooCommerce: door WP Overnight – 3.4.0
WooCommerce Product Bundles: door SomewhereWarm – 6.10.3
WooCommerce Product CSV Import Suite: door WooCommerce – 1.10.46
WooCommerce Sequential Order Numbers Pro: door SkyVerge – 1.17.0
WooCommerce: door Automattic – 7.4.1
Yoast SEO: door Team Yoast – 20.2.1
WP Mail SMTP: door WPForms – 3.7.0
WPFront Notificatie Balk: door Syam Mohan – 3.3.1
WP Overnight Sidekick: door WP Overnight – 2.5.1
YITH GeoIP Language Redirect for WooCommerce Premium: door YITH – 1.1.3
YITH WooCommerce Added to Cart Popup Premium: door YITH – 1.8.4
YITH WooCommerce Gift Cards Premium: door YITH – 3.3.8

### Inactive Plugins (13) ###

Autoptimize: door Frank Goossens (futtta) – 3.1.5
Classic Editor: door WordPress Contributors – 1.6.2
IP2Location Redirection: door IP2Location – 1.26.7
Nav Menu Manager: door Robert Noakes – 3.2.2
Nav Menu Roles: door Kathy Darling – 2.1.2
Variation Swatches for WooCommerce: door Woosuite – 2.1.8
WooCommerce Edit Order Numbers: door UltimateWoo – 1.1.1
WooCommerce Google Product Feed: door Ademti Software Ltd. – 10.1.2
WooCommerce Wholesale Lead Capture: door Rymera Web Co – 1.5.2
WooCommerce Wholesale Prices: door Rymera Web Co – 2.1.6.2
WooCommerce Wholesale Prices Premium: door Rymera Web Co – 1.14.6
WooSwatches - Woocommerce Color or Image Variation Swatches: door WooMatrix – 3.3.7
YITH WooCommerce Frequently Bought Together Premium: door YITH – 1.8.8

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (5) ###

Force Strong Passwords - WPE Edition: door Jason Cosper – 1.8.0
WP Engine Cache Plugin: door WP Engine – 1.1.2
WP Engine Seamless Login Plugin: door WP Engine – 1.6.0
WP Engine Security Auditor: door wpengine – 1.0.10
WP Engine System: door WP Engine – 5.0.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
ticket-event (ticket-event)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Winkelbasis: #699 - /winkel/
Winkelwagen: #705 - /winkelmand/
Afrekenen: #706 - /afrekenen/
Mijn account: #707 - /mijn-account/
Algemene voorwaarden: ❌ Pagina niet ingesteld

### Theme ###

Name: Shopkeeper Child Theme
Version: 1.00
Author URL: http:%20//www.getbowtied.com/
Child Theme: ✔
Parent Theme Name: Shopkeeper
Parent Theme Version: 2.9.984
Parent Theme Author URL: https://www.getbowtied.com/
WooCommerce Support: ✔

### Templates ###

Overrides: shopkeeper/woocommerce/archive-product.php
shopkeeper/woocommerce/checkout/form-coupon.php
shopkeeper/woocommerce/checkout/form-login.php
shopkeeper/woocommerce/content-product.php
shopkeeper/woocommerce/content-single-product.php
shopkeeper/woocommerce/global/quantity-input.php versie 7.2.1 is verouderd. De hoofdversie is 7.4.0
shopkeeper/woocommerce/global/sidebar.php
shopkeeper/woocommerce/global/wrapper-end.php
shopkeeper/woocommerce/global/wrapper-start.php
shopkeeper/woocommerce/single-product/add-to-cart/simple.php
shopkeeper/woocommerce/single-product/product-image.php
shopkeeper/woocommerce/single-product/product-thumbnails.php
shopkeeper/woocommerce/single-product/tabs/tabs.php
shopkeeper/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Leer hoe te updaten

### Product Bundles ###

Database Version: 6.10.3
Loopback Test: ✔
Template Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: NL
WooCommerce currency supported: ✔
Advanced Card Processing available in country: –
Pay Later messaging available in country: –
Webhook status: ✔
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-12 20:57:03 +01:00
Options: ✔
Notes: 26
Onboarding: completed

### WooCommerce Customer/Order/Coupon Export ###

Automated exports: 2
Custom formats: 4
Next export: Not scheduled

### Action Scheduler ###

Afgerond: 9.767
Oldest: 2023-02-09 17:47:34 +0100
Newest: 2023-03-12 16:23:37 +0100

In afwachting: 5
Oldest: 2023-03-12 19:48:44 +0100
Newest: 2024-01-01 00:00:01 +0100


### Status report information ###

Generated at: 2023-03-12 16:55:49 +01:00
`

**Comment by RVandenbussche** [comment] 2023-04-03 18:49
Is anyone going to fix this bug?

**Comment by RVandenbussche** [comment] 2023-04-03 18:55
@jonathansadowski is anyone going to fix this bug?

**Comment by RVandenbussche** [comment] 2023-05-13 18:25
Is this a tactic? Wait for an update of Woocommerce and then close the ticket?

**Comment by rrennick** [comment] 2023-05-17 18:20
> Is this a tactic? Wait for an update of Woocommerce and then close the ticket?

@RVandenbussche It looks like you accidentally created two identical issues. It was the second issue that was closed.

> When I export a product with the attribute "colour" (slug "shirt-colour") and value "black" (slug "shirt-black") it looks like the unique slug is not exported but the name.

Yes, that's correct. That is how the export and import are designed to work. I'll close this issue but feel free to @ me with a follow up with your use case for creating multiple attributes with the same name. I may be able to suggest an alternative implementation.

**Closed as completed by rrennick** 2023-05-17 18:20 UTC
Labels: Bug, Import/Export, type: community contribution

**Comment by RVandenbussche** [comment] 2023-07-05 08:40
@rrennick. That sounds like a bad implementation right? Because attribute names are not unique. And the attribute name is used in the front-end so you don't want to show the label "Coat colour 2" to the user because they are already on the coat product page and that might be confusing to the user. If the export/import function would be using the attribute slug instead that would be the best solution because it's an unique id. Sounds like a no-brainer to me to fix this.

This is personally very frustrating because I'm trying to export and import a lot of products only to find out it took the wrong attribute and I have to start all over again.

**Comment by rrennick** [comment] 2023-07-13 17:11
@RVandenbussche Could you explain the use case where you need multiple global attribute terms with the same label (eg. "Black")? Here's an example product where the attribute name is `Colour` and the terms used for variations are colour names:

```
ID,"Attribute 1 name","Attribute 1 value(s)","Attribute 1 visible","Attribute 1 global"
3364,Colour,"Green, Red, Yellow",1,1
3365,Colour,Red,,1
3366,Colour,Yellow,,1
3367,Colour,Green,,1
```

**Comment by RVandenbussche** [comment] 2023-07-13 17:43
@rrennick I think I've done that 3 times now but here is my problem: The problem arises when you use colour swatches or image swatches. So let's say I have a furry coat in colour (slug furry-colour) black (furry-black) and brown (furry-brown) and a t-shirt in colour black and brown. To explain the colours better to the user we use image swatches for the coat and use the colour swatches for the t-shirt. If I export and import the product then they all take the the same attribute furry-colour with furry-black and furry-brown so the t-shirt is also using image swatches with the wrong swatches.

If you're answer is that it's the problem of the swatches, it's not. The problem is that the attribute slug is not used but the attribute name. The attribute name is NOT unique in Woocommerce but the attribute slug is. My questions is why isnt' the slug used? It makes it all more difficult!

**Comment by rrennick** [comment] 2023-07-14 15:46
> The problem arises when you use colour swatches or image swatches

Thanks for the clarification. This sounds like it's an issue with how your swatches extension associates images to variations. In core, you can set an image for the variation in the dashboard or as a column in your import file. I'd suggest contacting the extension support to see if you could use the core default images. 

Edit to add: or possibly you could import/export the custom meta that the swatches extension uses for image association.

**Comment by RVandenbussche** [comment] 2023-07-15 14:57
@rrennick haha I expected this avoiding answer already, didn't even care to ready the rest of the answer did you? Could you explain me why a good developer would choose to use attribute name instead of an UNIQUE attribute slug?

Also when you have colour (slug: coat-colour) brown and black and you have colour (slug: shirt-colour) white and yellow and you import the t-shirt it adds white and yellow to slug coat-colour. So it has nothing to do with the swatch plugin. It's just a poor implementation.

Maybe it is best that a good developer looks into this bug?
