### ISSUE TITLE
Checkout Page does not set first listed payment gateway as default

### ISSUE THREAD

**Issue by michellemcdines** [woothemes/woocommerce#35954] opened 2022-12-13 10:31 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The ability to change the order of payment gateways was introduced in a previous update.

However regardless of the order that the gateways are dragged into in wp-admin, when you view the checkout page the default gateway is always whichever gateway was added/activated first.

### Expected behavior

I believe the correct behaviour should be that whichever payment gateway is first in the list, the radio button for selecting payment method should be set to this automatically - the inference being that the site admin will have put the preferred/most popular payment method first.

### Actual behavior

The checkout page lists the payment gateways in the order selected in wp-admin however the radio button is active for whichever payment gateway was added/activated first.

### Steps to reproduce

There are posts around with code to add to functions.php to set a default gateway, however I believe this is a bug that needs to be fixed.

The only non-code workaround I have worked out is to deactivate all payment gateways, then reactivate them with the preferred payment method activated first.

Example:

Site had three payment gateways activated as follows

Activated first - Cash on delivery
Activated second - BACS
Activated third - Stripe

Changing the order of these to display as:

Stripe
BACS
Cash on Delivery

still leaves the radio button active for Cash on Delivery

The workaround is to deactivate all payment gateways then reactivate them in the following order

1. Stripe
2. BACS
3. Cash on delivery

This results in Stripe being the active radio button on the checkout page.

The code needs to be corrected so that whichever payment gateway is listed first, the radio button is active for it on the checkout page.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://heavenonearthherbals.com
Site address (URL): https://heavenonearthherbals.com
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.5.2
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1q-fips

SUHOSIN Installed: –
MySQL Version: 5.7.39-42-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: iim_
Total Database Size: 73.59MB
Database Data Size: 50.85MB
Database Index Size: 22.74MB
iim_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
iim_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iim_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
iim_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
iim_woocommerce_order_itemmeta: Data: 0.23MB + Index: 0.17MB + Engine InnoDB
iim_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
iim_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iim_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iim_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_woocommerce_payment_tokenmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
iim_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_actionscheduler_actions: Data: 4.02MB + Index: 5.69MB + Engine InnoDB
iim_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_actionscheduler_logs: Data: 2.02MB + Index: 1.44MB + Engine InnoDB
iim_ac_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_admin_columns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_appointments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_coupons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_coupons_to_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_coupons_to_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_customer_bookings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_customer_bookings_to_events_periods: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_customer_bookings_to_events_tickets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_customer_bookings_to_extras: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_custom_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_custom_fields_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_custom_fields_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_custom_fields_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_events_periods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_events_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_events_to_providers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_events_to_tickets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_extras: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_galleries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_locations_views: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_notifications: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
iim_amelia_notifications_log: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
iim_amelia_notifications_sms_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_notifications_to_entities: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_packages_customers_to_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_packages_services_to_locations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_packages_services_to_providers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_packages_to_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_packages_to_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_payments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_providers_to_daysoff: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_providers_to_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_providers_to_google_calendar: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_providers_to_locations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_providers_to_outlook_calendar: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_providers_to_periods: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_providers_to_periods_services: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_providers_to_services: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_providers_to_specialdays: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_providers_to_specialdays_periods: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_providers_to_specialdays_periods_services: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_providers_to_timeouts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_providers_to_weekdays: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_providers_views: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_amelia_services_views: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_amelia_users: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iim_cartflows_ca_cart_abandonment: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
iim_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iim_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iim_comments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
iim_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
iim_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
iim_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iim_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_options: Data: 8.09MB + Index: 0.14MB + Engine InnoDB
iim_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_pmxi_imports: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
iim_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_postmeta: Data: 16.52MB + Index: 0.55MB + Engine InnoDB
iim_posts: Data: 3.52MB + Index: 0.20MB + Engine InnoDB
iim_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
iim_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
iim_term_relationships: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
iim_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
iim_usermeta: Data: 7.17MB + Index: 8.08MB + Engine InnoDB
iim_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
iim_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
iim_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
iim_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iim_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iim_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iim_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
iim_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
iim_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iim_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
iim_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iim_wps_hit: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
iim_wps_index: Data: 0.47MB + Index: 0.67MB + Engine InnoDB
iim_wps_key: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
iim_wps_object_term: Data: 0.11MB + Index: 0.22MB + Engine InnoDB
iim_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
iim_wps_query: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_wps_uri: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_wps_user_agent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_yoast_indexable: Data: 5.52MB + Index: 2.94MB + Engine InnoDB
iim_yoast_indexable_hierarchy: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
iim_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iim_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iim_yoast_seo_links: Data: 0.05MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 2
acf-field-group: 1
attachment: 225
cartflows_flow: 1
cartflows_step: 2
cookielawinfo: 13
custom_css: 8
e-landing-page: 1
elementor_library: 19
elementor-hf: 1
jetpack_migration: 2
jetpack-testimonial: 28
nav_menu_item: 13
oembed_cache: 31
page: 16
post: 19
product: 101
revision: 805
shop_coupon: 3
shop_order: 140
shop_order_refund: 10
wc_product_tab: 2
wp_global_styles: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Admin Columns Pro - WooCommerce: by AdminColumns.com – 3.7.3
Admin Columns Pro: by AdminColumns.com – 5.7.3
Advanced Custom Fields: by WP Engine – 6.0.4
Amelia: by TMS – 5.1
Astra Pro: by Brainstorm Force – 3.9.1
Astra Widgets: by Brainstorm Force – 1.2.12
Element Pack Pro: by BdThemes – 6.4.1
CartFlows: by CartFlows Inc – 1.11.5
CookieYes | GDPR Cookie Consent: by CookieYes – 3.0.5
Yoast Duplicate Post: by Enrico Battocchi and Team Yoast – 4.5
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.2
Elementor Pro: by Elementor.com – 3.7.3
Elementor: by Elementor.com – 3.8.1
Facebook for WooCommerce: by Facebook – 2.6.30
Folders: by Premio – 2.8.7
Elementor Header & Footer Builder: by Brainstorm Force
Nikhil Chavan – 1.6.13

Jetpack: by Automattic – 11.5.1
Google Ads & Marketing by Kliken: by Kliken – 1.0.8
Mailchimp for WooCommerce: by Mailchimp – 2.7.6
reCaptcha for WooCommerce: by I Thirteen Web Solution – 2.37
SiteGround Optimizer: by SiteGround – 7.2.6
WooCommerce Stripe Gateway: by WooCommerce – 7.0.1
WooCommerce Product Search: by itthinx – 3.4.0
WooCommerce Tab Manager: by SkyVerge – 1.13.1
WooCommerce Table Rate Shipping: by Bolder Elements – 4.2
WooCommerce: by Automattic – 7.1.0 (update to version 7.1.1 is available)
Yoast SEO: by Team Yoast – 19.10
WPForms Lite: by WPForms – 1.7.8
YITH WooCommerce Customize My Account Page: by YITH – 3.12.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #401 - /shop/
Basket: #97 - /my-basket/
Checkout: #98 - /checkout/
My account: #99 - /my-account/
Terms and conditions: #3897 - /terms-conditions/

### Theme ###

Name: Astra Child
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 3.9.1 – 3.9.4 is available
Parent Theme Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce Support: ✔

### Templates ###

Overrides: astra-child/woocommerce/archive-product.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-12-13 10:43:04 +00:00
Options: ✔
Notes: 118
Onboarding: completed

### Action Scheduler ###

Complete: 12,872
Oldest: 2022-11-12 20:12:06 +0000
Newest: 2022-12-13 10:30:13 +0000

Failed: 13
Oldest: 2022-11-05 14:57:06 +0000
Newest: 2022-12-12 05:27:05 +0000

Pending: 6
Oldest: 2022-12-13 18:37:55 +0000
Newest: 2022-12-19 05:28:56 +0000

### Status report information ###

Generated at: 2022-12-13 10:30:32 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment] 2022-12-14 12:13
Hi @michellemcdines,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the  WooCommerce 7.2.0 version and WordPress 6.1.1 version. 

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/207524851-831af68b-45bf-4dc9-8a55-19379d6afa2a.mp4


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by jorgeatorres** [comment] 2022-12-29 20:51
Hi @michellemcdines,

Thanks for the report. The behavior you've described is expected in this case.
Re-ordering gateways on the backend *does* affect the order in which they are displayed on the frontend, **but** if during a checkout flow you chose a gateway, we store that selection in the session, and restore it when you go to the checkout screen (regardless of the gateway order).

Otherwise, if you a buyer made a payment method choice during the checkout and decided to either refresh the page or go to a different page before coming back, that choice could've changed due to the admin possibly reordering the gateways.

When no choice has been made, the first gateway *does* get automatically selected. I'm assuming you're testing with a browser window that already has session data, but if you re-order gateways and open the checkout screen on an incognito window, the first gateway should've been selected.

As such, I'm going to close this issue, but feel free to re-open if I've misinterpreted something or if you feel this should still work differently.

**Closed as completed by jorgeatorres** 2022-12-29 20:51 UTC
Labels: Bug, plugin: woocommerce, type: community contribution
