### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by RavzaPapagan** [woothemes/woocommerce#37500] opened 2023-03-29 19:09 UTC
### Describe the solution you'd like

Hello, I am developing an e-commerce site with wordpress. I want to calculate the total cost by calculating the square meter of the products on my site, how should I do it?

### Describe alternatives you've considered

The idea I think is to keep the price of the product in the database and calculate the price from the wp_wc_product_meta_lookup table and the square meter from the page. where I can't get the price information from the table according to the page

**Comment by lsinger** [comment] 2023-03-29 19:23
Hi @RavzaPapagan,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review the [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- if you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- ask a question The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/); or
- make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/).

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by lsinger** 2023-03-29 19:23 UTC
Labels: Enhancement, type: community contribution
