### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by webhostingsrbijaRS** [woothemes/woocommerce#40065] opened 2023-09-07 09:14 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello i find performanse issue with MariaDB. 
Server that has issue specification: 
WHM/cPanel 110 | CloudLinux 7.9 | MariaDB 10.3 | LiteSpeed Web Server 6.1.2

Account transfered to server and do no have issue, server spec:
WHM/cPanel 110 | CloudLinux 7.9 | MySQL 5.7 | LiteSpeed Web Server 6.1.2

WordPress is the lastest at this moment and theme twentytwentythree, with plugins, woocommerce, elementor.

There is NO perofrmanse issue on other page except when click on EDIT PRODUCT. Even List product is under 1 sec. 
https://www.awesomescreenshot.com/video/20535366?key=abe0e75d6e6ff9670f694380591106c5

`lve-read-snapshot -u user-p 1d
...
>>> 2023-09-06T13:59:44, UID 1478

Faults:
        * CPU: 1

Processes:
+--------+-------------+---------+----------------------------------------------------+
|  PID   | Memory (Mb) | CPU (%) | CMD                                                |
+--------+-------------+---------+----------------------------------------------------+
| 281962 |      73     |    26   | lsphp:me/user/public_html/wp-admin/edit.php |
| 281933 |      96     |    4    | lsphp:/home/user/public_html/index.php      |
| 281728 |      42     |    0    | lsphp                                              |
| 281701 |      76     |    26   | lsphp:/home/user/public_html/index.php      |
| 281699 |      98     |    2    | lsphp:/home/user/public_html/index.php      |
| 281698 |     102     |    8    | lsphp:/home/user/public_html/index.php      |
| 281697 |      91     |    12   | lsphp:/home/user/public_html/index.php      |
| 281664 |      48     |    25   | lsphp:/home/user/public_html/index.php      |
| 248473 |      9      |    0    | lsphp                                              |
+--------+-------------+---------+----------------------------------------------------+

Http requests:
+------+-----------------+-----------+------------------------------------------------------------------------------------------+--------------+------+
| Pid  |      Domain     | Http type |                                           Path                                           | Http version | Time |
+------+-----------------+-----------+------------------------------------------------------------------------------------------+--------------+------+
| 9851 | domain.tld |    GET    |                           /wp-admin/edit.php?post_type=product                           |   HTTP/1.1   | 4.1  |
| 9851 | domain.tld |    GET    | /wp-json/wc-admin/options?options=woocommerce_task_list_reminder_bar_hidden&_locale=user |   HTTP/1.1   | 1.0  |
+------+-----------------+-----------+------------------------------------------------------------------------------------------+--------------+------+

Done..
[root@s1 ~]#`

### Expected behavior

After click on Edit product in list of product to open under 1sec. 

### Actual behavior

After click on Edit product in List of products open page to edit product after 20sec. 

### Steps to reproduce

1. go to /wp-admin/edit.php?post_type=product
2 click on edit product on some product

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://domain.tld
Site address (URL): https://domain.tld
WC Version: 8.0.3
REST API Version: ✔ 8.0.3
WC Blocks Version: ✔ 10.6.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: sr_RS
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.1.21
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 8.2.1
OpenSSL/1.1.1u

SUHOSIN Installed: –
MySQL Version: 10.3.39-MariaDB-cll-lve
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.3
WC Database Prefix: wpfh_
Укупна величина базе података: 11.48MB
Величина базе података: 10.70MB
Величина индекса базе података: 0.78MB
wpfh_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_actionscheduler_actions: Data: 0.16MB + Index: 0.07MB + Engine MyISAM
wpfh_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpfh_actionscheduler_logs: Data: 0.10MB + Index: 0.07MB + Engine MyISAM
wpfh_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpfh_e_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_mclean_refs: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wpfh_mclean_scan: Data: 0.17MB + Index: 0.04MB + Engine MyISAM
wpfh_options: Data: 1.98MB + Index: 0.05MB + Engine MyISAM
wpfh_postmeta: Data: 4.56MB + Index: 0.22MB + Engine MyISAM
wpfh_posts: Data: 3.64MB + Index: 0.18MB + Engine MyISAM
wpfh_sbi_feeds: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_sbi_feed_caches: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_sbi_instagram_feeds_posts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_sbi_instagram_feed_locator: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_sbi_instagram_posts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_sbi_sources: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpfh_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpfh_term_relationships: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpfh_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_usermeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpfh_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpfh_wc_admin_notes: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wpfh_wc_admin_note_actions: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wpfh_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wc_order_addresses: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wc_order_operational_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpfh_wc_product_meta_lookup: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wpfh_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpfh_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wdi_feeds: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wdi_themes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wpforms_payments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wpforms_payment_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wpforms_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wpf_filters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpfh_wpf_meta_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpfh_wpf_meta_values: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpfh_wpf_meta_values_bk: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 140
custom_css: 3
customize_changeset: 37
elementor_library: 2
nav_menu_item: 11
page: 12
popup: 1
post: 6
product: 99
revision: 71
wmpc-trash: 1893
wp_global_styles: 1
wp_navigation: 1
wp_template: 2
wpforms: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: од John Blackbourn – 3.13.1
Елементор: од Elementor.com – 3.15.3
Maintenance: од WebFactory Ltd – 4.08
WooCommerce: од Automattic – 8.0.3

### Inactive Plugins (3) ###

Smash Balloon Instagram Feed: од Smash Balloon – 6.2.1
Transliterator: од Ivijan-Stefan Stipić – 1.10.2
WPForms Lite: од WPForms – 1.8.3.1

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: RSD (рсд)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Продавница: #81 - /products/
Корпа: #82 - /cart-2/
Плаћање: #83 - /checkout-2/
Мој налог: #84 - /my-account-2/
Општи услови коришћења: ❌ Страница није подешена

### Theme ###

Name: Twenty Twenty-Three
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – Ако мењате WooCommerce на родитељској теми коју нисте сами направили
препоручујемо вам да користите изведену тему. Видите: Како направити изведену тему

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-09-07 11:26:23 +02:00
Options: ✔
Notes: 75
Onboarding: skipped

### Action Scheduler ###

Завршено: 594
Oldest: 2023-08-09 13:28:33 +0200
Newest: 2023-09-06 22:46:57 +0200

Није успело: 6
Oldest: 2023-08-09 13:28:33 +0200
Newest: 2023-09-06 12:07:59 +0200

На чекању: 1
Oldest: 2023-09-07 22:46:57 +0200
Newest: 2023-09-07 22:46:57 +0200

### Status report information ###

Generated at: 2023-09-07 11:00:22 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment] 2023-09-07 23:42
Hi @webhostingsrbijaRS: do you still have access to the environment where MariaDB is in use, and would you be able to install [Query Monitor](https://wordpress.org/plugins/query-monitor/) to check if any queries are particularly problematic?

**Comment by webhostingsrbijaRS** [comment] 2023-09-08 07:48
Query Monitor is in use as you can see in screenshot. 
Elementor goes and comes and change everytime >option_name<, "serbian-transliteration" very rare. 
Slow query are: 

<html>
<body>


SELECT option_valueFROM wpfh_optionsWHERE option_name = 'elementor_experiment-editor_v2'LIMIT 1 | +get_option() | Plugin: elementor | 0 | 0,0876
-- | -- | -- | -- | --
SELECT post_status, COUNT( * ) AS num_postsFROM wpfh_postsWHERE post_type = 'product'GROUP BY post_status | +wp_count_posts() | Plugin: woocommerce | 4 | 0,0878
SELECT option_valueFROM wpfh_optionsWHERE option_name = '_transient_timeout_serbian-transliteration-locales'LIMIT 1 | +get_option() | Plugin: serbian-transliteration | 1 | 0,0924
SELECT option_valueFROM wpfh_optionsWHERE option_name = 'woothemes_helper_master_key'LIMIT 1 | +get_option() | Plugin: woocommerce | 0 | 0,0872
SELECT option_valueFROM wpfh_optionsWHERE option_name = 'woocommerce_task_list_tracked_completed_actions'LIMIT 1 | +get_option() | Plugin: woocommerce | 0 | 0,0926
SELECT option_valueFROM wpfh_optionsWHERE option_name = '_transient_timeout_elementor_activation_redirect'LIMIT 1 | +get_option() | Plugin: elementor | 0 | 0,0842
SELECT *FROM wpfh_postsWHERE ID = 3348LIMIT 1 | +WP_Post::get_instance() | Plugin: woocommerce | 1 | 0,0784
SELECT t.term_idFROM wpfh_terms AS tINNER JOIN wpfh_term_taxonomy AS ttON t.term_id = tt.term_idWHERE tt.taxonomy IN ('product_shipping_class')ORDER BY t.name ASC | +WP_Term_Query->get_terms() | Plugin: woocommerce | 0 | 0,0808


</body>
</html>

**Comment by barryhughes** [comment] 2023-09-08 18:30
So the combined time of those queries doesn't seem *huge* (around 0.4s) and, in the screencast you shared in your original post, we can also see that of the 16s it took to build the page, less than 1s was spent on database queries.

Could something else be happening here: long-running HTTP requests, for instance? Query Monitor can also help to identify those.

**Comment by webhostingsrbijaRS** [comment] 2023-09-10 09:04
I didn't find HTTP request in query monitor but in network chrome inspect element has only this one: 
/wp-admin/post.php?post=3491&action=edit <= 5.7s
wp-json/wc-admin/options?options=woocommerce_task_list_reminder_bar_hidden&_locale=user <= 2s
/wp-admin/admin-ajax.php <= ~900ms two times this file

and show "waitning for server responds", and other files

**Comment by barryhughes** [comment] 2023-09-11 16:12
OK. Unfortunately, though, there isn't really enough information here to proceed: from the details shared so far, it's not clear that the problem lies with either the specific database engine (and, worth noting here that I don't see a big discrepancy if I test locally with `mariadb:10.3`) or with the queries generated by WooCommerce.

In terms of resolving things in your specific case, am I correct in thinking you have a solution (in that you've successfully switched to MySQL 5.7)?

**Comment by webhostingsrbijaRS** [comment] 2023-09-11 17:50
Yes, it is shared hosting dedicated. Different between servers is in MariaDB is on one and MySQL is on another, the rest of configuration si the same, even cPanel version is the same and OS.

**Comment by Babylon1999** [comment] 2023-10-08 14:20
Similar report in zd-7113877

https://wordpress.org/support/topic/after-woocommerce-update-both-frontend-and-wp-backend-became-extremely-slow/#post-17108545

**Comment by webhostingsrbijaRS** [comment] 2023-10-09 09:01
Since then i updated MariaDB to 10.6.15 but issue is still present.

**Comment by Babylon1999** [comment] 2023-10-16 21:20
Some feedback from zd-7113877 after I asked them to update MariaDB.

> Following [@babylon1999](https://wordpress.org/support/users/babylon1999/) advice, I’ve updated MariaDB from 10.3.39 to 10.6.15
I’ve also upgraded PHP from 7.4. to 8.0
All plugins updated, Woocommerce also to 8.2.
The long query keeps very slow and the other one:
SELECT post_status, COUNT( * ) AS num_posts
FROM usr8_posts
WHERE post_type = ‘product’
GROUP BY post_status
from caller: wp_count_posts()
is bigger than before, 5 seconds more or less

**Comment by lsinger** [comment] 2023-12-07 21:25
Hello @webhostingsrbijaRS,

Is there anything else you might be able to tell us about what is special about your environment? We haven't been able to reproduce the issue on our side and are still looking to understand how to trigger it. 

Does the issue still persist on the latest WooCommerce version? 

Does the version of WooCommerce make a difference, or is it isolated to just the database server? How many rows do all your tables have, roughly?

**Comment by webhostingsrbijaRS** [comment] 2023-12-07 21:31
Well i do not have any information that you request right now, since it is on produciton server and whetever client said about speed and has woocommerce in 24h we transfer accoun to another server. Also we do not create new accounts on that server since we confirm this issue.

I do not about last version, but when i reported this there is no diffrent with woo versions at that time. 
Environment i said in first post. 

Its small woocommerce shops less then 200 products.

**Comment by lsinger** [comment] 2024-01-22 09:16
@webhostingsrbijaRS Thank you again for you report. Since we cannot reproduce the issue with the information we have so far, we are closing this issue for now. Please open the issue again or create a new one if you new information comes to light.

**Closed as completed by lsinger** 2024-01-22 09:16 UTC
Labels: Bug, needs: triage feedback, type: community contribution, Performance
