### ISSUE TITLE
duplicate order number issued, previous order overwritten

### ISSUE THREAD

**Issue by ayerscares** [woothemes/woocommerce#7973] opened 2015-04-17 16:22 UTC
On my production site, WooCommerce recorded an order (successfully charged via payment gateway)... then 15 minutes and 22 seconds later, created another new order (totally separate customer) with the same order number. This overrode the first order. Two customers received confirmation emails with the same order number. (but the first order was not in the database).

Scary stuff.

During this time, no code changes, no database changes. Running WC 2.3.4.

**Comment by mikejolley** [comment] 2015-04-20 10:21
Core has [protection against this](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-checkout.php#L193-L197), and [new orders](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-checkout.php#L211) are created via [WordPress functions](https://github.com/woothemes/woocommerce/blob/c19f2e573e5828f7a8c79a3d3022a22e9f50086a/includes/wc-core-functions.php#L96).

I don't see a case where this could happen without outside influence. Are you running order number plugins?

**Comment by ayerscares** [comment] 2015-04-20 18:44
No order number plugins, but I do see that we pushed some new code to production close to the first order that went unrecorded. The code did not affect core or plugins.

Though it shouldn't have changed anything in the database, it's possible that the caches were cleared. (The page-cache, the CDN cache, and the object cache.) Could that have affected it?

**Comment by mikejolley** [comment] 2015-04-23 15:37
hmm I'm not sure how that would affect things. Has this only happened the once?

**Comment by ayerscares** [comment] 2015-04-23 15:38
Yes just that once.

From: Mike Jolley
Reply-To: woothemes/woocommerce
Date: Thursday, April 23, 2015 at 11:37 AM
To: woothemes/woocommerce
Cc: Ian Ayers
Subject: Re: [woocommerce] duplicate order number issued, previous order overwritten (#7973)


hmm I'm not sure how that would affect things. Has this only happened the once?

**Comment by mikejolley** [comment] 2015-04-23 15:49
Do you have any other logs that may be useful to us, and what gateway was it?

**Comment by mikejolley** [comment] 2015-04-27 10:27
If you find anything else out/happens again please let us know. I'm closing this right now as non reproducible.

**Closed by mikejolley** 2015-04-27 10:27 UTC
Labels: Needs Reporter Feedback

**Comment by sajeewasl** [comment] 2015-06-18 08:36
hi

**Comment by sajeewasl** [comment] 2015-06-18 08:37
I have the same issue

**Comment by deepankarpathak** [comment] 2015-06-18 09:38
I also have same issue. PG used was - PayTM.

**Comment by tmleeek** [comment] 2016-03-10 23:36
hello guys , its seems if the order failed on completing the payment and returned to the website and not processed the payment gateway will not accepting the same order , unless i clear the basket which is not cool , is there any way to make this refreshed

**Comment by tmleeek** [comment] 2016-03-11 01:25
how to renew the cart order id and where its stored

**Comment by tmleeek** [comment] 2016-03-11 13:11
how can i make order id generated only on the time person click place order button , because this really create a lot of trouble with payment gateways .

**Comment by mkaulback** [comment] 2018-04-11 15:54
I had the same issue occur yesterday. Two completely separate orders, both via different payment gateways. I received emails for both orders, but only one is showing in woo commerce orders.

Woocommerce - 3.3.5
Wordpress - 4.9.5

**Comment by surendhar-eventjini** [comment] 2020-01-02 08:48
Had this issue today - Woocommerce - 3.8.1
