### ISSUE TITLE
Stock quantity and pending payment behaviour

### ISSUE THREAD

**Issue by tatenalan** [woothemes/woocommerce#36454] opened 2023-01-16 17:31 UTC
### Describe the solution you'd like

Hello community! I hope this is the correct category to talk about this matter.  It is not a problem itself, but it is some behaviour it should change in my opinion.

When a client, let’s say “Client A” makes a purchase but doesn’t pay, the order remains in “Pending Payment” status. This status holds the stock but doesn’t reduce it. Leading some cases where the stock available is not the real stock and affecting the user experience.

for example:
We have 10 units of “Product A” and the “Client A” order 5 units of that product and doesn’t pay.

Then “Client B” see that “Product A” has 10 units in stock and adds 6 units or more to the cart. When goes to cart page a validation message appears and it says there are only 5 units in stock of “Product A”. This happens because the “Pending payment” order of Client A is holding 5 units in stock. 10 – 5 = 5.

### Describe alternatives you've considered

**I think of two solutions for this matter:**
1) Changing the behaviour of pending payment status so it reduces the stock instead of “holding it”.
2) Changing the quantity stock number so it shows the actual stock minus the holding stock from Pending payment orders.

**I would discard solution 1** because if I change the behaviour of pending payment to reduce stock and then the payment changes status to “failed” the stock is not returned. This would lead me to change also the “failed” status behaviour and I don’t think changing many behaviours should be a good idea.

**Solution 2** would be the best I believe because I just need to show the user the real stock (**total stock minus held stock from pending orders**).

Can anyone help me to get solution 2?

### Additional context

This is a default behaviour of Woocommerce

**Comment by rrennick** [comment] 2023-10-13 09:44
This issue is a duplicate of #31551 as the order is also Pending Payment on that issue.

**Closed as completed by rrennick** 2023-10-13 09:44 UTC
Labels: Enhancement, Product/Inventory Management, plugin: woocommerce, type: community contribution

**Comment by tatenalan** [comment] 2023-10-18 03:23
> This issue is a duplicate of #31551 as the order is also Pending Payment on that issue.

Hello @rrennick, By the way, ticket #31551 is similar but not identical. While both report improper stock handling, that ticket mentions that buyers were able to complete the purchase, causing the seller to sell more units than they actually had. In my case, the buyer is not allowed to complete the purchase and instead receives a validation message saying there are not enough units available. That ticket also links the issue with Stripe and Paypal, but mine does not. Do you still think these are duplicate issues? Thank you

**Comment by rrennick** [comment] 2023-10-18 14:34
> Do you still think these are duplicate issues? Thank you

@tatenalan Yes. Payment gateways can reduce stock at different times during the checkout/order flow. The underlying issue is a user being able to use the browser back button to re-initiate checkout on the same cart.

**Comment by rrennick** [comment] 2023-10-18 14:39
Also, @tatenalan there is an extension you can install that reduces stock for cart and pending payment orders where you can specify how long to hold the stock (eg 24 hours).

**Comment by tatenalan** [comment] 2023-10-18 18:56
@rrennick Firstly, thank you for following up. Does this issue have an official solution? Are you affiliated with the WooCommerce team? The native 'hold stock time' feature of WooCommerce is not a solution for this matter, as the problem arises while that stock is being held. However, perhaps the extension you mentioned could help. Could you please provide the download link for that extension?

Thank you again.

**Comment by rrennick** [comment] 2023-10-19 15:11
> Does this issue have an official solution?

I appreciate that this is an issue for how you want your shop to work but WooCommerce is working as designed. WooCommerce is designed to be very customizable through custom code.

> Are you affiliated with the WooCommerce team?

If you want to check this for anyone here you can click on their avatar.

> Could you please provide the download link for that extension?

There are multiple extensions which offer this. The one with WooCommerce support is [Reserve Stock for WooCommerce](https://woocommerce.com/products/reserve-stock-for-woocommerce/).
