### ISSUE TITLE
"Table does not exist - Woo 5.6.0" # False Positive in System Status 

### ISSUE THREAD

**Issue by PaulodoPorto** [woothemes/woocommerce#30579] opened 2021-08-25 19:51 UTC
Gentlemen, 
just to let the situation reported again. Today 08/25/21, I upgraded from version **5.5.2** to version **5.6.0.** 

I also needed to update the database and plus 2 template files. And unfortunately I'm facing the same situation on the website on Localhost.

I use XAMPP Server and everything is fine with the server.
I access the admin panel with a Admin Account. 

I don`t have any error message in the debug.log file when I refresh the page.

In addition to the attempts mentioned here, would anyone have another alternative so that I can try to solve the status problem?

Thank you so much in Advance!

- **Wordpress Version 5.8**
- **WooCommerce Version: 5.6.0**
- **WooCommerce Database Version: 5.6.0**

**Comment by juliaamosova** [comment] 2021-08-26 14:26
Hi @PaulodoPorto,

I am not a gentleman but I am happy to reply. 

We need a bit more information here in order to look into it further:

- How are you updating the plugin? Do you use an update available prompt in the plugins section? Manually? 
- How do you update the database? Do you click on the button on the notice to update the database?  
- How do you update 2 template files? Which files? 

Detailed step-by-step instructions on how to reproduce the issue are always preferred which is why we provide a template to submit the issue. If you can support your issue with screenshots or a short video, it is even better.

**Comment by PaulodoPorto** [comment] 2021-08-28 16:56
Hello @juliaamosova , Thank you so much for reply and i'm sorry for the late answer!
Here we go!

-     How are you updating the plugin? Do you use an update available prompt in the plugins section? Manually?
       A: Yes, I do the update often manually. I download the compacted folder on woocommerce directory/release on Github.
       I extract the folder inside my directory: C:\xampppserver2\htdocs\prowp\wp-content\plugins\woocommerce
       I active the Plugin on the Admin Panel.
-     How do you update the database? Do you click on the button on the notice to update the database?
       A: Yes, I clicked on the button to update the database. Before I do the backup of the database.
-     How do you update 2 template files? Which files?
      A: Those are the files. They were updated to Version 5.6.0
      The files update is made manually.
      astra-child/woocommerce/emails\email-addresses.php
      astra-child/woocommerce/order\order-details.php
     and before the point raise any doubts. Yes, the Father Template is always updated in the same day I receive an update notification
     
     It follows a screenshot to the actual table status on the woocommerce status session:
     Thank you so much and i'm happy to collaborate with the woocommerce!
     
     
![wootable](https://user-images.githubusercontent.com/20026126/131225128-8c5b2324-72e0-4907-927a-ef72b987d3ea.JPG)

**Comment by simplysaru** [comment] 2021-08-29 10:25
Hi @PaulodoPorto, 

Could you clarify on why you are updating this manually? Are you running into errors with the auto-updates in WordPress plugin dashboard? 

I updated from WooCommerce 5.5.2 to WooCommerce 5.6.0 from the plugins page dashboard and I didn't encounter any errors. I also updated via the manual method by unzipping it into the plugin folder, which also didn't create any errors for me.

**Comment by PaulodoPorto** [comment] 2021-08-30 10:35
Hello @simplysaru ,
Could you clarify on why you are updating this manually? Are you running into errors with the auto-updates in WordPress plugin dashboard?
**A: I don't' use auto-updates in Wordpress. I need to control what's happening during the update process.**
And yes, the error on Woocommerce status session persist.

**Comment by tammullen** [comment] 2021-09-08 12:33
Hi @PaulodoPorto ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by tammullen** 2021-09-08 12:33 UTC
Labels: needs: triage feedback, type: support request
