### ISSUE TITLE
Reports calculations

### ISSUE THREAD

**Issue by fabianhenzler** [woothemes/woocommerce#8592] opened 2015-07-16 14:47 UTC
![voila_capture 2015-07-16_04-41-31_nachm](https://cloud.githubusercontent.com/assets/1168345/8726481/c89685a6-2bda-11e5-9460-c19de13adf27.png)

Our production seem not to calculate and show the "gross sales", "net sales" and "average daily sales" anymore. Which Status do the orders have to be in to be included here?
Also the "worth of coupons used" seems to be calculated wrong.

**Comment by mikejolley** [comment] 2015-07-16 15:32
completed processing on-hold, but can be changed by plugins

**Comment by fabianhenzler** [comment] 2015-07-16 15:40
i understand - thanks :)

but the "worth of coupons used (3,00 €)" seems really off. the graph on the right show the accurate amount.

**Comment by mikejolley** [comment] 2015-07-16 15:55
If there is something up with statuses, I cannot really say whats causing that.

**Comment by fabianhenzler** [comment] 2015-07-16 16:12
all orders with coupons used are completed

**Comment by mikejolley** [comment] 2015-07-16 16:33
But none of those orders are being reported..

**Comment by fabianhenzler** [comment] 2015-07-16 16:34
yes, because they're all with 100% discount.

**Comment by mikejolley** [comment] 2015-07-16 16:41
Rather than debug these reports, I feel we should wait until you're running 2.4. The report queries have been changed in that release and may account for discounts better. Of course, this relies on the discount amount being set per order correctly and the type of order. I see you're running subs.

**Comment by mikejolley** [comment] 2015-07-27 11:29
Closing this to revisit after 2.4 if needed. OP report of gross sales and net sales is not a bug; the orders are discounted so gross is correctly 0.

**Closed by mikejolley** 2015-07-27 11:29 UTC

**Comment by kloon** [comment] 2015-07-30 11:56
Fixed via https://github.com/woothemes/woocommerce/commit/622dc777f004c487fc947f5f822f0d9ef08d9c44
