### ISSUE TITLE
No option to create an account password in Checkout Blocks

### ISSUE THREAD

**Issue by AbhinavSakalle** [woothemes/woocommerce#43993] opened 2024-01-23 11:14 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When account creation is enabled on the checkout with Checkout Blocks, there doesn't seem to be an option to create an account password. With the shortcode-based checkout, you get two fields (Username and Password) to create an account but that's not the case with the checkout blocks.

When you place the order using the Create account checkbox and enter your email address, the order is placed and the account gets created but you don't have a password to access it again unless you reset the password.

This kind of defeats the purpose of account creation for those who would like to allow users to create their own password at the time of account creation so it can be used in the future.

### Expected behavior

There should be an option to enter the password. A field similar to the one that appears on the shortcode-based checkout.

### Actual behavior

When you enable account creation on checkout and select the Create an account checkbox, no password field appears.

### Steps to reproduce

1. Create a checkout page with blocks and set it under WooCommerce > Settings > Advanced > Checkout
2. Go to WooCommerce > Settings > Accounts & Privacy enable the following:

-  Allow customers to place orders without an account (Required for checkout blocks to work for account creation)
-  Allow customers to create an account during checkout
- Screenshot: https://d.pr/i/7wsCYc

3. Add a product to the cart visit the checkout page as a non-logged-in user and select the Create an account checkbox
4. There is no field to create an account password: https://d.pr/i/4PTdjR

### WordPress Environment

`
### WordPress Environment ###

WC Version: 8.5.1
REST API Version: ✔ 8.5.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.2.15
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.4.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.1
WC Database Prefix: wp_
Total Database Size: 32.48MB
Database Data Size: 16.88MB
Database Index Size: 15.60MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.41MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.23MB + Index: 0.17MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.17MB + Index: 0.09MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.08MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 8.52MB + Index: 11.00MB + Engine InnoDB
wp_posts: Data: 2.48MB + Index: 0.81MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.36MB + Index: 0.58MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 15
aw_workflow: 1
bookable_resource: 3
custom_css: 1
nav_menu_item: 5
page: 13
post: 32
product: 279
product_variation: 3009
revision: 5
shop_coupon: 2
shop_order: 54
shop_order_refund: 3
shop_subscription: 8
wal_transaction_log: 1
wal_wallet: 1
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.5.1

### Inactive Plugins (37) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
AutomateWoo: by WooCommerce – 6.0.12 (update to version 6.0.13 is available)
Bookings Helper: by WooCommerce – 1.0.5
Braintree for WooCommerce Payment Gateway: by WooCommerce – 3.1.2
Code Snippets: by Code Snippets Pro – 3.6.2
Google Listings and Ads: by WooCommerce – 2.5.15
Jetpack: by Automattic – 13.0
Loco Translate: by Tim Whitlock – 2.6.6
PayPal PLUS for WooCommerce: by Inpsyde GmbH – 2.2.1
Product Bundle Discount: by Codup – 1.1.3.11
Product Video for WooCommerce: by Addify – 1.5.1 (update to version 1.6.0 is available)
Refer a Friend: by Addify – 1.1.0
Storefront Hamburger Menu: by WooCommerce – 1.2.2
Storefront Parallax Hero: by WooCommerce – 1.5.7
Storefront Powerpack: by WooCommerce – 1.6.2 (update to version 1.6.3 is available)
Wallet for WooCommerce: by Flintop – 3.4.0
WooCommerce All Products For Subscriptions: by WooCommerce – 4.1.0 (update to version 4.1.4 is available)
WooCommerce Bookings: by WooCommerce – 1.15.69 (update to version 2.0.8 is available)
WooCommerce Box Office: by WooCommerce – 1.1.39 (update to version 1.2.4 is available)
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.9 (update to version 1.7.12 is available)
WooCommerce FedEx Shipping: by WooCommerce – 3.8.4 (update to version 3.8.7 is available)
WooCommerce Local Pickup Plus: by SkyVerge – 2.11.1 (update to version 2.11.2 is available)
WooCommerce Order Barcodes: by WooCommerce – 1.4.0 (update to version 1.7.3 is available)
WooCommerce Payfast Gateway: by WooCommerce – 1.6.1
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Product Bundles: by WooCommerce – 6.17.0 (update to version 6.22.6 is available)
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.49 (update to version 1.10.67 is available)
WooCommerce Product Vendors: by WooCommerce – 2.1.66 (update to version 2.2.5 is available)
WooCommerce Royal Mail: by WooCommerce – 2.5.43 (update to version 3.1.0 is available)
WooCommerce Shipment Tracking: by WooCommerce – 1.8.0 (update to version 2.4.3 is available)
WooCommerce Shipping & Tax: by WooCommerce – 2.4.2
WooCommerce Smart Coupons: by StoreApps – 8.12.0 (update to version 8.14.0 is available)
WooCommerce Square: by WooCommerce – 4.4.1
WooCommerce Stripe Gateway: by WooCommerce – 7.9.1
WooPayments: by Automattic – 7.0.0
Woo Subscriptions: by WooCommerce – 5.8.0 (update to version 5.9.1 is available)
WordPress Importer: by wordpressdotorg – 0.8.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #51046 - /checkout-block/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.4
Author URL: https://woo.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-24 07:58:35 +00:00
Options: ✔
Notes: 166
Onboarding: completed

### Action Scheduler ###

Canceled: 3
Oldest: 2024-01-15 06:20:00 +0000
Newest: 2024-01-22 06:05:38 +0000

Complete: 1,028
Oldest: 2023-12-25 02:55:27 +0000
Newest: 2024-01-23 11:12:31 +0000

Failed: 88
Oldest: 2023-02-20 05:39:18 +0000
Newest: 2023-08-18 07:53:50 +0000

Pending: 4
Oldest: 2024-01-23 11:13:46 +0000
Newest: 2024-02-04 05:30:54 +0000

### Status report information ###

Generated at: 2024-01-23 11:12:36 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment] 2024-01-23 14:07
Hi,

Thanks for the feedback. This is a duplicate of https://github.com/woocommerce/woocommerce/issues/42430 so I'll mark this closed.

We're going to be working on deferred account creation for block checkout soon—this will allow creation with manually created passwords after checkout so as not to block conversions.

Thanks

**Closed as completed by mikejolley** 2024-01-23 14:07 UTC
Labels: Bug
