### ISSUE TITLE
Default sorting order not working correctly

### ISSUE THREAD

**Issue by Strumara** [woothemes/woocommerce#9794] opened 2015-12-08 20:56 UTC
This is on WC 2.4.11, but I find it also on 2.4.5.

Default sorting is not working in combination with products that have custom menu order. The products remain sorted on title. 

When changing the sorting (front end) in to f.e. "Popularity" and than back to "Default", the parameter "?orderby=menu_order" will appear in the menu. Now the products are sorted correctly.

**Comment by mikejolley** [comment] 2015-12-08 21:27
'default' can be anything you want. What is wp-admin/admin.php?page=wc-settings&tab=products&section=display set to?

**Comment by Strumara** [comment] 2015-12-09 19:02
Sorting on "custom ordering + name"
<img width="739" alt="schermafbeelding 2015-12-09 om 19 59 18" src="https://cloud.githubusercontent.com/assets/11558029/11695484/b68bde90-9eaf-11e5-9f8f-b87a1913a501.png">

**Comment by mikejolley** [comment] 2015-12-10 10:50
Post your system status report.

**Comment by Strumara** [comment] 2015-12-10 18:33
### WordPress Environment ###

WC Version: 2.4.11
WP Version: 4.3.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
Language: nl_NL

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.15
PHP Post Max Size: 32 MB
PHP Time Limit: -1
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.44
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.11
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (16) ###

Gravity Forms: door rocketgenius – 1.9.14
Actionable Google Analytics: door Tatvic – CC-V3-1.2
Akismet: door Automattic – 3.1.5
iThemes Security: door iThemes – 5.1.1
Postman SMTP: door Jason Hendriks – 1.7.2
WooCommerce Sisow Betaal Opties: door Sisow – 4.5.3
Stream: door XWP – 3.0.4
Taxonomy Metadata: door mitcho (Michael Yoshitaka Erlewine)
sirzooro – 0.5

W3 Total Cache: door Frederick Townes – 0.9.4.1
Woocommerce Advanced Bulk Edit: door George Iron – 3.6.2
WooCommerce Print Invoice & Delivery Note: door Triggvy Gunderson – 4.1.5
WooCommerce Local Pickup Plus: door SkyVerge – 1.10.0 – 1.11.0 is beschikbaar
WooCommerce: door WooThemes – 2.4.11
WooSidebars: door WooThemes – 1.4.3
Yoast SEO: door Team Yoast – 3.0.6
WP All Export Pro: door Soflyy – 1.2.1

### Settings ###

Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Winkelbasis: #4 - /shop
Winkelmand: #5 - /cart
Afrekenen: #6 - /checkout
Mijn account: #7 - /my-account

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Flatsome Child Theme
Version: 2.5
Author URL: http://www.uxthemes.com/
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 2.7.6
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/success.php
flatsome/product-searchform.php
flatsome/woocommerce/single-product/add-to-cart/grouped.php
flatsome/woocommerce/single-product/add-to-cart/simple.php
flatsome/woocommerce/single-product/add-to-cart/variable.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/additional-information.php
flatsome/woocommerce/single-product/tabs/description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

**Comment by mikejolley** [comment] 2015-12-14 11:56
I'm still unable to replicate this one. I find it odd that the query string would show different results because the default sort order, and that passed query, adjust the actual product query in exactly the same way.

https://github.com/woothemes/woocommerce/blob/77714623cf515e5fe83161752159b74741ec1e59/includes/class-wc-query.php#L553-L554

I'd guess that it might be partly due to the caching plugin - a querystring would cause a different 'cache'.

You can also check through your theme/child theme for any filters on woocommerce_default_catalog_orderby as this could affect the default in ways core cannot control.

Closing as this appears to be a non-core issue/unreproducible on clean install.

**Closed by mikejolley** 2015-12-14 11:56 UTC

**Comment by Strumara** [comment] 2015-12-14 12:18
Thanks for your help. I will try a new install

**Comment by wingsryder** [comment] 2017-04-21 12:47
I have same issue with this theme? Any solution ?

**Comment by duckonwater** [comment] 2017-05-03 11:21
Same issue with latest version, any news on this?

**Comment by duckonwater** [comment] 2017-05-03 12:18
Thank @TryGOnl but that didn't resolve it for us :-( Gonna try reinstalling and see if that fixes.

**Comment by pranay26** [comment] 2017-12-13 11:47
Same Issue.
Default Sorting dropdown is not working.
It behaves like its dead.

**Comment by Genesis671230** [comment] 2024-03-19 06:42
I am trying to change the default sorting with custom one. as well as implementing different UI.
But not working
