### ISSUE TITLE
Tax class assigned to products not calculated when local pickup is the shipping method

### ISSUE THREAD

**Issue by sukafia** [woothemes/woocommerce#31359] opened 2021-12-03 10:41 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When tax class is assigned to a product, the tax isn't calculated when local pickup is the selected shipping method but is calculated for other shipping methods.

**Expected behavior**
Tax classes should be independent of the shipping method and so should be calculated if local pickup is selected, just like it's calculated when a flat rate is selected.
**Actual behavior**
Tax is calculated when flat rate is selected but not calculated when local pickup is selected.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a shipping zone and add local pickup (free) and flat rate (paid) to it.
2. Go to WooCommerce > Settings > Tax and create a tax class (name it whatever you desire)
2. Configure a tax rate for the class (e.g 20%)
3. Create a product (e.g simple or variable product) and assign the tax class to the product
4. Add the product to the cart & select local pickup and you'll see tax isn't calculated - select another shipping method (e.g flat rate) and you'll see tax is calculated.

**Screenshots**
https://d.pr/i/qH2RJC (Tax calculated for flat rates)
https://d.pr/i/CExEU6 (Tax not shown for local pickup)

It's worth clarifying that this isn't shipping tax but the product tax so the selected shipping methods shouldn't affect tax.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
N/A
```

**Comment by sukafia** [comment] 2021-12-03 10:43
4562730-zen

**Comment by swatipawarGS** [comment] 2021-12-03 15:29
Hi @sukafia ,


Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using WooCommerce 5.9.0 version.

Please find below screenshots for reference :

For flat rates : 
![#31359(flat rate)](https://user-images.githubusercontent.com/94531721/144606653-7aa47f0c-b0a2-40b0-b3e2-5c411a01b398.jpg)


For local pickup : 


![#31359(local)](https://user-images.githubusercontent.com/94531721/144606357-565f1dba-b6a4-4e4d-a450-1fab52657a13.jpg)

Please provide us more detailed and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by sukafia** [comment] 2021-12-03 20:06
Hi @swatipawarGS, thanks for taking a look. Can you confirm that the tax class is assigned to the product like this: https://d.pr/i/epsOOc ?

**Comment by swatipawarGS** [comment] 2021-12-06 13:38
Hi @sukafia ,

Thank you for the updated screenshot, yes the tax class is assigned to the product as given in the screenshot but we are unable reproduce the issue on our end with WooCommerce 5.9.0 version.

Please find below screenshots for reference :

adding Tax class : 


![#31359(product)](https://user-images.githubusercontent.com/94531721/144804386-07c23332-ba78-4138-9f07-9b57009c3b60.jpg)

For flat rates :


![#31359(flat)](https://user-images.githubusercontent.com/94531721/144804381-1dcd89bc-5ab4-4448-bb34-4b6c04be249b.jpg)

For local pickup :

![#31359(local)](https://user-images.githubusercontent.com/94531721/144804385-1ff3c514-3101-4b83-ac61-e33dbe9203cd.jpg)




Please provide us with more details and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by aheckler** [comment] 2021-12-17 19:36
In testing, I could not repro this either. User in 4562730-zen said:

> I was able to solve this issue myself. The issue was the my shop's address was not set to the correct state in WooCommerce>Settings.
> 
> Please close this case on your end. 

@tammullen This issue can be closed.

**Comment by tammullen** [comment] 2021-12-17 19:38
Thanks @aheckler!
Closing

**Closed as completed by tammullen** 2021-12-17 19:38 UTC
Labels: Bug, needs: triage feedback
