### ISSUE TITLE
[Enhancement]: Improve Reduce Quantity Checkout for Limited Purchases

### ISSUE THREAD

**Issue by zachspears** [woothemes/woocommerce#48736] opened 2024-06-21 23:13 UTC
### Describe the solution you'd like

In the case where a customer has an item quantity in their cart that exceeds the purchase limit, such as in the case of enabling **Sold individually**, the store page presents an unintuitive interface. In this case, as seen in the example below, there is no indication of how many items are in the cart for the offending item, and the only way to reduce the number is to remove the item from the cart entirely. If there are a lot of items in the cart, it is also unintuitive to locate the offending item, as the only way to know which is causing the error is by the error itself or by comparing the product price to the total price. This creates a frustrating experience where, at best, the customer must remove the item from their cart entirely (as reducing the quantity is not possible despite the language of the error) and then go and locate the product to add it again, or at worst, abandon their cart altogether.  

<img width="1506" alt="Screenshot 2024-06-21 at 5 40 04 PM" src="https://github.com/woocommerce/woocommerce/assets/10124024/08ff10f4-9177-4cec-ac6b-9346084f0a6a">

A more intuitive and customer-friendly approach would be to add the quantity selector back to the offending item with an error color or indicator providing only the option to remove items. Once the item reaches the maximum allowed, the quantity selector can be obscured again.  

### Describe alternatives you've considered

Other options that would help include:
- Highlighting the offending item.
- An addition button that just removes extra quantities instead of the product itself.
- Indicating product quantities when an error like this occurs. 
- Update language of the error to be more intuitive to the required action. Instead of "Reduce quantity" which cannot be done by the customer, use the language "Remove item."

**Comment by mikejolley** [comment] 2024-06-25 14:35
@zachspears How do you get your cart into this state? 

![Screenshot 2024-06-25 at 15 35 20](https://github.com/woocommerce/woocommerce/assets/90977/42ae91ef-3426-413b-9647-0ed016155c56)

Items like this are blocked when you try to add more to the cart. If we're talking about changing settings once the cart is already populated, that is a problem, but it wouldn't be as high priority because it's more of an edge case scenario.

Removing the excess would be a good middle ground to avoid introducing the UI elements.

**Comment by mikejolley** [comment] 2024-07-22 12:13
I’m going to close this because there still isn’t anything actionable for us on this issue. I'm not sure its possible to get the cart into this state since items that are sold individually are blocked from being added to the cart twice. 

If you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Closed as completed by mikejolley** 2024-07-22 12:13 UTC
Labels: Enhancement, needs: author feedback, Cart, type: community contribution, Rubik
