### ISSUE TITLE
[HPOS] Compat with datastore getters when fetching a prop and order ID is 0

### ISSUE THREAD

**Issue by vedanshujain** [woothemes/woocommerce#38274] opened 2023-05-12 09:15 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In OrderTableDataStore class, we use `wc_get_order( $order_id )` in getters to fetch and return the prop. However, this may raise fatal in case `$order_id` is 0, for example, when order is not yet saved to the database. This issue scopes adding protections around those getters to handle case with order_id = 0 gracefully.

### Expected behavior

n/a

### Actual behavior

n/a

### Steps to reproduce

1. Add a custom filter like so:
```php
add_action( 'woocommerce_checkout_create_order', function( $order ) {
	throw new Exception( 'simulate a checkout error' );
} );
```
2. Checkout the order with a dummy product
3. If posts are active, you won't see a fatal error, but there will be a fatal error with HPOS active.

### WordPress Environment

n/a

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment] 2023-12-18 13:10
I cannot reproduce the error using the filter suggested above so I'll close the issue for now. Let's reopen if and when we find out that it still exists.

**Closed as completed by lsinger** 2023-12-18 13:10 UTC
Labels: Bug
