### ISSUE TITLE
[Enhancement]: Load categories and attributes on demand in product editor

### ISSUE THREAD

**Issue by Konamiman** [woothemes/woocommerce#34000] opened 2022-07-20 14:34 UTC
### Describe the solution you'd like

As pointed out in https://github.com/woocommerce/woocommerce/issues/26539, the edit product page in the admin area will take ages to render (frontend issue) in a site with thousands of categories and attributes, since all the existing category names, all the existing attribute names, and all the existing terms for attributes assigned to the product will be loaded upfront in order for the user to be able to select them.

Since all these existing categories, attributes and terms will be needed only when the user actually wants to edit them for the product at hand, I suggest to initially displaying only the values that are already applied to the product, and load the rest on demand whenever needed. Here's a rough implmentation suggestion:

### Categories

Current UI, it shows all the existing categories:

![image](https://user-images.githubusercontent.com/937723/180006526-ee7a40e8-04df-4e69-a7b4-80ade6005519.png)

Suggested alternative: when the edir product page is loaded, display only the categories that the product is currently in (ugly mockup, a real life version would get some styling):

![image](https://user-images.githubusercontent.com/937723/180006238-fce951eb-fa9b-4f7b-b45b-5d96e7e5fe96.png)

The user can click “Edit” **and then** the full list of categories would be retrieved via AJAX and the original UI with the checkboxes would be rendered. Maybe we could even add some pagination but that could go into a “v2” of the feature.

### Attributes

Current UI, it has a dropdown will "Custom product attribute" and all the existing attribute names, also it has (initially hidden) dropdowns with all the existing terms for all the attributes already applied to the product:

![image](https://user-images.githubusercontent.com/937723/180006819-64e5a8dd-53b8-46ce-b936-3bc53f71c6ca.png)

Suggested alternative:

For the attribute selector, replace the dropdown and the “Add” button with:

* A new “Add custom product attribute” button; and
* A dropdown that would load the attribute names via AJAX only when it’s first clicled; **and/or** a textbox with autocomplete.
 
For the attributes already existing in the product: load upfront and display only the terms that the product has already assigned for each attribute, then add an “Edit” button, and when the user clicks it, that’s when all the terms for that attribute are loaded via AJAX and the existing editor is switched to (again, an advanced version of this could use pagination for the list of terms):

![image](https://user-images.githubusercontent.com/937723/180007133-e79eb693-8d69-4833-9553-a65bde57e199.png)

### Implementation hint for the new categories UI

The attributes editor uses custom metaboxes that WooCommerce renders by itself, so it should be easy to modify. Changing the categories editor is a bit trickier, because it's just relying in the default taxonomy rendering provided by WordPress.

However it's doable with the appropriate hooking. Here's a possible way:

```php
add_action('add_meta_boxes', function() {
	global $wp_meta_boxes;

	$new_callback = function($post, $args) {
		global $wp_meta_boxes;

		// The following returns links, so better use something like get_terms
		// (also TODO: handle hierarchy)
		$categories = wc_get_product_category_list($post->ID,'<br/>');

		echo '<div>' . $categories. '</div>';
		echo '<br/>';
		echo '<div><b><a href="#">Edit</a></b></div>';
	};
	$wp_meta_boxes['product']['side']['core']['product_catdiv']['callback'] = $new_callback;
});
```

The "Edit" button would trigger an AJAX call that would execute the following:

```php
//$id comes from the request
$post = get_post($id);
$args = $wp_meta_boxes['product']['side']['sorted']['product_catdiv'];
ob_start();
post_categories_meta_box($post, $args);
$html = ob_get_clean();
return $html;
```

and then the frontend code would replace the categories `<div>` with the HTML received in the DOM.

### Describe alternatives you've considered

The OP of https://github.com/woocommerce/woocommerce/issues/26539 wasn't able to find any alternative and ended up giving up on using WooCommerce for their project 😟

### Additional context

Originally discussed in p7bje6-4if-p2.

**Comment by pmcpinto** [comment] 2022-07-22 10:56
@AnnaMag is it possible to have the team provide estimates for the changes proposed by Néstor? It would be great to see if we can include it in the next cycle.

@jarekmorawski I think all the suggestions make sense. But let me know if you have any concerns or additional recommendations. Thanks

**Comment by jarekmorawski** [comment] 2022-07-22 13:36
I agree. This seems to align with both current and future product editing experience. Regarding attributes, I've recently suggested a few changes to the user experience. One of them quite nicely captures what we're trying to do here.

<img width="708" alt="image" src="https://user-images.githubusercontent.com/79307566/180450608-1d4e7c41-8343-4446-8727-b117e3b12c72.png">

Products without any attributes could have an empty state that'd work in a similar manner.

<img width="720" alt="image" src="https://user-images.githubusercontent.com/79307566/180450359-51306ad5-6853-4cc9-9be3-aa1642f8d017.png">

**Comment by octaedro** [comment] 2022-08-12 19:20
Thank you @Konamiman for this excellent analysis.
The proposed changes look pretty straightforward and adding them shouldn't take more than two or three days. The downside of the solution is that all the categories will still be loaded. So it would improve the experience, but I'm not sure that it will solve the problem entirely for stores with thousands of categories.
I second the idea of implementing pagination in a v2.

**Comment by octaedro** [comment] 2022-08-15 13:45
Hey @pmcpinto,

Answering your question:
> @AnnaMag is it possible to have the team provide estimates for the changes proposed by Néstor? It would be great to see if we can include it in the next cycle.

Considering this is an old bug that only affects a few stores, code freeze will happen in 3 days, and during these days we have a tight bandwidth; what do you think about leaving this fix for the next release (7.0)?

**Comment by pmcpinto** [comment] 2022-08-23 10:05
> Considering this is an old bug that only affects a few stores, code freeze will happen in 3 days, and during these days we have a tight bandwidth; what do you think about leaving this fix for the next release (7.0)?

Hey @octaedro I think it makes sense to include this in the cycle that starts today and see if it's possible to ship it with 7.0. Thanks

**Comment by louwie17** [comment] 2022-09-13 17:52
As discussed on our Mothra team call, this issue needs a bit more grooming on what the exact issue is.
We should figure out if this is a rendering issue, and thus limit the amount that is rendered to the window height, see this [react-window](https://react-window.vercel.app/#/examples/list/fixed-size) as an example, we did probably want to use something different to solve this.

If it isn't a rendering issue, but an API query issue, we should explore pagination.

This issue should be timeboxed to two days for now to answer and try the above. If either will take a large amount of work and UI revamp, we will want to consider swapping in the new category dropdown for the new product management screen. As this component might of already solved this problem.

**Comment by louwie17** [comment] 2022-09-20 14:30
@jarekmorawski @Konamiman I currently have a [partial PR](https://github.com/woocommerce/woocommerce/pull/34744) open for adding the typeahead changes to the attributes tab.
But felled like there was some unanswered questions in relation to the **Product categories** widget.

One thing I want to note first is that I added over 7000 categories and didn't notice any rendering issues on my local machine, but of-course the UI became very counterintuitive as the user would have to use a very tiny scrollbar to find the categories, so the proposed changes are still beneficial.

To my questions:
- In terms of only showing selected categories in the list in the above format, what do we do if only a child is selected but not the parent? Do we want to still render the parent, but show some other icon for the actual selected categories?
Or should we just list them out similar to what product tags do:
<img width="298" alt="Screen Shot 2022-09-20 at 11 24 33 AM" src="https://user-images.githubusercontent.com/2240960/191284116-06132b4f-eb7d-4322-b649-d85d561a4aaa.png">
- I noticed there is a category typeahead dropdown on the product list page ( when more then 200 categories exist). I was wondering if we should make use of this same typeahead field and use that in the category list instead?
<img width="333" alt="Screen Shot 2022-09-20 at 11 26 29 AM" src="https://user-images.githubusercontent.com/2240960/191284605-fc72b3cb-cf49-4036-8879-ff09523a3e48.png">
- @jarekmorawski if it isn't to much work, it would be nice to get some kind of wireframe for the changes around the product categories as well.

**Comment by jarekmorawski** [comment] 2022-09-27 11:24
> In terms of only showing selected categories in the list in the above format, what do we do if only a child is selected but not the parent?

I think we'd use a new format for the child categories: `[Parent] > [Child]`. If just the parent was added, it would appear as `[Parent]`. Note that this structure would apply to the new UX, too.

> - I noticed there is a category typeahead dropdown on the product list page ( when more then 200 categories exist). I was wondering if we should make use of this same typeahead field and use that in the category list instead?

Good call! I think we could use a combination of this and the tags management interface. Maybe something like this would work? It's a quick mockup but could help set the direction. We would only load the list of categories on click rather than page load, like currently. cc @pmcpinto 

<img width="1463" alt="image" src="https://user-images.githubusercontent.com/79307566/192513474-d4b4747e-4c60-4da3-96c9-4cd08a4227ac.png">

Figma: 6cBYbZmiet1l7gzc28ce8k-fi-5301%3A253895

**Comment by louwie17** [comment] 2022-09-29 16:34
Thanks @jarekmorawski those designs look good, I did create a new issue for this part in particular, so it could be worked on in tandem if needed: https://github.com/woocommerce/woocommerce/issues/34885

**Comment by pmcpinto** [comment] 2022-10-12 18:09
@louwie17 do you have an estimate of when it will be possible to wrap up this work?

**Comment by louwie17** [comment] 2022-10-12 19:56
The attributes part of this issue has been finished and merged, I created a separate issue for the categories part #34885 .

As per @jarekmorawski design most of this should already be available, aside from the dropdown with the checkboxes. So to do that work it would take between 2-3 day's.
I have not started this part yet, as I had grabbed the MVP attributes work in the mean time. This is why I created a separate issue after the feedback so someone else on the team could grab it in the mean time.
I should finish the MVP attribute work soon, so could wrap this up afterwards if no-one else took the above issue yet.

**Comment by pmcpinto** [comment] 2022-10-13 13:44
👍 thanks for the update.

**Comment by pmcpinto** [comment] 2022-10-21 15:19
> The attributes part of this issue has been finished and merged

@louwie17 will these changes be released in 7.1?

**Comment by louwie17** [comment] 2022-10-21 15:39
> @louwie17 will these changes be released in 7.1?

Yeah they will be, as these changed were merged before the code freeze of 7.1.
I haven't tested it with the Beta yet though.

**Comment by lsinger** [comment] 2024-01-08 09:16
@pmcpinto @louwie17 the issue still persists and is open, yet it's in Mothra's "done" column. Is it maybe the case that a related or sub-task of this is done but the issue is still there? Also see #37548 for a related complication.

**Comment by louwie17** [comment] 2024-05-16 08:58
> @pmcpinto @louwie17 the issue still persists and is open, yet it's in Mothra's "done" column. Is it maybe the case that a related or sub-task of this is done but the issue is still there? Also see #37548 for a related complication.

Thanks for tagging us again @lsinger, this did get done under a feature flag, but we decided to not enable it as default because of the nature of the fix ( which is quite a UI update ).
Folks could still enable it if they install the WooCommerce Beta Tester and enable the **async-product-editor-category-field** feature under **Tools > WCA Test Helper > Features**.

I am also closing this because of the work in the new product editor, which also solves this issue and folks can also enable the new product editor.

**Closed as completed by louwie17** 2024-05-16 08:58 UTC
Labels: Enhancement, Product/Inventory Management, Performance
