### ISSUE TITLE
"Please log in" link on checkout does not do anything

### ISSUE THREAD

**Issue by shendy-a8c** [woothemes/woocommerce#33265] opened 2022-05-31 01:35 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

With a clean install, purchasing a subscription product with an email of an existing user, on checkout page, it will show 'An account is already registered with your email address. Please log in.' error.

![Screen Shot 2022-05-31 at 08 18 36](https://user-images.githubusercontent.com/73803630/171074884-66d1c49f-41ea-440b-9c68-32dbba24ac23.png)

### Expected behavior

The 'Please log in' link does something that allows user to login.

### Actual behavior

Clicking on the 'Please log in' link doesn't do anything.

### Steps to reproduce

1. Spin up a clean install wordpress site.
2. Install WooCommerce.
3. Install WooCommerce Subscriptions. This is required because we want to ask user to login on checkout and purchasing a subscription product with an existing user's email would do that.
4. Enable 'Direct bank transfer' payment from wp-admin > WooCommerce > Payments. This is so we don't have to install any payment plugins and to make sure the problem is not within other plugins.
5. Enable 'Accept Manual Renewals' from wp-admin > WooCommerce > Subscriptions. This is so the store can accept 'Direct bank transfer' payment for subscription product.
6. Create a 'Simple Subscription' product.
7. Try to purchase that product in an incognito mode.
8. On checkout page, input the admin's email.
9. Expect an error: 'An account is already registered with your email address. Please log in.'
10. Click on the 'Please log in' link and it will not do anything.

If 'Allow customers to log into an existing account during checkout' option is enabled from wp-admin > WooCommerce > Accounts & Privacy, clicking the 'Please log in' link will show a login form.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://fit-vampire.jurassic.ninja
Site address (URL): https://fit-vampire.jurassic.ninja
WC Version: 6.5.1
REST API Version: ✔ 6.5.1
WC Blocks Version: ✔ 7.4.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.53 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.29
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.1
WC Database Prefix: wp_
Total Database Size: 3.78MB
Database Data Size: 2.31MB
Database Index Size: 1.47MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.38MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 1
product: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

Companion Plugin: by Osk – 1.26
WooCommerce Subscriptions: by WooCommerce – 4.3.0
WooCommerce: by Automattic – 6.5.1

### Inactive Plugins (1) ###

WooCommerce Payments Dev Tools: by Automattic –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://fit-vampire.jurassic.ninja
Subscription Statuses: –
WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Payment Gateway Support ###

Direct bank transfer: products

### Action Scheduler ###

Complete: 7
Oldest: 2022-05-31 01:00:16 +0000
Newest: 2022-05-31 01:00:16 +0000

### Status report information ###

Generated at: 2022-05-31 01:35:01 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ABooooo** [comment] 2022-08-25 10:03
I am having the same issue. Is there any update on this?

**Comment by askwpgirl** [comment] 2022-11-01 01:59
The login link actually does do something, and the issue is unrelated to the plugins mentioned above. This happens with all installations of WooCommerce with Storefront and any number of themes.

To reproduce:

1. Create a user in WordPress. 
2. Log out of WordPress.
3. Attempt to place an order and checkout with the user email added for the user in step 1.
4. The "An account already exists for this email address" error displays. Click Login.
5. The page remains static, so you will not see the login fields above toggle open.

Here is a Loom. 

For my clients, I have edited the translation for this text to instruct the user to "login in above" and removed the link, so we don't lose conversions. This bug has been around long enough, I think it ought to be fixed. 

https://www.loom.com/share/787e57902480404998078df9c2ae22cc

**Comment by followluckycharm** [comment] 2022-11-21 02:32
I'm having this same issue as well and it's affecting customers. Any updates?

**Comment by askwpgirl** [comment] 2022-11-22 20:16
> I'm having this same issue as well and it's affecting customers. Any updates?

My sense is that it is not seen as an issue, so may take a lot of people commenting to get them to fix it. I'll see if I can come up with some javascript to use in the meantime to get the scroll up the page to work when that link is clicked.

**Comment by followluckycharm** [comment] 2022-11-24 09:27
> 

Have you opened a support ticket on the Wordpress Plugins page for Woocommerce? Maybe we can make some noise over there as well. :). https://wordpress.org/support/plugin/woocommerce/

**Comment by ABooooo** [comment] 2022-11-24 09:40
> My sense is that it is not seen as an issue, so may take a lot of people commenting to get them to fix it. I'll see if I can come up with some javascript to use in the meantime to get the scroll up the page to work when that link is clicked.

Your sense is correct. :) Unfortunately I've learnt that there are many such issues that Woocommerce doesn't consider as an issue. I've solve it with overwriting the link. It is not optimal but it's working.

**Comment by peterfabian** [comment] 2023-03-20 09:47
Hi, sorry for the late response and thank you for reporting the problem. Clicking this link should reveal the login form as you can see in the screen recording below, but it's above the error message, so it can easily be missed that this is happening. Additionally, it may not work universally in all themes. 


https://user-images.githubusercontent.com/2207451/226303118-014a4696-78d2-4b7a-bd84-eaed2f7552ef.mov

Can you please confirm if you see the same as me in the video above or if the link doesn't do anything at all? Thanks!

For now, I'm assigning high priority as this affects checkout and potentially conversion rates. 

Side note: I think the guest checkout must be disabled for this message to show up.

**Comment by ABooooo** [comment] 2023-03-20 16:41
Hi Peter, thank you for your reply. As I've written above, it is solved for now. I cannot tested it anymore, as it was a customer project and it is already closed. But I'll pay attention on this if the issue occur once again.

**Comment by askwpgirl** [comment] 2023-03-20 17:27
Hi @peterfabian  - the ONLY way to see the login is to scroll back up, which is not going to occur to anyone. Even in your video, you scrolled up first. Normal people aren't going to scroll up then click the link or scroll up after clicking the link. This makes this still a high priority problem to be fixed. I hope this can be finally fixed. It shouldn't be a hard fix.

**Comment by rrennick** [comment] 2023-10-17 19:02
This is a duplicate of #32072.

**Closed as completed by rrennick** 2023-10-17 19:02 UTC
Labels: Bug, Checkout, plugin: woocommerce, Rubik

**Comment by mjpennerconsulting** [comment] 2024-08-29 00:03
I too am experiencing a dead login link at the end of the message. Nothing shows up to scroll to at all. Clicking on the "Please Login" link does nothing. It behaves this way in Chrome and FireFox latest versions on a Windows 10 machine. Thanks!
