### ISSUE TITLE
Super slow WooCommerce - transient_timeout_wc

### ISSUE THREAD

**Issue by sixfootjames** [woothemes/woocommerce#9963] opened 2016-01-05 14:41 UTC
After an update about a month ago, we've started experiencing very slow page loads. I've taken the following steps:

- deactivated all the plugins
- introduced them one by one
- figured out it is WooCommerce
- installed Query Monitor
- tried to isolate the problem further
  - it seems this slowness happens on product pages that have not been loaded before. Some kind of caching issue?
- taken screenshots and attached below

I am at a loss as to what to do next and would appreciate some insight on this please.

http://shop.fairycaravan.co.za/

![capture](https://cloud.githubusercontent.com/assets/980759/12117580/5a816cca-b3ca-11e5-8f0a-a7de70bd2ac6.png)

![capture](https://cloud.githubusercontent.com/assets/980759/12118051/0c695a68-b3cd-11e5-9da6-b23135545336.png)

![capture](https://cloud.githubusercontent.com/assets/980759/12118197/c1e5eb5e-b3cd-11e5-85e8-1c552cf46c84.png)

**Comment by mikejolley** [comment] 2016-01-05 15:13
I'd suggest you read the dev blog/past issues r/e transient performance instead of opening new issues. https://woocommerce.wordpress.com/ We've addressed them in 2.5. There are tools to clear transients in WC > System Status you can use for the time being.

Also bare in mind, the slow cron job could quite easily be a plugin that relies on WooCommerce - when you de-activate core, all plugins that rely on core will also stop loading.

Since this is not a bug report, and transients have been covered elsewhere (dev blog and in the upcoming 2.5 update) I'm closing this issue.

https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

**Closed by mikejolley** 2016-01-05 15:13 UTC

**Comment by sixfootjames** [comment] 2016-01-05 18:47
Many thanks Mike. First time I've come across this and was not sure what Transients were until today.
Cheers!

**Comment by sixfootjames** [comment] 2016-02-23 13:45
Hi Mike,

We have now done everything we can including an update of WooCommerce.

If we switch off WooCommerce, the site runs perfectly fine and when we switch it on, the problems are back.

We have used the Clear Transient tool and we have implemented a cronjob script given to us by a guy who struggled with this for 3 months.

Is there anything else we can try that we're not aware of?

**Comment by mikejolley** [comment] 2016-02-23 13:50
> We have used the Clear Transient tool and we have implemented a cronjob script given to us by a guy who struggled with this for 3 months.

What is that?

**Comment by sixfootjames** [comment] 2016-02-23 13:53
This came after your suggestions to use the tool built into Woo

`<?php
​
require_once('wp-load.php');
​
global $wpdb;
$wpdb->show_errors();
​
if( $wpdb->query("DELETE FROM " . $wpdb->options . " WHERE option_name LIKE ('%\_transient\_%')") ){
	$msg =  "[" . date('Y-m-d H:i:s') . "] [Success] Transients removed successfully\r\n";
	echo $msg;
	$fhandle = fopen('./transients.log', 'a+');
	fwrite($fhandle, $msg);
	fclose($fhandle);
}else{
	$msg = "[" . date('Y-m-d H:i:s') . "] [Error] Error cleaning transients\r\n";
	$fhandle = fopen('./transients.log', 'a+');
	fwrite($fhandle, $msg);
	fclose($fhandle);
	echo $msg;
}
​
?>`

**Comment by sixfootjames** [comment] 2016-02-29 13:14
Hi Mike,
You have any news on this for us please?

**Comment by mikejolley** [comment] 2016-02-29 13:23
If transients are clear, and all old woocommerce_sessions are clear (this was in options table), optimise your tables. There is no other reason update_metadata would be slow - its a core WP function, not a WC specific function.
