### ISSUE TITLE
404 triggered when checkout has invalid custom fields

### ISSUE THREAD

**Issue by marcusforsberg** [woothemes/woocommerce#8724] opened 2015-08-05 09:40 UTC
Hello! I was sent here from the support team. :)

My company is currently integrating Woocommerce in to a large client's WordPress site. Woocommerce will not be used as an e-commerce platform per say, but rather as a way to pre-order products which will be delivered to a port of the customer's choice. Hence, we have no need for any of the default fields in Woocommerce's checkout, neither billing nor shipping. 

Using [these instructions](http://docs.woothemes.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/ ), we have removed all default fields and added our own. We also added back the two fields called billing_email and billing_phone but with our own classes.

This works fine when submitting through AJAX, but for non-JS use, weird things start to happen. 

All of our custom fields are set to be required, and the AJAX submit validates them correctly. However, for the normal submit, the POST request to /checkout returns a 404 if any field is invalid. If all fields are OK, or there are no required fields in the form, everything works. The terms and conditions checkbox also triggers this - if it's not checked, we get a 404. If the page is reloaded, the checkout form, now empty, shows up again with all the appropriate error messages; so the validation does seem to work.

I googled for a bit and noticed similar, unsolved 404 issues from several years back but nothing that was too specific. We're hoping this may give you a little more to go on. While we understand you do not give support for customised installations, we believe this is a bug and would like to help you in any possible way to get it fixed.

Please let me know what we can provide to help you fix this issue, if at all possible.

Thank you!

**Comment by marcusforsberg** [comment] 2015-08-05 09:42
In terms of code, we use the filters in the article I mentioned, only we actually replace all the default fields like so:

``` php
function woocommerce_custom_checkout_fields($fields) {
	global $custom_woocommerce_fields;

	return array(
		'billing' => $custom_woocommerce_fields,
	);
}
```

$custom_woocommerce_fields is just a simply array with fields, including the re-added billing_phone and billing_email.

**Comment by mikejolley** [comment] 2015-08-05 12:47
Rather than have us try to replicate without it, can you send the code you're using for your custom fields?

**Comment by DavidAnderson684** [comment] 2015-08-05 20:16
Have you got mod_security installed on your webserver? This can be configured to send a 404 back for any error condition, or any condition at all that its multitude of filters detects, thus masking the true problem (or, if it's just a mod_security filter, being the true problem).

**Comment by marcusforsberg** [comment] 2015-08-10 07:05
@DavidAnderson684 I thought this would be it when I saw your comment, but it turns out we don't have mod_security running on this server.

@mikejolley 

```php
// Custom Woocommerce checkout fields instead of the default ones
// See http://docs.woothemes.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/
// for how this stuff works
$custom_woocommerce_fields = array(
	'name' => array(
		'type' => 'text',
		'label' => 'Name',
	  	'required' => true,
		'input_class' => array('required'),
		'custom_attributes' => array('required' => 'required'),
	),

	'billing_email' => array(
		'type' => 'text',
		'label' => 'E-mail address',
		'required' => true,
		'input_class' => array('required'),
		'custom_attributes' => array('required' => 'required'),
	),

	'billing_phone' => array(
		'type' => 'text',
		'label' => 'Phone Number',
		'required' => true,
		'input_class' => array('required'),
		'custom_attributes' => array('required' => 'required'),
	),

	'booking_number' => array(
		'type' => 'text',
		'label' => 'Booking number',
		'required' => true,
		'input_class' => array('required'),
		'custom_attributes' => array('required' => 'required'),
	),

	'port' => array(
		'type' => 'radio',
		'label' => 'Port',
		'required' => true,
		'input_class' => array('required'),
		'custom_attributes' => array('required' => 'required'),
		'options' => array(
			'port 1, day' => 'Port 1 at 13:00',
			'port 2, day' => 'Port 2 at 14:00',
			'port 1, evening' => 'Port 1 at 19:00',
			'port 2, afternoon' => 'Port 2 at 16:00', 
		)
	),

	'travel_date' => array(
		'type' => 'text',
		'placeholder' => 'dd.mm.yyyy',
		'label' => 'Travel Date',
		'required' => true,
		'input_class' => array('woo-travel-date date-mindate required'),
		'custom_attributes' => array('required' => 'required'),
	),

	'car_registration' => array(
		'type' => 'text',
		'label' => 'Car registration',
		'required' => true,
		'input_class' => array('required'),
		'custom_attributes' => array('required' => 'required'),
	),

	'car_make_color' => array(
		'type' => 'text',
		'label' => 'Make and Colour',
		'required' => true,
		'input_class' => array('required'),
		'custom_attributes' => array('required' => 'required'),
	),
);

// Add custom Woocommerce fields to checkout page
add_filter('woocommerce_checkout_fields' , 'woocommerce_custom_checkout_fields');

function woocommerce_custom_checkout_fields($fields) {
    global $custom_woocommerce_fields;

    return array(
        'billing' => $custom_woocommerce_fields,
    );
}

// Validate custom Woocommerce fields
add_action('woocommerce_checkout_process', 'woocommerce_custom_checkout_fields_process');

function woocommerce_custom_checkout_fields_process() {
	// Date needs custom validation
	if(!empty($_POST['travel_date'])) {
		$hours = (int) get_option('woocommerce_order_time_limit');

		if(strtotime($_POST['travel_date']) - time() < $hours * 3600) {
			wc_add_notice(
					sprintf('Please place your order at least %s hours before travelling.'),
						'<strong>' . $hours . '</strong>'
					), 'error'
			);
		}
	}
}

// Save the custom Woocommerce fields with the order
add_action('woocommerce_checkout_update_order_meta', 'woocommerce_custom_checkout_fields_save');

function woocommerce_custom_checkout_fields_save($order_id) {
	global $custom_woocommerce_fields;

	foreach($custom_woocommerce_fields AS $key => $field) {
		$value = trim($_POST[$key]);
		if (!empty($value)) {
			update_post_meta($order_id, $key, sanitize_text_field($value));
		}
	}
}
```

**Comment by mikejolley** [comment] 2015-08-10 09:06
With your code, after fixing it, I had no 404. I think you're simply running into an error caused by your code.

This line:

`
 wc_add_notice(
                    sprintf('Please place your order at least %s hours before travelling.'),
                        '<strong>' . $hours . '</strong>'
                    ), 'error'
            );
`

Contains invalid syntax and causes a fatal error.

`wc_add_notice( sprintf( 'Please place your order at least %s hours before travelling.', '<strong>' . $hours . '</strong>' ), 'error' );`

Ensure you test with WP_DEBUG on because there are also notices.

Closing as this isn't a core issue.

**Closed by mikejolley** 2015-08-10 09:06 UTC
Labels: Needs Reporter Feedback

**Comment by marcusforsberg** [comment] 2015-08-10 11:45
That syntax error isn't present in our actual code, it was just a mistake I made when I removed the translation to avoid disclosing the client name. The code we run is otherwise identical to what I posted and free of (syntax) errors on our side.

**Comment by mikejolley** [comment] 2015-08-10 12:55
@marcusforsberg to test I simply added novalidate to the DOM and posted the form. It showed the missing field notices.

**Comment by marcusforsberg** [comment] 2015-08-11 08:01
@mikejolley After some more debugging, we finally found the cause of this. Notice that the first field in my code is called "name" which is a no-no (I feel I should have known this! ;)) and apparently caused the 404. Could this be browser-specific since it worked for you...?
