### ISSUE TITLE
Missing file after update

### ISSUE THREAD

**Issue by mattiabf** [woothemes/woocommerce#38601] opened 2023-06-04 09:31 UTC
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello,

after updating woocommerce I get this fatal error:

E_COMPILE_ERROR on line 242 of /wp-content/plugins/woocommerce/includes/wccom-site/class-wc-wccom-site.php. 

require_once(): Failed opening required '/wp-content/plugins/woocommerce/includes/wccom-site/rest-api/class-wc-rest-wccom-site-installer-errors.php'

The problem is: the file woocommerce is searching is called class-wc-rest-wccom-site-installer-errorS.php, while the file present in such folder is named  class-wc-rest-wccom-site-installer-error.php ("error" without the final "S").

There must be some spelling mistake somewhere, I think it is an easy bug to fix.

Please try to solve it

### Expected behavior

It should update without errors

### Actual behavior

Fatal error

### Steps to reproduce

-

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by psealock** [comment] 2023-06-15 21:28
Thanks @mattiabf, which version of WC do you have? In the latest branch I'm seeing the file referenced correctly:

https://github.com/woocommerce/woocommerce/blob/d51f69d2d712554a6f80de075e50a29553297ba3/plugins/woocommerce/includes/wccom-site/class-wc-wccom-site.php#L223

**Comment by mattiabf** [comment] 2023-06-15 21:30
I have 7.6.0, trying to update to 7.8

**Comment by psealock** [comment] 2023-06-15 21:39
Ok, right I see the incorrect spelling in the 7.6 branch. Hopefully the update works for you

https://github.com/woocommerce/woocommerce/blob/c3ed022e7ebfd39712d6cf760901cc791e6b78b0/plugins/woocommerce/includes/wccom-site/class-wc-wccom-site.php#LL242C44-L242C44

**Comment by mattiabf** [comment] 2023-06-16 05:52
The problem is:while updating to 7.8 I get the email from wordpress that something is wrong with my site, which enters in recovery mode. Do you think I should update it anyway? Would it be better to tweak the code manually before updating in order to avoid the error?

**Comment by samueljseay** [comment] 2023-06-22 08:35
Hi @mattiabf it's hard to know exactly what your new issue is, I suggest either:

1. Raise a [new issue](https://github.com/woocommerce/woocommerce/issues/new/choose) describing your problem with updating to 7.8 and steps to reproduce so we can investigate. (Don't forget to include details of your WC version, installed plugins etc in the issue description).

2. Or if you need support you could [open a support ticket](https://woocommerce.com/my-account/create-a-ticket/)

For this issue I'm thinking it makes sense to close since it's resolved in 7.8 but please feel free to reopen if you feel that is a mistake.

**Closed as completed by samueljseay** 2023-06-22 08:35 UTC
Labels: Bug, needs: triage feedback, type: community contribution
