### ISSUE TITLE
Duplicate priceSpecification throwing error in google search console

### ISSUE THREAD

**Issue by stephenblender** [woothemes/woocommerce#34826] opened 2022-09-24 16:01 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Beginning september 15th google search console started flagging some products schema _Invalid value in field "priceSpecification" (in "offers")_. In their docs google specifies "If you choose to use both offers.price and offers.priceSpecification properties, and there's a conflict between the two (for example, a different price or priceCurrency), Google will use the price information that's provided at the offers.price level." ([doc](https://developers.google.com/search/docs/appearance/structured-data/product)). 
Seems to be occurring for simple products only and not for variations.

If I remove the priceSpecification the error resolves.
`
add_filter( 'woocommerce_structured_data_product', 'nt_woocommerce_structured_data_product_offer', 10, 2 );
function nt_woocommerce_structured_data_product_offer( $markup, $product ) {
unset($markup['offers'][0]['priceSpecification']);
return $markup;
}
`

### Expected behavior

If working to meet Googles specification _price_ and _priceSpecification_ should not be together in offers.

### Actual behavior

Note price is included generally in the offer along with a _priceSpecification_.
`"offers":[{
"@type":"Offer",
"price":"27.50",
"priceValidUntil":"2023-12-31",
"priceSpecification":{"price":"27.50","priceCurrency":"USD","valueAddedTaxIncluded":"false"},
"priceCurrency":"USD","availability":"http:\/\/schema.org\/OutOfStock","url":"https:\/\/vitaminb12direct.com\/product\/syringes-30-gauge-x-5-16-monoject\/",
"seller":{"@type":"Organization","name":"Vitamin B12 Direct","url":"https:\/\/vitaminb12direct.com"}
}]`

### Steps to reproduce

<img width="1224" alt="Screen Shot 2022-09-24 at 8 52 11 AM" src="https://user-images.githubusercontent.com/3494902/192107266-6c74f2be-cae5-4ed1-9856-8eb55a9ddb12.png">

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment] 2022-09-26 18:53
Hi @stephenblender,

Thanks for the report. Can you please reply with information from your System Status Report? You can find the system status report from **WooCommerce > System Status** in WordPress admin. Click on "Get system report", and then "Copy for Support" and paste the results in a reply to this issue. Without the System Status Report, we will be unable to attempt to reproduce this issue.

**Comment by jonathansadowski** [comment] 2022-09-27 15:16
Thanks again for the report. I'm closing this in favor of #34851, which is a duplicate of this issue.

**Closed as completed by jonathansadowski** 2022-09-27 15:16 UTC
Labels: Bug, needs: author feedback, plugin: woocommerce
