### ISSUE TITLE
Version 6.4.0 - 7.1.0 (potentially any 6-7 updates) - New Zealand Region Shipping issue breaking websites. 

### ISSUE THREAD

**Issue by brettnzl** [woothemes/woocommerce#35562] opened 2022-11-14 02:13 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi, Since the version 7.1.0  update we have noticed on a number of our eCommerce sites that the shipping breaks for New Zealand regions. if you have a look below you can see the before and after updates. 

This is causing no shipping to be found at checkouts. 

**Before update (example 6.4.0): **
![wc-1](https://user-images.githubusercontent.com/13056905/201560159-bc874ed9-946b-4373-a13e-fbc3edeb1e00.png)

**After update (example 7.1.0): **
![wc-1-after](https://user-images.githubusercontent.com/13056905/201560200-7410fff8-7a1a-4d57-a87d-ddbc5a9c5f59.png)

I've had a look in the database and can see that in particular for New Zealand the region codes have changed from 2 char to 3 char. 

**Shipping zones from another site after update: ** 
<img width="295" alt="db1" src="https://user-images.githubusercontent.com/13056905/201560373-808d6314-d9cd-413a-8096-a1c01b16eb20.png">

**Region for v 6.4, or pre-update, and post-update**
<img width="304" alt="db2" src="https://user-images.githubusercontent.com/13056905/201560422-eeefe626-9d6e-4475-9f0d-7ac8934b3e74.png">

**I then re-added the same regions back in and can see that the codes have changed:**
<img width="302" alt="db3" src="https://user-images.githubusercontent.com/13056905/201560523-2c30579c-7660-4f07-999b-2330a3704544.png">

The update doesn't seem to update the pre-existing region codes, so when you make your update to version 7.1 the region codes still stay as 2 letters, which breaks the front-end shipping. 

### Expected behavior

When the update happens, these values should of been altered to the correct values. 

### Actual behavior

The Shipping breaks, and the admin panel gets changes from region names to a bunch of commas ",,,,,," see description and images.

### Steps to reproduce

- Add some New Zealand regions for shipping on a version of wooCommerce - v 6.4 or potentially another 
- Update the plugin to 7.1.0 
- Check the shipping regions (they will break)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.terrainindustries.co.nz
Site address (URL): https://www.terrainindustries.co.nz
WC Version: 6.4.0
REST API Version: ✔ 6.4.0
WC Blocks Version: ✔ 7.2.1
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.3.2
Log Directory Writable: ✔
WP Version: 6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_NZ
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.33
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.86.0
OpenSSL/1.1.1s

SUHOSIN Installed: –
MySQL Version: 5.7.40
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.4.0
WC Database Prefix: wp_
Total Database Size: 126.31MB
Database Data Size: 81.33MB
Database Index Size: 44.98MB
wp_woocommerce_sessions: Data: 4.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.23MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 4.52MB + Index: 5.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.72MB + Engine InnoDB
wp_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_duplicator_pro_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 1.52MB + Index: 0.17MB + Engine InnoDB
wp_gf_entry_meta: Data: 1.52MB + Index: 2.20MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.20MB + Index: 0.06MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nbanalytics: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.27MB + Index: 0.27MB + Engine InnoDB
wp_postmeta: Data: 18.55MB + Index: 21.06MB + Engine InnoDB
wp_posts: Data: 4.52MB + Index: 1.39MB + Engine InnoDB
wp_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_view: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_lead: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_rg_lead_detail: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.19MB + Index: 0.13MB + Engine InnoDB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 7.52MB + Index: 7.03MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 0.73MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.25MB + Index: 0.22MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.44MB + Index: 0.50MB + Engine InnoDB
wp_wc_order_stats: Data: 0.31MB + Index: 0.33MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.20MB + Index: 0.19MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.44MB + Index: 0.77MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfBlockedIPLog: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wfBlocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfConfig: Data: 2.19MB + Index: 0.00MB + Engine InnoDB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileMods: Data: 9.52MB + Index: 0.00MB + Engine InnoDB
wp_wfHits: Data: 2.02MB + Index: 0.20MB + Engine InnoDB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfKnownFileList: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfLogins: Data: 0.39MB + Index: 0.16MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfNotifications: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfStatus: Data: 0.19MB + Index: 0.13MB + Engine InnoDB
wp_wfTrafficRates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 2.03MB + Index: 0.14MB + Engine InnoDB
wp_yoast_indexable: Data: 4.52MB + Index: 1.17MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.11MB + Index: 0.16MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.33MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 48
acf-field-group: 8
attachment: 1062
nav_menu_item: 13
oembed_cache: 10
page: 19
post: 16
product: 695
product_variation: 2241
revision: 428
shop_coupon: 2
shop_order: 3411

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Gravity Forms: by Gravity Forms – 2.6.1
Advanced Custom Fields: Gravity Forms Field: by @adam_pope of @stormuk – 1.0.0
Admin Menu Tree Page View: by Ciprian Popescu – 2.7.7
Advanced Custom Fields PRO: by Delicious Brains – 5.12.2
Classic Editor: by WordPress Contributors – 1.6.2
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.4
MonsterInsights - eCommerce Addon: by MonsterInsights Team – 8.3.8
MonsterInsights Pro: by MonsterInsights – 8.10.1
Gravity Forms Mailchimp Add-On: by Gravity Forms – 5.0
Ninetyblack On Account Payments: by ninetyblack – 1.0
WooCommerce Admin: by WooCommerce – 3.3.2
WooCommerce Windcave Gateway: by OPMC – 4.7 (update to version 4.9 is available)
Windcave Gateway for WooCommerce: by Windcave – 1.1.5
WP WooCommerce Mailchimp: by Saint Systems – 2.4.9
WooCommerce Google Product Feed: by Ademti Software Ltd. – 10.6.0 (update to version 10.7.7 is available)
WooCommerce: by Automattic – 6.4.0 (update to version 7.1.0 is available)
Wordfence Security: by Wordfence – 7.7.1
Yoast SEO: by Team Yoast – 18.5.1
WP fail2ban: by Charles Lecklider – 4.3.0.9

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: NZD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Terrain Industrues
Version: 1.0.0
Author URL: http://ninetyblack.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: terrainindustries/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.4.0
terrainindustries/woocommerce/auth/form-grant-access.php version 2.4.0 is out of date. The core version is 4.3.0
terrainindustries/woocommerce/auth/form-login.php version 2.4.0 is out of date. The core version is 3.4.0
terrainindustries/woocommerce/cart/cart-empty.php version 2.0.0 is out of date. The core version is 3.5.0
terrainindustries/woocommerce/cart/cart-item-data.php
terrainindustries/woocommerce/cart/cart-shipping.php version 2.5.0 is out of date. The core version is 3.6.0
terrainindustries/woocommerce/cart/cart-totals.php
terrainindustries/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.8.0
terrainindustries/woocommerce/cart/cross-sells.php version 1.6.4 is out of date. The core version is 4.4.0
terrainindustries/woocommerce/cart/mini-cart.php version 2.5.0 is out of date. The core version is 5.2.0
terrainindustries/woocommerce/cart/proceed-to-checkout-button.php
terrainindustries/woocommerce/cart/shipping-calculator.php version 2.0.8 is out of date. The core version is 4.0.0
terrainindustries/woocommerce/checkout/cart-errors.php version 2.4.0 is out of date. The core version is 3.5.0
terrainindustries/woocommerce/checkout/form-billing.php version 2.1.2 is out of date. The core version is 3.6.0
terrainindustries/woocommerce/checkout/form-checkout.php version 2.3.0 is out of date. The core version is 3.5.0
terrainindustries/woocommerce/checkout/form-coupon.php version 2.2 is out of date. The core version is 3.4.4
terrainindustries/woocommerce/checkout/form-login.php version 2.0.0 is out of date. The core version is 3.8.0
terrainindustries/woocommerce/checkout/form-pay.php version 2.5.0 is out of date. The core version is 5.2.0
terrainindustries/woocommerce/checkout/form-shipping.php version 2.2.0 is out of date. The core version is 3.6.0
terrainindustries/woocommerce/checkout/payment-method.php version 2.3.0 is out of date. The core version is 3.5.0
terrainindustries/woocommerce/checkout/payment.php version 2.5.0 is out of date. The core version is 3.5.3
terrainindustries/woocommerce/checkout/review-order.php version 2.3.0 is out of date. The core version is 5.2.0
terrainindustries/woocommerce/checkout/terms.php version 2.5.0 is out of date. The core version is 3.4.0
terrainindustries/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.7.0
terrainindustries/woocommerce/content-product.php version 3.0.0 is out of date. The core version is 3.6.0
terrainindustries/woocommerce/content-single-product.php version 3.0.0 is out of date. The core version is 3.6.0
terrainindustries/woocommerce/content-widget-product.php version 2.5.0 is out of date. The core version is 3.5.5
terrainindustries/woocommerce/global/quantity-input.php version 2.5.0 is out of date. The core version is 4.0.0
terrainindustries/woocommerce/global/sidebar.php
terrainindustries/woocommerce/global/wrapper-end.php version 1.6.4 is out of date. The core version is 3.3.0
terrainindustries/woocommerce/global/wrapper-start.php version 1.6.4 is out of date. The core version is 3.3.0
terrainindustries/woocommerce/loop/add-to-cart.php version 2.5.0 is out of date. The core version is 3.3.0
terrainindustries/woocommerce/loop/loop-end.php
terrainindustries/woocommerce/loop/loop-start.php version 2.0.0 is out of date. The core version is 3.3.0
terrainindustries/woocommerce/loop/no-products-found.php
terrainindustries/woocommerce/loop/orderby.php version 2.2.0 is out of date. The core version is 3.6.0
terrainindustries/woocommerce/loop/pagination.php version 2.2.2 is out of date. The core version is 3.3.1
terrainindustries/woocommerce/loop/price.php
terrainindustries/woocommerce/loop/rating.php version 2.0.0 is out of date. The core version is 3.6.0
terrainindustries/woocommerce/loop/result-count.php version 2.0.0 is out of date. The core version is 3.7.0
terrainindustries/woocommerce/loop/sale-flash.php
terrainindustries/woocommerce/myaccount/dashboard.php version 2.6.0 is out of date. The core version is 4.4.0
terrainindustries/woocommerce/myaccount/downloads.php version 2.6.0 is out of date. The core version is 3.2.0
terrainindustries/woocommerce/myaccount/form-add-payment-method.php version 2.6.0 is out of date. The core version is 4.3.0
terrainindustries/woocommerce/myaccount/form-edit-account.php version 2.6.0 is out of date. The core version is 3.5.0
terrainindustries/woocommerce/myaccount/form-edit-address.php version 2.6.0 is out of date. The core version is 3.6.0
terrainindustries/woocommerce/myaccount/form-login.php version 2.6.0 is out of date. The core version is 4.1.0
terrainindustries/woocommerce/myaccount/form-lost-password.php version 2.6.0 is out of date. The core version is 3.5.2
terrainindustries/woocommerce/myaccount/form-reset-password.php version 2.6.0 is out of date. The core version is 3.5.5
terrainindustries/woocommerce/myaccount/lost-password-confirmation.php version 2.6.0 is out of date. The core version is 3.9.0
terrainindustries/woocommerce/myaccount/my-account.php version 2.6.0 is out of date. The core version is 3.5.0
terrainindustries/woocommerce/myaccount/my-address.php
terrainindustries/woocommerce/myaccount/my-downloads.php
terrainindustries/woocommerce/myaccount/my-orders.php
terrainindustries/woocommerce/myaccount/navigation.php
terrainindustries/woocommerce/myaccount/orders.php version 2.6.0 is out of date. The core version is 3.7.0
terrainindustries/woocommerce/myaccount/payment-methods.php
terrainindustries/woocommerce/myaccount/view-order.php version 2.6.0 is out of date. The core version is 3.0.0
terrainindustries/woocommerce/notices/error.php version 1.6.4 is out of date. The core version is 3.9.0
terrainindustries/woocommerce/notices/notice.php version 1.6.4 is out of date. The core version is 3.9.0
terrainindustries/woocommerce/notices/success.php version 1.6.4 is out of date. The core version is 3.9.0
terrainindustries/woocommerce/order/form-tracking.php version 1.6.4 is out of date. The core version is 3.6.0
terrainindustries/woocommerce/order/order-again.php version 2.3.0 is out of date. The core version is 3.5.0
terrainindustries/woocommerce/order/order-details-customer.php version 2.4.0 is out of date. The core version is 5.6.0
terrainindustries/woocommerce/order/order-details-item.php version 2.5.0 is out of date. The core version is 5.2.0
terrainindustries/woocommerce/order/order-details.php version 2.6.0 is out of date. The core version is 4.6.0
terrainindustries/woocommerce/order/tracking.php
terrainindustries/woocommerce/product-searchform.php version 2.5.0 is out of date. The core version is 3.3.0
terrainindustries/woocommerce/single-product/add-to-cart/external.php version 2.1.0 is out of date. The core version is 3.4.0
terrainindustries/woocommerce/single-product/add-to-cart/grouped.php version 3.0.7 is out of date. The core version is 4.8.0
terrainindustries/woocommerce/single-product/add-to-cart/simple.php version 3.0.0 is out of date. The core version is 3.4.0
terrainindustries/woocommerce/single-product/add-to-cart/variable.php version 3.0.0 is out of date. The core version is 6.1.0
terrainindustries/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 3.0.0 is out of date. The core version is 3.4.0
terrainindustries/woocommerce/single-product/add-to-cart/variation.php
terrainindustries/woocommerce/single-product/meta.php
terrainindustries/woocommerce/single-product/photoswipe.php
terrainindustries/woocommerce/single-product/price.php
terrainindustries/woocommerce/single-product/product-attributes.php version - is out of date. The core version is 3.6.0
terrainindustries/woocommerce/single-product/product-image.php version 3.1.0 is out of date. The core version is 3.5.1
terrainindustries/woocommerce/single-product/product-thumbnails.php version 3.1.0 is out of date. The core version is 3.5.1
terrainindustries/woocommerce/single-product/rating.php version 3.1.0 is out of date. The core version is 3.6.0
terrainindustries/woocommerce/single-product/related.php version 3.0.0 is out of date. The core version is 3.9.0
terrainindustries/woocommerce/single-product/review-meta.php version 3.0.0 is out of date. The core version is 3.4.0
terrainindustries/woocommerce/single-product/review-rating.php version 3.1.0 is out of date. The core version is 3.6.0
terrainindustries/woocommerce/single-product/review.php
terrainindustries/woocommerce/single-product/sale-flash.php
terrainindustries/woocommerce/single-product/share.php version 1.6.4 is out of date. The core version is 3.5.0
terrainindustries/woocommerce/single-product/short-description.php version 1.6.4 is out of date. The core version is 3.3.0
terrainindustries/woocommerce/single-product/stock.php
terrainindustries/woocommerce/single-product/tabs/additional-information.php
terrainindustries/woocommerce/single-product/tabs/description.php
terrainindustries/woocommerce/single-product/tabs/tabs.php version 2.4.0 is out of date. The core version is 3.8.0
terrainindustries/woocommerce/single-product/title.php
terrainindustries/woocommerce/single-product/up-sells.php
terrainindustries/woocommerce/single-product-reviews.php version 2.3.2 is out of date. The core version is 4.3.0
terrainindustries/woocommerce/single-product.php
terrainindustries/woocommerce/content-product_cat.php version 2.6.1 is out of date. The core version is 4.7.0
terrainindustries/woocommerce/taxonomy-product_cat.php version 1.6.4 is out of date. The core version is 4.7.0
terrainindustries/woocommerce/taxonomy-product_tag.php version 1.6.4 is out of date. The core version is 4.7.0

Outdated Templates: ❌
					
					
						Learn how to update

### WooCommerce Google Product Feed feeds ###

google: Google merchant centre product feed
  Type: google
  Category filter: -
  Categories: -

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send "item group ID": Enabled
Expanded schema markup: -
Debug key: c848c4c0-843f-4a2e-aaed-7eb41a55e9e2

### WooCommerce Google Product Feed fields ###

Product description: Main product description (full preferred) plus variation description
Brand: Pre-populates from brand taxonomy.
Manufacturer Part Number (MPN): Pre-populates from product sku.
Product Type: 
Google Product Category: 
Size system: 
Title: Pre-populates from product product_title.
Availability (in stock products): Defaults to "in stock".
Availability (backordered products): Defaults to "in stock".
Availability (out of stock products): Defaults to "out of stock".

### WooCommerce Google Product Feed DB status ###

Database version: 15
Active database version: 15
wc_gpf_render_cache: Empty
woocommerce_gpf_google_taxonomy (en-US): 5595 items

### Action Scheduler ###

Complete: 205
Oldest: 2022-10-14 17:37:21 +1300
Newest: 2022-11-14 15:03:49 +1300

Failed: 1
Oldest: 2022-04-13 16:14:49 +1200
Newest: 2022-04-13 16:14:49 +1200

### Status report information ###

Generated at: 2022-11-14 15:13:34 +13:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by samueljseay** [comment] 2022-11-15 00:59
Hi @brettnzl thanks for raising this. Could you confirm, I think this is a duplicate of https://github.com/woocommerce/woocommerce/issues/35535

**Comment by brettnzl** [comment] 2022-11-15 02:45
Hi @samueljseay It does look like the same symptoms, so I can assume its the same. I've just got more evidence of whats happening, via the database changes from 2 - 3 characters. 

either way we have experiences this on 3 different websites and tested specifically with the update and had the same result.

**Comment by psealock** [comment] 2022-11-20 23:33
Hey @brettnzl, thanks for raising the issue. This is indeed a duplicate of https://github.com/woocommerce/woocommerce/issues/35535. We have been able to reproduce the problem and I have escalated the issue to the development team so I will close this issue and mark it as duplicate.

**Closed as completed by psealock** 2022-11-20 23:33 UTC
Labels: Bug, needs: triage feedback, type: community contribution
