### ISSUE TITLE
[Fatal] Uncaught WC_Data_Exception: Ungültiger Produkttyp: Übergebene ID entspricht keiner Produktvariation | class-wc-product-variation-data-store-cpt.php:58

### ISSUE THREAD

**Issue by nigeljamesstevenson** [woothemes/woocommerce#51721] opened 2024-09-26 23:09 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Translation of title:
[Fatal] Uncaught WC_Data_Exception: Invalid product type: Passed ID does not correspond to a product variation | class-wc-product-variation-data-store-cpt.php:58

We observed the following fatal error in relation to WooCommerce 9.3.2 (note - this also existed in 9.2.3):

[Link to code](https://github.com/woocommerce/woocommerce/blob/4e0ebd83f4d51bdef1cd7d13c0a0047d55591d18/plugins/woocommerce/includes/data-stores/class-wc-product-variation-data-store-cpt.php#L58)

<details><summary>Stack trace</summary>
<p>

```
PHP Fatal error:  Uncaught WC_Data_Exception: Ungültiger Produkttyp: Übergebene ID entspricht keiner Produktvariation. in /.../plugins/woocommerce/9.3.2/includes/data-stores/class-wc-product-variation-data-store-cpt.php:58
Stack trace:
#0 /.../plugins/woocommerce/9.3.2/includes/class-wc-data-store.php(159): WC_Product_Variation_Data_Store_CPT->read(Object(WC_Product_Variation))
#1 /.../plugins/woocommerce/9.3.2/includes/abstracts/abstract-wc-product.php(139): WC_Data_Store->read(Object(WC_Product_Variation))
#2 /.../plugins/woocommerce/9.3.2/includes/class-wc-product-simple.php(24): WC_Product->__construct('75741')
#3 /.../plugins/woocommerce/9.3.2/includes/class-wc-product-variation.php(54): WC_Product_Simple->__construct('75741')
#4 /.../.../wp-content/plugins/bdroppy/src/Services/WooCommerce/Importer.php(888): WC_Product_Variation->__construct('75741')
#5 /.../.../wp-content/plugins/bdroppy/src/CronJob/Jobs/QueueJob.php(380): BDroppy\Services\WooCommerce\Importer->updateProductToWooCommerce(Object(stdClass), Object(BDroppy\Models\Mask\ProductMask), 1)
#6 /.../.../wp-content/plugins/bdroppy/src/CronJob/Jobs/QueueJob.php(39): BDroppy\CronJob\Jobs\QueueJob->updateMethod()
#7 /.../.../wp-content/plugins/bdroppy/src/CronJob/Jobs/BaseJob.php(41): BDroppy\CronJob\Jobs\QueueJob->handle()
#8 /.../core/6.6.2/wp-includes/class-wp-hook.php(324): BDroppy\CronJob\Jobs\BaseJob->run()
#9 /.../core/6.6.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#10 /.../core/6.6.2/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#11 /.../core/6.6.2/wp-cron.php(191): do_action_ref_array('bdroppy_queues_...', Array)
#12 {main}
  thrown in /.../plugins/woocommerce/9.3.2/includes/data-stores/class-wc-product-variation-data-store-cpt.php on line 58
``` 

</p>
</details> 

Looking at the path in the stack trace (plugins/bdroppy) - this could be related to the bdroppy plugin

### Expected behavior

We would expect a valid id to be passed i.e. based on the code  'product_variation' == $post_object->post_type

### Actual behavior

'product_variation' !== $post_object->post_type and throw new WC_Data_Exception is called

### Steps to reproduce

We don't have steps to reproduce, but observed 551 instances of this problem on Fri Sep 20, 1200 UTC to 2359 UTC on one site. Hopefully, someone can dig in and apply a defensive check if appropriate. - To be updated after investigation.

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment] 2024-10-02 13:50
This seems like a duplicate of #51208, but if I'm mistaken please do re-open.

**Closed as completed by barryhughes** 2024-10-02 13:50 UTC
Labels: Bug, Data Structure/CRUD/Backend Processing, type: fatal, env: internal
