### ISSUE TITLE
Inconsistent handling of out of stock variations when an "any" variation is present

### ISSUE THREAD

**Issue by billrobbins** [woothemes/woocommerce#30732] opened 2021-09-17 16:35 UTC
**Prerequisites (mark completed items with an [x]):**
- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
A merchant has a product with at least one attribute used for variations.  They only create variations for specific attributes that are out of stock.  The other combinations are covered by a variation that uses "any" for the attributes which is set to be in stock.

With the option to "hide out of stock items from the catalog" enabled, the out-of-stock variation appears to be "in stock" and can be purchased.

With the "hide out of stock items" option disabled, the out-of-stock variation can't be purchased.  There will be a message saying it is out of stock.  

**Expected behavior**
I expect the ability to purchase an "any" variation will be consistent regardless of the "hide out of stock items" setting.

**Actual behavior**
Out-of-stock variations can be purchased when an "any," "in-stock" variation exists and the "hide out of stock items" option is enabled.  

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a product with at least one attribute with multiple terms.  Use this attribute for variations.
2. Add a variation for "any" of the attribute.  Set it to be "in stock" and include a price.
3. Add a second variation for a specific attribute term.  Set it to "manage stock" and set the stock level to `0`.
4. Publish the product.  
5. Now go to WooCommerce > Settings > Products > Inventory and check the box to "hide out of stock items from the catalog."
6. View the product.  Notice how the "out of stock" variation can be added to the cart and purchased.
7. Disable the "hide out of stock items from the catalog" setting.  
8. Go back to the product and notice how the same variation can no longer be purchased.

**Screenshots**

Product attributes
![attributes](https://user-images.githubusercontent.com/1138631/133821335-ac3b6bc4-bc40-4b3e-bb5b-894e631726a5.png)

The "any" variation
![any-variation](https://user-images.githubusercontent.com/1138631/133821348-61b9a2e4-c899-42db-b9c2-b83333ba4d29.png)

The "out of stock" variation"
![out-of-stock-variation](https://user-images.githubusercontent.com/1138631/133821439-b8fbb795-2a42-4e1a-a843-b95af05e535c.png)

Hid out of stock enabled -- variation can be purchased
![out-of-stock-can-be-purchased](https://user-images.githubusercontent.com/1138631/133821466-e38b8fbc-956f-48ea-acf2-0e07e212136b.png)

Hide out of stock disabled -- variation can't be purchased
![out-of-stock-unavailable](https://user-images.githubusercontent.com/1138631/133821481-4a1bf273-5004-4472-b617-a5df4a53d83b.png)

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

<details>
```
### WordPress Environment ###

WordPress address (URL): http://quick.local
Site address (URL): http://quick.local
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.4.1
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 5.7.28
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: wp_
Total Database Size: 10.61MB
Database Data Size: 6.05MB
Database Index Size: 4.56MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_posts: Data: 0.42MB + Index: 0.14MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 272
customize_changeset: 1
page: 7
post: 2
product: 90
product_variation: 281

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (3) ###

Code Snippets: by Code Snippets Pro – 2.14.2
WooCommerce: by Automattic – 5.6.0
WP phpMyAdmin: by Puvox.software – 5.1.1.05

### Inactive Plugins (1) ###

WooCommerce One Page Checkout: by Automattic – 1.8.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.8.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 167
Oldest: 2021-09-16 17:39:52 +0000
Newest: 2021-09-17 16:16:22 +0000


### Status report information ###

Generated at: 2021-09-17 16:31:16 +00:00
```
</details>

**Comment by mouligreenlaw** [comment] 2021-09-23 03:55
This report was from this ticket:
4269261-zen

**Comment by rodelgc** [comment] 2021-09-24 09:08
Hi @billrobbins,

Thank you for bringing this issue to our attention. I can reproduce the issue except for this step:

> Go back to the product and notice how the same variation can no longer be purchased.

In my test, I was still able to add the "out of stock" variation after unchecking the "Hide out of stock" option in the Product Settings.

Here are the screenshots of my test using WC 5.6.0 and the Twenty Twenty-One theme:

The setup I used in the "any" and "out of stock" variations:

<img width="801" alt="Screen Shot 2021-09-24 at 4 54 25 PM" src="https://user-images.githubusercontent.com/4509348/134648983-3cbd3896-be84-4f43-b815-c0eee34d2bbc.png">
<img width="816" alt="Screen Shot 2021-09-24 at 4 54 36 PM" src="https://user-images.githubusercontent.com/4509348/134648997-477a076b-c379-4ad3-bad7-8e5f34db3f97.png">

Afterwhich, I was able to add the "out of stock" variation to the cart whether or not the "Hide out of stock" option was checked or unchecked:

<img width="1390" alt="Screen Shot 2021-09-24 at 4 58 12 PM" src="https://user-images.githubusercontent.com/4509348/134649185-564693df-e7d8-4fdd-8f00-e514cfa6cd8c.png">

Priority of this issue will be assigned shortly after we'd go through a round of prioritization. Please note it may take a couple of days.

**Comment by rrennick** [comment] 2023-11-23 20:28
Closing as a duplicate of #33588.

**Closed as completed by rrennick** 2023-11-23 20:28 UTC
Labels: Bug, plugin: woocommerce
