### ISSUE TITLE
Bugs after update!

### ISSUE THREAD

**Issue by Bels12345** [woothemes/woocommerce#47952] opened 2024-05-29 12:24 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I use woocommerce only as a showroom, not as a shop.
I have tese issues after the latest update
1. Product Editing page is loading very slowly. It takes almost 30 sec to load every time
2. Description edit in full editor doesn't work properly. Undo button doesn't work, also can't use "Ctrl+Z

### Expected behavior

I expected that the new upgrade will work properly!

### Actual behavior

Editing is very slow and impossible to make changes due to "undo button" missfunctiality.

### Steps to reproduce

Тhis is editing page waiting to load for 30-40 sec.  
![2024-05-29 14_58_55-‹ Белс](https://github.com/woocommerce/woocommerce/assets/171143980/016be7df-94a6-43c3-ba1a-dec6b21ffab7)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://bels-bg.com
Site address (URL): https://bels-bg.com
WC Version: 8.9.1
REST API Version: ✔ 8.9.1
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.18
PHP Post Max Size: 200 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 8.7.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.18-MariaDB-log
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.9.1
WC Database Prefix: wpgy_
Total Database Size: 45.89MB
Database Data Size: 42.73MB
Database Index Size: 3.16MB
wpgy_woocommerce_sessions: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wpgy_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_actionscheduler_actions: Data: 0.05MB + Index: 0.03MB + Engine MyISAM
wpgy_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpgy_actionscheduler_logs: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wpgy_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_comments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_e_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_jetpack_sync_queue: Data: 1.88MB + Index: 0.03MB + Engine MyISAM
wpgy_jetpack_waf_blocklog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_options: Data: 3.94MB + Index: 0.15MB + Engine MyISAM
wpgy_postmeta: Data: 23.90MB + Index: 0.57MB + Engine MyISAM
wpgy_posts: Data: 11.33MB + Index: 0.22MB + Engine MyISAM
wpgy_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpgy_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpgy_term_relationships: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wpgy_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpgy_trp_dictionary_bg_bg_en_gb: Data: 0.21MB + Index: 0.49MB + Engine MyISAM
wpgy_trp_dictionary_en_us_bg_bg: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wpgy_trp_gettext_bg_bg: Data: 0.36MB + Index: 0.49MB + Engine MyISAM
wpgy_trp_gettext_en_gb: Data: 0.17MB + Index: 0.33MB + Engine MyISAM
wpgy_trp_gettext_en_us: Data: 0.11MB + Index: 0.19MB + Engine MyISAM
wpgy_trp_gettext_original_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_trp_gettext_original_strings: Data: 0.23MB + Index: 0.22MB + Engine MyISAM
wpgy_trp_original_meta: Data: 0.08MB + Index: 0.10MB + Engine MyISAM
wpgy_trp_original_strings: Data: 0.19MB + Index: 0.16MB + Engine MyISAM
wpgy_usermeta: Data: 0.10MB + Index: 0.01MB + Engine MyISAM
wpgy_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpgy_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
wpgy_wc_admin_note_actions: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wpgy_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_wc_orders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_wc_orders_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_wc_order_addresses: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_wc_order_operational_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_wc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpgy_wc_product_meta_lookup: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wpgy_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpgy_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_wpc_accesslocks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpgy_wpc_login_fails: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 427
e-landing-page: 8
elementor_library: 5
faqs: 22
gallery: 3
jetpack_migration: 2
language_switcher: 4
mc4wp-form: 1
nav_menu_item: 55
page: 31
post: 6
product: 78
revision: 1454
service: 7
team: 8
wpcf7_contact_form: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (8) ###

Contact Form 7: by Takayuki Miyoshi – 5.9.4
Jetpack: by Automattic – 13.4
MC4WP: Mailchimp for WordPress: by ibericode – 4.9.13
Organiqo Plugin: by Template Path – 1.0
TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.7.6

UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.24.3

WooCommerce: by Automattic – 8.9.1
W3 Total Cache: by BoldGrid – 2.7.2

### Inactive Plugins (2) ###

Elementor: by Elementor.com – 3.20.4
Royal Elementor Addons: by WP Royal – 1.3.97

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: db.php
object-cache.php: object-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: BGN (лв.)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 143 KB

### WC Pages ###

Shop base: #9 - /products/
Cart: ❌ Page ID is set
but the page does not exist

Checkout: ❌ Page ID is set
but the page does not exist

My account: ❌ Page ID is set
but the page does not exist

Terms and conditions: ❌ Page not set

### Theme ###

Name: Organiqo Child
Version: 1.5
Author URL: 
Child Theme: ✔
Parent Theme Name: Organiqo
Parent Theme Version: 1.5
Parent Theme Author URL: http://themeforest.net/user/yogsthemes
WooCommerce Support: ✔

### Templates ###

Overrides: organiqo/woocommerce/archive-product.php version 3.6.0 is out of date. The core version is 8.6.0
organiqo/woocommerce/cart/cart-totals.php
organiqo/woocommerce/cart/cart.php version 3.8.0 is out of date. The core version is 7.9.0
organiqo/woocommerce/checkout/form-checkout.php
organiqo/woocommerce/checkout/payment.php version 3.5.3 is out of date. The core version is 8.1.0
organiqo/woocommerce/content-product.php
organiqo/woocommerce/content-single-product.php
organiqo/woocommerce/loop/loop-end.php
organiqo/woocommerce/loop/loop-start.php
organiqo/woocommerce/product-searchform.php version 3.6.0 is out of date. The core version is 7.0.1
organiqo/woocommerce/single-product/add-to-cart/external.php version 3.4.0 is out of date. The core version is 7.0.1
organiqo/woocommerce/single-product/add-to-cart/grouped.php version 4.8.0 is out of date. The core version is 7.0.1
organiqo/woocommerce/single-product/add-to-cart/simple.php version 3.4.0 is out of date. The core version is 7.0.1
organiqo/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 3.4.0 is out of date. The core version is 7.0.1
organiqo/woocommerce/single-product/related.php
organiqo/woocommerce/single-product/tabs/tabs.php
organiqo/woocommerce/single-product/title.php
organiqo/woocommerce/single-product.php
organiqo/woocommerce/taxonomy-product_cat.php

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-29 12:39:34 +03:00
Options: ✔
Notes: 126
Onboarding: completed

### Action Scheduler ###

Complete: 69
Oldest: 2024-04-29 03:15:39 +0300
Newest: 2024-05-29 14:32:47 +0300

Failed: 62
Oldest: 2023-05-16 15:40:43 +0300
Newest: 2024-05-19 16:22:45 +0300

Pending: 2
Oldest: 2024-05-29 20:20:37 +0300
Newest: 2024-05-30 11:36:47 +0300

### Status report information ###

Generated at: 2024-05-29 15:21:37 +03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by Bels12345** [comment] 2024-05-30 08:44
I found another bug!!! I can't use pictures from my gallery. I have to upload directly from my computer. I am not sure if this is real bug, but I don't like it

**Comment by kmanijak** [comment] 2024-08-16 12:41
Hi @Bels12345, I appreciate you raised this issue!

Sorry, you experienced some troubles with the new product editor. It's been a couple of months and couple of WooCommerce versions since the issue was raised. I think product editor is loading much faster now (couldn't experience 30-40s loading). I also verified that undo/CTRL-Z works properly in product description editing.

> I can't use pictures from my gallery. I have to upload directly from my computer. I am not sure if this is real bug, but I don't like it

This cannot be reproduced in the current version as well and you can add/edit images from your Media Library. 🙌 

![Image](https://github.com/user-attachments/assets/f55fc793-6eb8-4daa-9acd-6e38517b67a6)

Do you mind giving a try with WooCommerce 9.1.4? The issues should not be reproducible anymore and to keep the backlog clean I'd go ahead and close this one. But in case you still _can_ reproduce some of them in 9.1.4, the closed issues still can be commented on so give us a shout, please! Thank you!

**Closed as completed by kmanijak** 2024-08-16 12:41 UTC
Labels: Bug, Product/Inventory Management, type: community contribution, Kirigami
