### ISSUE TITLE
Stock management: Stock not being held when orders Pending Payment with PayPal or Stripe

### ISSUE THREAD

**Issue by pauljacobson** [woothemes/woocommerce#31551] opened 2022-01-04 07:34 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

A merchant noticed that they had multiple transactions for a single product within a 10 minute time period. It seems that the stock is not being reduced when the order status is _Pending Payment_, although in at least one case it is reduced despite payment failing.

The result seems to be unexpected and inappropriate stock reductions.

In other words, stock management is failing, and the merchant finds themselves overselling products.

This issue seems to be related to #30348 except this affects both Stripe and PayPal processing.

Our ticket is 4642984-zen

### Expected behavior

Stock should be reduced when an order is _Pending Payment_

### Actual behavior

Stock is not being reduced when an order is _Pending Payment_, with the result that stock levels are not being adjusted based on orders received taking into account the payment status.

### Steps to reproduce

At some stage, the stock was reduced to `-1` after a customer's payment intent was processed, as you can see here:

<img width="1076" alt="4642984_stock_reduction" src="https://user-images.githubusercontent.com/2912202/148023086-3b5b468d-1f5b-4ece-a73d-b1b533d57470.png">

During that time, a few more purchases went through for the product, including one at 7:36pm that reduced stock to 0, as you can see here:

<img width="1080" alt="4642984_stock_reduction_1" src="https://user-images.githubusercontent.com/2912202/148023187-1bb432fe-8f2f-432c-987a-570953b0de7f.png">

The first payment that stalled at 7:24pm, finally succeeded at 7:42pm and then reduced stock to -1.
We suspect that this is some intermingling of how the `hold stock` action and the `reduce stock` action work between PayPal and Stripe. Please also take a look at this internal discussion as this seems to be related: p1625465858228500-slack-C7U3Y3VMY

The _Allow backorders_ option is set to _Do not allow_. The site is also configured to hold stock for 10 minutes.

### WordPress Environment

<details>

WordPress address (URL): https://dynastybreaks.com
Site address (URL): https://dynastybreaks.com
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.27
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1l-fips

SUHOSIN Installed: –
MySQL Version: 5.7.32-35-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: wp_
Total Database Size: 781.68MB
Database Data Size: 495.77MB
Database Index Size: 285.91MB
wp_woocommerce_sessions: Data: 6.02MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 14.52MB + Index: 3.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 74.61MB + Index: 45.11MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 3.79MB + Index: 1.65MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 2.86MB + Index: 1.99MB + Engine MyISAM
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.19MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 1.52MB + Index: 1.20MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.08MB + Index: 0.14MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.27MB + Index: 0.20MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 49.58MB + Index: 29.09MB + Engine InnoDB
wp_failed_jobs: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_entry: Data: 0.20MB + Index: 0.02MB + Engine MyISAM
wp_gf_entry_meta: Data: 0.71MB + Index: 0.51MB + Engine MyISAM
wp_gf_entry_notes: Data: 0.13MB + Index: 0.03MB + Engine MyISAM
wp_gf_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_meta: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_revisions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_view: Data: 0.06MB + Index: 0.03MB + Engine MyISAM
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_bans: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_dashboard_events: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp_itsec_distributed_storage: Data: 3.29MB + Index: 0.00MB + Engine MyISAM
wp_itsec_fingerprints: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itsec_geolocation_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itsec_lockouts: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_itsec_logs: Data: 1.94MB + Index: 0.17MB + Engine MyISAM
wp_itsec_mutexes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itsec_opaque_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itsec_temp: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_itsec_user_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_login_redirects: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 10.44MB + Index: 1.17MB + Engine InnoDB
wp_postmeta: Data: 215.75MB + Index: 155.31MB + Engine InnoDB
wp_posts: Data: 47.56MB + Index: 8.06MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rsssl_csp_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.36MB + Index: 0.20MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_tm_tasks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_totalsoft_galleryv_dbt: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_totalsoft_galleryv_dbt_1: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_totalsoft_galleryv_dbt_2: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_totalsoft_galleryv_dbt_3: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_totalsoft_galleryv_dbt_4: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_totalsoft_galleryv_id: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_totalsoft_galleryv_manager: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_totalsoft_galleryv_videos: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_totalsoft_new_plugin: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 26.55MB + Index: 18.06MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 0.83MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.32MB + Index: 0.24MB + Engine MyISAM
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.16MB + Index: 0.29MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 3.08MB + Index: 2.54MB + Engine MyISAM
wp_wc_order_stats: Data: 1.87MB + Index: 1.25MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.10MB + Index: 0.11MB + Engine MyISAM
wp_wc_points_rewards_user_points: Data: 4.52MB + Index: 4.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 8.52MB + Index: 6.55MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.33MB + Index: 0.48MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woof_query_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfront_ure_login_redirect: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfront_ure_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_yoast_indexable: Data: 5.65MB + Index: 1.13MB + Engine MyISAM
wp_yoast_indexable_hierarchy: Data: 0.12MB + Index: 0.29MB + Engine MyISAM
wp_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_primary_term: Data: 0.12MB + Index: 0.15MB + Engine MyISAM
wp_yoast_seo_links: Data: 1.52MB + Index: 0.38MB + Engine InnoDB
wp_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 5
acf-field-group: 2
advgb_profiles: 1
amn_wpforms-lite: 1
attachment: 2580
aw_workflow: 1
custom_css: 1
faqs: 1
forum: 1
itsec-dash-card: 16
itsec-dashboard: 2
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
messages: 12
nav_menu_item: 54
oembed_cache: 2
option-tree: 1
page: 25
post: 3
product: 2552
product_variation: 479
random-result: 261
random-results: 1
revision: 86
seedprod: 2
shop_coupon: 263
shop_order: 45668
shop_order_refund: 145
wp_block: 3
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

Admin Menu Editor: by Janis Elsts – 1.10
Advanced Custom Fields PRO: by Delicious Brains – 5.11.4
PublishPress Blocks: by PublishPress – 2.11.1
AutomateWoo: by WooCommerce – 5.5.7
CW Extra Functions: by Crane | West – 1.0.0
Force First and Last Name as Display Name: by Stranger Studios – 1.2
GA Google Analytics: by Jeff Starr – 20210719
Gravity Forms: by Gravity Forms – 2.5.15
Hide Related Video Youtube: by Trần Hoàng Quốc. – 1.0
iThemes Security Pro: by iThemes – 7.0.3
Mailchimp for WooCommerce: by Mailchimp – 2.5.4
MainWP Child: by MainWP – 4.1.8
No CAPTCHA reCAPTCHA for WooCommerce: by MailOptin Team – 1.2.6
LoginWP (Formerly Peter's Login Redirect): by LoginWP Team – 3.0.0.6
Purchased Items Column WooCommerce: by pipdig – 1.5
ShipWorks Connector: by AdvancedCreation – 4.9.2
Storefront Hamburger Menu: by WooCommerce – 1.2.2
User Role Editor Pro: by Vladimir Garagulia – 4.60.2
User Switching: by John Blackbourn & contributors – 1.5.8
User Email Verification for WooCommerce: by XLPlugins – 3.5.0
Woo Login Redirect: by WP Doctor – 2.2.4
WooCommerce Advanced Notifications: by WooCommerce – 1.2.35
WooCommerce Conversion Tracking: by weDevs – 2.0.9
WooCommerce Stripe Gateway: by WooCommerce – 5.9.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.5
Booster for WooCommerce: by Pluggabl LLC – 5.4.9
WooCommerce PayPal Payments: by WooCommerce – 1.6.4
WooCommerce Points and Rewards: by WooCommerce – 1.7.4
WOOF - WooCommerce Products Filter: by realmag777 – 1.2.6.3
WooCommerce Shipping & Tax: by WooCommerce – 1.25.20
WooCommerce Stamps.com API integration: by WooCommerce – 1.3.24
WooCommerce Smart Coupons: by StoreApps – 4.33.1
WooCommerce - StampscomEndicia Integration: by Stamps.comEndicia – 2.0.0
WooCommerce: by Automattic – 6.0.0
Yoast SEO: by Team Yoast – 17.8
WP Mail SMTP: by WPForms – 3.2.1
YITH WooCommerce Name Your Price: by YITH – 1.3.0
YotuWP - YouTube Gallery: by  – 1.3.4.5

### Inactive Plugins (8) ###

Advanced Order Export For WooCommerce: by AlgolPlus – 3.2.2
Custom Sidebars: by WebFactory Ltd – 3.32
EU VAT for WooCommerce Pro: by WPWhale – 2.4.2
Password Strength Settings for WooCommerce: by Daniel Santoro – 3.0.0
WC Search Orders By Product: by WPHEKA – 1.6
WooCommerce Auto Restore Stock: by Gerhard Potgieter – 1.0.1
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.11.1
WordPress Users & WooCommerce Customers Import Export(BASIC): by WebToffee – 2.2.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #62 - /terms-conditions/

### Theme ###

Name: Dynasty Breaks
Version: 1.0.4
Author URL: https://thatwebguy.xyz
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 3.9.1
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: dynastybreaks/woocommerce/emails/customer-new-account.php version 3.7.0 is out of date. The core version is 6.0.0
dynastybreaks/woocommerce/single-product.php
dynastybreaks/taxonomy-product_cat.php version 1.6.4 is out of date. The core version is 4.7.0

Outdated Templates: ❌
					
					
						Learn how to update

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
PayPal card processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔

### Action Scheduler ###

Canceled: 13
Oldest: 2021-11-29 22:00:07 +0000
Newest: 2021-12-18 00:49:38 +0000

Complete: 14,430
Oldest: 2021-12-26 21:50:41 +0000
Newest: 2021-12-28 15:32:41 +0000

Failed: 22
Oldest: 2019-11-01 18:18:56 +0000
Newest: 2021-04-22 21:59:31 +0000

### Status report information ###

Generated at: 2021-12-28 10:55:26 -05:00

</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by EdithAllison** [comment] 2022-01-04 16:20
In WooCommerce, stock is only reduced when an order has reached payment stage. Pending Payment does not trigger stock reduction. But in the example you've shown, stock is reduced on "Failed" and this looks like a bug to me, updating status from Pending Payment to Failed should not trigger any stock movements.

**Comment by swatipawarGS** [comment] 2022-01-05 14:28
Hi @pauljacobson ,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using WooCommerce 6.0.0 version and WordPress 5.8.2 version. 

Please find below screenshot for reference :

![#31551](https://user-images.githubusercontent.com/94531721/148231554-7045f761-7916-40fa-9bdd-6f90abd0ba04.jpg)



Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by rodelgc** [comment] 2022-01-10 08:55
Adding the `type: bug` label.

**Comment by vbelolapotkov** [comment] 2023-11-11 09:15
@woocommerce/quark could you please take a look and prioritize?

**Comment by james-allan** [comment] 2023-11-13 06:43
I can't replicate this. After I put a product in my cart, chose PayPal Standard on checkout and proceeded to PayPal, a pending order is created, stock is held and an order note is added. 

<img width="288" alt="Screenshot 2023-11-13 at 4 23 45 pm" src="https://github.com/woocommerce/woocommerce/assets/8490476/a588ccc8-0d38-4ef5-9bb1-89258275815b">

---

WC core handles held stock on the `woocommerce_checkout_order_created` hook ([here](https://github.com/woocommerce/woocommerce/blob/8.2.2/plugins/woocommerce/includes/wc-stock-functions.php#L350C1-L368)) irrespective of the chosen payment method so I'm not sure how this could have only impacted PayPal or Stripe to begin with. 

If I view the product while there's this hold on the stock. I see that the product still appears to have 1 in stock, but if I add it to the cart, there's a cart error and checking out isn't possible.

<p align="center">
<img width="200" alt="Screenshot 2023-11-13 at 4 33 31 pm" src="https://github.com/woocommerce/woocommerce/assets/8490476/25e06831-9dc5-4711-b779-b50de71f4b57">
</br><sup>Product in stock?</sup></br>
</p>

---
<p align="center">
<img width="500" alt="Screenshot 2023-11-13 at 4 33 23 pm" src="https://github.com/woocommerce/woocommerce/assets/8490476/624e86c0-4a26-4551-aa83-bb4d54ccc2ad">
</br><sup>Cart error</sup></br>
</p>

---
<p align="center">
<img width="500" alt="Screenshot 2023-11-13 at 4 36 10 pm" src="https://github.com/woocommerce/woocommerce/assets/8490476/d60079df-ce3c-4e04-9fbd-f4b768abf934">
</br><sup>Checkout isn't displayed</sup></br>
</p>

Given I can't replicate and I don't think this is related to PayPal Standard specifically, I'll close this one now, but feel free to reopen if there's something I'm missing here. :)

**Closed as completed by james-allan** 2023-11-13 06:43 UTC
Labels: Bug, Payments, Product/Inventory Management, plugin: woocommerce, Payments Engineering
