### ISSUE TITLE
[Setup Wizard]- Business Details page has spacing issues for how many products and current annual revenue options.

### ISSUE THREAD

**Issue by shishurajpandey** [woothemes/woocommerce#32221] opened 2021-11-04 08:05 UTC
### Describe the bug
When a user moves back to the Store profile page of Setup Wizard flow from Buisness details page and again move back to Business Details page by clicking on continue then following options has spacing issues-
1.  `How many products do you plan to display?` --> 
`- 1000 is showing as 1 000 `
`- 1000+ is showing as 1 000+`
2.  `What's your current annual revenue?` ---->
-` Up to 3000,00 €  is showing as Up to 3 000,00 €`
-` Up to 3000,00 € - 10000,00 € is showing as Up to 3 000,00 € - 1 0000,00 €`

### To Reproduce

1. Install WooCommerce plugin
2. Activate the WooCommerce plugin and wait for the WooCommerce Setup Wizard flow to open
3. Now complete the setup flow and move to the Business details page by selecting `Åland Islands` as input for country.
3. Again move back to `store profier` page from `business details` page and then again move back to Business Details page by clicking on continue
4. Observe the `How many products do you plan to display?` and `What's your current annual revenue?` options for spacing issue.

### Actual behavior:
There should not be any spacing issue for the above said options.

### Screenshots

https://user-images.githubusercontent.com/19307354/140278286-0f1bf49a-dd32-4911-b9c7-1870087ba131.mp4

### Desktop (please complete the following information):

* OS: Windows OS
* Browser: Chrome
* Version: 95.0.4638.69

**Comment by moon0326** [comment] 2021-11-04 23:06
Thank you @raj007champ for taking the time to report this issue. I was able to reproduce it on my end.

We have space between numbers.

![Screen Shot 2021-11-04 at 4 04 52 PM](https://user-images.githubusercontent.com/4723145/140432296-2bef64f4-d028-4bb1-9a4d-a88780cd8c64.jpg)

**Comment by chihsuan** [comment] 2022-01-19 07:32
I found actually the `thousand_sep` of `Åland Islands` (AX) is a blank space in [woocommerce/i18n/locale-info.php](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/i18n/locale-info.php#L225).

We also post the same value.
![Screen Shot 2022-01-19 at 15 16 57](https://user-images.githubusercontent.com/4344253/150082573-31e2a133-72af-4b9d-96f8-61f67ac40f08.png)

But the value in DB becomes an empty string.

![Screen Shot 2022-01-19 at 15 18 09](https://user-images.githubusercontent.com/4344253/150082674-3098565b-940d-4755-a42d-4885d88fc3fd.png)

I think this is because we sanitize data before saving it.

If a blank space is expected, we might need to 1) modify the code to keep blank space in the table or 2) use another character, for example, `\s` for `thousand_sep`.

Otherwise, we should open an issue in Woocommerce core.

**Comment by ilyasfoo** [comment] 2022-01-24 07:14
@chihsuan Good catch on AX numbering format, I confirm it to be expected according to this site https://www.localeplanet.com/icu/sv-AX/index.html.

> But the value in DB becomes an empty string.

I agree with your assessment, this could probably be our value is trimmed prior saving. I think we should close this issue and report an issue on core for saving `woocommerce_price_thousand_sep` with a blank space value. I think we shouldn't try with `\s` since it will not be precise.

**Comment by adrianduffell** [comment] 2024-02-01 05:29
Closing this out as the setup wizard has a new implementation now.

**Closed as completed by adrianduffell** 2024-02-01 05:29 UTC
Labels: Bug, focus: i18n, plugin: woocommerce, Onboarding
