### ISSUE TITLE
No way for setting paypal NOSHIPPING attribute to 2

### ISSUE THREAD

**Issue by naveedcs** [woothemes/woocommerce#11122] opened 2016-06-14 19:19 UTC
We are in a situation where we want to send NOSHIPPING attribute in paypal request set to 2. If look into our option currently it can either be set to 0 or 1 by selecting a shipping option from woo-commerce papal admin settings.
[https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP/](url)

this link explains the NOSHIPPING attribute

**Comment by mikejolley** [comment] 2016-06-14 19:21
You can adjust ALL args sent to PayPal via the filter here https://github.com/woothemes/woocommerce/blob/master/includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php#L65

Also, you are linking to EXPRESS CHECKOUT docs. Core has PAYPAL STANDARD. Different arguments + docs.

**Comment by mikejolley** [comment] 2016-06-14 19:21
Closing as this is not a bug report, but a request for support which github is not intended for.

**Closed by mikejolley** 2016-06-14 19:21 UTC

**Comment by naveedcs** [comment] 2016-06-14 20:56
Nope it was not a request for support. It was an enhancement request. I know we can adjust this through filters but there should be a better way of doing this instead modifying code to adjust filters making it a setting option in admin.

**Comment by mikejolley** [comment] 2016-06-14 20:59
The majority of users won't need no_shipping=2, so it does not make much sense to include. Why collect address twice?

**Comment by naveedcs** [comment] 2016-06-14 21:03
Yea we sell virtual products we don't ship them we email them so we don't ask our customers for shipping address, instead we collect shipping address from paypal and send them invoice to that address. Why we send invoice ? we believe in some cases it helps us fight the chargebacks by provide a shipping proof

**Comment by mikejolley** [comment] 2016-06-14 21:07
But you're not shipping anything, so there is no "proof" :) Seems edge case regardless.

**Comment by naveedcs** [comment] 2016-06-14 21:13
I agree to the fact most of the users won't use it, thank you for your time @mikejolley I really appreciate it. You are right It definitely is an edge case.
