### ISSUE TITLE
We are facing an issue in creating an order when HPOS is active

### ISSUE THREAD

**Issue by Ifarooq-tekhqs** [woothemes/woocommerce#38677] opened 2023-06-12 11:42 UTC
Hi there,

We are facing an issue in creating an order when HPOS is active. New orderID is new incrementID when **Use the WordPress posts table** is used, but its 0 when **Use the WooCommerce orders tables** is active.

Admin -> WooCommerce -> Orders -> Add new order 

When we proceed with adding product.

![new order error](https://github.com/woocommerce/woocommerce/assets/34734298/fe18baf9-4dba-42e0-ace8-3aa2bb8ec6b7)

It stops with this error in image given below due to new OrderID 0.

![new order id 0 error](https://github.com/woocommerce/woocommerce/assets/34734298/53e45771-3711-4388-9569-37a45c34ff0b)

This occurs when I enable HPOS and custom payment method (Order #0 details). It works fine when HPOS is disabled or Custom payment method is disabled. No order increment OrderId is overridden in custom plugin. I think there is issue in these options. Orders and POsts tables are not synced during HPOS there is no entry in Wc_Orders table but it can be found in posts table. That could be the issue for 0 OrderId.

1) Keep the posts table and the orders tables synchronized
2) Switch to using the orders table as the authoritative data store for orders when sync finishes
3) Use database transactions for the orders data synchronization

@tammullen @vedanshujain Can you please suggest me what is the issue and how it can be solved?

_Originally posted by @Ifarooq-tekhqs in https://github.com/woocommerce/woocommerce/issues/34988#issuecomment-1576370125_

**Comment by Konamiman** [comment] 2023-06-22 09:41
Hi @Ifarooq-tekhqs, we are unable to reproduce the issue (which is expected, since as you say it only happens with your custom payment method is enabled). Would you be able to share with us the code of your custom plugin so that we can take a look at it and try to reproduce the issue?

Also, which version of WooCommerce are you using? Thank you!

**Comment by barryhughes** [comment] 2023-08-03 23:29
@Ifarooq-tekhqs we'll go ahead and close this since we haven't received any further information that would allow us to replicate. Of course, you can easily create a fresh issue with the needed information if you still need help. Thanks!

**Comment by Ifarooq-tekhqs** [comment] 2023-08-08 07:29
Hi @barryhughes @vedanshujain .

I am still unable to resolve this issue. Still i cannot create new order from admin as well as programmatically when HPOS is active. I have a custom payment module. When I disable that one then it shows new orderID else its 0. We are not overriding order increment ID just create new order programmatically in some scenarios like subscription orders. Can you please help me with this ASAP. Also can you please help me here or I need to open another ticket?

Thanks

**Comment by barryhughes** [comment] 2023-08-08 23:47
Hi @Ifarooq-tekhqs,

Re-opening as requested :-)

We need more information, though. Are you able to share your custom code (or, better yet, a minimal version of your code that would allow us to replicate on our side)?

**Comment by Ifarooq-tekhqs** [comment] 2023-08-10 08:25
Hi @barryhughes Thanks for your reply,

Actually I was using some function with this code to sync newly created order data to gateway.

$order = new \WC_Order($order_id);
$orderId = $order->get_id();

I was getting error of orderID (0) on many places. But now I tried this code instead and for the time being it resolved the issue of 0 orderID.

$order = wc_get_order($order_id);
$orderId = $order->get_id();

But now I am getting this code running multiple times. I am looking into it and will try to resolve this issue too. I will let you know in case of any assistance or guidance. Thanks for your help.

**Closed as completed** 2023-08-10 19:14 UTC
Labels: needs: triage feedback, type: community contribution

**Comment by barryhughes** [comment] 2023-08-10 19:18
OK, I'm not sure why that happened. For example, this code works for me when HPOS is enabled (substituting `12345` for a valid order ID):

```php
( new WC_Order( 12345 ) )->get_id(); # => 12345
```

If the alternative code you shared works for you, though, that's great. I've closed this again, though, since this sounds like perhaps a set of custom coding issues vs a clearly identified bug.
