### ISSUE TITLE
 Woocommerce 8.4.0 shipping cost Bug

### ISSUE THREAD

**Issue by Martje65** [woothemes/woocommerce#42801] opened 2023-12-13 22:05 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In this new version of the plugin there is a problem with the shipping methods costs, because when you put the amount with decimals, once you saved the changes, the values are truncated and therefore we cannot put exactly the cost that you need.

For example:

If I put an amount of €7,50 for a shipping method , once I saved the changes the value that appear is €7,00, and not the correct value that I have put in this cell.
It shows correct in the frontend but its not correct in the Backend.

Put at the shipping cost €7,50 en look in the shopping cart, ther you wil see €7,50
But if you look in the backend (wp-admin/admin.php?page=wc-settings&tab=shipping) you will see €7,00

![Frondend](https://github.com/woocommerce/woocommerce/assets/112067446/1c62e58f-8b1b-45e8-bc38-2b6ee8c56452)
![Backend](https://github.com/woocommerce/woocommerce/assets/112067446/c182cd11-1786-4e9c-a1e3-77e8c11e94ad)

### Expected behavior

That the shipping cost in the frondend are the same as the shipping cost in the backend.

### Actual behavior

Once you saved the changes, the values are truncated and therefore we cannot put exactly the cost that you need.

### Steps to reproduce

1 go to /admin.php?page=wc-settings&tab=shipping  and put your shipping cost in there with a decimal
2 go to the webpage and look in to you shopping cart, you will see there the correct shipping cost
3 go back to /admin.php?page=wc-settings&tab=shipping  and you will see there the shipping cost without the decimals

4 go back to  Woocommerce 8.3.1 and there is no problem and everything works as aspect

### WordPress Environment

.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by shameemreza** [comment] 2023-12-14 01:50
Initially reported here: https://wordpress.org/support/topic/woocommerce-8-4-0/#post-17275817

7445070-zen

**Comment by shameemreza** [comment] 2023-12-14 02:11
I tried recreating the issue on my end but encountered no problems. However, could you please give the workaround I shared [here](https://wordpress.org/support/topic/woocommerce-8-4-0/#post-17276138) a try and let us know the outcome?

In the meantime, while our dev team check it, you can run a conflict test to help you identify the cause of the issue. More info: https://woo.com/document/how-to-test-for-conflicts/

**Comment by Martje65** [comment] 2023-12-14 06:46
That did not help @shameemreza , the only thing that’s works for me is go back to version 8.3.1

@WooCommerce > Settings > General there are 2 decimals

And i saw that if you put up a number with decimals in the Free shipping you will get an “Please enter a valid number” error.

![enter a valid number](https://github.com/woocommerce/woocommerce/assets/112067446/85920124-95ee-45fa-8df1-7b7be17ccdd1)

**Comment by paulostp** [comment] 2023-12-18 14:02
We received another report here 7446805-zen

**Comment by psealock** [comment] 2023-12-19 10:01
This will be fixed by https://github.com/woocommerce/woocommerce/pull/42916

**Comment by shameemreza** [comment] 2023-12-24 03:19
There is probably another similar report here: https://wordpress.org/support/topic/shipping-cost-number-after-the-disappears

7487119-zen

**Comment by psealock** [comment] 2024-01-08 23:14
Closed by https://github.com/woocommerce/woocommerce/pull/42916

**Closed as completed by psealock** 2024-01-08 23:14 UTC
Labels: Bug, Shipping, type: community contribution, Escargot
