### ISSUE TITLE
Mini Cart doesn't open after adding to cart

### ISSUE THREAD

**Issue by asafm7** [woothemes/woocommerce#42245] opened 2023-08-21 18:14 UTC
## Describe the bug

Mini Cart doesn't open after adding to the cart, although the setting is turned on.

## To reproduce

1. Set the Mini Cart to open after adding to the cart.
2. Add to cart.

## Expected behavior

Mini Cart should open

## Screenshots

Not relevant.

## Environment

<details>
<summary>WordPress Environment</summary>

```
### WordPress Environment ###

WordPress address (URL): https://staging2.pepite.co.il
Site address (URL): https://staging2.pepite.co.il
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: ❌ 6.2.2 - יש גרסה חדשה יותר של WordPress (6.3)
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: –
Language: he_IL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.85.0
OpenSSL/3.0.9

SUHOSIN Installed: –
MySQL Version: 5.7.39-42-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: isp_
הגודל הכולל של בסיס הנתונים: 18.61MB
גודל הנתונים של בסיס הנתונים: 13.84MB
גודל האינדקס של בסיס הנתונים: 4.77MB
isp_woocommerce_sessions: נתונים: 0.34MB + אינדקס: 0.02MB + מנוע InnoDB
isp_woocommerce_api_keys: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
isp_woocommerce_attribute_taxonomies: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
isp_woocommerce_downloadable_product_permissions: נתונים: 0.02MB + אינדקס: 0.06MB + מנוע InnoDB
isp_woocommerce_order_items: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
isp_woocommerce_order_itemmeta: נתונים: 0.08MB + אינדקס: 0.03MB + מנוע InnoDB
isp_woocommerce_tax_rates: נתונים: 0.02MB + אינדקס: 0.06MB + מנוע InnoDB
isp_woocommerce_tax_rate_locations: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
isp_woocommerce_shipping_zones: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
isp_woocommerce_shipping_zone_locations: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
isp_woocommerce_shipping_zone_methods: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
isp_woocommerce_payment_tokens: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
isp_woocommerce_payment_tokenmeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
isp_woocommerce_log: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
isp_actionscheduler_actions: נתונים: 0.42MB + אינדקס: 0.50MB + מנוע InnoDB
isp_actionscheduler_claims: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
isp_actionscheduler_groups: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
isp_actionscheduler_logs: נתונים: 0.34MB + אינדקס: 0.25MB + מנוע InnoDB
isp_commentmeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
isp_comments: נתונים: 0.02MB + אינדקס: 0.09MB + מנוע InnoDB
isp_gla_attribute_mapping_rules: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
isp_gla_budget_recommendations: נתונים: 0.22MB + אינדקס: 0.14MB + מנוע InnoDB
isp_gla_merchant_issues: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
isp_gla_shipping_rates: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
isp_gla_shipping_times: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
isp_links: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
isp_mailchimp_carts: נתונים: 0.03MB + אינדקס: 0.00MB + מנוע InnoDB
isp_mailchimp_jobs: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
isp_options: נתונים: 3.52MB + אינדקס: 0.17MB + מנוע InnoDB
isp_postmeta: נתונים: 1.52MB + אינדקס: 0.48MB + מנוע InnoDB
isp_posts: נתונים: 3.52MB + אינדקס: 0.30MB + מנוע InnoDB
isp_sgs_log_events: נתונים: 0.33MB + אינדקס: 0.14MB + מנוע InnoDB
isp_sgs_log_visitors: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
isp_termmeta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
isp_terms: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
isp_term_relationships: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
isp_term_taxonomy: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
isp_trp_gettext_he_il: נתונים: 1.52MB + אינדקס: 0.48MB + מנוע InnoDB
isp_trp_gettext_original_meta: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
isp_trp_gettext_original_strings: נתונים: 0.38MB + אינדקס: 0.27MB + מנוע InnoDB
isp_usermeta: נתונים: 0.16MB + אינדקס: 0.03MB + מנוע InnoDB
isp_users: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
isp_wc_admin_notes: נתונים: 0.06MB + אינדקס: 0.00MB + מנוע InnoDB
isp_wc_admin_note_actions: נתונים: 0.05MB + אינדקס: 0.02MB + מנוע InnoDB
isp_wc_category_lookup: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
isp_wc_customer_lookup: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
isp_wc_download_log: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
isp_wc_orders: נתונים: 0.02MB + אינדקס: 0.11MB + מנוע InnoDB
isp_wc_orders_meta: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
isp_wc_order_addresses: נתונים: 0.02MB + אינדקס: 0.06MB + מנוע InnoDB
isp_wc_order_coupon_lookup: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
isp_wc_order_operational_data: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
isp_wc_order_product_lookup: נתונים: 0.02MB + אינדקס: 0.06MB + מנוע InnoDB
isp_wc_order_stats: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
isp_wc_order_tax_lookup: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
isp_wc_product_attributes_lookup: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
isp_wc_product_download_directories: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
isp_wc_product_meta_lookup: נתונים: 0.05MB + אינדקס: 0.09MB + מנוע InnoDB
isp_wc_rate_limits: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
isp_wc_reserved_stock: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
isp_wc_tax_rate_classes: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
isp_wc_webhooks: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
isp_wpforms_payments: נתונים: 0.02MB + אינדקס: 0.14MB + מנוע InnoDB
isp_wpforms_payment_meta: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
isp_wpforms_tasks_meta: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
isp_wpmailsmtp_debug_events: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
isp_wpmailsmtp_tasks_meta: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
isp_wsal_metadata: נתונים: 0.06MB + אינדקס: 0.06MB + מנוע InnoDB
isp_wsal_occurrences: נתונים: 0.06MB + אינדקס: 0.03MB + מנוע InnoDB
isp_yoast_indexable: נתונים: 0.08MB + אינדקס: 0.09MB + מנוע InnoDB
isp_yoast_indexable_hierarchy: נתונים: 0.02MB + אינדקס: 0.05MB + מנוע InnoDB
isp_yoast_migrations: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
isp_yoast_primary_term: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB
isp_yoast_seo_links: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע InnoDB

### Post Type Counts ###

attachment: 251
customize_changeset: 1
feedback: 1
global_product_addon: 1
page: 12
popup: 1
popup_theme: 8
post: 2
product: 33
product_variation: 134
revision: 417
shop_coupon: 5
shop_order: 11
tm_global_cp: 11
tm_template_cp: 6
wp_block: 4
wp_global_styles: 1
wp_navigation: 2
wp_template: 9
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

ווקומרס: מאת חברת אוטומטיק – 7.9.0 (העדכון לגרסה 8.0.2 זמין)

### Inactive Plugins (21) ###

CardCom Payment Gateway: מאת CardCom LTD – 3.4.8.2
Create Block Theme: מאת WordPress.org – 1.13.2
Extra Product Options & Add-Ons for WooCommerce: מאת ThemeComplete – 6.3.2
Facebook for WooCommerce: מאת Facebook – 3.0.30
Google Listings and Ads: מאת WooCommerce – 2.5.2
Jetpack: מאת Automattic – 12.4
Loco Translate: מאת Tim Whitlock – 2.6.4
Mailchimp for WooCommerce: מאת Mailchimp – 3.1
Morning for WooCommerce: מאת Morning – 1.2.0
Pinterest for WooCommerce: מאת WooCommerce – 1.3.6 (העדכון לגרסה 1.3.8 זמין)
SearchWP Modal Search Form: מאת SearchWP
LLC – 0.5.3

SiteGround Central: מאת SiteGround – 3.0.1
SiteGround Optimizer: מאת SiteGround – 7.3.4
SiteGround Security: מאת SiteGround – 1.4.5
Site Kit by Google: מאת Google – 1.106.0
WooCommerce Additional Variation Images: מאת WooCommerce – 2.3.2
WooCommerce Google Analytics Integration: מאת WooCommerce – 1.8.4
WPForms Lite: מאת WPForms – 1.8.2.3
WP Mail SMTP: מאת WP Mail SMTP – 3.8.2
Yoast SEO: מאת Team Yoast – 20.13
Yoast SEO: WooCommerce: מאת Team Yoast – 15.7

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ILS (₪)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

בסיס חנות: woocommerce/woocommerce-blocks#5 - /shop/
סל קניות: woocommerce/woocommerce-blocks#6 - /cart/
תשלום: woocommerce/woocommerce-blocks#7 - /checkout/
החשבון שלי: woocommerce/woocommerce-blocks#8 - /my-account/
תנאי שימוש: woocommerce/woocommerce-blocks#636 - /terms-of-use/

### Theme ###

Name: Pepite
Version: 0.0.1
Author URL: 
Child Theme: ❌ – אם משנים את ווקומרס בערכת נושא אב שלא נבנתה באופן אישי
מומלץ להשתמש בערכת עיצוב בת. אפשר לראות: כיצד ליצור ערכת עיצוב בת

WooCommerce Support: ❌ ללא הצהרה

### Templates ###

Overrides: /home/customer/www/staging2.pepite.co.il/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/home/customer/www/staging2.pepite.co.il/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/home/customer/www/staging2.pepite.co.il/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-09 13:35:29 +03:00
Options: ✔
Notes: 85
Onboarding: completed

### Action Scheduler ###

הושלם: 846
Oldest: 2023-07-13 13:04:05 +0300
Newest: 2023-08-21 21:02:41 +0300

נכשל: 112
Oldest: 2023-07-02 17:22:37 +0300
Newest: 2023-07-02 17:22:37 +0300

ממתין לאישור: 4
Oldest: 2023-08-21 22:00:12 +0300
Newest: 2023-08-25 00:32:07 +0300


### Status report information ###

Generated at: 2023-08-21 21:04:51 +03:00

```

<details>

## Additional context

Tried both simple and variable products.

**Comment by kmanijak** [comment] 2023-08-22 10:51
Hi @asafm7, thanks for raising the issue! 👍 

Unfortunately, I cannot reproduce the problem. I tried locally with my setup as well as on https://staging2.pepite.co.il/ with Chrome, Firefox and Safari - Mini Cart opens efery time I add product to the cart:

https://github.com/woocommerce/woocommerce-blocks/assets/20098064/2898a8e7-d91d-4904-8638-8b38a32b87a2

Can you provide more details on how to reproduce it? What browser do you use?

Thanks 🙌

**Comment by asafm7** [comment] 2023-08-22 15:04
Thanks @kmanijak .

Maybe it's only working on archive pages and not single product pages?

And/or maybe its only working for simple products and not for variable products?

Can you visit any other products' page ( besides the one you added on the video) and try from there?

**Comment by kmanijak** [comment] 2023-08-24 09:58
> Maybe it's only working on archive pages and not single product pages?

I tried that and you're right, Mini Cart doesn't open when adding a product from Single Product page. I'll move this issue to the backlog.

Notes:
- when adding to cart from single product page, then there's additional refresh that may influence the Mini Cart open behavior. Requires further investigation.

**Comment by asafm7** [comment] 2023-08-24 10:53
Thanks @kmanijak .

It also means the feature only works for simple products, as variable products can't be added to the cart from an archive page.

**Comment by asafm7** [comment] 2023-09-05 10:17
@kmanijak is there an issue I can subscribe to track?

Thanks.

**Comment by kmanijak** [comment] 2023-09-05 11:16
@asafm7 - I moved this particular issue to the backlog, meaning that any updates will be provided here. I hope that works for you 🙌

**Comment by asafm7** [comment] 2023-09-05 11:20
Okay, thanks @kmanijak

**Comment by mikejolley** [comment] 2023-12-13 15:11
This issue is being tracked here https://github.com/woocommerce/woocommerce/issues/42638

Closing as a duplicate. Thanks.

**Closed as completed by mikejolley** 2023-12-13 15:11 UTC
Labels: Bug, type: community contribution, Rubik, block: mini-cart
