### ISSUE TITLE
 Problem calculating decimals with Taxes Included

### ISSUE THREAD

**Issue by studiograficorosati** [woothemes/woocommerce#34756] opened 2022-09-21 08:25 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello,

I have a big problem with decimals, I applied Italian VAT at 22% but when you calculate the product in the cart the decimals are wrong.

Example:
10 products in the cart from € 133.68 (22% VAT excluded) exit at € 1,336.77 when in reality 133.68 × 10 = 1,336.80

I have read many forums and many people have this problem.

It has been an unsolved problem for several years. It is possible that Woocommerce cannot solve it?!?!?

The solution is not to remove VAT as the site is dedicated to resellers and it is unthinkable that they see prices including VAT.

There are no online solutions that solve the problem.

I represent a company that invoices millions of euros. It is not a budget problem but a problem of credibility. The prices, even if only a few cents, are always wrong.

I got one of the best paid programmers involved to try and fix the bug here is his answer:

“… .. I have spent many days and hours on this project and in that time I can even build a complete system…. however Woocommerce does not provide any fixes for this bug.

I created all the code from scratch ...

Unfortunately, his bug is in woocommerce core files which saves data in 16-digit format…

It is not possible to get correct decimals in this version of woocommerce. you can convince with the customer unfortunately his fault is not in our hands.

16 digits after the dot cannot be checked.

I have tried everything and nothing has happened nobody can do it, I can bet on it.

I've tried everything ...

it is useless if we make changes on the plugin if then it will go away every time you update Woocommerce, because the core files all change.

The only smart way is to wait for the next Woocommerce updates that will address the issue ...

Hundreds of questions on the woocommce page regarding this bug ... `"

### Expected behavior

10 products in the cart from € 133.68 (22% VAT excluded) exit at € 1,336.77 when in reality 133.68 × 10 = 1,336.80

### Actual behavior

I have a big problem with decimals, I applied Italian VAT at 22% but when you calculate the product in the cart the decimals are wrong.

Example:
10 products in the cart from € 133.68 (22% VAT excluded) exit at € 1,336.77 when in reality 133.68 × 10 = 1,336.80

### Steps to reproduce

bug.mediatoys.shop/bug.mov
![Schermata 2022-09-21 alle 10 23 52](https://user-images.githubusercontent.com/114060858/191454138-2aa86318-aaa5-4d88-bc79-1f40f1007ec1.png)
![Schermata 2022-09-21 alle 10 23 11](https://user-images.githubusercontent.com/114060858/191454265-d5c2168b-6ddb-4131-88db-12bce4315a0d.png)

### WordPress Environment ###

WordPress address (URL): https://bug.mediatoys.shop
Site address (URL): https://bug.mediatoys.shop
WC Version: 6.9.3
REST API Version: ✔ 6.9.3
WC Blocks Version: ✔ 8.3.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.30
PHP Post Max Size: 700 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1q-fips

SUHOSIN Installed: –
MySQL Version: 5.7.39-42-log
Max Upload Size: 700 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.3
WC Database Prefix: r8tJg_
Total Database Size: 233.19MB
Database Data Size: 192.17MB
Database Index Size: 41.02MB
r8tJg_woocommerce_sessions: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
r8tJg_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
r8tJg_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
r8tJg_woocommerce_order_items: Data: 0.13MB + Index: 0.05MB + Engine InnoDB
r8tJg_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.81MB + Engine InnoDB
r8tJg_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
r8tJg_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
r8tJg_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
r8tJg_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
r8tJg_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_actionscheduler_actions: Data: 9.52MB + Index: 11.61MB + Engine InnoDB
r8tJg_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_actionscheduler_logs: Data: 6.52MB + Index: 6.03MB + Engine InnoDB
r8tJg_awb_critical_css: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
r8tJg_comments: Data: 0.17MB + Index: 0.09MB + Engine InnoDB
r8tJg_fusion_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
r8tJg_fusion_form_entries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_fusion_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_fusion_form_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
r8tJg_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
r8tJg_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
r8tJg_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
r8tJg_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
r8tJg_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_mclean_refs: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
r8tJg_mclean_scan: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_options: Data: 16.31MB + Index: 0.27MB + Engine InnoDB
r8tJg_postmeta: Data: 19.55MB + Index: 9.03MB + Engine InnoDB
r8tJg_posts: Data: 96.52MB + Index: 2.33MB + Engine InnoDB
r8tJg_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
r8tJg_revslider_css_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_revslider_sliders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_revslider_sliders_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_revslider_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_revslider_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_sgs_log_events: Data: 13.52MB + Index: 0.00MB + Engine InnoDB
r8tJg_sgs_log_visitors: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
r8tJg_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
r8tJg_stock_notifier_popular_product: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_termmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
r8tJg_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
r8tJg_term_relationships: Data: 1.52MB + Index: 0.31MB + Engine InnoDB
r8tJg_term_taxonomy: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
r8tJg_usermeta: Data: 3.52MB + Index: 5.03MB + Engine InnoDB
r8tJg_users: Data: 0.20MB + Index: 0.23MB + Engine InnoDB
r8tJg_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
r8tJg_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
r8tJg_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
r8tJg_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
r8tJg_wc_order_product_lookup: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
r8tJg_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
r8tJg_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
r8tJg_wc_product_attributes_lookup: Data: 0.20MB + Index: 0.16MB + Engine InnoDB
r8tJg_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_wc_product_meta_lookup: Data: 0.36MB + Index: 0.45MB + Engine InnoDB
r8tJg_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_wfblockediplog: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
r8tJg_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
r8tJg_wfconfig: Data: 0.47MB + Index: 0.00MB + Engine InnoDB
r8tJg_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_wffilemods: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
r8tJg_wfhits: Data: 0.44MB + Index: 0.23MB + Engine InnoDB
r8tJg_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
r8tJg_wfknownfilelist: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
r8tJg_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_wflogins: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
r8tJg_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
r8tJg_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
r8tJg_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
r8tJg_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_wpfront_ure_login_redirect: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
r8tJg_wpfront_ure_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
r8tJg_wpfront_ure_post_type: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_wpfront_ure_taxonomy: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_wt_iew_action_history: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
r8tJg_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_wt_iew_mapping_template: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
r8tJg_yith_wcan_filter_sessions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
r8tJg_yith_wcch_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_yith_wcch_sessions: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
r8tJg_yith_ywrac_email_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
r8tJg_yoast_indexable: Data: 5.52MB + Index: 1.88MB + Engine InnoDB
r8tJg_yoast_indexable_hierarchy: Data: 0.13MB + Index: 0.19MB + Engine InnoDB
r8tJg_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
r8tJg_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
r8tJg_yoast_seo_links: Data: 0.20MB + Index: 0.22MB + Engine InnoDB

### Post Type Counts ###

attachment: 2988
avada_faq: 8
custom_css: 1
customize_changeset: 5
cwginstocknotifier: 13
fusion_element: 20
fusion_form: 2
fusion_icons: 2
fusion_tb_layout: 8
fusion_tb_section: 14
nav_menu_item: 42
page: 30
post: 6
product: 2785
product_variation: 6
revision: 1362
shop_coupon: 5
shop_order: 62
wmpc-trash: 240
yith_price_rule: 4
yith_wcan_preset: 3
yith-wcdppm-rule: 1
ywrac_cart: 35
ywrac_email: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Avada Builder: by ThemeFusion – 3.8.1
Avada Core: by ThemeFusion – 5.8.1
WooCommerce: by Automattic – 6.9.3

### Inactive Plugins (27) ###

All-in-One WP Migration: by ServMask – 7.65
All-in-One WP Migration Unlimited Extension: by ServMask – 2.38
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: by codewoogeek – 3.0
Code Snippets: by Code Snippets Pro – 3.2.0
CTX Feed: by WebAppick – 4.5.2
Gravity Forms: by Gravity Forms – 2.6.5.1
Import Export for WooCommerce Wrapper: by WebToffee – 1.1.6
Import Export WordPress Users and WooCommerce Customers: by WebToffee – 2.3.4
Loco Translate: by Tim Whitlock – 2.6.2
Media Cleaner (Pro): by Jordy Meow – 6.4.5
reCaptcha for WooCommerce: by I Thirteen Web Solution – 2.37
SiteGround Central: by SiteGround – 2.0.8
SiteGround Optimizer: by SiteGround – 7.2.1
SiteGround Security: by SiteGround – 1.3.1
User Import Export for WooCommerce Add-on: by WebToffee – 1.1.4
User Switching: by John Blackbourn & contributors – 1.7.0
WooCommerce EU Vat & B2B: by Lagudi Domenico – 11.8
WooCommerce Payments: by Automattic – 4.7.2
WooCommerce Shipment Tracking: by WooCommerce – 1.7.1
WPFront User Role Editor: by Syam Mohan – 3.2.1.11184
YITH Dynamic Pricing per Payment Method for WooCommerce Premium: by YITH – 2.6.0
YITH WooCommerce Ajax Product Filter Premium: by YITH – 4.13.0
YITH WooCommerce Customer History Premium: by YITH – 1.15.0
YITH WooCommerce Minimum Maximum Quantity Premium: by YITH – 1.21.0
YITH WooCommerce Recover Abandoned Cart Premium: by YITH – 2.15.0
YITH WooCommerce Role Based Prices Premium: by YITH – 1.16.0
Yoast SEO: by Team Yoast – 19.7.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #212 - /catalogo-b2b/
Basket: #7 - /carrello/
Checkout: #8 - /ordina/
My account: #9 - /mio-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Avada Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 7.8.1
Parent Theme Author URL: https://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-09-21 15:26:12 +00:00
Options: ✔
Notes: 60
Onboarding: skipped

### Action Scheduler ###

Complete: 27,602
Oldest: 2022-08-21 10:52:25 +0000
Newest: 2022-09-21 08:10:06 +0000

Pending: 3
Oldest: 2022-09-21 08:15:06 +0000
Newest: 2022-09-21 08:18:10 +0000

### Status report information ###

Generated at: 2022-09-21 08:10:21 +00:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by joashrajin** [comment] 2022-09-21 08:50
Duplicate of https://github.com/woocommerce/woocommerce/issues/34529

**Closed as completed by joashrajin** 2022-09-21 08:50 UTC
Labels: Bug
