### ISSUE TITLE
Google Fonts @import error in custom email template file

### ISSUE THREAD

**Issue by simkoG** [woothemes/woocommerce#31343] opened 2021-12-01 10:38 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Cannot use `@import` with Google Fonts link in custom email template design with the `email/email-styles.php` file. 

**Expected behavior**
Write the `@import` rule to the email's `<head>` tag inside an `<style type="text/css"></style>`.

**Actual behavior**
If you put a Google Fonts `@import` link in the `emails/email-styles.php` file the link's end will be cut down and therefore the external file cannot be downloaded. 

```css
@import url("https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;700%26display=swap");
```
```html
<style type="text/css">@import url("https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;</style>
```
If you convert the link with bit.ly url shortener, the url won't be stripped down, and the file can be loaded to the email. But I don't want to use a third party tool for an `@import` only.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
1. Install Wordpress with WooCommerce, Storefront and [Storefront child theme](https://woocommerce.com/document/set-up-and-use-a-child-theme/).
2. Import the sample products, set a delivery method, and also set a payment method. 
3. Copy the `woocommerce/templates/emails/email-styles.php` file to the child theme's `woocommerce/emails` folder. 
4. Add this before the first `body` rule (around the 45-46 lines): 
```css
@import url("https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;700%26display=swap");
```
5. Make a full test order. 
6. Check the sent email's source code. 
7. You will find this in the email's `head` tag: 
```html
<style type="text/css">@import url("https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;</style>
```

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
You can check the System Status here: https://pastebin.com/78WXSpYP

**Comment by juliaamosova** [comment] 2021-12-06 22:16
Hi @simkoG,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by simkoG** [comment] 2022-02-07 12:07
Any update on this bug?

**Comment by barryhughes** [comment] 2022-02-15 22:50
Hi @simkoG,

This seems like a possible bug in the Emogrifier library, which we use to inline CSS rules within emails. 

As it happens, we are planning to update Emogrifier sometime soon (see #30027) and, based on a quick test using the new `CssInliner` from Emogrifier 6.0, it looks like that may resolve this problem.

Marking this as a bug and will keep it open for the time being, but once that other issue has been actioned we can revisit this one, confirm the problem is solved and hopefully close this out.

In the meantime, would it help to change things from:

```css
@import url("https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;700%26display=swap");
```

To (slight tweak in terms of which characters are URL-encoded):

```css
@import url("https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400%3B700&display=swap");
```

Based on a quick test with the existing version of Emogrifier it seems like that may help, but it merits a little further testing (and, if it doesn't help, I suggest holding tight until we can update things).

**Closed as completed** 2022-06-08 12:29 UTC
Labels: Bug, plugin: woocommerce
