### ISSUE TITLE
Attributes shown differently between products (both on cart and checkout page)

### ISSUE THREAD

**Issue by linesbytim** [woothemes/woocommerce#31230] opened 2021-11-17 11:32 UTC
On both the cart page and the checkoukt page I have the problem that attributes are shown diffently from one product to another. Please see the image below:
![](https://user-images.githubusercontent.com/93785924/140545636-59778482-03a4-44b8-a339-508dc7cc4985.png)
Items with three attributes list the attributes and also with their title whilst the ones with two are inline and do not bear the title. Is their any way I can get them all like the ones for two attributes? (So, Amsterdam and Rotterdam are perfect, how can I get They Bay also shown in this way?)

**Comment by vijayhardaha** [comment] 2021-12-31 16:56
WooCommerce has an inbuilt check for adding attributes names with the product title, if attributes are less than 3 then they will be showing along with the product title but if attributes are 3 or 3+ then they will be showing after the title in a list as you see in 3rd cart item.

However, you can override this thing by adding this line of custom code 
```php
add_filter( 'woocommerce_product_variation_title_include_attributes', '__return_true' );
```

But if in your variation set if you have a variation that allows choosing the "Any ..." option that it will still show in the new line.

**Comment by rodelgc** [comment] 2022-01-05 06:32
Hi @linesbytim,

> Items with three attributes list the attributes and also with their title whilst the ones with two are inline and do not bear the title

This behavior is intentional as clarified by the Core team [here](https://github.com/woocommerce/woocommerce/issues/31173#issuecomment-992444360).

> Is their any way I can get them all like the ones for two attributes?

Please try @vijayhardaha's suggestion above if it works. 

If it doesn't, the best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

I am closing this issue for now because the type of issue you submitted looks like a custom code related question. GitHub should be treated as a place to report confirmed bugs only.

**Closed as completed by rodelgc** 2022-01-05 06:32 UTC
Labels: type: support request
