### ISSUE TITLE
Shopping cart seems to be broken in 2.5.2 if user is not logged in

### ISSUE THREAD

**Issue by comproom** [woothemes/woocommerce#10290] opened 2016-02-06 18:58 UTC
I had 2.4.12, I am not a beta tester yet.  I updated to 2.5.2 and now notice that guest shopping baskets are not working.  To reproduce:-

1.  Add any product to the shopping cart, do not log in.

2.  View cart.  The cart is empty.

This is with the latest Wordpress 4.2.  I do have Wordfence activated, but I deactivated it, with the same result.  Downgrading back to 2.4.12 fixes the problem.

If this issue is duplicated, I apologise, but I couldn't find it.

My online store is at http://www.comproom.co.uk/?page_id=226.

Many thanks.

**Comment by mikejolley** [comment] 2016-02-06 19:13
View System status. Probably missing database table.

**Comment by comproom** [comment] 2016-02-06 19:15
Hi,

 

Doubt it, or the old version wouldn’t work.

 

All the best

 

Steve

 

Computer Room Services

77 Exeter Close

Stevenage

Hertfordshire

SG1 4PW

Tel: +44(0)1438-742286

Mob: +44(0)7956-334938

Fax: +44(0)1438-759589

Email:  <mailto:steve@comproom.co.uk> steve@comproom.co.uk

Web:  <http://www.comproom.co.uk/> http://www.comproom.co.uk

**Comment by mikejolley** [comment] 2016-02-06 20:22
Maybe you should check given that sessions use tables now....

**Comment by comproom** [comment] 2016-02-06 20:32
No tables missing..

**Comment by mikejolley** [comment] 2016-02-06 20:33
If you've reverted back it's not going to tell you. 

Woocommerce_sessions is the table name.

**Comment by comproom** [comment] 2016-02-06 22:52
Hi Mike,

 

From what I can see from PHPMyAdmin, Woocommerce_sessions is there.

 

Computer Room Services

77 Exeter Close

Stevenage

Hertfordshire

SG1 4PW

Tel: +44(0)1438-742286

Mob: +44(0)7956-334938

Fax: +44(0)1438-759589

Email:  <mailto:steve@comproom.co.uk> steve@comproom.co.uk

Web:  <http://www.comproom.co.uk/> http://www.comproom.co.uk

**Comment by reigelgallarde** [comment] 2016-02-07 00:50
I have tried your site, it's working.

**Comment by MattyLB** [comment] 2016-02-07 04:06
I've also checked your site and it works fine. Clear your browser cache and/or try to use incognito/private window mode on your browser. Either way - the shopping cart portion of your website works.

**Comment by comproom** [comment] 2016-02-07 09:38
Matt,

 

Of course the shopping cart works, because I downgraded Woocommerce.  I can’t have it not work for guest customers, so I don’t want to upgrade again, until we know what’s going on.

 

Computer Room Services

77 Exeter Close

Stevenage

Hertfordshire

SG1 4PW

Tel: +44(0)1438-742286

Mob: +44(0)7956-334938

Fax: +44(0)1438-759589

Email:  <mailto:steve@comproom.co.uk> steve@comproom.co.uk

Web:  <http://www.comproom.co.uk/> http://www.comproom.co.uk

**Comment by comproom** [comment] 2016-02-07 09:43
Hi again.

 

Please try it now folks, I have just upgraded Woocommerce.  I am prepared to bet that it doesn’t work.  Remember don’t create an account or log in, just add something to the cart and try to view it.  I am using IE 11 if that makes a difference, but it doesn’t work with Firefox either.

 

Computer Room Services

77 Exeter Close

Stevenage

Hertfordshire

SG1 4PW

Tel: +44(0)1438-742286

Mob: +44(0)7956-334938

Fax: +44(0)1438-759589

Email:  <mailto:steve@comproom.co.uk> steve@comproom.co.uk

Web:  <http://www.comproom.co.uk/> http://www.comproom.co.uk

**Comment by Kenshino** [comment] 2016-02-07 10:12
Yup doesn't work. But if anything, looks like a session issue to me

**Comment by comproom** [comment] 2016-02-07 10:13
What’s the best way to solve it then please?  Can I restore tables in WC?  Or can I uninstall/reinstall without losing my data?

 

Thanks.

 

Computer Room Services

77 Exeter Close

Stevenage

Hertfordshire

SG1 4PW

Tel: +44(0)1438-742286

Mob: +44(0)7956-334938

Fax: +44(0)1438-759589

Email:  <mailto:steve@comproom.co.uk> steve@comproom.co.uk

Web:  <http://www.comproom.co.uk/> http://www.comproom.co.uk

**Comment by mikejolley** [comment] 2016-02-07 10:19
Can you comment on github so we don't have to read your email footer every reply :p 

If you go to ?page_id=227&add-to-cart=266 you temporarily get an item.

Really looks like that table is missing, or there is caching/varnish going on on the cart page.

**Comment by mikejolley** [comment] 2016-02-07 10:21
You should post the system status report here too, and rule out the security plugin as a course.

**Comment by comproom** [comment] 2016-02-07 10:21
Sorry, it’s just quicker.  I can remove everything at the bottom so it looks just like a comment.

 

My reall issue is how are normal users like me going to deal with this when they upgrade?  I do still consider this an issue.

**Comment by mikejolley** [comment] 2016-02-07 10:27
> My reall issue is how are normal users like me going to deal with this when they upgrade?  I do still consider this an issue.

This does not affect everyone. I've seen 2 other reports, and one was caused by multisite cookies (fixed) and another server caching rules. Cart pages need to be excluded from cache, or a rule added based on the cookie name.

**Comment by comproom** [comment] 2016-02-07 10:28
Mike,

 

Cart rules are excluded from Wordfence.  I checked myself and checked with them.

**Comment by mikejolley** [comment] 2016-02-07 10:31
Sorry, but if you're not willing to rule out plugin + theme conflicts to narrow down you're issue there isn't much anyone can do here. As I said, the issue is not affecting all users, so its something unique to your setup - you just need to narrow down what that is.

You've also not shared your status report, and technically this issue should have been closed initially because of lack of info and because we don't do general support here. I've left it open so I can see what you're running which doesn't play nice with the new database table.

**Comment by mikejolley** [comment] 2016-02-07 10:32
Wordfence - falcon engine? Some users had to add the cookie to the exclusion rules. I'd need to see your settings ideally once you've confirmed its causing it.

**Comment by comproom** [comment] 2016-02-07 10:33
I’ve ruled out the security plugin by deactivating it.  I even deleted and reinstalled Wordfence after finding WC still didn’t work.

 

System Report Below:-

 

 

### WordPress Environment ###

 

Home URL: http://www.comproom.co.uk

Site URL: http://www.comproom.co.uk

WC Version: 2.5.2

Log Directory Writable: ✔  C:\homepage/wp-content/uploads/wc-logs/

WP Version: 4.4.2

WP Multisite: –

WP Memory Limit: 256 MB

WP Debug Mode: –

Language: en_GB

 

### Server Environment ###

 

Server Info: Apache/2.4.18 (Win64) PHP/7.0.2

PHP Version: 7.0.2

PHP Post Max Size: 8 MB

PHP Time Limit: 30

PHP Max Input Vars: 1000

SUHOSIN Installed: –

MySQL Version: 5.6.11

Max Upload Size: 2 MB

Default Timezone is UTC: ✔

fsockopen/cURL: ✔

SoapClient: ✕ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.

DOMDocument: ✔

GZip: ✔

Multibyte String: ✔

Remote Post: ✔

Remote Get: ✔

 

### Database ###

 

WC Database Version: 2.5.2

: 

woocommerce_sessions: ✔

woocommerce_api_keys: ✔

woocommerce_attribute_taxonomies: ✔

woocommerce_termmeta: ✔

woocommerce_downloadable_product_permissions: ✔

woocommerce_order_items: ✔

woocommerce_order_itemmeta: ✔

woocommerce_tax_rates: ✔

woocommerce_tax_rate_locations: ✔

 

### Active Plugins (7) ###

 

Akismet: by Automattic – 3.1.7

Recent Posts Widget Extended: by Satrya – 0.9.9.5

WooCommerce Disability VAT Exemption: by WooThemes – 1.3.0

WooCommerce: by WooThemes – 2.5.2

WooThemes Helper: by WooThemes – 1.5.9

Wordfence Security: by Wordfence – 6.0.24

Wp Mail Bank: by Tech Banker – 1.36

 

### Settings ###

 

Force SSL: –

Currency: GBP (£)

Currency Position: left

Thousand Separator: ,

Decimal Separator: .

Number of Decimals: 2

 

### API ###

 

API Enabled: ✔

API Version: 3.1.0

 

### WC Pages ###

 

Shop Base: #226 - /?page_id=226

Basket: #227 - /?page_id=227

Checkout: #228 - /?page_id=228

My Account: #229 - /?page_id=229

 

### Taxonomies ###

 

Product Types: external (external)

grouped (grouped)

simple (simple)

variable (variable)

 

 

### Theme ###

 

Name: Responsive Child

Version: 1.0.0

Author URL: http://www.comproom.co.uk

Child Theme: ✔

Parent Theme Name: Responsive

Parent Theme Version: 1.9.7.5 – 1.9.7.7 is available

Parent Theme Author URL: http://cyberchimps.com

WooCommerce Support: ✔

 

### Templates ###

 

Overrides: –

**Comment by comproom** [comment] 2016-02-07 10:35
Mike,

 

Just sent the system report.  I also said I have uninstalled Wordfence completely and it had no effect.

 

Only thing I can think of now is disabling all plugins except WC and then re-enabling them one by one.  But I hope the system report gives you a clue.

**Comment by mikejolley** [comment] 2016-02-07 10:37
Wordfence is the only one that stands out. Some caching plugins can affect sites after being removed however, as they add stuff to wp-config.php and wp-content/ Best to deactivate the caching settings within the plugin, but leave it active.

Show me the rules in your .htaccess file.

And look for any COOKIE_DOMAIN or SITE_URL entries in your wp-config.php file.

@claudiosmweb we should add cookie domain to system status.

**Comment by MattyLB** [comment] 2016-02-07 10:41
I haven't seen this issue after upgrading. Have you always used "plain" permalinks? Also, can you try a 5.x version of PHP after ruling everything else out? Could be a conflict there.

I have seen this same issue when I used WordFence with Falcon Engine enabled. Even after disabling the plugin, I still had cache issues and other lingering problems because I copied the falcon script into my nginx.conf file (others use .htaccess, etc) - either way - I'm in agreement with @mikejolley  that this may be the culprit in the end.

**Comment by comproom** [comment] 2016-02-07 10:45
Mike,

 

Thanks again.

 

Here are my .htaccess rules:-

 

<files wp-config.php>

order allow,deny deny from all

</files>

Options -Indexes

 

Nothing I can find in wp-config.php, though I won’t post it all here, as it has secret keys and such.

**Comment by comproom** [comment] 2016-02-07 10:49
Matt,

 

I can try a 5.x version of PHP a bit later for sure.  Yes I have always used plain permalinks.

 

I also tried the obvious things, setting permas to something else then resetting them.

 

Mike I only posted this here as opposed to general support, as I thought it was a simple matter of something broken.  If it is my setup, I apologise and should have gone to support, but WC has been behaving so well for the last year or so that I was surprised by something that simple breaking.  I hope some of the info you have now helps.

 

Again I come back to the fact that a normal user wouldn’t expect something as simple as the shopping cart to break, but I guess that something to do with sessions as you say has changed.

**Comment by mikejolley** [comment] 2016-02-07 10:50
If you want to email access to do some tests that's fine by me. Still thinking cache but it's easy to debug that with code.

**Comment by comproom** [comment] 2016-02-07 10:55
Mike,

 

I can give you FTP or RDP access if you can Email me privately with your Email address.

 

I am anxious to help you with this, but am not a seasoned developer.

 

Thanks.

**Comment by mikejolley** [comment] 2016-02-07 10:59
My email address is on my GitHub profile.

**Comment by mikejolley** [comment] 2016-02-07 14:57
Closing as we've confirmed this is table related.

**Closed by mikejolley** 2016-02-07 14:57 UTC

**Comment by duvanmonsa** [comment] 2016-06-23 22:17
In the WooCommerce version 2.5 they change the way the sessions works.  
[](https://woocommerce.wordpress.com/2015/10/07/new-session-handler-in-2-5/)

What i did was install this plugin [](https://github.com/kloon/woocommerce-large-sessions) then my cart is not empty any more with guess users. 

I hope it helps someone else.
