### ISSUE TITLE
get_available_variations() returns blank price_html attributes if all variations have the same price

### ISSUE THREAD

**Issue by depquid** [woothemes/woocommerce#7616] opened 2015-03-03 14:42 UTC
I have some products that have variations that are priced the same.  If at least one of the variations is priced differently from the others, everything works fine.  But if all of the variations are the same price, price_html for each variation returned by get_available_variations() is just an empty string.

**Comment by mikejolley** [comment] 2015-03-05 10:18
This is known behaviour. There are 2 price displays for variations; 1 below the title and 1 after selecting a variation. When all prices are identical, the 2nd is removed since it will be a duplicate of the first.

**Closed by mikejolley** 2015-03-05 10:18 UTC

**Comment by Jany-M** [comment] 2018-12-06 16:46
@mikejolley What if we are choosing to hide the first one, for layout /functionality purposes on all products, and use the second one as only way to display prices? Did you not consider that?
Scenarios are too many to arbitrarily just add this _specific_ behaviour.
Let he users decide what to do instead, depending on their needs (as [others](https://github.com/woocommerce/woocommerce/issues/11827) have also expressed)?
