### ISSUE TITLE
Product bug 

### ISSUE THREAD

**Issue by club23bk** [woothemes/woocommerce#31027] opened 2021-10-25 14:34 UTC
**Dears, 

kindly I need help with woocommerce issue, when i add a new product it wont appear neither in the woocommerce dashboard nor in the website, it is really messed up a lot of bugs come the way!

Please I need a help ASAP

Best regards,
Ali**
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by kevinamorim** [comment] 2021-10-25 14:37
This is very vague. Did you try without any additional plugin activated and with the default theme?

**Comment by club23bk** [comment] 2021-10-25 18:40
Hi kevin,

Yes i deactivated all the plugins and im using the hello/elemntor theme,

Im still seeing bugs in the products section when i upload a product
another one disappears, when i click on all products it shows 4 products
and when i click on published products it shows 5 products,

What could be the problem?

Thanks in advance,
Ali

**Comment by club23bk** [comment] 2021-10-25 19:48
Hi Kevin,

I went to wp admin/woocommerce status/log/ fatal error and it showed me
this:

fatal-errors-2021-10-24-1d7c3d2e8fd4178ffd826927c6c4cc80.log

it's something with the woocommerce shipping zone, however im not using the
default woocommerce shipping setting im using DHL express,

I hope you can help me with this

**Comment by rodelgc** [comment] 2021-10-26 06:21
Hi @club23bk,

I couldn't replicate this issue using WC 5.8.0 and the default Twenty Twenty-One theme. As you can see from my screenshot below, I'm able to see my newly added product both in the WP Admin Dashboard and in the Store page, and the total count of products were incremented just fine:
<img width="1313" alt="Screen Shot 2021-10-26 at 2 07 38 PM" src="https://user-images.githubusercontent.com/4509348/138819710-389b8b17-9bf5-4d9b-adb9-0dc9bed23e7c.png">
<img width="1391" alt="Screen Shot 2021-10-26 at 2 08 45 PM" src="https://user-images.githubusercontent.com/4509348/138819735-f4bc22fe-ddf4-47b4-80dc-c777f87c539f.png">

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
﻿
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
﻿
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
﻿
If you confirm the bug, please provide us with clear steps to reproduce it.
﻿
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by rodelgc** 2021-10-26 06:21 UTC
Labels: Bug, status: can't reproduce, type: support request
