### ISSUE TITLE
"Save Changes" dialog prevents editing variations

### ISSUE THREAD

**Issue by lawkwok** [woothemes/woocommerce#9709] opened 2015-11-26 17:53 UTC
When updating prices or deleting variations, the browser asks if you want to save changes first. If you click yes, the variations proceed to be saved, but the intended action of updating price or deleting variations, never gets executed.

Additionally, the dialog pops up even if no changes were made.

**Comment by mikejolley** [comment] 2015-11-30 12:34
I'm not really certain what you're referring to here. This is what happens on my install when editing prices. Note there is no popup unless you attempt to navigate away from the page before saving.

![variations](https://cloud.githubusercontent.com/assets/90977/11471581/a13de5cc-975e-11e5-94a4-a0e6da6adf13.gif)

If it's browser specific or caused by a certain addon or certain version, add to your report. Closing as reproducible for now. cc @claudiosmweb

**Closed by mikejolley** 2015-11-30 12:34 UTC

**Comment by lawkwok** [comment] 2015-12-01 23:42
I cannot reproduce the issue anymore, even though it was happening consistent over the past few weeks. When then issue happened, I was using the bulk edit dropdown. I was able to get the changes to apply more consistently if I first expanded all the variations.

![screen shot 2015-11-30 at 1 16 35 pm](https://cloud.githubusercontent.com/assets/11021583/11517780/b4e231cc-9840-11e5-8eff-bf4858500ece.png)
