### ISSUE TITLE
Using Woocommerce Rest API to create order but when order is created its not applying shipping cost.

### ISSUE THREAD

**Issue by kbharti24** [woothemes/woocommerce#30694] opened 2021-09-10 13:22 UTC
Hello Team, 

I am using  Woocommerce Rest API to create order but when order is created its not applying shipping cost. 

On the woocommerce website end shipping methods are setup, which should apply the shipping cost within order.
It's not calculating the shipping cost by own for API order.  API only have options to send a fixed amount value of shipping in request. But in my case this values calculated based on the Weight of products. 

How Can I do that ?

Thanks

**Comment by tammullen** [comment] 2021-09-11 16:42
Hi @kbharti24 ,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by tammullen** 2021-09-11 16:42 UTC
Labels: type: support request
