### ISSUE TITLE
Coupons with same code return bad data

### ISSUE THREAD

**Issue by arindamgit** [woothemes/woocommerce#10487] opened 2016-03-07 11:41 UTC
Before submitting your issue, please go through the following checklist. Thanks!

- [x] I have searched this repository (top of the page) for the issue and it has not been fixed or reported already.
- [x] I am not asking for support (general support - https://wordpress.org/support/plugin/woocommerce, premium plugin support - https://support.woothemes.com).

FOR BUG REPORTS

- [x] I am using the latest stable release of WooCommerce.
- [ ] I've disabled all plugins to ensure it's a core bug and not a plugin issue.
- [ ] I've switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
- [x] I have grabbed the system status report from WooCommerce > System Status (paste in the area below).

EXPLANATION OF THE ISSUE

WooCommerce Version 2.4.13
API Version v3

STEPS TO REPRODUCE THE ISSUE

1. Create two coupons of the same code. Do this by hand not via API. Make sure the coupon settings are different but just the "code" is same.
2. Fire the /coupons API
3. The result returns just one coupon (the old one) - twice!

SYSTEM STATUS REPORT

### WordPress Environment ###

Home URL: http://dev.preptest.in:8090/wordpress
Site URL: http://dev.preptest.in:8090/wordpress
WC Version: 2.4.13
Log Directory Writable: ✕ To allow logging
make /var/www/html/wordpress/wp-content/uploads/wc-logs/ writable or define a custom WC_LOG_DIR.

WP Version: 4.4.1
WP Multisite: –
WP Memory Limit: 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: 5.5.9-1ubuntu4.14
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.47
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.13
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (7) ###

Hello Dolly: by Matt Mullenweg – 1.6
JSON API User: by Ali Qureshi – 2.0
JSON API: by Dan Phiffer – 1.1.1
WP OAuth Server: by Justin Greer – 3.1.93
WP REST API: by WP REST API Team – 2.0-beta10
WC Vendors: by WC Vendors – 1.8.3
WooCommerce: by WooThemes – 2.4.13

### Settings ###

Force SSL: –
Currency: INR (Rs.)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Clean Box
Version: 0.5 – 1.1 is available
Author URL: http://catchthemes.com/
Child Theme: ✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: Not Declared

### Templates ###

Overrides: –

**Comment by vphat28** [comment] 2016-03-07 11:46
I think we should not create coupons with same code, also it doesn't make sense

**Comment by arindamgit** [comment] 2016-03-07 11:47
I think we should write better code :)

-- 
Arindam Das
AppsWorld Software (P) Ltd 
Room # 848, Level8, RDB Boulevard 
Plot K1, Sector V, Block –EP&GP 
Salt Lake City, Kolkata -700091
Mob: +91.987.471.2712


On 7 March 2016 at 5:16:26 PM, Xavi Nguyen (notifications@github.com) wrote:

I think we should not create coupons with same code, also it doesn't make sense

**Comment by mikejolley** [comment] 2016-03-07 13:03
"we" ;)?  One coupon should return for the code you have a dupe of. As admin states after save:

> Coupon code already exists - customers will use the latest coupon with this code.

The API will see two occurrences of the coupon code, and when getting details will only get the first. This is to be expected. 

The only bug here is with "customers will use the latest coupon with this code"  - its getting the older one instead.

**Comment by arindamgit** [comment] 2016-03-07 13:08
Yes it is the bug!

The problem probably is in the statement - … and when getting details will only get the first

“First” with respect to what? Creation Time, sorted ascending or descending. Pretty open for interpretation.

We = We the developers of the world :)

Hope “we” get a fix in next release.

-- 
Arindam Das
AppsWorld Software (P) Ltd 
Room # 848, Level8, RDB Boulevard 
Plot K1, Sector V, Block –EP&GP 
Salt Lake City, Kolkata -700091
Mob: +91.987.471.2712


On 7 March 2016 at 6:33:17 PM, Mike Jolley (notifications@github.com) wrote:

"we" ;)? One coupon should return for the code you have a dupe of. As admin states after save:

Coupon code already exists - customers will use the latest coupon with this code.

The API will see two occurrences of the coupon code, and when getting details will only get the first. This is to be expected.

The only bug here is with "customers will use the latest coupon with this code" - its getting the older one instead.

**Closed** 2016-03-07 13:08 UTC

**Comment by mikejolley** [comment] 2016-03-07 13:11
>  customers will use the latest coupon with this code.

Fix above.

**Comment by arindamgit** [comment] 2016-03-07 13:12
Super cool. Thanks!!

-- 
Arindam Das
AppsWorld Software (P) Ltd 
Room # 848, Level8, RDB Boulevard 
Plot K1, Sector V, Block –EP&GP 
Salt Lake City, Kolkata -700091
Mob: +91.987.471.2712


On 7 March 2016 at 6:42:05 PM, Mike Jolley (notifications@github.com) wrote:

customers will use the latest coupon with this code.

Fix above.

**Comment by lexzz** [comment] 2021-02-22 09:37
I know this in an old issue but I have a problem with this I cant solve.
One of our webshops keeps showing "Coupon code already exists - customers will use the latest coupon with this code."
Only in the wp-admin area. But this message keeps popping up after each click.

We had a duplicate coupon code but that is deleted now.
How can we get rid of this message?

Hope someone can help, thank you!
