### ISSUE TITLE
Can't change quantity after variation selection

### ISSUE THREAD

**Issue by Asitis** [woothemes/woocommerce#10256] opened 2016-02-03 13:18 UTC
Since 2.5.1 (for sure) there is a bug in selection the quantity of a product after a variation selection, running the latest WooCommerce on Storefront theme and latest Composite Products plugin.

When a user selects a product which has a variable option (such as color or size) and a quantity field for that item, it's no longer possible to move up the quantity from 1 after the selection for the option is made.
If you change the quantity béfore selecting the option, the field does work, but after making a selection it snaps back to one and is unable to change (the field isn't "disabled" but just doesn't change anymore).

I encountered this issue on a production site, and was able to replicate it in on a staging site, disabling all custom code, other plugins and themes. I hoped updating to 2.5.2 would fix it, but it didn't.

![wcissue](https://cloud.githubusercontent.com/assets/9464641/12783268/ba9f4f2e-ca80-11e5-9d75-b976b7879250.jpg)

Edit; tl;dr - this issue seems to be related to not managing stock in Woocommerce, turning it on for both variable product and variations resolves this issue, though it's still unclear why it's needed "all of a sudden".

**Comment by mikejolley** [comment] 2016-02-03 13:28
@Asitis see if that variation has manage stock enabled

**Comment by Asitis** [comment] 2016-02-03 13:40
@mikejolley There is no option of 'manage stock', nowhere in the variation, in the variable product nor the parent (composite) product. Just "In stock" or "Out of stock" dropdowns.

**Comment by mikejolley** [comment] 2016-02-03 14:06
Is stock management off in settings in that case?

**Comment by Asitis** [comment] 2016-02-03 14:36
Aye, it is (always has been), since the client doesn't use it. Turning it on now, on both the variable product as the variation does the trick though. 
Did something change in the code to make this necessary? I guess it would be a workaround to manage stock on every productlevel and allowing backorders, but ofcourse we'd rather not.

**Comment by franticpsyx** [comment] 2016-02-03 15:29
>running the latest WooCommerce on Storefront theme and latest Composite Products plugin.

Is this about Composite Products? There is a known issue caused by `get_stock_quantity` returning `null` in WC 2.5. It will be patched in the next CP version, due for release in the next couple days.

@Asitis If this is about Composite Products, please open a ticket about it - this repository is for core issues only.

**Comment by Asitis** [comment] 2016-02-03 15:50
@franticpsyx I wasn't sure if this was a problem with Composite Products, since the issue came up with a WooCommerce update and seemed to resolve editing only the variable product, not the composite product. But if what you say is true, this could be the case.

**Comment by franticpsyx** [comment] 2016-02-03 15:57
@Asitis Correct :+1: but still - if quantity selectors of Variable Products work correctly in WC core, but not in CP, then it's a CP issue. Please open a ticket and we'll take it from there :)

**Comment by Asitis** [comment] 2016-02-04 08:14
@franticpsyx I'm trying to send a ticket via the Woothemes site, but no matter what I do, there's errors allround (I think something might be amiss in the ticket system). I couldn't find a github for the composite products, is there one?

**Comment by franticpsyx** [comment] 2016-02-04 11:58
@Asitis - there is no public GitHub repo for CP, unfortunately.
There are no known issues with the ticket system that I know of - tickets are coming in all the time just fine. What kind of error(s) are you getting?

**Comment by Asitis** [comment] 2016-02-04 12:09
Hmm, I kept getting "Error occured, try again" over and over again, even after refreshing and emptying cache. But I'll try again!

**Comment by mikejolley** [comment] 2016-02-04 16:48
@kloon ^

**Comment by robgwin** [comment] 2016-02-05 00:10
I think I've hit a similar problem. Let me know if I should open a separate case for this but it seems very similar to the above.

I just installed a brand new WC today on WP 4.3. I have a variable product, with variations for Large, Medium, Small. I do not want to manage stock in WC, so I left Manage Stock unchecked on the main inventory tab. And I'm trying to uncheck Manage Stock for each of the variations, but it won't stick. I uncheck the box, I click Save Changes. The spinner spins for a couple seconds like it's updating, and the Save Changes box goes dark like it saved. And then another couple seconds later, without me doing anything, the variation edit view suddenly collapses. When I re-expand it, Manage Stock is checked again.

Here's a screencast:
https://drive.google.com/file/d/0B3_UuRCY8qAPQ0xwTWFxSERneDg/view?usp=sharing

**Comment by mikejolley** [comment] 2016-02-05 12:00
@robgwin that was fixed in 2.5.2

**Closed by mikejolley** 2016-02-05 12:00 UTC

**Comment by franticpsyx** [comment] 2016-02-05 14:28
@mikejolley - I can't find any changes in WC 2.5.2.

This is the breaking change: https://github.com/woothemes/woocommerce/commit/d93140515621d736ddc0ff296e037d460b2e8759

The method still returns `null`. Not saying that we should change it, but there hasn't been any change in 2.5.2 that I could find.

**Comment by mikejolley** [comment] 2016-02-05 14:38
@franticpsyx my comment was aimed at the last guy who had the save issue we patched. @claudiosmweb  ^

**Comment by robgwin** [comment] 2016-02-05 17:10
@mikejolley So it was, sorry!
