### ISSUE TITLE
Selling out of stock and going to -1

### ISSUE THREAD

**Issue by gidhublan** [woothemes/woocommerce#40192] opened 2023-09-15 06:06 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The sentence "'Allow backorders?' option is selected as 'Do not allow,' and in the store settings, it is set as 'Out of stock threshold 0.' Sometimes, products go down to -1 in stock.

### Expected behavior

After the stock reaches 0, it should not go down to -1.

### Actual behavior

The product, which initially has 1 item in stock, becomes 0 in the same order records, and then -1.

### Steps to reproduce

![Ekran Resmi 2023-09-15 09 04 30](https://github.com/woocommerce/woocommerce/assets/133167168/4718771e-2ca4-4cea-9986-95de9ec52576)

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.xxxxxxx.com
Site address (URL): https://www.xxxxxxx.com
WC Version: 8.1.0
REST API Version: ✔ 8.1.0
WC Blocks Version: ✔ 10.9.3
Action Scheduler Version: ✔ 3.6.2
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: tr_TR
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 3000
PHP Max Input Vars: 1000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.28-MariaDB
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.1.0
WC Database Prefix: wp_
Toplam veritabanı boyutu: 9489.56MB
Veritabanı veri boyutu: 5464.87MB
Veritabanı indis boyutu: 4024.69MB
wp_woocommerce_sessions: Veriler: 45.06 MB + Dizin: 1.02 MB + Motor InnoDB
wp_woocommerce_api_keys: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Veriler: 0.02 MB + Dizin: 0.17 MB + Motor InnoDB
wp_woocommerce_order_items: Veriler: 130.66 MB + Dizin: 39.58 MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Veriler: 1000.98 MB + Dizin: 679.75 MB + Motor InnoDB
wp_woocommerce_tax_rates: Veriler: 0.02 MB + Dizin: 0.08 MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Veriler: 0.02 MB + Dizin: 0.05 MB + Motor InnoDB
wp_woocommerce_shipping_zones: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_woocommerce_payment_tokens: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Veriler: 0.02 MB + Dizin: 0.05 MB + Motor InnoDB
wp_woocommerce_log: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_actionscheduler_actions: Veriler: 58.06 MB + Dizin: 36.16 MB + Motor InnoDB
wp_actionscheduler_claims: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_actionscheduler_groups: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_actionscheduler_logs: Veriler: 46.06 MB + Dizin: 21.03 MB + Motor InnoDB
wp_commentmeta: Veriler: 1.48 MB + Dizin: 0.61 MB + Motor InnoDB
wp_comments: Veriler: 510.00 MB + Dizin: 316.59 MB + Motor InnoDB
wp_easywpsmtp_debug_events: Veriler: 0.09 MB + Dizin: 0.00 MB + Motor InnoDB
wp_easywpsmtp_tasks_meta: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_failed_jobs: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_intense_ups_entegrasyon_etiketler: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_intense_ups_entegrasyon_ilce_kodlari: Veriler: 0.33 MB + Dizin: 0.00 MB + Motor InnoDB
wp_intense_ups_entegrasyon_islem_loglari: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_intense_yurtici_kargo_entegrasyon_bildirimleri: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_intense_yurtici_kargo_entegrasyon_denetleme_kuyruk: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_intense_yurtici_kargo_entegrasyon_islem_loglari: Veriler: 19.55 MB + Dizin: 0.00 MB + Motor InnoDB
wp_ism_out_of_stock_request: Veriler: 7.52 MB + Dizin: 10.02 MB + Motor InnoDB
wp_ism_sent_email: Veriler: 3.52 MB + Dizin: 0.00 MB + Motor InnoDB
wp_iyzico_card: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_iyzico_order: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_links: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_mailchimp_carts: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_mailchimp_jobs: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_options: Veriler: 130.44 MB + Dizin: 36.41 MB + Motor InnoDB
wp_postmeta: Veriler: 2626.92 MB + Dizin: 2345.78 MB + Motor InnoDB
wp_posts: Veriler: 254.78 MB + Dizin: 120.19 MB + Motor InnoDB
wp_queue: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_css: Veriler: 0.13 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_css_bkp: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_layer_animations: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_layer_animations_bkp: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_navigations: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_navigations_bkp: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_sliders: Veriler: 0.11 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_sliders_bkp: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_slides: Veriler: 0.34 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_slides_bkp: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_static_slides: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_revslider_static_slides_bkp: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_smush_dir_images: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_termmeta: Veriler: 0.16 MB + Dizin: 0.16 MB + Motor InnoDB
wp_terms: Veriler: 0.14 MB + Dizin: 0.16 MB + Motor InnoDB
wp_term_relationships: Veriler: 5.25 MB + Dizin: 3.23 MB + Motor InnoDB
wp_term_taxonomy: Veriler: 0.11 MB + Dizin: 0.16 MB + Motor InnoDB
wp_usermeta: Veriler: 337.89 MB + Dizin: 211.45 MB + Motor InnoDB
wp_users: Veriler: 17.55 MB + Dizin: 14.55 MB + Motor InnoDB
wp_wccs_conditions: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_wccs_condition_meta: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_wc_admin_notes: Veriler: 0.11 MB + Dizin: 0.00 MB + Motor InnoDB
wp_wc_admin_note_actions: Veriler: 0.08 MB + Dizin: 0.02 MB + Motor InnoDB
wp_wc_category_lookup: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_wc_customer_lookup: Veriler: 23.55 MB + Dizin: 16.05 MB + Motor InnoDB
wp_wc_download_log: Veriler: 0.02 MB + Dizin: 0.05 MB + Motor InnoDB
wp_wc_orders: Veriler: 0.02 MB + Dizin: 0.11 MB + Motor InnoDB
wp_wc_orders_meta: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_wc_order_addresses: Veriler: 0.02 MB + Dizin: 0.06 MB + Motor InnoDB
wp_wc_order_coupon_lookup: Veriler: 4.52 MB + Dizin: 4.98 MB + Motor InnoDB
wp_wc_order_operational_data: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_wc_order_product_lookup: Veriler: 116.64 MB + Dizin: 90.27 MB + Motor InnoDB
wp_wc_order_stats: Veriler: 106.67 MB + Dizin: 57.63 MB + Motor InnoDB
wp_wc_order_tax_lookup: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_wc_product_attributes_lookup: Veriler: 2.47 MB + Dizin: 2.20 MB + Motor InnoDB
wp_wc_product_download_directories: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_wc_product_meta_lookup: Veriler: 8.52 MB + Dizin: 12.72 MB + Motor InnoDB
wp_wc_rate_limits: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_wc_reserved_stock: Veriler: 1.27 MB + Dizin: 0.00 MB + Motor InnoDB
wp_wc_tax_rate_classes: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_wc_webhooks: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_wpfront_ure_login_redirect: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_wpfront_ure_options: Veriler: 0.02 MB + Dizin: 0.03 MB + Motor InnoDB
wp_wpfront_ure_post_type: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_wpfront_ure_taxonomy: Veriler: 0.02 MB + Dizin: 0.02 MB + Motor InnoDB
wp_wpmm_subscribers: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_wpr_rocket_cache: Veriler: 2.50 MB + Dizin: 2.50 MB + Motor InnoDB
wp_wpr_rucss_used_css: Veriler: 0.02 MB + Dizin: 0.11 MB + Motor InnoDB
wp_yikes_easy_mc_forms: Veriler: 0.02 MB + Dizin: 0.00 MB + Motor InnoDB
wp_yith_wcwl: Veriler: 0.17 MB + Dizin: 0.06 MB + Motor InnoDB
wp_yith_wcwl_lists: Veriler: 0.14 MB + Dizin: 0.20 MB + Motor InnoDB

### Post Type Counts ###

attachment: 23238
la_block: 2
la_portfolio: 5
la_team_member: 8
la_testimonial: 1
nav_menu_item: 91
oembed_cache: 1
page: 35
post: 2
product: 8117
product_variation: 26731
revision: 4756
shop_coupon: 46934
shop_order: 514018
shop_order_refund: 12661
wp_global_styles: 1
wp_navigation: 1
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

Advanced Cron Manager: (BracketSpace) – 2.5.2
Akismet Anti-spam: Spam Protection: (Automattic - Anti-spam Team) – 5.3
AppMySite: (AppMySite) – 3.10.0
WooCommerce için ödeme yöntemleri ücretleri ve indirimleri: (Tyche Softwares) – 2.10.3
Contact Form 7: (Takayuki Miyoshi) – 5.8
Disable Cart Fragments: (Optimocha) – 2.3
Discount Rules and Dynamic Pricing for WooCommerce: (Discount Team) – 5.21.0
Easy WP SMTP: (Easy WP SMTP) – 2.1.2
Envato Market: (Envato) – 2.0.10
Hezarfen For Woocommerce: (Intense Yazılım Ltd.) – 1.6.2
In Stock Mailer for WooCommerce: (Frank Pagano) – 2.1.1
Intense WooCommerce Yurtiçi Kargo Entegrasyonu: (Intense Yazılım) – 4.0.0
Intense Kargo Takip Modülü: (Intense Yazılım Int. Tekn. San. ve Tic. Ltd. Şti.) – 1.2.14
iyzico WooCommerce: (iyzico) – 3.2.6
WPBakery Page Builder: (Michael M - WPBakery.com) – 6.4.1
LA Studio Core: (LA Studio) – 2.2.5
OnSale Page for WooCommerce: (wpgenie) – 1.1.1
Precise Package Demo Data: (LA Studio) – 1.0.1
Slider Revolution: (ThemePunch) – 6.2.23
StorePep WooCommerce App Integration: (StorePep) – 2.1.6
Variation Swatches for WooCommerce: (AOVUP) – 2.2.0
WC Hide Shipping Methods: (Rynaldo Stoltz) – 1.5
Bulk Price Update for Woocommerce: (TechnoCrackers) – 2.2.2
Woo Product Category Discount Pro: (WooExtend) – 3.13
WooCommerce Shipping & Tax: (WooCommerce) – 2.3.4
WooCommerce: (Automattic) – 8.1.0
LightStart - Maintenance Mode, Coming Soon and Landing Page Builder: (Themeisle) – 2.6.8
WP Rocket: (WP Media) – 3.15.0.1
Smush Pro: (WPMU DEV) – 3.14.2
WPFront User Role Editor: (Syam Mohan) – 3.2.1.11184
WPMU DEV Dashboard: (WPMU DEV) – 4.11.21
Easy Forms for Mailchimp: (YIKES
Inc.) – 6.8.9

YITH WooCommerce Compare: (YITH) – 2.31.0
YITH WooCommerce Social Login: (YITH) – 1.4.8

### Inactive Plugins (1) ###

WC Kredi Kartı ile Kapıda Ödeme: (Murat Bütün) – 1.1.9

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: TRY (₺)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Mağaza giriş sayfası: #774 - /shop/
Sepet sayfası: #775 - /cart/
Ödeme sayfası: #776 - /checkout/
Hesabım sayfası: #777 - /my-account/
Şartlar ve koşullar: ❌ Sayfa ayarlanmamış

### Theme ###

Name: Precise
Version: 1.8
Author URL: http://themeforest.net/user/LA-Studio?ref=LA-Studio
Child Theme: ❌ – WooCommerce'i kendinizin oluşturmadığı ana bir temada düzenliyorsanız
yardımcı bir tema kullanmanızı öneririz. Bkz.: Nasıl yardımcı tema oluşturulur?

WooCommerce Support: ✔

### Templates ###

Overrides: precise/woocommerce/archive-product.php
precise/woocommerce/cart/cross-sells.php
precise/woocommerce/content-product.php
precise/woocommerce/content-single-product.php
precise/woocommerce/global/quantity-input.php
precise/woocommerce/loop/add-to-cart.php
precise/woocommerce/loop/loop-end.php
precise/woocommerce/loop/loop-start.php
precise/woocommerce/loop/orderby.php
precise/woocommerce/loop/pagination.php
precise/woocommerce/loop/sale-flash.php
precise/woocommerce/myaccount/form-login.php
precise/woocommerce/product-searchform.php
precise/woocommerce/single-product/product-image.php
precise/woocommerce/single-product/product-thumbnails.php
precise/woocommerce/single-product/related.php
precise/woocommerce/single-product/tabs/tabs.php
precise/woocommerce/single-product/up-sells.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-09-15 13:11:06 +03:00
Options: ✔
Notes: 188
Onboarding: completed

### Action Scheduler ###

İptal edildi: 1
Oldest: 2023-09-15 05:37:58 +0000
Newest: 2023-09-15 05:37:58 +0000

Tamamla: 108.440
Oldest: 2023-08-15 05:46:04 +0000
Newest: 2023-09-15 05:44:13 +0000

Başarısız: 649
Oldest: 2022-11-01 17:33:07 +0000
Newest: 2023-09-15 05:41:59 +0000

Devam ediyor: 1
Oldest: –
Newest: –

Bekleyen: 45
Oldest: 2023-09-15 05:43:26 +0000
Newest: 2023-09-15 09:44:14 +0000

### Status report information ###

Generated at: 2023-09-15 08:44:31 +03:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment] 2023-09-15 09:24
Hello @gidhublan,

Thank you for raising the issue. I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. 

Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [[Storefront](https://en-gb.wordpress.org/themes/storefront/)](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

If the problem persists, please feel free to reopen this issue.

**Closed as completed by lsinger** 2023-09-15 09:24 UTC
Labels: Bug, type: community contribution

**Comment by gidhublan** [comment] 2023-09-15 09:37
Since the site is actively engaged in sales, changing the theme is not possible. It's not very feasible to individually deactivate each plugin to identify potential conflicts, as it affects the site's functionality. My site is very busy and generates a high volume of sales.

If I know the hooks where this conflict might occur, I can search within the theme or plugin code.

**Comment by gidhublan** [comment] 2023-09-17 07:32
Since the site is actively engaged in sales, changing the theme is not possible. It's not very feasible to individually deactivate each plugin to identify potential conflicts, as it affects the site's functionality. My site is very busy and generates a high volume of sales.

If I know the hooks where this conflict might occur, I can search within the theme or plugin code.

**Comment by lsinger** [comment] 2023-09-18 10:29
Thank you, @gidhublan. 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

It sounds to me like you might want to try one of the following: 

- contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/) (if you are a paying customer of WooCommerce)
- ask a question in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/)
- post to the [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/), or 
- hire a developer to look into this further.
