### ISSUE TITLE
Can't generate new REST API keys

### ISSUE THREAD

**Issue by Konamiman** [woothemes/woocommerce#34764] opened 2022-09-21 14:18 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The bug is present in WooCommerce `trunk` as of the time of writing this (it's not present in the latest released version, 6.9.3)

It's not possible to generate an API key through the WooCommerce - Settings - Advanced - REST API - Add key button (URL: `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=keys&create-key=1`), the screen keeps showing a progress indicator forever and the network inspeactor shows that the `POST /wp-admin/admin-ajax.php` request (action: `woocommerce_update_api_key`) has resulted in a 500 error.

The error is thrown in the backend by `WCAdminAssets::get_script_asset_filename` while trying to resolve the path for the file `assets/client/admin/wp-admin-scripts/payment-method-promotions`. The `assets/client/admin` folder exists but it's empty.

This is also causing the E2E tests to fail, since as part of the tests setup a key is created using the said settings page.

### Expected behavior

The requested file exists and the error doesn't appear, the key creation succeeds and so do the E2E tests.

### Steps to reproduce

1. Start with a fresh clone of the WooCommerce repository in `trunk`
2. `pnpm install`, then `pnpm run build`
3. Notice how `plugins/woocommerce/assets/client/admin` folder exists and is empty
4. Try to create a REST API key by going to Settings - Advanced - REST API - Add key and see the described behavior

Possibly related: `pnpm run build` does actually succeed for 22 tasks and fails for the last one:

> ERROR in client/tasks/fills/tax/woocommerce-tax/plugins.tsx:77:5
woocommerce/client/admin:turbo:build: TS2322: Type '{ onComplete: (activatedPlugins: string[], response: InstallPluginsResponse) => void; onError: (errors: unknown, response: unknown) => void; onSkip: () => void; skipText: string; onAbort: () => void; abortText: string; }' is not assignable to type 'IntrinsicAttributes & { children?: ReactNode; }'.

In WooCommerce 6.9.3 22 tasks succeed and none fails.

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mattsherman** [comment] 2022-09-21 16:51
Thanks, @Konamiman — I’ll take a look and fix this.

**Comment by mattsherman** [comment] 2022-09-21 19:15
@Konamiman 

> Possibly related: pnpm run build does actually succeed for 22 tasks and fails for the last one

I just did a new clone. I get `Tasks:    26 successful, 26 total` when I run `pnpm run build`. I wonder why things are different for us?

**Comment by mattsherman** [comment] 2022-09-21 19:39
@Konamiman I can't reproduce this.

I did...

```
rm -rf woocommerce-monorepo
git clone git@github.com:woocommerce/woocommerce.git woocommerce-monorepo
cd woocommerce-monorepo
nvm use
pnpm install
pnpm run build
```

Build succeeds with...

```
 Tasks:    26 successful, 26 total
Cached:    4 cached, 26 total
  Time:    48.31s 
```

The `pnpm run build` command is the step where the files under `plugin/woocommerce/assets/client/admin` get generated. They do not exist prior to that.

**Comment by Konamiman** [comment] 2022-09-22 07:35
Looks like updating pnpm to v7 and doing a `git clean -fdx` on the repo before trying the install+build fixes the issue. The question then is why it's failing in https://github.com/woocommerce/woocommerce/pull/34727 (e.g. https://github.com/woocommerce/woocommerce/actions/runs/3081381529/jobs/4979862394 )

**Comment by mattsherman** [comment] 2022-09-23 11:51
@Konamiman I'm closing this one. If you are still having build issues, please open up a new specific issue. Thanks!

**Closed as completed by mattsherman** 2022-09-23 11:51 UTC
Labels: Bug, plugin: woocommerce
