### ISSUE TITLE
Product Quantity Update - Internet Explorer

### ISSUE THREAD

**Issue by DustinHartzler** [woothemes/woocommerce#11811] opened 2016-08-30 13:24 UTC
## EXPLANATION OF THE ISSUE

We’re having an issue with the upgrade to WooCommerce 2.6.4 (but only with Internet Explorer, tested on IE 11) when we change the quantity of any given item directly in the shopping cart. When you highlight the quantity, then change the number and hit enter, it asks you for a coupon code as you can see here: http://screencast.com/t/Q3MyFf8Ig What’s weird is that it only happens when you hit the enter button, not when you click on the “Update Cart” button.

We have noticed that it occurs on multiple WooCommerce sites we know of, but only the ones with AJAX cart update, not the ones that do a standard form submission/POST back to the cart to update.

Dev site is running with Storefront and all plugins deactivated.

**Comment by mikejolley** [comment] 2016-09-06 09:07
@jameskoster can you take a look at this?

**Comment by mikejolley** [comment] 2016-09-06 11:05
@coderkevin Works fine in Chrome, but I don't have IE to test this. Would you care to take a look please?

**Comment by DustinHartzler** [comment] 2016-09-12 23:51
@coderkevin have you had a chance to take a look at thisL

**Comment by coderkevin** [comment] 2016-09-13 02:53
@DustinHartzler I was just setting up a Windows machine today to test it on. I'll reply back here soon after I get this reproduced and looking for a root cause.

**Comment by coderkevin** [comment] 2016-09-13 20:38
I have reproduced this issue on IE. It is, in fact, interpreting the <Enter> submit on the Quantity as a submit on the Apply Coupon button. I'm not exactly sure of the best way to correct this, but I'll try a couple courses of action over the next day or two and report back here.

**Comment by coderkevin** [comment] 2016-09-22 21:04
Fixed in https://github.com/woothemes/woocommerce/pull/11963

**Closed** 2016-09-22 22:17 UTC
Labels: Bug
