### ISSUE TITLE
Shipping Zones

### ISSUE THREAD

**Issue by Omar-Hamsho** [woothemes/woocommerce#37199] opened 2023-03-13 20:39 UTC
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hi
I work with more than one shipping company
Each shipping company has a group of regions, and each group has one price according to weight.
I want to enter the regions in each freight company as a group. To make it easier for me to update prices.

### Expected behavior

I expected all shipping options to appear

### Actual behavior

Picture as an example:
I work with DHL and PTT for shipping to Germany
But the store always shows the highest shipping company in the list (DHL appears because it is at the top, and PTT does not appear)

### Steps to reproduce

![3 142436](https://user-images.githubusercontent.com/127793030/224825687-0bce6c87-146d-4f3f-a834-dd76bbcf03ab.png)
![142651](https://user-images.githubusercontent.com/127793030/224825692-05919674-a19b-4090-9240-0e1da4a7d83d.png)

### WordPress Environment

`
### wp-core ###

version: 6.1.1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 1
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/u218563898/domains/merhababookstore.com/public_html
wordpress_size: 60.88 MB (63832478 bytes)
uploads_path: /home/u218563898/domains/merhababookstore.com/public_html/wp-content/uploads
uploads_size: 119.52 MB (125325047 bytes)
themes_path: /home/u218563898/domains/merhababookstore.com/public_html/wp-content/themes
themes_size: 30.14 MB (31606993 bytes)
plugins_path: /home/u218563898/domains/merhababookstore.com/public_html/wp-content/plugins
plugins_size: 291.51 MB (305670102 bytes)
database_size: 31.64 MB (33177600 bytes)
total_size: 533.69 MB (559612220 bytes)

### wp-active-theme ###

name: Wooma (wooma)
version: 1.0.4
author: Ninetheme
author_website: http://ninetheme.com/about
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, wooma, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, editor-style, automatic-feed-links, title-tag, custom-background, custom-header, html5, admin-bar, menus, widgets
theme_path: /home/u218563898/domains/merhababookstore.com/public_html/wp-content/themes/wooma
auto_update: Disabled

### wp-themes-inactive (3) ###

Twenty Twenty-One: version: 1.7, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Three: version: 1.0, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Two: version: 1.3, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (1) ###

wp-hide-loader.php: author: (undefined), version: (undefined)

### wp-plugins-active (22) ###

Cargo Tracking for WooCommerce: version: 1.0.5, author: İlhan Aydınlı, Auto-updates disabled
Checkout Field Editor and Manager for WooCommerce: version: 2.2.9, author: Acowebs, Auto-updates disabled
Contact Form 7: version: 5.7.4, author: Takayuki Miyoshi, Auto-updates disabled
Customer Reviews for WooCommerce: version: 5.19.0, author: CusRev, Auto-updates disabled
Elementor: version: 3.11.4, author: Elementor.com, Auto-updates disabled
Envato Market: version: 2.0.8, author: Envato, Auto-updates disabled
Eticsoft SanalPOS PRO! Multi Payment Gateway: version: 2.7.1.0, author: eticsoft.com, Auto-updates disabled
Flexible Shipping: version: 4.19.1, author: Octolize, Auto-updates disabled
Google Listings and Ads: version: 2.4.0, author: WooCommerce, Auto-updates disabled
Hostinger: version: 1.1.0, author: Hostinger, Auto-updates disabled
Jetpack: version: 11.9, author: Automattic, Auto-updates disabled
Kargo Takip Türkiye: version: 0.1.00, author: Unbelievable.Digital, Auto-updates disabled
MailPoet: version: 4.8.0, author: MailPoet, Auto-updates disabled
Pinterest for WooCommerce: version: 1.2.14, author: WooCommerce, Auto-updates disabled
Safe SVG: version: 2.0.3, author: 10up, Auto-updates disabled
Template Library and Redux Framework: version: 4.3.26, author: Extendify, Auto-updates disabled
Use Any Font: version: 6.3.01, author: Dnesscarkey, Auto-updates disabled
WooCommerce: version: 7.4.1, author: Automattic, Auto-updates disabled
WooCommerce Weight Based Shipping: version: 5.4.1, author: weightbasedshipping.com, Auto-updates disabled
Wooma Elementor Addons: version: 1.0.3, author: Ninetheme, Auto-updates disabled
WPForms Lite: version: 1.8.0.2, author: WPForms, Auto-updates disabled
WP Hide & Security Enhancer: version: 1.9.9, author: Nsp Code, Auto-updates disabled

### wp-plugins-inactive (8) ###

Akismet Anti-Spam: version: 5.0.2, author: Automattic, Auto-updates disabled
All-in-One WP Migration: version: 7.72, author: ServMask, Auto-updates disabled
Google Analytics for WordPress by MonsterInsights: version: 8.12.1, author: MonsterInsights (latest version: 8.13.0), Auto-updates disabled
LiteSpeed Cache: version: 5.3.3, author: LiteSpeed Technologies, Auto-updates disabled
OptinMonster: version: 2.13.0, author: OptinMonster Popup Builder Team, Auto-updates disabled
Site Kit by Google: version: 1.95.0, author: Google (latest version: 1.96.0), Auto-updates disabled
WPC Smart Compare for WooCommerce: version: 5.4.0, author: WPClever, Auto-updates disabled
WPC Smart Wishlist for WooCommerce: version: 4.6.2, author: WPClever, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1808
imagemagick_version: ImageMagick 7.1.0-20 Q16-HDRI x86_64 2022-01-22 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 1024M
upload_max_filesize: 1024M
max_effective_size: 1 GB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 1,007 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 196608
	imagick::RESOURCETYPE_MAP: 1,007 GB
	imagick::RESOURCETYPE_MEMORY: 503 GB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, ASHLAR, AVI, AVIF, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUBE, CUR, CUT, DATA, DCM, DCR, DCRAW, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FARBFELD, FAX, FF, FITS, FL32, FLV, FRACTAL, FTS, FTXT, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, HALD, HDR, HEIC, HEIF, HISTOGRAM, HRZ, HTM, HTML, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, KERNEL, LABEL, M2V, M4V, MAC, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORA, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PHM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PS, PS2, PS3, PSB, PSD, PTIF, PWP, QOI, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGB565, RGBA, RGBO, RGF, RLA, RLE, RMF, RSVG, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TM2, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YAML, YCbCr, YCbCrA, YUV
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 4.18.0-425.3.1.lve.el8.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 8.0.28 64bit
php_sapi: litespeed
max_input_variables: 3000
time_limit: 120
memory_limit: 1024M
max_input_time: 120
upload_max_filesize: 1024M
php_post_max_size: 1024M
curl_version: 7.84.0 OpenSSL/1.1.1p
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.6.12-MariaDB-cll-lve
client_version: mysqlnd 8.0.28
max_allowed_packet: 1073741824
max_connections: 2000

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/u218563898/domains/merhababookstore.com/public_html/wp-content
WP_PLUGIN_DIR: /home/u218563898/domains/merhababookstore.com/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 1024M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable
0: Writable

### redux-framework ###

version: 4.3.26
installation: plugin
data directory: /home/u218563898/domains/merhababookstore.com/public_html/wp-content/plugins/redux-framework/redux-core/
browser: 
	Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
	Browser: Chrome
	Version: 111.0.0.0
	Platform: Windows

### redux-instance-wooma ###

opt_name: wooma
global_variable: wooma
dev_mode: false
ajax_save: true
page_slug: Wooma
page_permissions: manage_options
menu_type: submenu
page_parent: ninetheme_theme_manage
compiler: true
output: true
output_tag: true
templates_path: undefined
extensions: 
	Accordion: 1.0.1
	Custom Fonts: 2.0.0
	Customizer: 4.0.0
	Datetime: 2.0.0
	Google Maps: 2.0.0
	Import Export: 4.0.0
	Js Button: 2.0.0
	Metaboxes: 4.0.0
	Multi Media: 4.3.15
	Options Object: 4.0.0
	Repeater: 4.3.7
	Search: 3.4.5
	Shortcodes: 4.3.5
	Social Profiles: 4.3.17
	Widget Areas: 1.0.0

### jetpack ###

site_id: 216568318
ssl_cert: No
time_diff: undefined
version_option: 11.9:1678702476
old_version: 11.9:1678702476
public: Public
master_user: #1 merhabayayimcilik@gmail.com
current_user: #1 merhabayayimcilik@gmail.com
tokens_set: Blog User
blog_token: pfSPSO(l3XJqI%Cnw1sz29&Xpvlh&Tyv
user_token: 9Hj$Forh!Z0em#BiwQeQxv*r@$HYXpe&
version: 11.9
jp_plugin_dir: /home/u218563898/domains/merhababookstore.com/public_html/wp-content/plugins/jetpack/
plan: free
protect_header: {"trusted_header":"REMOTE_ADDR","segments":1,"reverse":false}
full_sync: {"started":"Mon, 13 Mar 2023 10:15:22 +0000","finished":"Mon, 13 Mar 2023 10:15:33 +0000","progress":{"options":{"finished":true},"functions":{"finished":true},"constants":{"finished":true},"users":{"total":"1","sent":1,"finished":true,"last_sent":"1"},"network_options":{"finished":true}},"config":{"options":true,"functions":true,"constants":true,"users":[1],"network_options":true}}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/merhababookstore.com","siteurl":"https:\/\/merhababookstore.com","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.

### wpforms ###

version: 1.8.0.2
lite: Mar 11, 2023 @ 9:41pm
upload_dir: Writable
total_forms: undefined
total_submissions: undefined

`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment] 2023-11-28 13:16
Hey @Omar-Hamsho, are you manually setting up the shipping via Flat Rate methods? If so this is totally achievable to do and WooCommerce should always present all the matches in a matching zone.

I believe where you are making the mistake is that you are confusing what a zone is vs what a shipping method is and defining shipping methods as zones.

A zone should represent a country and then within that zone, you should define multiple shipping methods that should be presented if a customer address matches the zone. A customer address will only match on a single zone, but all shipping methods inside that zone will be displayed to the customer, unless there are rules tied to the method like you can do with free shipping.

![EYxlcR.png](https://github.com/woocommerce/woocommerce/assets/271630/dd0e0950-7abc-4cad-8136-fabe7eb09666)
![RBgard.png](https://github.com/woocommerce/woocommerce/assets/271630/83b8227d-5e2c-4610-bb08-a1db27fd442f)

Closing this as it is not a bug but rather a configuration issue.

**Closed as completed by kloon** 2023-11-28 13:16 UTC
Labels: Bug, Shipping, type: community contribution, Escargot
