### ISSUE TITLE
When Hide out of stock items from the catalog is enabled, product category pages show incorrect results

### ISSUE THREAD

**Issue by amElnagdy** [woothemes/woocommerce#31773] opened 2022-01-31 16:03 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When you enable this option under WooCommerce → Settings → Products → Inventory: `Hide out of stock items from the catalog`, out of stock products will count towards the showing result as shown

![https://d.pr/i/piX1Ec](https://d.pr/i/piX1Ec+) 
Full Size: https://d.pr/i/piX1Ec

It's counting 5 because there's an out of stock product in this product category:

![https://d.pr/i/YNonbg](https://d.pr/i/YNonbg+) 
Full Size: https://d.pr/i/YNonbg

### Expected behavior

It should say `Showing all 4 results` where it says: `Showing all 5 results` in the above screenshot

### Actual behavior

It's showing `Showing all 5 results` instead of `Showing all 4 results`

### Steps to reproduce

1. Set a product to be out of stock.
2. Enable this option under WooCommerce → Settings → Products → Inventory: `Hide out of stock items from the catalog`.
3. Open a product category page and check the results count.

### WordPress Environment

`
### WordPress Environment ###
WC Version: 6.1.1
REST API Version: ✔ 6.1.1
WC Blocks Version: ✔ 6.5.2
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ✔
WP Version: 5.9
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.27
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.80.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.32-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.1
WC Database Prefix: wp_
Total Database Size: 25.17MB
Database Data Size: 15.92MB
Database Index Size: 9.25MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.22MB + Index: 0.23MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.61MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.28MB + Index: 0.25MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ariadminer_connections: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_aw_pq_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aw_pq_faq_category_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aw_pq_translations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.22MB + Index: 0.22MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.02MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 2.52MB + Index: 3.66MB + Engine InnoDB
wp_posts: Data: 0.34MB + Index: 0.20MB + Engine InnoDB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_wpr_rucss_resources: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wps_hit: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wps_index: Data: 0.33MB + Index: 0.48MB + Engine InnoDB
wp_wps_key: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wps_object_term: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wps_query: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_uri: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_user_agent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

addify_quote: 3
addify_rfq: 1
attachment: 62
aw_workflow: 10
bookable_person: 7
bookable_resource: 9
customize_changeset: 5
custom_css: 1
def_reg_fields: 10
event_ticket: 4
fme_qifw_woocomerce: 1
global_product_addon: 1
page: 24
post: 1
product: 137
product_variation: 249
revision: 24
shop_coupon: 15
shop_order: 156
shop_order_refund: 8
shop_subscription: 28
wcpf_item: 5
wcpf_project: 1
wc_booking: 7
wc_membership_plan: 1
wc_user_membership: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 6.1.1

### Inactive Plugins (95) ###

Akismet Anti-Spam: by Automattic – 4.2.2
Amazon Product Importer: by Nxtal – 1.2.4 (update to version 2.0.2 is available)
ARI Adminer: by ARI Soft – 1.2.3
AutomateWoo: by WooCommerce – 5.5.8
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.6.2
B2B for WooCommerce: by Addify – 1.9.0 (update to version 2.0.0 is available)
Bookings Helper: by WooCommerce – 1.0.3
Braintree for WooCommerce Payment Gateway: by WooCommerce – 2.6.2
Classic Editor: by WordPress Contributors – 1.6.2
Code Snippets: by Code Snippets Pro – 2.14.3
Custom Start Date For WooCommerce Subscriptions: by Launch & Sell – 1.1
Email Customizer Pro For WooCommerce: by StoreApps – 3.2.0 (update to version 3.3.0 is available)
Facebook for WooCommerce: by Facebook – 2.6.9
Facebook for WooCommerce - settings tools: by SkyVerge – 1.0.0
Follow-Up Emails: by WooCommerce – 4.9.15 (update to version 4.9.17 is available)
Health Check & Troubleshooting: by The WordPress.org community – 1.4.5
Instructor Helper For WooCommerce Bookings: by Jesse Pearson – 1.0.1
Jetpack: by Automattic – 10.6-beta
Loco Translate: by Tim Whitlock – 2.5.5
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.6
Multi-Carrier ShipStation Shipping for WooCommerce: by OneTeamSoftware – 1.4.6
Pinterest for WooCommerce: by WooCommerce – 1.0.1 (update to version 1.0.3 is available)
Product Filters for WooCommerce: by WooCommerce – 1.2.5 (update to version 1.2.8 is available)
Product Questions And FAQ By Aheadworks: by Aheadworks – 2.0.0
Quantity Buttons for WooCommerce: by FME Addons – 1.0.1
Quick Buy Now Button for WooCommerce: by Addify – 1.3.6 (update to version 1.3.7 is available)
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Request a Quote for WooCommerce: by Addify – 2.3.0 (update to version 2.4.0 is available)
Say What?: by Ademti Software – 2.0.2
Storefront Powerpack: by WooCommerce – 1.6.1
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.48
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.25
WooCommerce Additional Variation Images: by WooCommerce – 1.9.0
WooCommerce Advanced Notifications: by WooCommerce – 1.2.34 (update to version 1.2.36 is available)
WooCommerce Affirm Gateway: by WooCommerce – 1.2.2 (update to version 1.3.4 is available)
WooCommerce All Products For Subscriptions: by WooCommerce – 3.2.0
WooCommerce Amazon Pay: by WooCommerce – 2.0.3 (update to version 2.1.0 is available)
WooCommerce AvaTax: by SkyVerge – 1.15.0
WooCommerce Blocks: by Automattic – 6.8.0
WooCommerce Bookings: by WooCommerce – 1.15.50
WooCommerce Box Office: by WooCommerce – 1.1.35 (update to version 1.1.36 is available)
WooCommerce Brands: by WooCommerce – 1.6.25 (update to version 1.6.26 is available)
WooCommerce Cart Add-Ons: by WooCommerce – 2.1.0
WooCommerce Chained Products: by StoreApps – 2.9.9 (update to version 2.11.0 is available)
WooCommerce Checkout Field Editor: by WooCommerce – 1.6.2 (update to version 1.7.0 is available)
WooCommerce Composite Products: by WooCommerce – 8.3.7
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.10.0 (update to version 1.12.0 is available)
WooCommerce Currency Converter: by WooCommerce – 1.6.25 (update to version 1.6.26 is available)
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.3.3
WooCommerce Deposits: by WooCommerce – 1.5.7 (update to version 1.5.8 is available)
WooCommerce Distance Rate Shipping: by WooCommerce – 1.0.28 (update to version 1.0.31 is available)
WooCommerce Dynamic Pricing: by Element Stark – 3.1.27
WooCommerce EU VAT Number: by WooCommerce – 2.4.1
WooCommerce FedEx Shipping: by WooCommerce – 3.4.40
WooCommerce Force Sells: by WooCommerce – 1.1.29
WooCommerce Gift Cards: by SomewhereWarm – 1.8.2 (update to version 1.10.0 is available)
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.14 (update to version 2.4.15 is available)
WooCommerce Memberships: by SkyVerge – 1.22.9
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.24
WooCommerce Mix and Match Products: by Kathy Darling – 1.11.2 (update to version 1.11.6 is available)
WooCommerce Name Your Price: by Kathy Darling – 3.3.2 (update to version 3.3.7 is available)
WooCommerce One Page Checkout: by Automattic – 1.8.1 (update to version 1.9.1 is available)
WooCommerce Order Barcodes: by WooCommerce – 1.3.24
WooCommerce PayFast Gateway: by WooCommerce – 1.4.19 (update to version 1.4.20 is available)
WooCommerce Payments: by Automattic – 3.6.0 (update to version 3.6.1 is available)
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce PayPal Payments: by WooCommerce – 1.6.4
WooCommerce Photography: by WooCommerce – 1.0.29
WooCommerce Points and Rewards: by WooCommerce – 1.7.2 (update to version 1.7.5 is available)
WooCommerce Pre-Orders: by WooCommerce – 1.5.30 (update to version 1.6.0 is available)
WooCommerce Product Add-ons: by WooCommerce – 4.5.0
WooCommerce Product Bundles: by WooCommerce – 6.13.3
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.46
WooCommerce Product Search: by itthinx – 4.0.1 (update to version 4.3.0 is available)
WooCommerce Product Vendors: by WooCommerce – 2.1.57 (update to version 2.1.58 is available)
WooCommerce Shipment Tracking: by WooCommerce – 1.6.28 (update to version 1.6.31 is available)
WooCommerce Shipping & Tax: by WooCommerce – 1.25.20 (update to version 1.25.21 is available)
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.15 (update to version 2.3.17 is available)
WooCommerce Smart Coupons: by StoreApps – 4.33.1 (update to version 4.35.0 is available)
WooCommerce Software Add-On: by WooCommerce – 1.7.19
WooCommerce Square: by WooCommerce – 2.8.0
WooCommerce Stripe Gateway: by WooCommerce – 6.0.0
WooCommerce Subscription Downloads: by WooCommerce – 1.1.31
WooCommerce Subscriptions: by WooCommerce – 4.0.1
WooCommerce Subscriptions - Custom Price String: by Prospress Inc. – 1.0.4
WooCommerce Subscriptions Gifting: by WooCommerce – 2.1.3
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.36
WooCommerce UPS Shipping: by WooCommerce – 3.2.34 (update to version 3.2.37 is available)
WooCommerce USPS Shipping: by WooCommerce – 4.4.69
WooCommerce Xero Integration: by WooCommerce – 1.7.38 (update to version 1.7.40 is available)
WP Crontrol: by John Blackbourn & crontributors – 1.12.0
WP File Manager: by mndpsingh287 – 7.1.3
WP Mail Logging: by Wysija – 1.10.2
WP Rocket: by WP Media – 3.10.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
photography (photography)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,467
Oldest: 2022-01-04 17:32:19 +0200
Newest: 2022-01-31 17:56:41 +0200

Pending: 24
Oldest: 2022-01-31 18:00:50 +0200
Newest: 2022-05-07 03:00:00 +0200

Failed: 5
Oldest: 2021-12-01 19:20:48 +0200
Newest: 2022-01-19 06:32:10 +0200

Canceled: 18
Oldest: 2022-01-02 02:12:29 +0200
Newest: -0001-11-30 02:05:09 +0205

### Status report information ###

Generated at: 2022-01-31 18:00:03 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by amElnagdy** [comment] 2022-01-31 16:10
Ref: 4735427-zen

**Comment by Aljullu** [comment] 2024-08-21 06:56
I'm not able to reproduce this issue, maybe it has been fixed since it was reported? The steps I followed:

1. Make sure you have a Product category with at least two products.
2. Visit the product category page in the frontend. Notice it lists both products and has the text _Showing all 2 results_.

![image](https://github.com/user-attachments/assets/8dd59fe4-d738-41e6-904b-bf385dc8c340)

3. Set one of the products out of stock.
4. Visit the product category page in the frontend again. Notice it still lists both products and has the text _Showing all 2 results_.

![image](https://github.com/user-attachments/assets/da828be9-1f87-4b1b-a5af-3119db852d74)

5. Enable the _Hide out of stock items from the catalog_ option in the Settings.
6. Visit the product category page in the frontend again. Notice it only lists one product and has the text _Showing the single result_.

![image](https://github.com/user-attachments/assets/2001d5bb-4ff8-4b65-b0e2-0ffd1d891c39)

I'm closing the issue based on that. But please, feel free to reopen if you think it's a mistake.

**Closed as not planned** 2024-08-21 06:56 UTC
Labels: Bug, Store Frontend, plugin: woocommerce, Kirigami, Performance
