### ISSUE TITLE
Big arrow icons - Analytics - Custom period of time

### ISSUE THREAD

**Issue by arigato-one** [woothemes/woocommerce#35470] opened 2022-11-02 14:02 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If you go to Analytics - Revenue - Custom (period of time) then the arrows for previous / next are extremely big.

<img width="510" alt="Screenshot 2022-11-02 at 15 59 22" src="https://user-images.githubusercontent.com/17124280/199508899-46b0cdd5-622c-4376-971b-b0baa0deb894.png">

### Expected behavior

The arrows should be smaller :) 

### Actual behavior

The arrows are bigger and is difficult to select a custom period of time

### Steps to reproduce

WordPress Dashboard -> Analytics -> Revenue -> Custom (period of time)
The bug will appear.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://woocommerce.local
Site address (URL): https://woocommerce.local
WC Version: 7.0.1
REST API Version: ✔ 7.0.1
WC Blocks Version: ✔ 8.5.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: ro_RO
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Unix)
PHP Version: 8.1.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.1
WC Database Prefix: wp_
Total Database Size: 9.61MB
Database Data Size: 7.83MB
Database Index Size: 1.78MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_cart_abandonment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_commercekit_searches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commercekit_swatches_cache_count: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commercekit_waitlist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commercekit_wishlist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commercekit_wishlist_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 5.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 1.39MB + Index: 0.19MB + Engine InnoDB
wp_posts: Data: 0.22MB + Index: 0.06MB + Engine InnoDB
wp_seopress_significant_keywords: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_snippets: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 54
custom_css: 2
elementor_library: 8
nav_menu_item: 26
page: 19
post: 3
product: 10
product_variation: 9
shop_order: 1
wp_block: 1
wp_global_styles: 2
wpcode: 49

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

CommerceGurus Commercekit: by CommerceGurus – 2.1.1
Customer Reviews for WooCommerce: by CusRev – 5.6.4
Database Cleaner & Optimizer (2022): by Jordy Meow – 0.6.8
Elementor: by Elementor.com – 3.8.0
WPCode - Insert Headers, Footers, and Code Snippets: by WPCode – 2.0.3
Kirki Customizer Framework: by David Vongries – 4.0.24
Media File Renamer (Pro): by Jordy Meow – 5.4.9
One Click Demo Import: by OCDI – 3.1.2
Perfmatters: by forgemedia – 2.0.0
SVG Support: by Benbodhi – 2.5.1
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.19
WooCommerce: by Automattic – 7.0.1
SEOPress PRO: by The SEO Guys at SEOPress – 6.0.1
SEOPress: by The SEO Guys at SEOPress – 6.0.2

### Inactive Plugins (4) ###

Health Check & Troubleshooting: by The WordPress.org community – 1.5.1
LiteSpeed Cache: by LiteSpeed Technologies – 5.3
Media Cleaner: by Jordy Meow – 6.4.9
WooCommerce Stripe Gateway: by WooCommerce – 6.9.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: RON (lei)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #18 - /magazin/
Cart: #19 - /cos/
Checkout: #20 - /finalizare/
My account: #21 - /contul-meu/
Terms and conditions: #2 - /termeni-si-conditii/

### Theme ###

Name: Shoptimizer
Version: 2.6.2
Author URL: https://www.commercegurus.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-03 08:25:55 +02:00
Options: ✔
Notes: 51
Onboarding: completed

### Action Scheduler ###

Complete: 27
Oldest: 2022-10-07 15:38:38 +0300
Newest: 2022-11-02 15:56:43 +0200

Pending: 3
Oldest: 2022-11-02 16:09:15 +0200
Newest: 2022-11-09 15:54:15 +0200

### Status report information ###

Generated at: 2022-11-02 16:01:23 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by kaushikasomaiya** [comment] 2022-11-03 04:51
5677344-zen

**Comment by kaushikasomaiya** [comment] 2022-11-03 04:52
Able to replicate on my test site as well.

**Comment by jacoswan** [comment] 2022-11-03 06:32
Also able to replicate on localhost, WPCOM, Pressable, and JN sites in latest Chrome, Firefox, and DuckDuckGo. Active theme doesn't make a difference. 

Downgrading through versions to as far as 6.7.0 does not seem to resolve, even with local cookies and caches cleared.

**Comment by arigato-one** [comment] 2022-11-03 06:38
> Also able to replicate on localhost, WPCOM, Pressable, and JN sites in latest Chrome, Firefox, and DuckDuckGo. Active theme doesn't make a difference.
> 
> Downgrading through versions to as far as 6.7.0 does not seem to resolve, even with local cookies and caches cleared.

I think is related to WordPress 6.1

**Comment by bgrgicak** [comment] 2022-11-03 07:05
> I think is related to WordPress 6.1

We started seeing the issue after updating to WordPress 6.1.

**Comment by TowyTowy** [comment] 2022-11-05 14:31
Happens for me too.

**Comment by swatipawarGS** [comment] 2022-11-08 13:22
Hi @arigato-one,
Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the  WooCommerce 7.0.1 version and WordPress 6.1 version. 

Please find below the screenshot for reference :
![#35470](https://user-images.githubusercontent.com/94531721/200523316-aa7bfd12-69a6-4642-8b10-c85ddbe74312.jpg)

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by amElnagdy** [comment] 2022-11-08 13:31
5677394-zen

**Comment by kaushikasomaiya** [comment] 2022-11-09 14:03
5697301-zen

**Comment by kaushikasomaiya** [comment] 2022-11-09 14:30
Following CSS can be loaded to WPAdmin using any Admin CSS plugin as a temporary fix: https://d.pr/n/Ltz4Fw

**Comment by arigato-one** [comment] 2022-11-09 15:22
> Following CSS can be loaded to WPAdmin using any Admin CSS plugin as a temporary fix: https://d.pr/n/Ltz4Fw

Isn't too much CSS for this problem?

**Comment by kaushikasomaiya** [comment] 2022-11-09 15:33
@arigato-one It appears that not only the arrows are big but styling of whole calendar is messed up due to missing styles. I extracted these styles from WP Includes folder, these should already be loaded but not sure why they are missing.

**Comment by orhanfernandes** [comment] 2022-11-09 20:49
5698780-zen

**Comment by rbgly** [comment] 2022-11-14 08:38
5700647-zen

**Comment by felipevelzani** [comment] 2022-11-15 19:27
5705143-zen

https://user-images.githubusercontent.com/40555737/202008044-d1adf0fa-9f41-4d89-bfc4-b7b4648598c7.mp4

**Comment by felipevelzani** [comment] 2022-11-15 19:44
List of references from #35509:

* 5703560-zen
* 5668444-zen
* 5690274-zen
* 5691148-zen
* 5691601-zen
* 5699223-zen
* 5704552-zen
* 38014571-hc
* https://wordpress.org/support/topic/analytics-error-3/
* https://wordpress.org/support/topic/wc-analytic-custom-report-issue/

**Comment by vinnykaur** [comment] 2022-11-16 11:48
5716069-zen

**Comment by arigato-one** [comment] 2022-11-16 13:28
> 5716069-zen

What does it mean?
I see that there are multiple strings like yours.
Can you explain?
Thanks

**Comment by jaxr** [comment] 2022-11-16 14:11
37871096-hc

**Comment by xuexue28** [comment] 2022-11-16 16:37
Another one here: https://wordpress.org/support/topic/woocommerce-analytics-select-a-date-issue/

**Comment by felipevelzani** [comment] 2022-11-16 18:01
Hi @arigato-one!

> > 5716069-zen
> 
> What does it mean? I see that there are multiple strings like yours. Can you explain? Thanks

This is an internal reference added by the WooCommerce team, and these are newly reported cases related to this issue. We keep track of it to see the proportion of this issue across multiple websites. I appreciate your patience!

**Comment by xuexue28** [comment] 2022-11-17 06:01
https://wordpress.org/support/topic/analytics-custom-date-picker-not-working/

**Comment by thuautp** [comment] 2022-11-17 11:26
5718868-zen

**Comment by namiokuzono** [comment] 2022-11-18 21:48
5721107-zen

**Comment by xuexue28** [comment] 2022-11-21 16:30
https://wordpress.org/support/topic/woocommerce-analytics-showing-big-arrows/

**Comment by jacoswan** [comment] 2022-11-22 13:14
5729495-zen

**Comment by xuexue28** [comment] 2022-11-23 06:56
https://wordpress.org/support/topic/analytics-custom-date-picker-v-7-0-1/#post-16219686

**Comment by sanebg** [comment] 2022-11-24 03:15
That’s ridiculous. I just updated to 7.1.0 and broke my Analytics tab exactly as shown on the screenshot above.

Please, fix this fast. Reporting is massively important for any WooCommerce Store.

**Comment by rubileandro** [comment] 2022-11-24 12:28
[5737433-zen](5737433-zd-woothemes)

**Comment by EjayhanFernandes** [comment] 2022-11-26 09:13
5742487-zen

**Comment by kylebarrow** [comment] 2022-11-28 23:53
A quick CSS workaround I'm using to make the icons usable until a fix is released:

`.DayPickerNavigation,ul.DayPicker_weekHeader_ul{display:flex}.DayPickerNavigation .DayPickerNavigation_button{width:30px;margin:0 10px}`

Loaded  via admin_enqueue_scripts

**Comment by chihsuan** [comment] 2022-11-29 01:59
Hey @woocommerce/mothra Users keep reporting the bug. Could someone take a look at this? 🙏

**Comment by arigato-one** [comment] 2022-11-29 06:53
> A quick CSS workaround I'm using to make the icons usable until a fix is released:
> 
> `.DayPickerNavigation,ul.DayPicker_weekHeader_ul{display:flex}.DayPickerNavigation .DayPickerNavigation_button{width:30px;margin:0 10px}`
> 
> Loaded via admin_enqueue_scripts

It's working great.
Thanks

You can add this code via this code snippets which will be added in theme functions.php or you can use Code Snippets / WP Code plugin.

add_action('admin_head', 'my_custom_css_admin');

function my_custom_css_admin() {
  echo '<style>
  .DayPickerNavigation,ul.DayPicker_weekHeader_ul{display:flex}.DayPickerNavigation .DayPickerNavigation_button{width:30px;margin:0 10px}
  </style>';
}

**Comment by chihsuan** [comment] 2022-11-29 07:50
> It's working great.

@arigato-one I'm glad it works for you! 🙂 

Reopen it since it's a workaround. We'll fix it in Core.

**Comment by AnnaMag** [comment] 2022-11-29 19:06
Thank you @chihsuan!

@nathanss @octaedro I've added this issue to the backlog.

**Comment by nathanss** [comment] 2022-11-29 20:30
This is a duplicate of #35645 and is fixed by #35649. 

It will be released in version 7.2 on December 13th.

**Closed as completed by nathanss** 2022-11-29 20:30 UTC
Labels: Bug, Good First Issue, plugin: woocommerce, Reports/Analytics, type: community contribution

**Comment by xue28** [comment] 2022-11-30 15:44
https://wordpress.org/support/topic/analytics-svgs-have-no-max-width/#post-16248310

**Comment by xue28** [comment] 2022-12-06 06:33
https://wordpress.org/support/topic/error-in-analytic-date-filter-calendar/

**Comment by madisoncmiller** [comment] 2022-12-06 14:40
37464841-hc

**Comment by SKR2004** [comment] 2022-12-07 23:15
> That’s ridiculous. I just updated to 7.1.0 and broke my Analytics tab exactly as shown on the screenshot above.
> 
> Please, fix this fast. Reporting is massively important for any WooCommerce Store.

If the analytics fail, the whole system fails, you don't know any readings, and you're back in the age of paper and pen

**Comment by Mxchael** [comment] 2022-12-09 03:01
38498961-hc

**Comment by sanebg** [comment] 2022-12-10 06:36
The fact that this issue has existed for almost 2 months for something so essential, like the Analytics tab, says a lot about the company behind WooCommerce and the path that has been taken.

It's just a matter of time before a more modern, lightweight, and fast-developing competitor takes over the market.

Many giant behemoths have died overnight because of negligence, arrogance, and lack of urgency to survive and thrive.

**Comment by SKR2004** [comment] 2022-12-10 10:29
Very proven and logical words

**Comment by jromales** [comment] 2022-12-13 06:43
37286396-hc

**Comment by igorhereira** [comment] 2022-12-21 15:49
5804043-zen

**Comment by juned456** [comment] 2023-03-20 07:27
Hello i am also getting the same issue, please fix it asap.
