### ISSUE TITLE
[Enhancement]: Don't query on every admin page load all of our millions of orders for the payment method "woocommerce_payments" if it's not installed

### ISSUE THREAD

**Issue by daheadcracker** [woothemes/woocommerce#40053] opened 2023-09-06 09:07 UTC
### Describe the solution you'd like

On every admin page view the method "has_wcpay" is beeing triggered:
/wp-content/plugins/woocommerce/src/Internal/Admin/WcPayWelcomePage.php

We don't have wc pay installed or ever used it. We have millions of orders from the subscription plugin in our DB and this unnecessary query is slowing down our backend by almost 2 seconds on every page.

### Describe alternatives you've considered

I just hotfixed it currently by just returning false, but this gets annoying after every update.
One could do e.g. a quick fix by checking if the plugin is even installed with something like if( !function_exists(...) ){ return false; }

**Comment by vbelolapotkov** [comment] 2023-09-12 09:38
@woocommerce/moltres could you please take a look and prioritize it? Scanning all orders definitely may create performance hit on large stores. From the first look, priority of this is pretty high, but I defer to you for final estimate.

**Comment by vbelolapotkov** [comment] 2023-09-12 09:51
Sorry, that's a duplicate of #39742, so closing this one.

**Closed as completed by vbelolapotkov** 2023-09-12 09:51 UTC
Labels: Enhancement, Payments, type: community contribution, Payments Engineering
