### ISSUE TITLE
No Category/ Sub-category Delete Option

### ISSUE THREAD

**Issue by Lahori-Jawan** [woothemes/woocommerce#10472] opened 2016-03-04 07:20 UTC
My company is using flatsome theme with woocommerce. I just added a category under 
Products->Category and nothing happend, so I kept clicking for 5 or 6 times more because there was no sign of operation being done. then I refreshed the page and whoh... there were all those clicked categories with same name. So now I wanted to delete them but when i hover over the newly created categories, there would be options i.e. Edit | Quick Edit | View. But there is no 'Delete' option.

![category](https://cloud.githubusercontent.com/assets/7579344/13520263/bbc10e3c-e200-11e5-897d-1afcae74525c.PNG)

when i click 'Quick Edit', it shows following

![quick](https://cloud.githubusercontent.com/assets/7579344/13520469/592ab10e-e202-11e5-82de-2fc5162c98b0.PNG)

which means data i.e. title, slug is not being stored but somehow category is being created.
Woocommerce version (from woocommerce.php) 2.4.12

How could i solve this?

**Comment by reigelgallarde** [comment] 2016-03-04 09:46
maybe your nulled flatsome theme is the culprit... try changing other theme like twenty twelve.. see if the issue is still there...

**Comment by mikejolley** [comment] 2016-03-04 10:18
Yeah, its visible for me too. Either the user role has no access, or you have something messing with your screens. Posts > Categories would be the same. Also, if cats don't appear right away, ensure woocommerce_termmeta table exists.

Closing as its not a bug on our installs.

**Closed by mikejolley** 2016-03-04 10:18 UTC

**Comment by Lahori-Jawan** [comment] 2016-03-04 11:32
there is woocommerce_termmeta table available as can be seen

![woo](https://cloud.githubusercontent.com/assets/7579344/13525844/a6e67ea0-e225-11e5-8229-67c3daa86e39.PNG).

yeah, you are right. Posts > Categories also messed up now. I just added one category i.e. text cat but all other categories from Products > Categories turned up here too. I am using it as admin, so what could be the problem?

**Comment by mikejolley** [comment] 2016-03-04 12:01
Can't really say; but as its affects WP sitewide I doubt its WC specific.
