### ISSUE TITLE
Woocommerce Post featured image problem

### ISSUE THREAD

**Issue by Julian0079** [woothemes/woocommerce#31079] opened 2021-11-03 14:36 UTC
Hi so i have a problem with my wordpress. Im using Hallo theme, Elementor pro, woocommerce and polylang. 

Right now i cant add any featured image to my posts. So every time im adding an image it is not updated. So it is always empty. 
I inspected the website while uploading and saw an issue with woocommerce. I have attached the gif. Maybe someone has an idea. Many thanks !
![Animation](https://user-images.githubusercontent.com/60205877/140080903-585b03c1-f9be-4d4f-a644-fa49f1e05ba4.gif)

**Comment by tammullen** [comment] 2021-11-03 19:52
Hi @Julian0079 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by tammullen** 2021-11-03 19:52 UTC
Labels: type: support request
