### ISSUE TITLE
[Enhancement]: In-app guidance - DOM toolkit

### ISSUE THREAD

**Issue by becdetat** [woothemes/woocommerce#32465] opened 2022-04-04 07:48 UTC
### Describe the solution you'd like

This is part of an internal project - see (pbIJXs-1qT-p2) for more context.

This will use the [tooltip](https://github.com/woocommerce/woocommerce/issues/32463) and [step guidance](https://github.com/woocommerce/woocommerce/issues/32463) components. Completion of this issue will depend on those components being stable enough to consume (although they may still require further styling for example).

This toolkit will provide an API for creating in-app guidance over any DOM element. The use case is to be able to create in-app guidance for 3PD extension admin pages without requiring the 3PD extensions themselves to be changed.

For a specific 3PD extension, this implementation consists of two layers:

- the toolkit ( *which is the deliverable for this issue* ), and
- the _implementation_ layer - code that consumes the toolkit API and hooks in-app guidance to arbitrary DOM elements that belong to the 3PD extension's admin page(s)

## The toolkit

A relatively comprehensive toolkit that allows tooltips and step guidances to be created over the top of any DOM element, with enough capabilities to handle the requirements of providing in-app guidance to most 3PD extension pages
It’s likely that this will need to be implemented natively (i.e. not a React component).

- The API provided by this toolkit should be simple enough that the implementation layer (below) is relatively easy to create and maintain
- It should use something like CSS selectors or some other way to make the DOM selection somewhat fuzzy and maintainable (for example if the 3PD extension moves something, the in-app guidance should still hopefully work without needing an update). To keep from getting too brittle we could consider a library such as [sizzle](https://github.com/jquery/sizzle/wiki) or just use the bundled jQuery if we can assume it will be present.

## The implementation layer

An implementation layer for a specific 3PD extension, which uses the toolkit to create the in-app guidance over the 3PD extension without having to modify or have access to the 3PD extension code.

- Implementation layers should probably register with the toolkit, and only get loaded when required (e.g. via URL matching)

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by adrianduffell** [comment] 2023-05-01 23:07
Duplicate of https://github.com/woocommerce/woocommerce/issues/32892

**Closed as completed by adrianduffell** 2023-05-01 23:07 UTC
Labels: Enhancement, plugin: woocommerce
