### ISSUE TITLE
Issue with cart.php displaying quantity for items set as 'sold individually'

### ISSUE THREAD

**Issue by bonniec0** [woothemes/woocommerce#37079] opened 2023-03-06 13:05 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Since update 7.4.0, there has been an issue with the cart.php template. Since the update, on the cart page the the quantity is blank for products that are set to be 'sold individually'. Before the update it displayed a fixed quantity of 1 for products set as 'sold individually', which is much more useful as it confirms to customers that they have just the one product in their basket. The mini-cart & the checkout both still display a fixed quantity of one, so I assume that when the cart.php file was updated in 7.4.0, the code to display the quantity as 1 was accidentally deleted.

I have already brought this issue up on the Woocommerce community forum, where it was confirmed that the issue was also present on your testing site (using Storefront) with WooCommerce versions 7.4.0 and 7.4.1

Thank you very much,
Bonnie

### Expected behavior

The quantity to be fixed and display as '1' in the cart page for products set as 'sold individually'

### Actual behavior

The quantity field being blank in the cart page for products set as 'sold individually'

### Steps to reproduce

Set a product as 'sold individually'.
Add that item to basket.
Go to basket page and look at quantity field.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://thebonnebijouterie.co.uk
Site address (URL): https://thebonnebijouterie.co.uk
WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.4.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Debian)
PHP Version: 8.0.21
PHP Post Max Size: 10 MB
PHP Time Limit: 60
PHP Max Input Vars: 2500
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.6.3-MariaDB-1:10.6.3+maria~buster-log
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.1
WC Database Prefix: wp_
Total Database Size: 3216.92MB
Database Data Size: 3194.84MB
Database Index Size: 22.08MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_braapf_product_stock_status_parent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_braapf_product_variation_attributes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_braapf_term_taxonomy_hierarchical: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_braapf_variable_attributes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bv_ip_store: Data: 0.28MB + Index: 0.30MB + Engine InnoDB
wp_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_ca_cart_abandonment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_iconic_woothumbs_cache: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_is_inverted_index: Data: 6.16MB + Index: 9.63MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 7.20MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 8.47MB + Index: 2.91MB + Engine InnoDB
wp_posts: Data: 3170.20MB + Index: 6.97MB + Engine InnoDB
wp_snippets: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.25MB + Index: 0.09MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tinvwl_analytics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_tinvwl_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tinvwl_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

astra-advanced-hook: 3
attachment: 2492
br_product_filter: 10
custom_css: 4
customize_changeset: 21443
is_search_form: 1
nav_menu_item: 177
page: 40
post: 6
product: 349
revision: 2012
wp_block: 1
wp_global_styles: 1
wpforms: 8

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Ivory Search: by Ivory Search – 5.5
Astra Pro: by Brainstorm Force – 4.0.1
WooThumbs for WooCommerce by Iconic: by Iconic – 5.1.1
Loco Translate: by Tim Whitlock – 2.6.3
MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall: by MalCare Security – 4.87
TI WooCommerce Wishlist: by TemplateInvaders – 2.3.5
Advanced AJAX Product Filters for WooCommerce: by BeRocket – 1.6.3.4
WooCommerce: by Automattic – 7.4.1
WP 2FA - Two-factor authentication for WordPress: by WP White Security – 2.4.1
WPForms Lite: by WPForms – 1.8.0.2

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 5.0.2
Breeze: by Cloudways – 2.0.17
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.23

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #3604 - /shop/
Basket: #3605 - /basket/
Checkout: #3606 - /checkout/
My account: #3607 - /my-account/
Terms and conditions: #26299 - /terms-conditions/

### Theme ###

Name: RJG Child
Version: 1.0.0
Author URL: http://wpastra.com/about/
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 4.0.2
Parent Theme Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce Support: ✔

### Templates ###

Overrides: rjg-child/woocommerce/cart/mini-cart.php
rjg-child/woocommerce/checkout/form-billing.php
rjg-child/woocommerce/checkout/form-checkout.php
rjg-child/woocommerce/checkout/form-shipping.php
rjg-child/woocommerce/checkout/review-order.php
rjg-child/woocommerce/myaccount/form-login.php
rjg-child/woocommerce/myaccount/form-lost-password.php
rjg-child/woocommerce/myaccount/navigation.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-06 18:51:24 +00:00
Options: ✔
Notes: 14
Onboarding: completed

### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Complete: 154
Oldest: 2023-02-03 13:58:48 +0000
Newest: 2023-03-06 12:57:34 +0000

Failed: 2
Oldest: 2023-02-28 18:46:41 +0000
Newest: 2023-02-28 18:46:41 +0000

Pending: 7
Oldest: 2023-03-06 19:41:20 +0000
Newest: 2023-03-10 19:06:35 +0000

### Status report information ###

Generated at: 2023-03-06 13:03:53 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jonathansadowski** [comment] 2023-03-06 15:05
Hi @bonniec0,

Thanks for the report. This issue looks to be a duplicate of #36920, which is slated to be fixed with the release of 7.5.0. I'm going to close this as it should be fixed with our next release. If I'm mistaken and it's not the same issue, please let me know.

**Comment by bonniec0** [comment] 2023-03-06 17:56
Hi @jonathansadowski ,

Thank you for the response, I don't think it is quite the same issue. It occurs with simple products rather than on product variations. If you go to Product data > Inventory then tick Sold individually (Limit purchases to 1 item per order). This is the product type for which the issue displays.

Unlike the issue you linked to, I am not able to add multiple to my cart (so I assume the maximum limit is being enforced), rather once in the cart there is simply no quantity displayed in the quantity field - it is blank. It may well be the same logic causing both issues, but I just wanted to clarify the difference.

Sorry for the confusion & thank you,
Bonnie

**Comment by jonathansadowski** [comment] 2023-03-08 19:45
Hi @bonniec0,

Sorry for the confusion and thanks for clarifying, then I'll reopen this and we'll try and reproduce.

**Comment by coreymckrill** [comment] 2023-03-21 19:28
Hi @bonniec0, you can see the reasoning for this change in #36460. Having the quantity selector still be visible for "sold individually" products was actually a fairly recent change (version 7.2) and a lot of people didn't like it, so it was changed back.

**Closed as not planned by coreymckrill** 2023-03-21 19:28 UTC
Labels: Bug, Cart, plugin: woocommerce, type: community contribution
