### ISSUE TITLE
PHP Notice:  Undefined index: `line_total` when ordering again

### ISSUE THREAD

**Issue by jimjasson** [woothemes/woocommerce#42120] opened 2023-11-07 09:27 UTC
## Describe the bug

When clicking the Order again button for an order under My Account > Orders and the cart block is used, the following error is triggered: 

```
[06-Nov-2023 15:41:50 UTC] PHP Notice:  Undefined index: line_total in /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/class-wp-list-util.php on line 170
[06-Nov-2023 15:41:50 UTC] PHP Stack trace:
[06-Nov-2023 15:41:50 UTC] PHP   1. {main}() /Users/dimitrioskytros/Local Sites/wp/app/public/index.php:0
[06-Nov-2023 15:41:50 UTC] PHP   2. require() /Users/dimitrioskytros/Local Sites/wp/app/public/index.php:17
[06-Nov-2023 15:41:50 UTC] PHP   3. require_once() /Users/dimitrioskytros/Local Sites/wp/app/public/wp-blog-header.php:19
[06-Nov-2023 15:41:50 UTC] PHP   4. include() /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/template-loader.php:106
[06-Nov-2023 15:41:50 UTC] PHP   5. get_template_part($slug = 'content', $name = 'page', $args = *uninitialized*) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-content/themes/storefront/page.php:24
[06-Nov-2023 15:41:50 UTC] PHP   6. locate_template($template_names = [0 => 'content-page.php', 1 => 'content.php'], $load = TRUE, $load_once = FALSE, $args = []) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/general-template.php:206
[06-Nov-2023 15:41:50 UTC] PHP   7. load_template($_template_file = '/Users/dimitrioskytros/Local Sites/wp/app/public/wp-content/themes/storefront/content-page.php', $load_once = FALSE, $args = []) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/template.php:720
[06-Nov-2023 15:41:50 UTC] PHP   8. require() /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/template.php:787
[06-Nov-2023 15:41:50 UTC] PHP   9. do_action($hook_name = 'storefront_page') /Users/dimitrioskytros/Local Sites/wp/app/public/wp-content/themes/storefront/content-page.php:18
[06-Nov-2023 15:41:50 UTC] PHP  10. WP_Hook->do_action($args = [0 => '']) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/plugin.php:517
[06-Nov-2023 15:41:50 UTC] PHP  11. WP_Hook->apply_filters($value = '', $args = [0 => '']) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/class-wp-hook.php:334
[06-Nov-2023 15:41:50 UTC] PHP  12. storefront_page_content('') /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/class-wp-hook.php:310
[06-Nov-2023 15:41:50 UTC] PHP  13. the_content($more_link_text = *uninitialized*, $strip_teaser = *uninitialized*) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-content/themes/storefront/inc/storefront-template-functions.php:352
[06-Nov-2023 15:41:50 UTC] PHP  14. apply_filters($hook_name = 'the_content', $value = '<!-- wp:woocommerce/cart -->\n<div class="wp-block-woocommerce-cart alignwide is-loading"><!-- wp:woocommerce/filled-cart-block -->\n<div class="wp-block-woocommerce-filled-cart-block"><!-- wp:woocommerce/cart-items-block -->\n<div class="wp-block-woocommerce-cart-items-block"><!-- wp:woocommerce/cart-line-items-block -->\n<div class="wp-block-woocommerce-cart-line-items-block"></div>\n<!-- /wp:woocommerce/cart-line-items-block -->\n\n<!-- wp:woocommerce/cart-cross-sells-block -->\n<div class="wp-block-woocommerce-'...) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/post-template.php:256
[06-Nov-2023 15:41:50 UTC] PHP  15. WP_Hook->apply_filters($value = '<!-- wp:woocommerce/cart -->\n<div class="wp-block-woocommerce-cart alignwide is-loading"><!-- wp:woocommerce/filled-cart-block -->\n<div class="wp-block-woocommerce-filled-cart-block"><!-- wp:woocommerce/cart-items-block -->\n<div class="wp-block-woocommerce-cart-items-block"><!-- wp:woocommerce/cart-line-items-block -->\n<div class="wp-block-woocommerce-cart-line-items-block"></div>\n<!-- /wp:woocommerce/cart-line-items-block -->\n\n<!-- wp:woocommerce/cart-cross-sells-block -->\n<div class="wp-block-woocommerce-'..., $args = [0 => '<!-- wp:woocommerce/cart -->\n<div class="wp-block-woocommerce-cart alignwide is-loading"><!-- wp:woocommerce/filled-cart-block -->\n<div class="wp-block-woocommerce-filled-cart-block"><!-- wp:woocommerce/cart-items-block -->\n<div class="wp-block-woocommerce-cart-items-block"><!-- wp:woocommerce/cart-line-items-block -->\n<div class="wp-block-woocommerce-cart-line-items-block"></div>\n<!-- /wp:woocommerce/cart-line-items-block -->\n\n<!-- wp:woocommerce/cart-cross-sells-block -->\n<div class="wp-block-woocommerce-'...]) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/plugin.php:205
[06-Nov-2023 15:41:50 UTC] PHP  16. do_blocks($content = '<!-- wp:woocommerce/cart -->\n<div class="wp-block-woocommerce-cart alignwide is-loading"><!-- wp:woocommerce/filled-cart-block -->\n<div class="wp-block-woocommerce-filled-cart-block"><!-- wp:woocommerce/cart-items-block -->\n<div class="wp-block-woocommerce-cart-items-block"><!-- wp:woocommerce/cart-line-items-block -->\n<div class="wp-block-woocommerce-cart-line-items-block"></div>\n<!-- /wp:woocommerce/cart-line-items-block -->\n\n<!-- wp:woocommerce/cart-cross-sells-block -->\n<div class="wp-block-woocommerce-'...) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/class-wp-hook.php:310
[06-Nov-2023 15:41:50 UTC] PHP  17. render_block($parsed_block = ['blockName' => 'woocommerce/cart', 'attrs' => [], 'innerBlocks' => [0 => [...], 1 => [...]], 'innerHTML' => '\n<div class="wp-block-woocommerce-cart alignwide is-loading">\n\n</div>\n', 'innerContent' => [0 => '\n<div class="wp-block-woocommerce-cart alignwide is-loading">', 1 => NULL, 2 => '\n\n', 3 => NULL, 4 => '</div>\n']]) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/blocks.php:1171
[06-Nov-2023 15:41:50 UTC] PHP  18. WP_Block->render($options = *uninitialized*) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/blocks.php:1133
[06-Nov-2023 15:41:50 UTC] PHP  19. Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback($attributes = [], $content = '\n<div class="wp-block-woocommerce-cart alignwide is-loading"><div data-block-name="woocommerce/filled-cart-block" class="wp-block-woocommerce-filled-cart-block"><div data-block-name="woocommerce/cart-items-block" class="wp-block-woocommerce-cart-items-block"><div data-block-name="woocommerce/cart-line-items-block" class="wp-block-woocommerce-cart-line-items-block"></div>\n\n<div data-block-name="woocommerce/cart-cross-sells-block" class="wp-block-woocommerce-cart-cross-sells-block">\n<h2 class="wp-block-headin'..., $block = class WP_Block { public $parsed_block = ['blockName' => 'woocommerce/cart', 'attrs' => [...], 'innerBlocks' => [...], 'innerHTML' => '\n<div class="wp-block-woocommerce-cart alignwide is-loading">\n\n</div>\n', 'innerContent' => [...]]; public $name = 'woocommerce/cart'; public $block_type = class WP_Block_Type { public $api_version = 1; public $name = 'woocommerce/cart'; public $title = ''; public $category = NULL; public $parent = NULL; public $ancestor = NULL; public $icon = NULL; public $description = ''; public $keywords = [...]; public $textdomain = NULL; public $styles = [...]; public $variations = [...]; public $selectors = [...]; public $supports = [...]; public $example = NULL; public $render_callback = [...]; public $attributes = [...]; public $uses_context = [...]; public $provides_context = NULL; public $editor_script_handles = [...]; public $script_handles = [...]; public $view_script_handles = [...]; public $editor_style_handles = [...]; public $style_handles = [...]; private $deprecated_properties = [...] }; public $context = []; protected $available_context = ['postId' => 2827, 'postType' => 'page']; protected $registry = class WP_Block_Type_Registry { private $registered_block_types = [...] }; public $inner_blocks = class WP_Block_List { protected $blocks = [...]; protected $available_context = [...]; protected $registry = class WP_Block_Type_Registry { ... } }; public $inner_html = '\n<div class="wp-block-woocommerce-cart alignwide is-loading">\n\n</div>\n'; public $inner_content = [0 => '\n<div class="wp-block-woocommerce-cart alignwide is-loading">', 1 => NULL, 2 => '\n\n', 3 => NULL, 4 => '</div>\n']; public $attributes = [] }) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/class-wp-block.php:258
[06-Nov-2023 15:41:50 UTC] PHP  20. Automattic\WooCommerce\Blocks\BlockTypes\Cart->enqueue_assets($attributes = [], $content = '\n<div class="wp-block-woocommerce-cart alignwide is-loading"><div data-block-name="woocommerce/filled-cart-block" class="wp-block-woocommerce-filled-cart-block"><div data-block-name="woocommerce/cart-items-block" class="wp-block-woocommerce-cart-items-block"><div data-block-name="woocommerce/cart-line-items-block" class="wp-block-woocommerce-cart-line-items-block"></div>\n\n<div data-block-name="woocommerce/cart-cross-sells-block" class="wp-block-woocommerce-cart-cross-sells-block">\n<h2 class="wp-block-headin'..., $block = class WP_Block { public $parsed_block = ['blockName' => 'woocommerce/cart', 'attrs' => [...], 'innerBlocks' => [...], 'innerHTML' => '\n<div class="wp-block-woocommerce-cart alignwide is-loading">\n\n</div>\n', 'innerContent' => [...]]; public $name = 'woocommerce/cart'; public $block_type = class WP_Block_Type { public $api_version = 1; public $name = 'woocommerce/cart'; public $title = ''; public $category = NULL; public $parent = NULL; public $ancestor = NULL; public $icon = NULL; public $description = ''; public $keywords = [...]; public $textdomain = NULL; public $styles = [...]; public $variations = [...]; public $selectors = [...]; public $supports = [...]; public $example = NULL; public $render_callback = [...]; public $attributes = [...]; public $uses_context = [...]; public $provides_context = NULL; public $editor_script_handles = [...]; public $script_handles = [...]; public $view_script_handles = [...]; public $editor_style_handles = [...]; public $style_handles = [...]; private $deprecated_properties = [...] }; public $context = []; protected $available_context = ['postId' => 2827, 'postType' => 'page']; protected $registry = class WP_Block_Type_Registry { private $registered_block_types = [...] }; public $inner_blocks = class WP_Block_List { protected $blocks = [...]; protected $available_context = [...]; protected $registry = class WP_Block_Type_Registry { ... } }; public $inner_html = '\n<div class="wp-block-woocommerce-cart alignwide is-loading">\n\n</div>\n'; public $inner_content = [0 => '\n<div class="wp-block-woocommerce-cart alignwide is-loading">', 1 => NULL, 2 => '\n\n', 3 => NULL, 4 => '</div>\n']; public $attributes = [] }) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/AbstractBlock.php:86
[06-Nov-2023 15:41:50 UTC] PHP  21. Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->enqueue_assets($attributes = [], $content = '\n<div class="wp-block-woocommerce-cart alignwide is-loading"><div data-block-name="woocommerce/filled-cart-block" class="wp-block-woocommerce-filled-cart-block"><div data-block-name="woocommerce/cart-items-block" class="wp-block-woocommerce-cart-items-block"><div data-block-name="woocommerce/cart-line-items-block" class="wp-block-woocommerce-cart-line-items-block"></div>\n\n<div data-block-name="woocommerce/cart-cross-sells-block" class="wp-block-woocommerce-cart-cross-sells-block">\n<h2 class="wp-block-headin'..., $block = class WP_Block { public $parsed_block = ['blockName' => 'woocommerce/cart', 'attrs' => [...], 'innerBlocks' => [...], 'innerHTML' => '\n<div class="wp-block-woocommerce-cart alignwide is-loading">\n\n</div>\n', 'innerContent' => [...]]; public $name = 'woocommerce/cart'; public $block_type = class WP_Block_Type { public $api_version = 1; public $name = 'woocommerce/cart'; public $title = ''; public $category = NULL; public $parent = NULL; public $ancestor = NULL; public $icon = NULL; public $description = ''; public $keywords = [...]; public $textdomain = NULL; public $styles = [...]; public $variations = [...]; public $selectors = [...]; public $supports = [...]; public $example = NULL; public $render_callback = [...]; public $attributes = [...]; public $uses_context = [...]; public $provides_context = NULL; public $editor_script_handles = [...]; public $script_handles = [...]; public $view_script_handles = [...]; public $editor_style_handles = [...]; public $style_handles = [...]; private $deprecated_properties = [...] }; public $context = []; protected $available_context = ['postId' => 2827, 'postType' => 'page']; protected $registry = class WP_Block_Type_Registry { private $registered_block_types = [...] }; public $inner_blocks = class WP_Block_List { protected $blocks = [...]; protected $available_context = [...]; protected $registry = class WP_Block_Type_Registry { ... } }; public $inner_html = '\n<div class="wp-block-woocommerce-cart alignwide is-loading">\n\n</div>\n'; public $inner_content = [0 => '\n<div class="wp-block-woocommerce-cart alignwide is-loading">', 1 => NULL, 2 => '\n\n', 3 => NULL, 4 => '</div>\n']; public $attributes = [] }) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/Cart.php:146
[06-Nov-2023 15:41:50 UTC] PHP  22. Automattic\WooCommerce\Blocks\BlockTypes\Cart->enqueue_data($attributes = []) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/AbstractBlock.php:406
[06-Nov-2023 15:41:50 UTC] PHP  23. Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->hydrate_api_request($path = '/wc/store/v1/cart') /Users/dimitrioskytros/Local Sites/wp/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/Cart.php:253
[06-Nov-2023 15:41:50 UTC] PHP  24. Automattic\WooCommerce\Blocks\Domain\Services\Hydration->get_rest_api_response_data($path = '/wc/store/v1/cart') /Users/dimitrioskytros/Local Sites/wp/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets/AssetDataRegistry.php:326
[06-Nov-2023 15:41:50 UTC] PHP  25. rest_preload_api_request($memo = [], $path = '/wc/store/v1/cart') /Users/dimitrioskytros/Local Sites/wp/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Domain/Services/Hydration.php:45
[06-Nov-2023 15:41:50 UTC] PHP  26. rest_do_request($request = class WP_REST_Request { protected $method = 'GET'; protected $params = ['URL' => [...], 'GET' => [...], 'POST' => [...], 'FILES' => [...], 'JSON' => NULL, 'defaults' => [...]]; protected $headers = []; protected $body = NULL; protected $route = '/wc/store/v1/cart'; protected $attributes = ['methods' => [...], 'accept_json' => FALSE, 'accept_raw' => FALSE, 'show_in_index' => TRUE, 'args' => [...], 'callback' => [...], 'permission_callback' => '__return_true']; protected $parsed_json = TRUE; protected $parsed_body = FALSE }) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/rest-api.php:2912
[06-Nov-2023 15:41:50 UTC] PHP  27. WP_REST_Server->dispatch($request = class WP_REST_Request { protected $method = 'GET'; protected $params = ['URL' => [...], 'GET' => [...], 'POST' => [...], 'FILES' => [...], 'JSON' => NULL, 'defaults' => [...]]; protected $headers = []; protected $body = NULL; protected $route = '/wc/store/v1/cart'; protected $attributes = ['methods' => [...], 'accept_json' => FALSE, 'accept_raw' => FALSE, 'show_in_index' => TRUE, 'args' => [...], 'callback' => [...], 'permission_callback' => '__return_true']; protected $parsed_json = TRUE; protected $parsed_body = FALSE }) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/rest-api.php:545
[06-Nov-2023 15:41:50 UTC] PHP  28. WP_REST_Server->respond_to_request($request = class WP_REST_Request { protected $method = 'GET'; protected $params = ['URL' => [...], 'GET' => [...], 'POST' => [...], 'FILES' => [...], 'JSON' => NULL, 'defaults' => [...]]; protected $headers = []; protected $body = NULL; protected $route = '/wc/store/v1/cart'; protected $attributes = ['methods' => [...], 'accept_json' => FALSE, 'accept_raw' => FALSE, 'show_in_index' => TRUE, 'args' => [...], 'callback' => [...], 'permission_callback' => '__return_true']; protected $parsed_json = TRUE; protected $parsed_body = FALSE }, $route = '/wc/store/v1/cart', $handler = ['methods' => ['GET' => TRUE], 'accept_json' => FALSE, 'accept_raw' => FALSE, 'show_in_index' => TRUE, 'args' => ['context' => [...]], 'callback' => [0 => class Automattic\WooCommerce\StoreApi\Routes\V1\Cart { ... }, 1 => 'get_response'], 'permission_callback' => '__return_true'], $response = NULL) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/rest-api/class-wp-rest-server.php:1041
[06-Nov-2023 15:41:50 UTC] PHP  29. Automattic\WooCommerce\StoreApi\Routes\V1\AbstractCartRoute->get_response($request = class WP_REST_Request { protected $method = 'GET'; protected $params = ['URL' => [...], 'GET' => [...], 'POST' => [...], 'FILES' => [...], 'JSON' => NULL, 'defaults' => [...]]; protected $headers = []; protected $body = NULL; protected $route = '/wc/store/v1/cart'; protected $attributes = ['methods' => [...], 'accept_json' => FALSE, 'accept_raw' => FALSE, 'show_in_index' => TRUE, 'args' => [...], 'callback' => [...], 'permission_callback' => '__return_true']; protected $parsed_json = TRUE; protected $parsed_body = FALSE }) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/rest-api/class-wp-rest-server.php:1194
[06-Nov-2023 15:41:50 UTC] PHP  30. Automattic\WooCommerce\StoreApi\Utilities\CartController->calculate_totals() /Users/dimitrioskytros/Local Sites/wp/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Routes/V1/AbstractCartRoute.php:98
[06-Nov-2023 15:41:50 UTC] PHP  31. WC_Cart->calculate_shipping() /Users/dimitrioskytros/Local Sites/wp/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Utilities/CartController.php:42
[06-Nov-2023 15:41:50 UTC] PHP  32. WC_Cart->get_shipping_packages() /Users/dimitrioskytros/Local Sites/wp/app/public/wp-content/plugins/woocommerce/includes/class-wc-cart.php:1430
[06-Nov-2023 15:41:50 UTC] PHP  33. wp_list_pluck($input_list = ['a41b3bb3e6b050b6c9067c67f663b915' => ['key' => 'a41b3bb3e6b050b6c9067c67f663b915', 'product_id' => 3144, 'variation_id' => 0, 'variation' => [...], 'quantity' => 1, 'data_hash' => 'b5c1d5ca8bae6d4896cf1807cdf763f0', 'data' => class WC_Product_Simple { ... }]], $field = 'line_total', $index_key = *uninitialized*) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-content/plugins/woocommerce/includes/class-wc-cart.php:1510
[06-Nov-2023 15:41:50 UTC] PHP  34. WP_List_Util->pluck($field = 'line_total', $index_key = NULL) /Users/dimitrioskytros/Local Sites/wp/app/public/wp-includes/functions.php:5258
```

## To reproduce

1. Use the Cart/Checkout block.
2. Create a Simple Product.
3. Purchase it.
4. From the admin, go to the Orders tab and set the order as 'Completed'.
5. From the frontend, go to My Account > Orders and select the order you just placed.
6. Click "Order again".
7. See the error.

## Expected behavior

The expected behavior is that someone can order again without seeing any errors.

### WordPress (please complete the following information):

-   WordPress version: 6.3
-   WooCommerce version: 8.2.1

**Comment by opr** [comment] 2023-12-21 15:52
Hi @jimjasson thanks for reporting this however I am unable to reproduce. I followed the instructions you left, and tried on both a block theme and classic theme. No notices were shown for me.

I even checked `wp-includes/class-wp-list-util.php` line 170 and logged any attempts to access `line_total` but there were none.

Please can you try to reproduce? If not reproducible we will close the issue.

Thanks!

**Comment by jimjasson** [comment] 2023-12-29 06:11
Hey @opr 👋

Yep, I can still replicate this -- here's a short video: 

https://github.com/woocommerce/woocommerce/assets/25955483/dfc44347-a612-441c-963d-85fc3816cf63


To double-check, have you enabled `define( 'WP_DEBUG', true );` in your WP config file in order to see PHP Notices like the one above?

**Comment by wavvves** [comment] 2023-12-29 16:56
@jimjasson I'm also not getting luck replicating, can you do it on every new order? Can you do it on a JN instance and share it?

**Comment by jimjasson** [comment] 2024-01-03 07:03
Hey @wavvves and @opr, 

I asked @xristos3490 to give this a try too and couldn't replicate it, so it could be that there is something corrupt in my site that is causing this. I am frequently switching between the short-code and block based cart, so this might have something to do with it. 

In any case, I think it is safe to close this for now.

**Closed as completed** 2024-01-03 09:58 UTC
Labels: Bug, Cart, needs: triage feedback, Rubik, block: cart
