### ISSUE TITLE
Cart, Checkout, etc. Block Templates Issue

### ISSUE THREAD

**Issue by NenadObradovic** [woothemes/woocommerce#41906] opened 2023-12-06 12:40 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello guys,

I found the problem with the new Gutenberg block templates for Cart, Checkout, etc. pages when theme is not a block theme.

I created the new clean WordPress installation and by default, the Twenty Twenty-Four theme is activated (which is a block theme) then I installed the WooCommerce plugin and set it up with sample data import. After that, if you go to the website you will see that the Single Product Page and Cart page for example are built with your new Gutenberg blocks, which is ok.

After that you want to install some other theme, I installed/activated the Qi theme ( https://wordpress.org/themes/qi/ ) for example which is **NOT BLOCK theme**, and if you go to the single product page you will see that the page template is automatically returned to the classic template, which is also ok. But if you add some product to the cart and went to the cart page, you will get the problem where Cart page, Checkout, etc. are not transformed to the classic templates but stay built with Gutenberg blocks. Now you need to go manually to those pages and transform blocks to classic templates.

Thanks for your time.

Best regards,
Nenad Obradovic

### Expected behavior

Automatically transformed Cart, Checkout, etc. pages to classic templates when the theme is not a block theme.

### Actual behavior

Pages Cart, Checkout, etc. the rest were built with Gutenberg blocks

### Steps to reproduce

Please watch the video with all the steps, https://app.screencast.com/fAqFGHWVZjyK2?conversation=oUgGOSo8YJDKTX1Gw6wXtJ

### WordPress Environment ###

WordPress address (URL): http://clean-wp.local
Site address (URL): http://clean-wp.local
WC Version: 8.3.1
REST API Version: ✔ 8.3.1
WC Blocks Version: ✔ 11.4.9
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.23
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.77.0
OpenSSL/1.1.1t

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.1
WC Database Prefix: wp_
Total Database Size: 5.41MB
Database Data Size: 3.66MB
Database Index Size: 1.75MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.48MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
page: 7
post: 2
product: 18
product_variation: 7
revision: 1
shop_order_placehold: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce: by Automattic – 8.3.1
WordPress Importer: by wordpressdotorg – 0.8.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Qi
Version: 1.2.2
Author URL: https://qodeinteractive.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-07 11:56:34 +00:00
Options: ✔
Notes: 63
Onboarding: completed

### Action Scheduler ###

Complete: 4
Oldest: 2023-12-06 11:57:50 +0000
Newest: 2023-12-06 11:59:54 +0000

Failed: 1
Oldest: 2023-12-06 11:57:50 +0000
Newest: 2023-12-06 11:57:50 +0000

Pending: 1
Oldest: 2023-12-07 11:57:50 +0000
Newest: 2023-12-07 11:57:50 +0000

### Status report information ###

Generated at: 2023-12-06 12:30:14 +00:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment] 2023-12-11 14:32
This actually sounds like expected behaviour. Templates are reverted because they **require** a block theme to work—this includes product templates, and the "cart", "checkout" templates pictured here:

![Image](https://github.com/woocommerce/woocommerce/assets/90977/823e10fc-4835-43b1-8a75-0421dd6c20ae)

However, the cart and checkout **blocks** work with any theme and are the new defaults. These should _not_ revert to shortcodes automatically. The only case where you'd need to revert to shortcodes is in the presence of an extension compatibility issue. 

There is a distinction between blocks within posts/pages which work with any theme, and block templates which only work with block themes.

Hope this makes sense. I am closing this as won't fix since its the expected behaviour.

**Closed as completed by mikejolley** 2023-12-11 14:32 UTC
Labels: Bug, status: won't fix, type: community contribution, Rubik, Blocks/Patterns/Templates

**Comment by NenadObradovic** [comment] 2023-12-18 12:23
Hello @mikejolley ,

Thanks for your response. 

_"However, the cart and checkout blocks work with any theme and are the new defaults."_ - This is right only if the theme supports Gutenberg or its block theme in other cases, the theme will be messed up because you set blocks to default. 

Please consider adding some button/action or option in your Tools with that case so we can use it to return pages to works with shortcodes instead of blocks.

There is one more problem, you can also see it in the video I sent you. When the Single Product template is returned automatically to the classic and you try to add the product to the cart, **Notice Message** template is a **block template** and not **classic template** as whole page is.

For now, I used the code below to return it automatically for my case, but I want to find a better solution :)

```
<?php

if ( ! class_exists( 'TestClassName_WooCommerce' ) ) {
	/**
	 * WooCommerce theme class
	 */
	class TestClassName_WooCommerce {
		private static $instance;

		public function __construct() {

			if ( class_exists( 'WooCommerce' ) ) {
				// Check the default WooCommerce page and replace Gutenberg blocks inside content if exist
				add_action( 'admin_init', array( $this, 'update_woo_pages_content' ) );
				add_action( 'template_redirect', array( $this, 'has_block_template' ) );
			}
		}

		/**
		 * @return TestClassName_WooCommerce
		 */
		public static function get_instance() {
			if ( is_null( self::$instance ) ) {
				self::$instance = new self();
			}

			return self::$instance;
		}

		function update_woo_pages_content() {
			$is_block_theme = wp_is_block_theme();
			$is_updated     = get_transient( '_woo_pages_block_content_updated' );

			if ( ! $is_block_theme && empty( $is_updated ) ) {
				$cart_page_id     = get_option( 'woocommerce_cart_page_id' );
				$checkout_page_id = get_option( 'woocommerce_checkout_page_id' );
				$pages_to_update  = array();

				if ( ! empty( $cart_page_id ) ) {
					$pages_to_update['cart'] = $cart_page_id;
				}

				if ( ! empty( $checkout_page_id ) ) {
					$pages_to_update['checkout'] = $checkout_page_id;
				}

				if ( ! empty( $pages_to_update ) ) {
					foreach ( $pages_to_update as $page_key => $page_id ) {
						$post_content = get_the_content( null, false, $page_id );

						if ( ! empty( $post_content ) && strpos( $post_content, 'wc-block' ) !== false ) {
							// Update the post into the database
							wp_update_post(
								array(
									'ID'           => $page_id,
									'post_content' => '<!-- wp:shortcode -->[woocommerce_' . esc_attr( $page_key ) . ']<!-- /wp:shortcode -->',
								)
							);

							set_transient( '_woo_pages_block_content_updated', true );
						}
					}
				}
			}
		}

		function has_block_template() {

			if (
				is_singular( 'product' ) ||
				( is_product_taxonomy() && is_tax( 'product_cat' ) ) ||
				( is_product_taxonomy() && is_tax( 'product_tag' ) ) ||
				( is_post_type_archive( 'product' ) || is_page( wc_get_page_id( 'shop' ) ) ) ||
				( is_post_type_archive( 'product' ) && is_search() )
			) {
				add_filter( 'woocommerce_has_block_template', '__return_false', 5 );
			}
		}
	}

	TestClassName_WooCommerce::get_instance();
}
```

Best regards,
Nenad
