### ISSUE TITLE
Unexpected behavior of the method WC_Shipping_Free_Shipping::is_available()

### ISSUE THREAD

**Issue by weAreCoine** [woothemes/woocommerce#52674] opened 2024-11-08 16:20 UTC
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Unexpected behavior from the WC_Shipping_Free_Shipping::is_available method when the minimum amount for free shipping is written in decimal notation with comma

### Expected behavior

I think it is appropriate to convert the string to float before comparing so as to avoid unexpected behavior. On my sites, I solved it by modifying the control as follows:

`if ($total >= NumberUtil::round($freeShipping->min_amount, wc_get_price_decimals()) {
            $has_met_min_amount = true;
        }`

### Actual behavior

In the is_available method of the WC_Shipping_Free_Shipping class on line 207 the check between a float and a string is done. When min_amount is set using the comma for decimals (such as in Italy), the behavior of the check is abnormal. For example, in my case, it results in if(80.00 >= '400.00') returning true.

var_dump(80.0 >= '400.00'); // true
var_dump(80.0 >= '400.00'); // false

### Steps to reproduce

1. Set Woocommerce to use comma for decimals and period for thousands
2. set free shipping with a minimum threshold >100 euros (e.g., 400)
3. add a product that costs 80 euro to the cart.
4. go to checkout and note that free shipping will have been applied

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.3.3
Legacy REST API Package Version: ✔ 1.0.4
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.29
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 8.2.1
OpenSSL/3.1.4

SUHOSIN Installed: –
MySQL Version: 8.0.36-28
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 7
acf-field-group: 3
attachment: 49255
br_labels: 2
cms_block: 2
custom_css: 1
e-landing-page: 1
elementor_library: 36
elementor_snippet: 1
mc4wp-form: 2
nav_menu_item: 213
oembed_cache: 12
page: 63
post: 6
product: 1932
product_variation: 2852
product-feed: 2
revision: 16479
shop_coupon: 45
shop_order: 47
shop_order_refund: 23
woodmart_sidebar: 1
woodmart_slide: 33
wp_global_styles: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (42) ###

Query Monitor: di John Blackbourn – 3.16.4
WPML Multilingual CMS: di OnTheGoSystems – 4.5.11
Secure Custom Fields: di WordPress.org – 6.3.10.2
WooCommerce Advanced Product Labels: di BeRocket – 1.2.7
Ajax Search Pro: di Ernest Marcinko – 4.21.10
Product Feed Manager for WooCommerce: di RexTheme – 7.4.22
Classic Editor: di Contributori WordPress – 1.6.5
Classic Widgets: di WordPress Contributors – 0.3
Cloudflare: di Cloudflare
Inc. – 4.12.8

Coiné: di Luca Barbi – 0.1
Duplica pagina: di mndpsingh287 – 4.5.4
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: di Thomas Geiger – 1.20.2
Elementor Pro: di Elementor.com – 3.24.2
Elementor: di Elementor.com – 3.25.4
Font Awesome: di Font Awesome – 4.5.0
Hash Psw: di Paolo Romano – 0.1
iubenda | All-in-one Compliance for GDPR / CCPA Cookie Consent + more: di iubenda – 3.11.1
Klaviyo: di Klaviyo
Inc. – 3.4.1

Loco Translate: di Tim Whitlock – 2.6.11
MC4WP: Mailchimp for WordPress: di ibericode – 4.9.18
MC4WP: Mailchimp for WordPress Premium: di ibericode – 4.9.6
PixelYourSite PRO: di PixelYourSite – 9.0.0
Product Availability Slots for WooCommerce: di FantasticPlugins – 4.8
Product Catalog Feed Pro by PixelYourSite: di PixelYourSite – 5.5.1
Payment Plugins for PayPal WooCommerce: di Payment Plugins
support@paymentplugins.com – 1.0.53

Speed Optimizer: di SiteGround – 7.7.0
weLaunch Framework: di weLaunch.io – 1.1.1
WPC Product Bundles for WooCommerce (Premium): di WPClever – 8.1.3
Payment Plugins for Stripe WooCommerce: di Payment Plugins
support@paymentplugins.com – 3.3.77

Country Based Payments for WooCommerce: di Ivan Paulin – 1.5
WooCommerce Email Test: di RaiserWeb – 1.2.2
WooCommerce Legacy REST API: di WooCommerce – 1.0.4
WooCommerce Multilingual & Multicurrency: di OnTheGoSystems – 5.0.2
WooCommerce Product Recommendations: di WooCommerce – 1.4.15 (aggiornamento alla versione 4.1.0 disponibile)
WooCommerce Shop the Look: di weLaunch – 1.0.9
WooCommerce: di Automattic – 9.3.3
Woodmart Core: di  – 1.0.34
Yoast SEO: di Team Yoast – 23.8
WP Mail SMTP: di WP Mail SMTP – 4.2.0
WPForms Lite: di WPForms – 1.9.2.1
WPML Media: di OnTheGoSystems – 2.7.1
WPML String Translation: di OnTheGoSystems – 3.2.2

### Inactive Plugins (3) ###

Scalapay Gateway Easy Installment: di Scalapay – 3.0.0
Wordfence Security: di Wordfence – 8.0.0
Zendesk Chat Widget: di Zendesk – 1.4.18

### Dropin Plugins () ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

Legacy API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 giorni
Level threshold: –
Log directory size: 3 MB

### WC Pages ###

Shop base: #12152 - /negozio/
Carrello: #12153 - /carrello/ -  Contiene lo shortcode [woocommerce_cart]
Pagamento: #12154 - /pagamento/ -  Contiene lo shortcode [woocommerce_checkout]
Il mio account: #12155 - /mio-account/
Termini e condizioni: ❌ L'ID della pagina è impostato
ma la pagina non esiste


### Theme ###

Name: Woodmart Child
Version: 1.0.0
Author URL: http://xtemos.com
Child Theme: ✔
Parent Theme Name: Woodmart
Parent Theme Version: 6.5.4 – 7.6.0 è disponibile
Parent Theme Author URL: http://themeforest.net/user/xtemos
WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php versione 3.4.0 è obsoleta. La versione attuale è 8.6.0
woodmart/woocommerce/cart/cart-item-data.php
woodmart-child/woocommerce/cart/cart.php versione 4.4.0 è obsoleta. La versione attuale è 7.9.0
woodmart/woocommerce/cart/cross-sells.php
woodmart/woocommerce/cart/mini-cart.php versione 5.2.0 è obsoleta. La versione attuale è 9.2.0
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/checkout/thankyou.php versione 3.7.0 è obsoleta. La versione attuale è 8.1.0
woodmart/woocommerce/content-product-cat.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
woodmart-child/woocommerce/emails/admin-new-order.php
woodmart-child/woocommerce/emails/email-order-details.php
woodmart-child/woocommerce/emails/email-styles.php versione 4.0.0 è obsoleta. La versione attuale è 9.3.0
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php versione 3.6.0 è obsoleta. La versione attuale è 9.2.0
woodmart/woocommerce/global/quantity-input.php versione 4.0.0 è obsoleta. La versione attuale è 7.8.0
woodmart/woocommerce/loop/add-to-cart.php versione 3.3.0 è obsoleta. La versione attuale è 9.2.0
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php versione 2.0.0 è obsoleta. La versione attuale è 7.8.0
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php versione 3.3.1 è obsoleta. La versione attuale è 9.3.0
woodmart-child/woocommerce/loop/price.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php versione 4.1.0 è obsoleta. La versione attuale è 9.2.0
woodmart-child/woocommerce/product-searchform.php versione 3.3.0 è obsoleta. La versione attuale è 7.0.1
woodmart/woocommerce/single-product/add-to-cart/grouped.php versione 4.8.0 è obsoleta. La versione attuale è 7.0.1
woodmart/woocommerce/single-product/add-to-cart/variable.php
woodmart/woocommerce/single-product/meta.php
woodmart-child/woocommerce/single-product/price.php
woodmart/woocommerce/single-product/product-attributes.php versione 3.6.0 è obsoleta. La versione attuale è 9.3.0
woodmart/woocommerce/single-product/product-image.php versione 3.5.1 è obsoleta. La versione attuale è 9.0.0
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/description.php
woodmart/woocommerce/single-product/tabs/tabs.php
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Scopri come aggiornare					 |
					
						
					
					
						Cancella la cache delle informazioni sul tema dello stato del sistema.

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-11-09 09:55:17 +00:00
Options: ✔
Notes: 177
Onboarding: completed

### Action Scheduler ###

Complete: 3.340
Oldest: 2024-10-08 16:41:21 +0000
Newest: 2024-11-08 16:09:14 +0000

Failed: 27
Oldest: 2022-07-07 08:24:31 +0000
Newest: 2024-10-15 08:45:37 +0000

Pending: 11
Oldest: 2024-11-08 17:02:12 +0000
Newest: 2024-11-15 09:05:24 +0000


### Product Recommendations ###

Database Version: 1.4.15
Loopback Test: ✔
Task Queueing Test: ✔
Page Cache Test: ❌ Test failed.

### Status report information ###

Generated at: 2024-11-08 16:14:17 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment] 2024-11-11 23:16
Possible Duplicate of https://github.com/woocommerce/woocommerce/issues/46558

**Comment by albarin** [comment] 2024-11-12 10:22
Closing as duplicate of f https://github.com/woocommerce/woocommerce/issues/46558

**Closed as completed by albarin** 2024-11-12 10:22 UTC
Labels: Bug, Shipping, Settings, type: community contribution
