### ISSUE TITLE
checkout page not working,

### ISSUE THREAD

**Issue by avastamin** [woothemes/woocommerce#10561] opened 2016-03-15 10:00 UTC
The spinning image rounding and rounding. I tried default theme and it works but no working with my theme. 

I did not find any javascript error or php error. I debuged in many ways but there is no clue. Here is the system status: Hope someone will have idea about the problem.

`
### WordPress Environment ###

Home URL: https://ruhul.testmedidate.de
Site URL: https://ruhul.testmedidate.de
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.5.31-nmm1
PHP Post Max Size: 200 MB
PHP Time Limit: 30
PHP Max Input Vars: 3000
SUHOSIN Installed: –
MySQL Version: 5.6.27
Max Upload Size: 200 MB
Default Timezone is UTC: ✕ Default timezone is Europe/Berlin - it should be UTC
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.5.5

### Settings ###

Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #21246 - /shop/
Cart: #21247 - /cart/
Checkout: #21248 - /checkout/
My Account: #21249 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: MediDate
Version: 1.0
Author URL: http://logikstudio.de/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment] 2016-03-15 11:48
Firstly, the new issue form states that github is not for support purposes. There are forums, there is your theme authors support area if the theme is breaking the page.

2nd:

> The spinning image rounding and rounding. I tried default theme and it works but no working with my theme.

If its a theme issue, its code in your theme at fault. We cannot debug 3rd party themes for you. No doubt its a javascript issue, or its missing things like wp_footer where scripts get enqueued.

Closing this issue as its not a bug report for WC core.

**Closed by mikejolley** 2016-03-15 11:48 UTC
