### ISSUE TITLE
woocommerce.com, min.js and openness of the WP ecosystem

### ISSUE THREAD

**Issue by kkmuffme** [woothemes/woocommerce#30896] opened 2021-10-07 08:02 UTC
This is an issue relating to woocommerce.com (however there's no easy way to contact them)

Some plugins sold on woocommerce.com only include a .min.js/.min.css but not the unminified js/css.

This makes extending features, checking bugs and also validating security much harder (even impossible in some cases).
Plugins provided via woocommerce.com must have unminified js included in them too.

Otherwise, soon enough, we will have mangled PHP code too, which is against the open source policy of the WP eco-system and puts woocommmerce firmly in the magento territory (where literally everything is mangled and cannot be extended)

**Comment by juliaamosova** [comment] 2021-10-12 17:21
Hi @kkmuffme,

Thank you for reporting the issue. It is on the woocommerce.com side of things which is not a part of this repository. It is being developed in another repository which is private.

I created a bug report on your behalf in the correct (private) repository so that the right team could take a look further.

Because the issue is not related to the WooCommerce plugin itself, I am going to close it. However, please rest assured that the woocommerce.com team will take a look at it further.

**Closed as completed by juliaamosova** 2021-10-12 17:21 UTC

**Comment by madeincosmos** [comment] 2021-11-02 10:24
Hi @kkmuffme! Can you let us know which plugins on the WooCommerce.com marketplace only have minified sources? I checked a few flagship extensions like Subscriptions, Memberships or Stripe, and they all have full unminified JavaScript source code included in the plugin package.

If you purchased some plugins through our marketplace, you can get in touch with our support team through [this contact form](https://woocommerce.com/my-account/create-a-ticket/) and select **Help with my account**. You can add a link to this conversation as a reference.

Thanks!

**Comment by kkmuffme** [comment] 2021-11-03 19:54
Product Reviews Pro

I already got the source from the devs, but its a time waste to request it every time they update it.

**Comment by madeincosmos** [comment] 2021-11-04 08:10
Thanks for letting us know. We're checking with our team now what's the best way to make plugin source code accessible to everyone who bought it and will keep you updated here.
