### ISSUE TITLE
Application for e-mail " processing " to order " on- hold"

### ISSUE THREAD

**Issue by yardz** [woothemes/woocommerce#8169] opened 2015-05-15 02:18 UTC
I'm still having problems with orders to be paid with bank tiket .

When a customer purchases with bank tiket , he receives an e- mail as if the order were " processing " . However the order is "on- hold" .

As tiket can take up to four days to inform the payment , I get several calls a day asking if it has been compensated , since e- mail is not sent when when payment is approved , but when the order is made .

I'm not in trouble to "inform the details of the order" but " whether it has been paid / compensated ."

Autal the way I 'm doing the manual process . It would be interesting if the WooCommerce send an email when the order change "on -hold " to " processing " . Not with the order data, but stating " confirmed order / pay order "

**Comment by mikejolley** [comment] 2015-05-15 09:27
Dupe of https://github.com/woothemes/woocommerce/issues/8160

**Closed by mikejolley** 2015-05-15 09:27 UTC
