### ISSUE TITLE
Stock is being deducted for composed items before order is saved

### ISSUE THREAD

**Issue by eahm** [woothemes/woocommerce#38055] opened 2023-04-30 10:25 UTC
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When creating a new order from the backend admin panel in WooCommerce and adding a new composed item, the child items of the composed item are deducted from the stock immediately upon adding them, even if the order is still in pending status and has not been saved. The expected behavior is that the stock for child items of composed items should only be deducted once the order has been saved and the status is set to actionable.

### Expected behavior

The stock for child items of composed items should only be deducted once the order has been saved with actionable status.

### Actual behavior

The stock for child items of composed items is deducted immediately upon adding the composed item to the order, even if the order is still in pending status or not been saved.

### Steps to reproduce

Steps to reproduce:
The composed item:
-Stock management: unchecked
-Stock status: In stock
-Components: item with (Stock management: checked, Stock status: In stock)
1. Go to the WooCommerce backend admin panel and create a new order.
2. Click 'Add Item(s)' button then click 'Add Product(s)', select the composed item then click 'Add' button.
3. Observe that the stock for the child items is immediately deducted by going to the product page, even though the order is in pending status and has not been saved or click create.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.passion-way.net
Site address (URL): https://www.passion-way.net
WC Version: 7.6.1
REST API Version: ✔ 7.6.1
WC Blocks Version: ✔ 9.8.5
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: ❌ 6.1.1 - There is a newer version of WordPress available (6.2)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 48 MB
PHP Time Limit: 300
PHP Max Input Vars: 2000
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 5.5.68-MariaDB
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.1
WC Database Prefix: P5s54_
Total Database Size: 3196.17MB
Database Data Size: 1702.47MB
Database Index Size: 1493.70MB
P5s54_woocommerce_sessions: Data: 2.02MB + Index: 0.05MB + Engine InnoDB
P5s54_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
P5s54_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
P5s54_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
P5s54_woocommerce_order_items: Data: 52.59MB + Index: 30.59MB + Engine InnoDB
P5s54_woocommerce_order_itemmeta: Data: 522.00MB + Index: 530.92MB + Engine InnoDB
P5s54_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
P5s54_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
P5s54_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
P5s54_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
P5s54_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
P5s54_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
P5s54_actionscheduler_actions: Data: 12.02MB + Index: 16.13MB + Engine InnoDB
P5s54_actionscheduler_claims: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
P5s54_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
P5s54_actionscheduler_logs: Data: 11.02MB + Index: 8.03MB + Engine InnoDB
P5s54_ac_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_admin_columns: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
P5s54_aryo_activity_log: Data: 13.02MB + Index: 0.00MB + Engine InnoDB
P5s54_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
P5s54_atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
P5s54_atum_product_data: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
P5s54_bulkgate_module: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
P5s54_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
P5s54_comments: Data: 260.80MB + Index: 154.42MB + Engine InnoDB
P5s54_easywpsmtp_debug_events: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
P5s54_easywpsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_ewwwio_images: Data: 0.50MB + Index: 0.39MB + Engine InnoDB
P5s54_ewwwio_queue: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
P5s54_jetpack_waf_blocklog: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
P5s54_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
P5s54_options: Data: 37.23MB + Index: 5.05MB + Engine InnoDB
P5s54_postmeta: Data: 498.98MB + Index: 527.80MB + Engine InnoDB
P5s54_posts: Data: 52.48MB + Index: 31.95MB + Engine InnoDB
P5s54_pw_stock_log: Data: 41.58MB + Index: 0.00MB + Engine InnoDB
P5s54_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
P5s54_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_revslider_sliders: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
P5s54_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_revslider_slides: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
P5s54_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
P5s54_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_rm_fields: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
P5s54_rm_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_rm_front_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_rm_login: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_rm_login_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_rm_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_rm_paypal_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_rm_paypal_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_rm_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_rm_sent_mails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_rm_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_rm_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_rm_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_rm_submission_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_rm_tasks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_rm_task_exe_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_stock_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_termmeta: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
P5s54_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
P5s54_term_relationships: Data: 0.42MB + Index: 0.22MB + Engine InnoDB
P5s54_term_taxonomy: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
P5s54_usermeta: Data: 67.61MB + Index: 56.14MB + Engine InnoDB
P5s54_users: Data: 3.52MB + Index: 4.55MB + Engine InnoDB
P5s54_user_tokens: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
P5s54_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
P5s54_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_wc_customer_lookup: Data: 5.52MB + Index: 4.03MB + Engine InnoDB
P5s54_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
P5s54_wc_order_composite_lookup: Data: 12.52MB + Index: 20.97MB + Engine InnoDB
P5s54_wc_order_coupon_lookup: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
P5s54_wc_order_product_lookup: Data: 73.61MB + Index: 78.19MB + Engine InnoDB
P5s54_wc_order_stats: Data: 22.55MB + Index: 14.52MB + Engine InnoDB
P5s54_wc_order_tax_lookup: Data: 9.52MB + Index: 8.03MB + Engine InnoDB
P5s54_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
P5s54_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
P5s54_wc_product_meta_lookup: Data: 0.25MB + Index: 0.44MB + Engine InnoDB
P5s54_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
P5s54_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
P5s54_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
P5s54_wfpklist_template_data: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
P5s54_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_yikes_easy_mc_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
P5s54_yoast_seo_links: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
P5s54_yoast_seo_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
P5s54_zp_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 4
acf-field-group: 1
attachment: 3005
atum_supplier: 1
customize_changeset: 2
fs-shipping-notice: 1
jp_sitemap: 1
jp_sitemap_master: 1
jp_vid_sitemap: 1
la_block: 1
la_portfolio: 15
la_team_member: 4
la_testimonial: 7
nav_menu_item: 33
page: 21
pos-station: 7
product: 1488
revision: 66
shop_coupon: 12
shop_order: 141763
shop_order_refund: 1
wp_global_styles: 1
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

Cloudflare: by Cloudflare
Inc. – 4.11.0

Contact Form 7: by Takayuki Miyoshi – 5.7.6
WooCommerce Composite Products: by WooCommerce – 8.7.5
WooCommerce Shipping & Tax: by WooCommerce – 2.2.4
WooCommerce: by Automattic – 7.6.1
LightStart - Maintenance Mode, Coming Soon and Landing Page Builder: by Themeisle – 2.6.7

### Inactive Plugins (19) ###

Members: by MemberPress – 3.2.5
Order Minimum/Maximum Amount for WooCommerce: by WPFactory – 4.2.9

Query Monitor: by John Blackbourn – 3.12.2
W3 Total Cache: by BoldGrid – 2.3.1
WooCommerce Payments: by Automattic – 5.5.1 (update to version 5.8.0 is available)
WP Crontrol: by John Blackbourn & crontributors – 1.15.2
WP Super Cache: by Automattic – 1.9.4

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: BHD (BD)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 3
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #875 - /shop/
Cart: #876 - /cart/
Checkout: #877 - /checkout/
My account: #878 - /my-account/
Terms and conditions: #189 - /terms-and-conditions/

### Theme ###

Name: Lapa Child
Version: 1.0
Author URL: http://themeforest.net/user/LA-Studio?ref=LA-Studio
Child Theme: ✔
Parent Theme Name: Lapa
Parent Theme Version: 1.2.2
Parent Theme Author URL: http://themeforest.net/user/LA-Studio?ref=LA-Studio
WooCommerce Support: ✔

### Templates ###

Overrides: lapa/woocommerce/archive-product.php
lapa-child/woocommerce/cart/cart-shipping.php
lapa-child/woocommerce/cart/cart.php
lapa/woocommerce/cart/cross-sells.php
lapa-child/woocommerce/cart/mini-cart.php
lapa-child/woocommerce/checkout/form-pay.php
lapa-child/woocommerce/checkout/order-receipt.php
lapa-child/woocommerce/checkout/payment.php
lapa-child/woocommerce/checkout/review-order.php
lapa/woocommerce/content-product.php
lapa/woocommerce/content-single-product.php
lapa/woocommerce/global/quantity-input.php
lapa/woocommerce/loop/add-to-cart.php
lapa/woocommerce/loop/loop-end.php
lapa/woocommerce/loop/loop-start.php
lapa/woocommerce/loop/orderby.php
lapa/woocommerce/loop/pagination.php
lapa/woocommerce/loop/sale-flash.php
lapa/woocommerce/myaccount/form-login.php version 6.1.0 is out of date. The core version is 7.0.1
lapa-child/woocommerce/order/order-details-customer.php
lapa/woocommerce/product-searchform.php
lapa/woocommerce/single-product/price.php
lapa/woocommerce/single-product/product-image.php
lapa/woocommerce/single-product/related.php
lapa/woocommerce/single-product/tabs/tabs.php
lapa/woocommerce/single-product/up-sells.php
lapa/woocommerce/taxonomy-product-cat.php version 3.4.0 is out of date. The core version is 4.7.0

Outdated Templates: ❌
					
					
						Learn how to update

### Composite Products ###

Database Version: 8.7.5
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-30 20:04:56 +03:00
Options: ✔
Notes: 19
Onboarding: completed

### Action Scheduler ###

Complete: 35,170
Oldest: 2023-03-30 13:18:18 +0300
Newest: 2023-04-30 13:03:25 +0300

Failed: 88
Oldest: 2022-09-24 09:27:06 +0300
Newest: 2023-04-19 17:56:47 +0300

Pending: 1
Oldest: 2023-04-30 22:41:25 +0300
Newest: 2023-04-30 22:41:25 +0300

### Status report information ###

Generated at: 2023-04-30 13:19:22 +03:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Konamiman** [comment] 2023-05-08 07:15
Hi @eahm, thanks for your report. This issue is caused by the WooCommerce Composite Products extension, not by WooCommerce itself. So I'm closing this issue and notifying it to the extension development team.

**Closed as completed by Konamiman** 2023-05-08 07:15 UTC
Labels: Bug, Product/Inventory Management, needs: developer feedback, plugin: woocommerce, type: community contribution
