### ISSUE TITLE
Check $transient for possible non object values in class-wc-helper-updater.php

### ISSUE THREAD

**Issue by kaushikasomaiya** [woothemes/woocommerce#38649] opened 2023-06-08 14:25 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Opening this as directed in p1686229233690439-slack-C7U3Y3VMY

$transient might be null or non-object in various cases due to conflicting themes/plugins or server issues.

https://github.com/woocommerce/woocommerce/blob/5c4746cefc1d5d4ac5753d969cef2c83f4e5e9db/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php#L39

This sometimes causes warnings or worse crashes the site. 

Affected tickets:

- 6383574-zen

> En fejl af typen E_ERROR skete i linje 75 i filen wp-content/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php. Fejlbesked: Uncaught Error: Attempt to modify property "no_update" on null in  wp-content/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php:75

Other cases:

- 5944779-zen
- 6241920-zen
- 4128750-zen
- 4212553-zen
- https://wordpress.org/support/topic/woocommerce-no_update-on-null-and-php-8-0/#post-15677856
- 5944773-zen
- 4218483-zen
- https://wordpress.org/support/topic/e_error-help/#post-16661123
- https://wordpress.org/support/topic/probleme-class-wc-helper-updater-php/
- https://wordpress.org/support/topic/class-wc-helper-updater-php-causing-critical-error/

I am opening this for further investigation and see if we can protect against bad $transient values.

**Comment by kaushikasomaiya** [comment] 2023-10-05 11:10
7125987-zen
> 023-10-05T08:31:40+00:00 CRITICAL Uncaught Error: Attempt to assign property "translations" on bool in /chroot/ html/wp-content/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php:81

**Comment by mi5t4n** [comment] 2023-10-13 08:27
May be a Duplicate of #40319 .

PR: #40733

**Comment by barryhughes** [comment] 2023-10-20 18:20
Thanks, @mi5t4n. I agree—let's go ahead and close this one.

For the benefit of others coming across this, the fix in [PR#40733](https://github.com/woocommerce/woocommerce/pull/40733) should generally be available in our upcoming 8.3.0 release (scheduled for November 14).

**Closed as completed by barryhughes** 2023-10-20 18:20 UTC
Labels: Bug, WCCOM/Marketplace

**Comment by pinkiyadav84** [comment] 2023-11-20 11:32
Issue still not resolve in 8.3.0. Please advise when this issue will resolve?

**Comment by barryhughes** [comment] 2023-11-20 17:13
The linked PR was merged. Are you sure the issue you are seeing is identical, and can you provide any more information (a full error message and/or backtrace)?

**Comment by pinkiyadav84** [comment] 2023-11-21 11:13
https://github.com/woocommerce/woocommerce/issues/38649 i am facing same issue:

Uncaught Error: Attempt to assign property "translations" on bool in /chroot/home/a2ebae18/[9723015b29.nxcli.io/html/wp-content/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php:81](http://9723015b29.nxcli.io/html/wp-content/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php:81) Stack trace: #0 /chroot/home/a2ebae18/[9723015b29.nxcli.io/html/wp-includes/class-wp-hook.php(312)](http://9723015b29.nxcli.io/html/wp-includes/class-wp-hook.php(312)): WC_Helper_Updater::transient_update_plugins(true) #1 /chroot/home/a2ebae18/[9723015b29.nxcli.io/html/wp-includes/plugin.php(205)](http://9723015b29.nxcli.io/html/wp-includes/plugin.php(205)): WP_Hook->apply_filters(true, Array) #2 /chroot/home/a2ebae18/[9723015b29.nxcli.io/html/wp-includes/option.php(2053)](http://9723015b29.nxcli.io/html/wp-includes/option.php(2053)): apply_filters('pre_set_site_tr...', Object(stdClass), 'update_plugins') #3 /chroot/home/a2ebae18/[9723015b29.nxcli.io/html/wp-includes/update.php(393)](http://9723015b29.nxcli.io/html/wp-includes/update.php(393)): set_site_transient('update_plugins', Object(stdClass)) #4 /chroot/home/a2ebae18/[9723015b29.nxcli.io/html/wp-includes/update.php(1022)](http://9723015b29.nxcli.io/html/wp-includes/update.php(1022)): wp_update_plugins() #5 /chroot/home/a2ebae18/[9723015b29.nxcli.io/html/wp-includes/class-wp-hook.php(310)](http://9723015b29.nxcli.io/html/wp-includes/class-wp-hook.php(310)): _maybe_update_plugins('') #6 /chroot/home/a2ebae18/[9723015b29.nxcli.io/html/wp-includes/class-wp-hook.php(334)](http://9723015b29.nxcli.io/html/wp-includes/class-wp-hook.php(334)): WP_Hook->apply_filters(NULL, Array) #7 /chroot/home/a2ebae18/[9723015b29.nxcli.io/html/wp-includes/plugin.php(517)](http://9723015b29.nxcli.io/html/wp-includes/plugin.php(517)): WP_Hook->do_action(Array) #8 /chroot/home/a2ebae18/[9723015b29.nxcli.io/html/wp-admin/admin.php(175)](http://9723015b29.nxcli.io/html/wp-admin/admin.php(175)): do_action('admin_init') #9 /chroot/home/a2ebae18/[9723015b29.nxcli.io/html/wp-admin/plugins.php(10)](http://9723015b29.nxcli.io/html/wp-admin/plugins.php(10)): require_once('/chroot/home/a2...') #10 {main} thrown in /chroot/home/a2ebae18/[9723015b29.nxcli.io/html/wp-content/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php](http://9723015b29.nxcli.io/html/wp-content/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php) on line 81

**Comment by barryhughes** [comment] 2023-11-21 18:01
Are you positive you have updated to `8.3.0`? Let's look at part of the error message you shared (I shortened the filepath a little, for brevity):

```
Uncaught Error: Attempt to assign property "translations" on bool in 
/.../wp-content/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php:81)
```

If we look at that specific line in the context of our 8.2.2 release, the error 'makes sense':

https://github.com/woocommerce/woocommerce/blob/8.2.2/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php#L81

However, if we look at the same line in the context of our 8.3.0 release, it points to an empty line and you can see the safe-guards we added on the following line:

https://github.com/woocommerce/woocommerce/blob/8.3.0/plugins/woocommerce/includes/admin/helper/class-wc-helper-updater.php#L81
