### ISSUE TITLE
Prevent duplicate orders being placed

### ISSUE THREAD

**Issue by WillBrubaker** [woothemes/woocommerce#41527] opened 2023-11-16 21:06 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When processing checkout, if a payment is successful, a call to `wp_send_json` is made, and we expect the browser to redirect upon receiving that in response to the AJAX request. However, if the webserver chokes at this critical moment, the AJAX call may receive a 503 response code or an empty response. This will result in an error message being displayed to the customer. This may be `SyntaxError: Unexpected end of JSON input` or `SyntaxError: unexpected token < in JSON at position 0`. This leads the customer to believe that payment was unsuccessful and they will try again, sometimes repeatedly, resulting in multiple orders/charges.

### Expected behavior

The JavaScript on checkout fires a `checkout_error` event. I would expect if that event is fired, the checkout button would be disabled and/or additional messaging displayed to the customer. Perhaps prompt them to check their email for order confirmation or contact the shop owner before trying to resubmit payment.

### Actual behavior

When this happens, it ends up causing some exceedingly tricky troubleshooting. Aside from the obvious multiple orders and charges, it's often difficult to find evidence that this happened. It's not necessarily caused by a PHP error so there's nothing in PHP error logs. Payments are successful so there's no clues in payment gateway logs.

2764754-zen
7238549-zen
6669306-zen
4164886-zen
3635960-zen

### Steps to reproduce

1. To simulate what happens when the webserver chokes, you can add `die(503)` right before this line: https://github.com/woocommerce/woocommerce/blob/8.3.0/plugins/woocommerce/includes/class-wc-checkout.php#L1069
2. Go through checkout
3. Receive error though order exists and is paid
4. Repeat 2 & 3 until bankrupt and angry

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://testsite.local
Site address (URL): https://testsite.local
WC Version: 8.2.2
REST API Version: ✔ 8.2.2
WC Blocks Version: ✔ 11.1.3
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Unix)
PHP Version: 7.4.30
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.0.20
WC Database Prefix: wp_
Total Database Size: 83.19MB
Database Data Size: 47.71MB
Database Index Size: 35.48MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.38MB + Index: 0.81MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.48MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 11.52MB + Index: 12.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fakenames: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
ib_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.08MB + Index: 2.67MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.06MB + Index: 2.05MB + Engine InnoDB
wp_afwc_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_commission_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_hits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_afwc_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_afwc_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.13MB + Index: 0.31MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 1.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.22MB + Index: 0.52MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 10.19MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 2.47MB + Index: 0.89MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.14MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 2.52MB + Index: 5.03MB + Engine InnoDB
wp_users: Data: 0.17MB + Index: 0.17MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.23MB + Index: 0.17MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_mnm_child_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 2.52MB + Index: 4.98MB + Engine InnoDB
wp_wc_order_stats: Data: 0.48MB + Index: 0.47MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcrp_rental_products_rentals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcrp_rental_products_rentals_archive: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_ab_testing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_ab_testing_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_ab_testing_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 399
aw_workflow: 1
bookable_resource: 1
customize_changeset: 4
mailpoet_page: 1
order_shipment: 4
page: 12
post: 2
product: 215
product_variation: 12
revision: 19
shop_bogof_rule: 1
shop_coupon: 2
shop_order: 76
shop_order_refund: 2
shop_subscription: 19
wc_booking: 6
wp_global_styles: 2
wp_navigation: 1
wp_template: 3
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

AutomateWoo: by WooCommerce – 6.0.8
My Template Overrides: by Hiro – 0.1b
Proxy HTTP requests: by Hiro – 0.1b
Testing various code snippets: by Will    Brubaker – 1.0
WooCommerce Bookings: by WooCommerce – 2.0.5
WooCommerce Stripe Gateway: by WooCommerce – 7.6.2
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 6.7.0 (update to version 6.8.0 is available)
WooCommerce Points and Rewards: by WooCommerce – 1.7.45
WooCommerce Pre-Orders: by WooCommerce – 2.0.5
WooCommerce Product Add-ons: by WooCommerce – 6.5.0
WooCommerce Square: by WooCommerce – 4.3.1
Woo Subscriptions: by WooCommerce – 5.7.0
WooCommerce: by Automattic – 8.2.2 (update to version 8.3.0 is available)

### Inactive Plugins (34) ###

A/B Testing for WooCommerce: by Progressus.io – 1.1.3
Affiliate For WooCommerce: by StoreApps – 6.30.0
Ajax Pagination & Infinite scroll for WooCommerce: by FME ADDONS – 1.0.0
Braintree for WooCommerce Payment Gateway: by WooCommerce – 3.0.8
FakerPress: by Gustavo Bordoni – 0.6.1
Import Export Suite for WooCommerce: by WebToffee – 1.2.2
MailPoet: by MailPoet – 4.35.1
Order Item Backtrace Logger: by Hiro – 0.1b
Order Status Change Update Backtrace Logger: by Hiro – 0.1b
Query Monitor: by John Blackbourn – 3.14.1
Rental Products: by 99w – 4.4.1
Subscriptions can not be activated Backtrace Logger: by Hiro – 0.1b
WooCommerce Affirm Gateway: by WooCommerce – 2.1.1
WooCommerce All Products For Subscriptions: by WooCommerce – 4.1.3
WooCommerce Box Office: by WooCommerce – 1.2.2
WooCommerce Brands: by WooCommerce – 1.6.62
WooCommerce Buy One Get One Free: by Oscar Gare – 4.1.5
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.12
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.5.0
WooCommerce Deposits: by WooCommerce – 2.2.2
WooCommerce Flat Rate Box Shipping: by WooCommerce – 2.2.4
WooCommerce Gift Cards: by WooCommerce – 1.16.6
WooCommerce Measurement Price Calculator: by SkyVerge – 3.22.0
WooCommerce Memberships: by SkyVerge – 1.25.0
WooCommerce Min/Max Quantities: by WooCommerce – 4.1.2
WooCommerce One Page Checkout: by Automattic – 2.8.1
WooCommerce Order Status Manager: by SkyVerge – 1.15.2
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.65
WooCommerce Product Vendors: by WooCommerce – 2.2.3
WooCommerce Ship to Multiple Addresses: by WooCommerce – 4.0.0
WooCommerce Table Rate Shipping: by WooCommerce – 3.1.6
WooCommerce USPS Shipping: by WooCommerce – 4.7.5
WooCommerce Warranty Requests: by WooCommerce – 2.3.0
YayPricing Pro - WooCommerce Dynamic Pricing And Discounts: by YayCommerce – 2.4.9

### Must Use Plugins (1) ###

My Muplugin: by Ghost in the machine – 1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7704 - /shop/
Cart: #7705 - /cart/
Checkout: #7706 - /checkout/
My account: #7707 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Blockbase
Version: 3.1.16
Author URL: https://automattic.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /Users/will/Local Sites/testsitewoo/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/Users/will/Local Sites/testsitewoo/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/Users/will/Local Sites/testsitewoo/app/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### WooPayments ###

Version: 6.7.0
Connected to WPCOM: Yes
WPCOM Blog ID: 223142506
Account ID: acct_1Nmqvl2EfXYIEFts
Payment Gateway: Enabled
Test Mode: Enabled
UPE: Enabled (deferred_intent)
UPE Enabled APMs: card,bancontact,ideal,sofort
WooPay: Enabled (product,cart,checkout)
WooPay Incompatible Extensions: Yes
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Public Key Encryption: Disabled
Auth and Capture: Enabled
Documents: Enabled
Logging: Enabled

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://testsite.local
Subscriptions-core Library Version: 6.5.0
Subscription Statuses: wc-active: 5
wc-pending: 2
wc-on-hold: 9
wc-cancelled: 3

WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Washington

### Subscriptions by Payment Gateway ###

other: wc-on-hold: 1
wc-active: 1

Stripe: wc-cancelled: 3
wc-on-hold: 4
wc-active: 2

WooPayments: wc-active: 2
wc-on-hold: 1

### Payment Gateway Support ###

WooPayments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

Square: products
card_types
customer_decline_messages
payment_form
authorization
charge
charge-virtual
capture_charge
refunds
voids
customer_id
tokenization
add_payment_method
token_editor
subscriptions
subscription_suspension
subscription_cancellation
subscription_reactivation
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_change_customer
subscription_payment_method_change_admin
pre-orders

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders

WooPayments (Bancontact): products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

WooPayments (iDEAL): products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

WooPayments (Sofort): products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

### Square ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Save to Log

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-11-14 06:19:22 -07:00
Options: ✔
Notes: 123
Onboarding: skipped

### Action Scheduler ###

Canceled: 53
Oldest: 2023-10-17 02:47:59 +0000
Newest: -0001-11-30 00:00:00 +0000

Complete: 2,790
Oldest: 2023-10-16 00:13:26 +0000
Newest: 2023-11-09 03:35:40 +0000

Failed: 141
Oldest: 2023-03-02 00:49:01 +0000
Newest: 2023-11-13 03:26:07 +0000

Pending: 61
Oldest: 2023-11-14 03:38:41 +0000
Newest: 2024-10-11 04:17:37 +0000

### Status report information ###

Generated at: 2023-11-16 14:06:05 -07:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by adam-sandor** [comment] 2023-12-19 18:19
I would like to pile on here - we had very serious problems in our shop because of this issue. Somehow this was happening for about 5% of our orders causing a lot of duplicate orders by customers.

**Comment by lkraav** [comment] 2023-12-19 20:50
I'd highly recommend looking through #14541, esp. if you're running WC any older than current 8.4.

**Comment by adam-sandor** [comment] 2023-12-31 17:02
I'm running 8.3.1 and have tons of duplicate orders. Looking at the release notes of 8.4 there doesn't seem to be any changes fixing that. Or did I miss something?

**Comment by glagonikas** [comment] 2023-12-31 17:50
> I'm running 8.3.1 and have tons of duplicate orders. Looking at the release notes of 8.4 there doesn't seem to be any changes fixing that. Or did I miss something? 

It's worth looking for patterns and listing your active plugins, as there are quite a few reasons why this might occur.

For example, this might occur mostly with a specific gateway or payment method.

In our case it was caused by the bug resolved in this thread and there was a separate issue for customers using apple pay, so two separate plugins needed to be identified

**Comment by WillBrubaker** [comment] 2024-01-09 04:26
7524694-zen

**Comment by lynnjat7** [comment] 2024-02-08 18:34
Same issue here: 7712167-zen

**Comment by sverleis** [comment] 2024-02-23 14:53
Happening for customer in 7769519-zen

**Comment by wavvves** [comment] 2024-03-26 15:22
I'm currently looking at this and discussing a way to fix it https://github.com/woocommerce/woocommerce/issues/43770#issuecomment-2020268481

**Comment by wavvves** [comment] 2024-03-26 16:07
Just an update while debugging this, it may actually be worst than expected.
If we tamper with the $result making it invalid on L1063, we get the following actually encouraging the shopper to re-try the order:

<img width="476" alt="image" src="https://github.com/woocommerce/woocommerce/assets/17236129/6106339c-2543-400c-8f7d-1593abdfdc04">

Which in case the payment was made, it's a big no. The order went through and it is available in the system. 

~EDIT: Fortunately it is not possible anymore to simply click place order again, as the cart is cleared so the user will be presented with the following:~

<img width="454" alt="image" src="https://github.com/woocommerce/woocommerce/assets/17236129/d8696064-90cd-46bb-9397-1c6e50db1492">

~From there, the only way to duplicate the order is to rebuild cart and go through the checkout flow once more.~

Actually it is, but by inserting a `die()` in `process_checkout()`

I'm opening a PR offering better feedback in case of an inadequate response from the payment gateway / any problem parsing that into a proper JSON response, wrapping `SyntaxError: Unexpected end of JSON input` or` SyntaxError: unexpected token < in JSON at position 0` (and any JSON parse issue) with actual helpful information for the shopper.

**Closed as completed** 2024-04-05 14:21 UTC
Labels: Bug, Checkout, Rubik, impact: high
