### ISSUE TITLE
Ensure stale bot notifies authors of stale issues and PRs and closes them after sufficient inactivity

### ISSUE THREAD

**Issue by lsinger** [woothemes/woocommerce#37786] opened 2023-04-18 12:20 UTC

**Comment by DavidAnderson684** [comment] 2023-04-18 16:53
This suggestion comes up regularly in different free software projects. But ignoring peoples' issues for a really long time isn't a situation that's improved by auto-closing them. Auto-closing is just a way of treating the symptom ("2000 issues still open, we can reduce that number with an auto-closing bot!") instead of the cause (reported issues are ignored for years when somebody needs to do their job by taking a definite decision on the issue, whether that's `wontfix` or something else).

What's needed is human beings to go through them. Auto-closing issues just creates huge amounts of pointless "busy work" when the reporters get the alerts and come back to re-open them (or when other people re-report the same issue). But don't close issues simply on the grounds that nobody looked at them, that's just automated time-wasting for no actual gain (lowering the number shown in the "open issues" total is not a real gain).

**Comment by rrennick** [comment] 2023-04-25 20:53
> Auto-closing issues just creates huge amounts of pointless "busy work" when the reporters get the alerts and come back to re-open them (or when other people re-report the same issue).

@DavidAnderson684 I appreciate where you are coming from. However, I monitored the stalebot for a few months after it was [originally implemented](https://github.com/woocommerce/woocommerce/commit/cea88305a79097703c7978152b8156d3578fb22c) and very few of the issues it closed were re-opened. The stalebot warns the reporter that it will close the issue if the issue is not updated in the next 7 days. Doing that improved the probability that an issue would be followed up on.

**Comment by DavidAnderson684** [comment] 2023-04-25 21:33
Speaking personally, in other bug trackers that have implemented stale bots, my response to having no reply on a ticket for a year, two years, whatever, and then getting the stale bot saying "please post to re-open this if you still care" is often to not bother, because you doubt that the chances that it'll get attention if you do are worth it. So, here in the WooCommerce issue tracker, there are 2000 open issues. If you re-open an issue, it's more in hope than solid belief that something will happen. So, I think you'd have to do a survey of *why* people didn't re-open their issues to conclude that it's because the issue can be believed with high confidence to be no longer relevant rather than for any other reason.

**Comment by rrennick** [comment] 2023-04-26 11:01
> in other bug trackers that have implemented stale bots, my response to having no reply on a ticket for a year, two years, whatever, and then getting the stale bot saying "please post to re-open this if you still care"

I appreciate that your comment/feedback is based on other stalebots. This stalebot did not close issues based on issue age.

> I think you'd have to do a survey of why people didn't re-open their issues

The current logic it has is that it closes issues where we have asked for more information and do not receive a response. Excluding weekends, the request for more info is usually made within 48 hours of issue creation. The reporter has 14 days after the request to respond before the issue was closed. The reason it's not currently working is that the labels in the repo have changed and it filters issues with specific labels.

**Comment by ObliviousHarmony** [comment] 2023-05-19 22:00
We discussed this in yesterday's team meeting and decided against moving forward with it right now. There is currently a lot of discussion in-flight about addressing our issue and pull request backlog. As part of that we can talk about how to address stale issues and PRs and re-implement this bot according to the rules that are decided upon. I have disabled [the stalebot workflow](https://github.com/woocommerce/woocommerce/actions/workflows/stalebot.yml) for now pending this work.

**Closed as not planned by ObliviousHarmony** 2023-05-19 22:00 UTC
Labels: Task (new), focus: monorepo infrastructure
