### ISSUE TITLE
no customer ID with HPOS and WC 8.1.0 or 8.1.1

### ISSUE THREAD

**Issue by CameronD73** [woothemes/woocommerce#40236] opened 2023-09-17 06:13 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

All our products are subscriptions.
I was previously running 8.0.x in sync mode, with HPOS as the primary.
All orders since WC 8.1.0 upgrade have failed.

Symptoms: I create a new order, go to checkout, fill out personal details, and after checkout,

1. the new user account is created
2. the new customer gets sent welcome email
3. I get error message "Invalid subscription customer_id" and the checkout refuses to proceed.

Examing the orders shows customer ID is always "guest" and there are no customer details.

_**If I switch to POST tables as the primary method then it all proceeds as expected.**_

WP version 6.3.1
WC-subscriptions v5.4.0
I have template overrides on some files in my theme, but all are up to date.

### Expected behavior

I expect the same outcome whether HPOS or Post tables are the primary record.

### Actual behavior

as described in first section - customer id gets set to zero after the customer account (wordpress user account) gets created.

### Steps to reproduce

as described in first section.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://birdsqueensland.org.au
Site address (URL): https://birdsqueensland.org.au
WC Version: 8.1.1
REST API Version: ✔ 8.1.1
WC Blocks Version: ✔ 10.9.3
Action Scheduler Version: ✔ 3.6.2
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 3100
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.15-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.1.1
WC Database Prefix: wpzi_
Total Database Size: 200.68MB
Database Data Size: 135.89MB
Database Index Size: 64.79MB
wpzi_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wpzi_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzi_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzi_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpzi_woocommerce_order_items: Data: 0.16MB + Index: 0.08MB + Engine InnoDB
wpzi_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.86MB + Engine InnoDB
wpzi_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpzi_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzi_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzi_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzi_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzi_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzi_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzi_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzi_actionscheduler_actions: Data: 21.13MB + Index: 14.33MB + Engine InnoDB
wpzi_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzi_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzi_actionscheduler_logs: Data: 9.09MB + Index: 9.13MB + Engine InnoDB
wpzi_ac_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzi_admin_columns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzi_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpzi_automatewoo_customers: Data: 0.09MB + Index: 0.19MB + Engine InnoDB
wpzi_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzi_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpzi_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzi_automatewoo_logs: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wpzi_automatewoo_log_meta: Data: 0.11MB + Index: 0.14MB + Engine InnoDB
wpzi_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpzi_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzi_charitable_campaign_donations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpzi_charitable_donormeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzi_charitable_donors: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpzi_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzi_comments: Data: 1.52MB + Index: 0.67MB + Engine InnoDB
wpzi_email_log: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wpzi_facetwp_index: Data: 0.28MB + Index: 0.44MB + Engine InnoDB
wpzi_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzi_gf_entry: Data: 0.22MB + Index: 0.03MB + Engine InnoDB
wpzi_gf_entry_meta: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
wpzi_gf_entry_notes: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wpzi_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzi_gf_form_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpzi_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzi_gf_form_view: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpzi_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzi_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzi_loginizer_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzi_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzi_mailchimp_jobs: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wpzi_options: Data: 10.38MB + Index: 0.19MB + Engine InnoDB
wpzi_pmxe_exports: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wpzi_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wpzi_pmxe_posts: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wpzi_pmxe_templates: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wpzi_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzi_pmxi_hash: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wpzi_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzi_pmxi_images: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wpzi_pmxi_imports: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wpzi_pmxi_posts: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
wpzi_pmxi_templates: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wpzi_postexpirator_debug: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzi_postmeta: Data: 16.52MB + Index: 14.06MB + Engine InnoDB
wpzi_posts: Data: 2.52MB + Index: 1.25MB + Engine InnoDB
wpzi_ppfuture_actions_args: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpzi_redirection_404: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzi_redirection_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzi_redirection_items: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wpzi_redirection_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzi_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzi_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzi_term_relationships: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
wpzi_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpzi_usermeta: Data: 3.50MB + Index: 5.03MB + Engine InnoDB
wpzi_users: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wpzi_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpzi_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzi_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzi_wc_customer_lookup: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wpzi_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzi_wc_orders: Data: 0.42MB + Index: 0.21MB + Engine MyISAM
wpzi_wc_orders_meta: Data: 2.04MB + Index: 2.83MB + Engine MyISAM
wpzi_wc_order_addresses: Data: 0.34MB + Index: 0.24MB + Engine MyISAM
wpzi_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzi_wc_order_operational_data: Data: 0.26MB + Index: 0.13MB + Engine MyISAM
wpzi_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wpzi_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wpzi_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzi_wc_product_attributes_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzi_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpzi_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpzi_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzi_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzi_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzi_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzi_wfblockediplog: Data: 0.10MB + Index: 0.08MB + Engine MyISAM
wpzi_wfblocks7: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wpzi_wfconfig: Data: 2.60MB + Index: 0.02MB + Engine MyISAM
wpzi_wfcrawlers: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpzi_wffilechanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzi_wffilemods: Data: 5.40MB + Index: 0.66MB + Engine MyISAM
wpzi_wfhits: Data: 1.65MB + Index: 0.16MB + Engine MyISAM
wpzi_wfhoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzi_wfissues: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wpzi_wfknownfilelist: Data: 3.89MB + Index: 0.20MB + Engine MyISAM
wpzi_wflivetraffichuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzi_wflocs: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wpzi_wflogins: Data: 0.50MB + Index: 0.12MB + Engine MyISAM
wpzi_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzi_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wpzi_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpzi_wfnotifications: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzi_wfpendingissues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzi_wfreversecache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzi_wfsecurityevents: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzi_wfsnipcache: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpzi_wfstatus: Data: 0.13MB + Index: 0.06MB + Engine MyISAM
wpzi_wftrafficrates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzi_wfwaffailures: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpzi_wpml_mails: Data: 43.31MB + Index: 9.39MB + Engine MyISAM
wpzi_yoast_indexable: Data: 1.36MB + Index: 0.61MB + Engine InnoDB
wpzi_yoast_indexable_hierarchy: Data: 0.11MB + Index: 0.17MB + Engine InnoDB
wpzi_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpzi_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpzi_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 177
acf-field-group: 23
attachment: 1129
aw_workflow: 5
bqcg_video: 140
campaign: 2
cg_bird: 28
cg_bird_place: 65
cg_event: 70
cg_library: 1364
donation: 39
nav_menu_item: 170
oembed_cache: 69
page: 76
post: 12
product: 10
product_variation: 25
revision: 2103
shop_order: 784
shop_subscription: 1182

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (41) ###

Gravity Forms: by Gravity Forms – 2.7.13
Advanced Custom Fields: Gravity Forms Field: by @adam_pope of @stormuk – 1.1.0
ACF: Better Search: by Mateusz Gbiorczyk – 4.2.0
Flexible Content Preview for Advanced Custom Fields: by Jameel Moses – 1.0.6
Advanced Custom Fields: Font Awesome: by Matt Keys – 4.0.6
Advanced Custom Fields: Nav Menu Field: by Faison Zutavern – 2.0.0
Advanced Custom Fields PRO: by WP Engine – 6.2.1.1
AutomateWoo: by WooCommerce – 6.0.4
Style Guide: by Caleb Gittins – 1.0
Charitable: by Charitable Donations & Fundraising Team – 1.7.0.13
Classic Editor: by WordPress Contributors – 1.6.3
Admin Columns: by AdminColumns.com – 4.6.1
Custom Post Type UI: by WebDevStudios – 1.14.0
Display Environment Type: by Roy Tanck – 1.3.1
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
Enable Media Replace: by ShortPixel – 4.1.3
Extended User Search In WP-Admin: by Amit Mittal – 3
FacetWP - Flyout menu: by FacetWP
LLC – 0.8.1

FacetWP: by FacetWP
LLC – 4.2.5

GravityWP - CSS Selector: by GravityWP – 1.0.2
Import and export users and customers: by codection – 1.23.2
Imsanity: by Exactly WWW – 2.8.2
Lock User Account: by teknigar – 1.0.3
Mailchimp for WooCommerce: by Mailchimp – 3.2
Plugins Condition: by Katsushi Kawamori – 1.07
PublishPress Future: by PublishPress – 3.1.0
Redirection: by John Godley – 5.3.10
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Safe SVG: by 10up – 2.2.0
Simple Custom Post Order: by Colorlib – 2.5.6
UpdraftPlus - Backup/Restore: by UpdraftPlus.com
DavidAnderson – 1.23.10

User Switching: by John Blackbourn & contributors – 1.7.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.8.5
WooCommerce Name Your Price: by Kathy Darling – 3.5.6
WooCommerce PayPal Payments: by WooCommerce – 2.2.2
WooCommerce Subscriptions: by WooCommerce – 5.4.0
WooCommerce: by Automattic – 8.1.1
Wordfence Security: by Wordfence – 7.10.3
Yoast SEO: by Team Yoast – 21.1
WP Crontrol: by John Blackbourn & crontributors – 1.15.3
WP Mail Logging: by WP Mail Logging Team – 1.12.0

### Inactive Plugins (6) ###

Maintenance: by WebFactory Ltd – 4.08
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.1.0
WP All Export: by Soflyy – 1.3.9
WP All Import - ACF Add-On: by Soflyy – 3.3.7
WP All Import Pro: by Soflyy – 4.7.8
WP Migrate: by WP Engine – 2.6.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: grouped (grouped)
variable (variable)
external (external)
subscription (subscription)
variable subscription (variable-subscription)
simple (simple)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
exclude-from-search (exclude-from-search)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #859 - /shop/
Cart: #860 - /cart/
Checkout: #861 - /checkout/
My account: #862 - /my-account/
Terms and conditions: #32 - /legal-issues/

### Theme ###

Name: Birds Queensland
Version: 1.0
Author URL: http://www.calebgittins.com.au
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: birds-queensland/woocommerce/archive-product.php
birds-queensland/woocommerce/cart/mini-cart.php
birds-queensland/woocommerce/checkout/thankyou.php
birds-queensland/woocommerce/content-single-product.php
birds-queensland/woocommerce/emails/customer-new-account.php
birds-queensland/woocommerce/emails/email-footer.php
birds-queensland/woocommerce/emails/email-header.php
birds-queensland/woocommerce/emails/email-styles.php
birds-queensland/woocommerce/global/wrapper-end.php
birds-queensland/woocommerce/global/wrapper-start.php
birds-queensland/woocommerce/myaccount/dashboard.php
birds-queensland/woocommerce/myaccount/form-edit-account.php
birds-queensland/woocommerce/myaccount/form-login.php
birds-queensland/woocommerce/myaccount/navigation.php
birds-queensland/woocommerce/single-product/add-to-cart/variable.php
birds-queensland/woocommerce/single-product/short-description.php
birds-queensland/woocommerce/single-product/title.php
birds-queensland/woocommerce/single-product.php

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://birdsqueensland.org.au
Subscriptions-core Library Version: 6.2.0
Subscriptions Template Theme Overrides: birds-queensland/woocommerce/myaccount/view-subscription.php
Subscription Statuses: trash: 1
wc-active: 635
wc-cancelled: 19
wc-expired: 461
wc-on-hold: 63
wc-pending: 2
wc-pending-cancel: 1

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: Australia — Queensland

### Subscriptions by Payment Gateway ###

Direct bank transfer: trash: 1
wc-active: 204
wc-cancelled: 4
wc-on-hold: 17
wc-pending-cancel: 1

Cheque payments: wc-active: 49
wc-on-hold: 2

PayPal: wc-active: 226
wc-cancelled: 1
wc-expired: 3
wc-on-hold: 21
wc-pending: 2

### Payment Gateway Support ###

Direct bank transfer: products
PayPal: refunds
products
tokenization
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

Cheque payments: products

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: AU
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: ✔
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-09-17 20:52:51 +10:00
Options: ✔
Notes: 34
Onboarding: completed

### Action Scheduler ###

Canceled: 10
Oldest: 2023-08-21 21:58:04 +1000
Newest: 2023-09-17 13:27:48 +1000

Complete: 35,976
Oldest: 2023-08-17 16:08:32 +1000
Newest: 2023-09-17 16:05:54 +1000

Failed: 8
Oldest: 2023-02-25 23:15:53 +1000
Newest: 2023-08-28 09:55:25 +1000

Pending: 649
Oldest: 2023-09-17 16:07:54 +1000
Newest: 2026-09-07 18:16:45 +1000

### Name Your Price ###

Version: 
Database version: 
Template overrides: –

### Status report information ###

Generated at: 2023-09-17 16:06:06 +10:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by CameronD73** [comment] 2023-09-18 03:49
Update:
problem reproducible with "Storefront" theme.
Problem also manifests when a customer renews a current subscription.  The renewal process generates an order with empty customer details, and ID = 0.
Payment details are not captured

I have added a fake non-subscription product to a test site and the problem does not happen with non-subscription products - only an order that includes a subscription.

**Comment by jorgeatorres** [comment] 2023-09-18 09:00
Hi @CameronD73,

We were unable to reproduce this with WC 8.1.0 and Subscriptions 5.4.0, so we think we might be missing some details or there might be an environmental component affecting the output here.
You mentioned a test site, which I presume you can run with minimal plugins. Does this happen with only WooCommerce and Subscriptions active? Can you share screenshots of your subscription product settings? Which gateway are you using?* How is it configured?

I apologize if these questions seem obvious, but given we couldn't reproduce this ourselves, we need some more details to debug this further.


*From your SSR, we assumed PayPal Payments, which we used in testing, but would like to confirm)

**Comment by CameronD73** [comment] 2023-09-18 11:55
Hi @jorgeatorres 
Using  storeFront theme, I have stripped the test site down to WC, WC-subs, Paypal Payments 2.2.2 and it works (selecting BACS payment).
Add back in AutomateWoo 6.0.4 and it causes the problem.
My workflows there are based on events relating to subscription expiry, cancellation, not starting subscriptions.

**Comment by CameronD73** [comment] 2023-09-18 12:26
the product list export CSV file is [here](https://birdsqueensland.org.au/test/wc-product-export-18-9-2023-1695039141338.csv).
It is a single product with 5 variations.

**Comment by jorgeatorres** [comment] 2023-09-18 12:38
Hi @CameronD73!

Nice job figuring out AutomateWoo had something to do with the issue. We were able to replicate the problem now and are looking into a possible fix. I'll let you know as soon as I have something to report. Thanks for bringing this to our attention!

**Comment by CameronD73** [comment] 2023-09-20 12:30
I'm not sure if this is related or probably a separate bug.
I am stuck at the moment with posts being authoritative and noticed that the sync process is very patchy.
For example, yesterday I had several subscriptions renewed and the "_schedule_next_payment" date metadata is not updated.

`wp wc cot verify_cot_data`
shows 192 errors in 1981 orders.

On the other hand, things like updated email addresses when I was running HPOS as primary were never synced back to the posts tables.

So now I have no single authoritative set of data.

**Comment by jorgeatorres** [comment] 2023-09-21 11:31
Hi @CameronD73!

We have a fix for the AutomateWoo incompatibility (see #40282) which should be merged soon.
We've also discovered some metadata sync issues with Subscriptions (and other with address indexes), but we're still investigating. It'd be very helpful if you could open an issue about those, possibly with an extract of the output from `verify_cot_data`. We're mostly interested in the keys that are failing to sync properly.

Please let me know if that's something you can do. Thanks again for your report!

**Closed as completed** 2023-09-22 06:59 UTC
Labels: Bug, type: community contribution

**Comment by CameronD73** [comment] 2023-09-23 02:18
The changes in AutomateWoo v6.0.5 seem to have fixed this issue.
