### ISSUE TITLE
Payment Processing Errors: "The card has expired", "Instrument declined", and "Payer action required

### ISSUE THREAD

**Issue by premkumarbsetec** [woothemes/woocommerce#49198] opened 2024-07-05 13:54 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I am experiencing multiple payment processing errors in WooCommerce, which result in the order status changing from "Pending payment" to "Failed". The specific error messages are as follows:

    The card has expired:
        Error Message: The card has expired. Order status changed from Pending payment to Failed.
    Instrument declined:
        Error Message: Instrument declined. The instrument presented was either declined by the processor or bank, or it can’t be used for this payment. Order status changed from Pending payment to Failed.
    Payer action required, possibly overcharge:
        Error Message: Payer action required, possibly overcharge. Payer needs to perform the following action before proceeding with payment. Order status changed from Pending payment to Failed.

### Expected behavior

The payment should be processed successfully, and the order status should change to "Processing" or "Completed" instead of "Failed".

### Actual behavior

The payment should be processed successfully, and the order status should change to "Processing" or "Completed" instead of "Failed".

### Steps to reproduce

1. Add items to the cart.
2. Proceed to checkout.
3. Enter payment information.
4. place the order.

### WordPress Environment

WooCommerce version: 9.0.2
WordPress version: 6.4.3
Payment gateway:
WooCommerce PayPal Payments Version: 2.7.0

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by vbelolapotkov** [comment] 2024-07-09 12:20
Hey @premkumarbsetec, thanks for reporting this. What you describe are common payment failure reasons, and it's expected behavior to mark such orders as failed. E.g. you can read more about order failed status [here](https://woocommerce.com/document/managing-orders/order-statuses/) or read this blog article on [understanding and fixing failed orders](https://woocommerce.com/posts/understand-and-fix-failed-order-status-in-woocommerce/).

> I am experiencing multiple payment processing errors in WooCommerce

At the same time, I see you're mentioning multiple errors. How big is the amount of such failures? Has it changed recently? Asking because sometimes such observations may mean a fraudulent activity by a malicious actor on the store, e.g. when somebody is trying to test stolen card numbers.

**Comment by vbelolapotkov** [comment] 2024-07-17 09:37
I'm closing this one because the behavior described seems to be expected. @premkumarbsetec feel free to reopen if the issue is still relevant and there is more information about it.

**Closed as completed by vbelolapotkov** 2024-07-17 09:37 UTC
Labels: Bug, Payments, type: community contribution, Payments Engineering
