### ISSUE TITLE
Admin JS packages are not translated

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#32485] opened 2022-04-05 02:27 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

It seems JS packages are not translated by `@wordpress/i18n`. I think this affects all JS packages brought from WCAdmin.

Example:

Texts from Preset such as `Month to date` are from `@woocommerce/date` https://github.com/woocommerce/woocommerce/blob/8812feedaa20d778ee27877c4b8f987152172810/packages/js/date/src/index.js#L34-L44
<img src="https://user-images.githubusercontent.com/3747241/161666205-d98aad2b-ccdc-4eac-8e1e-e57e1b344202.png" width="400">

### Expected behavior

JS packages should translate

### Actual behavior

Does not translate

### Steps to reproduce

1. Change your WordPress language to another language
2. Update your translations in Dashboard > Updates to make sure language packs are downloaded
3. Go to Analytics > Overview
4. Click on date range and see texts are not translated

### WordPress Environment

WooCommerce version: |   | 6.4.0
-- | -- | --
WooCommerce REST API package: |   | 6.4.0 /var/www/html/wp-content/plugins/woocommerce/includes
WooCommerce Blocks package: |   | 7.2.0 /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/
Action Scheduler package: |   | 3.4.0 /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler
Log directory writable: |   | /var/www/html/wp-content/uploads/wc-logs/
WordPress version: |   | 5.9.2

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by ilyasfoo** [comment] 2022-04-05 02:29
It seems that by the time package is run, locale isn't fully loaded yet:

![image](https://user-images.githubusercontent.com/3747241/161667048-6e2769f7-a1ba-4954-b3b3-d5824b38df05.png)

This is when React client is rendering:

![image](https://user-images.githubusercontent.com/3747241/161667132-6a5e070f-4264-406d-872a-2c6d21200fb5.png)

To see it, simply put a `debugger` statement around `__()` function calls, go to that page with your browser console opened and run `wp.i18n.getLocaleData('woocommerce')` to get the list of all loaded translations available

**Comment by ObliviousHarmony** [comment] 2022-04-05 19:48
Perhaps it has something to do with the generation of the POT file? Previously, all of the JS was available in `packages/woocommerce-admin`. Now it's in `assets/client` so maybe we need to make a change here?

**Comment by ObliviousHarmony** [comment] 2022-04-08 21:43
I've spent some time looking at this issue and I want to share my findings. I knew very little about how WordPress i18n works when starting this so I went down a few rabbit holes.

- The strings are being found by `makepot` so we shouldn't see any problems with translations themselves.
- I compared the `date/index.js` file between `trunk` and `release/6.4` and found some notable differences:
  - The files are totally different
  - The unminification plugin is broken, both `index.min.js` and `index.js` are identical

My investigation brought me to [this pull request](https://github.com/woocommerce/woocommerce-admin/pull/8476), which seems likely to have been the cause of these differences. While I don't know for certain, I think that the differences introduced here are responsible for the problems with localization. I would like to dive deeper into understanding Webpack, but right now, it seems like there are others better suited to resolving this.

We should consider this a blocker for 6.5 and resolve the issue ASAP.

cc @rjchow since you landed the linked PR
cc @moon0326 because I poked you in Slack

**Closed as completed** 2022-04-14 09:03 UTC
Labels: Bug, package: @woocommerce/date
