### ISSUE TITLE
Order attribution for a customer with many orders, memory limit hits!

### ISSUE THREAD

**Issue by seldimi** [woothemes/woocommerce#44345] opened 2024-02-05 08:40 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When you try to load the order of a member that has many orders (eg. 25.000 orders ) it crashes. We have HPOS disabled at the moment

### Expected behavior

The expected behavior should render the order edit page and the users analytics to be held or cached for performance.

### Actual behavior

it breaks cause of memory limit, even if its 2GB
Switching off the order attribution, works perfectly and instant.

### Steps to reproduce

Make a user with 25.000 fake orders
Access one order on wp-admin

### WordPress Environment

wooocommmerce + wordpress latest with a user having 25.000 + orders 

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by shameemreza** [comment] 2024-02-07 15:28
Related to https://github.com/woocommerce/woocommerce/issues/43829

**Comment by seldimi** [comment] 2024-02-07 15:41
I'ts not related to the front-end and the JS, but the back-end and order edit page.

**Comment by loulemos** [comment] 2024-02-12 15:34
Can confirm it affects the Woocommerce order page backend, adds a significant delay when trying to access orders, switching order statuses and so on.

**Comment by seldimi** [comment] 2024-02-12 15:36
if you can make a faker and add about 2000 orders on a certain user id (registered, not guest) and try to load one order, you will notice the delay

**Comment by loulemos** [comment] 2024-02-12 15:38
We have close to 20 thousand orders and the delay is very noticeable, our logistics team has been complaining about it for a week or so and disabling the Order Attribution fixed things.

**Comment by Brianmitchtay** [comment] 2024-02-12 21:46
Seeing this cause orders to not be editable and causing PHP execution timeouts in 7730336-zd-a8c for a merchant with over 30k orders.

**Comment by loulemos** [comment] 2024-02-13 10:30
Would like to report that even with this feature disabled anything related to Woocommerce on the backend has a noticeable delay, from editing products to entering into orders. Seems like it's something related to the latest Woocommerce update outside of order attribution module as the rest of our backend feels as fast as it ever was.

Please see: https://github.com/woocommerce/woocommerce/issues/43829#issuecomment-1941175889

**Comment by layoutd** [comment] 2024-02-13 12:20
Thanks for the report and the followup comments. This pending change should address the sluggish backend with high order volume: https://github.com/woocommerce/woocommerce/pull/44318

It should be merged this week, and once confirmed we aim to patch release it with 8.6.x.

**Comment by loulemos** [comment] 2024-02-14 10:59
Hey @layoutd just wondering what's the reason for the slow woocommerce backoffice even when Order Attribution is off? We have 20 thousand orders, everything is as optimized as possible and I am 100% sure the backoffice slowdown only happens when interacting with the native woocommerce components like opening orders, editing products and so on.

**Comment by layoutd** [comment] 2024-02-14 11:17
Hi @loulemos, since yours appears to be an unrelated issue (this issue _does_ seem to be resolved by disabling Order Attribution), could you create a new issue or support request with more details? Did you notice the issue after updating to a specific WooCommerce version? Sharing your system report may help identify issues.

**Comment by Brianmitchtay** [comment] 2024-02-19 18:37
Seeing this come up again in 7763310-zd-a8c

**Comment by layoutd** [comment] 2024-02-20 14:54
If the store is on 8.6+ then Order Attribution will not likely be causing performance issues in the admin anymore. See #44318.

@seldimi, can you confirm whether 8.6.x addresses your issues?

**Comment by layoutd** [comment] 2024-03-08 10:33
Closing this issue as resolved with #44318 (released in WooCommerce 8.6). If there are any other similar reports or problems, we can address them in a new issue.

**Closed as completed by layoutd** 2024-03-08 10:33 UTC
Labels: Bug, Reports/Analytics, type: community contribution, Ventures
