### ISSUE TITLE
Analytics daterange picker

### ISSUE THREAD

**Issue by andyNuu** [woothemes/woocommerce#35694] opened 2022-11-23 15:28 UTC
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The styles for the date range picker under Analytics in the admin are missing.
![wc date range](https://user-images.githubusercontent.com/93152429/203584142-286cbec1-b2cd-4825-8d52-217b5e97a355.png)

### Expected behavior

To be able to select a date range in the Analytics part of the admin.

### Actual behavior

I cannot select a date range and the styling for the day select and the arrows seem to be missing.

### Steps to reproduce

1. select Analytics -> Orders
2. select date range
3. select custom

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://us.nuumobile.com
Site address (URL): https://us.nuumobile.com
WC Version: 7.0.1
REST API Version: ✔ 7.0.1
WC Blocks Version: ✔ 8.5.2
Action Scheduler Version: ✔ 3.5.2
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.25
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 10.3.37-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.1
WC Database Prefix: wp_
Total Database Size: 294.57MB
Database Data Size: 221.46MB
Database Index Size: 73.11MB
wp_woocommerce_sessions: Data: 3.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.42MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 6.52MB + Index: 6.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.16MB + Index: 0.20MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 3.02MB + Index: 2.92MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.02MB + Index: 1.48MB + Engine InnoDB
wp_aioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_posts: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wp_blc_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_blc_instances: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_blc_links: Data: 0.50MB + Index: 0.13MB + Engine InnoDB
wp_blc_synch: Data: 0.17MB + Index: 0.09MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 2.52MB + Index: 1.66MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frm_fields: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frm_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frm_items: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_frm_item_metas: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_imagify_files: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_imei: Data: 0.23MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 1.47MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.48MB + Index: 0.00MB + Engine InnoDB
wp_mo_openid_linked_user: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_action_meta: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_field_meta: Data: 1.48MB + Index: 0.00MB + Engine InnoDB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_form_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_upgrades: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_ninja_forms_uploads: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 12.28MB + Index: 2.16MB + Engine InnoDB
wp_postmeta: Data: 32.56MB + Index: 26.09MB + Engine InnoDB
wp_posts: Data: 16.09MB + Index: 3.52MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_social_users: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_taxjar_record_queue: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 19.34MB + Index: 15.97MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 1.03MB + Engine InnoDB
wp_user_registration_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 1.52MB + Index: 0.39MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.42MB + Index: 0.47MB + Engine InnoDB
wp_wc_order_stats: Data: 0.52MB + Index: 0.50MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblockediplog: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 2.30MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 21.55MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.02MB + Index: 0.20MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 10.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 1.02MB + Index: 0.17MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 1.02MB + Index: 0.09MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 60.56MB + Index: 0.00MB + Engine InnoDB
wp_wpr_rocket_cache: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 5.52MB + Index: 3.47MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.47MB + Index: 0.59MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 5.52MB + Index: 3.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 39
acf-field-group: 8
attachment: 1104
custom_css: 2
elementor_font: 8
elementor_library: 1
elementor-hf: 1
faq: 49
fgf_master_log: 167
fgf_rules: 2
frm_form_actions: 1
frm_styles: 1
is_search_form: 1
nav_menu_item: 93
nf_sub: 18809
oembed_cache: 10
page: 49
post: 98
product: 56
product_variation: 58
promo_ribbon: 3
revision: 61
shop_coupon: 18
shop_order: 5155
shop_order_refund: 326
sp_wp_carousel: 1
user_registration: 1
wp_block: 2
wp_global_styles: 2
wpcf7_contact_form: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

Advanced Custom Fields PRO: by WP Engine – 6.0.3
AfterShip Tracking - All-In-One WooCommerce Order Tracking (Free plan available): by AfterShip – 1.15.1
Auto Image Attributes From Filename With Bulk Updater: by Arun Basil Lal – 3.2
Broken Link Checker: by WPMU DEV – 1.11.19
Honeypot for Contact Form 7: by Nocean – 2.1.1
Contact Form 7: by Takayuki Miyoshi – 5.6.4
GTM4WP: by Thomas Geiger – 1.16.1
Facebook for WooCommerce: by Facebook – 2.6.28
GDPR: by Trew Knowledge – 2.1.2
Imagify: by Imagify - Optimize Images & Convert WebP – 2.0
Jetpack: by Automattic – 11.5.1
Klarna Checkout for WooCommerce: by Krokedil – 2.8.7
Klarna Order Management for WooCommerce: by klarna
krokedil – 1.7.0

Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 2.12.1

Mailchimp for WooCommerce: by Mailchimp – 2.7.6
Ninja Forms: by Saturday Drive – 3.6.14
Order Export & Order Import for WooCommerce: by WebToffee – 2.2.8
Quick Page/Post Redirect Plugin: by anadnet – 5.2.3
Really Simple SSL: by Really Simple Plugins – 6.0.5
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 4.1.5
User Role Editor: by Vladimir Garagulya – 4.63.1
Import Export WordPress Users and WooCommerce Customers: by WebToffee – 2.3.5
WooCommerce Anti Fraud: by OPMC Australia Pty Ltd – 4.7.1
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.3.3 (update to version 5.3.5 is available)
WooCommerce Stripe Gateway: by WooCommerce – 6.9.0
WooCommerce PayPal Payments: by WooCommerce – 1.9.5 (update to version 2.0.0 is available)
WooCommerce Shipment Tracking: by WooCommerce – 1.9.0
WooCommerce - ShipStation Integration: by WooCommerce – 4.3.1
WooCommerce: by Automattic – 7.0.1 (update to version 7.1.0 is available)
Wordfence Security: by Wordfence – 7.7.1
Yoast SEO: by Team Yoast – 19.9
WP Mail SMTP: by WPForms – 3.6.1
WP Migrate Lite: by Delicious Brains – 2.4.2
WP Rocket: by WP Media – 3.12.2.1
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.9.6

### Inactive Plugins (12) ###

AddToAny Share Buttons: by AddToAny – 1.8.5
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.8.0
Extend NUU Connection: by Andy Hastings – 1.0
Maintenance: by WebFactory Ltd – 4.06
NUU Checkout Tracker: by Andy Hastings – 1.0
Nuumobile Gutenberg Layout: by  – 2.0.0
Nuumobile Page Template: by  – 1.0.1
Promotional Ribbon: by Andy Hastings – 1.0
SheetDB: by SheetDB – 1.1.6
Verizon IMEI Tracking: by Andy Hastings – 1.0
WooCommerce Fraud Prevention Plugin: by theDotstore – 2.1.2
WordPress Importer: by wordpressdotorg – 0.8

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Must Use Plugins (1) ###

WP Migrate DB Compatibility: by Delicious Brains – 1.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #507 - /accessories/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #3 - /privacy-policy/

### Theme ###

Name: NUU Mobile 2022
Version: 1.0.0
Author URL: https://us.nuumobile.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: nuumobile2022/woocommerce/cart/cart-empty.php version 3.5.0 is out of date. The core version is 7.0.1
nuumobile2022/woocommerce/cart/cart-item-data.php
nuumobile2022/woocommerce/cart/cart-shipping.php
nuumobile2022/woocommerce/cart/cart-totals.php
nuumobile2022/woocommerce/cart/cart.php version 3.8.0 is out of date. The core version is 7.0.1
nuumobile2022/woocommerce/cart/cross-sells.php
nuumobile2022/woocommerce/cart/proceed-to-checkout-button.php version 2.4.0 is out of date. The core version is 7.0.1
nuumobile2022/woocommerce/cart/shipping-calculator.php version 4.0.0 is out of date. The core version is 7.0.1
nuumobile2022/woocommerce/checkout/cart-errors.php
nuumobile2022/woocommerce/checkout/form-billing.php
nuumobile2022/woocommerce/checkout/form-checkout.php
nuumobile2022/woocommerce/checkout/form-coupon.php version 3.4.4 is out of date. The core version is 7.0.1
nuumobile2022/woocommerce/checkout/form-login.php
nuumobile2022/woocommerce/checkout/form-shipping.php
nuumobile2022/woocommerce/checkout/order-receipt.php
nuumobile2022/woocommerce/checkout/payment-method.php
nuumobile2022/woocommerce/checkout/payment.php version 3.5.3 is out of date. The core version is 7.0.1
nuumobile2022/woocommerce/checkout/review-order.php
nuumobile2022/woocommerce/checkout/terms.php
nuumobile2022/woocommerce/checkout/thankyou.php
nuumobile2022/woocommerce/single-product/add-to-cart/variable.php
nuumobile2022/woocommerce/single-product/short-description.php
nuumobile2022/woocommerce/single-product/title.php

Outdated Templates: ❌
					
					
						Learn how to update

### Klarna Checkout Request Log ###

No KCO errors: 

### Klarna Payments Request Log ###

2022-11-10 17:27:39: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-10 17:27:37: KP Update Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-10 13:07:31: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-10 13:07:29: KP Update Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-10 11:51:59: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-10 11:51:59: KP Update Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-10 06:47:14: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-10 06:46:59: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-10 06:46:58: KP Update Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-09 21:52:25: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-09 21:52:25: KP Update Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-09 20:27:30: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-09 20:27:28: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-09 20:25:03: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-11-09 20:24:59: KP Create Session
Response code: 401
Response message: {"headers":[],"body":"<html><head><title>401 Authorization Required<\/title><\/head><body><center><h1>401 Authorization Required<\/h1><\/center><\/body><\/html>","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

### Klarna Countries ###

Production Countries: US
Test Countries: US

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-24 03:29:17 -06:00
Options: ✔
Notes: 25
Onboarding: completed

### WooCommerce Customer/Order/Coupon Export ###

Automated exports: 0
Custom formats: 0
Next export: Not scheduled

### Action Scheduler ###

Canceled: 2
Oldest: 2022-11-06 15:37:08 -0600
Newest: 2022-11-17 00:37:52 -0600

Complete: 7,210
Oldest: 2022-10-23 20:28:29 -0500
Newest: 2022-11-23 09:27:14 -0600

Failed: 11
Oldest: 2022-01-04 09:00:00 -0600
Newest: 2022-09-19 20:40:22 -0500

Pending: 5
Oldest: 2022-11-23 09:36:05 -0600
Newest: 2022-11-24 09:11:23 -0600

### Status report information ###

Generated at: 2022-11-23 09:28:06 -06:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment] 2022-11-24 11:58
Hi @andyNuu,
Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the  WooCommerce 7.1.0 version and WordPress 6.1.1 version. 

Please find below the screenshot for reference :
![#35694](https://user-images.githubusercontent.com/94531721/203715649-aac77b66-8fcf-4124-8a00-04e11e69bc3d.jpg)

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by kaushikasomaiya** [comment] 2022-11-27 06:57
Closing as duplicate of #35470

**Closed as completed by kaushikasomaiya** 2022-11-27 06:57 UTC
Labels: Bug, status: reproduction, plugin: woocommerce, Reports/Analytics, type: community contribution
