### ISSUE TITLE
[Enhancement]: Less E_ERROR messages

### ISSUE THREAD

**Issue by paaljoachim** [woothemes/woocommerce#53684] opened 2024-12-13 01:51 UTC
### Describe the solution you'd like

Hey

I have lately been experiencing a lot of E_ERROR messages coming from WooCommerce.
Here is one example.

WordPress-versjon 6.7.1
Aktivt tema: X – Child Theme (versjon 1.0.0)
Nåværende utvidelse: WooCommerce (versjon 9.4.3)
PHP-versjon 8.1.31

En feil av typen E_ERROR ble forårsaket i linje 260 i filen /customers/4/4/f/cwkbhqsni/webroots/r1330104/wp-content/plugins/woocommerce/src/Packages.php. Feilmelding: Uncaught Error: Call to a member function get_column_count() on null in /customers/4/4/f/cwkbhqsni/webroots/r1330104/wp-content/plugins/woocommerce/src/Packages.php:260
Stack trace:
#0 /customers/4/4/f/cwkbhqsni/webroots/r1330104/wp-includes/class-wp-hook.php(326): Automattic\WooCommerce\Packages::display_notice_for_merged_plugins('koko-analytics/...')
#1 /customers/4/4/f/cwkbhqsni/webroots/r1330104/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#2 /customers/4/4/f/cwkbhqsni/webroots/r1330104/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /customers/4/4/f/cwkbhqsni/webroots/r1330104/wp-admin/includes/class-wp-plugins-list-table.php(1491): do_action('after_plugin_ro...', 'koko-analytics/...', Array, 'all')
#4 /customers/4/4/f/cwkbhqsni/webroots/r1330104/wp-content/plugins/glow/includes/class-glow-worker-wordpress.php(154): WP_Plugins_List_Table->single_row(Array)
#5 /customers/4/4/f/cwkbhqsni/webroots/r1330104/wp-content/plugins/glow/glow-worker.php(346): Glow_Worker_Wordpress->getPlugins()
#6 /customers/4/4/f/cwkbhqsni/webroots/r1330104/wp-content/plugins/glow/glow-worker.php(1138): getPlugins()
#7 /customers/4/4/f/cwkbhqsni/webroots/r1330104/wp-includes/class-wp-hook.php(322): checkPluginsThemesCore()
#8 /customers/4/4/f/cwkbhqsni/webroots/r1330104/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#9 /customers/4/4/f/cwkbhqsni/webroots/r1330104/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#10 /customers/4/4/f/cwkbhqsni/webroots/r1330104/wp-cron.php(191): do_action_ref_array('glow_backup_hoo...', Array)
#11 {main}
  thrown

Another site:

En feil av typen E_ERROR ble forårsaket i linje 260 i filen /customers/0/6/f/cw1v32epv/webroots/r1131363/wp-content/plugins/woocommerce/src/Packages.php. Feilmelding: Uncaught Error: Call to a member function get_column_count() on null in /customers/0/6/f/cw1v32epv/webroots/r1131363/wp-content/plugins/woocommerce/src/Packages.php:260
Stack trace:
#0 /customers/0/6/f/cw1v32epv/webroots/r1131363/wp-includes/class-wp-hook.php(326): Automattic\WooCommerce\Packages::display_notice_for_merged_plugins('block-visibilit...')
#1 /customers/0/6/f/cw1v32epv/webroots/r1131363/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#2 /customers/0/6/f/cw1v32epv/webroots/r1131363/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /customers/0/6/f/cw1v32epv/webroots/r1131363/wp-admin/includes/class-wp-plugins-list-table.php(1491): do_action('after_plugin_ro...', 'block-visibilit...', Array, 'all')
#4 /customers/0/6/f/cw1v32epv/webroots/r1131363/wp-content/plugins/glow/includes/class-glow-worker-wordpress.php(154): WP_Plugins_List_Table->single_row(Array)
#5 /customers/0/6/f/cw1v32epv/webroots/r1131363/wp-content/plugins/glow/glow-worker.php(346): Glow_Worker_Wordpress->getPlugins()
#6 /customers/0/6/f/cw1v32epv/webroots/r1131363/wp-content/plugins/glow/glow-worker.php(1138): getPlugins()
#7 /customers/0/6/f/cw1v32epv/webroots/r1131363/wp-includes/class-wp-hook.php(322): checkPluginsThemesCore()
#8 /customers/0/6/f/cw1v32epv/webroots/r1131363/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#9 /customers/0/6/f/cw1v32epv/webroots/r1131363/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#10 /customers/0/6/f/cw1v32epv/webroots/r1131363/wp-cron.php(191): do_action_ref_array('glow_backup_hoo...', Array)
#11 {main}
  thrown

### Describe alternatives you've considered

Just deleting the email after having checked that the site is still working.

### Additional context

I am getting too many emails that show an E_ERROR message.

**Comment by barryhughes** [comment] 2024-12-16 22:35
Hi! This seems like a duplicate of https://github.com/woocommerce/woocommerce/issues/53057, which was solved in https://github.com/woocommerce/woocommerce/pull/53438. I'd recommend holding tight until 9.5.1 is released, which *should* be tomorrow or the next day.

**Closed as completed by barryhughes** 2024-12-16 22:35 UTC
Labels: Enhancement, type: community contribution

**Comment by paaljoachim** [comment] 2024-12-16 22:45
Great. Thanks Barry @barryhughes
