### ISSUE TITLE
[Fatal] Uncaught ValueError: Path cannot be empty in /includes/wc-template-functions.php:53

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#51818] opened 2024-10-01 17:17 UTC
## Describe the bug

We observed the following fatal error in relation to WooCommerce 9.3.3:

[Link to code](https://github.com/woocommerce/woocommerce/blob/516b55b734afa4e87821627bfa63a1964e919864/plugins/woocommerce/includes/wc-template-functions.php#L53)

<details><summary>Stack trace</summary>
```
Stack trace:
#0 /../../../wp-includes/class-wp-hook.php(324): wc_template_redirect('')
#1 /../../../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#2 /../../../wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /../../../wp-includes/template-loader.php(13): do_action('template_redire...')
#4 /../../../wp-blog-header.php(19): require_once('/wordpress/core...')
#5 /../../../index.php(17): require('/wordpress/core...')
#6 {main}
  thrown in /../../woocommerce/9.3.3/includes/wc-template-functions.php on line 53
```
</details>

## Expected behavior
No fatal thrown

## Actual behavior
Fatal error thrown

## Steps to reproduce
We don't have steps to reproduce, but observed 664 instances of this problem on Fri Sep 27, 1200 UTC to 2359 UTC on one site. Hopefully, someone can dig in and apply a defensive check if appropriate. - To be updated after investigation.

## WordPress Environment
N/A

**Comment by barryhughes** [comment] 2024-10-02 13:49
I believe this is a duplicate of https://github.com/woocommerce/woocommerce/issues/51304, but def re-open if I'm mistaken.

**Closed as completed by barryhughes** 2024-10-02 13:49 UTC
Labels: Bug, Blocks/Patterns/Templates, type: fatal, env: internal
