### ISSUE TITLE
Analytics Custom Date Range

### ISSUE THREAD

**Issue by ValueErr** [woothemes/woocommerce#35509] opened 2022-11-07 15:41 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On a fresh install of WooCommerce, the Select a Custom Date Range function within the analytics section is bugged as the buttons to go a month forwards or backwards are too big.

### Expected behavior

Ability to utilise the Select a Custom Date Range function without any visual bugs

### Actual behavior

Unable to properly use the Select a Custom Date Range function due to the bugged out buttons.

### Steps to reproduce

1. Set up a blank site
2. Install fresh install of WooCommerce
3. Open up the Analytics section from the side menu
4. Attempt to set a **Custom Date Range** using the **Date Range** dropdown

### WordPress Environment

```
### WordPress Environment ###

WordPress address (URL): http://localhost:10058
Site address (URL): http://localhost:10058
WC Version: 7.0.1
REST API Version: ✔ 7.0.1
WC Blocks Version: ✔ 8.5.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.4.1
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.4
WC Database Prefix: wp_
Total Database Size: 4.86MB
Database Data Size: 3.40MB
Database Index Size: 1.46MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.50MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.0.1

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-08 15:28:39 +00:00
Options: ✔
Notes: 36
Onboarding: skipped

### Action Scheduler ###

Complete: 5
Oldest: 2022-11-07 15:28:41 +0000
Newest: 2022-11-07 15:40:38 +0000

Pending: 5
Oldest: 2022-11-07 15:40:45 +0000
Newest: 2022-11-08 15:28:41 +0000


### Status report information ###

Generated at: 2022-11-07 15:41:12 +00:00

```

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by cena** [comment] 2022-11-07 18:54
Also reported in 5690274-zen.

On my test site, the custom picker looks like this and the calendar icons don't work.  You can manually enter dates.


![SCR-20221107-hw5](https://user-images.githubusercontent.com/19334/200391364-2d3b6176-9e4d-4d30-a7df-52cc331d0941.png)


---

Manually inputting custom dates and clicking on Filter seems to work, however:

![SCR-20221107-htf](https://user-images.githubusercontent.com/19334/200391106-be4921fb-cc82-477b-9d86-2b746206a5a2.png)

--
WP 6.1
WC 7.0
Storefront

**Comment by ericfri** [comment] 2022-11-07 19:12
5691601-zen

**Comment by cena** [comment] 2022-11-07 20:04
5691148-zen

**Comment by ValueErr** [comment] 2022-11-08 09:11
> Also reported in 5690274-zen.
> 
> On my test site, the custom picker looks like this and the calendar icons don't work. You can manually enter dates.
> 
> ![SCR-20221107-hw5](https://user-images.githubusercontent.com/19334/200391364-2d3b6176-9e4d-4d30-a7df-52cc331d0941.png)
> 
> Manually inputting custom dates and clicking on Filter seems to work, however:
> 
> ![SCR-20221107-htf](https://user-images.githubusercontent.com/19334/200391106-be4921fb-cc82-477b-9d86-2b746206a5a2.png)
> 
> -- WP 6.1 WC 7.0 Storefront

I can confirm this is exactly what I am experiencing.

**Comment by swatipawarGS** [comment] 2022-11-08 13:20
Hi @ValueErr,
Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the  WooCommerce 7.0.1 version and WordPress 6.1 version. 

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/200497716-7d24949d-dc4d-48d5-9cfe-040a59787ed1.mp4


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by sf-steve** [comment] 2022-11-08 18:05
Can also confirm on live sites with versions 7.0.1, 6.5.1 & 6.6.1, the later 2 not having been updated, and not (as far as we can tell) having had this issue previously. Perhaps related to something external (wordpress core?)

**Comment by thisissandip** [comment] 2022-11-09 05:35
Also reported in: https://wordpress.org/support/topic/analytics-error-3/#post-16179818

**Comment by j111q** [comment] 2022-11-09 06:07
Just adding that this bug was also reported to the Woo Design team internally; thanks @ValueErr for submitting this issue and @swatipawarGS for investigating! 🙏

**Comment by anastas10s-afk** [comment] 2022-11-09 17:31
Also reported here: https://wordpress.org/support/topic/wc-analytic-custom-report-issue/

Screenshot from a test installation of mine, where I can reproduce it: https://snipboard.io/RKuqab.jpg

**Comment by Babylon1999** [comment] 2022-11-12 13:42
One more here:

zd-5699223

https://wordpress.org/support/topic/analytics-pages-blank-after-update-to-7-1-0/

**Comment by nicdwilson** [comment] 2022-11-14 03:20
zd-5704552

**Comment by imodouglas** [comment] 2022-11-14 10:29
38014571-hc

**Comment by ryanr14** [comment] 2022-11-14 15:25
5668444-zen

**Comment by anastas10s-afk** [comment] 2022-11-14 21:38
5703560-zen

**Comment by kaushikasomaiya** [comment] 2022-11-15 07:08
Note that this is also being followed here #35470 and a temporary fix might be rolled out soon.

**Comment by imodouglas** [comment] 2022-11-15 07:16
> Note that this is also being followed here #35470 and a temporary fix might be rolled out soon.

In addition to this, a CSS walkaround has been given [here](https://github.com/woocommerce/woocommerce/issues/35470#issuecomment-1308852769)

**Comment by ValueErr** [comment] 2022-11-15 09:48
> > Note that this is also being followed here #35470 and a temporary fix might be rolled out soon.
> 
> In addition to this, a CSS walkaround has been given [here](https://github.com/woocommerce/woocommerce/issues/35470#issuecomment-1308852769)

I can confirm this temporary CSS workaround works for the time being

**Comment by felipevelzani** [comment] 2022-11-15 19:36
Closing as duplicated — please see #35470.

**Closed as completed by felipevelzani** 2022-11-15 19:36 UTC
Labels: Bug, status: reproduction, plugin: woocommerce, type: community contribution
