### ISSUE TITLE
[HPOS] get orders throwing fatal error : Uncaught WC_Data_Exception

### ISSUE THREAD

**Issue by iamsathyaseelan** [woothemes/woocommerce#35613] opened 2022-11-17 10:23 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

While fetching multiple orders using the **_wc_get_orders_** function throws a **Fatal error**: Uncaught WC_Data_Exception: Invalid parent ID in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php:880

### Expected behavior

It should return the list of orders based on the given arguments.

### Actual behavior

I is throwing an error.

`Fatal error: Uncaught WC_Data_Exception: Invalid parent ID in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php:880 

Stack trace: 

#0 /Applications/MAMP/htdocs/wordpress/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(574): WC_Data->error('order_invalid_p...', 'Invalid parent ...') 

#1 /Applications/MAMP/htdocs/wordpress/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(1289): WC_Abstract_Order->set_parent_id('920') 

#2 /Applications/MAMP/htdocs/wordpress/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(1272): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore->set_order_prop(Object(Automattic\WooCommerce\Admin\Overrides\OrderRefund), 'parent_id', '920') 

#3 /Applications/MAMP/htdocs/wordpress/wp-content/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php(1030): Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStor in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php on line 880`

### Steps to reproduce

1. Place a new order on the storefront.
2. Provide a full refund for the newly placed order.
3. Delete the refunded order.
4. Try to get all orders using the `wc_get_orders` function.
5. Now you can see the fatal error.

**Note:** argument for the `wc_get_orders` function should be like the below example.

`
function issue_get_orders() {
	$query_args = array(
		'post_type'      => array( 'shop_order', 'shop_order_refund', 'shop_subscription' ),
		'post_status'    => array_keys( wc_get_order_statuses() ),
		'posts_per_page' => 500,
		'paged'          => false,
		'offset'         => 0,
		'order'          => 'ASC',
		'orderby'        => 'ID',
		'date_query'     => array(
			'relation' => 'AND',
			array(
				'column' => 'date_updated_gmt',
				'after'  => '2022-11-01 00:00:01',
				'before' => '2022-11-18 00:00:01',
			),
		),
	);
	$orders = wc_get_orders( $query_args );
}

add_action( 'wp_footer', 'issue_get_orders' );
`

[Here is the video](https://drive.google.com/file/d/1lYnjLlENPkH9dJ1whb0-6-8geX-k4SKJ/view?usp=sharing) to reproduce the issue.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost:8888/wordpress
Site address (URL): http://localhost:8888/wordpress
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2u PHP/7.4.21 mod_wsgi/3.5 Python/2.7.18 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.30.1
PHP Version: 7.4.21
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.7.34
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: wp_
Total Database Size: 28.56MB
Database Data Size: 20.66MB
Database Index Size: 7.90MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
bounce_emails_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chapters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chapter_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
couplet: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
section: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_afwc_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_commission_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_hits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_afwc_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_applicant_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bounced_email_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_dd_analytics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dd_workflows: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dpad_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dpad_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_eddpc_subscription: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_edd_adjustmentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_adjustments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_edd_customermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_edd_customer_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_edd_customer_email_addresses: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_edd_logmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_logs: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_edd_logs_api_requestmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_logs_api_requests: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_logs_file_downloadmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_logs_file_downloads: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_edd_notemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_notes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_edd_notifications: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_edd_ordermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_edd_order_addresses: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_edd_order_adjustmentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_order_adjustments: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_edd_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_edd_order_transactions: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_edd_subscriptions: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_email_customizer_plus_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fc_campaign_emails: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_fc_campaign_url_metrics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fc_funnels: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_funnel_metrics: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_funnel_sequences: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_funnel_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fc_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_subscribers: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_fc_subscriber_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_subscriber_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_subscriber_pivot: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_fc_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fc_url_stores: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_hustle_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_hustle_entries_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_hustle_modules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_hustle_modules_meta: Data: 0.17MB + Index: 0.03MB + Engine InnoDB
wp_hustle_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_icegram_tracking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_actions: Data: 0.09MB + Index: 0.22MB + Engine InnoDB
wp_ig_blocked_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_campaigns: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_ig_contactmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ig_contacts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_ig_contacts_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ig_contact_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ig_custom_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_ig_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_lists_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ig_mailing_queue: Data: 0.19MB + Index: 0.02MB + Engine InnoDB
wp_ig_queue: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_ig_sending_queue: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_ig_temp_import: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_unsubscribe_feedback: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_wc_cart: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_ig_wc_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_ig_workflows: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_workflows_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lhr_log: Data: 2.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailster_actions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailster_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailster_forms_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailster_form_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailster_links: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailster_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailster_lists_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailster_queue: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailster_subscribers: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailster_subscriber_fields: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailster_subscriber_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mail_catcher_logs: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
wp_newsletter: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_emails: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_newsletter_sent: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_stats: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_newsletter_user_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 7.03MB + Index: 0.11MB + Engine InnoDB
wp_pimwick_gift_card: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_pimwick_gift_card_activity: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_postmeta: Data: 1.41MB + Index: 0.30MB + Engine InnoDB
wp_posts: Data: 1.34MB + Index: 0.13MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tutor_earnings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tutor_quiz_attempts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tutor_quiz_attempt_answers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tutor_quiz_questions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tutor_quiz_question_answers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_tutor_withdraws: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_um_metadata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wf_sn_tests: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 63
aw_workflow: 6
download: 4
edd_discount: 2
edd_log: 10
edd_payment: 9
elementor_library: 1
es_template: 4
ig_campaign: 3
ig_message: 6
lesson: 1
mailpoet_page: 1
mt_pp: 1
newsletter: 1
oembed_cache: 3
order_status: 1
page: 29
popup: 1
popup_theme: 8
post: 5
postman_sent_mail: 30
product: 21
product_variation: 11
revision: 309
shop_coupon: 9
shop_order: 41
shop_order_refund: 11
shop_subscription: 7
topics: 1
tutor_quiz: 1
um_directory: 1
um_form: 3
wp_global_styles: 1
wpcode: 2
yaymail_template: 11

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.1.0

### Inactive Plugins (38) ###

Affiliate For WooCommerce: by StoreApps – 4.12.0
AutomateWoo: by WooCommerce – 5.4.1
Backup Migration: by Migrate – 1.2.2
Code Snippets: by Code Snippets Pro – 3.2.1
Custom Order Status Manager for WooCommerce: by Bright Plugins – 0.10
Discount Deals - Dynamic product pricing and discount rules: by Discount Deals – 1.0.0
Easy Digital Downloads: by Easy Digital Downloads – 3.1.0.1.1
Easy Digital Downloads - Recurring Payments: by Easy Digital Downloads – 2.11.7
Easy Digital Downloads Putler Connector: by putler
storeapps – 3.0.0

Elementor: by Elementor.com – 3.7.8
Elementor Pro: by Elementor.com – 3.4.1
Email Subscribers & Newsletters: by Icegram – 5.4.7
Es Using Multiple Esp: by Sathyaseelan – 1.0
Job application form: by Sathyaseelan – 1.0.0
Mail logging - WP Mail Catcher: by James Ward – 2.0.5
One User Avatar: by One Designs – 2.3.9
Post SMTP: by Post SMTP – 2.1.10
PW WooCommerce BOGO Free: by Pimwick
LLC – 2.39

Test Project: by sathyaseelan – 1.0.0
Theme Customisations: by WooThemes – 1.0.0
Tutor LMS: by Themeum – 2.1.1
Ultimate Member: by Ultimate Member – 2.5.1
User Profile Picture: by Cozmoslabs – 2.6.0
WooCommerce Beta Tester: by WooCommerce – 2.1.0
WooCommerce Cash On Pickup: by Marian Kadanka – 1.6.1
WooCommerce Email Customizer Plus: by Flycart – 1.2.7
WooCommerce PayPal Payments: by WooCommerce – 1.9.4 (update to version 1.9.5 is available)
WooCommerce Putler Connector - Accurate Analytics and Reports for your WooCommerce Store: by putler
storeapps – 2.10.0

WooCommerce Putler Connector - Accurate Analytics and Reports for your WooCommerce Store: by putler
storeapps – 3.0.0

WooCommerce Stripe Gateway: by WooCommerce – 7.0.1
WooCommerce Subscriptions: by WooCommerce – 3.1.6
Woo Discount Rules: by Flycart – 2.4.5
Woo Discount Rules PRO 2.0: by Flycart – 2.4.1
Workflow Automation: by sathyaseelan – 1.0
WPC Composite Products for WooCommerce: by WPClever – 5.4.0
WPCode - Insert Headers, Footers, and Code Snippets: by WPCode – 2.0.3
WP Crontrol: by John Blackbourn & crontributors – 1.14.0
WP Mail SMTP: by WPForms – 3.6.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #6 - /
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.0 (update to version 4.2.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-18 05:36:12 +05:30
Options: ✔
Notes: 111
Onboarding: completed

### Action Scheduler ###

Complete: 150
Oldest: 2022-10-20 05:07:12 +0000
Newest: 2022-11-17 10:18:21 +0000

Pending: 2
Oldest: 2022-11-17 10:23:39 +0000
Newest: 2022-11-18 04:42:18 +0000

Failed: 3
Oldest: 2022-06-27 04:53:17 +0000
Newest: 2022-11-17 04:42:18 +0000

### Status report information ###

Generated at: 2022-11-17 15:52:57 +05:30
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by vedanshujain** [comment] 2022-12-21 10:36
Hey @iamsathyaseelan , looks like this is happening because the parent ID that order is referring to does not exist. Which is why its not able to set an ID, can you confirm if an order with ID `920` exist in your database?

**Comment by vedanshujain** [comment] 2023-01-04 08:17
Closing this in favor of #35909 , root cause is being addressed there.

**Closed as completed by vedanshujain** 2023-01-04 08:17 UTC
Labels: Bug, status: developer reproduction, type: community contribution
