### ISSUE TITLE
WCPay menu item experiment: next steps

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32219] opened 2021-11-12 11:42 UTC
**Description:** we want to expand the experiment implemented in [#686](https://github.com/Automattic/wc-calypso-bridge/issues/686) and [#744](https://github.com/automattic/wc-calypso-bridge/issues/744)
More info here: p1634651781002000-slack-C01LPBCV4J1/

**Acceptance criteria:**

- [ ] Reuse the same flow implemented in https://github.com/automattic/wc-calypso-bridge/issues/744
- [ ] exclude new users and users who already have the extension installed
- [ ] We want to start with a small subset of US stores (10%). Using ExPlat seems to be the best approach to segment the two experiences

**Event tracking:** 
It was challenging to find a way to track when the user viewed the menu item. It would be helpful to explore if it's possible to track this in this experiment accurately.
Maybe we can get this through ExPlat without creating new Tracks. We can use an event like `wcadmin_page_view` as the exposure event and then ExPlat automatically shows the variant with the menu item to X number of people 🤔

**Comment by pmcpinto** [comment] 2021-11-12 11:42
cc @adrianduffell @becdetat

**Comment by pmcpinto** [comment] 2021-11-16 10:46
@adrianduffell can you let me know when you have news about the effort required to implement this? Thanks

**Comment by adrianduffell** [comment] 2021-11-17 11:14
@pmcpinto We estimate 8 story points (about 25% of our normal capacity per cycle). It's something we could target for the Woo Admin 3.1 release, with Inbox 2.0 our main priority ahead of the upcoming 3.0 beta.

**Comment by pmcpinto** [comment] 2021-11-17 11:44
> @pmcpinto We estimate 8 story points (about 25% of our normal capacity per cycle). It's something we could target for the Woo Admin 3.1 release, with Inbox 2.0 our main priority ahead of the upcoming 3.0 beta.

Thanks for sharing the estimate. @thenbrent is everything goes as planned we'll release the experiment in WC 6.2 (February). Does this timing sound good to you?

**Comment by thenbrent** [comment] 2021-11-22 06:30
@pmcpinto is WC 6.2 being released February 8? (I couldn't see on Proton's P2 sidebar, because it only goes to January). If the 8th, that will be fine. The goal is to have the WC Pay in core plans finalized by 2022-02-28, and the results of this are an important contributor to that so we want to get 1-2 weeks data on it before finalizing those plans.

**Comment by pmcpinto** [comment] 2021-11-22 11:39
> @pmcpinto is WC 6.2 being released February 8?

Yes

**Comment by moon0326** [comment] 2021-12-14 02:48
Hey @pmcpinto ✋ 

> It was challenging to find a way to track when the user viewed the menu item. It would be helpful to explore if it's possible to track this in this experiment accurately.

As far as I know, we're already tracking the page view with `page_view` track. Could you share with us what was challenging? Is this because the name is not unique?

**Comment by pmcpinto** [comment] 2021-12-14 15:02
> As far as I know, we're already tracking the page view with page_view track. Could you share with us what was challenging? Is this because the name is not unique?

@moon0326 in the previous experiments we assumed that everyone in the eCommerce plan that fired a wc-admin pageview saw the WCPay red badge. And this wasn't 100% accurate as we weren't tracking the red badge views or something similar. But as I mentioned in the description, maybe we can get this through ExPlat without creating new Tracks. We can use an event like wcadmin_page_view as the exposure event and then ExPlat automatically shows the variant with the menu item to X number of people

**Comment by moon0326** [comment] 2021-12-15 19:23
> > As far as I know, we're already tracking the page view with page_view track. Could you share with us what was challenging? Is this because the name is not unique?
> 
> @moon0326 in the previous experiments we assumed that everyone in the eCommerce plan that fired a wc-admin pageview saw the WCPay red badge. And this wasn't 100% accurate as we weren't tracking the red badge views or something similar. But as I mentioned in the description, maybe we can get this through ExPlat without creating new Tracks. We can use an event like wcadmin_page_view as the exposure event and then ExPlat automatically shows the variant with the menu item to X number of people

Thank you for the explanation 👍 

Please correct me if I'm wrong since I'm not very experienced with `exposure event` concept yet, but it sounds like users must be assigned to an experiment first according to this [field guide](https://github.com/Automattic/experimentation-platform/wiki/Experimenter%27s-Guide#what-is-an-exposure-event-and-when-do-i-need-it). 

>  If you add an exposure event, metrics are then only calculated for users that were assigned an experiment variation and triggered the exposure event

I think we still can't track if the assigned users saw the WCPay red badge or not accurately since they might not click the menu after all. 

What do you think about adding an event when the users hover over the menu? I can look into it if it's doable.

**Comment by adrianduffell** [comment] 2021-12-17 13:20
> It's something we could target for the Woo Admin 3.1 release

> The goal is to have the WC Pay in core plans finalized by 2022-02-28, and the results of this are an important contributor to that so we want to get 1-2 weeks data on it before finalizing those plans.

Our re-aligned development cycles for EOY causes us some bother here. Assuming that having the data by 2022-02-28 is a hard requirement, we'll need to cherry-pick this work in after the 3.1 code freeze. cc @moon0326 @ilyasfoo

**Comment by pmcpinto** [comment] 2021-12-29 10:50
@moon0326 @ilyasfoo sorry, I missed this [comment](woocommerce/woocommerce#32219).

> Please correct me if I'm wrong since I'm not very experienced with exposure event concept yet, but it sounds like users must be assigned to an experiment first according to this field guide.

Mmm, you're right.

> I think we still can't track if the assigned users saw the WCPay red badge or not accurately since they might not click the menu after all.

Payments is a [top-level menu item](https://d.pr/i/bFNWEv), so users will see the red badge without hovering over the menu, right? 

If we use Abacus and assign 10% of US stores to the treatment version, I think we will know automatically the users that are exposed to the experiment. The main drawback is that in the future we can exclude this cohort from similar experiments 🤔 
Also, how do we ensure that new users and users who already have the extension installed or a wcpay account are not exposed to the experiment?

**Comment by ilyasfoo** [comment] 2021-12-30 03:51
> Payments is a top-level menu item, so users will see the red badge without hovering over the menu, right?

Yes


> If we use Abacus and assign 10% of US stores to the treatment version, I think we will know automatically the users that are exposed to the experiment. The main drawback is that in the future we can exclude this cohort from similar experiments 🤔

I have a suggestion for using a site option to "tag" the exposed users [here](https://github.com/woocommerce/woocommerce-admin/issues/8070#issuecomment-1002860654)

>Also, how do we ensure that new users and users who already have the extension installed or a wcpay account are not exposed to the experiment?

This is a good point, we can bake in logic to ensure that users who have the extension installed are not exposed. We can detect if they have a wcpay account if they have already set up wcpay on their site.

**Comment by pmcpinto** [comment] 2021-12-30 11:39
> we can bake in logic to ensure that users who have the extension installed are not exposed. We can detect if they have a wcpay account if they have already set up wcpay on their site.

Great!

> I have a suggestion for using a site option to "tag" the exposed users here

@ilyasfoo that can be a good workaround, even if it's not scalable. What if we approach this from a different angle and target 100% of users located in a smaller country? For example, NZ and IE. That would simplify the implementation and mitigate some risks, right?

**Comment by ilyasfoo** [comment] 2021-12-31 05:09
>What if we approach this from a different angle and target 100% of users located in a smaller country? For example, NZ and IE. That would simplify the implementation and mitigate some risks, right?

That sounds good as well. To implement, we'll just have to add a custom segment in WPCOM to apply the `woo_store_country` check similar to the tasklist experiment for US, CA, & AU. If you confirm to go this route, let us know the list of countries to apply to & the experiment names.

**Comment by pmcpinto** [comment] 2022-01-03 10:58
@ilyasfoo when do you need the final answer regarding this change?

**Comment by ilyasfoo** [comment] 2022-01-03 13:31
@pmcpinto If we're going to use other countries like you suggested, ideally before Thursday since RC is next week Tuesday. If we're attempting my suggestion, I'd say by tomorrow since otherwise, we may risk having to include big changes after RC.

**Comment by pmcpinto** [comment] 2022-01-03 18:38
@ilyasfoo let's go with using 100% of other countries*: NZ and IE. This option seems to be less risky and with less work and less tech debt. Thanks!

*  excluding new users and users who already have the extension installed or a wcpay account

cc @thenbrent

**Comment by moon0326** [comment] 2022-01-04 00:45
Thank you @pmcpinto @ilyasfoo! It sounds like we have a plan 👍

**Comment by pmcpinto** [comment] 2022-01-05 07:17
The experiment name can be: woocommerce_payments_menu_promo_nz_ie

**Comment by ilyasfoo** [comment] 2022-01-05 08:43
@pmcpinto  Would we want to use dynamic naming, `woocommerce_payments_menu_promo_nz_ie_2022_01`? We can set the experiment for February as well

**Comment by pmcpinto** [comment] 2022-01-05 10:20
> @pmcpinto Would we want to use dynamic naming, woocommerce_payments_menu_promo_nz_ie_2022_01? We can set the experiment for February as well

Good idea. It makes sense to use dynamic naming. Thanks for the suggestion 🙌

**Comment by ilyasfoo** [comment] 2022-01-06 02:24
@pmcpinto Nice! Are you able to help with setting up the experiments? Code changes are made by @moon0326 and at the moment we're pretty confident the logic works, but it'll be great to have it up with `staging` by Monday next week so we can properly test before RC. 

Btw just to be clear, don't use the audience country filter in Abacus because we're using a custom segment for checking eligibility based on the store location.

**Comment by pmcpinto** [comment] 2022-01-10 14:46
@ilyasfoo based on what we talked about last week, the Abacus experiment will be implemented by Chi-Hsuan, right?

**Comment by ilyasfoo** [comment] 2022-01-11 01:10
@pmcpinto Yes

**Comment by pmcpinto** [comment] 2022-01-26 11:23
@ilyasfoo the Abacus experiment was enabled a couple of days ago. Is everything working properly? Let me know if you're confident that we'll be able to release this in WC 6.2. Thanks

**Comment by ilyasfoo** [comment] 2022-01-27 06:48
@pmcpinto I've just tested it in [WC 6.2 RC](https://developer.woocommerce.com/2022/01/25/woocommerce-6-2-rc/) in both WPCOM and JN, I confirmed to be able to get treatment when the store is in `NZ` or `IE`. @moon0326 had also deployed the bridge changes yesterday to make sure the WCPay menu codes do not conflict.

I'm confident it's ready for release in 6.2

**Comment by pmcpinto** [comment] 2022-01-27 10:07
> @pmcpinto I've just tested it in WC 6.2 RC in both WPCOM and JN, I confirmed to be able to get treatment when the store is in NZ or IE. @moon0326 had also deployed the bridge changes yesterday to make sure the WCPay menu codes do not conflict.
> I'm confident it's ready for release in 6.2

@ilyasfoo thanks for the update. Were you able to verify that the event tracking is working as expected?
I'm trying to use the bookmarklet to get the treatment version, but it's not working 🤔

**Comment by ilyasfoo** [comment] 2022-01-27 12:23
@pmcpinto It's possible that your site may have attempted to get an assignment while not having the store's location set up yet, thus gets ineligible, and it's cached so changing store location would not immediately fix it. The cache is stored for 2 hours so you may try again after.

I find a reliable way to test this in JN is install WC 6.1 first, setup the store with NZ or IE, and then install 6.2 RC. Also make sure WCPay plugin isn't already installed (I noticed WPCOM ecom plan does this). I didn't even have to use bookmarklet since the experiment is already running and JN isn't proxied I think.

> Were you able to verify that the event tracking is working as expected?

Yep! I've tested and these tracks were fired:
- wcadmin_wcpay_exit_survey
- wcadmin_wcpay_welcome_learn_more
- wcadmin_wcpay_connect_account_clicked
- wcadmin_page_view

**Comment by pmcpinto** [comment] 2022-01-27 16:40
> @pmcpinto It's possible that your site may have attempted to get an assignment while not having the store's location set up yet, thus gets ineligible, and it's cached so changing store location would not immediately fix it. The cache is stored for 2 hours so you may try again after.

You're right. It was a caching issue. I just checked the JN site and was able to access the experiment.

**Comment by becdetat** [comment] 2022-03-07 04:02
@pmcpinto @adrianduffell @ilyasfoo  Is this ticket able to be closed?

**Comment by ilyasfoo** [comment] 2022-03-24 12:10
@becdetat Yes this can be closed, we've just finished running the WCPay in core experiment. I think any further actions should be filed in a new issue.

**Closed as completed by ilyasfoo** 2022-03-24 12:10 UTC
Labels: Payments, plugin: woocommerce

**Comment by becdetat** [comment] 2022-03-25 04:32
Thanks @ilyasfoo :-)
