### ISSUE TITLE
Report is displaying HTML for certain elements (Product Vendor, WC Ship&Tax)

### ISSUE THREAD

**Issue by namiokuzono** [woothemes/woocommerce#38900] opened 2023-06-22 20:57 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In the below two cases, the issues show up when a merchant views their Shipping labels under WooComemrce > Reports > Shipping Labels

6405094-zd-woothemes
6409018-zd-woothemes

## WC Ship&Tax

Shipping Labels Report: WooCommerce Reports > **Shipping Labels tab**:
![image](https://github.com/woocommerce/woocommerce/assets/85893744/249ac97f-6107-4f0c-a563-560933e34044)

## Product Vendor
It is also happening with Product Vendor - WooCommerce > Reports > **Vendors tab**: 
![ss-Mgj0SvsA](https://github.com/woocommerce/woocommerce/assets/85893744/3f88581d-9a8b-464c-9ecd-5d16255b9ff6)

This issue also happens when you are vendor, and viewing reports. 
![ss-mOgFni3x](https://github.com/woocommerce/woocommerce/assets/85893744/e05293ff-a66e-4e82-86a3-14234a083033)

### Expected behavior

HTML should not be escaped like this in reports. 

### Actual behavior

So far, we have these specific instances for Product Vendors and Shipping Labels reports. 

### Steps to reproduce

WC Ship&Tax
1. Install WooCommerce and Shipping & Tax 
2. Test purchase shipping label 
3. Go to WooCommerce > Reports > **Shipping Labels tab**

Product vendor:
1. Install WooCommerce and Product Vendor
2. Test purchase any products 
3. Go to WooCommerce > Reports > **Vendors tab**

### WordPress Environment

[SystemStatusReport_woo-nation.mystagingwebsite.com_2023-06-22T20-57-09.txt](https://github.com/woocommerce/woocommerce/files/11840423/SystemStatusReport_woo-nation.mystagingwebsite.com_2023-06-22T20-57-09.txt)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by namiokuzono** [comment] 2023-06-22 22:02
6455250-zd-woothemes

**Comment by jtobiesen** [comment] 2023-06-23 10:45
6405094-zd-woothemes

**Comment by samueljseay** [comment] 2023-06-26 13:16
@namiokuzono it looks like these bugs are for reports generated by other plugins? Perhaps these issues should be raised with those plugins and not in core?

**Comment by thisissandip** [comment] 2023-06-26 14:19
@samueljseay you are on point. The issue is not within the core but within the other plugins. I have created the issues. We can close this.

**Closed as completed** 2023-06-27 12:22 UTC
Labels: Bug, needs: author feedback

**Comment by muhammedsafiulazam** [comment] 2023-06-27 23:20
I'm facing this issue. I have tried by deactivating plugins and themes. Vendor's reports are completely broken.
