### ISSUE TITLE
PHP Notice: `Undefined index: woocommerce_wc_pay_promotion_payment_methods_table_v2`

### ISSUE THREAD

**Issue by strarsis** [woothemes/woocommerce#32201] opened 2022-01-09 16:32 UTC
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When loading the "Payments" page in WooCommerce settings, a PHP notice occurs:
````
Undefined index: woocommerce_wc_pay_promotion_payment_methods_table_v2
````

### Expected behavior

No PHP notices, especially not because for missing indices.

### Actual behavior

PHP notice for a missing index.

### Steps to reproduce

1. New WordPress installation.
2. Install and enable WooCommerce plugin.
3. For unknown reasons the WooCommerce setup appears to be unfinished, the WooCommerce setup Dashboard widget lists `0 / 6 steps`, which already seems to be an unexpected internal state.
4. Open the WooCommerce (general) settings page - no PHP notices/warnings/errors yet.
5. Open the WooCommerce payments settings page. 
The described PHP notice occurs.

````
### WordPress Environment ###

WordPress address (URL): https://<redacted>/wp
Site address (URL): https://<redacted>
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: de_DE_formal
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.19.4
PHP Version: 7.4.21
PHP Post Max Size: 150 MB
PHP Time Limit: 600
PHP Max Input Vars: 6000
cURL Version: 7.68.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.6-MariaDB-1:10.5.6+maria~focal
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 7.51MB
Datenbank-Datengröße: 4.47MB
Datenbank-Indexgröße: 3.04MB
wp_woocommerce_sessions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lockdowns: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_login_fails: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Daten: 2.25MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Daten: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_posts: Daten: 0.31MB + Index: 0.06MB + Engine InnoDB
wp_redirection_404: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_stream: Daten: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_stream_meta: Daten: 0.30MB + Index: 0.48MB + Engine InnoDB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsal_metadata: Daten: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_wsal_occurrences: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 14
page: 14
post: 3
revision: 27
woovouchers: 5
wp_global_styles: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

EditorsKit: von Munir Kamal – 1.33.3
Disable Blog: von Joshua Nelson – 0.4.10
Disable Comments: von WPDeveloper – 2.3.2
Dublin Core Title Metatag: <Redacted>
Favicon by RealFaviconGenerator: von Philippe Bernard – 1.3.29
Gutenberg: von Gutenberg-Team – 12.3.0
Jetpack: von Automattic – 10.4
Login LockDown: von Michael VanDeMar – v1.8.1
PayPal for WooCommerce: von Angell EYE – 2.5.19
Preferred Languages: von Pascal Birchler – 1.8.0
Redirection: von John Godley – 5.1.3
Reusable Blocks Extended: von audrasjb – 0.8
Stream: von XWP – 3.8.2
SVG Support: von Benbodhi – 2.3.21
User Role Editor: von Vladimir Garagulya – 4.61
Germanized für WooCommerce: von vendidero – 3.8.0
WooCommerce: von Automattic – 6.0.0
WP Activity Log for WooCommerce: von WP White Security – 1.3.1
WP Mail SMTP: von WPForms – 3.2.1
WP Redis: von Pantheon
Josh Koenig
Matthew Boynes
Daniel Bachhuber
Alley Interactive – 1.1.4

wp-Typography: von Peter Putzer – 5.7.2

### Inactive Plugins (0) ###


### Dropin Plugins (1) ###

object-cache.php: object-cache.php

### Must Use Plugins (2) ###

Bedrock Autoloader: von Roots – 1.0.3
Register Theme Directory: von Roots – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: woocommerce/woocommerce#50 - /shop/
Warenkorb: woocommerce/woocommerce#51 - /shop/warenkorb/
Kasse: woocommerce/woocommerce#52 - /shop/kasse/
Mein Konto: woocommerce/woocommerce#53 - /shop/mein-konto/
Allgemeine Geschäftsbedingungen: woocommerce/woocommerce#62 - /shop/agb/

### Theme ###

Name: <Redacted>
Version: 1.0.0
Author URL: <Redacted>
Child Theme: ❌ – Wenn Sie WooCommerce mit einem Theme
das Sie nicht selbst entwickelt haben
an eigene Bedürfnisse anpassen
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie Sie ein Child-Theme erstellen (engl.)

WooCommerce Support: ❌ Nicht deklariert

### Templates ###

Overrides: –

### Action Scheduler ###

Abgeschlossen: 11
Oldest: 2022-01-09 14:50:02 +0000
Newest: 2022-01-09 14:55:42 +0000

Ausstehend: 3
Oldest: 2022-01-10 02:00:03 +0000
Newest: 2022-01-10 03:00:03 +0000


### Status report information ###

Generated at: 2022-01-09 17:29:47 +01:00
````

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by joshuahalldesign** [comment] 2022-01-10 06:32
Same issue happening for me.

**Comment by swatipawarGS** [comment] 2022-01-10 12:46
Hi @strarsis ,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using WooCommerce 6.0.0 version and WordPress 5.8.3 version.

Please find below screenshot for reference :

![#31594](https://user-images.githubusercontent.com/94531721/148751581-12d546d8-2d6f-4b24-a8eb-f37fa509cbcd.jpg)


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by barryhughes** [comment] 2022-03-10 03:28
Looks like this relates to `WooCommerce\Admin\Experimental_Abtest` and/or `Automattic\WooCommerce\Admin\Features\WcPayPromotion\Init` ... moving to WC Admin for further triage.

**Comment by adrianduffell** [comment] 2023-05-02 02:20
Thanks for reporting this @strarsis, it's much appreciated. It looks like the notice no longer appears so I'll close this out. Please re-open if you continue to see the problem.

![image](https://user-images.githubusercontent.com/9312929/235565288-707e2b33-e679-4e58-895b-1d24a495a881.png)

**Closed as completed** 2023-05-02 02:20 UTC
Labels: Bug, plugin: woocommerce
