### ISSUE TITLE
Unable to obtain list of countries during setup

### ISSUE THREAD

**Issue by Fydon** [woothemes/woocommerce#50865] opened 2024-08-22 09:20 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When creating a new domain based Multisite WordPress instance using [Local](https://localwp.com/) with PHP 8.1.29, Apache 2.4.43 and MySQL 8.0.16 and activating the WooCommerce plugin, I see the error "_Oops! We encountered a problem while fetching the list of countries to choose from._". Selecting skip this step causes the new page to load, but never progressing beyond that page. As you can see in the GIF below, there are multiple 404 errors.

![msedge_C5U7jJcbLM](https://github.com/user-attachments/assets/845876a4-37e1-4667-92f5-560d6cf276cf)

The failure to load the country list was mentioned as a part of https://github.com/woocommerce/woocommerce/issues/49512#issuecomment-2300555111, but the focus of the fix was on defaulting values so that they are present rather than why the list was not available.

### Expected behavior

The country list loads and the setup process completes.

### Actual behavior

The setup process does not complete.

### Steps to reproduce

1. Install Local
2. Create a domain based Multisite WordPress (currently version 6.6.1) instance with PHP 8.1.29, Apache 2.4.43 and MySQL 8.0.16
3. Install WooCommerce on the network (currently version 9.2.1)
4. Active WooCommerce on the site

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.2.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Win32) mod_fcgid/2.3.9a
PHP Version: 8.1.29
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 8.4.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
page: 7
post: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 9.2.1

### Inactive Plugins (0) ###


### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 13 B

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/ -  Contains the woocommerce/cart block
Checkout: #8 - /checkout/ -  Contains the woocommerce/checkout block
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-08-22 08:41:47 +00:00
Options: ✔
Notes: 1
Onboarding: -

### Action Scheduler ###

Pending: 2
Oldest: 2024-08-22 08:41:58 +0000
Newest: 2024-08-22 08:42:53 +0000


### Status report information ###

Generated at: 2024-08-22 09:12:41 +00:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by chihsuan** [comment] 2024-09-04 10:12
Hey @Fydon, The 404 errors are likely because your local environment routing might not be set up correctly. Please double-check your Apache configuration and ensure that it is correct. The WooCommerce plugin is trying to fetch the country list via an AJAX request, but the request is failing because the route has yet to be found. 

If you still can't figure it out, I recommend contacting the [WooCommerce support forums](https://wordpress.org/support/plugin/woocommerce/) for further assistance. 

Since this is not a bug, we will close this issue soon. If you have any other questions, feel free to ask. Thanks!

**Comment by Fydon** [comment] 2024-09-04 10:44
Local sets up everything (database, mail, host file, apache, PHP, etc.) and everything else works fine, just not the WooCommerce setup. When I set it up myself using manually (Docker, Caddy, etc.) or use Studio by WordPress it works. I mainly filed the bug as for some people using Local (or now Studio) would be the only way they would be able to be able to try WooCommerce locally. I'm able to use other means.

**Comment by chihsuan** [comment] 2024-09-06 07:09
Thanks for the clarification! Based on your response, it seems like the issue is specific to Local's setup. I don't think this is a WooCommerce issue, but rather a Local issue as this is because of the way Local sets up server routing. I recommend reaching out to Local's support team for further assistance if anyone else is facing the same issue. 

Thanks for bringing this to our attention!

**Closed as completed by chihsuan** 2024-09-06 07:09 UTC
Labels: Bug, focus: i18n, type: community contribution, Onboarding

**Comment by ilyasfoo** [comment] 2024-10-11 02:54
Reported in 8791532-zd-a8c, user bumped into this error. Unknown if environment is Local, but potentially we could do a better error handling to prompt the user about a misconfigured site

**Comment by sym0503** [comment] 2024-10-18 13:15
I have the same question, are you using 1panel to install WordPress?

**Comment by samayo** [comment] 2024-12-14 16:56
i just had this issue and i rested nginx and php it went away, for context i had a redeclared WP_DEBUG in wp-config.php and it was showing error but i removed that before restarting the services, not sure if this had anything to do with it.

**Comment by BeshevGames** [comment] 2024-12-18 16:17
Had the same problem, switched from Firefox to Chrome and it worked.
