### ISSUE TITLE
Buttons in the Products (beta) block doesn't follow the global button styling, and aren't consistent with the editor

### ISSUE THREAD

**Issue by asafm7** [woothemes/woocommerce#42283] opened 2023-07-21 15:16 UTC
Buttons in the Products (beta) block don't follow the global button styling and aren't consistent with the editor.

Steps to reproduce:
1. Go to Editor
2. Add Products (Beta) block
3. Change the Product Button styles through Inspector Controls
4. Save the changes
5. Go to frontend

More information:
When a regular, standalone, button block is added to the template - the issue is fixed. So, I assume the issue is that when there isn't a regular button on the page the button styling isn't being loaded.

This issue might affect more blocks, such as Cart, Mini Cart, Add to Cart, or Add to Cart with Options blocks.

Screenshot:
![image](https://github.com/woocommerce/woocommerce-blocks/assets/14274769/40ba6596-3985-42cf-b70a-08d484717f91)
 
Left: Frontend view; Right: Editor view

**Comment by kmanijak** [comment] 2023-08-01 12:04
Hi @asafm7, thanks for raising this issue! I confirm I can reproduce it by following these steps:

Steps to reproduce:
1. Go to Editor
2. Add Products (Berta) block
3. Change the Product Button styles through Inspector Controls
4. Save the changes
5. Go to frontend 

Expected: Button styles should be the same in Editor and Frontend
Actual: Custom styles are applied in Editor, but not in Frontend

I assigned this issue to the Product Collection epic, which is a block that we're actively working on that will bring more flexibility than Products (Beta) block. In terms of product elements (like button), they use the same blocks underneath, hence one fix should solve the problem for both Products (Beta) and Product Collection.

@asafm7, can I ask you to include the steps to reproduce the issue to the issue description (feel free to copy-paste the ones I provided above) and add description to images in table so it's easier to understand by anybody who's going to work on this in future? Thanks! 🙌

**Comment by asafm7** [comment] 2023-08-01 17:50
Sure, @kmanijak.

I added the steps.

I'm not sure I understand what you meant about the description though (and couldn't find a how to add a table). I added a short description. I hope it's alright. Let me know if anything else is needed from me.

**Comment by kmanijak** [comment] 2023-08-02 06:58
> I'm not sure I understand what you meant about the description though

Sorry for the confusion! I meant exactly what you did, to add steps to the issue 🙌 

> (and couldn't find a how to add a table)

Never mind, my bad - I had an impression the screenshot you added is in fact two screenshots in table 🤦 

> I added a short description.

This is perfect, thank you! 🙌

**Comment by imanish003** [comment] 2023-12-27 07:11
Hi @asafm7,

I attempted to replicate the issue and it appears to have been resolved in the current version.

@kmanijak, can you confirm if this issue is still occurring on your end?

**Comment by kmanijak** [comment] 2023-12-28 11:05
Seems related: https://github.com/woocommerce/woocommerce-blocks/issues/8667

**Comment by kmanijak** [comment] 2023-12-28 13:37
> @kmanijak, can you confirm if this issue is still occurring on your end?

Yes, @imanish003 I can't reproduce it anymore with neither Products (Beta) nor Product Collection block, hence I'm closing the issue.

**Closed as completed by kmanijak** 2023-12-28 13:37 UTC
Labels: Bug, Kirigami, block-type: product elements, block: product collection
