### ISSUE TITLE
Shop Page Filter Query Causes Inconsistent Block UI Rendering Without Product Attribute Lookup Table

### ISSUE THREAD

**Issue by Lee-WonJun** [woothemes/woocommerce#44453] opened 2024-02-08 12:42 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When including a filter query on the Shop page, filtering products with the catalog table's product lookup table results in the Block UI rendering correctly. However, if not using the product lookup table, the Block UI fails to render properly. This issue arises because the get_template_loader_default_file function determines there is no taxonomy_has_block_template and thus renders taxonomy-product-attribute.php. Notably, this problem does not occur with Storefront since it is not a block theme.

https://github.com/woocommerce/woocommerce/assets/10369528/9c07a588-3de8-44b0-819e-db021a915d5a

### Expected behavior

The variation in template rendering based on the use of the attribute table is unusual and not desirable. When using filters on the Shop page, utilizing the block renderer seems to be the correct approach regardless of the attribute table's usage status.

### Actual behavior

When not using the catalog table's product lookup table, the Block UI does not render correctly.

### Steps to reproduce

1. Enable the use of the product lookup table in the WordPress admin page.
2. Navigate to WooCommerce > Shop page.
3. Attempt product filtering using AJAX. (Directly entering a URL with the filter query string is also viable.)
4. Observe normal operation.
5. Disable the use of the product lookup table in the WordPress admin page.
6. Confirm the issue where the Block UI fails to render properly when not using the product lookup table.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost:8000
Site address (URL): http://localhost:8000
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: ❌ 6.3.2 - 새 버전의 워드프레스를 사용할 수 있습니다(6.4.3).
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: ko_KR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Debian)
PHP Version: 8.1.25
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.88.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 5.7.44
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ 귀하의 서버는 SoapClient 클래스가 활성화되어있지 않습니다 - 몇 결제 게이트웨이는 SOAP를 사용하며
올바르게 동작하지 않을 수 있습니다.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
총 데이터베이스 크기: 93.95MB
데이터베이스 데이터 크기: 81.22MB
데이터베이스 인덱스 크기: 12.73MB
wp_woocommerce_sessions: 데이터: 0.02MB + 색인: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: 데이터: 0.02MB + 색인: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: 데이터: 0.02MB + 색인: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: 데이터: 0.02MB + 색인: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: 데이터: 0.02MB + 색인: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: 데이터: 0.02MB + 색인: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: 데이터: 0.02MB + 색인: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: 데이터: 0.02MB + 색인: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: 데이터: 0.02MB + 색인: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: 데이터: 0.02MB + 색인: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: 데이터: 0.02MB + 색인: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: 데이터: 0.02MB + 색인: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: 데이터: 0.02MB + 색인: 0.03MB + Engine InnoDB
wp_woocommerce_log: 데이터: 0.02MB + 색인: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: 데이터: 0.05MB + 색인: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: 데이터: 0.02MB + 색인: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: 데이터: 0.02MB + 색인: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: 데이터: 0.02MB + 색인: 0.03MB + Engine InnoDB
wp_commentmeta: 데이터: 0.02MB + 색인: 0.03MB + Engine InnoDB
wp_comments: 데이터: 0.02MB + 색인: 0.09MB + Engine InnoDB
wp_links: 데이터: 0.02MB + 색인: 0.02MB + Engine InnoDB
wp_options: 데이터: 4.05MB + 색인: 0.06MB + Engine InnoDB
wp_postmeta: 데이터: 67.59MB + 색인: 4.03MB + Engine InnoDB
wp_posts: 데이터: 8.52MB + 색인: 7.06MB + Engine InnoDB
wp_snippets: 데이터: 0.02MB + 색인: 0.03MB + Engine InnoDB
wp_termmeta: 데이터: 0.02MB + 색인: 0.03MB + Engine InnoDB
wp_terms: 데이터: 0.02MB + 색인: 0.03MB + Engine InnoDB
wp_term_relationships: 데이터: 0.02MB + 색인: 0.02MB + Engine InnoDB
wp_term_taxonomy: 데이터: 0.02MB + 색인: 0.03MB + Engine InnoDB
wp_usermeta: 데이터: 0.02MB + 색인: 0.03MB + Engine InnoDB
wp_users: 데이터: 0.02MB + 색인: 0.05MB + Engine InnoDB
wp_wc_admin_notes: 데이터: 0.06MB + 색인: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: 데이터: 0.05MB + 색인: 0.02MB + Engine InnoDB
wp_wc_category_lookup: 데이터: 0.02MB + 색인: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: 데이터: 0.02MB + 색인: 0.03MB + Engine InnoDB
wp_wc_download_log: 데이터: 0.02MB + 색인: 0.03MB + Engine InnoDB
wp_wc_orders: 데이터: 0.02MB + 색인: 0.11MB + Engine InnoDB
wp_wc_orders_meta: 데이터: 0.02MB + 색인: 0.03MB + Engine InnoDB
wp_wc_order_addresses: 데이터: 0.02MB + 색인: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: 데이터: 0.02MB + 색인: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: 데이터: 0.02MB + 색인: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: 데이터: 0.02MB + 색인: 0.06MB + Engine InnoDB
wp_wc_order_stats: 데이터: 0.02MB + 색인: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: 데이터: 0.02MB + 색인: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: 데이터: 0.02MB + 색인: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: 데이터: 0.02MB + 색인: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: 데이터: 0.02MB + 색인: 0.09MB + Engine InnoDB
wp_wc_rate_limits: 데이터: 0.02MB + 색인: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: 데이터: 0.02MB + 색인: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: 데이터: 0.02MB + 색인: 0.02MB + Engine InnoDB
wp_wc_webhooks: 데이터: 0.02MB + 색인: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 29667
page: 8
post: 2
product: 27
revision: 2
shop_order_placehold: 1
wp_global_styles: 1
wp_navigation: 1
wp_template: 3
wpc_product_badge: 2
yith_wcan_preset: 1
yith-wcbm-badge: 1

### Security ###

Secure connection (HTTPS): ❌
					상점에서 HTTPS를 사용하고 있지 않습니다. HTTPS 및 SSL 인증서에 대해 더 알아보기 .
Hide errors from visitors: ✔

### Active Plugins (4) ###

Code Snippets: Code Snippets Pro – 3.6.2
우커머스: 오토매틱스 – 8.4.0(8.5.2 버전으로 업데이트할 수 있음)
WPC Badge Management for WooCommerce: WPClever – 2.3.7
YITH WooCommerce Ajax Product Filter: YITH – 4.30.0

### Inactive Plugins (4) ###

Akismet Anti-spam: Spam Protection: Automattic - Anti-spam Team – 5.3
Category Order and Taxonomy Terms Order: Nsp-Code – 1.8
Hello Dolly: Matt Mullenweg – 1.7.2
YITH WooCommerce Badge Management: YITH – 3.2.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: KRW (₩)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

상점 기준 경로: #6 - /shop/
장바구니: #7 - /cart/
결제: #8 - /checkout/
내 계정: #9 - /my-account/
이용약관: ❌ 페이지가 설정되지 않았습니다

### Theme ###

Name: Blockskit Shop
Version: 1.0.0
Author URL: https://blockskit.com
Child Theme: ❌ – 직접 제작한 테마가 아닌 경우 부모 테마의 우커머스 코드를 수정하는 것보다 하위 테마를 사용할 것을 권장합니다. 다음을 참고하세요: 하위 테마 생성하기
WooCommerce Support: ❌ 선언되지 않음

### Templates ###

Overrides: /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-13 06:44:23 +09:00
Options: ✔
Notes: 65
Onboarding: completed

### Action Scheduler ###

대기 중: 74
Oldest: 2023-12-13 15:44:26 +0900
Newest: 2024-02-08 20:22:50 +0900

### Status report information ###

Generated at: 2024-02-08 21:29:00 +09:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Aljullu** [comment] 2024-02-13 07:43
Thanks for opening this issue and creating a PR, @Lee-WonJun!

Unfortunately, we tried to reproduce the issue you described without luck, could you give us more details on how to reproduce it? When doing so, make sure to disable all plugins, switch to a default theme (ie: Twenty Twenty Four) and remove any custom code you might have written, this will help us reproduce the steps in an environment similar to yours.

Thanks in advance!

**Comment by Lee-WonJun** [comment] 2024-02-14 12:34
@Aljullu 
I retested this issue with a new Docker container, and it occurred again. This is a block theme issue, so it cannot be reproduced with the default theme. I used the Blockskit Shop theme for reproduction.

Additionally, I am not entirely sure about the conditions that cause this error, so I am sharing the settings in WooCommerce.
`http://localhost:8000/shop/?product_cat=Uncategorized&filter_a=aa,bb&query_type_a=or`


![image](https://github.com/woocommerce/woocommerce/assets/10369528/c19b1a11-8bdd-406f-9a27-fdbd89e20279)
![image](https://github.com/woocommerce/woocommerce/assets/10369528/d4626bf2-c200-4519-8c8a-e07c9657cec6)
![image](https://github.com/woocommerce/woocommerce/assets/10369528/30572351-0be1-4ea0-a990-ec3612970fe1)
![image](https://github.com/woocommerce/woocommerce/assets/10369528/3b8cf3f1-a412-4d69-9c38-029b9160e4f8)
![image](https://github.com/woocommerce/woocommerce/assets/10369528/740e88ff-46e8-4a10-8d1e-e89f93dcf03f)
![image](https://github.com/woocommerce/woocommerce/assets/10369528/0167c74a-106a-4178-ad54-c3440827abcf)

this is sql dump
[sql.zip](https://github.com/woocommerce/woocommerce/files/14279424/sql.zip)

**Comment by Aljullu** [comment] 2024-02-14 15:38
Thanks for coming back to us, @Lee-WonJun! I just tested with [Blockskit Shop theme](https://wordpress.org/themes/blockskit-shop/) and the [YITH WooCommerce Ajax Product Filter plugin](https://wordpress.org/plugins/yith-woocommerce-ajax-navigation/) but I'm still unable to reproduce.

I would suggest reading the [WooCommerce Self-Service Guide](https://woo.com/document/woocommerce-self-service-guide/), which helps diagnose this kind of issues, specially the part focused on identifying [Plugin and theme conflicts](https://woo.com/document/woocommerce-self-service-guide/#section-4). Once you know which plugin is causing the conflict, you will need to contact the authors of that specific plugin so they can investigate the bug. Unfortunately, that's not something we can fix from the WooCommerce side.

> This is a block theme issue, so it cannot be reproduced with the default theme.

Heads-up that [Twenty Twenty-Four](https://wordpress.org/themes/twentytwentyfour/) is a default theme and a block theme. So ideally you should be able to reproduce the issue in Twenty Twenty-Four or any other WordPress default theme.

While we do our best to make WooCommerce compatible with all plugins and themes out there, we are not able to audit all codebases from every WooCommerce plugin, theme and store.

Hope you understand!

**Comment by Lee-WonJun** [comment] 2024-02-14 17:25
@Aljullu 
I've confirmed that the issue occurs even with a totally clear installation of WooCommerce (via a docker container). After experimenting with several block WooCommerce themes (Blockskit Shop theme / deco (not free) / Gadgethub), the problem persists, but it appears normal with the "Twenty Twenty-Four" theme. To understand this phenomenon, I analyzed the code and found that block themes do not work with themes that include archive-product.html, as shown in the attached file.

![image](https://github.com/woocommerce/woocommerce/assets/10369528/cf2837ff-6f33-4c5b-a773-f1ebb1928972)

I am almost certain this is an issue with WooCommerce because it is odd that the elements rendered change depending on the presence of an attributes table.

To reproduce the phenomenon exa

https://github.com/woocommerce/woocommerce/assets/10369528/eeee296d-639d-40f7-a62c-d0d2e10fb974

ctly, I will capture a video from start to finish.

**Comment by Aljullu** [comment] 2024-02-15 08:22
Thanks for the detailed video, @Lee-WonJun, I was finally able to reproduce the same as you! :tada: I will be investigating this issue today.

**Comment by Aljullu** [comment] 2024-03-15 12:12
It turns out, this issue was fixed in https://github.com/woocommerce/woocommerce/pull/44537, so it will be included in WooCommerce 8.8.0. :slightly_smiling_face: Besides that, in https://github.com/woocommerce/woocommerce/pull/44850 we include some more changes that would have fixed the issue too (and which will prevent similar issues to appear in the future).

Based on that, I will go ahead and close this issue.

**Closed as completed by Aljullu** 2024-03-15 12:12 UTC
Labels: Bug, needs: triage feedback, type: community contribution, Kirigami, Blocks/Patterns/Templates, block: products by attribute
