### ISSUE TITLE
Payments Welcome Screen needs updating

### ISSUE THREAD

**Issue by rogermattic** [woothemes/woocommerce#33623] opened 2022-06-27 14:18 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When the user goes directly to Payments from the main navigation, currently we display an outdated version of the Payments Welcome  Screen and the  accordion link to display `Other payment providers` is missing

### Expected behavior

1. The design should be aligned with [this Figma](https://www.figma.com/file/e428PXC0QyEwYqtX48lLq0/%5BWCPay%5D-Positioning-and-Conversion?node-id=12835%3A106429)
2. There should be an accordion link included to see `Other payment providers`
3. When expanded, the `See more` link should take the user to the external marketplace (https://woocommerce.com/product-category/woocommerce-extensions/payment-gateways/)

### Actual behavior

Payments page displays an old version of the Payments Welcome Screen and is missing an accordion link to display `Other payment providers`

<img width="895" alt="Screenshot 2022-06-27 at 15 13 45" src="https://user-images.githubusercontent.com/94967682/175963389-b1669202-8e03-4491-9bf7-c6a4a8bcbf37.png">

### Steps to reproduce

1. Onboard to WooCommerce from a WCPay eligible country (opt in to install WCPay during the initial onboarding)
2. Select `Payments` in the main navigation

### WordPress Environment

WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ilyasfoo** [comment] 2022-07-05 05:30
Hi @rogermattic, looking at the screenshot you provided, I believe that UI is coming from WooCommerce Payments plugin when it is installed & activated (as the URL is pointing to `/payments/connect`).

If WCPay isn't activated, this is the screen we're showing:

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/3747241/177256006-1ee9a76d-a42b-4a69-b8e5-b3d6a8b8ec14.png">

**Comment by rogermattic** [comment] 2022-07-05 20:29
Hey @ilyasfoo you are right and  as I mentioned in the **Steps to reproduce**:
1. Onboard to WooCommerce from a WCPay eligible country (opt in to install WCPay during the initial onboarding)
2. Select Payments in the main navigation

The screenshot that I attached is coming from the state when WCPayments is installed (during the initial onboarding to WooCommecre) but haven't been activated yet. So when I went to the **Payments** item from the main navigation, that's how it's looking:
<img width="1746" alt="Screenshot 2022-07-05 at 21 24 53" src="https://user-images.githubusercontent.com/94967682/177410189-54bf4908-e056-44f0-a98c-b7066a658e74.png">

In this state, the expected behavior should be:
1. The design should be aligned with [this Figma](https://www.figma.com/file/e428PXC0QyEwYqtX48lLq0/%5BWCPay%5D-Positioning-and-Conversion?node-id=12835%3A106429)
2. There should be an accordion link included to see Other payment providers
3. When expanded, the See more link should take the user to the external marketplace (https://woocommerce.com/product-category/woocommerce-extensions/payment-gateways/)

I think the screenshot that you attached in your comment is actually coming from the state when WCPay haven't been installed & activated, it's also the view that is accessible from the Homescreen Task List, which isn't the case I wanted to cover.

Does that make sense?

**Comment by ilyasfoo** [comment] 2022-07-06 02:44
Thanks for confirming, @rogermattic! Unfortunately, both the `Payment` menu item and screen you're referring to (`/payments/connect`) do not live in WooCommerce Core, so we don't have control over the UI. It lives in [WooCommerce Payments plugin](https://github.com/Automattic/woocommerce-payments/blob/trunk/client/index.js#L47:L56), so it needs to be handled by another team 🙏

**Comment by rogermattic** [comment] 2022-07-07 13:19
Hey @ilyasfoo thanks for your message. What's the best way I could direct it to the relevant team, please?

**Comment by ilyasfoo** [comment] 2022-07-08 11:13
Hi @rogermattic, I believe team @woocommerce/moltres were working on the `/payments/connect` screen. Sorry if I tagged the wrong team!

**Comment by ismaeldcom** [comment] 2022-07-08 12:58
Hi @ilyasfoo! Yes, we've worked before with that screen. And I think the issue @rogermattic mentions might be caused by the expected design being under an Explat experiment. We've never decided to commit to the new or older design after the experiment.

**Comment by chihsuan** [comment] 2022-07-14 03:10
Hey @rogermattic I'm going to close this since the screen lives in `WooCommerce Payments` plugin. Please feel free to let us know if anything that we could help with. Thanks!

**Closed as completed by chihsuan** 2022-07-14 03:10 UTC
Labels: Bug, Payments, plugin: woocommerce
