### ISSUE TITLE
$order->update_status( 'wc-completed' ); not sending order notes in email

### ISSUE THREAD

**Issue by streamworksaudio** [woothemes/woocommerce#31424] opened 2021-12-12 05:21 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have some code that is fired by the woocommerce_order_status_processing hook.  The code goes through each item on the order and retrieves (if required) some meta data for the product and adds it as an order note for that item (wc_add_order_item_meta).  This works perfectly.  However I am trying to tweak it so that the order is set to 'Completed' after the notes are added (as the item would be a virtual item).   I do this by calling $order->update_status( 'wc-completed' ); at the end of the code.  This does set the order to complete, however the email sent does not have the new Order Note added to it (under the item listing).  The orders are indeed created as you can see them from the My Account->View Order page. 

If I am to leave this out of the code and manually update the order from processing to completed in the admin then the email will show the order notes correctly.  It is only when I set the order to automatically update to 'Completed' does this happen.

Is this the correct behaviour?  Isn't there a way to automatically update the order to completed with the order noted showing on the email?

Cheers

### Expected behavior

Order notes are created by function on the woocommerce_order_status_processing hook and sent with the email after setting the order to completed with $order->update_status( 'wc-completed' );

### Actual behavior

Order notes are created however not on the 'Order Complete' email.

### Steps to reproduce

Use the woocommerce_order_status_processing hook to add order item notes then use $order->update_status( 'wc-completed' );  - the Order Complete email will be missing the notes.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://streamworksaudio.com
Site address (URL): https://streamworksaudio.com
WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.1.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 2.8.0
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Ubuntu)
PHP Version: 7.4.3
PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.27-0ubuntu0.20.04.1
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: wp_
Total Database Size: 130.78MB
Database Data Size: 96.06MB
Database Index Size: 34.72MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.47MB + Index: 1.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.30MB + Index: 0.13MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_as3cf_items: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_commentmeta: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_comments: Data: 2.52MB + Index: 1.44MB + Engine InnoDB
wp_dokan_announcement: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_orders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dokan_refund: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_vendor_balance: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_withdraw: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fc_campaign_emails: Data: 18.02MB + Index: 4.27MB + Engine InnoDB
wp_fc_campaign_url_metrics: Data: 1.03MB + Index: 0.00MB + Engine InnoDB
wp_fc_campaigns: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_fc_funnel_metrics: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_fc_funnel_sequences: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_funnel_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_funnels: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fc_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_sequence_tracker: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_subscriber_meta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_fc_subscriber_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fc_subscriber_pivot: Data: 0.25MB + Index: 0.33MB + Engine InnoDB
wp_fc_subscribers: Data: 0.22MB + Index: 0.20MB + Engine InnoDB
wp_fc_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fc_url_stores: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nx_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nx_posts: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_nx_stats: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 9.33MB + Index: 0.23MB + Engine InnoDB
wp_oses_attachments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oses_clicks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_email_attachments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_emails: Data: 38.02MB + Index: 0.13MB + Engine InnoDB
wp_oses_failures: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_oses_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 11.52MB + Index: 14.03MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.59MB + Engine InnoDB
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_gsc: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_reviewx_criterias: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_reviewx_process_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_reviewx_reminder_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 4.52MB + Index: 6.03MB + Engine InnoDB
wp_users: Data: 0.25MB + Index: 0.23MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.23MB + Index: 0.20MB + Engine InnoDB
wp_wc_download_log: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.42MB + Index: 0.45MB + Engine InnoDB
wp_wc_order_stats: Data: 0.36MB + Index: 0.34MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 78
custom_css: 1
customize_changeset: 14
download: 49
elementor_library: 4
elementor_snippet: 2
email: 8
email-templates: 1
instructor: 8
nav_menu_item: 10
oembed_cache: 2
page: 12
post: 1
product: 58
revision: 39
shop_coupon: 149
shop_order: 3304
shop_order_refund: 22
user_request: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

Advanced Custom Fields: by Delicious Brains – 5.11.4
Advanced noCaptcha & invisible Captcha: by WP White Security – 6.1.7
WP Offload Media: by Delicious Brains – 2.5.6
Code Snippets: by Code Snippets Pro – 2.14.3
Dokan: by weDevs – 3.3.2
Elementor Pro: by Elementor.com – 3.5.2
Elementor: by Elementor.com – 3.4.8
FluentCRM - Marketing Automation For WordPress: by Fluent CRM – 2.3.0
FluentCRM Pro: by Fluent CRM – 2.3.1
HappyFiles: by Codeer – 1.5.1
Kadence WooCommerce Email Designer: by Kadence WP – 1.4.9
Leira Letter Avatar: by Ariel – 1.3.6
NotificationX: by WPDeveloper – 2.3.0
ReviewX: by WPDeveloper – 1.3.9
Rank Math SEO: by Rank Math – 1.0.78
Streamworks Audio: by Chris Hawkins – 4.3.6
User Switching: by John Blackbourn & contributors – 1.5.8
WooCommerce Stripe Gateway: by WooCommerce – 5.9.0
WooCommerce Google Analytics Pro: by SkyVerge – 1.11.1
WooCommerce: by Automattic – 5.9.0
WP Offload SES Lite: by Delicious Brains – 1.4.6
YITH WooCommerce Featured Video: by YITH – 1.6.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #73417 - /marketplace/
Cart: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: #4045 - /checkout/
My account: #396 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Kadence
Version: 1.1.11
Author URL: https://www.kadencewp.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 236
Oldest: 2021-11-19 16:12:42 -0800
Newest: 2021-12-11 20:30:04 -0800

Pending: 1
Oldest: 2021-12-18 20:30:04 -0800
Newest: 2021-12-18 20:30:04 -0800

### Status report information ###

Generated at: 2021-12-11 21:20:26 -08:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by saqibamin** [comment] 2021-12-13 10:22
@streamworksaudio 
Can you confirm if you saved order `$order->save();` after adding the notes and before updating the status?

**Comment by streamworksaudio** [comment] 2021-12-13 13:17
@saqibamin

Yes, the portion of my code that adds the note then sets the status to 'completed' is:

$order->add_order_note($_digital_code_order_note);
$order->save();
$order->update_status( 'wc-completed' );

The notes are saved in the order and can be seen from the order view in My Account.  It is just the emails that do not have the notes under the items.

**Comment by rodelgc** [comment] 2021-12-14 06:46
Hi @streamworksaudio,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 

If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by rodelgc** 2021-12-14 06:46 UTC
Labels: Bug, type: support request
