### ISSUE TITLE
Ampersand changed to &amp in product titles (Shop Manager)

### ISSUE THREAD

**Issue by florianmastacan** [woothemes/woocommerce#36469] opened 2023-01-17 08:29 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Product titles which contain the ampersand sign are saved correctly by Administrator but the ampersand is changed to &amp if the save action is performed by any account with the Shop Manager rights. The issue occurs for new products and also if you edit an existing product.

### Expected behavior

Saving the title (including for the edit function) should keep the & sign without changing it to &amp

### Actual behavior

If a Shop Manager is adding or editing a product which contains the ampersand in title, the ampersand is changed from & to &amp

### Steps to reproduce

1. edit a product which contains ampersand in title area (with  a Shop Manager account)
2. update the product
3. the title is changed with & being replaced by &amp

or

1. create a new product which contains ampersand in title area (with a Shop Manager account)
2. save the product
3. the title for the new created product contains &amp insteand of the regular & sign 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://woocommerce.webbing.ro
Site address (URL): https://woocommerce.webbing.ro
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.27
PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 1500
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 10.3.35-MariaDB
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: 0MX61M_
Total Database Size: 3.84MB
Database Data Size: 2.40MB
Database Index Size: 1.44MB
0MX61M_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0MX61M_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0MX61M_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0MX61M_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
0MX61M_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0MX61M_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0MX61M_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
0MX61M_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0MX61M_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0MX61M_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0MX61M_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0MX61M_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0MX61M_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0MX61M_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0MX61M_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
0MX61M_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0MX61M_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0MX61M_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0MX61M_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0MX61M_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
0MX61M_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0MX61M_options: Data: 1.47MB + Index: 0.03MB + Engine InnoDB
0MX61M_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0MX61M_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
0MX61M_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0MX61M_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0MX61M_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0MX61M_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0MX61M_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0MX61M_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
0MX61M_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
0MX61M_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0MX61M_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0MX61M_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0MX61M_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0MX61M_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0MX61M_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
0MX61M_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
0MX61M_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
0MX61M_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0MX61M_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0MX61M_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
0MX61M_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0MX61M_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
0MX61M_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
0MX61M_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 3
product: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.3.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #6 - /index.php/shop/
Cart: #7 - /index.php/cart/
Checkout: #8 - /index.php/checkout/
My account: #9 - /index.php/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-18 08:23:29 +00:00
Options: ✔
Notes: 37
Onboarding: skipped

### Action Scheduler ###

Complete: 6
Oldest: 2023-01-17 08:24:41 +0000
Newest: 2023-01-17 08:25:32 +0000

Pending: 1
Oldest: 2023-01-18 08:24:41 +0000
Newest: 2023-01-18 08:24:41 +0000

### Status report information ###

Generated at: 2023-01-17 08:25:40 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment] 2023-01-18 12:55
Hi @florianmastacan,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the  WooCommerce 7.3.0 version and WordPress 6.1.1 version. 

Please find below the screencast for reference : 

https://user-images.githubusercontent.com/94531721/213100609-289f13da-37a9-43f0-8602-695e0a27b6e7.mp4

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by kevinnoorlander** [comment] 2023-10-03 23:13
Any idea when this will be fixed? Seems like a bug to me, not an enhancement.

**Comment by coreymckrill** [comment] 2024-05-07 23:37
I suspect this is due to a longstanding issue in WordPress core: https://core.trac.wordpress.org/ticket/11311

It's not just WooCommere's product titles where this happens, but in posts, pages, and some other places as well. It's definitely not great UX, but it's something that should be fixed upstream, in WordPress, rather than in WooCommerce.

**Closed as completed by coreymckrill** 2024-05-07 23:37 UTC
Labels: Bug, Enhancement, plugin: woocommerce, type: community contribution
