### ISSUE TITLE
[Enhancement]: Allow the removal of the "WooCommerce knowledge base" blog feed Coupons screen

### ISSUE THREAD

**Issue by TimBHowe** [woothemes/woocommerce#31430] opened 2021-12-13 21:00 UTC
### Describe the solution you'd like

The "WooCommerce knowledge base" displays on the Marketing and Coupon Section of sites regardless of if you want the information or not.

This is making asset request to the https://woocommerce.com/ site for the blog feed for post and on the Coupon Screen post with the 'coupons' tag.

This still appears even when the WooCommerce > Settings > Advanced > WooCommerce.com setting for the Usage Tracking and Marketplace suggestions.

There appears to not be a back-end setting to remove this external blog feed from the backend of the site.

### Describe alternatives you've considered

Looked at dequeue the following
`add_action( 'admin_enqueue_scripts', array( $this, 'maybe_add_marketing_coupon_script' ) );`

Add a check to this function
`/**
 * Return installed marketing extensions data.
 *
 * @param \WP_REST_Request $request Request data.
 *
 * @return \WP_Error|\WP_REST_Response
 */
public function get_knowledge_base_posts( $request ) {
	$category = $request->get_param( 'category' );
	return rest_ensure_response( MarketingFeature::get_instance()->get_knowledge_base_posts( $category ) );
}
`

**Comment by datgausaigon** [comment] 2021-12-16 10:20
Hi, in current version of WooCommerce we have any solution remove/disable the "WooCommerce knowledge base"?
"WooCommerce knowledge base" "eat" some admin performance and bother my admin. Any way? Hard code, Hook, etc?
Thanks

**Comment by TimBHowe** [comment] 2021-12-17 21:04
This should remove it from the Coupons page

```php
function remove_woo_coupon_blogfeed(){
	wp_dequeue_script( 'wc-admin-marketing-coupons' );
}
add_action( 'admin_enqueue_scripts', 'remove_woo_coupon_blogfeed', 15, 1 );
```
but it really just stops the js from building the blog feed on that page and doesn't stop it from making the request to https://woocommerce.com/wp-json/wp/v2/posts?utm_medium=product

This should also probably be in the https://github.com/woocommerce/woocommerce-admin as it is part of that package but since it is core I wanted to address the issue here

**Comment by datgausaigon** [comment] 2023-07-29 17:49
Hi @TimBHowe ,
Thanks for your code. It work!!!
Love❤️

**Comment by rrennick** [comment] 2023-11-23 18:47
Closing this as a duplicate of #31462.

**Closed as completed by rrennick** 2023-11-23 18:47 UTC
Labels: Enhancement, plugin: woocommerce

**Comment by TimBHowe** [comment] 2023-11-24 12:48
I notice you close this as a duplicate, and in the other issue you mentioned that 

> Closing this as the marketing screen has been refactored.

https://github.com/woocommerce/woocommerce/issues/31462#issuecomment-1824817046

Will this be an option in the refactoring? 
What is the timeline for this?
