### ISSUE TITLE
Images don’t show all when “add/edit” Product Image (Featured Image)

### ISSUE THREAD

**Issue by datgausaigon** [woothemes/woocommerce#30679] opened 2021-09-09 03:39 UTC
Hi,

I got a issue when “add/edit” Product Image (Featured Image) for “Product” (also with Post). 
When add/edit Product Image (Featured Image), I don’t see any image in “Media library” Tab window.

Step to raise this Issue:

0. New Blank WordPress Setup (5.8.1 with PHP 8.0.10)
1. Add some images (png, jpg)
2. Add and Active WooCommerce Plugin
4. Create new Product
5. From Product Image (Featured Image) => Set image
6. I see the “Filter media” in “Media library” Tab window is set: “Images” and “All dates” => No image showing!
7. I change date filter to “September 2021” => all images in 9/2021 will show
8. I change date filter to “All dates” => all images will show
9. ===> Now I can select Image, but the first load I don't see any images?

=> On the first time select media for add/edit Product Image (Featured Image) => Don’t load image.

P/S: This issue also have with Post if use “Classic Editor” Plugin too.

Thank

**Comment by christopherdarling** [comment] 2021-09-23 13:42
Same issue here, upgrading from WP 5.7.2 to WP 5.8.1 and WC 5.5.1 > 5.6.0.

I have to 'Remove image' update, then add image.

**Comment by swatipawarGS** [comment] 2021-11-19 13:43
Hi @datverse ,

Thank you for taking the time to report this bug, we really appreciate your help. I can't reproduce it on my end using WooCommerce 5.9.0 version .

Below is the screencast documenting my experience:


https://user-images.githubusercontent.com/94531721/142632116-a1d4e92a-27b2-4920-b3cd-0a55d5a48e5b.mp4

**Comment by datgausaigon** [comment] 2021-11-21 12:48
Hi @swatipawarGS 
Thank for your reply and your video. Can you try reproduce this issue with this steps:
1. Create new Product
2. Add "Product Image" for product
3. Set Title (Product Name), ect => Save Product
4. Go to Products / All Products => Edit Product
5. In Product Image (on Edit not Create New) => Click the image to edit or update

=> We will see the issue.

I miss something, the issue raise when edit product. I tested with latest WordPress, WooCommerce and PHP 8.0.13.

Thanks

**Comment by swatipawarGS** [comment] 2021-11-23 16:17
Hi @datverse ,

Thank you for the updated information on this issue. I can reproduce it using above steps on my end using  WooCommerce 5.9.0 version and WordPress 5.8.2 version.



https://user-images.githubusercontent.com/94531721/143019858-a9069281-ee10-413e-a7c8-e0343e031750.mp4



Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by datgausaigon** [comment] 2021-11-23 17:00
Hi @swatipawarGS, 
Thank for your reply. This issue also raise with default "post" type when use classic tinymce editor. I think this is in the editor core of WordPress. You can check this issue with "post" when use "Classic Editor" plugin or enable tinymce editor for post with "Advanced Editor Tools (previously TinyMCE Advanced)" plugin. 
Thanks

**Comment by swatipawarGS** [comment] 2021-11-26 13:54
Hi @datverse ,

Thank you for the updated information. We are able reproduce the issue with "Post" on our end using WooCommerce 5.9.0 version and "Classic Editor" plugin .

Please find below screencast for reference :


https://user-images.githubusercontent.com/94531721/143572406-e2feffca-aaa8-4ed9-9d63-cbeabafd1db9.mp4


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by datgausaigon** [comment] 2021-12-09 04:56
Hi, maybe this issue fixed in WordPress 5.9

https://core.trac.wordpress.org/ticket/53765

Thanks

**Comment by peterfabian** [comment] 2022-05-19 11:12
Thanks for reporting back. I belive this has indeed been fixed in WP 5.9. Please let us know if you're still seeing the problem. Thanks!

**Closed as completed by peterfabian** 2022-05-19 11:12 UTC
Labels: plugin: woocommerce
