### ISSUE TITLE
e2e-core-tests needs build script

### ISSUE THREAD

**Issue by rrennick** [woothemes/woocommerce#31396] opened 2021-12-08 16:19 UTC
Follow up issue to #31235. We used @wordpress/deprecated in that PR. It requires using the ES6 format `import`. Prior to this the core tests package used CommonJS and didn't require a build.

**Comment by rrennick** [comment] 2021-12-09 17:39
Also, I believe the build issue in 7-gh-woocommerce/platform-private needs to be addressed before we can publish packages.

**Comment by Luc45** [comment] 2021-12-27 15:26
~@rrennick Do we want to keep that import/ES6 and come up with a build/transpile script, or do we want to remove the import/ES6?~

Nevermind, I have read the original issue and confirmed with Greg that this indeed about transpiling the files from ES6~ to ES5. Question: Do we run the tests in versions of Chrome older than Chrome 50? If this is only for the testing environment, can we assume that ES6 is available in the browser under test?

**Comment by zhongruige** [comment] 2021-12-27 20:10
WooCommerce follows WordPress for browser support (see details in [Browser support - Make WordPress Core](https://make.wordpress.org/core/handbook/best-practices/browser-support/)), so we only need to worry about testing L-2 versions of Chrome in this case, and won't be testing back to Chrome 50.

**Comment by Luc45** [comment] 2021-12-27 20:33
> WooCommerce follows WordPress for browser support (see details in [Browser support - Make WordPress Core](https://make.wordpress.org/core/handbook/best-practices/browser-support/)), so we only need to worry about testing L-2 versions of Chrome in this case, and won't be testing back to Chrome 50.

Thanks for the info! In that case, I believe that transpiling is completely optional, as we control the Chrome version through Puppetter, and we can be sure that `import` and probably all other ES6 syntax will be available, as they were released in 2015, and our minimum Puppetteer version was released in 2019.

Let me know if you think I'm missing something, and whether we should move forward with a build/transpile script after all?

**Comment by zhongruige** [comment] 2021-12-28 16:33
> as we control the Chrome version through Puppetter, and we can be sure that import and probably all other ES6 syntax will be available, as they were released in 2015, and our minimum Puppetteer version was released in 2019.

Thanks for mentioning this @Luc45! One thing to note is we are looking at moving to Playwright, which will give us [added browsers](https://playwright.dev/docs/browsers) that we can run tests against, so given that, it may still make sense to build and transpile.

Also want to loop in @rrennick on this for some further feedback before we make a decision either way.

**Comment by Luc45** [comment] 2021-12-28 16:58
@zhongruige Since I won't have other stuff going on right now, I am thinking about proceeding with the build/transpile PR for now, so we can have something done if we decide to move forward with it, as I still have to do a lot of research anyway to pull this out - I have done this before with Babel, but historically I have been primarily a PHP-focused developer, and even though I am willing and interested in getting deeper into JavaScript, I will need to do some research on how this is usually handled in other projects at Automattic, and what are the best practices around this

**Comment by zhongruige** [comment] 2021-12-28 17:13
Just noting that our other packages (e2e-utils and e2e-envrionment) both have build scripts that can be referenced as you look into this:

* https://github.com/woocommerce/woocommerce/tree/trunk/packages/js/e2e-utils
* https://github.com/woocommerce/woocommerce/tree/trunk/packages/js/e2e-environment

**Closed as completed** 2022-01-06 16:34 UTC
Labels: package: @woocommerce/e2e-core-tests
