### ISSUE TITLE
Featured Product Block: Edit product image breaks the block

### ISSUE THREAD

**Issue by shaunandrews** [woothemes/woocommerce#42380] opened 2023-05-02 19:28 UTC
When I add a **Featured Product** block to my page, and choose a product, I'm presented with an option in the toolbar to edit my feature product's Featured Image:

<img width="693" alt="CleanShot 2023-05-02 at 15 22 53@2x" src="https://user-images.githubusercontent.com/191598/235765265-10081d32-76a4-4e73-a2f7-59f6e25757cf.png">

Pressing this button in the toolbar breaks the block, and leaves me with this:

<img width="692" alt="CleanShot 2023-05-02 at 15 27 38@2x" src="https://user-images.githubusercontent.com/191598/235766024-bed4d790-ff8d-4f4f-afd3-b685e104c590.png">

Unfortunately the undo button does nothing, so I'm force to delete the broken Featured Product block.

**Comment by shaunandrews** [comment] 2023-05-02 19:31
This happens for the Featured Category block, too.

**Comment by Aljullu** [comment] 2023-05-03 06:29
Thanks for opening this issue @shaunandrews! What version of WooCommerce and WC Blocks are you using? In theory, this issue was fixed in https://github.com/woocommerce/woocommerce-blocks/pull/9142, which landed in WC Blocks 9.8.5 and 10.0.3, and [WC core 7.6.1](https://developer.woocommerce.com/2023/04/26/woocommerce-7-6-1-fix-release/). I wasn't able to reproduce it in `trunk` either.

**Comment by Aljullu** [comment] 2023-12-12 09:30
I'm going to close this issue as I can't reproduce. We can reopen it if somebody finds this issue again.

**Closed as not planned by Aljullu** 2023-12-12 09:30 UTC
Labels: Bug, Kirigami, block: featured category, block: featured product
