### ISSUE TITLE
Shortcode cart page goes blank when adding/removing coupons

### ISSUE THREAD

**Issue by c-shultz** [woothemes/woocommerce#50455] opened 2024-08-07 19:27 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Adding/removing coupon codes on shortcode cart page results in the page content disappearing. The page must be refreshed to continue. This was reproduced on two separate Jurassic Ninja sites with no plugins besides WooCommerce 9.1.4 installed.

cc @bborman22  @asumaran who discovered this issue

### Expected behavior

Coupon updates do not break cart page.

### Actual behavior

Adding/removing coupon codes on shortcode cart page results in the page content disappearing. A refresh is necessary to continue.

### Steps to reproduce

1. Create a shortcode cart page
2. Create a coupon code
3. Add product to cart
4. Apply coupon code on cart page
5. Cart page content disappears
6. Refresh page to continue

https://github.com/user-attachments/assets/557ffbc8-74dc-4f51-9d63-497a522851af

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.1.4
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/3.0.11

SUHOSIN Installed: –
MySQL Version: 10.6.18-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
page: 8
post: 2
product: 1
revision: 2
shop_coupon: 1
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
WooCommerce: by Automattic – 9.1.4

### Inactive Plugins (1) ###

Jetpack: by Automattic – 13.7-beta

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 43 KB

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/ -  Contains the woocommerce/cart block
Checkout: #8 - /checkout/ -  Contains the woocommerce/checkout block
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-08-08 19:00:00 +00:00
Options: ✔
Notes: 58
Onboarding: completed

### Action Scheduler ###

Complete: 4
Oldest: 2024-08-07 19:00:39 +0000
Newest: 2024-08-07 19:03:00 +0000

Failed: 2
Oldest: 2024-08-07 19:03:00 +0000
Newest: 2024-08-07 19:03:00 +0000

Pending: 2
Oldest: 2024-08-08 19:00:39 +0000
Newest: 2024-08-08 19:03:00 +0000


### Status report information ###

Generated at: 2024-08-07 19:23:55 +00:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by c-shultz** [comment] 2024-08-07 20:41
@wavvves @senadir report that this is a known issue when the shortcode cart page is not defined as the active cart page. 

I confirmed that updating the active cart page stops this from happening (in WooCommerce > Settings > Advanced > Page setup)

**Comment by senadir** [comment] 2024-08-07 20:53
@c-shultz if you don't mind I will close this since it's a duplicate of https://github.com/woocommerce/woocommerce/issues/44232

**Closed as not planned by senadir** 2024-08-07 20:53 UTC
Labels: Bug, Store Frontend, Rubik

**Comment by c-shultz** [comment] 2024-08-07 20:59
I was about to suggest that, @senadir. I didn't look far enough in my issue search to discover the original report. Thanks!

**Comment by senadir** [comment] 2024-08-07 21:01
No issue, it was also tricky for me to find.
