### ISSUE TITLE
Sold Individually not hiding the quantity box on 7.2.0

### ISSUE THREAD

**Issue by raifd** [woothemes/woocommerce#36007] opened 2022-12-15 09:20 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When enabling `Sold individually` under Product Data the quantity box will still display on version 7.2.0.

![Annotation on 2022-12-15 at 10-20-00](https://user-images.githubusercontent.com/23462281/207821213-502fac96-e31a-4500-9847-dfbb577d26ab.png)
![Annotation on 2022-12-15 at 10-19-51](https://user-images.githubusercontent.com/23462281/207821225-0c5a7e96-e71e-4937-85fd-1e243887b0b0.png)

### Expected behavior

As per [this closed bug report](https://github.com/woocommerce/woocommerce/pull/34282) and the behavior on the previous versions of core WooCommerce I'd expect the quantity box to not display if `Sold individually` is checked.

### Actual behavior

The quantity box still appears even though `Sold individually` is checked.

### Steps to reproduce

1. Update to 7.2.0
2. Create a simple product
3. Check `Sold individually` under **Product Data > Inventory**

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 7.2.0
REST API Version: ✔ 7.2.0
WC Blocks Version: ✔ 8.9.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.33
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.86.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.2.0
WC Database Prefix: wp_
Total Database Size: 5.04MB
Database Data Size: 2.74MB
Database Index Size: 2.30MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.08MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 0.17MB + Index: 0.16MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tec_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_tec_occurrences: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcrp_rental_products_rentals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
customize_changeset: 1
custom_css: 1
gtc_gift_card: 2
lty_lottery_ticket: 1
odr_order_bump: 1
odr_template: 1
order_shipment: 4
page: 15
post: 1
prl_engine: 1
product: 12
revision: 1
shop_coupon: 3
shop_order: 17
ticket-meta-fieldset: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce: by Automattic – 7.2.0
WP Rollback: by GiveWP.com – 1.7.2

### Inactive Plugins (105) ###

Address Field Autocomplete For WooCommerce: by wpexpertsio – 1.0.3
Advanced Flat Rate Shipping For WooCommerce: by theDotstore – 4.7.5
Akismet Anti-Spam: by Automattic – 5.0.2
Auctions for WooCommerce: by WPInstitut – 1.8
AutomateWoo: by WooCommerce – 5.5.18
B2B & Wholesale Suite: by WebWizards – 1.4.0
B2B for WooCommerce: by Addify – 2.1.0
Braintree for WooCommerce Payment Gateway: by WooCommerce – 2.8.0 (update to version 2.9.0 is available)
Bulk Discounts for WooCommerce: by Plugify – 1.0.5
Bulk Table Editor for WooCommerce: by Consortia – 2.2.19
Check Conflicts: by ioannup – 1.1.4
Checkout Fields Manager: by Addify – 1.0.0
Code Snippets: by Code Snippets Pro – 3.2.2
Conditional Checkout Fields for WooCommerce: by FME Addons – 1.2.0
Conditional Coupons for WooCommerce: by SKROTRON – 1.0.1
Cost Calculator Builder: by StylemixThemes – 3.1.0
Customer Upload Files for WooCommerce: by FME Addons – 1.1.0
Custom Stock Quantity Multiplier for WooCommerce: by E-Plugins – 1.0.0
Custom User Registration Fields for WooCommerce: by Addify – 1.7.8
Discounts for WooCommerce Subscriptions: by Meow Crew – 2.3.0
Event Tickets: by Modern Tribe
Inc. – 4.10.10.1

Event Tickets Plus: by Modern Tribe
Inc. – 4.10.10

Extra Fees for WooCommerce: by FantasticPlugins – 3.6
Free Gifts for WooCommerce: by FantasticPlugins – 8.4
Gift Card By Aheadworks: by Aheadworks – 1.0.0
Gift Card Product for Woocommerce: by Adam Husar/Pixel Hero – 1.18
Gift Cards Pro for WooCommerce: by FantasticPlugins – 3.3
Jetpack: by Automattic – 11.7-a.3
Jetpack Boost: by Automattic - Website Speed and Performance team – 1.5.1
Loco Translate: by Tim Whitlock – 2.6.3
Lottery for WooCommerce: by FantasticPlugins – 7.2
Order Bump for WooCommerce: by FantasticPlugins – 2.7
Page Optimize: by Automattic – 0.5.2
Product Brands for WooCommerce: by WP1 – 1.2.8
Product Designer for WooCommerce: by FantasticPlugins – 4.2
Product Filters for WooCommerce: by WooCommerce – 1.3.8
Product Variations Table Listing: by Addify – 1.0.2
Quantity Discounts & Pricing For Woocommerce: by Plugify – 4.0.2
Rental Products: by 99w – 4.0.2
Say What?: by Ademti Software – 2.1.2
Smart Bulk Variations: by HighAddons – 1.0.2
Storefront Powerpack: by WooCommerce – 1.6.1
String Locator: by InstaWP – 2.6.0
Swiss Post: by FirstPoint Sàrl – 1.3
The Events Calendar: by Modern Tribe
Inc. –

The Events Calendar PRO: by Modern Tribe
Inc. – 4.7.9

Tiered Price Table for WooCommerce: by U2Code – 4.6.0
Top Bar for WooCommerce: by Addify – 1.2.5
WC Shipping Rates Importer: by joesat – 1.1.0
WCS staging: by mb – 1.0
WooCommerce Admin: by WooCommerce – 3.3.2
WooCommerce Advanced Notifications: by WooCommerce – 1.4.0
WooCommerce Blocks: by Automattic – 8.9.1
WooCommerce Box Office: by WooCommerce – 1.1.45
WooCommerce Brands: by WooCommerce – 1.6.36
WooCommerce Bulk Variations: by Lucas Stark – 1.6.9
WooCommerce Buy One Get One Free: by Oscar Gare – 3.6.0
WooCommerce Checkout Add-Ons: by SkyVerge – 2.5.7
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.4
WooCommerce Composite Products: by WooCommerce – 8.5.2
WooCommerce Conditional Shipping and Payments: by WooCommerce – 1.14.4
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.10.4
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.3.5
WooCommerce Deposits: by WooCommerce – 1.5.11
WooCommerce Distance Rate Shipping: by WooCommerce – 1.2.0
WooCommerce Dynamic Pricing: by Element Stark – 3.1.28
WooCommerce EU VAT Number: by WooCommerce – 2.4.3
WooCommerce FedEx Shipping: by WooCommerce – 3.5.0
WooCommerce Gift Cards: by WooCommerce – 1.15.0
WooCommerce Local Pickup Plus: by SkyVerge – 2.9.12
WooCommerce Measurement Price Calculator: by SkyVerge – 3.20.1
WooCommerce Memberships: by SkyVerge – 1.23.1
WooCommerce Min/Max Quantities: by WooCommerce – 4.0.4
WooCommerce Order Status Logger: by @billrobbins – 0.1
WooCommerce PayFast Gateway: by WooCommerce – 1.4.19 (update to version 1.5.0 is available)
WooCommerce Payments: by Automattic – 5.0.3 (update to version 5.1.2 is available)
WooCommerce PayPal Payments: by WooCommerce – 1.9.5 (update to version 2.0.1 is available)
WooCommerce PDF Invoices: by Andrew Benbow – 4.15.6
WooCommerce Points and Rewards: by WooCommerce – 1.7.22
WooCommerce Pre-Orders: by WooCommerce – 1.7.3
WooCommerce Price Based on Country (Basic): by Oscar Gare – 2.2.5
WooCommerce Product Add-ons: by WooCommerce – 5.0.0
WooCommerce Product Bundles: by WooCommerce – 6.16.1
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.49
WooCommerce Product Recommendations: by WooCommerce – 2.2.0
WooCommerce Product Vendors: by WooCommerce – 2.1.69
WooCommerce Shipment Tracking: by WooCommerce – 1.7.0
WooCommerce Shipping & Tax: by WooCommerce – 2.0.0 (update to version 2.1.0 is available)
WooCommerce Shipping Per Product v2: by WooCommerce – 2.4.0
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.8.0
WooCommerce Smart Coupons: by StoreApps – 6.7.0
WooCommerce Square: by WooCommerce – 3.3.0 (update to version 3.4.1 is available)
WooCommerce Stamps.com API integration: by WooCommerce – 1.7.1
WooCommerce Store Credit: by Themesquad – 4.2.3
WooCommerce Stripe Gateway: by WooCommerce – 7.0.1
WooCommerce Subscriptions: by WooCommerce – 4.6.0
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.37
WooCommerce USPS Shipping: by WooCommerce – 4.5.0
WooCommerce Zapier: by OM4 Software – 2.3.1
WP Crontrol: by John Blackbourn & crontributors – 1.14.0
WP Downgrade | Specific Core Version: by Reisetiger – 1.2.5
WPFront Scroll Top: by Syam Mohan – 2.0.7.08086
WP phpMyAdmin: by Puvox.software – 5.2.0.7
WP Reset: by WebFactory Ltd – 1.95
Zapier for WordPress: by Zapier – 1.0.4

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
gift_card (gift_card)
grouped (grouped)
lottery (lottery)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-12-16 08:55:38 +00:00
Options: ✔
Notes: 52
Onboarding: skipped

### Action Scheduler ###

Complete: 164
Oldest: 2022-11-18 08:57:41 +0000
Newest: 2022-12-15 09:13:56 +0000

Pending: 2
Oldest: 2022-12-15 09:19:02 +0000
Newest: 2022-12-15 11:58:24 +0000

Failed: 3
Oldest: 2022-12-05 08:39:27 +0000
Newest: 2022-12-05 08:40:30 +0000

### Status report information ###

Generated at: 2022-12-15 09:18:19 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by DSCreative** [comment] 2022-12-15 10:43
Can confirm i'm seeing the same issue with this.

**Comment by syhussaini** [comment] 2022-12-15 12:38
As a workaround, I used the following custom CSS code.

```
.quantity {
    display: none;
}
```

 #5791973-zen

**Comment by DSCreative** [comment] 2022-12-15 12:54
It might actually be better to use:

`.sold-individually .quantity {
    display: none;
}`

Otherwise quantity boxes for products which are not set to be sold individually will be hidden as well.

**Comment by fredchandler** [comment] 2022-12-15 13:34
The code that hides the quantity input

`function woo_remove_all_quantity_fields( $return, $product ) {
  return true;
}
add_filter( 'woocommerce_is_sold_individually', 'woo_remove_all_quantity_fields', 10, 2 );`

Not works anymore after update 7.2.0

**Comment by swatipawarGS** [comment] 2022-12-16 13:38
Hi @raifd,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the  WooCommerce 7.2.0 version and WordPress 6.1.1 version. 

Please find below the screenshots for reference :

![#36007(backend)](https://user-images.githubusercontent.com/94531721/208039306-4ae70d08-9c30-4ded-9bde-34b371dda6c7.jpg)

![#36007(productpage))](https://user-images.githubusercontent.com/94531721/208039311-864ec64d-852f-42d3-aaa2-70aac5ed9370.jpg)



Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by raifd** [comment] 2022-12-16 13:51
Thank you for taking a closer look at this @swatipawarGS I have not taken a closer look but my guess is, it might be related [to the recent change with min/max quantities](https://github.com/woocommerce/woocommerce/releases/tag/7.2.0#:~:text=Make%20qty%20input%20box%20visible%20when%20min_qty%20%3D%20max_qty%20by%20%40kirtangajjar%20in%20%2334282).

**Comment by daveloodts** [comment] 2022-12-20 09:04
Thanks for following up this bug. I was hoping that 7.2.1 got a fix for this, but don't seem like it.
I do hope a solution comes quick, cause a lot of customers (store owners) of us use this sold-individually feature. Therefore we postpone all the WooCommerce updates to 7.2.x

Any idea when there will be a fix for this?

**Comment by barryhughes** [comment] 2022-12-22 17:28
> I have not taken a closer look but my guess is, it might be related [to the recent change with min/max quantities](https://github.com/woocommerce/woocommerce/releases/tag/7.2.0#:~:text=Make%20qty%20input%20box%20visible%20when%20min_qty%20%3D%20max_qty%20by%20%40kirtangajjar%20in%20%2334282).

That's correct. There were inconsistencies in terms of how the quantity input renders across a couple of scenarios, so the idea was to render it in a more consistent fashion, albeit set it to 'readonly' in cases where it should not be changed (sold individually being one of those).

The idea was simply to make it obvious to customers that the quantity they are purchasing is one (or, a higher but still unchangeable quantity, in other contexts). Of course, based on the discussion here it seems that is not optimal in all cases.

> Therefore we postpone all the WooCommerce updates to 7.2.x

There are various CSS workarounds that can be applied, as noted above, and it is generally safe and easy to apply them. Though, I of course understand that may not be something that everyone is comfortable with.

> Any idea when there will be a fix for this?

We can't offer any guarantees: this isn't critical in the sense of it breaking sites, and let's also remember it may in fact be desirable for other merchants (who wouldn't have a reason to comment here).

I'll apply our high priority tag, though, and we'll set some time aside to think about the best way forward.

**Comment by ludovicsclain** [comment] 2022-12-22 18:58
> let's also remember it may in fact be desirable for other merchants (who wouldn't have a reason to comment here).

I do not understand the logic of leaving a quantity field in front if it is not modifiable, both on the checkout page and on the cart page, there is nothing desirable for me in there :)

**Comment by barryhughes** [comment] 2022-12-22 20:07
Well, one reason could be for consistency and to reduce confusion (such as in a store where only a subset of products are sold individually). To be clear, though, I'm not stating that we will not make a change—only that there are a range of opinions, and selling scenarios, to consider :-)

**Comment by leandroprz** [comment] 2022-12-24 16:32
I'm also experiencing this issue in v7.2.2.

**Comment by ghost** [comment] 2022-12-29 11:41
Please fix this issue. Still relevant in 7.2.2.

**Comment by ghost** [comment] 2022-12-29 11:45
The quantity field should be hidden when you set a product to be sold individually, but it appears this is no longer the case. So this is a bug. It is essential for stores selling digital goods.

**Comment by kaushikasomaiya** [comment] 2023-01-03 09:11
5832368-zen
5824289-zen

**Comment by daveloodts** [comment] 2023-01-07 08:24
Very sad and upset to see this is not fixed in 7.3. 
There is absolutely no case or example why the quantity field must be displayed; when in fact it's pretty useless. You can click on it, but it won't count up or down. In other words: it causes enormous friction for the buyer and extra work for the store owner te reply those "stock"-quantity questions.
Don't break what isn't broken, and more baffled that this isn't probably a major thing to fix.

So again, please fix this in 7.3. We probably won't update over 7.2 because of this bug; cause we are pretty sure our store owners won't like it. We represent 50 stores.

**Closed as completed** 2023-01-10 08:50 UTC
Labels: Bug, plugin: woocommerce, type: community contribution

**Comment by francoishvz** [comment] 2023-01-10 09:49
38318511-hc

**Comment by Swaps4** [comment] 2023-01-12 05:27
Here's a temporary fix using CSS:

.sold-individually .quantity {
	display: none;
}

**Comment by helgatheviking** [comment] 2023-01-13 15:34
> set it to 'readonly' in cases where it should not be changed (sold individually being one of those).

Personally I think this is frustrating since there's no explanation to the customer as to _why_ they can't change on it. I have customers asking me how to hide the quantity input all the time as there are plenty of use cases where it's irrelevant, distracting, or otherwise unwanted. So this feels like a reversion to me and hopefully you'll consider going back to actually hiding the input when min = max = 1.

**Comment by barryhughes** [comment] 2023-01-13 17:12
> Hopefully you'll consider going back to actually hiding the input when min = max = 1.

Yes, to clarify: a [change was merged](https://github.com/woocommerce/woocommerce/pull/36350) that will hide the input when products are sold individually.

**Comment by helgatheviking** [comment] 2023-01-13 18:01
Thanks @barryhughes I just pulled that in and ran `pnpm build`. And while there's every the build tools are failing with me (any day that ends in Y) this isn't solving it for me with Twenty twenty three theme. 

Any reason we can't revert back to a hidden input?

**Comment by barryhughes** [comment] 2023-01-13 19:01
Hi @helgatheviking,

> And while there's every the build tools are failing with me (any day that ends in Y) this isn't solving it for me with Twenty twenty three theme.

Yes, the build process is in some ways 'heavier' than it used to be and problems can surface/sometimes it may not complete, depending on available resources.  That said, it does seem to work for me (with Twenty-Twenty Three):

![2023-qty-input](https://user-images.githubusercontent.com/3594411/212397369-4d56f40b-db9e-436d-a214-c8c439337ac9.png)

I'm not sure what system you are using for development, but if Grep is available and (from the root of the built plugin directory) you were to run:

```sh
grep sold-individually assets/css/twenty-twenty-three.css
```

Do you see output like the following (if so, the problem may be browser caching) or nothing at all (in which case, probably the build process failed to complete)?

<img width="1006" alt="grep-sold-indiv" src="https://user-images.githubusercontent.com/3594411/212397871-4453939f-3d32-4cba-9c8d-b9abf0414821.png">

> Any reason we can't revert back to a hidden input?

The original change, which was intended as an enhancement, has (as the above conversation shows) created a large disturbance—which of course was not at all the intention. We'll have a think about setting the type attribute back to `hidden` for these cases (though, I'd still be interested to know if the issue with Twenty Twenty Three was perhaps build related, or a caching problem, or if actually there is a further dimension we missed).

**Comment by helgatheviking** [comment] 2023-01-13 19:19
Thanks @barryhughes I just pulled that in and ran `pnpm build`. And while there's every the build tools are failing with me (any day that ends in Y) this isn't solving it for me with Twenty twenty three theme. 

![image](https://user-images.githubusercontent.com/507025/212401067-4e865c17-692e-4792-b4f7-3a050e14ec39.png)


Any reason we can't revert back to a hidden input?

**Comment by helgatheviking** [comment] 2023-01-13 20:01
>Yes, the build process is in some ways 'heavier' than it used to be and problems can surface/sometimes it may not complete, depending on available resources. 

I fight with the build tools on a near daily basis. hasn't been fun for me, but it looks like it was caching this time :)

Going to have negative implications for my mix and match plugin (And therefore presumably Composite Products and Product Bundles) as it's is hiding my inputs if the box/container/main product is sold individually (folks commonly use that to hide the main quantity input)

![image](https://user-images.githubusercontent.com/507025/212408840-9aa849e0-0ad4-4996-813c-4adb92dacca4.png)

**Comment by barryhughes** [comment] 2023-01-13 20:05
That's good feedback, thanks. You're using `woocommerce_before_quantity_input_field` (or the `*_after_*` version) for that?

**Comment by helgatheviking** [comment] 2023-01-13 20:10
Neither... I just call `woocommerce_quantity_input()` inside a loop of all the child products. Similar to how Grouped Products work I think... except Grouped product disable the option for selling individually. I wouldn't want to do that since my users frequently use "sold individually" to intentionally hide the main quantity next to the add to cart button. 

I have another issue https://github.com/woocommerce/woocommerce/issues/32094 asking to wrap the quantity input and button in some kind of wrapping div themes can eventually use to `display: flex` the two elements without breaking my plugins so much. if implemented it would be easier to target that _specific_ quantity input. but there's a lot of support issues guaranteed with outdated themes.

**Comment by helgatheviking** [comment] 2023-01-16 19:03
Another option, could you put the `sold-individually` class on the quantity itself? Though I think that might still interfere with Mix and Match where a sold individually child item is displayed as a check box. Hmmm :thinking: I think I am partial to the hidden input myself.

**Comment by barryhughes** [comment] 2023-01-16 19:31
> Hmmm 🤔 I think I am partial to the hidden input myself.

Yep, I think we can do that and still meet some of the objectives of the original PR that introduced the change.
