### ISSUE TITLE
Misplaced Home link in new navigation

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#32912] opened 2022-05-09 03:37 UTC
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

<img src="https://user-images.githubusercontent.com/3747241/167336210-c05e12ea-606d-4eea-95fa-e0fa2a29ce60.png" width="200">

Discovered by @becdetat and successfully reproduced in a JN site.

### Expected behavior

The Home link should be located as the first item under "WooCommerce" section

### Actual behavior

Located under "Extensions" section

### Steps to reproduce

1. Go to Settings > Advanced
2. Enable new navigation
3. Go to WooCommerce
4. Observe the Home link

### WordPress Environment

WC 6.4.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by mattsherman** [comment] 2022-05-17 00:59
@ilyasfoo @becdetat I cannot reproduce this on JN with WC 6.5.1. Do you have any additional details on how to reproduce this? Would you be able to check if you can still reproduce it with EC 6.5.1? 

<img width="233" alt="Screen Shot 2022-05-16 at 20 58 25" src="https://user-images.githubusercontent.com/2098816/168705936-63f67725-6d43-4bb3-90ef-f95de4fde2a1.png">

**Comment by ilyasfoo** [comment] 2022-05-17 03:34
@mattsherman Thanks for checking, I confirm this isn't reproducible in 6.5.1. Closing

**Comment by mattsherman** [comment] 2022-05-26 17:36
Reopening this, as @pmcpinto and @verofasulo have run across this. If either of you can provide more details that would help us to narrow this done, please share!

**Comment by mattsherman** [comment] 2022-05-26 23:13
This might only manifest itself on WordPress.com eCommerce plan sites.

**Comment by verofasulo** [comment] 2022-05-27 14:44
> Reopening this, as @pmcpinto and @verofasulo have run across this. If either of you can provide more details that would help us to narrow this done, please share!

@mattsherman happy to help - which details do you need to investigate further?

**Comment by joshuatf** [comment] 2022-05-27 17:39
I'm only able to reproduce this issue on 6.4.1.  When upgrading to the latest version of WC, this is no longer an issue.

I think we can safely close this issue since the ecomm plans use 6.4.1 currently and will be fixed once those versions are bumped.  cc @pmcpinto and @verofasulo in case there are other ways to reproduce.

**Comment by joshuatf** [comment] 2022-06-07 13:12
Double checking with @pmcpinto and @verofasulo one more time before closing this issue.

**Comment by pmcpinto** [comment] 2022-06-08 08:07
I wasn't able of finding another way to reproduce this. I think it's ok to close the issue. Thanks for checking this.

**Comment by becdetat** [comment] 2022-06-09 04:35
I've just checked the eCommerce site that I first noticed this in and can confirm that the Home link is now in the correct place, so the version must have been bumped. Thanks everyone for looking into this :-)

**Comment by mattsherman** [comment] 2022-06-10 19:35
Closing this issue, based on the discussion.

**Closed as completed by mattsherman** 2022-06-10 19:35 UTC
Labels: Bug, plugin: woocommerce
