### ISSUE TITLE
2.6 REST API error retrieving orders by multiple statuses [API]

### ISSUE THREAD

**Issue by tdittmar** [woothemes/woocommerce#11676] opened 2016-08-11 07:27 UTC
## EXPLANATION OF THE ISSUE

In version 2.5 and in 2.6 using the old API it was possible to filter orders by multiple statuses comma-separating them in the `status` parameter.

The new API returns an error if I try that saying that `status is not one of any, pending, processing ...`.

Is this a bug? Is this kind of filtering still possible? Did I miss something?

**Comment by mikejolley** [comment] 2016-08-12 10:25
This is not possible in the new API. The valid statuses are validated here https://github.com/woothemes/woocommerce/blob/efd390e9510d168ae730b05504225aa21b2a99cc/includes/api/class-wc-rest-orders-controller.php#L1789

Pinging @claudiosmweb to see if this is something we want to include in an update, but this is not a bug so I will close it out.

Also documented here https://woothemes.github.io/woocommerce-rest-api-docs/#list-all-orders

**Closed by mikejolley** 2016-08-12 10:25 UTC

**Comment by tdittmar** [comment] 2016-08-15 13:21
Thanks for clearing this up. I'd just like to add that this is really a breaking change, as with the new API you actually need to make 3 REST calls when one was enough with the old API.

**Comment by EvolutionSigns** [comment] 2017-02-02 15:11
I have to agree with tdittmar - it would be very helpful to be able to either filter by multiple statuses or exclude a status in the API call.

**Comment by andyslack** [comment] 2017-11-28 12:51
Agree with tdittmar, this is a must!!

**Comment by mikejolley** [comment] 2017-12-04 12:49
It's part of v3 api (unreleased).
