### ISSUE TITLE
QUESTION : Composer and Packagist

### ISSUE THREAD

**Issue by DobbyZer** [woothemes/woocommerce#31627] opened 2022-01-12 19:16 UTC
Hello all,

I have some question. I install my website with bedrock template. But i dont find some plugin like Woocomerce Payment / Subscription on packagist.

Do you have any information and help to resolve this problem ?

Thank's

**Comment by lanej0** [comment] 2022-01-12 22:43
Hi @DobbyZer ,
﻿
While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
﻿
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
﻿
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
﻿
If you confirm the bug, please provide us with clear steps to reproduce it.
﻿
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by lanej0** 2022-01-12 22:43 UTC
Labels: type: support request

**Comment by andfinally** [comment] 2023-07-04 08:57
Hi @DobbyZer, that's right – those plugins aren't available on Packagist – also, we have no immediate plans to add support for Composer installation.

**Comment by szepeviktor** [comment] 2023-08-09 19:58
@DobbyZer There are many ways to install software with Composer not available on Packagist.
https://github.com/szepeviktor/composer-managed-wordpress/blob/master/README.md#package-types
