### ISSUE TITLE
RemoteInboxNotifications ArrayColumn parameter error

### ISSUE THREAD

**Issue by Jonas18175** [woothemes/woocommerce#30773] opened 2021-09-22 10:37 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

A php warning:
Warning: array_column() expects parameter 1 to be array, string given in /bitnami/wordpress/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/RemoteInboxNotifications/Transformers/ArrayColumn.php on line 27

Results in a 502 Error in my docker wp container (On woocommerce setting page)

WP Version 5.8.1

**Expected behavior**
Settings Page working.

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
Woocommerce Setting Page

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): *retracted*
Site address (URL): *retracted*
WC Version: 5.7.0
REST API Version: ✔ 5.7.0
WC Blocks Version: ✔ 5.7.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.6.4
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE_formal
External object cache: –

### Server Environment ###

Server Info: nginx/1.21.3
PHP Version: 7.4.23
PHP Post Max Size: 800 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 8.0.22-13.1
Max Upload Size: 800 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.7.0
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 4.82MB
Datenbank-Datengröße: 3.38MB
Datenbank-Indexgröße: 1.44MB
wp_woocommerce_sessions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_addonlibrary_addons: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_addonlibrary_categories: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Daten: 2.47MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
elementor_library: 1
page: 7
post: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Elementor Pro: von Elementor.com – 3.0.6
Elementor: von Elementor.com – 3.4.4
ElementsKit Lite: von Wpmet – 2.3.6
Error Log Monitor: von Janis Elsts – 1.7
Essential Addons for Elementor: von WPDeveloper – 4.9.1
Flexible Elementor Panel: von WebMat – 2.3.7
Loco Translate: von Tim Whitlock – 2.5.3
SiteOrigin CSS: von SiteOrigin – 1.3.2
Unlimited Elements for Elementor: von Unlimited Elements – 1.4.82
WooCommerce: von Automattic – 5.7.0

### Inactive Plugins (6) ###

Akismet Anti-Spam: von Automattic – 4.1.9
All in One SEO: von All in One SEO Team – 4.1.0.2
AMP: von AMP Project Contributors – 2.0.11
AWS for WordPress: von AWS Labs
WP Engine – 4.3.1

Google Analytics for WordPress by MonsterInsights: von MonsterInsights – 7.17.0
WP Mail SMTP: von WPForms – 3.0.3

### Must Use Plugins (3) ###

client-side-image-resize.php: von  –
proxy.php: von  –
webp_activate.php: von  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #19 - /shop/
Warenkorb: #22 - /cart/
Kasse: #25 - /checkout/
Mein Konto: #28 - /my-account/
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: Hello Elementor
Version: 2.4.1
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – Wenn Sie WooCommerce mit einem Theme
das Sie nicht selbst entwickelt haben
an eigene Bedürfnisse anpassen
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie Sie ein Child-Theme erstellen (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Abgebrochen: 1
Oldest: 2021-09-22 09:44:36 +0000
Newest: 2021-09-22 09:44:36 +0000

Abgeschlossen: 3
Oldest: 2021-09-22 09:44:36 +0000
Newest: 2021-09-22 09:56:59 +0000

### Status report information ###

Generated at: 2021-09-22 10:35:05 +00:00
`
</details>

**Comment by rodelgc** [comment] 2021-09-22 16:09
Hi @Jonas18175 ,

Thank you for raising the issue. However, I can’t reproduce it on my end.

I can access the WooCommerce Settings just fine on WC 5.7.0:

<img width="973" alt="Screen Shot 2021-09-23 at 12 07 12 AM" src="https://user-images.githubusercontent.com/4509348/134380919-87f7152f-883d-4a4f-b211-68188f1ef6bf.png">

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

For the meantime, I'm closing the issue. Please add a comment if you think I missed something. Thanks!

**Closed as completed by rodelgc** 2021-09-22 16:09 UTC
Labels: Bug, type: support request

**Comment by Jonas18175** [comment] 2021-09-24 11:24
I use WP 5.8.1, not 5.7.0 - I run that in a fresh Container. I tested it now with the Storefront Theme, but its the same error.
/reopen

**Comment by twwn** [comment] 2021-10-19 14:44
We're getting the same error since moving to PHP8(.0.10). WP 5.8.1, WC 5.8.0.

```
2021-10-18T10:03:54+00:00 CRITICAL Uncaught TypeError: array_column(): Argument #1 ($array) must be of type array, string given in …/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/RemoteInboxNotifications/Transformers/ArrayColumn.php:27
Stack trace:
#0 …/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/RemoteInboxNotifications/Transformers/ArrayColumn.php(27): array_column()
#1 …/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/RemoteInboxNotifications/TransformerService.php(59): Automattic\WooCommerce\Admin\RemoteInboxNotifications\Transformers\ArrayColumn->transform()
#2 …/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/RemoteInboxNotifications/OptionRuleProcessor.php(45): Automattic\WooCommerce\Admin\RemoteInboxNotifications\TransformerService::apply()
#3 …/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/RemoteInboxNotifications/RuleEvaluator.php(62): Automattic\WooCommerce\Admin\RemoteInboxNotifications\OptionRuleProcessor->process()
#4 …/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/RemoteFreeExtensions/EvaluateExtension.php(27): Automattic\WooCommerce\Admin\RemoteInboxNotifications\RuleEvaluator->evaluate()
#5 …/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/RemoteFreeExtensions/Init.php(48): Automattic\WooCommerce\Admin\Features\RemoteFreeExtensions\EvaluateExtension::evaluate()
#6 …/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/OnboardingFreeExtensions.php(75): Automattic\WooCommerce\Admin\Features\RemoteFreeExtensions\Init::get_extensions()
#7 …/wp-includes/rest-api/class-wp-rest-server.php(1140): Automattic\WooCommerce\Admin\API\OnboardingFreeExtensions->get_available_extensions()
#8 …/wp-includes/rest-api/class-wp-rest-server.php(987): WP_REST_Server->respond_to_request()
#9 …/wp-includes/rest-api/class-wp-rest-server.php(414): WP_REST_Server->dispatch()
#10 …/wp-includes/rest-api.php(370): WP_REST_Server->serve_request()
#11 …/wp-includes/class-wp-hook.php(303): rest_api_loaded()
#12 …/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#13 …/wp-includes/plugin.php(518): WP_Hook->do_action()
#14 …/wp-includes/class-wp.php(388): do_action_ref_array()
#15 …/wp-includes/class-wp.php(750): WP->parse_request()
#16 …/wp-includes/functions.php(1291): WP->main()
#17 …/wp-blog-header.php(16): wp()
#18 …/index.php(17): require('...')
#19 {main}
  thrown in …/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/RemoteInboxNotifications/Transformers/ArrayColumn.php in line 27
```

**Comment by cambiph** [comment] 2021-12-17 09:50
Having the same error:

```
2021-12-17T09:29:40+00:00 CRITICAL Uncaught TypeError: array_column(): Argument #1 ($array) must be of type array, string given in /customers/3/7/8/xxxx/httpd.www/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/RemoteInboxNotifications/Transformers/ArrayColumn.php:27
Stack trace:
#0 /customers/3/7/8/xxxx/httpd.www/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/RemoteInboxNotifications/Transformers/ArrayColumn.php(27): array_column('', 'slug')
#1 /customers/3/7/8/xxxx/httpd.www/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/RemoteInboxNotifications/TransformerService.php(59): Automattic\WooCommerce\Admin\RemoteInboxNotifications\Transformers\ArrayColumn->transform('', Object(stdClass), '')
#2 /customers/3/7/8/xxxx/httpd.www/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/RemoteInboxNotifications/OptionRuleProcessor.php(45): Automattic\WooCommerce\Admin\RemoteInboxNotifications\TransformerService::apply('', Array, '')
#3 /customers/3/7/8/xxxx/httpd.www/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/RemoteInboxNotifications/RuleEvaluator.php(62): Automattic\WooCommerce\Admin\RemoteInboxNotifications\OptionRuleProcessor->process(Object(stdClass), NULL)
#4 /customers/3/7/8/xxxx/httpd.www/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/RemoteFreeExtensions/EvaluateExtension.php(27): Automattic\WooCommerce\Admin\RemoteInboxNotifications\RuleEvaluator->evaluate(Array)
#5 /customers/3/7/8/xxxx/httpd.www/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/RemoteFreeExtensions/Init.php(48): Automattic\WooCommerce\Admin\Features\RemoteFreeExtensions\EvaluateExtension::evaluate(Object(stdClass))
#6 /customers/3/7/8/xxxx/httpd.www/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/OnboardingFreeExtensions.php(75): Automattic\WooCommerce\Admin\Features\RemoteFreeExtensions\Init::get_extensions()
#7 /customers/3/7/8/xxxx/httpd.www/wp-includes/rest-api/class-wp-rest-server.php(1140): Automattic\WooCommerce\Admin\API\OnboardingFreeExtensions->get_available_extensions(Object(WP_REST_Request))
#8 /customers/3/7/8/xxxx/httpd.www/wp-includes/rest-api/class-wp-rest-server.php(987): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wc-admin/onboa...', Array, NULL)
#9 /customers/3/7/8/xxxx/httpd.www/wp-includes/rest-api/class-wp-rest-server.php(414): WP_REST_Server->dispatch(Object(WP_REST_Request))
#10 /customers/3/7/8/xxxx/httpd.www/wp-includes/rest-api.php(370): WP_REST_Server->serve_request('/wc-admin/onboa...')
#11 /customers/3/7/8/xxxx/httpd.www/wp-includes/class-wp-hook.php(303): rest_api_loaded(Object(WP))
#12 /customers/3/7/8/xxxx/httpd.www/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#13 /customers/3/7/8/xxxx/httpd.www/wp-includes/plugin.php(518): WP_Hook->do_action(Array)
#14 /customers/3/7/8/xxxx/httpd.www/wp-includes/class-wp.php(388): do_action_ref_array('parse_request', Array)
#15 /customers/3/7/8/xxxx/httpd.www/wp-includes/class-wp.php(750): WP->parse_request('')
#16 /customers/3/7/8/xxxx/httpd.www/wp-includes/functions.php(1291): WP->main('')
#17 /customers/3/7/8/xxxx/httpd.www/wp-blog-header.php(16): wp()
#18 /customers/3/7/8/xxxx/httpd.www/index.php(17): require('/customers/3/7/...')
#19 {main}
  thrown in /customers/3/7/8/xxxx/httpd.www/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/RemoteInboxNotifications/Transformers/ArrayColumn.php op de lijn 27
```
