### ISSUE TITLE
 it’s not show the messages wc_add_notice() but when invoke wc_print_notices(); show in 3 different places the same message

### ISSUE THREAD

**Issue by norud** [woothemes/woocommerce#44862] opened 2024-02-21 18:41 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I was using wc_add_notice() to show messages, right now I’m upgrading a plug-in with WOO 8.6.0 (with blocks as default) and StorefrontVersión: 4.5.4 but right now it’s not show the message, when invoke wc_print_notices(); show in 3 different places the same message.
I try wc_print_notice() for single, but doesn’t work because is one notice at 3 different places.

i have to make the plugins compatible with checkout blocks
i'm facing the challenge to display payment error after redirect, in previous version was working fine wc_add_notice before blocks

![image](https://github.com/woocommerce/woocommerce/assets/46699973/1b0440c6-6ddb-4cea-8294-7763f18d37c7)

Also when the order is modify from FE and make:
`
$this->order->update_status( 'pending' );
$this->order->save();
`
the order is not show at Orders sidebar menu, 
![image](https://github.com/woocommerce/woocommerce/assets/46699973/06d0d60d-4946-4ee3-aa86-1f9494d023ab)

but is show it from Analytic sidebar menu Order
![image](https://github.com/woocommerce/woocommerce/assets/46699973/416924d1-40d1-4599-ab00-1720a6dbd0c7)

or editing one of the order exist an change the id:
`{{webUrl}}/wp-admin/admin.php?page=wc-orders&action=edit&id={{hidden_order_id}}`

thanks

### Expected behavior

- show one message.
- show the order on the Order sidebar menu not only at Analytic sidebar menu.

### Actual behavior

- show in 3 different places the same message.
- not show the order on the Order sidebar menu.

### Steps to reproduce

1. new WP installations
2. install woo
3. use dummy getaway to use wc_add_notice($message, $error_type); and try to see the error, for me is not show it i force with  wc_print_notices(); which show in 3 different places same message.
4. for order hidden have to make some modifications from FE such create the order as draft and them update at BE with: `$this->order->update_status( 'pending' ); $this->order->save();`

### WordPress Environment

<details>
<summary>System Status Report</summary>

```

<html>
<body>
<!--StartFragment-->
Entorno WordPress
--
Dirección de WordPress (URL): |   | https://tilopay-plugin-wp.test
Dirección del sitio (URL): |   | https://tilopay-plugin-wp.test
Versión de WooCommerce: |   | 8.6.0
Paquete de la REST API de WooCommerce: |   | 8.6.0 C:\laragon\www\tilopay-plugin-wp\wp-content\plugins\woocommerce\includes
WooCommerce Blocks package: |   | 11.8.0-dev C:\laragon\www\tilopay-plugin-wp\wp-content\plugins\woocommerce/
Action Scheduler package: |   | 3.7.1 C:\laragon\www\tilopay-plugin-wp\wp-content\plugins\woocommerce\packages\action-scheduler
Directorio de registros con permiso de escritura: |   | C:\laragon\www\tilopay-plugin-wp/wp-content/uploads/wc-logs/
Versión de WordPress: |   | 6.4.3
WordPress multisitio: |   | –
Límite de memoria de WordPress: |   | 24 GB
Modo de depuración de WordPress: |   |  
Cron de WordPress: |   |  
Idioma: |   | es_CR
Caché externa de objetos: |   | –

<!--EndFragment-->
</body>
</html>Entorno WordPress
Dirección de WordPress (URL):		https://tilopay-plugin-wp.test
Dirección del sitio (URL):		https://tilopay-plugin-wp.test
Versión de WooCommerce:		8.6.0
Paquete de la REST API de WooCommerce:		 8.6.0 C:\laragon\www\tilopay-plugin-wp\wp-content\plugins\woocommerce\includes
WooCommerce Blocks package:		 11.8.0-dev C:\laragon\www\tilopay-plugin-wp\wp-content\plugins\woocommerce/
Action Scheduler package:		 3.7.1 C:\laragon\www\tilopay-plugin-wp\wp-content\plugins\woocommerce\packages\action-scheduler
Directorio de registros con permiso de escritura:		 C:\laragon\www\tilopay-plugin-wp/wp-content/uploads/wc-logs/
Versión de WordPress:		6.4.3
WordPress multisitio:		–
Límite de memoria de WordPress:		24 GB
Modo de depuración de WordPress:		
Cron de WordPress:		
Idioma:		es_CR
Caché externa de objetos:		–
Entorno del servidor
Información del servidor:		Apache/2.4.54 (Win64) OpenSSL/1.1.1q mod_fcgid/2.3.10-dev
Versión de PHP:		8.3.0
PHP post max size:		5 GB
PHP time limit:		36000
PHP max input vars:		1000
Versión cURL:		8.4.0, OpenSSL/3.0.12
SUHOSIN Instalado:		–
Versión de MySQL:		8.0.30
Tamaño máximo de subida:		2 GB
Por defecto la zona horaria es GMT:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Cadena multibyte:		
Publicación remota:		
Obtención remota:		
Base de datos
Versión de la base de datos de WordPress:		8.6.0
Prefijo de la base de datos	 	wp_
Tamaño total de la base de datos	 	8.32MB
Tamaño de los datos de la base de datos	 	5.31MB
Tamaño del índice de la base de datos	 	3.01MB
wp_woocommerce_sessions	 	Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_api_keys	 	Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies	 	Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions	 	Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_order_items	 	Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_order_itemmeta	 	Datos: 0.08MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_tax_rates	 	Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_tax_rate_locations	 	Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zones	 	Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations	 	Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods	 	Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_payment_tokens	 	Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta	 	Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_log	 	Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_actions	 	Datos: 0.30MB + Índice: 0.41MB + Motor InnoDB
wp_actionscheduler_claims	 	Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_groups	 	Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_logs	 	Datos: 0.20MB + Índice: 0.19MB + Motor InnoDB
wp_commentmeta	 	Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_comments	 	Datos: 0.13MB + Índice: 0.09MB + Motor InnoDB
wp_links	 	Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_options	 	Datos: 3.05MB + Índice: 0.08MB + Motor InnoDB
wp_postmeta	 	Datos: 0.28MB + Índice: 0.28MB + Motor InnoDB
wp_posts	 	Datos: 0.08MB + Índice: 0.06MB + Motor InnoDB
wp_term_relationships	 	Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_term_taxonomy	 	Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_termmeta	 	Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_terms	 	Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_usermeta	 	Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_users	 	Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_admin_note_actions	 	Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
wp_wc_admin_notes	 	Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp_wc_category_lookup	 	Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_customer_lookup	 	Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_download_log	 	Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_addresses	 	Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_wc_order_coupon_lookup	 	Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_operational_data	 	Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_product_lookup	 	Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_wc_order_stats	 	Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_order_tax_lookup	 	Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_orders	 	Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
wp_wc_orders_meta	 	Datos: 0.28MB + Índice: 0.58MB + Motor InnoDB
wp_wc_product_attributes_lookup	 	Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_download_directories	 	Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_product_meta_lookup	 	Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_wc_rate_limits	 	Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_reserved_stock	 	Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_tax_rate_classes	 	Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_webhooks	 	Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
Contador de tipo de contenido
attachment	 	1
customize_changeset	 	1
page	 	7
post	 	2
product	 	2
revision	 	4
shop_order	 	31
shop_order_placehold	 	16
wp_navigation	 	1
wp_template	 	2
Seguridad
Conexión segura (HTTPS):		
Ocultar errores a los visitantes		Los mensajes de error no deberían mostrarse a los visitantes.
Plugins activos (2)
[Tilopay](https://wordpress.org/plugins/tilopay/)	 	por Tilopay – 2.1.2
[WooCommerce](https://woo.com/)	 	por Automattic – 8.6.0 (update to version 8.6.1 is available)
Plugins inactivos (0)
Ajustes
API activada:		–
Forzar SSL:		–
Moneda		CRC (₡)
Ubicación de la moneda		left
Separador de miles		,
Separador decimal		.
Número de decimales		2
Taxonomías: Tipos de producto		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomías: Visibilidad del producto		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
Connected to Woo.com:		–
Enforce Approved Product Download Directories:		
HPOS feature screen enabled:		
HPOS enabled:		
Order datastore:		Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled:		–
Páginas de WooCommerce
[Base de la tienda](https://tilopay-plugin-wp.test/wp-admin/post.php?post=6&action=edit):		#6 - /tienda/
[Carrito](https://tilopay-plugin-wp.test/wp-admin/post.php?post=7&action=edit):		#7 - /carrito/
[Finalizar compra](https://tilopay-plugin-wp.test/wp-admin/post.php?post=8&action=edit):		#8 - /finalizar-compra/
[Mi cuenta](https://tilopay-plugin-wp.test/wp-admin/post.php?post=9&action=edit):		#9 - /mi-cuenta/
Términos y condiciones:		 Página sin definir
Tema
Nombre:		Storefront
Versión:		4.5.4
URL del autor:		https://woo.com/
Tema hijo:		 – Si estás modificando WooCommerce en un tema padre que no has creado personalmente, te recomendamos utilizar un tema hijo. Ver: [Cómo crear un tema hijo](https://developer.wordpress.org/themes/advanced-topics/child-themes/)
Compatible con WooCommerce:		
Plantillas
Anulaciones:	 	–
Admin
Enabled Features:		activity-panels, analytics, product-block-editor, coupons, core-profiler, customer-effort-score-tracks, import-products-task, experimental-fashion-sample-products, shipping-smart-defaults, shipping-setting-tour, homescreen, marketing, mobile-app-banner, navigation, onboarding, onboarding-tasks, product-variation-management, product-virtual-downloadable, product-external-affiliate, product-grouped, product-linked, remote-inbox-notifications, remote-free-extensions, payment-gateway-suggestions, shipping-label-banner, subscriptions, store-alerts, transient-notices, woo-mobile-welcome, wc-pay-promotion, wc-pay-welcome-page
Disabled Features:		customize-store, minified-js, new-product-management-experience, product-pre-publish-modal, settings, async-product-editor-category-field
Daily Cron:		 Next scheduled: 2024-02-22 18:04:33 +00:00
Options:		
Notes:		75
Onboarding:		completed
Programador de acciones
Version:	3.7.1
Data store:	ActionScheduler_DBStore
Estado de la acción	 	Contador	Fecha programada más antigua	Fecha programada más reciente
Completar	 	1.102	2024-01-22 18:05:41 +0000	2024-02-21 18:40:56 +0000
Fallida	 	1	2024-01-22 18:07:32 +0000	2024-01-22 18:07:32 +0000
Pendiente	 	1	2024-02-21 22:16:24 +0000	2024-02-21 22:16:24 +0000
Status report information
Generated at:	 	2024-02-21 18:41:01 +00:00

```
</details>

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by opr** [comment] 2024-03-01 10:46
Hi, thanks for taking the time to report these issues.

I was unable to reproduce the issue of the notice appearing three times, perhaps you could give some clearer reproduction instructions, exactly what code did you use, and where did you add it in the dummy payment gateway plugin?

For the second issue you mentioned

> for order hidden have to make some modifications from FE such create the order as draft and them update at BE with: $this->order->update_status( 'pending' ); $this->order->save();

it is still unclear how to reproduce this. I set an order to draft then did the following:

```php

add_action( 'init', function() {
	$order = wc_get_orders(
		[ 'status' => [ 'wc-draft' ] ]
	)[0];
	$order->set_status( 'pending' );
	$order->save();
} );
```

and it worked OK for me.

Could you provide some code and fuller reproduction steps, thanks!

**Comment by norud** [comment] 2024-03-05 00:53
thanks for response, here is video about the hidden order https://drive.google.com/file/d/1weJPF_gxzORITryZS2uUV0Qbh93RW1lP/view?usp=sharing

the plugin have 2 ways to process payment:

**1. Redirect:**
- 1.1 call `public function process_payment( $order_id )` and redirect to payment form, as you see at the video the order is waiting 
the payen.
1.2 The payment redirect to checkout page and the plugin check if payment was approved or rejected and update the respective order status: 

```js
public function __construct() {
    global $woocommerce;
    $order = wc_get_order( $request_order_id ); 

    if ( $order ) {
        $order->update_status( 'failed' ); // Payment error
        $order->update_status( 'processing' ); // Success payment
        $order->save();
    }
}
```
after that the order is hiding 

**2. Native:**
- 2.1: Before call `public function process_payment( $order_id )`, I'm using blocks 
```js
const Tilopay = {
    paymentMethodId: settings.id,
    name: settings.id,
    label: <Label />,
    content: <TilopayComponent />,
    edit: <TilopayComponent />,
    canMakePayment: () => true,
    ariaLabel: label,
    //placeOrderButtonLabel: __('Pay with Tilopay', 'tilopay'),
    supports: {
        features: settings.supports,
    }
};

const TilopayComponent = (props) => {
    const wc_order_id = select('wc/store/checkout').getOrderId(); // This line marks the order as draft
};

```
- 2.2 Attempt to make the payment calling `public function process_payment( $order_id )` this action is from checkout BTN).
- 2.3 If payment need 3ds redirect and return to checkout where the plugin will check if the payment was approve or reject to update the order status:
```js
public function __construct() {
    global $woocommerce;
    $order = wc_get_order( $request_order_id ); 

    if ( $order ) {
        $order->update_status( 'failed' ); // Payment error
        $order->update_status( 'processing' ); // Success payment
        $order->save();
    }
}
```
after that the order is hiding 

The issue `wc_add_notice()` but when invoke `wc_print_notices();` show in 3 different places the same message" i did not find the right solutions, so i handle with js to apply innerHtml at the checkout to show one message.

thanks in advance

**Comment by nielslange** [comment] 2024-03-06 07:22
Hello @norud, I tried to reproduce this issue based on your provided code snippet. Unfortunately, I wasn't able to do so. Could you share the entire plugin with us so that we're able to reproduce the order and notice issues?

As for the order updates. In https://github.com/woocommerce/woocommerce/issues/44862#issuecomment-1972957042, @opr shared the following code:
```js
...
$order->set_status( 'pending' );
$order->save();
...
```

In your reply, you shared this code:
```js
...
$order->update_status( 'failed' ); // Payment error
$order->update_status( 'processing' ); // Success payment
$order->save();
...
```

Calling the function `$order->save()` is only needed when calling `$order->set_status( ... )` When calling `$order->update_status( ... )`, the save function automatically gets called. There's no need to call that function separately.

As for the order status updates, I assume that setting the status to `failed` and then to `processing` immediately after each other is for testing purposes, correct? 

As mentioned before, it would be helpful to share your plugin with us so that we can check what is causing the issues on your end.

**Comment by norud** [comment] 2024-03-09 01:35
@nielslange sure 
[tilopay-dev-v3-8-3-2024.zip](https://github.com/woocommerce/woocommerce/files/14544522/tilopay-dev-v3-8-3-2024.zip)

after install you have to make cd wp-content\plugins\tilopay this for blocks
`npm i
npm run start
`
then you have to config tilopay at {url}/wp-admin/admin.php?page=wc-settings&tab=checkout&section=tilopay:
`
Integration key: 
8907-2635-5382-9803-4346
API user: 
fAiSUQ
API password:
zQulHO
Embedded native payment or through redirect: select "Native checkout payment form"
`
and save it should look like:
![image](https://github.com/woocommerce/woocommerce/assets/46699973/71907d1d-ce6d-44c7-9078-7874c02ef9ce)

then just make the checkout flow and select Tilopay as payment method, use this test card:
card:
4111 1111 1111 1111
expiry:
12 / 24
CVV:
123
should look like:
![image](https://github.com/woocommerce/woocommerce/assets/46699973/d2a02221-1f0a-44cd-a6ad-d0db855b2a05)
just click on place order 
the 3ds challenge will show it: 
![image](https://github.com/woocommerce/woocommerce/assets/46699973/20e44add-9cfe-4df2-9e74-a720b60ad617)
and type 3ds2 and submit 

To show in 3 different places the same message: add this to the checkout ?message_error=Response%20error will show it:
![image](https://github.com/woocommerce/woocommerce/assets/46699973/5615991d-ccc2-4cff-8b56-abb5b751010f)

thanks, in advance!

**Comment by wavvves** [comment] 2024-03-15 15:40
Hi @norud thanks for reaching out. I'm trying to follow this, and I have to confess, not easy considering there are 2 issues reported here 😅. 

Let's try and break it down, for the notices issue (which I couldn't replicate on a fresh env):

- The top notice doesn't seem a familiar position to me. Can we please make sure this is not theme related / there arent any mods or plugins outputting notices before the header / weird CSS putting it up there / any dev changes added by you printing this?
- As for the other two, can you please try on a new page containing a freshly added Checkout block? Seems to me the Notices element is duplicated (you can also check the source of the page for this)

As a wrap up, after sorting these two out, the expected behaviour would be just to see one of the last two notices.

For the second issue about changing the order status, I would suggest removing it from this thread to avoid confusion. Also this doesn't sound like an issue or bug (I managed to programmatically change order statuses without displaying problems on the order list) but something you might need support implementing. Do you mind [starting a discussion](https://github.com/woocommerce/woocommerce/discussions/new/choose) for it instead?

**Comment by norud** [comment] 2024-03-20 23:57
@wavvves thanks for response, the issue "show in 3 different places the same message" actually it is not a problem because I handled it by applying innerHTML = "";

**Please take only the second issue** "The order is hidden when the status is updated."
 If you prefer, we can arrange a meeting to explain the complete flow and show how the problem is generated, you can contact me on sac@tilopay.com subject WOO Issue with Yeral DR.

regards

**Comment by opr** [comment] 2024-03-29 21:13
@norud thanks for the update, glad to hear you fixed the first issue.

> Please take only the second issue "The order is hidden when the status is updated."

Ok, please could you close this issue and open a new one with _only_ the issue you're reporting. This thread is very complicated as we're trying to follow two issues at once and the threads are getting a little mixed up. I appreciate it's extra work for you but it would really help our team.

We would also appreciate some _minimal_ reproduction steps to help us do this. As @wavvves mentions, it could be something in your plugin, so if we reduce the amount of code required to replicate it that would really help us narrow this down.

Thanks a lot for your patience!

**Comment by norud** [comment] 2024-04-02 18:37
@opr @wavvves already create new one https://github.com/woocommerce/woocommerce/issues/46136
thanks

**Comment by nielslange** [comment] 2024-04-03 05:31
Thanks for creating #46136, @norud. As @opr mentioned, this thread became very long, and as it touched two issues, rather difficult to follow. I'm closing this issue now.

**Closed as completed by nielslange** 2024-04-03 05:31 UTC
Labels: Bug, Checkout, needs: triage feedback, type: community contribution, Rubik
