### ISSUE TITLE
Fatal error on latest beta 6.0.0 beta 1 in frontend

### ISSUE THREAD

**Issue by BackuPs** [woothemes/woocommerce#31284] opened 2021-11-24 12:41 UTC
I just created a clean wp install with Woocommerce beta 1 V 6.0.0 and going to the frontend of the website shows me a fatal error.

No gutenberg plugin activate. Just installed the latest beta 6.0.0 beta 1 and I get this error in the frontend.  

Switching to 5.90 resolves the error. Please fix.

**

> Fatal error: Uncaught Error: Call to undefined function Automattic\WooCommerce\Blocks\gutenberg_supports_block_templates() in /var/docs/server.tst/public/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTemplatesController.php on line 13

**

**Comment by larsenlarsson** [comment] 2021-11-24 15:03
Works fine with WordPress 5.8.2.
Error occurs when using WordPress development version 5.9-alpha-52236

**Comment by tammullen** [comment] 2021-11-24 15:59
Hi @BackuPs,

Thank you for reporting the issue, I can reproduce it. 
This appears to be caused by WooCommerce Blocks.  
We are closing your issue in favor of your previously submitted issue in the WooCommerce Blocks repository. 
https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5236
Please continue sharing your feedback there if needed.

**Closed as completed by tammullen** 2021-11-24 15:59 UTC
