### ISSUE TITLE
Tax shown as "Tax" not "VAT" when "Itemized" selected

### ISSUE THREAD

**Issue by rtpHarry** [woothemes/woocommerce#35943] opened 2022-12-12 22:32 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I've recorded a video demonstrating what I'm seeing:

https://soapbox.wistia.com/videos/nwNM6S3ypX

The store is set to GB for the country, which is a VAT country.

When WooCommerce > Settings > Tax > Tax Options > Display Tax Totals == "Itemized" then the tax_or_vat hook is never called and the checkout shows `tax` when it should show `vat`.

If you change it to "As a single total" then the correct `vat` strings are displayed.

For reference, here in the checkout it is showing VAT:

<img width="643" alt="image" src="https://user-images.githubusercontent.com/1038062/207167096-f6109fd2-519f-4023-a35f-4f31fbc09675.png">

I've also tested switching that setting on and off and it affects the My Account > Orders > View Order page.

### Expected behavior

Show VAT in all places "Tax" is displayed when the country is a vat country

### Actual behavior

Tax is leaking out in places like the checkout, and my account -> view order, as the vat_or_tax() is never called

### Steps to reproduce

1. Set "display tax totals" as "show single..."
2. Set the base country to a vat country eg GB (Great Britain / United Kingdom)
3. Put a breakpoint on WC_Countries->tax_or_vat() 
4. Go to checkout and see that tax_or_vat() is called and `vat` is correctly displayed in the totals
5. Now change "display tax totals" to "itemized"
6. Revisit the checkout
7. See that the breakpoint is no longer triggered
8. See that the `vat` string now incorrectly says `tax`

### WordPress Environment

```
### WordPress Environment ###

WordPress address (URL): https://knepp.test
Site address (URL): https://knepp.test
WC Version: 7.1.1
REST API Version: ✔ 7.1.1
WC Blocks Version: ✔ 8.7.6
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 2GB
WP Debug Mode: –
WP Cron: –
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: nginx/1.23.2
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.18-MariaDB-1:10.5.18+maria~ubu2004
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.1
WC Database Prefix: wp_
Total Database Size: 346.52MB
Database Data Size: 291.38MB
Database Index Size: 55.14MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 11.52MB + Index: 12.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.48MB + Index: 0.70MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.38MB + Index: 0.31MB + Engine InnoDB
wp_addonlibrary_addons: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
wp_addonlibrary_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aryo_activity_log: Data: 0.44MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.25MB + Index: 0.58MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 1.36MB + Engine InnoDB
wp_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_duplicator_pro_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jckwds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_post_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_rel_default: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_taxonomies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lecm_rewrite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 11.42MB + Index: 0.14MB + Engine InnoDB
wp_pmxe_exports: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 155.58MB + Index: 23.06MB + Engine InnoDB
wp_posts: Data: 77.08MB + Index: 3.19MB + Engine InnoDB
wp_redirection_404: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 6.52MB + Index: 7.03MB + Engine InnoDB
wp_users: Data: 0.38MB + Index: 0.42MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.39MB + Index: 0.23MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 1.52MB + Index: 0.48MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.48MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.23MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.19MB + Index: 0.13MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpo_wcpbn_batch_numbers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 1.52MB + Index: 0.72MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.23MB + Index: 0.19MB + Engine InnoDB

### Post Type Counts ###

acf-field: 6
acf-field-group: 1
attachment: 1313
aw_workflow: 31
bookable_person: 1
elementor_library: 26
elementor_snippet: 1
global_product_addon: 2
jet-engine: 8
jet-menu: 7
jet-popup: 3
jet-woo-builder: 21
nav_menu_item: 96
oembed_cache: 5
page: 137
pewc_field: 1
pewc_group: 1
post: 81
product: 171
product_variation: 388
recipes: 9
revision: 2034
shop_coupon: 447
shop_order: 4709
tablepress_table: 3
team-member: 42
wc_booking: 227
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (50) ###

Unlimited Elements for Elementor (Premium): by Unlimited Elements – 1.5.43
Advanced Custom Fields PRO: by WP Engine – 6.0.5
Activity Log: by Activity Log Team – 2.8.5
Astra Pro: by Brainstorm Force – 3.9.4
AutomateWoo: by WooCommerce – 5.6.0
Cachebuster: by Albert Peschar – 1.3
Disable User Login: by Saint Systems – 1.3.3
Yoast Duplicate Post: by Enrico Battocchi and Team Yoast – 4.5
Duplicator Pro: by Snap Creek – 4.5.8.3
Duplicator Pro: by Snap Creek – 4.5.8.3
Elementor Pro: by Elementor.com – 3.9.0
Elementor: by Elementor.com – 3.9.0
ElementsKit Lite: by Wpmet – 2.7.5
Products & Order Export for WooCommerce: by WPWhale – 2.0
Flexible Shipping: by Octolize – 4.17.0
WooCommerce Delivery Slots by Iconic: by Iconic – 1.18.0
JetBlocks For Elementor: by Crocoblock – 1.3.5
JetEngine - Custom visibility conditions: by Crocoblock – 1.0.0
JetEngine - Repeater field values: by Matthew Harris
runthings.dev – 1.1.1

JetEngine - Trim string callback: by Crocoblock – 1.0.0
JetEngine: by Crocoblock – 3.0.8
JetMenu: by Crocoblock – 2.2.4
JetPopup: by Crocoblock – 1.6.3
JetTricks: by Crocoblock – 1.4.3
JetWooBuilder - Category Custom Product Template: by Matthew Harris
runthings.dev – 1.2.0

JetWooBuilder For Elementor: by Crocoblock – 2.1.0
LiteSpeed Cache: by LiteSpeed Technologies – 5.3
Mailgun: by Mailgun – 1.8.8
MainWP Child: by MainWP – 4.3.0.1
Premium Addons for Elementor: by Leap13 – 4.9.42
Redirection: by John Godley – 5.3.6
Knepp Custom Checkout Question - 12+ Confirmation: by Matthew Harris
runthings.dev – 1.2.1

Current Year Shortcode: by Matthew Harris
runthings.dev – 1.1.0

WooCommerce Accommodation Bookings: by WooCommerce – 1.1.36
WooCommerce Bookings: by WooCommerce – 1.15.68
DPD UK & DPD Local Labels and Tracking: by Octolize – 1.13.0
WooCommerce Stripe Gateway: by WooCommerce – 7.0.1
WooCommerce Knepp Accommodation Bookings: by Matthew Harris
runthings.dev – 1.4.0

WooCommerce Print Order List: by WP Overnight – 1.9.0
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.2.5
WooCommerce Product Add-ons: by WooCommerce – 5.0.2
WooCommerce Product Batch Numbers: by WP Overnight – 1.8.0
WooCommerce Shipping & Tax: by WooCommerce – 2.1.0
WooCommerce Store Credit: by Themesquad – 4.2.4
WooCommerce: by Automattic – 7.1.1
Yoast SEO: by Team Yoast – 19.11
WP All Export Pro: by Soflyy – 1.8.1
WP All Import Pro: by Soflyy – 4.7.8
WP All Export - WooCommerce Export Add-On Pro: by Soflyy – 1.0.5
WP All Import - WooCommerce Import Add-On Pro: by Soflyy – 3.3.4

### Inactive Plugins (4) ###

CookieYes | GDPR Cookie Consent: by CookieYes – 3.0.6
Really Simple SSL: by Really Simple Plugins – 6.0.12
Wordfence Security: by Wordfence – 7.8.0
WordPress Importer: by wordpressdotorg – 0.8

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
external (external)
grouped (grouped)
simple (simple)
store_credit (store_credit)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: ❌ Page not set
Basket: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: #639 - /checkout/
My account: #640 - /my-account/
Terms and conditions: #7544 - /legal/terms-of-use/

### Theme ###

Name: Knepp
Version: 1.0.0
Author URL: https://sokastudio.co.uk/
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 3.9.4
Parent Theme Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce Support: ✔

### Templates ###

Overrides: /srv/www/knepp/public_html/wp-content/plugins/jet-woo-builder/templates/woocommerce/checkout/form-checkout.php
/srv/www/knepp/public_html/wp-content/plugins/jet-woo-builder/templates/woocommerce/checkout/thankyou.php
knepp/woocommerce/emails/customer-new-account.php
/srv/www/knepp/public_html/wp-content/plugins/jet-woo-builder/templates/woocommerce/myaccount/dashboard.php
/srv/www/knepp/public_html/wp-content/plugins/jet-woo-builder/templates/woocommerce/myaccount/downloads.php
/srv/www/knepp/public_html/wp-content/plugins/jet-woo-builder/templates/woocommerce/myaccount/form-edit-account.php version 3.5.0 is out of date. The core version is 7.0.1
/srv/www/knepp/public_html/wp-content/plugins/jet-woo-builder/templates/woocommerce/myaccount/form-login.php
/srv/www/knepp/public_html/wp-content/plugins/jet-woo-builder/templates/woocommerce/myaccount/my-address.php
/srv/www/knepp/public_html/wp-content/plugins/jet-woo-builder/templates/woocommerce/myaccount/orders.php version 3.7.0 is out of date. The core version is 7.0.1
/srv/www/knepp/public_html/wp-content/plugins/jet-woo-builder/templates/woocommerce/content-product_cat.php

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-12-13 16:48:19 +00:00
Options: ✔
Notes: 91
Onboarding: completed

### Action Scheduler ###

Complete: 1,523
Oldest: 2022-11-12 09:37:11 +0000
Newest: 2022-12-12 21:41:54 +0000

Pending: 4
Oldest: 2022-12-13 18:00:08 +0000
Newest: 2023-01-01 07:40:06 +0000


### Store Credit ###

Prices entered with tax: yes
Show My Account: yes
Delete after use: yes
Individual use: no
Include tax: no
Apply to shipping: yes
Coupon code format: {coupon_code}
Overrides: -

### Status report information ###

Generated at: 2022-12-12 22:25:00 +00:00
```

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment] 2022-12-16 17:19
Hi @rtpHarry,

Thanks for reaching out and for the clear instructions on how to reproduce. We discussed this on the team, and we believe the "Itemized" option here is working as intended: that is, it is displaying all the taxes with their respective names.

Your site is displaying "Tax" probably because that's the name the tax has in the settings (which is also the default name).

A possible workaround would be to rename this tax as "VAT" if you so desire, by going to WC > Settings > Tax and changing the name of the tax under the "Tax name" to "VAT" (you first have to choose the correct rate category section, of course).

Please let us know if that works. In the meantime, I'm closing this issue, but feel free to re-open if you think this is truly a bug or if I've misrepresented the situation.

**Closed as not planned by jorgeatorres** 2022-12-16 17:19 UTC
Labels: Bug, plugin: woocommerce, type: community contribution
