### ISSUE TITLE
The "class" attribute is displayed incorrectly in the search widget wc

### ISSUE THREAD

**Issue by aprinciple** [woothemes/woocommerce#30775] opened 2021-09-22 15:02 UTC
Outputs the attribute "class name" instead of class, so css styles do not work

<img width="934" alt="Screenshot 2021-09-22 at 17 50 48" src="https://user-images.githubusercontent.com/46525581/134369125-e4a031bd-59ce-4d3f-9e7c-e3e7c8c9afc6.png">

Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://test.aprinciple.site
Site address (URL): https://test.aprinciple.site
WC Version: 5.7.0
REST API Version: ✔ 5.7.0
WC Blocks Version: ✔ 5.7.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.6.4
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 512 МБ
WP Debug Mode: –
WP Cron: ✔
Language: ru_RU
External object cache: –

### Server Environment ###

Server Info: nginx/1.20.1
PHP Version: 8.0.6
PHP Post Max Size: 1 ГБ
PHP Time Limit: 120
PHP Max Input Vars: 10000
cURL Version: 7.60.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.7-MariaDB
Max Upload Size: 1 ГБ
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.7.0
WC Database Prefix: wp_
Общий размер базы данных: 1.08MB
Размер данных в базе данных: 0.91MB
Размер индекса базы данных: 0.17MB
wp_woocommerce_sessions: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_woocommerce_api_keys: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_woocommerce_attribute_taxonomies: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_woocommerce_downloadable_product_permissions: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_woocommerce_order_items: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_woocommerce_order_itemmeta: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_woocommerce_tax_rates: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_woocommerce_tax_rate_locations: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_woocommerce_shipping_zones: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_woocommerce_shipping_zone_locations: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_woocommerce_shipping_zone_methods: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_woocommerce_payment_tokens: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_woocommerce_payment_tokenmeta: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_woocommerce_log: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_actionscheduler_actions: Данные: 0.00MB + Индекс: 0.02MB + Движок MyISAM
wp_actionscheduler_claims: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_actionscheduler_groups: Данные: 0.00MB + Индекс: 0.01MB + Движок MyISAM
wp_actionscheduler_logs: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_commentmeta: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_comments: Данные: 0.00MB + Индекс: 0.01MB + Движок MyISAM
wp_links: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_options: Данные: 0.85MB + Индекс: 0.04MB + Движок MyISAM
wp_postmeta: Данные: 0.01MB + Индекс: 0.02MB + Движок MyISAM
wp_posts: Данные: 0.02MB + Индекс: 0.01MB + Движок MyISAM
wp_rio_process_queue: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_termmeta: Данные: 0.00MB + Индекс: 0.01MB + Движок MyISAM
wp_terms: Данные: 0.00MB + Индекс: 0.01MB + Движок MyISAM
wp_term_relationships: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_term_taxonomy: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_tinvwl_analytics: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_tinvwl_items: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_tinvwl_lists: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_usermeta: Данные: 0.00MB + Индекс: 0.01MB + Движок MyISAM
wp_users: Данные: 0.00MB + Индекс: 0.01MB + Движок MyISAM
wp_wc_admin_notes: Данные: 0.02MB + Индекс: 0.00MB + Движок MyISAM
wp_wc_admin_note_actions: Данные: 0.01MB + Индекс: 0.00MB + Движок MyISAM
wp_wc_category_lookup: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_wc_customer_lookup: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_wc_download_log: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_wc_order_coupon_lookup: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_wc_order_product_lookup: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_wc_order_stats: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_wc_order_tax_lookup: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_wc_product_meta_lookup: Данные: 0.00MB + Индекс: 0.01MB + Движок MyISAM
wp_wc_reserved_stock: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
wp_wc_tax_rate_classes: Данные: 0.00MB + Индекс: 0.01MB + Движок MyISAM
wp_wc_webhooks: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM

### Post Type Counts ###

attachment: 2
customize_changeset: 4
nav_menu_item: 6
page: 9
post: 2
product: 2
revision: 3
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Advanced Custom Fields: от Delicious Brains – 5.10.2
Webcraftic Clearfy - плагин оптимизации для Wordpress: от Creative Motion  – 1.9.6
Contact Form 7: от Takayuki Miyoshi – 5.4.2
Webcraftic Robin image optimizer: от Webcraftic  – 1.5.4
Список желаний TI WooCommerce: от TemplateInvaders – 1.28.4
WooCommerce: от Automattic – 5.7.0

### Inactive Plugins (2) ###

Invisible reCaptcha: от Mihai Chelaru – 1.2.3
W3 Total Cache: от BoldGrid – 2.1.8

### Settings ###

API Enabled: –
Force SSL: –
Currency: UAH (₴)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Ссылка магазина: #7 - /shop/
Корзина: #8 - /cart/
Оформление заказа: #9 - /checkout/
Мой аккаунт: #10 - /my-account/
Правила и условия: ❌ Страница не задана

### Theme ###

Name: Storefront
Version: 3.8.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – Если вы хотите оформить WooCommerce родительской темой
которую создал кто-то другой
мы рекомендуем воспользоваться дочерней темой. См. "Как создать дочернюю тему"

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Шаблоны TI WooCommerce Wishlist ###

Переопределения: –

### Action Scheduler ###

Выполнено: 5
Oldest: 2021-09-22 08:03:19 +0000
Newest: 2021-09-22 14:20:32 +0000


### Status report information ###

Generated at: 2021-09-22 17:57:02 +03:00
`
```
</details>

**Comment by rodelgc** [comment] 2021-09-22 16:17
Hi @aprinciple,

Thank you for submitting the issue. However, you didn’t completely fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

It would also be helpful if you could provide us a screenshot of the element that has the `classname` attribute.

Here's the template you need to fill out:

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by wayheming** [comment] 2021-09-24 08:36
same error

**Comment by simplysaru** [comment] 2021-09-26 14:15
Hi @aprinciple, @wayheming 

I couldn't replicate this issue at all. 
<img width="1255" alt="Markup 2021-09-26 at 19 35 45" src="https://user-images.githubusercontent.com/2734132/134811279-d4b689ec-a34e-451e-a3ee-3d1244a52810.png">

If you are sure this is a bug, please provide us with the information requested so we could take a look further.
﻿
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
﻿
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
﻿
**Screenshots**
If applicable, add screenshots to help explain your problem.
﻿
**Expected behavior**
A clear and concise description of what you expected to happen.
﻿
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
﻿
**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
﻿

**Comment by aprinciple** [comment] 2021-09-26 15:29
> Hi @aprinciple, @wayheming
> 
> I couldn't replicate this issue at all.
> <img alt="Markup 2021-09-26 at 19 35 45" width="1255" src="https://user-images.githubusercontent.com/2734132/134811279-d4b689ec-a34e-451e-a3ee-3d1244a52810.png">
> 
Bcz an update has already been released, fixed

**Comment by simplysaru** [comment] 2021-09-26 15:37
Thanks. Since this is fixed. I will close this issue.

**Closed as completed by simplysaru** 2021-09-26 15:37 UTC
Labels: Bug, needs: triage feedback
