### ISSUE TITLE
Forced checkout blocks not loading in block themes

### ISSUE THREAD

**Issue by rajeshsingh520** [woothemes/woocommerce#51224] opened 2024-09-09 09:07 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have creates a simple block that auto add itself to the checkout page info block , this code works properly when the site is running a normal Non block based theme. but as soon as we use a Block based theme for wordpress the checkout page is rendered but our block are not rendered and there is no error as well

we checked the status and it says our block is register as a child block bit it does not render

### Expected behavior

Block should always apply below the parent checkout block (in this case Info block in Woocommerce checkout block)

![image](https://github.com/user-attachments/assets/fdb391a7-3234-42bc-8a8e-afa2ffb996c0)

### Actual behavior

Buy when we are changing to Block based wordpress theme like Twenty twenty four , the auto insertion of our block does not happen and there is no error and even we checked the  registered block list and our block was registered as child block for it

wc.blocksCheckout.getRegisteredBlocks(
	'woocommerce/checkout-contact-information-block'
);

![image](https://github.com/user-attachments/assets/4d7a722b-9e71-4ac7-b033-491df4b585bc)

### Steps to reproduce

1. Activate a non block based theme Twenty-Twenty
2. Create a checkout page using woocommerce checkout block
3. install the attached plugin small plugin with a js code to auto insert a message "TEST BLOCK" after the email id this will work in non block based theme
[test-block.zip](https://github.com/user-attachments/files/16928183/test-block.zip)

4. Activate a Block based wordpress theme say Twenty-Twenty-Four
now you won't see the block added to the checkout page

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.2.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.23
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.77.0
OpenSSL/1.1.1t

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 53
bc_x1379_op_type: 1
custom_css: 1
customize_changeset: 2
language_switcher: 4
nav_menu_item: 4
order_status: 1
page: 32
pi_cefw_combine: 1
pi_cefw_custom_group: 1
pi_coupon_template: 1
pi_discount_rule: 9
pi_dpmw_rules: 9
pi_dtt_special_date: 1
pi_efrs_combine: 1
pi_efrs_custom_group: 4
pi_efrs_package: 1
pi_fees_rule: 25
pi_pccdt_setting: 1
pi_pending_amt: 616
pi_shipping_method: 14
pisol_location: 3
po_product_options: 4
polylang_mo: 2
post: 4
product: 49
product_variation: 28
revision: 201
shop_coupon: 29
shop_deposit: 10
shop_order: 1091
shop_order_refund: 4
shop_subscription: 11
uni_cpo_option: 3
wc_conditional_fee: 1
wc-donation: 1
wc-donation-report: 1
wp_global_styles: 3
wp_navigation: 1
wp_template: 2
wp_template_part: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Test plugin: by PI Websolution – 3.0.49.17
WooCommerce: by Automattic – 9.2.3

### Inactive Plugins (239) ###

24hr time comparison: by PI Websolution – 1.0
AAA production hour: by PI Websolution – 1.1
Adding Flat rate shipping in Woocommerce Role manager: by PI Websolution – 1.0
Add order note for Woocommerce App: by PI Websolution – 1.0
Advanced Coupons for WooCommerce Free: by Rymera Web Co – 4.6.1.1
Advanced Dynamic Pricing for WooCommerce: by AlgolPlus – 4.3.0
Advanced Flat Rate Shipping For WooCommerce: by theDotstore – 4.2.1
Advanced Free - Flat shipping WooCommerce: by PI Websolution – 1.6.4.42
Advanced Free - Flat shipping WooCommerce - Pro: by PI Websolution – 1.2.9.12
Advanced Order Export For WooCommerce: by AlgolPlus – 3.5.1
Afterpay Gateway for WooCommerce: by Afterpay – 3.0.2
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.2
ApplePay for Hyperpay Payment Gateway for WooCommerce: by Hyperpay Team – 1.0
Area rule for shipping method: by PI Websolution – 1.1
Bayna - Deposits & Partial Payments for WooCommerce: by Codeixer – 1.2.7
BC Woo Custom Thank You Pages: by WooCommerce & WordPress Tutorials – 1.4.12
Both shipping and billing should be in post code range: by PI Websolution – 1.0
Buy one get one free PRO: by PI Websolution – 1.4.44.13
CartBounty - Save and recover abandoned carts for WooCommerce: by Streamline.lv – 5.0.1
CCAvenue Payment Gateway for WooCommerce: by Nilesh Chourasia – 3.1
Change position of delivery and pickup on checkout page: by PI Websolution – 1.0
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.8.1
Cities Shipping Zones for WooCommerce: by Condless – 1.0.7
Code Profiler: by Jerome Bruandet ~ NinTechNet Ltd. – 1.5
Code Snippets: by Code Snippets Pro – 3.4.0
Combined time slot order limit: by PI Websolution – 1.0
Conditional discount rule for WooCommerce: by PI Websolution – 1.9.37.33
Conditional discount rule for WooCommerce - Pro: by PI Websolution – 1.2.7.47
Conditional extra fees for WooCommerce: by PI Websolution – 1.1.39
Conditional extra fees for WooCommerce PRO: by PI Websolution – 1.0.30.34
Conditional Payments for WooCommerce: by Lauri Karisola / WP Trio – 2.3.2
Contact Form 7: by Takayuki Miyoshi – 5.8
Content Blocks (Custom Post Widget): by Johan van der Wijk – 3.2.3
Convert Order limit in to quantity limit per time slot: by PI Websolution – 1.0
Convert order limit to quantity limit: by PI Websolution – 1.0
CSS JS Manager, Async JavaScript, Defer Render Blocking CSS: by Pi Websolution – 2.4.49.22
CURCY - Multi Currency for WooCommerce: by VillaTheme – 2.2.2
Custom additional charge rule based on product price: by Pi WebSolution – 1.0
Custom coupon rule for shipping: by PI Websolution – 1.0
Custom coupon rule for shipping: by PI Websolution – 1.0
Customer review for WooCommerce: by PI Websolution – 1.0.17
Customer Reviews for WooCommerce: by CusRev – 5.49.3
Custom Order Status: by Addify – 1.0.1 (update to version 1.1.1 is available)
Custom product page: by PI Websolution – 1.0
Custom rule for fees: by PI Websolution – 1.1
Custom special date text field: by PI Websolution – 1.0
Custom Zone based rule for shipping: by PI Websolution – 1.2.9.11
Debug Bar: by wordpressdotorg – 1.0.1
Delivery & Pickup Date Time for WooCommerce: by CodeRockz – 1.3.63
Delivery date and time shortcode pro: by Rajesh Singh – 1.0.0
Delivery days cutoff  master PRO: by PI Websolution – 1.0.6
Delivery pickup popup Pro: by PI Websolution – 1.1.3.23
Delivery pickup reminder email Woocommerce: by PI Websolution – 1.4.49
Delivery pickup reminder email Woocommerce Pro: by PI Websolution – 1.1.7.16
Deposits & Partial Payments for WooCommerce: by Acowebs – 1.0.10
Different date time for different Pickup and Delivery location PRO: by PI Websolution – 1.1.13
Different Delivery type for Dokan vendors: by PI Websolution – 1.0.0
Dining at restaurant pro: by PI Websolution – 1.1.9
Direct checkout, WooCommerce Single page checkout , WooCommerce One page checkout - PRO: by PI Websolution – 1.3.9.16
Direct Checkout for WooCommerce: by QuadLayers – 2.4.2
Disable Comments: by Samir Shah – 1.10.2
Disable payment method / COD fees for Order for WooCommerce: by PI Websolution – 1.1.7.60
Disable payment method / COD fees for Order for WooCommerce (PRO): by PI Websolution – 1.0.49.46
Dokan: by weDevs – 3.9.5
Donation For Woocommerce: by wpexpertsio – 3.4.6.2
Dropdown of optional fee: by PI Websolution – 1.1
Duplicate Post: by Enrico Battocchi – 3.2.4
Easy Updates Manager: by Easy Updates Manager Team – 9.0.8
Elated CPT: by Elated Themes – 1.4
Elated Instagram Feed: by Elated Themes – 2.1
Elated Twitter Feed: by Elated Themes – 1.1
Elementor: by Elementor.com – 3.9.2
Email Log: by Sudar – 2.4.8
Empty Cart Button for WooCommerce: by ProWCPlugins – 1.2.8
Enquiry Quotation for WooCommerce: by PI Websolution – 2.2.30
Envato Market: by Envato – 2.0.7
Estimated Delivery for WooCommerce: by TaxarPro – 1.2.2
Estimate delivery date for Woocommerce Pro: by PI Websolution – 4.7.20.14
Everest Forms: by WPEverest – 1.7.2.2
Extend popup plugin: by PI Websolution – 1.0
Financial report: by PI Websolution – 1.0.4
First order for vendor rule: by PI Websolution – 1.0
Fix Time picker distorted by "Livemesh Addons for WPBakery Page Builder": by PI Websolution – 1.0
Flexible Refund and Return Order for WooCommerce: by WP Desk – 1.0.1
Flexible Shipping: by Octolize – 4.22.1
FluentSMTP: by FluentSMTP & WPManageNinja Team – 2.2.2
Fluid Checkout for WooCommerce - Lite: by Fluid Checkout – 2.2.2
Germanized for WooCommerce: by vendidero – 3.16.9
Google Analytics for WooCommerce: by WooCommerce – 2.1.5
Hide payment option as per selected date: by PI Websolution – 1.0
Hide shipping on cart page: by PI Websolution – 1.0
Hide shipping on cart page: by PI Websolution – 1.0
HTTP2 push content: by Pi websolution – 1.9.74
Hyperpay Payment Gateway plugin for WooCommerce: by Hyperpay Team – 1.0
Hyyan WooCommerce Polylang Integration: by Hyyan Abo Fakher – 1.5.0
Increment decrement quantity: by  –
Index WP MySQL For Speed: by Oliver Jones
Rick James – 1.4.11

Jetpack: by Automattic – 13.0
KingComposer: by King-Theme – 2.9.3
License manager: by PI Websolution – 1.0.14
LiteSpeed Cache: by LiteSpeed Technologies – 6.2.0.1
Loco Translate: by Tim Whitlock – 2.6.11
Mada for Hyperpay Payment Gateway for WooCommerce: by Hyperpay Team – 1.0
Manual activation: by PI Websolution – 1.0
Mercado Lite - Revolutionize Your eCommerce Store into Multifaceted Sales Platform: by RedefiningTheWeb – 1.1.0
Mercado Pro - Revolutionize Your eCommerce Store into Multifaceted Sales Platform: by RedefiningTheWeb – 1.1.1
Minimum Maximum quantity & Minimum Order amount for WooCommerce Pro: by Pi Websolution – 1.3.4.49
Minimum Purchase Amount For WooCommerce: by CT Talks – 2.3.19
Min Max Default Quantity for WooCommerce: by WPFactory – 4.5.23
Min Purchase Amount for Delivery order Pro (Addon plugin): by PI Websolution – 1.0.6.10
Modify delivery / pickup date and time: by PI Websolution – 1.0.6
Multi-Step Checkout for WooCommerce (Pro): by ThemeHigh – 2.0.2
Multi step compatible with date and time plugin: by PI Websolution – 1.1
My Extension Name: by The WordPress Contributors – 0.1.0
Only one fees can be selected: by PI Websolution – 1.0
Optimize date and time plugin: by PI Websolution – 1.0
Order Calendar for WooCommerce: by PI Websolution – 1.6.43
Order Calendar for WooCommerce Pro: by PI Websolution – 1.2.2.27
Order date, Order pickup, Order date time, Pickup Location, delivery date  for WooCommerce: by PI Websolution – 3.0.49.17
Order Delivery Date for WooCommerce (Lite version): by Tyche Softwares – 3.10.2
Page Builder by SiteOrigin: by SiteOrigin – 2.10.11
Payment Gateway Based Fees and Discounts for WooCommerce: by Tyche Softwares – 2.11.0
Payment Plugins for PayPal WooCommerce: by Payment Plugins
support@paymentplugins.com – 1.0.21

PayPlug pour WooCommerce (Officiel): by PayPlug – 1.2.10
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.7.7
Performance Lab: by WordPress Performance Team – 2.8.0
Phone Orders for WooCommerce: by AlgolPlus – 3.8.10
PhonePe Payment Solutions: by PhonePe – 2.0.11
PHP Compatibility Checker: by WP Engine – 1.5.2
Pickup location by url: by PI Websolution – 1.0
Pison Coupon discount offer: by Pi Web Solutions – 1.0.6
PI WooCommerce order date time and type PRO: by PI Websolution – 3.3.11.11
PixelYourSite: by PixelYourSite – 7.2.1.1
Plugin Check (PCP): by WordPress Performance Team and Plugin Review Team – 1.0.2
Polylang: by WP SYNTEX – 3.3.3
Postcode in popup: by PI Websolution – 1.1
Post Types Order: by Nsp Code – 1.9.8
PPOM for WooCommerce by N-MEDIA: by Najeeb Ahmad – 24.8
Preparation time Master PRO: by PI Websolution – 1.2.6.29.7
Price by Formula Calculator for WooCommerce: by Plugify – 3.0.1 (update to version 4.0.1 is available)
Print Invoice & Delivery Notes for WooCommerce: by Tyche Softwares – 4.6.5
Product daily quantity limit: by PI Websolution – 1.0
Product delivery type: by PI Websolution – 1.0
Product Options and Price Calculation Formulas for WooCommerce – Uni CPO: by MooMoo Agency – 4.9.22
Product Options and Price Calculation Formulas for WooCommerce – Uni CPO (Premium): by MooMoo Agency – 4.9.8
PRO Order Deliver, date, time, pickup location: by PI Websolution – 1.3.1
Qty Increment Buttons for WooCommerce: by taisho – 2.7.5
Query Monitor: by John Blackbourn – 3.15.0
Razorpay Payment Links for WooCommerce: by Sayan Datta – 1.1.5
Red color for date and time in Email: by PI Websolution – 1.0
Renewal reminder email v2: by PI Websolution – 1.0.9
Restaurant Menu using WooCommerce: by PI Websolution – 6.2.47
Restaurant Menu using WooCommerce Pro: by PI Websolution – 2.7.3
RestroPress: by MagniGenie – 2.8.3.2
RTL Tester: by <a href="http://blog.yoavfarhi.com">Yoav Farhi</a>
<a href="http://automattic.com">Automattic</a> – 1.1

Safe SVG: by 10up – 2.0.3
Save Checkout form details: by PI Websolution – 1.0
Save time in 12 hr format: by PI Websolution – 1.0
Script to block monday, once it is Saturday time gone past 12pm: by PI Websolution – 1.0
senangPay: by senangPay – 3.1.2
Sendcloud | Smart Shipping Service: by Sendcloud B.V. – 2.4.4
Shipment tracking option: by PI Websolution – 1.0
Shipping currency rule: by PI Websolution – 1.0
Shipping method and zone relation: by PI Websolution – 1.0.0
Shipping Method Display Style for WooCommerce: by theDotstore – 3.7.7
Shipping method dropdown for WooCommerce: by PI Websolution – 1.0.26
Shipping option for DTT plugin: by PI Websolution – 1.0.3
Side Cart WooCommerce: by XootiX – 2.1
Simple Custom Post Order: by Colorlib – 2.5.0
SiteOrigin Widgets Bundle: by SiteOrigin – 1.15.8
SO Page Builder Animate: by Dunhakdis – 0.5
Special Working date & Special Timing Pro: by PI Websolution – 1.0.7.10
Speculative Loading: by WordPress Performance Team – 1.1.0
STCPay for Hyperpay Payment Gateway for WooCommerce: by Hyperpay Team – 1.0
Store Hours Manager for WooCommerce: by BizSwoop a CPF Concepts
LLC Brand – 4.0.4

Stripe Payment Gateway for WooCommerce ( Basic ): by WebToffee – 3.4.9
Support proto star: by PI Websolution – 1.3
SureTriggers: by SureTriggers – 1.0.34
SVG Support: by Benbodhi – 2.3.18
TeraWallet: by StandaloneTech – 1.5.5
Test jQuery Updates: by The WordPress Team – 1.0.1
Time slot rule for shipping: by PI Websolution – 1.1
TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.7.9

Use options for delivery type: by PI Websolution – 1.1
User Role Editor: by Vladimir Garagulya – 4.53.1
Vat field for invoice: by PI Websolution – 1.0
Wallet Premium: by Hoicker – 2.8
Webba Booking (Premium): by WebbaPlugins – 5.0.44
wePOS - Point Of Sale (POS) for WooCommerce: by weDevs – 1.1.6
Woo Add Custom States: by Trusted Technology Solutions (TrusTech) – 1.8.5
Woo All Products For Subscriptions: by Woo – 4.1.5 (update to version 6.0.2 is available)
WooCommerce Advance Cash On Delivery PRO: by CodeRockz – 1.0.8
WooCommerce Amazon Fulfillment: by Never Settle – 3.3.5
WooCommerce Attribute Stock (Lite): by Mewz – 1.7.10
WooCommerce AvaTax: by SkyVerge – 1.16.5 (update to version 2.8.0 is available)
WooCommerce Blocks: by Automattic – 10.8.1
WooCommerce Checkout Manager: by QuadLayers – 4.9.9
WooCommerce Deposits: by WooCommerce – 2.1.1 (update to version 2.3.1 is available)
WooCommerce Extra Fees Plugin: by theDotstore – 3.9.6
WooCommerce Legacy REST API: by WooCommerce – 1.0.4
WooCommerce Menu Cart: by WP Overnight – 2.12.0
WooCommerce Mix and Match Products: by Kathy Darling – 2.1.3 (update to version 2.7.7 is available)
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.3.2
WooCommerce Open Close: by Pluginbazar – 4.2.8
WooCommerce Order Test - WP Fix It: by WP Fix It – 2.2
WooCommerce Payments: by Automattic – 4.5.2 (update to version 8.1.1 is available)
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce PayPal Payments: by WooCommerce – 2.6.1 (update to version 2.9.0 is available)
WooCommerce PDF Invoices, Packing Slips, Delivery Notes & Shipping Labels: by WebToffee – 2.7.5
WooCommerce Point of Sale: by Webkul – 3.5.0
WooCommerce Price Based on Country: by Oscar Gare – 3.2.0
WooCommerce Role Based Methods: by WPBackOffice – 2.4.2 (update to version 2.5.2 is available)
WooCommerce Smart COD: by woosmartcod.com – 1.6.1
WooCommerce Smart Coupons: by StoreApps – 9.0.1 (update to version 9.8.3 is available)
WooCommerce Stripe Gateway: by WooCommerce – 6.2.2
WooCommerce Subscriptions: by WooCommerce – 5.0.0 (update to version 6.6.2 is available)
WooCommerce Weight Based Shipping: by weightbasedshipping.com – 5.3.22
WOOCS - WooCommerce Currency Switcher: by realmag777 – 1.3.8
Woo Discount Rules: by Flycart – 2.4.2
WOOF - WooCommerce Products Filter: by realmag777 – 1.2.6.4
Woo Product Bundles: by Woo – 7.1.0 (update to version 8.0.3 is available)
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.5.5
WPBakery Page Builder: by Michael M - WPBakery.com – 6.10.0
WPC AJAX Add to Cart for WooCommerce: by WPClever – 1.6.2
WPC Composite Products for WooCommerce: by WPClever.net – 3.0.4
WPC Product Bundles for WooCommerce: by WPClever – 7.3.1
WPC Product Bundles for WooCommerce (Premium): by WPClever – 7.3.1
WPC Product Timer for WooCommerce: by WPClever – 3.3.0
WP Crontrol: by John Blackbourn – 1.16.3
WPC Variations Radio Buttons for WooCommerce: by WPClever – 3.2.5
WP Mail Logging: by Wysija – 1.10.4
WP Mail SMTP: by WPForms – 2.4.0
WPML Multilingual CMS: by OnTheGoSystems – 4.6.8
WPML String Translation: by OnTheGoSystems – 3.2.8
WP Super Cache: by Automattic – 1.11.0
YayMail - WooCommerce Email Customizer: by YayCommerce – 2.8.3
YITH WooCommerce Deposits and Down Payments Premium: by YITH – 1.13.0
YITH WooCommerce Dynamic Pricing and Discounts Premium: by YITH – 1.6.4
Yoast SEO: by Team Yoast – 22.6

### Dropin Plugins () ###

object-cache.php: Performance Lab Server Timing Object Cache Drop-In

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 209 KB

### WC Pages ###

Shop base: #347 - /shop-page/
Cart: #7 - /cart/ -  This page's content is overridden by custom template content
Checkout: #8 - /checkout/ -  This page's content is overridden by custom template content
My account: #9 - /my-account/
Terms and conditions: #2197 - /terms/

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-09-10 02:03:06 +05:30
Options: ✔
Notes: 70
Onboarding: completed

### Action Scheduler ###

Complete: 17,142
Oldest: 2024-08-09 14:51:11 +0530
Newest: 2024-09-09 14:12:57 +0530

Pending: 4
Oldest: 2024-09-09 14:13:02 +0530
Newest: 2024-09-10 07:18:30 +0530

Failed: 52
Oldest: 2023-02-12 07:36:03 +0530
Newest: 2024-09-03 13:09:39 +0530


### Status report information ###

Generated at: 2024-09-09 14:12:59 +05:30
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rajeshsingh520** [comment] 2024-09-10 12:00
I found when i use IntegrationInterface for loading my JS then it works with the Block based theme but now i am having another issue in Firefox, in firefox extension data is not passed in properly to my block it works 60% of time but if we use browser arrow key to go back and forward then suddenly module brakes as it did not receive the extension data that is needed by module 

use Automattic\WooCommerce\Blocks\Integrations\IntegrationInterface;

**Comment by wavvves** [comment] 2024-09-13 18:51
Hi @rajeshsingh520, thank you for reporting.
I suspect that this might be caused by saved template data, can you navigate to Appearance -> Editor and inspect the Checkout template? If it has saved changes maybe try to revert it to the original state?

**Comment by mikejolley** [comment] 2024-09-16 11:50
> I found when i use IntegrationInterface for loading my JS then it works with the Block based theme 

Glad the initial issue is resolved.

> in firefox extension data is not passed in properly to my block it works 60% of time but if we use browser arrow key to go back and forward then suddenly module brakes as it did not receive the extension data that is needed by module

Add error handling to detect if the data is present. It may be running too early before the data is repopulated. This is related to caching.

I will close this because the original issue was not a problem in blocks. Create a new issue if you discover a problem elsewhere with reproduction steps.

Thanks

**Closed as completed by mikejolley** 2024-09-16 11:50 UTC
Labels: Bug, needs: author feedback, Checkout, type: community contribution, Rubik

**Comment by two-yearshell** [comment] 2025-01-29 15:25
This answer’s worth seeing https://lnkr.fun/5b0557d
