### ISSUE TITLE
WooCommerce Setup Wizard broken on multisite installs

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#44119] opened 2024-01-26 14:51 UTC
### Describe the bug

Whenever accessing `WooCommerce > Home` on a multisite install, it gets stuck on the preloader page with the following error:
<img width="1237" alt="Screenshot 2024-01-26 at 08 31 34" src="https://github.com/woocommerce/woocommerce/assets/15730971/00683a7b-6a87-4dc1-be35-4f51b34a9cb4">

<img width="419" alt="Screenshot 2024-01-26 at 08 42 10" src="https://github.com/woocommerce/woocommerce/assets/15730971/5835ad58-65e1-41c2-8ec7-055640c4746d">

Note: this issue was also reported on: https://wordpress.org/support/topic/stuck-at-woocommerce-setup-wizard/

### Expected behavior

Users on a multisite install should be able to proceed with their store setup as any other WooCommerce store.

### Actual behavior

Users are greeted with a preloader and an `invalid_json` error.

### Steps to reproduce

1. Create a multisite subdirectory install
2. Install WooCommerce on the main network site
3. Activate WooCommerce on a subsite
4. Access WooCommerce > Home

Example of site config from LocalWP:

<img width="857" alt="Screenshot 2024-01-26 at 08 51 07" src="https://github.com/woocommerce/woocommerce/assets/15730971/6023b939-ef8c-4a42-8a41-819065daebc6">

### WordPress Environment

.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nefeline** [comment] 2024-01-26 17:58
Update: I did an additional test here & was able to confirm that this problem only happens when the network configuration rules in the .htaccess file are not prepared yet for a multisite install: whenever those are added (from Network Admin > Settings > Network Setup), everything works as expected; that’s the only way to reproduce the problem so far, so its safe to consider it an edge case.

**Comment by Aljullu** [comment] 2024-01-29 08:43
FYI: in the .org forum, a user [reported](https://wordpress.org/support/topic/stuck-at-woocommerce-setup-wizard/#post-17377640) they can reproduce in a non-multisite install.

**Comment by psealock** [comment] 2024-01-30 02:36
I'm unable to reproduce on JN with multisite, and it looks like this is why

> was able to confirm that this problem only happens when the network configuration rules in the .htaccess file are not prepared yet for a multisite install

Waiting on further information from user.

**Comment by andfinally** [comment] 2024-02-12 11:56
I am seeing a similar issue with a WordPress Local by Flywheel single site – WooCommerce loads, but I'm unable to view the home, because I'm stuck on a blank setup-wizrad page. I am viewing over http. I see @nefeline is using the `multisite.local` domain, but her browser is saying `Not Secure`, so maybe she's also on http and it's something to do with the protocol. I notice the user on the .org forum is also viewing over http. Or maybe it's something specific to Local.

<img width="500" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1647564/40d326cb-267d-4cac-9093-3156301f6dc0">


<img width="500" alt="image" src="https://github.com/woocommerce/woocommerce/assets/1647564/16ff6183-1b33-45dd-b562-c23667ea3720">

**Comment by chihsuan** [comment] 2024-05-06 10:04
I was able to reproduce this issue using the steps provided with LocalWP.

![Screenshot 2024-05-06 at 17 52 37](https://github.com/woocommerce/woocommerce/assets/4344253/e22e0d39-2a46-4aa0-a232-afb70b67a7c2)

I found that this is because **the subsite's permalinks are not set up correctly**, resulting in a 404 error when trying to access the REST API endpoints.

Some related issues:

- https://wordpress.org/support/topic/wp-rest-api-returning-404s/
- https://stackoverflow.com/questions/34670533/wordpress-rest-api-wp-api-404-error-cannot-access-the-wordpress-rest-api
- https://wordpress.org/support/topic/site-health-rest-api-returns-a-404/

I'm not familiar with the Local WP, but one way to fix this is to add a `.htaccess` file to the subsite's WP directory with the following content:

```
# BEGIN WordPress
# The directives (lines) between "BEGIN WordPress" and "END WordPress" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
```

Or just using Nginx instead of Apache.

Since this issue is not related to WooCommerce, I'm closing this issue. If anyone still faces this issue and think it's related to WooCommerce, feel free to reopen this issue. Thanks!

**Closed as completed by chihsuan** 2024-05-06 10:04 UTC
Labels: Bug, plugin: woocommerce, Onboarding
