### ISSUE TITLE
Copy Update - store looking great message

### ISSUE THREAD

**Issue by ilyasfoo** [woothemes/woocommerce#38040] opened 2023-04-28 11:27 UTC
Originally filed by @thatmikebal in https://github.com/Automattic/wc-calypso-bridge/issues/1046

> Just need a space after the emoji in the message that says "Your store is looking great!...."

![Image](https://user-images.githubusercontent.com/89872780/224379414-ea867005-feca-4977-a888-b77ef00c851c.png)

### Acceptance criteria

1. Update the copy to have spacing after emoji and add period at the end.
2. Please check if there's any other Snackbar component usage with similar emoji setup and fix them too.

**Comment by igorradovanov** [comment] 2023-05-29 19:22
I'd like to work on this issue.

**Comment by ilyasfoo** [comment] 2023-06-02 08:35
Awesome, thanks @igorradovanov! Let me know if you need help

**Comment by igorradovanov** [comment] 2023-06-07 11:50
I am unable to replicate the problem with emoji spacing on Linux/Windows PCs. It is possible that this issue is specific to the way MacOS renders emojis. There is a [bug ticket ](https://bugs.chromium.org/p/chromium/issues/detail?id=596223&q=596223&can=2)in Chromium that mentions "This issue occurs when displaying emojis in Mac Chrome on a non-retina screen." 

Should we wait for an official fix from the Chromium team, or should we attempt to address the problem ourselves by implementing a fix for non-retina displays using a margin through a media query? Additionally, it seems that there is a missing period at the end of the sentence on multiple notices, so we can definitely resolve that part of this issue.

**Comment by ilyasfoo** [comment] 2023-06-07 13:21
Great catch, @igorradovanov! I think it's fine to attempt to address the problem ourselves. I've looked at the [notices API](https://developer.wordpress.org/block-editor/reference-guides/data/data-core-notices/#createsuccessnotice), and it seems we can utilize the `options.icon` parameter for emojis:

`wp.data.dispatch('core/notices').createNotice('info', 'Notice here', {icon: '🔥'})`

<img width="306" alt="image" src="https://github.com/woocommerce/woocommerce/assets/3747241/15deaa17-68c3-458e-8cf6-93e53ffbaac5">

**Comment by igorradovanov** [comment] 2023-06-12 19:29
Sounds great @ilyasfoo, I'll go over all notices and use the `options.icon` parameter instead of the current solution with the string concatenation.

**Comment by igorradovanov** [comment] 2023-06-12 19:35
Not sure if it's possible to switch the position from left to right using this approach. There is no information in the documentation regarding the position. 

The documentation also states that 'Only used when the type is set to snackbar.' Does that mean we should explicitly set the type for these notices (icons do work even without the explicit type set)? 

Here is an example of the notice that displays the icon on the right side next to the message: https://github.com/woocommerce/woocommerce/blob/90e4ddbf296262d17f9f907b2a57df4205f5e58a/plugins/woocommerce-admin/client/task-lists/fills/tax/index.tsx#L127

**Comment by ilyasfoo** [comment] 2023-06-13 02:28
Good catch, @igorradovanov! We'll have to try your media query approach then, it seems to be more appropriate for our use cases. Do you have a reliable way to reproduce the issue?

**Comment by igorradovanov** [comment] 2023-06-19 19:06
I don't have any Apple devices, but I do have a paid plan of BrowserStack. Should we leave this issue to someone who has actual devices that can reproduce this error?

**Comment by ilyasfoo** [comment] 2023-06-20 01:39
I think BrowserStack should be good enough to reproduce the issue. Perhaps the tricky part is exposing your environment to it, which ngrok may come in handy.

However, if it's too much of a hassle for you, it's fine @igorradovanov. No pressure!

**Comment by Armondal** [comment] 2023-07-27 09:30
I have a MacBook Air (M1, 2020) model. I have tried to recreate this issue. But I couldn't find the issue. I think it is already resolved. 
<img width="1440" alt="Screenshot 2023-07-27 at 3 23 11 PM" src="https://github.com/woocommerce/woocommerce/assets/25416793/9d737eb6-4e10-43e9-89ed-cfe481df282a">

WordPress Environment
WordPress address (URL): https://woocommerce-issue.test/
Site address (URL): https://woocommerce-issue.test/
WC Version: 7.9.0
WP Version: 6.2.2 
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
Language: en_US
External object cache: –
PHP version: 7.4.33
Web server: nginx/1.25.0
Browser: Safari
Mac OS: 13.2 (22D49)

**Comment by igorradovanov** [comment] 2023-07-28 13:43
@Armondal, this issue only occurs on the Chrome browser for Mac. 
@ilyasfoo , I was off due to some private issues, but I'm back in the office now and will take a closer look at the new implementation. In case anyone else wants to work on this one, please feel free to join. :hugs:

**Comment by adrianduffell** [comment] 2023-09-14 09:30
Hey @igorradovanov, did you have a chance to look at this more?

**Comment by adrianduffell** [comment] 2023-09-26 06:52
I'll close this out because I don't believe we are displaying this snackbar anymore. However please just re-open if I'm wrong 😄 

Thanks for your help with this folks!

**Closed as completed by adrianduffell** 2023-09-26 06:52 UTC
Labels: Bug, Good First Issue
