### ISSUE TITLE
the cart icon the sidebar is empty and there is no error anywhere about it

### ISSUE THREAD

**Issue by ElectroYModz** [woothemes/woocommerce#38789] opened 2023-06-19 01:29 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

the cart icon the sidebar is empty and there is no error anywhere about it

### Expected behavior

to show the content of the cart

### Actual behavior

Nothing is show the the div is completly empty

### Steps to reproduce

IDK
it started doing it about a week ago at least

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://promodzshop.com
Site address (URL): https://promodzshop.com
WC Version: 7.8.0
REST API Version: ✔ 7.8.0
WC Blocks Version: ✔ 10.2.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.28
PHP Post Max Size: 2 GB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.84.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.6.12-MariaDB-cll-lve
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.0
WC Database Prefix: wp_
Total Database Size: 98.40MB
Database Data Size: 87.65MB
Database Index Size: 10.75MB
wp_woocommerce_sessions: Data: 2.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_acfw_store_credits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.30MB + Index: 0.36MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.34MB + Index: 0.25MB + Engine InnoDB
wp_addonlibrary_addons: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_addonlibrary_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aioseo_cache: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_aioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_aioseo_posts: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_aws_cache: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_aws_index: Data: 0.25MB + Index: 0.23MB + Engine InnoDB
wp_bpspro_db_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bpspro_login_security: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bpspro_mscan: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bpspro_seclog_ignore: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_burst_goals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_burst_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_burst_statistics: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_dnsmpd: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_cwcfp_conditional_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_edd_adjustmentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_adjustments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_edd_customermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_edd_customer_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_edd_customer_email_addresses: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_edd_logmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_logs: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_edd_logs_api_requestmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_logs_api_requests: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_logs_file_downloadmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_logs_file_downloads: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_edd_notemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_notes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_edd_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_ordermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_orders: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_edd_order_addresses: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_edd_order_adjustmentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_order_adjustments: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_edd_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_edd_order_transactions: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_ee_products_sync_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ee_product_sync_call: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ee_product_sync_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ee_product_sync_profile: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ee_prouct_pre_sync_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_frmt_form_entry: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_frmt_form_entry_meta: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_frmt_form_reports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_frmt_form_views: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_independent_analytics_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_independent_analytics_campaign_urls: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_independent_analytics_referrers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_independent_analytics_referrer_groups: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_independent_analytics_resources: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_independent_analytics_sessions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_independent_analytics_views: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_independent_analytics_visitors: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_independent_analytics_visitors_1_16_archive: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_independent_analytics_wc_orders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_avatar: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_img_optm: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_img_optming: Data: 0.16MB + Index: 0.27MB + Engine InnoDB
wp_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_url_file: Data: 0.06MB + Index: 0.14MB + Engine InnoDB
wp_lmfwc_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lmfwc_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lmfwc_licenses: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_lmfwc_licenses_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_maintenance_page: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mo_discord_linked_user: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 12.45MB + Index: 0.27MB + Engine InnoDB
wp_postmeta: Data: 53.44MB + Index: 2.86MB + Engine InnoDB
wp_posts: Data: 12.52MB + Index: 0.47MB + Engine InnoDB
wp_ppc_exceptions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_ppc_exception_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ppc_roles: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ppi_errors: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ppi_imported: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ppi_runs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ppress_coupons: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_ppress_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ppress_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ppress_formsmeta: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_ppress_meta_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ppress_ordermeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ppress_orders: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_ppress_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ppress_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ppress_subscriptions: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_pp_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_pp_group_members: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_serial_numbers: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_serial_numbers_activations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sfa_abandoned_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_slicewp_affiliates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_slicewp_affiliate_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_slicewp_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_slicewp_commission_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_slicewp_creatives: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_slicewp_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_slicewp_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_slicewp_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_slicewp_payments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_slicewp_payment_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_slicewp_payouts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_slicewp_payout_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_slicewp_visits: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_statistics_exclusions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_statistics_historical: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_statistics_pages: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_statistics_search: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_statistics_useronline: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_statistics_visit: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_statistics_visitor: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_statistics_visitor_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.48MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.31MB + Index: 0.08MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsm_bounceVisits: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_browsers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsm_countries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wsm_dailyHourlyReport: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsm_dateWiseBounce: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_dateWiseBounceRate: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_dateWiseFirstVisitors: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_dateWisePageViews: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_dateWiseVisitors: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_datewise_report: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsm_hourWiseBounce: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_hourWiseBounceRate: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_hourWiseFirstVisitors: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_hourWisePageViews: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_hourWiseVisitors: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_logUniqueVisit: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wsm_logVisit: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wsm_monthlyDailyReport: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsm_monthWiseBounce: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_monthWiseBounceRate: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_monthWiseFirstVisitors: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_monthWisePageViews: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_monthWiseVisitors: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_monthwise_report: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsm_oSystems: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsm_pageViews: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_regions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsm_resolutions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsm_searchEngines: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsm_toolBars: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsm_uniqueVisitors: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_url_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wsm_visitorInfo: Data: 0.00MB + Index: 0.00MB + Engine
wp_wsm_yearlyMonthlyReport: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsm_yearwise_report: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_x_currency: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acoplw_badges: 1
attachment: 537
condition_group: 4
custom_css: 1
customize_changeset: 1
e-landing-page: 2
elementor_library: 61
envato_tk_import: 1
forminator_forms: 3
nav_menu_item: 145
oembed_cache: 1
page: 35
post: 5
product: 58
product_variation: 73
restriction: 4
revision: 1889
shop_coupon: 2
shop_order: 19
shop_order_refund: 2
somdn_tracked: 7
udb_widgets: 1
wpforms: 4
x-currency: 15
x-currency-switcher: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (53) ###

Acowebs Product Labels For Woocommerce: by Acowebs – 1.5.1
Advanced Woo Search: by ILLID – 2.81
Basic User Avatars: by Stranger Studios – 1.0.7
Custom Order Status Manager for WooCommerce: by Bright Plugins – 1.0
PublishPress Capabilities: by PublishPress – 2.8.1
Checkout Field Editor and Manager for WooCommerce: by Acowebs – 2.2.13
Custom Order Webhook: by ElectroY Modz – 1.0
Dark Mode for WP Dashboard: by Naiche – 1.2.3
Discord Auto Roles: by ElectroY Modz – 1.0
Discord Link: by ElectroY Modz – 1.0
Duplicate Menu: by Jonathan Christopher – 0.2.2
Elementor Pro: by Elementor.com – 3.13.2
Elementor: by Elementor.com – 3.13.4
Envato Elements: by Envato – 2.0.12
Error Log Monitor: by Janis Elsts – 1.7.6
Forminator: by WPMU DEV – 1.24.1
Free Downloads WooCommerce Pro: by WP Enhanced – 3.5.3
Frontend Reset Password: by WP Enhanced – 1.2.1
Hostinger: by Hostinger – 1.1.0
Imagify: by Imagify – Optimize Images & Convert WebP – 2.1.1
Jetpack: by Automattic – 12.2.1
JWT Authentication for WP-API: by Enrique Chavez – 1.3.2
License Manager for WooCommerce (Free): by LicenseManager – 2.2.8
LiteSpeed Cache: by LiteSpeed Technologies – 5.4
Mailchimp for WooCommerce: by Mailchimp – 2.8.3
Maintenance Page: by ThemeGrill – 1.0.8
Order Status Control for WooCommerce: by Bright Plugins – 1.0.2
Permalink Manager Pro: by Maciej Bis – 2.3.1
Popup API Trigger: by ElectroY Modz – 1.0
PublishPress Permissions: by PublishPress – 3.9.3
WP REST API: by WP REST API Team – 2.0-beta15
Restrict User Access: by Joachim Jensen - DEV Institute – 2.4.2
Sellix Pay: by Sellix io – 1.9.3
SliceWP: by SliceWP – 1.0.94
Orbit Fox Companion: by Themeisle – 2.10.25
Unlimited Elements for Elementor: by Unlimited Elements – 1.5.69
User Role Editor: by Vladimir Garagulya – 4.63.3
User Switching: by John Blackbourn & contributors – 1.7.0
Visibility Logic for Elementor: by StaxWP – 2.3.4
Checkout with Cash App on WooCommerce: by The African Boss – 5.2.1
Open Graph and Twitter Card Tags: by WPExperts – 3.3.0
WooCommerce Stripe Gateway: by WooCommerce – 7.4.1
WooCommerce Payments: by Automattic – 6.0.0
WooCommerce PayPal Payments: by WooCommerce – 2.1.0
WooCommerce Shipping & Tax: by WooCommerce – 2.2.5
WooCommerce: by Automattic – 7.8.0
Wordfence Security: by Wordfence – 7.9.3
WP Discord Invite: by Sarvesh M Rao – 2.4.1
WP Mail SMTP: by WP Mail SMTP – 3.8.0
WP Socials Settings: by ElectroY Modz – 1.0.1
WPForms Lite: by WPForms – 1.8.2.1
X-Currency-Pro: by DoatKolom – 1.1.0
X-Currency: by DoatKolom – 1.4.1

### Inactive Plugins (3) ###

All-in-One WP Migration: by ServMask – 7.75
Sold Out Badge for WooCommerce: by Charlie Etienne – 4.4.0
XML Sitemap Generator for Google: by Auctollo – 4.1.11

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #98 - /shop/
Cart: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: #101 - /my-account/
Terms and conditions: #940 - /terms-of-service/

### Theme ###

Name: Hestia
Version: 3.0.30
Author URL: https://themeisle.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://promodzshop.com
Subscriptions-core Library Version: 5.7.2
Subscription Statuses: –
WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No

### Store Setup ###

Country / State: United Kingdom (UK)

### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method

Sellix: products

### WooCommerce PayPal Payments ###

Onboarded: –
Shop country code: GB
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-06-19 15:45:53 +00:00
Options: ✔
Notes: 90
Onboarding: skipped

### WooCommerce Payments ###

Version: 6.0.0
Connected to WPCOM: Yes
Blog ID: 216315433
Account ID: acct_1MnBIxCOG7L3OrRd

### Action Scheduler ###

Complete: 765
Oldest: 2023-05-19 03:42:21 +0000
Newest: 2023-06-18 22:40:43 +0000

Failed: 94
Oldest: 2023-03-04 10:53:01 +0000
Newest: 2023-06-18 21:49:18 +0000

Pending: 7
Oldest: 2023-06-19 22:40:43 +0000
Newest: 2023-06-23 13:35:18 +0000

### Status report information ###

Generated at: 2023-06-19 01:28:32 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment] 2023-06-19 04:44
Probably a duplicate of this [issue](https://github.com/woocommerce/woocommerce/issues/38735).

**Closed as completed** 2023-06-19 15:40 UTC
Labels: Bug, type: community contribution
