### ISSUE TITLE
[Enhancement]: Make Store API more accessible to mobile app builder by NO required Nonce Token - only API KEY is enough.

### ISSUE THREAD

**Issue by sanskritkm** [woothemes/woocommerce#38936] opened 2023-06-26 09:45 UTC
### Describe the solution you'd like

I have already read this: https://github.com/woocommerce/woocommerce-blocks/tree/trunk/src/StoreApi I really love this way to build flutter mobile by using exist woocommerce as backend for mobile app.

Nowadays, API call is like this way `curl "https://example-store.com/wp-json/wc/store/v1/products"` it not just only easy for coding but it make API call a lot accessible to other platform like No-Code mobile builder platform, it's support API call only by this way: `curl "https://example-store.com/wp-json/wc/store/v1/cart"` and API Key can't be Nonce Token.

One thing it is impossible for other platforms connect to Woocommerce is **POST cart** in Woocommerce (curl "https://example-store.com/wp-json/wc/store/v1/cart") it is requested Nonce Token as a second step to request to this API call. Document here: `https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/nonce-tokens.md` this nonce token can only create in Wordpress side.

### Describe alternatives you've considered

No-Code platform build mobile app can't include Nonce Token in the header when request (nonce token need PHP to generate code). 

If Woocommerce can improve not required Nonce Token in the header (Only API KEY, Ex: Customer Key & Secret Key) than a lot mobile (no-code builder) developer will use Woocommerce as backend for e-commerce in the future.

[Suggestion] Could we improve it by using only Woocommerce API Key (CustomerKey & Secret Key) rather than require additional Nonce Token? Possible?

Thanks,

**Comment by lsinger** [comment] 2024-02-16 09:27
Also see #42341 -- might be the same issue?

**Comment by dinhtungdu** [comment] 2024-07-23 03:13
I changed the tem to Rubik as this issue relates to Cart and Checkout.

**Comment by mikejolley** [comment] 2024-07-23 09:38
This is a duplicate of https://github.com/woocommerce/woocommerce/issues/42341 so we can track this request there. Marking closed.

**Closed as completed by mikejolley** 2024-07-23 09:38 UTC
Labels: Enhancement, REST/Store API/Webhooks, type: community contribution, Rubik
