### ISSUE TITLE
Settings tab not loading XHR and missing tbody data on Shipping Zones

### ISSUE THREAD

**Issue by tradesouthwest** [woothemes/woocommerce#43305] opened 2024-01-04 22:21 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When opening Settings > Shipping tab, Shipping zones do not display on this admin page. (...wp-admin/admin.php?page=wc-settings&tab=shipping&section) 

tfoot (Rest of the world default shipping zone) shows and the thead with Zone name / Regions / Shipping methods text shows but, the whole tbody tag has not content displayed whatsoever. 
![bug1Screenshot_2024-01-04_15-07-21](https://github.com/woocommerce/woocommerce/assets/2350010/dea92273-b6d3-4582-afd3-ead500f8c55e)

It appears as if the XHR for that one specific endpoint is not loading. EVERY tab or sub-setting on every tab will load at the least: wp-json/wp/v2/me?context and a few other XHRs like, wp-json/wc-admin/onboarding/tasks - This bug page (...admin.php?page=wc-settings&tab=shipping&section) does NOT load any XHR. The Console only shows this message for Shipping default tab (all other shipping subtabs load XHR) `The resource at “https://thecoloradocookiecompany.com/stage1223/wp-content/plugins/woocommerce/assets/client/admin/components/index.js?ver=8.4.0” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly.`

### Expected behavior

When saving a new Shipping zone, WC should show that saved shipping zone on said page/tab. I can see the saved zones in the database of WP instance in the `woocommerce_` options and in (wordpress)`_options` tables. I do NOT, however see the options appear rendered on the Shipping admin page.

Note that shipping zones will show in cart and checkout. So options ARE saving, just not displaying.

### Actual behavior

Administrator should see ALL Shipping Zones.

### Steps to reproduce

1. Read history at https://wordpress.org/support/topic/wc-shipping-zones-missing/
2. Open Woo > Settings > Shipping
3. Done with Storefront and no plugins except Woocommerce active.
4. Tried uploading files from 8.5.0 beta1 but did not change anything.

### WordPress Environment

SSR: https://gist.github.com/tradesouthwest/97771566d8670a6f211fdfd2fda81947 

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tradesouthwest** [comment] 2024-01-05 17:16
I did run across a wp-includes/js error `Uncaught TypeError: h is undefined
    <anonymous> https://thecoloradocookiecompany.com/stage1223/wp-includes/js/wp-auth-check.min.js?ver=6.4.2:2
    jQuery 7
    xhr https://thecoloradocookiecompany.com/stage1223/wp-includes/js/heartbeat.min.js?ver=6.4.2:2
    jQuery 4
[wp-auth-check.min.js:2:652](https://thecoloradocookiecompany.com/stage1223/wp-includes/js/wp-auth-check.min.js?ver=6.4.2)`

Looks like there is an undefined constant or var in wp-includes/js/wp-auth-check.min.js?ver=6.4.2 

![bug2Screenshot_2024-01-05_10-12-34](https://github.com/woocommerce/woocommerce/assets/2350010/741bbd47-7951-4136-98d9-144e3f973d60)
![bug3Screenshot_2024-01-05_10-13-18](https://github.com/woocommerce/woocommerce/assets/2350010/ff289214-d64c-4f0d-bc00-9189a0bad0f6)

I can follow up on this report, as a WordPress bug at some point.

**Comment by tradesouthwest** [comment] 2024-01-05 21:21
And my fix for this was to hard code a loop into the table body:
    
    <tbody class="wc-shipping-zone-rows wc-shipping-tables-tbody">
	&gt;?php 
	$data_store = WC_Data_Store::load( 'shipping-zone' );
        $raw_zones = $data_store->get_zones();
    foreach ( $raw_zones as $zone ) { 
    ?&lt;
	<tr><td width="1%" class="wc-shipping-zone-custom"></td>
		<td class="wc-shipping-zone-name">
			<?php echo $zone->zone_name; ?>
		</td>
		<td class="wc-shipping-zone-region">
			<?php esc_html_e( 'regions', 'woocommerce' ); ?></td>
		<td class="wc-shipping-zone-methods">
			<ul>
			<?php
		
			echo '<li>[foreach loop on methods]</li>'; 
		
			?>
			</ul>
		</td>
		<td class="wc-shipping-zone-actions">
			<a class="wc-shipping-zone-action-edit" 
			href="admin.php?page=wc-settings&amp;tab=shipping&amp;zone_id=<?php echo $zone->zone_id; ?>"><?php esc_html_e( 'Edit', 'woocommerce' ); ?></a>
		</td></tr>
		&gt;?php
    }
    ?&lt;

	</tbody>

**Comment by tradesouthwest** [comment] 2024-01-08 14:36
To see complete patch visit: <a href="http://snippwiki.com/public-snippet.php?pub_id=110" title="share link to this snippet">View: Woocommerce get shipping methods get zone locations WC_Shipping_Zone class tbody fix missing shipping zones and regions.</a>

**Comment by tradesouthwest** [comment] 2024-02-26 16:46
Any updates on this issue? I am moving the site to a new host and loading fresh installs of WP/Woo. I'm sure this will fix but would love to know how this effects Settings in Woo and effects customer Checkout experience will not allow customer to checkout due to "No shipping methods chosen" error.

**Comment by coreymckrill** [comment] 2024-05-08 16:40
Hi @tradesouthwest, I just tried to reproduce this issue on WooCommerce 8.8.3, and wasn't able to. I suspect any problem that may have been in the WC code when you first reported this has since been fixed, so I'm going to close the issue. But if you are still seeing this problem, and can provide some detailed step-by-steps to get it to happen, please reopen!

**Closed as not planned by coreymckrill** 2024-05-08 16:40 UTC
Labels: Bug, Settings, type: community contribution

**Comment by drtikosti** [comment] 2025-01-07 16:16
Having exact same issue now, just discovered it today - did the usual troubleshooting (off other plugins, update templates, etc...) and issue still persists. Shipping zones not shown - but visible/applicable in the checkout, checkout works, orders can be submitted.

issue is, i'm unable to edit shipping zones/methods - thus unable to change shipping costs.

**Comment by coreymckrill** [comment] 2025-01-11 00:18
@drtikosti can you provide step-by-step instructions of how to replicate the issue with WooCommerce as the only active plugin?
