### ISSUE TITLE
WooCommerce: Content under my account is not accessible

### ISSUE THREAD

**Issue by vonrotzmario** [woothemes/woocommerce#31021] opened 2021-10-24 19:27 UTC
Hello

On my online shop marymar.ch the content under my account (e.g. order received) is not available / not working. In the image attached you can find the error message.

Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issu
<img width="1280" alt="Bildschirmfoto 2021-10-24 um 21 08 00" src="https://user-images.githubusercontent.com/93096886/138609571-cf1a71cb-eea1-4dd5-9be8-672392d07b7a.png">
e. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by rodelgc** [comment] 2021-10-25 14:13
Hi @vonrotzmario,

I can access the `/my-account/edit-account` page just fine on my test site using WC 5.8 and Storefront as the theme:

<img width="848" alt="Screen Shot 2021-10-25 at 9 57 06 PM" src="https://user-images.githubusercontent.com/4509348/138709455-ebc805a3-28cc-4c30-b3a8-d22c00fe4340.png">

Could it be that you're accessing the wrong url? As that error message appears when you use a non-existent URL.

It will be good to share the exact steps to replicate this issue. Without these details, we can’t fully evaluate this concern. 

Also, it will be great if you could share your current System Status Report. You can get it by navigating to the `WooCommerce / Status` section of your site. Once there, click on the `Get system report` button and then copy it by clicking on the `Copy for support` button. Then paste it here in a comment.

**Comment by vonrotzmario** [comment] 2021-10-25 20:41
Hello

Thanks for your feedback.

This error occurred when submitting an order on marymar.ch. And also when
logging in to my account I cannot open the other pages under my account.

Best regards
Mario


Am Mo., 25. Okt. 2021 um 16:13 Uhr schrieb rodelgc ***@***.***

**Comment by rodelgc** [comment] 2021-10-26 06:48
Thank you @vonrotzmario for the response. Since I couldn't replicate the issue, and that the issue only happens on your site so far, it could be that several of your plugins or themes are causing it. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
﻿
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Also, you may use these support channels:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
﻿
If you confirm the bug, please provide us with clear steps to reproduce it.
﻿
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take another look.

**Closed as completed by rodelgc** 2021-10-26 06:48 UTC
Labels: Bug, status: can't reproduce, needs: triage feedback, type: support request
