### ISSUE TITLE
woocommerce_order_note_added hook not trigger when Customer notes added programically

### ISSUE THREAD

**Issue by totalard** [woothemes/woocommerce#37591] opened 2023-04-06 10:31 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

```
add_action('woocommerce_order_note_added', function ($comment_id, $orderid) {
//code run here
}, 10, 2);
```

This code wont trigger 

```
$order = wc_get_order($orderid);
$order->add_order_note($_POST['content'], 1, true);
```

seems bug, please fix

### Expected behavior

hook must trigger as notes added

### Actual behavior

Hook not triggering

### Steps to reproduce

Just use the simple code to find works or not

### WordPress Environment

PHP 8
wp 6.1.1
woo 7.5.0

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment] 2023-04-28 20:18
Hi @totalard!

Thanks for reaching out. We couldn't reproduce what you've described. `add_order_note()` does fire the hook `woocommerce_order_note_added` after adding the note.
See https://github.com/woocommerce/woocommerce/blob/a7b1beaa05f303d8b933548f421fe2b2d54859c0/plugins/woocommerce/includes/class-wc-order.php#L1931.

Please notice that the relevant post types must be in place, so you should only add note orders after, at least, the `init` hook has ran, so that WC has initialized the relevant parts. We also noticed in your test code, that you're assuming the second argument to the action callback (`$orderid`) is an order ID, but in reality it's a full order object.

I'm going to close this for now, but feel free to re-open if you can consistently reproduce and can provide some more details on this.

**Closed as completed by jorgeatorres** 2023-04-28 20:18 UTC
Labels: Bug, Order Management, needs: developer feedback, plugin: woocommerce, type: community contribution
