### ISSUE TITLE
Woocommerce admin running slow after 6.0.0 update

### ISSUE THREAD

**Issue by andy-jam** [woothemes/woocommerce#31481] opened 2021-12-20 00:11 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Updated from 5.8 to 6.0.0

Admin immediately running slow. 

### Expected behavior

No change in responsiveness. 

### Actual behavior

Over 8 seconds to present any page in admin.
Front end still running fine.

### Steps to reproduce

On a site with a substantial number of products (mine had 400,000):
Upgrade from 5.9.0 to 6.0.0

Wait for database update and scheduled tasks to complete. 

Load up query monitor.
Go to any product, order or pretty much any page in admin.
This query pops up 7 times, each taking over a second to run:
SELECT wp_posts.ID
FROM wp_posts
LEFT JOIN wp_term_relationships
ON (wp_posts.ID = wp_term_relationships.object_id)
WHERE 1=1
AND ( wp_term_relationships.term_taxonomy_id IN (2,3,4,5) )
AND wp_posts.post_type = 'product'
AND ((wp_posts.post_status = 'publish'))
GROUP BY wp_posts.ID
ORDER BY wp_posts.post_date DESC
LIMIT 0, 1

I've rolled back to 5.9.0 and the site's admin is back up to speed. 

Not sure how to proceed from here. 

Sorry, the status report I have is from after I rolled back. I can't leave the live site slow. 

The 2 out of date plugins were updated prior to upgrading woocommerce. 

I'll have to clone the site to work the problem. 

Cheers, 

Andy 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.hvac-sanitary.co.uk
Site address (URL): https://www.hvac-sanitary.co.uk
WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.1.0
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.8.0
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.26
PHP Post Max Size: 50 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.79.1
OpenSSL/1.1.1l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.32-MariaDB
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: wp_
Total Database Size: 3519.78MB
Database Data Size: 1695.68MB
Database Index Size: 1824.10MB
wp_woocommerce_sessions: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.27MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 2.02MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wolseley_categories: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wolseley_manufacturers: Data: 0.09MB + Index: 0.10MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.39MB + Index: 0.67MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.39MB + Index: 0.28MB + Engine InnoDB
wp_aws_cache: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_aws_index: Data: 656.00MB + Index: 504.97MB + Engine InnoDB
wp_check_email_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 1.39MB + Engine InnoDB
wp_csp3_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.31MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 619.00MB + Index: 1015.97MB + Engine InnoDB
wp_posts: Data: 228.78MB + Index: 105.50MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 36.59MB + Index: 24.58MB + Engine InnoDB
wp_term_taxonomy: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_usermeta: Data: 0.50MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.17MB + Index: 0.23MB + Engine InnoDB
wp_wc_order_stats: Data: 0.17MB + Index: 0.20MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 44.58MB + Index: 87.77MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdp_orders: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_wdp_order_items: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wdp_product_collections: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdp_rules: Data: 0.30MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Data: 97.64MB + Index: 78.80MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 4.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 14700
nav_menu_item: 14
page: 48
product: 407785
revision: 83
seedprod: 2
shop_order: 1028
shop_order_refund: 331

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Advanced Dynamic Pricing for WooCommerce: by AlgolPlus – 3.3.2
Advanced Woo Search: by ILLID – 2.42
The SEO Framework: by The SEO Framework Team – 4.2.2
Autoptimize: by Frank Goossens (futtta) – 2.9.3
Coming Soon Page, Maintenance Mode & Landing Pages by SeedProd: by SeedProd – 6.6.0
Yoast Duplicate Post: by Enrico Battocchi and Team Yoast – 4.2
CAOS: by Daan from FFW.Press – 4.1.9
Index WP MySQL For Speed: by Ollie Jones – 1.3.3
Really Simple SSL: by Really Simple Plugins – 5.2.0
Safe SVG: by Daryll Doyle – 1.9.9
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.16.66.25

WooCommerce Brands: by WooCommerce – 1.6.25
WooCommerce PayPal Pro Hosted: by WooCommerce – 1.0.23
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.46
WooCommerce: by Automattic – 5.9.0 (update to version 6.0.0 is available)

### Inactive Plugins (1) ###

Query Monitor: by John Blackbourn – 3.7.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Basket: #7 - /basket/
Checkout: #8 - /checkout/
My account: ❌ Page visibility should be public
Terms and conditions: #68 - /about-us/terms-and-conditions/

### Theme ###

Name: HVAC
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 3.9.1
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: hvac/woocommerce/single-product/product-image.php

### Action Scheduler ###

Complete: 1,569
Oldest: 2021-11-19 10:08:14 +0000
Newest: 2021-12-20 00:04:15 +0000

### Status report information ###

Generated at: 2021-12-20 00:07:29 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment] 2021-12-20 10:29
Hi @andy-jam ,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using WooCommerce 6.0.0 version and WordPress 5.8.2 version.

Please find below screencast for reference :


https://user-images.githubusercontent.com/94531721/146729769-239bdb83-e9a9-4626-870d-5d540421be8a.mp4

Please provide us more detailed and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by andy-jam** [comment] 2021-12-20 10:49
Hi Swati,

Thanks for looking into this.

You're not doing an equivalent test.

You only have a tiny number of products. Any new database performance issues are concealed by the power of your servers.

Retry with 400,000 products. I doubt they need image attachments so you should be able to load the data up quickly.

Additionally you should also be able to spot that the same query is running 7 times as reported. Query Monitor should be able to spot that on your test install. Reducing this to one instance will bring performance back in line with woocommerce 5.9.0

If you want specifics please let me know so I can help.

Cheers,

Andy






Cheers,

Andy


https://www.SiteBoosting.co.uk

________________________________

**Comment by swatipawarGS** [comment] 2021-12-20 13:32
Hi @andy-jam ,

Thank you pointing out the mistake. We are now able to reproduce the issue on our end with huge number of products using WooCommerce 6.0.0 version and  WordPress 5.8.2 version. 

Please find below screenshot for reference :

![#31481](https://user-images.githubusercontent.com/94531721/146767703-2e5e7ebe-0570-431c-b033-2996dc30f249.jpg)


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by andy-jam** [comment] 2021-12-20 13:39
Hi Swati,

Fantastic news!

To have the fault found is half the problem solved.

Will there be an update here when the issue is resolved?

Cheers,

Andy

Cheers,

Andy



https://www.SiteBoosting.co.uk

________________________________

**Comment by namiokuzono** [comment] 2021-12-22 16:22
Reported also 33321457-hc

**Comment by andy-jam** [comment] 2022-01-12 17:52
With the new version 6.1 of Woocommerce is this fixed yet?
If not any idea of when?
Cheers,

Andy

**Comment by andy-jam** [comment] 2022-02-13 10:02
6.1.1 and 6.2 have been released. Is the bug fixed yet?
Cheers,
Andy

**Comment by andy-jam** [comment] 2022-02-13 10:04
> 
Where is this? 

"Reported also 33321457-hc"

**Comment by samiahmedsiddiqui** [comment] 2022-03-15 11:22
+1

**Comment by samiahmedsiddiqui** [comment] 2022-03-15 11:24
I am also noticing a similar issue on one of my clients WooCommerce site. Is there any ETA to fix issue?

**Comment by chihsuan** [comment] 2023-03-30 11:07
This has been fixed by https://github.com/woocommerce/woocommerce/issues/34833

**Closed as completed by chihsuan** 2023-03-30 11:07 UTC
Labels: Bug, plugin: woocommerce
