### ISSUE TITLE
HPOS meta data not saving in checkout

### ISSUE THREAD

**Issue by dipin-bajra** [woothemes/woocommerce#39309] opened 2023-07-19 08:59 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

So I've tried to add a custom data to the order meta using HPOS method using the following code 

```
add_action( 'woocommerce_order_status_processing', 'cm_order_meta_test' );
add_action( 'woocommerce_order_status_completed', 'cm_order_meta_test' );
function cm_order_meta_test( $order_id ) {
	$order = wc_get_order($order_id);
	$order->update_meta_data('_test_hpost_value', 'ik');
	$order->save();
}
```

The data is not being saved in the order meta at the initial checkout process but if we changed or update the order status from the backend then the data is being saved in that particular meta. Please check for the possible issue occurring here .

Please note the checkout is for a virtual product and the status of the order is completed when checkout finishes.

### Expected behavior

Custom data being saved in the order meta at the initial checkout process. 

### Actual behavior

Data only saves after manually changing the order status

### Steps to reproduce

No screenshots applicable

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://zoomtest.local
Site address (URL): http://zoomtest.local
WC Version: 7.8.2
REST API Version: ✔ 7.8.2
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Win32) mod_fcgid/2.3.9a
PHP Version: 7.4.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.68.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.28
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.2
WC Database Prefix: wp_
Total Database Size: 45.07MB
Database Data Size: 23.20MB
Database Index Size: 21.87MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 9.52MB + Index: 13.59MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 6.52MB + Index: 5.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.30MB + Index: 0.28MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
mailpoet_page: 1
page: 7
post: 2
product: 24
product_variation: 7
shop_order: 54
shop_order_placehold: 1
shop_order_refund: 1
wc_booking: 28
zoom-meetings: 4

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (5) ###

Zoom Integration for WooCommerce and Bookings: by codemanas – 2.8.2
Video Conferencing with Zoom: by Deepen Bajracharya – 4.2.1
WooCommerce Bookings: by WooCommerce – 2.0.0
WooCommerce Stripe Gateway: by WooCommerce – 7.4.1
WooCommerce: by Automattic – 7.8.2 (update to version 7.9.0 is available)

### Inactive Plugins (2) ###

Query Monitor: by John Blackbourn – 3.13.1
Zoom Integration for WooCommerce: by Codemanas – 2.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
zoom_meeting (zoom_meeting)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Two
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-20 08:47:11 +00:00
Options: ✔
Notes: 73
Onboarding: completed

### Action Scheduler ###

Complete: 29,370
Oldest: 2023-07-14 08:48:28 +0000
Newest: 2023-07-19 08:48:33 +0000

Failed: 11
Oldest: 2023-07-14 08:55:35 +0000
Newest: 2023-07-19 08:15:00 +0000

Pending: 4
Oldest: 2023-07-19 09:15:00 +0000
Newest: 2023-08-17 06:51:43 +0000

### Status report information ###

Generated at: 2023-07-19 08:58:38 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment] 2023-08-31 00:24
@dipin-bajra is this still an issue for you? I'm wondering if [this change](https://github.com/woocommerce/woocommerce/pull/39700/files#diff-8c34c1a6f743002d1f2db13c299d2086d0209889f72abc86bef3bd734abb2585L2361-R2363) may have fixed it.

If not, could you add some step-by-step reproduction steps to the issue description?

**Comment by dipin-bajra** [comment] 2023-09-01 08:46
Hello @coreymckrill  yes, the issue is also still there with the update. 
I have used the code below to add custom data to the order meta using the HPOS method
```
add_action( 'woocommerce_order_status_processing', 'cm_order_meta_test' );
add_action( 'woocommerce_order_status_completed', 'cm_order_meta_test' );
function cm_order_meta_test( $order_id ) {
	$order = wc_get_order($order_id);
	$order->update_meta_data('_test_hpost_value', 'ikr');
	$order->save();
} 
```
So whenever an order is created the custom data should be stored automatically in the order meta at the initial checkout process which isn't the case here. It is only saved if we manually change or update the order status from the backend.

For example: If an order is created then the status of that order will be "processing" so at this initial state this custom data should be saved to the order meta "_test_hpost_value" which only happens if we switch order status from "processing" to "competed" or vice versa.

**Comment by coreymckrill** [comment] 2023-09-01 22:18
@dipin-bajra ok I can replicate with your code snippet. But, I'm not convinced this is actually a bug. You're hooking into the status transition part of updating an order, but I'm not sure that's the right place for what you're trying to do. It sounds like what you actually want to do is add data to an order right after checkout is complete, right? Have you tried using [`woocommerce_checkout_order_created`](https://github.com/woocommerce/woocommerce/blob/f493e921d5730543344485af8edfeb9749b4d9f3/plugins/woocommerce/includes/class-wc-checkout.php#L458-L463) instead?

**Comment by dipin-bajra** [comment] 2023-09-04 08:45
@coreymckrill Yes, I have tried using [woocommerce_checkout_order_created](https://github.com/woocommerce/woocommerce/blob/f493e921d5730543344485af8edfeb9749b4d9f3/plugins/woocommerce/includes/class-wc-checkout.php#L458-L463) but in my case, the order could go to the hold or pending status and I want the meta to be saved as soon as payment is completed
Or, if the order status has been manually changed to processing or completed

**Comment by wnolfm** [comment] 2023-09-12 16:44
@dipin-bajra If you test with this, does it work? 

```
add_action( 'woocommerce_order_status_changed', 'cm_order_meta_test', 10, 3 );
function cm_order_meta_test( $order_id, $old_status, $new_status ) { 
    if ( 'processing' === $new_status ) {
        $order = wc_get_order($order_id);
	$order->update_meta_data('_test_hpost_value', 'ik');
	$order->save();
    }
}

**Comment by dipin-bajra** [comment] 2023-09-13 05:39
@wnolfm The code only works if the order status is manually changed. We need to be able to make this change in both situations
 i) User makes Order - Payment is confirmed/made - Order goes to either (Process or Completed(if is a virtual product))
ii) User makes Order - Payment is pending - Shop Admin changes status to Processing

The use case is that if and only if Payment is made for an Order or Order is manually updated to processing.
We would need to connect to a 3rd Party service (Shipstatoin, Zoom, Accounting SAAS) to create a record on the third party service.

This was possible to do before HPOS with the following code.

``` 
add_action( 'woocommerce_order_status_processing', 'cm_order_meta_test' );
add_action( 'woocommerce_order_status_completed', 'cm_order_meta_test' );
function cm_order_meta_test( $order_id ) {
	$order = wc_get_order($order_id);
	//get order details and send data to 3rd Party
} ```

**Comment by Konamiman** [comment] 2023-09-25 15:16
Hi @dipin-bajra, I have tested the code snippet you posted as part of the issue description and it's working as expected: when performing an order from the shop, and paying by credit card (so the order goes to "Processing" directly, without admin intervention), the `_test_hpost_value` order meta item is created. Is this the correct way of testing, or am I missing something?

Anyway, WooCommerce 8.2 will be released on October 10. When that happens, could you please update, try again, and tell us how it went? Thank you!

**Comment by dipin-bajra** [comment] 2023-09-28 06:17
@Konamiman Yes, you're correct. I just performed a few tests once more, and it's working on the current version. Thanks a lot!

**Comment by Konamiman** [comment] 2023-09-28 09:07
Closing because the reported bug seems to already have been fixed.

**Closed as completed by Konamiman** 2023-09-28 09:07 UTC
Labels: Bug, needs: triage feedback, type: community contribution
