### ISSUE TITLE
[GlobalStep] For WPCOM site, PHP Fatal error with Uncaught Error: Class "Automattic\WooCommerce\Internal\Logging\SafeGlobalFunctionProxy" not found" is displayed after upgrading WooCommerce plugin version to "9.5.0-dev".

### ISSUE THREAD

**Issue by gglobalstep** [woothemes/woocommerce#52643] opened 2024-11-07 14:07 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

For WPCOM site, PHP Fatal error with Uncaught Error: Class "Automattic\WooCommerce\Internal\Logging\SafeGlobalFunctionProxy" not found is displayed after upgrading WooCommerce plugin version to "9.5.0-dev".

### Expected behavior

For WPCOM site,  WooCommerce plugin version to "9.5.0-dev" should be upgraded without any error.

### Actual behavior

For WPCOM site, PHP Fatal error with Uncaught Error: Class "Automattic\WooCommerce\Internal\Logging\SafeGlobalFunctionProxy" not found is displayed after upgrading WooCommerce plugin version to "9.5.0-dev".

### Steps to reproduce

1. Open WPCOM Commerce site.
2. Navigate to /wp-admin/plugin-install.php?tab=upload to upgrade the WooCommerce version
3. Install and upgrade the Woocommerce version 9.5.0-dev plugins.
4. Observe that, PHP Fatal error with Uncaught Error: Class "Automattic\WooCommerce\Internal\Logging\SafeGlobalFunctionProxy" not found is displayed after upgrading WooCommerce plugin version to "9.5.0-dev".

### Fatal error logs:
[#52643.txt](https://github.com/user-attachments/files/17662665/52643.txt)

### Screenshot:

![Image](https://github.com/user-attachments/assets/fef4bfd9-d478-46a4-9964-df3fc6e1f895)

### WordPress Environment

Woocommerce Version: 9.5.0-dev
WordPress version: 6.7-RC3

PC:
Windows 10
Chrome (Version 130.0.6723.117)
Firefox (Version 132.0.1)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.5.0-dev
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7-RC3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.30
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.10.1
OpenSSL/3.0.14

SUHOSIN Installed: –
MySQL Version: 10.6.19-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 68
jetpack_migration: 2
mailpoet_page: 1
page: 21
patterns_ai_data: 1
post: 3
product: 36
product_variation: 35
revision: 73
shop_coupon: 5
shop_order: 41
shop_order_placehold: 5
wp_global_styles: 6
wp_navigation: 2
wp_template: 2
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (41) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
AutomateWoo: by WooCommerce – 6.1.0
Blaze Ads: by Automattic – 0.5.2
Crowdsignal Forms: by Automattic – 1.7.2
Facebook for WooCommerce: by Facebook – 3.2.10
Google for WooCommerce: by WooCommerce – 2.8.6
Gutenberg: by Gutenberg Team – 19.5.1
Jetpack: by Automattic – 14.0-a.11
Layout Grid: by Automattic – 1.8.4
MailPoet Premium: by MailPoet – 5.3.0
MailPoet: by MailPoet – 5.3.6
Page Optimize: by Automattic – 0.5.6
Pinterest for WooCommerce: by WooCommerce – 1.4.11
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.1.2

Query Monitor: by John Blackbourn – 3.16.4
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 4.2.3
TikTok: by TikTok – 1.2.10
Woo AI: by WooCommerce – 0.6.0
WooCommerce.com Update Manager: by Automattic – 1.0.3
Avalara AvaTax: by Avalara – 2.8.5
WooCommerce Back In Stock Notifications: by Woo – 2.0.4
WooCommerce Brands: by WooCommerce – 1.7.6
WooCommerce Stripe Gateway: by Stripe – 8.8.1
WooCommerce Gift Cards: by Woo – 2.1.0
Google Analytics for WooCommerce: by WooCommerce – 2.1.7
WooCommerce Min/Max Quantities: by Woo – 5.0.3
WooCommerce Payments Dev Tools: by Automattic –
WooPayments: by WooCommerce – 8.4.0
WooCommerce Product Add-Ons: by Woo – 7.1.2
WooCommerce Product Bundles: by Woo – 8.1.2
WooCommerce Product Recommendations: by Woo – 4.1.0
WooCommerce Shipping & Tax: by WooCommerce – 2.8.3
WooCommerce Shipment Tracking: by WooCommerce – 2.5.2
WooCommerce Australia Post Shipping: by WooCommerce – 2.6.4
WooCommerce Canada Post Shipping: by WooCommerce – 3.0.3
WooCommerce FedEx Shipping: by WooCommerce – 4.1.2
WooCommerce Royal Mail: by WooCommerce – 3.4.2
WooCommerce UPS Shipping: by WooCommerce – 3.7.3
WooCommerce USPS Shipping: by WooCommerce – 5.0.1
WooCommerce: by Automattic – 9.5.0-dev
WP Mail Logging: by WP Mail Logging Team – 1.13.1

### Inactive Plugins (2) ###

Classic Editor: by WordPress Contributors – 1.6.5
WooCommerce EU VAT Number: by WooCommerce – 2.9.9

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Must Use Plugins (1) ###

wpcomsh-loader.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 1 MB

### WC Pages ###

Shop base: #64 - /shop-3/
Basket: #65 - /cart-4/ -  Contains the woocommerce/cart block
Checkout: #207 - /checkoutblock-2-2/ -  Contains the woocommerce/checkout block
My account: #67 - /my-account-3/
Terms and conditions: #85 - /shortcodecheckout/

### Theme ###

Name: Storefront
Version: 4.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 8.4.0
Connected to WPCOM: Yes
WPCOM Blog ID: 233257147
Account ID: acct_1PI5vPFymjhngUXh
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Disabled
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### MailPoet ###

Sending Method: MailPoet
Send all site's emails with: Default WordPress sending method
Task Scheduler method: Action Scheduler
Cron ping URL: 

### Back In Stock ###

Database Version: 2.0.4
Loopback Test: ✔

### Gift Cards ###

Database Version: 2.1.0
Loopback Test: ✔
Task Queueing Test: ✔

### Product Bundles ###

Database Version: 8.1.2
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout

Daily Cron: ✔ Next scheduled: 2024-11-08 09:33:12 +00:00
Options: ✔
Notes: 78
Onboarding: skipped

### Action Scheduler ###

Complete: 38,337
Oldest: 2024-10-07 15:16:40 +0100
Newest: 2024-11-07 14:09:58 +0000

Failed: 3
Oldest: 2024-07-04 10:57:52 +0100
Newest: 2024-10-30 02:31:12 +0000

Pending: 16
Oldest: 2024-11-07 14:10:58 +0000
Newest: 2024-11-09 07:17:30 +0000


### Product Recommendations ###

Database Version: 4.1.0
Loopback Test: ✔
Task Queueing Test: ✔
Page Cache Test: Cache in use

### Status report information ###

Generated at: 2024-11-07 14:10:36 +00:00
```
</details>

**Comment by gglobalstep** [comment] 2024-11-22 15:24
Hello, 

I have re-tested the issue using WooCommerce 9.5.0 Beta 1, and I can confirm that the PHP fatal error is no longer occurring. Everything works as expected with this version.

**Comment by ilyasfoo** [comment] 2024-11-27 02:22
I was able to reproduce this when upgrading from WooCommerce 9.4.2 to 9.6.0-dev nightly build on 26th November. The site was reset on 24th November, and I had a few products on the site before upgrading. 

This could be a similar issue with WPCOM updating plugins (pb22l9-2ub-p2#comment-2732). The previous issue was due to moving an existing class, and the workaround was to soft deprecate it in https://github.com/woocommerce/woocommerce/pull/46163 instead.

```
[27-Nov-2024 02:12:13 UTC] PHP Warning:  include_once(/srv/htdocs/wp-content/plugins/woocommerce/woocommerce.php): Failed to open stream: No such file or directory in /srv/htdocs/__wp__/wp-settings.php on line 526
[27-Nov-2024 02:12:13 UTC] PHP Warning:  include_once(): Failed opening '/srv/htdocs/wp-content/plugins/woocommerce/woocommerce.php' for inclusion (include_path='/:.') in /srv/htdocs/__wp__/wp-settings.php on line 526
[27-Nov-2024 02:12:13 UTC] PHP Fatal error:  Uncaught Error: Class "Automattic\WooCommerce\Internal\Logging\SafeGlobalFunctionProxy" not found in /srv/htdocs/wp-content/plugins/woocommerce/src/Internal/Logging/RemoteLogger.php:277
Stack trace:
#0 /srv/htdocs/wp-content/plugins/woocommerce/src/Internal/Logging/RemoteLogger.php(155): Automattic\WooCommerce\Internal\Logging\RemoteLogger->is_variant_assignment_allowed()
#1 /srv/htdocs/wp-content/plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php(93): Automattic\WooCommerce\Internal\Logging\RemoteLogger->is_remote_logging_allowed()
#2 /srv/htdocs/wp-content/plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php(257): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->get_core_data()
#3 /srv/htdocs/wp-content/plugins/woocommerce/src/Blocks/Assets/AssetDataRegistry.php(386): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->initialize_core_data()
#4 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->enqueue_asset_data('')
#5 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#6 /srv/htdocs/__wp__/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /srv/htdocs/__wp__/wp-admin/admin-footer.php(95): do_action('admin_print_foo...')
#8 /srv/htdocs/__wp__/wp-admin/update.php(186): require_once('/srv/htdocs/__w...')
#9 {main}
  thrown in /srv/htdocs/wp-content/plugins/woocommerce/src/Internal/Logging/RemoteLogger.php on line 277
[27-Nov-2024 02:12:14 UTC] PHP Fatal error:  Uncaught Error: Class "Automattic\WooCommerce\Internal\Logging\SafeGlobalFunctionProxy" not found in /srv/htdocs/wp-content/plugins/woocommerce/src/Internal/Logging/RemoteLogger.php:53
Stack trace:
#0 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-logger.php(189): Automattic\WooCommerce\Internal\Logging\RemoteLogger->handle(1732673534, 'critical', 'Uncaught Error:...', Array)
#1 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-logger.php(236): WC_Logger->log('critical', 'Uncaught Error:...', Array)
#2 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-woocommerce.php(406): WC_Logger->critical('Uncaught Error:...', Array)
#3 [internal function]: WooCommerce->log_errors()
#4 {main}
  thrown in /srv/htdocs/wp-content/plugins/woocommerce/src/Internal/Logging/RemoteLogger.php on line 53
```

**Comment by rjchow** [comment] 2024-11-27 02:43
Can't say I quite understand what might be going on, but some details:
- SafeGlobalFunctionProxy was introduced [only in 9.5.0](https://github.com/woocommerce/woocommerce/pull/51432)
- It seems to be intermittent with two recorded occurrences (9.4.2 -> 9.6.0-dev, ? -> 9.5.0-dev)  so it could be an Autoloader race condition? (I'm not familiar with how autoloader works)

**Comment by ilyasfoo** [comment] 2024-11-27 08:32
@rjchow This is also specific to WPCOM as it was never replicated in other environments

**Comment by tammullen** [comment] 2024-11-29 21:04
If I upgrade (9.4.2 > 9.5.0-beta.2) by uploading the zip I get the error
If I upgrade (9.4.2 > 9.5.0-beta.2) using the snippet below to simulate the upgrade prompt on plugins page I do not get the error.

I think this might be similar to other past fatals like this one https://github.com/woocommerce/woocommerce/issues/39036#issuecomment-1625593005 


```
add_filter( 'site_transient_update_plugins', 'set_woocommerce_update', 10, 1 );

function set_woocommerce_update( $value ) {
$update_version = '9.5.0-beta.2';
$update_package = 'https://downloads.wordpress.org/plugin/woocommerce.9.5.0-beta.2.zip';
if ( ! file_exists( trailingslashit( WP_PLUGIN_DIR ) . 'woocommerce/woocommerce.php' ) ) {
//WooCommerce not installed so bail.
return $value;
}
$current_version = get_file_data( trailingslashit( WP_PLUGIN_DIR ) . 'woocommerce/woocommerce.php', array( 'Version' => 'Version') )['Version'];
if ( $current_version === $update_version ) {
// Already on desired WooCommerce version.
return $value;
}
// Cause a new WooCommerce update.
if ( ! empty( $value->no_update['woocommerce/woocommerce.php'] ) ) {
$woocommerce = $value->no_update['woocommerce/woocommerce.php'];
$woocommerce->new_version = $update_version;
$woocommerce->package = $update_package;
$value->response['woocommerce/woocommerce.php'] = $woocommerce;
}
return $value;
}
```

**Comment by ilyasfoo** [comment] 2024-12-02 01:54
@tammullen Thanks for the context. If I understand this correctly, there's nothing to do on our end? If so, should we close this issue?

**Comment by chihsuan** [comment] 2024-12-11 09:45
I'll close this. We have a general issue here https://github.com/woocommerce/woocommerce/issues/52311 to avoid this happend again.

**Closed as completed by chihsuan** 2024-12-11 09:45 UTC
Labels: Bug, Logging, type: fatal
