### ISSUE TITLE
"Ghost" item back in cart after purchase

### ISSUE THREAD

**Issue by cherylstash** [woothemes/woocommerce#30750] opened 2021-09-21 18:17 UTC
am having an issue with my WooCommerce/AutomateWoo installation.

I do the following:
1) Add an item to my cart
2) Check out (Either in test mode or with a 100% coupon applied)
3) Recieve order confirmation. At this point, I observe that the cart is empty.
4) Verify in the database that the persistent cart has been cleared from the database.
5) Open https://domain/cart
Expected: The cart is still clear
Actual: About half the time the item has returned to the cart. (It appears to occur in clusters, where I cannot reproduce the bug a few times in a row, and then the next few times it triggers the bbug.)

I've managed to reproduce this behavior using the following theme and minimal plugin set:

Theme

Storefront 3.8.1

Plugins

AutomateWoo 5.5.2 
WooCommerce 5.6.0
WooCommerce Stripe Gateway 5.5.0

I believe I have disabled all caching.

There are no errors in the php log or debug.log.

Has anyone been able to resolve a similar issue and know what steps to take?
Is there a tool or process useful for determining the root cause of what could be repopulating the cart?
Is there a way to troubleshoot whether something in AutomateWoo is failing silently and responsible?

**WordPress Environment**  (below is for a test site we made with fresh Wordpress install and the bare minimum, so now two sites are having the same errors)
`
### WordPress Environment ###

WordPress address (URL): https://www.supergoodinfinite.com
Site address (URL): https://www.supergoodinfinite.com
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.23
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1l-fips

SUHOSIN Installed: –
MySQL Version: 5.7.32-35-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: txu_
Total Database Size: 8.59MB
Database Data Size: 6.10MB
Database Index Size: 2.49MB
txu_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
txu_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
txu_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
txu_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
txu_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
txu_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
txu_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
txu_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
txu_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
txu_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
txu_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
txu_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
txu_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
txu_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
txu_actionscheduler_actions: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
txu_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
txu_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
txu_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
txu_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
txu_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
txu_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
txu_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
txu_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
txu_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
txu_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
txu_automatewoo_log_meta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
txu_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
txu_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
txu_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
txu_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
txu_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
txu_mylisting_events: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
txu_mylisting_messages: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
txu_mylisting_relations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
txu_mylisting_visits: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
txu_options: Data: 3.16MB + Index: 0.08MB + Engine InnoDB
txu_postmeta: Data: 1.48MB + Index: 0.27MB + Engine InnoDB
txu_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
txu_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
txu_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
txu_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
txu_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
txu_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
txu_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
txu_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
txu_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
txu_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
txu_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
txu_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
txu_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
txu_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
txu_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
txu_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
txu_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
txu_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
txu_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
txu_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 112
aw_workflow: 1
case27_listing_type: 5
case27_user_package: 46
elementor_library: 1
job_listing: 20
nav_menu_item: 9
page: 24
post: 5
product: 6
revision: 9
shop_coupon: 1
shop_order: 52

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 3.7.1
AutomateWoo: by WooCommerce – 5.5.2
Debug Bar: by wordpressdotorg – 1.1.2
WooCommerce Stripe Gateway: by WooCommerce – 5.5.0
WooCommerce: by Automattic – 5.6.0
WP Crontrol: by John Blackbourn & crontributors – 1.10.0

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: job_package (job_package)
promotion_package (promotion_package)
simple (simple)

Taxonomies: Product Visibility: 
Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #153 - /shop/
Cart: #152 - /cart/
Checkout: #151 - /checkout/
My account: #150 - /my-account-2/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.8.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 220
Oldest: 2021-09-20 02:04:32 +0000
Newest: 2021-09-21 16:27:40 +0000

### Status report information ###

Generated at: 2021-09-21 18:13:15 +00:00
`

**Comment by rodelgc** [comment] 2021-09-23 12:28
Hi @cherylstash ,

Thank you for submitting the issue. However, I can’t reproduce the issue. In my test setup where WooCommerce 5.6.0 is the only plugin installed (no Query Monitor, AutomateWoo, etc.), the cart remained empty after placing the order.

Please see if you could still reproduce the issue by having only WooCommerce installed. If the issue is resolved, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by cherylstash** [comment] 2021-09-23 12:34
When it is woocommerce alone there is no problem, when Woocommerce and Automatewoo are the only plugins the problem happens.  So therefore it appears related to Automatewoo.  Also, to be more specific, when we have one workflow enabled in AutomateWoo, and that is to send an email upon trigger "Order Paid".

**Comment by cherylstash** [comment] 2021-09-23 14:10
Also this is for a digital product.

**Comment by cherylstash** [comment] 2021-09-24 15:10
Here are some videos:
https://www.loom.com/share/eb547325abde4a3e9f4612088d6c6aa7

error doesn't happen until around 3:15, you can see sometimes it takes a few times:  
https://www.loom.com/share/65151e9c995a46dd9dea31a0f21a0469

**Comment by cherylstash** [comment] 2021-09-24 15:20
It seems like when there is a bug, an order or two before missed a step or switched from cron to async.  I have zero traffic on this site so its concerning:

<google-sheets-html-origin><style type="text/css"></style>

ORDERS WITH NO BUGS: |   |   |  
-- | -- | -- | --
1 | cron cron | automatewoo/async/maybe_order_created | 322
2 | cron cron | automatewoo/order/status_changed_async |  
3 | cron cron | wc-admin_import_customers |  
4 | cron cron | wc-admin_import_orders |  
  |   |   |  
1 | cron cron | automatewoo/async/maybe_order_created | 323
2 | cron cron | automatewoo/order/status_changed_async |  
3 | cron cron | wc-admin_import_customers |  
4 | cron cron | wc-admin_import_orders |  
  |   |   |  
1 | cron cron | automatewoo/async/maybe_order_created | 324
2 | cron cron | automatewoo/order/status_changed_async |  
3 | async async | wc-admin_import_orders |  
ORDER WITH BUG: |   |   |  
1 | async async | automatewoo/async/maybe_order_created | 325
2 | async async | automatewoo/order/status_changed_async |  
3 | async async | wc-admin_import_customers |  
4 | async async | wc-admin_import_orders |

**Comment by cherylstash** [comment] 2021-09-24 17:02
Actually my bad I decided to disable Automatewoo to do a little more testing with just Woocommerce and Woocommerce Stripe Gateway, and the error is still there on the 8th test:
<google-sheets-html-origin><style type="text/css"></style>

DISABLED AUTOMATEWOO |   |   |  
-- | -- | -- | --
1 | async async | wc-admin_import_customers |  
2 | async async | wc-admin_import_orders | 332
  |   |   |  
1 | async async | wc-admin_import_customers |  
2 | async async | wc-admin_import_orders | 333
  |   |   |  
1 | cron cron | wc-admin_import_customers |  
2 | cron cron | wc-admin_import_orders | 334
  |   |   |  
1 | cron cron | wc-admin_import_orders | 335
2 | cron cron | wc-admin_import_customers |  
  |   |   |  
1 | cron cron | wc-admin_import_orders | 336
2 | async async | wc-admin_import_customers |  
  |   |   |  
1 | async async | wc-admin_import_orders | 337
2 | async async | wc-admin_import_customers |  
  |   |   |  
1 | async async | wc-admin_import_orders | 338
  |   |   |  
CHECKOUT WITH BUG: |   |   |  
1 | cron cron | wc-admin_import_orders | 339

**Comment by cherylstash** [comment] 2021-09-24 18:15
I am actually not that clear on whether it still happens with Automatewoo off, it happened a couple times and then it tapered off and didn't happen again for many, many test cases.  Its like there will be an error upstream in either Cron or Async or talking to each other, and once those get reinserted back into the cart, if there are no more glitches, it all resolves.

**Comment by cherylstash** [comment] 2021-09-28 22:34
I also just purchased 3 separate transactions of $1 on my site to see if it was the 100% discount coupons or test mode that was not working, and the 3rd one had the same error- order processed, payment authorized, but when customer goes to www.domain.com/cart the item is in cart as though it was never purchased.

**Comment by jantowell** [comment] 2021-09-30 06:33
Hi @cherylstash,

I have exactly the same issue. I have many more plugins, but I have been using the following like you

wordpress 5.8.1 
custom theme 
automatewoo 5.5.2
woocommerce 5.6.0
woocommerce stripe gateway 5.5.0

but I have managed to continue to create the problem fairly consistently today on test with automatewoo disabled and woocomerce stripe gateway disabled. I have also been able to create the issue with coupons, stripe and paypal as the payment methods.

I have had reports of the issue on chrome desktop and safari mobile 

In the Chrome console if you type sessionStorage you will see the content that is used for the cart. I have found that when it fails sometimes the cart is recreated in the session storage as early as the order-received page. I haven't worked out yet why it is intermittent or how the session storage is getting repopulated with the previous cart.

I would love any more insight you gain into this.

Thanks

Janette

**Comment by AashikP** [comment] 2021-10-01 08:47
@cherylstash 

I see you're already working with us at WooCommerce.com in request #4226424-zen regarding this. Can we please request you continue troubleshooting with us via that ticket so that we can get to the bottom of it, and then report back here if it indeed turns out to be a bug in the system?

@jantowell Since you have AutomateWoo, you can get support via https://woocommerce.com/my-account/create-a-ticket/?form=ticket. Please open a support request directly, and include a link to this GitHub comment so that we can investigate further via ticket.

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. 

---

For anyone else landing on this ticket, in order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug, which cannot be replicated on fresh installations. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by AashikP** 2021-10-01 08:47 UTC
Labels: status: can't reproduce

**Comment by cherylstash** [comment] 2021-10-05 00:01
@AashikP  How do I message you?  Support told me this is indeed a bug and they will be investigating this.  I'd like to hear if anyone has found a patch or work-around in the meantime.

**Comment by jantowell** [comment] 2021-10-05 00:13
@cherylstash, I really would like to contact you regarding this, as I have the same issue and I am trying to find out where the bug is. You say that "it is indeed a bug", a bug in what? AutomateWoo, or WooCommerce? Feel free to directly email me my email address is web @ jtowell .com .au (obviously without the spaces). Thanks Janette

**Comment by AashikP** [comment] 2021-10-11 04:13
@cherylstash We've narrowed this down to be a bug in AutomateWoo and there currently isn't a workaround that we're aware of. This GitHub repository is specifically for core WooCommerce. Please continue further discussion regarding the issue on the ticket (Request #4226424-zen).

@jantowell Please send an email directly to `help@woocommerce.com` from the email address of the account you used to purchase AutomateWoo so that we can keep you posted about the bug report.
