### ISSUE TITLE
Product filter by attribute doesn't take into account disabled variations

### ISSUE THREAD

**Issue by mattiadesiderio** [woothemes/woocommerce#41058] opened 2023-10-27 10:09 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

If a variation has been deactivated, it must not appear in the filters widget and must not appear in the search results either. (Example url: */negozio/?filter_taglia=47 shouldn't show any result since there is no active variation with this size)

### Expected behavior

Variations of a product that are NOT active (the unchecked checkbox) must not appear in the widget's filters, even if they are available. 

There is no point in showing them because since they are inactive, if the user enters inside the product he wouldn't see them.

### Actual behavior

Variations of a product that are NOT active (the unchecked checkbox) must not appear in the widget's filters, even if they are available. 

There is no point in showing them because since they are inactive, if the user enters inside the product he wouldn't see them.

### Steps to reproduce

1. Create a variable product.
2. Generate variations
3. Leave variations available, but uncheck "Enabled".
4. Save
5. In the shop set up a "Filter by attribute" widget and you will still see the variations that have been deactivated

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://testing.staging-v430.cloud
Site address (URL): https://testing.staging-v430.cloud
WC Version: 8.2.1
REST API Version: ✔ 8.2.1
WC Blocks Version: ✔ 11.1.2
Action Scheduler Version: ✔ 3.6.3
Log Directory Writable: ✔
WP Version: 6.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.11
PHP Post Max Size: 16 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 8.0.35
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.1
WC Database Prefix: 7s1vOy_
Dimensione totale database: 4.23MB
Dimensione dati database: 2.57MB
Dimensione indice database: 1.66MB
7s1vOy_woocommerce_sessions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
7s1vOy_woocommerce_order_items: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_woocommerce_order_itemmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
7s1vOy_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
7s1vOy_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
7s1vOy_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_actionscheduler_actions: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
7s1vOy_actionscheduler_claims: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_actionscheduler_logs: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_comments: Dati: 0.02MB + indice: 0.08MB + motore InnoDB
7s1vOy_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_options: Dati: 1.52MB + indice: 0.03MB + motore InnoDB
7s1vOy_postmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_posts: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
7s1vOy_term_relationships: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_term_taxonomy: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_termmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_terms: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_usermeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_users: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
7s1vOy_wc_admin_note_actions: Dati: 0.05MB + indice: 0.02MB + motore InnoDB
7s1vOy_wc_admin_notes: Dati: 0.06MB + indice: 0.00MB + motore InnoDB
7s1vOy_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
7s1vOy_wc_customer_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_wc_order_addresses: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
7s1vOy_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_wc_order_operational_data: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_wc_order_product_lookup: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
7s1vOy_wc_order_stats: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
7s1vOy_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_wc_orders: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
7s1vOy_wc_orders_meta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
7s1vOy_wc_product_attributes_lookup: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_wc_product_download_directories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_wc_product_meta_lookup: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
7s1vOy_wc_rate_limits: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_wc_reserved_stock: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
7s1vOy_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
7s1vOy_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB

### Post Type Counts ###

attachment: 1
customize_changeset: 1
page: 7
post: 2
product: 2
product_variation: 4
wp_global_styles: 1
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Classic Widgets: by WordPress Contributors – 0.3
WooCommerce: by Automattic – 8.2.1

### Inactive Plugins (2) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7 - /negozio/
Carrello: #8 - /carrello/
Pagamento: #9 - /pagamento/
Il mio account: #10 - /mio-account/
Termini e condizioni: ❌ La pagina non è impostata

### Theme ###

Name: Twenty Twenty-One
Version: 1.9
Author URL: https://wordpress.org/
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un tema child. Vedi: Come creare un tema child

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-10-28 08:55:38 +00:00
Options: ✔
Notes: 63
Onboarding: skipped

### Action Scheduler ###

Completato: 13
Oldest: 2023-10-27 08:56:48 +0000
Newest: 2023-10-27 09:11:52 +0000

Operazione non riuscita: 1
Oldest: 2023-10-27 09:04:23 +0000
Newest: 2023-10-27 09:04:23 +0000

In attesa: 1
Oldest: 2023-10-28 08:56:48 +0000
Newest: 2023-10-28 08:56:48 +0000

### Status report information ###

Generated at: 2023-10-27 10:05:50 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment] 2023-11-02 22:51
Duplicate of https://github.com/woocommerce/woocommerce/issues/31451.

**Closed as completed by barryhughes** 2023-11-02 22:51 UTC
Labels: Bug, Store Frontend, type: community contribution
