### ISSUE TITLE
Data missing from orders/xx/refunds API when HPOS enabled

### ISSUE THREAD

**Issue by bryceadams** [woothemes/woocommerce#37697] opened 2023-04-13 02:31 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

**If WooCommerce HPOS is enabled:** When making a request for an order's refunds through the WooCommerce REST API, eg. orders/123/refunds, the `amount`, `reason`, and `refunded_by` attributes are all set to 0/empty, when there is a value. The values shown under the `meta_data` attribute:

<img width="509" alt="CleanShot 2023-04-13 at 12 27 40@2x" src="https://user-images.githubusercontent.com/1532482/231631831-77814592-7b6c-4c00-9538-99695233981c.png">

**If WooCommerce HPOS is disabled (using WordPress posts table):** The data is there as expected:

<img width="505" alt="CleanShot 2023-04-13 at 12 29 38@2x" src="https://user-images.githubusercontent.com/1532482/231632166-a54062e6-9cf9-49dd-b51c-084c4dddd466.png">
	

### Expected behavior

Refunds API endpoint should return amount/reason/etc. when the data is there when using WooCommerce orders table (HPOS).

### Actual behavior

The data is empty.

### Steps to reproduce

1. Enable WooCommerce HPOS beta.
2. Make an API request to the WooCommerce REST API to get an order's refunds.
3. You'll notice the amount/reason/other data missing.
4. Disable HPOS / Switch back to WordPress Posts table and do #2 again and you'll see the data is there as expected.

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment] 2023-04-26 14:25
Thanks for reporting this, we'll look into a fix :+1:

**Comment by vedanshujain** [comment] 2023-07-10 13:02
hey @bryceadams, is this still an issue, I am not able to reproduce on the latest WooCommerce. This may have been fixed by some other PR.
![Screenshot 2023-07-10 at 6 30 03 PM](https://github.com/woocommerce/woocommerce/assets/7571618/1c63c146-c116-4711-9761-1818731443e8)

**Comment by bryceadams** [comment] 2023-07-13 00:22
Hey @vedanshujain. Yep, it is still an issue. I just tested with the WooCommerce 7.8.2.

The issue is there in your screenshot too. If you view the amount, it's set to 0, even though it shows as 2116.36 in the meta data. Same with reason and refunded by. Both are empty/0 but the data is in the meta data. These fields should probably **not** be shown in the meta data but instead be set as the amount/reason/refunded_by keys.

**Comment by vedanshujain** [comment] 2023-07-13 13:15
Not sure how I missed that, anycase PR here: #39219

**Closed as completed** 2023-07-14 06:34 UTC
Labels: Bug, REST/Store API/Webhooks, plugin: woocommerce, type: community contribution
