### ISSUE TITLE
Can't install extensions after business details step

### ISSUE THREAD

**Issue by elizaan36** [woothemes/woocommerce#32234] opened 2021-09-17 18:29 UTC
### Describe the bug
I'm unable to install extensions in the free business features step of the store profiler, and I'm getting the error "Your business details cannot be updated."

There's also a "Retry" button in the business features step and another link to "Continue without installing". I had to choose continue without installing in order to proceed to the next step.

This is extremely confusing for users because there's no way to know they have to go back to the previous tab to move forward without installing the extensions. They could essentially be getting stuck on the free features screen with no way out.

### To Reproduce
1. Create a new site and install WooCommerce
2. Go through the steps of the store profiler until the business features step
3. Try to install extensions

### Screenshots
<img width="1392" alt="Screen Shot 2021-09-17 at 10 42 07 AM" src="https://user-images.githubusercontent.com/5121465/133835993-753c316d-73a9-4c3e-b1fa-01b4f1921352.png">
<img width="482" alt="Screen Shot 2021-09-17 at 10 42 21 AM" src="https://user-images.githubusercontent.com/5121465/133836000-b3e9100c-ad92-4ef0-a67b-a6bb61df75fc.png">

### Expected behavior
The extensions should install in the free business features step.

### Desktop (please complete the following information):
I'm testing on Mac/Firefox

**Comment by elizaan36** [comment] 2021-09-21 16:53
Also tried installing WCPay via WP plugins and I'm getting an error there as well. "Destination folder already exists."

<img width="617" alt="image" src="https://user-images.githubusercontent.com/5121465/134213792-29bdb93a-3610-458a-bef7-f56ce870df66.png">

@moon0326 mentioned that the issue is probably that the plugin can't be installed when it failed on the first attempt. This is a Jurassic Ninja site, which often gets backend errors. This could happen on other sites, but rarely.

@pmcpinto it might be looking more closely into this and seeing how much of an edge case it is, since it's a dead end for the free features step **and** for installing WCPay.

**Comment by pmcpinto** [comment] 2021-09-22 09:27
Thanks for opening an issue about this. AFAIR we tried to debug this in the past and it was difficult to find the root cause. Maybe we can include this in the next GlobalStep testing cycle. @becdetat @mattsherman what do you think?

**Comment by mattsherman** [comment] 2021-09-23 15:35
@pmcpinto @elizaan36 It sounds like there are two distinct issues here...

1. Extensions fail to install during the "Free features" step of the profiler. This sounds like it is intermittent and difficult to reproduce/diagnosis. I'm not sure that it is useful to have GlobalStep explicitly try to reproduce this... I would think that any such failure would already be reported by them.
    - We should log when this failure happens, if we already don't, so that we can see how often this occurs.
    - We should consider retrying the installation automatically, *if* we think the problem is intermittent and could actually succeed if the user were to manually click "Retry".
2. When extensions fail to install during the "Free features" step of the profiler, the user gets stuck.
    - We should improve the UX here show the "Retry" and "Continue without installing" on the "Free features" tab.

**Comment by elizaan36** [comment] 2021-09-23 21:11
> We should consider retrying the installation automatically, if we think the problem is intermittent and could actually succeed if the user were to manually click "Retry".

Yeah, I did try the "Retry" button a few times with no luck.

Since it's a database error where the plugin already appears there for whatever reason (from what Moon had mentioned on Slack, there's almost no point in having a Retry button, unless it's to drive people batty lol.)

Do you think it would make more sense to just show the link, "Continue without installing" after the error? I definitely agree it should be on the free features step and can mock up a placement for it.

Not sure how many stores this impacts because it's so hard to reproduce, but would be great to know of a solution when this happens. We can share that in a message, even if it's just to contact support, then at least users are able to troubleshoot themselves.

**Comment by pmcpinto** [comment] 2021-09-24 09:11
@mattsherman what do you think about exploring the idea shared on woocommerce/woocommerce-admin#6988 to solve this?

**Comment by mattsherman** [comment] 2021-09-26 12:57
@pmcpinto I don't think that the idea shared on woocommerce/woocommerce-admin#6988 necessarily solves this issue, but they are very closely related, and I think that it would be good for Mothra to look into improving this. I'll put this on our radar for Cycle 18.

**Comment by becdetat** [comment] 2021-11-10 02:06
@mattsherman Is Mothra still looking at this?

**Comment by mattsherman** [comment] 2021-11-12 19:27
We will be looking into this as a part of the woocommerce/woocommerce-admin#7919 spike.

**Comment by joshuatf** [comment] 2022-01-31 21:01
I've encountered this issue before in certain hosting environments.  IIRC the issue was that the installation workflow bailed after creating the folder, but permissions had not been properly set by the host.

In this event, there was an empty folder with the plugin name, so there's not a plugin to activate, but this also prevented installation of a new plugin at this path.

I'm not sure if this truly resolves the issue, but just noting here that we have async plugin endpoints now ( https://github.com/woocommerce/woocommerce-admin/pull/8079 ) so we could potentially add a buffer between installs to prevent read/write locking on those folders if that is the issue.

**Comment by chihsuan** [comment] 2023-03-30 10:59
We've identified a couple of common issues during installing step in https://github.com/woocommerce/team-ghidorah/issues/188.

Closing this. I think we'll work on this in a new issue.

**Closed as completed by chihsuan** 2023-03-30 10:59 UTC
Labels: Bug, plugin: woocommerce
