### ISSUE TITLE
CRITICAL Uncaught Error: Call to undefined function as_get_scheduled_actions()

### ISSUE THREAD

**Issue by jobst** [woothemes/woocommerce#35868] opened 2022-12-07 04:05 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The FATAL ERROR (at the end) happens intermittend BUT OFTEN, my logs are full of this.
When the error happens, the user sees the WP generated error message "There has been a critical error on this website".
It has never happened to me as the MAIN admin, so I though my website is OK - I did not know there was  something wrong.
Only when the other admin told me (and he got this error only twice) was I made aware there is something wrong on the site.

It took me a while to figure out it was related to a function called 'as_get_scheduled_actions'.
It took me another 2 hours to get it down to WOOCOMMERCE.

I searched for the function 'as_get_scheduled_actions' and it **does indeed NOT EXIST in the entire tree of the website.**
However the actual call to the function come from within the woocommerce directory tree ONLY.

It seems, too, the error started ONLY somewhere around the 30.11.2022 just after I upgraded the plugins.
I am not sure what the WOOCOMMERCE version number was before the date, however I do update regularly.

Also I have found another ISSUE talking about the same problem: https://github.com/woocommerce/action-scheduler/issues/730

As I have now figured out I need to have another plugin installed called "Action Scheduer" providing that function.
I was never advised about this, I have Woocommerce installed on some site for 5 years or more.

Why does WOOCOMMERCE not warn me about a missing plugin?
I have been using Woocommerce for many years and have been upgrading it on many machines.

I was never made aware of this "Action Scheduler" thing, I also was not aware we had a problem.

```
2022-11-30T18:59:06+11:00 CRITICAL Uncaught Error: Call to undefined function as_get_scheduled_actions() in PATH_TO_WP_INSTALL/wp-content/plugins/woocommerce/includes/queue/class-wc-action-queue.php:158
Stack trace:
#0 PATH_TO_WP_INSTALL/wp-content/plugins/woocommerce/src/Admin/Schedulers/SchedulerTraits.php(185): WC_Action_Queue->search()
#1 PATH_TO_WP_INSTALL/wp-content/plugins/woocommerce/src/Admin/Schedulers/SchedulerTraits.php(297): Automattic\WooCommerce\Internal\Admin\Schedulers\ImportScheduler::has_existing_jobs()
#2 PATH_TO_WP_INSTALL/wp-content/plugins/woocommerce/src/Internal/Admin/Schedulers/CustomersScheduler.php(145): Automattic\WooCommerce\Internal\Admin\Schedulers\ImportScheduler::schedule_action()
#3 PATH_TO_WP_INSTALL/wp-content/plugins/woocommerce/src/Internal/Admin/Schedulers/CustomersScheduler.php(159): Automattic\WooCommerce\Internal\Admin\Schedulers\CustomersScheduler::schedule_import()
#4 PATH_TO_WP_INSTALL/wp-includes/class-wp-hook.php(310): Automattic\WooCommerce\Internal\Admin\Schedulers\CustomersScheduler::schedule_import_via_last_active()
#5 PATH_TO_WP_INSTALL/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#6 PATH_TO_WP_INSTALL/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 PATH_TO_WP_INSTALL/wp-includes/meta.php(334): do_action()
#8 PATH_TO_WP_INSTALL/wp-includes/user.php(1185): update_metadata()
#9 PATH_TO_WP_INSTALL/wp-content/plugins/woocommerce/includes/wc-user-functions.php(930): update_user_meta()
#10 PATH_TO_WP_INSTALL/wp-content/plugins/woocommerce/includes/wc-user-functions.php(902): wc_update_user_last_active()
#11 PATH_TO_WP_INSTALL/wp-includes/class-wp-hook.php(308): wc_user_logged_in()
#12 PATH_TO_WP_INSTALL/wp-includes/class-wp-hook.php(332): WP_Hook->app in PATH_TO_WP_INSTALL/wp-content/plugins/woocommerce/includes/queue/class-wc-action-queue.php on line 158
```

### Expected behavior

No (standard) Wordpress Error message displayed, i.e. the function "as_get_scheduled_actions()" should exist in the woocommerce tree so the error does NOT appear.

Should the adminstrators of a website having WOOCOMMERCE installed not being advised they have a missing plugin?
I would assume there would be a red  message box in the admin panel telling me I need to install another plugin.
(other plugins do that).

I have had woocommerce plugins installed for years across many websites.
I have never known I need this other plugin called "Action Scheduler".

I am even not sure why or whether I need it.

### Actual behavior

The user is faced RANDOMLY with the error WP created message:  "There has been a critical error on this website".

Should WOOCOMMERCE not WARN me about a missing plugin instead of being quiet?
I have had woocommerce installed on many machines, I have never known I had to install the "Action Scheduler"

### Steps to reproduce

I cannot reproduce the error REGULARLY, sorry!
However, it happens at the very least twice an hour.

### WordPress Environment

Well I have just figured out I need another plugin as in MY eyes the site was performing WELL.
I personally never received an error  accessing the site.

So WHY wold I actually look at the STATUS page ... I dont have the time to do that on all of my sites.

`
### WordPress Environment ###

WordPress address (URL): https://www.salesessentials.com
Site address (URL): https://www.salesessentials.com
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.5.3
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.30
PHP Post Max Size: 256 MB
PHP Time Limit: 600
PHP Max Input Vars: 5000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 8.0.26
Max Upload Size: 256 MB
Default Timezone is UTC: ❌ Default timezone is Australia/Melbourne - it should be UTC
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: wp_
Total Database Size: 186.16MB
Database Data Size: 109.98MB
Database Index Size: 76.18MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.31MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
bcg_myNotes: Data: 2.52MB + Index: 0.22MB + Engine InnoDB
bcg_noticeboard: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
bcg_options: Data: 0.38MB + Index: 0.06MB + Engine InnoDB
bcg_user_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_PO_plugins: Data: 0.19MB + Index: 0.03MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ajax_chat: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_allowphp_functions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bas_count: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bas_image: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_blog_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 21.55MB + Index: 9.03MB + Engine InnoDB
wp_comments: Data: 12.52MB + Index: 29.13MB + Engine InnoDB
wp_cst_new_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fbv_attachment_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_layerslider: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_media_file_manager_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ngg_album: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ngg_gallery: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ngg_pictures: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 9.31MB + Index: 1.72MB + Engine InnoDB
wp_postmeta: Data: 8.52MB + Index: 10.03MB + Engine InnoDB
wp_posts: Data: 5.52MB + Index: 0.86MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.19MB + Index: 0.16MB + Engine InnoDB
wp_term_taxonomy: Data: 0.22MB + Index: 0.25MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.17MB + Index: 0.22MB + Engine InnoDB
wp_usermeta: Data: 9.52MB + Index: 10.03MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 0.42MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.33MB + Index: 0.25MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.36MB + Index: 0.41MB + Engine InnoDB
wp_wc_order_stats: Data: 0.27MB + Index: 0.27MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfBlockedIPLog: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wfBlocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfConfig: Data: 2.30MB + Index: 0.00MB + Engine InnoDB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileMods: Data: 7.52MB + Index: 0.00MB + Engine InnoDB
wp_wfHits: Data: 8.02MB + Index: 2.81MB + Engine InnoDB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfIssues: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_wfKnownFileList: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfLogins: Data: 1.52MB + Index: 0.30MB + Engine InnoDB
wp_wfNotifications: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wfPendingIssues: Data: 0.05MB + Index: 0.13MB + Engine InnoDB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfStatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_wfTrafficRates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wlcc_contentarchiver: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wlcc_contentmanager_move: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wlcc_contentmanager_repost: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wlcc_contentmanager_set: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wlcc_contentsched: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wlm_api_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wlm_contentlevel_options: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wlm_contentlevels: Data: 0.20MB + Index: 0.42MB + Engine InnoDB
wp_wlm_email_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wlm_emailbroadcast: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wlm_level_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wlm_logs: Data: 0.23MB + Index: 0.28MB + Engine InnoDB
wp_wlm_options: Data: 5.52MB + Index: 0.09MB + Engine InnoDB
wp_wlm_presto_player_visits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wlm_user_options: Data: 0.44MB + Index: 0.70MB + Engine InnoDB
wp_wlm_userlevel_options: Data: 1.52MB + Index: 2.34MB + Engine InnoDB
wp_wlm_userlevels: Data: 0.25MB + Index: 0.41MB + Engine InnoDB
wp_yoast_indexable: Data: 1.52MB + Index: 0.50MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.42MB + Index: 0.23MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 913
certificate: 6
certificate_template: 6
coaching-tab: 45
course: 8
feedback: 1
karma-slider: 2
lesson: 135
nav_menu_item: 127
oembed_cache: 2
page: 91
plugin_group: 1
post: 162
product: 69
product_variation: 2
question: 225
quiz: 147
revision: 37
sensei_message: 2
shop_coupon: 2
shop_order: 2186
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Action Scheduler: by Automattic – 3.5.3
Barrett Allow PHP in Posts/Pages: by Jobst Schmalenbach
Sales Essentials – 3.0.4

Barrett Author Slug: by Jobst Schmalenbach
Sales Essentials
2014 – 1.3
jobst
January 2018

Barrett Disable Users: by Jobst Schmalenbach – 1.0.5
Barrett MIGS Gateway: by Jobst Schmalenbach
Sales Essentials
(C) 2013-2017 – 4.0.0

Barrett Social Bookmarks: by Jobst Schmalenbach – 4.1.6
Barrett WC Wishlist Integration: by Jobst Schmalenbach – 3.1.0
Disable Gutenberg: by Jeff Starr – 2.8.1
Disable REST API: by Dave McHale – 1.7
Free Downloads WooCommerce: by Square One Media – 3.5.1
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
Enable Media Replace: by ShortPixel – 4.0.1
FileBird: by Ninja Team – 4.3.2
WPBakery Page Builder: by Michael M - WPBakery.com – 6.10.0
Karma Builder: by TrueThemes – 2.2.9
MailChimp: by MailChimp – 1.5.8
Manage Notification E-mails: by Virgial Berveling – 1.8.4
reCaptcha for WooCommerce: by I Thirteen Web Solution – 2.38
Sensei LMS Certificates: by Automattic – 2.1.0 (update to version 2.3.0 is available)
Sensei LMS: by Automattic – 3.14.0 (update to version 4.9.0 is available)
Advanced Editor Tools (previously TinyMCE Advanced): by Automattic – 5.6.0
User Switching: by John Blackbourn & contributors – 1.7.0
Widget Logic: by WPChef – 5.10.4
WishList Member™: by WishList Products – 3.20.0
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.3.2
WooCommerce: by Automattic – 7.1.0
Wordfence Security: by Wordfence – 7.8.0
Yoast SEO: by Team Yoast – 19.11
WP Better Attachments: by Dan Holloran – 1.3.11

### Inactive Plugins (3) ###

Barrett Broadcast Message Widget: by Jobst Schmalenbach
SalesEssentials
July 2014 – 1.1 jobst
June 2016
added color

Media File Manager: by Atsushi Ueda – 1.4.2
User Notes: by Cartpauj – 1.0.2

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD (AUD $)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: configurable (configurable)
downloadable (downloadable)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
virtual (virtual)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #12 - /shop/
Cart: #13 - /cart/
Checkout: #14 - /checkout/
My account: #16 - /my-account/
Terms and conditions: #10406 - /terms-and-conditions/

### Theme ###

Name: Salesessentials Karma Child Theme
Version: 1.2
Author URL: 
Child Theme: ✔
Parent Theme Name: Karma
Parent Theme Version: 5.0.4
Parent Theme Author URL: http://www.truethemes.net
WooCommerce Support: ✔

### Templates ###

Overrides: salesessentials/archive-product.php
salesessentials/checkout/payment.php version 3.5.3 is out of date. The core version is 7.0.1
salesessentials/checkout/review-order.php
salesessentials/checkout/thankyou.php
salesessentials/emails/customer-invoice.php
salesessentials/emails/customer-new-account.php
salesessentials/emails/customer-reset-password.php
salesessentials/emails/email-footer.php
salesessentials/emails/email-header.php
salesessentials/emails/email-order-details.php
salesessentials/emails/email-order-items.php
salesessentials/emails/email-styles.php
salesessentials/myaccount/dashboard.php
salesessentials/myaccount/form-edit-account.php version 3.5.0 is out of date. The core version is 7.0.1
salesessentials/myaccount/form-login.php version 6.0.0 is out of date. The core version is 7.0.1
salesessentials/myaccount/form-lost-password.php version 3.5.2 is out of date. The core version is 7.0.1
salesessentials/myaccount/form-reset-password.php version 3.5.5 is out of date. The core version is 7.0.1
salesessentials/myaccount/my-account.php
salesessentials/myaccount/my-downloads.php
salesessentials/order/order-details.php
salesessentials/single-product/meta.php
salesessentials/single-product/price.php

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-12-07 03:12:41 +11:00
Options: ✔
Notes: 9
Onboarding: completed

### Action Scheduler ###

Complete: 64
Oldest: 2022-11-07 05:25:17 +1100
Newest: 2022-12-07 14:13:09 +1100

Pending: 1
Oldest: 2022-12-08 14:13:09 +1100
Newest: 2022-12-08 14:13:09 +1100

### Status report information ###

Generated at: 2022-12-07 14:23:16 +11:00
`

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment] 2023-01-06 19:26
Hi @jobst,

Sorry to hear you have experienced difficulties.

> I searched for the function 'as_get_scheduled_actions' and it does indeed NOT EXIST in the entire tree of the website ... I have now figured out I need to have another plugin installed called "Action Scheduer" providing that function.

So long as you install WooCommerce from the WordPress plugin directory, this should not be a problem and you should not have to install Action Scheduler separately. This is because the Action Scheduler library is bundled within WooCommerce. For example, here is a link showing the location of the function you were searching for, in our latest release:

https://plugins.trac.wordpress.org/browser/woocommerce/tags/7.2.2/packages/action-scheduler/functions.php#L277

On the other hand, if you install WooCommerce some other way—such as by cloning our Git repository—you would have to make sure you follow all the recommended steps (like running `composer install`) to ensure these dependencies are available to you.

> [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.

You don't seem to have performed the above step, but [testing for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/) is important if we are to determine the source of problems like this one.

> Also I have found another ISSUE talking about the same problem: https://github.com/woocommerce/action-scheduler/issues/730

At this stage, I don't think we can be sure that is the very same problem. 

The error in that other issue references a different function and is something we've seen when multiple versions of Action Scheduler are present within the same WordPress installation. [See here for more details](https://developer.woocommerce.com/2021/10/12/best-practices-for-deconflicting-different-versions-of-action-scheduler/)—that problem would not however lead to a missing function error for `as_get_scheduled_actions()`.

So, although superficially similar, it's quite likely the problem you are facing is something else.

**Comment by peterfabian** [comment] 2023-05-22 12:18
As we haven't received any response in a long time, I'm closing this bugreport. Feel free to comment again if you have more info and we might reopen the bug report.

**Closed as completed by peterfabian** 2023-05-22 12:18 UTC
Labels: Bug, needs: author feedback, plugin: woocommerce, type: community contribution

**Comment by jobst** [comment] 2023-05-23 01:57
I am sorry, I did not receive any alert someone had followed up until yesterday when I recevied the message about being closed.

> ....
> On the other hand, if you install WooCommerce some other way—such as by cloning our Git repository—you would have to make sure you follow all the recommended steps (like running `composer install`) to ensure these dependencies are available to you.

I did not, this is a *VERY* old install, I have had this site for a long time but I have kept it updated ever since then.
The original install (2013) of woocommerce was by installing it via Plugins -> Add New -> Upload Plugin -> File
This is what I do.

> > [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
> 
> You don't seem to have performed the above step, but [testing for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/) is important if we are to determine the source of problems like this one.

It is rather strange you say that, why would you say that?
I have disabled all but the woocommerce required plugins, the error still came up.
This is one of the first things I do for ANY plugin problem.

The issue I have with this site it's a life site, it too contains an online learning platform.
I cannot keep it down and/or plugins disabled for a long periods of time.

> 
> > Also I have found another ISSUE talking about the same problem: [woocommerce/action-scheduler#730](https://github.com/woocommerce/action-scheduler/issues/730)
> 
> At this stage, I don't think we can be sure that is the very same problem.
> 
Ok.


Also, there is an entry in the scheduler log I have just seen
action_scheduler/migration_hook | Failed |   | action-scheduler-migration | Non-repeating | 2023-01-16 07:23:55 +0000 (4 months 6 days ago)

Not sure what I did on the 16.01.23

**Comment by barryhughes** [comment] 2023-05-23 18:14
> Also, there is an entry in the scheduler log I have just seen
action_scheduler/migration_hook | Failed |   | action-scheduler-migration | Non-repeating | 2023-01-16 07:23:55 +0000 (4 months 6 days ago)

Actions can fail sometimes, but if you don't see this consistently it probably is nothing to worry about (and is likely unrelated to the core problem you reported).

**Comment by barryhughes** [comment] 2023-05-23 18:14
In your original message you noted:

> I searched for the function 'as_get_scheduled_actions' and it does indeed NOT EXIST in the entire tree of the website.
> However the actual call to the function come from within the woocommerce directory tree ONLY.

It sounds like you were not notified of my reply, but I followed up with this note:

> Action Scheduler library is bundled within WooCommerce. For example, here is a link showing the location of the function you were searching for, in our latest release:
>
> https://plugins.trac.wordpress.org/browser/woocommerce/tags/7.2.2/packages/action-scheduler/functions.php#L277

If you are comfortable using a file manager or similar tool, can you check if you see the function now? To be clear, in your case, you would probably have to navigate to:

`wp-content/plugins/woocommerce/packages/action-scheduler/functions.php`

Is that file present and do you see the function now? If not, you may need to re-install WooCommerce. 

Either way, if you are still encountering the same problem *(call to undefined function as_get_scheduled_actions)* then I think the best course of action is to open a fresh issue, over on the WooCommerce issue tracker, since the problem is probably not in Action Scheduler itself but rather happens as a result of thee way things are structured in WooCommerce Core:

[WooCommerce > New Issue > Bug Report](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&projects=&template=1-bug-report.yml)
