### ISSUE TITLE
Restore post merge CI jobs

### ISSUE THREAD

**Issue by rrennick** [woothemes/woocommerce#44003] opened 2024-01-23 15:27 UTC
**Issue Description:**

The new CI matrix [generates an error](https://github.com/woocommerce/woocommerce/actions/runs/7624031316) on merge to trunk because `base-ref` is not set. If you run `ci-jobs` with a base ref of `trunk, it produces no jobs.

```
# pnpm utils ci-jobs origin/trunk

> woocommerce-monorepo@ utils /Users/ronrennick/Sites/wc/wp-content/woocommerce
> ./tools/monorepo-utils/bin/run "ci-jobs" "origin/trunk"
                                                                         
✔ Parsing Project Graph... complete.
✔ Pulling File Changes... complete.
✔ Creating Jobs... complete.
No lint jobs to run.
No test jobs to run.
```

**Comment by jonathansadowski** [comment] 2024-01-23 15:55
This looks to be a dupe of #43679

**Closed as not planned by jonathansadowski** 2024-01-23 15:55 UTC
Labels: focus: monorepo infrastructure
