### ISSUE TITLE
WooCommerce order status not  update as transaction done and shipping status changes

### ISSUE THREAD

**Issue by rahul738544** [woothemes/woocommerce#49185] opened 2024-07-05 10:48 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

from last few days there is problem I found that Woocommerce order status not changed as transaction done or any shipping movement status are changing, I trided it change to manually but return to same stutus "failed" and continuously sending  emails at reporting emails 

### Expected behavior

Normally when successful transaction status changes to processing and while it completed to delivery then it shows the order his complete, but not even serial keys are delivery it shows failed and also after transaction successful it show only failed please find any solution

### Actual behavior

showing wrong status and malfunctioning for sending status emails of "orders failed" even order completed its process.  In case of digital products it shows failed after successful transaction completion and software keys are delivered to customer.

### Steps to reproduce

![image](https://github.com/woocommerce/woocommerce/assets/156095636/3c6acd9f-ce78-4abf-8583-f1a09737c868)

this is the orders screen order #14952 is done with COD but it shows failed 

![image](https://github.com/woocommerce/woocommerce/assets/156095636/4ffbf053-6ad6-45c1-99a7-0ac91cae019e)

this is showing order #14952 constantly getting email on after successful order done

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.0.2
Legacy REST API Package Version: ✔ 1.0.4
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.1.27
PHP Post Max Size: 2 GB
PHP Time Limit: 360
PHP Max Input Vars: 5000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.11.8-MariaDB-cll-lve
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 5
acf-field-group: 3
astra-advanced-hook: 1
attachment: 1094
aw_workflow: 7
awl-labels: 5
cartflows_flow: 1
cartflows_step: 3
cms_block: 23
e-landing-page: 1
elementor_library: 5
fpf_fields: 1
mailpoet_page: 1
mc4wp-form: 1
nav_menu_item: 149
ni-order-status: 6
oembed_cache: 4
page: 17
pi_dpmw_rules: 1
portfolio: 9
post: 1
product: 207
product_variation: 6
product-feed: 2
revision: 37
rm_content_editor: 1
sc_form: 1
shop_order: 34
sp_wps_shortcodes: 1
viwcpf_filter_block: 7
viwcpf_filter_menu: 1
wafs: 2
whatsapp-accounts: 1
woodmart_layout: 4
woodmart_sidebar: 2
woodmart_size_guide: 1
woodmart_slide: 3
woodmart_woo_fbt: 5
woodmart_woo_lv: 3
wp_global_styles: 1
wp_navigation: 1
wp_template: 2
wp_template_part: 1
yith_wcan_preset: 1
yith_wcps_type: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

PayU India: by PayU – 4.1.1
Advanced Custom Fields: by WP Engine – 6.3.3
Disable Gutenberg: by Jeff Starr – 3.1.2
Disable payment method / COD fees for Order for WooCommerce: by PI Websolution – 1.1.7.41
Easy Product Bundles for WooCommerce: by Product Bundles Team – 4.9.1
Elementor Pro: by Elementor.com – 3.22.1
Elementor: by Elementor.com – 3.22.3
Google Listings and Ads: by WooCommerce – 2.7.5
Site Kit by Google: by Google – 1.130.0
Header Footer Code Manager: by DraftPress – 1.1.38
Hostinger Tools: by Hostinger – 3.0.2
LiteSpeed Cache: by LiteSpeed Technologies – 6.2.0.1
Live Sales Notifications for WooCommerce: by PI Websolution – 2.2.76
PhonePe Payment Solutions: by PhonePe – 2.0.11
Rank Math SEO PRO: by Rank Math – 3.0.65
Rank Math SEO: by Rank Math – 1.0.222
Shiprocket: by Shiprocket – 2.0.2
Simple Chat Button: by Rasoul Mousavian – 1.8.0
Temporary Login Without Password: by StoreApps – 1.8.3
WC Serial Numbers: by PluginEver – 1.7.5
WooCommerce Free Shipping Per Product: by WPRuby – 1.2.5
Woo Payment Discounts: by WPCodelibrary – 1.3.0
1 Razorpay: Signup for FREE PG: by Team Razorpay – 4.6.7
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Legacy REST API: by WooCommerce – 1.0.4
WooCommerce: by Automattic – 9.0.2
Woodmart Core: by  – 1.0.36
WP Mail Logging: by WP Mail Logging Team – 1.12.0

### Inactive Plugins (0) ###


### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: object-cache.php

### Must Use Plugins (1) ###

Disable Auto Updates: by  –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: easy_product_bundle (easy_product_bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 7 MB

### WC Pages ###

Shop base: #9 - /shop/
Cart: #10 - /basket/
Checkout: #11 - /checkout/
My account: #12 - /my-account/
Terms and conditions: #122 - /terms-and-conditions/

### Theme ###

Name: Woodmart
Version: 8.2.0
Author URL: http://themeforest.net/user/xtemos
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php version 3.4.0 is out of date. The core version is 8.6.0
woodmart/woocommerce/cart/cart-item-data.php
woodmart/woocommerce/cart/cart.php version 7.4.0 is out of date. The core version is 7.9.0
woodmart/woocommerce/cart/cross-sells.php
woodmart/woocommerce/cart/mini-cart.php version 5.2.0 is out of date. The core version is 7.9.0
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/checkout/thankyou.php version 3.7.0 is out of date. The core version is 8.1.0
woodmart/woocommerce/content-product-cat.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php
woodmart/woocommerce/global/quantity-input.php version 7.4.0 is out of date. The core version is 7.8.0
woodmart/woocommerce/loop/add-to-cart.php version 3.3.0 is out of date. The core version is 9.0.0
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php version 2.0.0 is out of date. The core version is 7.8.0
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php
woodmart/woocommerce/product-searchform.php
woodmart/woocommerce/single-product/add-to-cart/grouped.php
woodmart/woocommerce/single-product/add-to-cart/variable.php
woodmart/woocommerce/single-product/meta.php
woodmart/woocommerce/single-product/product-attributes.php
woodmart/woocommerce/single-product/product-image.php version 3.5.1 is out of date. The core version is 7.8.0
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/description.php
woodmart/woocommerce/single-product/tabs/tabs.php
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product-reviews.php
woodmart/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
pattern-toolkit-full-composability
product-pre-publish-modal
settings
async-product-editor-category-field
launch-your-store
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-06 08:05:26 +05:30
Options: ✔
Notes: 81
Onboarding: completed

### Action Scheduler ###

Complete: 54,721
Oldest: 2024-06-04 10:42:17 +0000
Newest: 2024-07-05 10:40:04 +0000

Failed: 12,751
Oldest: 2023-10-20 16:46:15 +0000
Newest: 2024-07-05 10:40:03 +0000

Pending: 11
Oldest: 2024-07-05 10:40:31 +0000
Newest: 2024-07-30 00:06:03 +0000


### Status report information ###

Generated at: 2024-07-05 16:10:30 +05:30
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by vbelolapotkov** [comment] 2024-07-09 12:30
Hey @rahul738544, thanks for your report! I might be wrong, but it looks like some extension is messing up with order statuses. What do you see in order notes from all these failed orders? Do you know if anything has changed on the store before the problem started to appear? 

It looks like you're using Shiprocket for managing orders delivery, correct? Have you tried a plugin conflict test on the store?

Asking all these questions, because I don't see signs of WooCommerce functioning incorrectly yet.

**Comment by vbelolapotkov** [comment] 2024-07-17 09:35
I'm closing this one because we can't reproduce on our end. @rahul738544 feel free to reopen if the issue is still relevant and there is more information about it.

**Closed as completed by vbelolapotkov** 2024-07-17 09:35 UTC
Labels: Bug, Payments, type: community contribution, Payments Engineering
