### ISSUE TITLE
Back to top after Product Collection pagination

### ISSUE THREAD

**Issue by asafm7** [woothemes/woocommerce#42829] opened 2023-12-14 15:28 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When clicking on a new page on a Product Collection pagination placed on the bottom of the grid, the scrolling position remains on the bottom of the grid.

### Expected behavior

The page should be scrolled back to the top of the grid.

### Actual behavior

The scrolling position remains on the bottom of the grid.

### Steps to reproduce

Use a Product Collection block with a pagination at the bottom.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://hobbies4.life
Site address (URL): https://hobbies4.life
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.1.26
PHP Post Max Size: 64 MB
PHP Time Limit: 600
PHP Max Input Vars: 1800
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.16-MariaDB-cll-lve
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: whHhGW_
Total Database Size: 93.82MB
Database Data Size: 76.37MB
Database Index Size: 17.45MB
whHhGW_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
whHhGW_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_aryo_activity_log: Data: 1.27MB + Index: 1.47MB + Engine InnoDB
whHhGW_blc_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_blc_instances: Data: 1.52MB + Index: 0.22MB + Engine InnoDB
whHhGW_blc_links: Data: 5.52MB + Index: 0.75MB + Engine InnoDB
whHhGW_blc_synch: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_bwt_failed_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_bwt_passed_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_cky_banners: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
whHhGW_cky_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_cky_cookie_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_cmplz_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
whHhGW_indexnow_failed_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_indexnow_passed_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_litespeed_avatar: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_litespeed_crawler: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_litespeed_crawler_blacklist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_litespeed_url: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
whHhGW_litespeed_url_file: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
whHhGW_options: Data: 5.27MB + Index: 0.13MB + Engine InnoDB
whHhGW_postmeta: Data: 6.52MB + Index: 4.03MB + Engine InnoDB
whHhGW_posts: Data: 42.52MB + Index: 0.58MB + Engine InnoDB
whHhGW_relevanssi: Data: 4.48MB + Index: 6.94MB + Engine InnoDB
whHhGW_relevanssi_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_termmeta: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
whHhGW_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
whHhGW_term_relationships: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
whHhGW_term_taxonomy: Data: 1.45MB + Index: 0.03MB + Engine InnoDB
whHhGW_tinvwl_analytics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_tinvwl_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_tinvwl_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_usermeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
whHhGW_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_vrts_alerts: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
whHhGW_vrts_tests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
whHhGW_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
whHhGW_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_orders: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
whHhGW_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_wc_product_attributes_lookup: Data: 0.19MB + Index: 0.13MB + Engine InnoDB
whHhGW_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
whHhGW_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wfblockediplog: Data: 0.27MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_wfconfig: Data: 1.28MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wffilemods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfhits: Data: 2.02MB + Index: 0.25MB + Engine InnoDB
whHhGW_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_wfknownfilelist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wflogins: Data: 1.09MB + Index: 0.16MB + Engine InnoDB
whHhGW_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
whHhGW_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfnotifications: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
whHhGW_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
whHhGW_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
whHhGW_yoast_indexable: Data: 0.19MB + Index: 0.09MB + Engine InnoDB
whHhGW_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
whHhGW_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
whHhGW_yoast_prominent_words: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
whHhGW_yoast_seo_links: Data: 0.16MB + Index: 0.09MB + Engine InnoDB

### Post Type Counts ###

acf-field: 81
acf-field-group: 4
attachment: 374
feedback: 65
hobby: 4
oembed_cache: 71
page: 15
post: 18
product: 71
revision: 2955
wp_block: 4
wp_global_styles: 7
wp_navigation: 2
wp_template: 11
wp_template_part: 3
wpcode: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

ManageWP - Worker: by GoDaddy – 4.9.17
ACF Content Analysis for Yoast SEO: by Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 3.1

Advanced Custom Fields PRO: by WP Engine – 6.2.4
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
Activity Log: by Activity Log Team – 2.9.0
Bing Webmaster Url Submission: by Bing Webmaster – 1.0.13
Broken Link Checker: by WPMU DEV – 2.2.3
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 6.5.6
Site Kit by Google: by Google – 1.115.0
IndexNow: by Microsoft Bing – 1.0.1
Jetpack: by Automattic – 12.9
LiteSpeed Cache: by LiteSpeed Technologies – 6.0
Loco Translate: by Tim Whitlock – 2.6.6
Mailgun: by Mailgun – 1.9.6
Performance Lab: by WordPress Performance Team – 2.7.0
Relevanssi: by Mikko Saari – 4.21.1
TI WooCommerce Wishlist: by TemplateInvaders – 2.8.0
Tidio Chat: by Tidio Ltd. – 6.0.11
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.23.13

VRTs – Visual Regression Tests: by Bleech – 1.6.0
WooCommerce: by Automattic – 8.4.0
Wordfence Security: by Wordfence – 7.11.0
Yoast SEO Premium: by Team Yoast – 21.6
Yoast SEO: by Team Yoast – 21.7

### Inactive Plugins (2) ###

Query Monitor: by John Blackbourn – 3.15.0
SearchWP Modal Search Form: by SearchWP
LLC – 0.5.3

### Dropin Plugins (2) ###

maintenance.php: maintenance.php
object-cache.php: Performance Lab Server Timing Object Cache Drop-In

### Must Use Plugins (2) ###

Deactivate Plugins on Staging: by  –
ManageWP - Worker Loader: by GoDaddy – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #653 - /
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: #656 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Loudness Child Theme
Version: 0.0.1
Author URL: 
Child Theme: ✔
Parent Theme Name: Loudness
Parent Theme Version: 1.0.5
Parent Theme Author URL: https://automattic.com
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /home/asafdevc/hobbies4.life/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/error.php
/home/asafdevc/hobbies4.life/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/notice.php
/home/asafdevc/hobbies4.life/wp-content/plugins/woocommerce/packages/woocommerce-blocks/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-15 14:56:39 +00:00
Options: ✔
Notes: 92
Onboarding: skipped

### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Complete: 34
Oldest: 2023-11-14 08:24:03 +0000
Newest: 2023-12-14 08:54:03 +0000

Failed: 9
Oldest: 2023-04-12 15:59:56 +0100
Newest: 2023-06-01 14:52:29 +0100

Pending: 1
Oldest: 2023-12-15 08:54:03 +0000
Newest: 2023-12-15 08:54:03 +0000

### Status report information ###

Generated at: 2023-12-14 15:26:53 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Aljullu** [comment] 2023-12-19 17:47
Thanks for opening this issue, @asafm7! It looks like another user has already filled the same issue before, so in order to consolidate all the conversations/discussion in one single place, I will close this issue as duplicate of https://github.com/woocommerce/woocommerce/issues/42195.

**Closed as not planned by Aljullu** 2023-12-19 17:47 UTC
Labels: Bug, type: community contribution, Kirigami, Blocks/Patterns/Templates
