### ISSUE TITLE
Problème Notes de Commande Woocommerce

### ISSUE THREAD

**Issue by libbruneteaux** [woothemes/woocommerce#30818] opened 2021-09-25 07:50 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

**Les notes des commandes ont disparue...** Comment les retrouver ? 

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by tammullen** [comment] 2021-09-28 18:02
Hi @libbruneteaux ,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by libbruneteaux** [comment] 2021-10-07 09:47
Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)
Steps to reproduce the bug:

    Go to 'woocommerce > order'
    Click on 'the last order'
    
    See error on "Notes de Commande"

**Expected behavior**
Les notes de commandes ont disparue ! 


WordPress Environment
`
### WordPress Environment ###

WordPress address (URL): http://lwsxrg75rhs2.librairiebruneteaux.fr
Site address (URL): http://lwsxrg75rhs2.librairiebruneteaux.fr
WC Version: 5.7.1
REST API Version: ✔ 5.7.1
WC Blocks Version: ✔ 6.0.2
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.7.1
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 128 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.24
PHP Post Max Size: 6 Mo
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.60-0+deb7u1-log - Nous recommandons MySQL version 5.6 minimum. Voir : Exigences de WordPress
Max Upload Size: 64 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.7.1
WC Database Prefix: mjxYu
Taille totale de la base de données: 354.82MB
Taille de la base de données: 340.25MB
Taille de l’index: 14.57MB
mjxYuwoocommerce_sessions: Données : 273.31MB + Index : 3.79MB + Moteur MyISAM
mjxYuwoocommerce_api_keys: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
mjxYuwoocommerce_attribute_taxonomies: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuwoocommerce_downloadable_product_permissions: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuwoocommerce_order_items: Données : 0.05MB + Index : 0.03MB + Moteur MyISAM
mjxYuwoocommerce_order_itemmeta: Données : 0.41MB + Index : 0.22MB + Moteur MyISAM
mjxYuwoocommerce_tax_rates: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
mjxYuwoocommerce_tax_rate_locations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuwoocommerce_shipping_zones: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuwoocommerce_shipping_zone_locations: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuwoocommerce_shipping_zone_methods: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuwoocommerce_payment_tokens: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuwoocommerce_payment_tokenmeta: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuwoocommerce_log: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuactionscheduler_actions: Données : 3.25MB + Index : 1.02MB + Moteur MyISAM
mjxYuactionscheduler_claims: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuactionscheduler_groups: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
mjxYuactionscheduler_logs: Données : 3.10MB + Index : 1.87MB + Moteur MyISAM
mjxYuac_abandoned_cart_history_lite: Données : 27.67MB + Index : 0.67MB + Moteur MyISAM
mjxYuac_email_templates_lite: Données : 0.01MB + Index : 0.00MB + Moteur MyISAM
mjxYuac_guest_abandoned_cart_history_lite: Données : 0.01MB + Index : 0.00MB + Moteur MyISAM
mjxYuac_sent_history_lite: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuaiowps_events: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuaiowps_failed_logins: Données : 0.02MB + Index : 0.01MB + Moteur MyISAM
mjxYuaiowps_global_meta: Données : 4.11MB + Index : 0.00MB + Moteur MyISAM
mjxYuaiowps_login_activity: Données : 0.03MB + Index : 0.01MB + Moteur MyISAM
mjxYuaiowps_login_lockdown: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuaiowps_permanent_block: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYucommentmeta: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
mjxYucomments: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
mjxYuebay_accounts: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuebay_auctions: Données : 0.01MB + Index : 0.01MB + Moteur MyISAM
mjxYuebay_categories: Données : 0.69MB + Index : 0.81MB + Moteur MyISAM
mjxYuebay_jobs: Données : 0.01MB + Index : 0.00MB + Moteur MyISAM
mjxYuebay_log: Données : 0.05MB + Index : 0.00MB + Moteur MyISAM
mjxYuebay_messages: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuebay_orders: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuebay_payment: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuebay_profiles: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuebay_shipping: Données : 0.01MB + Index : 0.00MB + Moteur MyISAM
mjxYuebay_sites: Données : 0.01MB + Index : 0.00MB + Moteur MyISAM
mjxYuebay_stocks_log: Données : 0.04MB + Index : 0.00MB + Moteur MyISAM
mjxYuebay_store_categories: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuebay_transactions: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYufailed_jobs: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYufb3d_pages: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYulinks: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYumabmobileapp_component_types: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYumab_banner: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYumab_banner_image: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYumab_cms_page_data: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYumab_fcm_details: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYumab_mobileapp_banners: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYumab_mobileapp_layouts: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYumab_mobileapp_layout_component: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYumab_mobileapp_product_data: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYumab_mobileapp_tab_bar: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
mjxYumab_mobileapp_top_category: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYumab_push_notification_history: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYumab_unique_verification: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYumailchimp_carts: Données : 0.02MB + Index : 0.00MB + Moteur MyISAM
mjxYumailchimp_jobs: Données : 0.01MB + Index : 0.00MB + Moteur MyISAM
mjxYuoptions: Données : 9.13MB + Index : 0.54MB + Moteur MyISAM
mjxYupimwick_gift_card: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYupimwick_gift_card_activity: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYupostmeta: Données : 10.69MB + Index : 4.16MB + Moteur MyISAM
mjxYuposts: Données : 6.85MB + Index : 0.71MB + Moteur MyISAM
mjxYuqueue: Données : 0.02MB + Index : 0.00MB + Moteur MyISAM
mjxYutermmeta: Données : 0.02MB + Index : 0.02MB + Moteur MyISAM
mjxYuterms: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
mjxYuterm_relationships: Données : 0.09MB + Index : 0.20MB + Moteur MyISAM
mjxYuterm_taxonomy: Données : 0.01MB + Index : 0.01MB + Moteur MyISAM
mjxYuusermeta: Données : 0.26MB + Index : 0.04MB + Moteur MyISAM
mjxYuusers: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
mjxYuwcpdf_invoice_number: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuwc_admin_notes: Données : 0.02MB + Index : 0.00MB + Moteur MyISAM
mjxYuwc_admin_note_actions: Données : 0.01MB + Index : 0.00MB + Moteur MyISAM
mjxYuwc_category_lookup: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
mjxYuwc_customer_lookup: Données : 0.02MB + Index : 0.02MB + Moteur MyISAM
mjxYuwc_download_log: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuwc_order_coupon_lookup: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuwc_order_product_lookup: Données : 0.03MB + Index : 0.04MB + Moteur MyISAM
mjxYuwc_order_stats: Données : 0.02MB + Index : 0.02MB + Moteur MyISAM
mjxYuwc_order_tax_lookup: Données : 0.01MB + Index : 0.02MB + Moteur MyISAM
mjxYuwc_product_meta_lookup: Données : 0.18MB + Index : 0.25MB + Moteur MyISAM
mjxYuwc_reserved_stock: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuwc_tax_rate_classes: Données : 0.00MB + Index : 0.01MB + Moteur MyISAM
mjxYuwc_webhooks: Données : 0.00MB + Index : 0.00MB + Moteur MyISAM
mjxYuwms_labels: Données : 0.05MB + Index : 0.01MB + Moteur MyISAM

### Post Type Counts ###

attachment: 2862
customize_changeset: 1
jetpack_migration: 2
jp_img_sitemap: 6
jp_img_sitemap_index: 3
jp_sitemap: 3
jp_sitemap_master: 3
nav_menu_item: 65
page: 11
post: 2
product: 954
product_variation: 1662
pw_gift_rule: 3
revision: 130
shop_order: 241
shop_order_refund: 5
ulpb_post: 1

### Security ###

Secure connection (HTTPS): ❌
					Votre boutique n’utilise pas HTTPS. En savoir plus sur HTTPS et les certificats SSL.
Hide errors from visitors: ✔

### Active Plugins (27) ###

All In One WP Security: par Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.4.9

Delete All Comments of wordpress: par Navneet Soni – 4.1
Ever Woo Free Product: par Ever Team – 1.2.7
Facebook for WooCommerce: par Facebook – 2.6.5
Instant Articles for WP: par Automattic
Dekode
Facebook – 4.2.1

Flexible Shipping: par WP Desk – 4.8.4
Reviews and Rating - Google My Business: par Noah Hearle
Design Extreme – 3.41

3D FlipBook - Lite Edition: par iberezansky – 1.11.5
Jetpack: par Automattic – 10.2
Mailchimp for WooCommerce: par Mailchimp – 2.5.3
PluginOps Optin Builder: par PluginOps – 4.0.7.9
PluginOps Landing Page Builder: par PluginOps – 1.4.9.2
Product Assembly / Gift Wrap / ... Cost for WooCommerce: par Webdados – 2.2.2
PW WooCommerce Gift Cards Pro: par Pimwick
LLC – 1.330

User Role Editor: par Vladimir Garagulya – 4.60.2
Chronopost & Mondial relay pour WooCommerce - WCMultiShipping: par L’équipe WCMultiShipping – 1.0.0
WooCommerce Blocks: par Automattic – 6.0.2
Panier abandonné gratuit pour WooCommerce: par Tyche Softwares – 5.10.0
WooCommerce Admin: par WooCommerce – 2.7.1
PW Woocommerce Advanced Gift Rules: par Proword – 5.6
WooCommerce Bulk Discount: par Rene Puchinger – 3.0
WooCommerce PayPal Payments: par WooCommerce – 1.6.0
WooCommerce PDF Invoices & Packing Slips: par Ewout Fernhout – 2.10.1
WooCommerce Shipping & Tax: par WooCommerce – 1.25.18
WooCommerce: par Automattic – 5.7.1
WP-Lister Lite for eBay: par WP Lab – 3.0.5
WPFront Notification Bar: par Syam Mohan – 2.2.0.082910

### Inactive Plugins (1) ###

Woocommerce Gift Wrapper: par Little Package – 4.5

### Must Use Plugins (1) ###

1&1 Product Subdomain: par 1&1 – 1.1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Base de la boutique: #5 - /
Panier: #6 - /panier
Commander: #7 - /commande
Mon compte: #8 - /mon-compte
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Toujours
Version: 1.1.0
Author URL: http://automattic.com/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ❌ Non déclaré

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: No
Shop country code: FR
PayPal card processing available in country: Yes
Pay Later messaging available in country: Yes
Vault enabled: No

### Action Scheduler ###

Terminé: 7 953
Oldest: 2021-10-02 09:06:07 +0000
Newest: 2021-10-07 09:37:29 +0000

Échoué: 12
Oldest: 2021-07-27 16:26:10 +0000
Newest: 2021-07-27 16:26:10 +0000

En attente: 8
Oldest: 2021-10-07 09:46:33 +0000
Newest: 2021-10-08 00:14:34 +0000


### Status report information ###

Generated at: 2021-10-07 10:42:47 +01:00
`

**Comment by AashikP** [comment] 2021-10-23 09:26
Hi @libbruneteaux,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by AashikP** 2021-10-23 09:26 UTC
Labels: Bug
