### ISSUE TITLE
[CYS on Core] Investigate issue of certain blocks not rendering as expected.

### ISSUE THREAD

**Issue by nefeline** [woothemes/woocommerce#45475] opened 2024-03-11 10:14 UTC
**Issue Description:**

We have received feedback from a few folks informing us that, on occasion, a few blocks are failing to load in the CYS. We are opening this issue so we can prioritize investigating the problem and identify the steps to reproduce it.

**Comment by gigitux** [comment] 2024-03-13 14:43
This issue was caused by a regression in WordPress 6.5. The regression has been fixed in WordPress 6.5-RC2 thanks to this patch: https://core.trac.wordpress.org/changeset/57802

**Closed as completed by gigitux** 2024-03-13 14:43 UTC
Labels: Bug, plugin: woocommerce, Kirigami, Onboarding
