### ISSUE TITLE
[API] in_stock => false not working

### ISSUE THREAD

**Issue by ad-on-is** [woothemes/woocommerce#10850] opened 2016-05-04 09:08 UTC
My code:

    'product' => array('stock_quantity' => 100, 'in_stock' => false)

When saving this product, my expected result is a product, with stock 100 and `_stock_status` set to "outofstock".
Instead `_stock_status` is set to "instock".

My first assumption was that setting the `_stock_status` to "outofstock" while having a stock_amount > 0 doesn't work. But I can change the `_stock_status` in the backend to "outofstock" even when there's stock.

Cheers,
Adis

**Comment by claudiosmweb** [comment] 2016-05-04 10:38
@mikejolley by default we do the same in the admin interface. Should be we change it to run `wc_update_product_stock_status()` after `wc_update_product_stock()`?

**Comment by mikejolley** [comment] 2016-05-04 10:41
@claudiosmweb that could be problematic because then the status would never change automatically.

**Comment by claudiosmweb** [comment] 2016-05-04 10:45
@mikejolley that's what I'm thinking xD

@ad-on-is So need to change automatically, then this is "Won't fix". In other words, need you will need to update twice, like in the admin interface.

**Closed by claudiosmweb** 2016-05-04 10:45 UTC
Labels: Won't Fix

**Comment by mikejolley** [comment] 2016-05-04 10:49
@claudiosmweb you could for the sake of the API, do it afterwards if explicitly set in the call. If it's not set,  let core handle it?

In admin this isn't possible because all fields are posted.

**Comment by claudiosmweb** [comment] 2016-05-04 10:53
@mikejolley still not easy to handle on API, since we always save by default and to enable the first time. Maybe we can check it with the Products CRUD.

**Comment by ad-on-is** [comment] 2016-05-04 11:32
It works when I set `'stock_amount' => 0, 'is_stock' => false`. Then `_stock_status` is set to "outofstock" on the first time.

**Comment by claudiosmweb** [comment] 2016-05-04 11:59
@ad-on-is yep, because `stock_amount` will set the status after save the `in_stock`. This is expected behavior.

**Comment by claudiosmweb** [comment] 2016-05-04 12:00
https://github.com/woothemes/woocommerce/blob/master/includes/api/legacy/v3/class-wc-api-products.php#L1581-L1591

**Comment by ad-on-is** [comment] 2016-05-04 12:34
Ah, now I see. `set_stock()`triggers `check_stock_status()` which calls `set_stock_status()` in the core.

**Comment by ad-on-is** [comment] 2016-05-04 12:38
> @ad-on-is So need to change automatically, then this is "Won't fix". In other words, need you will need to update twice, like in the admin interface.

I don't think that this is an acceptable solution. Especially not in bulk-imports where it takes hours to import thousands of products, and then another few hours just to update the `stock_status`.
