### ISSUE TITLE
REST API: Create Order - Sign up fee is being used as discount.

### ISSUE THREAD

**Issue by seb86** [woothemes/woocommerce#31065] opened 2021-11-01 23:14 UTC
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When creating an order via the WC REST API for a subscriptions product with a sign up fee, the sign up fee is being used as a discount.

The totals are not being calculated correctly compared to when an order is created for a subscriptions product via the native checkout process.

**Expected behavior**

Totals are calculated correctly without manually setting the line item total and the sign up fee is not discounted.

Sign up fee should not be marked as a coupon in totals.

**Actual behavior**

Right now the sign up fee is displayed discounted and the totals show it as a coupon when no coupon is actually applied to the order.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a simple subscription product.
2. Set price as $20 and sign up fee as $5 with a billing period every month.
3. Publish product.

### Create a new order via native checkout.

4. View product page and press add to cart.
5. Checkout to process order.

When you view the order you will see the sign up fee was charged correctly.

### Create a new order via the WC REST API.

4. Make sure you only applying the product ID from the newly created product and the quantity is set to `1`.

Doesn't matter if the customer is a guest or you have assigned the order to a registered customer.

When you view the order, the line total is `$20` and underneith it says `$5` discount which is not what it should be at all.

You will also see in the totals area, it is marked under Coupon(s) -$5

I hope this bug can be fixed asap as this is critical for our use of the REST API.

**Screenshots**

> Product Data
![Product data](https://user-images.githubusercontent.com/497406/139753794-cf05e667-6242-4228-82a0-b92a3d5d6b46.png)

> Order after native checkout process
![Order after native checkout process](https://user-images.githubusercontent.com/497406/139753824-db18a74f-a594-4b14-94cd-332470bc9f44.png)

> Order created via WC REST API
![Order created via WC REST API](https://user-images.githubusercontent.com/497406/139753842-699161f7-e323-4e2a-9d65-1c507ca38d13.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
* WordPress v5.8.1
* WooCommerce v5.9
* WooCommerce Subscriptions v3.1.6

**Comment by seb86** [comment] 2021-11-03 14:44
Quick update. This issue was replicated with many older versions of WooCommerce.

**Comment by tammullen** [comment] 2021-11-03 20:28
Hi @seb86 

Thank you for reporting the issue. I believe this is on the WooCommerce Subscriptions side of things which is not a part of this repository. It is being developed in another repository which is private.

I created a bug report on your behalf in the correct (private) repository so that the right team could take a look further.

Because the issue initially appears to be not related to the WooCommerce plugin itself, I am going to close it. However, please rest assured that the WooCommerce Subscriptions team will take a look at it further. If there are any updates we will post them here or if there is a problem with WooCommerce Core itself we will reopen the issue.

**Closed as completed** 2021-11-03 20:29 UTC
Labels: Bug

**Comment by seb86** [comment] 2021-11-03 22:28
@tammullen Thank you for getting back to me. I look forward to any updates.

**Comment by brucealdridge** [comment] 2021-11-07 23:08
Hey @seb86 

I've had a look into this issue and am unable to reproduce this issue on a fresh install.

This was the code I used to test.

~~~php

$woocommerce = new Automattic\WooCommerce\Client(
	'http://testsite', 
	'ck_##############', 
	'cs_##############', 
	[
		'wp_api' => true,
		'version' => 'wc/v3'
	]
);

$data = [
	'payment_method' => 'bacs',
	'payment_method_title' => 'Direct Bank Transfer',
	'set_paid' => true,
	'billing' => [
		'first_name' => 'John', 
                 'last_name' => 'Doe',
		'address_1' => '969 Market',
		'address_2' => '',
		'city' => 'San Francisco',
		'state' => 'CA',
		'postcode' => '94103',
		'country' => 'US',
		'email' => 'john.doe@example.com',
		'phone' => '(555) 555-5555'
	],
	'shipping' => [
		'first_name' => 'John',
		'last_name' => 'Doe',
		'address_1' => '969 Market',
		'address_2' => '',
		'city' => 'San Francisco',
		'state' => 'CA',
		'postcode' => '94103',
		'country' => 'US'
	],
	'line_items' => [
		[
			'product_id' => 1,
			'quantity' => 1
		]
	],
];

$woocommerce->post('orders', $data);
~~~

I have confirmed that the signup fee does not get added in this instance and have added an issue to investigate this. 

If you can supply more information on how to replicate this issue rather than replying to this issue, can you please create a support ticket so we can get all the information we need - https://woocommerce.com/my-account/create-a-ticket/
please reference this closed issue.

Thank you.

**Comment by seb86** [comment] 2021-11-08 00:24
@brucealdridge Hey. Thank you for getting back to me. I clearly missed adding a step for you to get the same results as the screenshots provided but as you found out that the sign up fee is not being applied at all.

My tests were done in Postman so if you did the same and use this example order request as raw JSON for the body you will get the same results as shown above.

```json
{
  "payment_method": "bacs",
  "payment_method_title": "Direct Bank Transfer",
  "status": "completed",
  "currency": "USD",
  "billing": {
    "first_name": "John",
    "last_name": "Doe",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US",
    "email": "john.doe@example.com",
    "phone": "(555) 555-5555"
  },
  "shipping": {
    "first_name": "John",
    "last_name": "Doe",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US"
  },
  "line_items": [
    {
      "product_id": 81,
      "quantity": 1,
      "subtotal": "25"
    }
  ],
  "set_paid": true
}
```

Notice the subtotal is set as 25. Nothing else in the order request is asking it to discount $5

As a temporary fix for our solution we instead set the total as $25

```json
{
  "payment_method": "bacs",
  "payment_method_title": "Direct Bank Transfer",
  "status": "completed",
  "currency": "USD",
  "billing": {
    "first_name": "John",
    "last_name": "Doe",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US",
    "email": "john.doe@example.com",
    "phone": "(555) 555-5555"
  },
  "shipping": {
    "first_name": "John",
    "last_name": "Doe",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US"
  },
  "line_items": [
    {
      "product_id": 81,
      "quantity": 1,
      "total": "25"
    }
  ],
  "set_paid": true
}
```

Hope you can get it fixed asap.

Thanks again.

**Comment by brucealdridge** [comment] 2021-11-08 01:19
@seb86 It looks like that `"subtotal"` line is causing the issue. I can replicate the issue when this is added however this is not a documented feature.
I would recommend opening a ticket via the link I gave you above to talk to one of our Happiness engineers about the best solution for you. This may include either using the [fee_lines object](https://woocommerce.github.io/woocommerce-rest-api-docs/#order-fee-lines-properties) or using the [subscriptions specific api](https://woocommerce.github.io/subscriptions-rest-api-docs/#create-a-subscription) depending on the use-case.

**Comment by seb86** [comment] 2021-11-08 01:36
@brucealdridge The are two issues here. The first that the sign up fee is not being added as you found out and the second that if you were to manually set the subtotal of the item, it does not calculate the totals correctly and thinks that the sign up fee is used to discount the item without a coupon as shown in the third screenshot.

I'm well aware that is it not documented and it should not be. This is a bug that needs solving. I have provided with all I can.

I'm unable to use the support form provided via the link as I do not own a copy of the product. I use to have access to the subscriptions repository with permission by Prospress. Now I don't since acquisition.
