### ISSUE TITLE
Post merge CI run fails

### ISSUE THREAD

**Issue by rrennick** [woothemes/woocommerce#43286] opened 2024-01-04 15:43 UTC
**Issue Description:**

The [`Run tests against trunk after PR merge`](https://github.com/woocommerce/woocommerce/actions/workflows/smoke-test-pr-merge.yml) fails after every merge. In the random sample I check, it was the performance test that is failing.

**Comment by jonathansadowski** [comment] 2024-01-23 15:55
This looks to be a dupe of #43679

**Closed as not planned by jonathansadowski** 2024-01-23 15:55 UTC
Labels: focus: monorepo infrastructure
