### ISSUE TITLE
Price Amount Cart Incorrect

### ISSUE THREAD

**Issue by Cocoroi** [woothemes/woocommerce#31273] opened 2021-11-22 15:25 UTC
Hello,

I have a problem, in the basket (whether it is the page or in the menu) the price is not correct.
![Screenshot_1](https://user-images.githubusercontent.com/78262052/142888200-0f35b2bd-405f-438e-acfe-f3fb60dccea2.png)

I'm using QuadMenu for the menu just in case.

Also, on some products, the site applies a reduction of 1 cent on its own ...

Regarding the price, I managed to make it roughly consistent by disabling the Booster Checkout Fees but I don't want to remove it: /
![Screenshot_2](https://user-images.githubusercontent.com/78262052/142888203-ae4cad2b-61cb-4d5d-bdfb-074a1dcc7b3d.png)

Please help me !

**Comment by rodelgc** [comment] 2021-11-25 06:39
Hi @Cocoroi,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by rodelgc** 2021-11-25 06:39 UTC
Labels: type: support request
