### ISSUE TITLE
woocomerce coupon discounts with multiple flat rates methods not working?

### ISSUE THREAD

**Issue by aloksharma1** [woothemes/woocommerce#30713] opened 2021-09-14 18:44 UTC
I have a woocommerce site, where we use **discount coupons** to provide **free shipping or flat rate shipping** to our customers. Generally our coupons system works fine for our needs, now we have to provide our users with multiple flat rate based discount coupons and we were able to easily add multiple types of flat rate shipping methods using : 

**woocommerce->settings->shipping methods->shipping zones->shipping methods** 

as show in image here :

[![enter image description here][1]][1]

But the problem is my generated coupon only shows flat rate (parent) option in **woocommerce** and coupon always targets the first flat rate shipping method of 24.95 price rule when checkout, like this :
[![enter image description here][2]][2]

[![enter image description here][3]][3]

  [1]: https://i.stack.imgur.com/rkndm.png
  [2]: https://i.stack.imgur.com/JLtQs.png
  [3]: https://i.stack.imgur.com/NEbbF.png

Here what I want to target is not just flat rates, but different types of flat rates **[as shown in first pic]** for different coupons. I tried checking the database, but woocomerce generated database uses WordPress default tables to manage records which makes it very difficult to me to find the right target.

so here is my query:
1. is there any way to do this using database?
2. are their any plugin available which can make me enabled to add inner shipping methods to coupon discounts?
3. or if its not possible in woocommerce , do we need to make custom code?

**Comment by juliaamosova** [comment] 2021-09-18 19:36
Hi @aloksharma1,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by juliaamosova** 2021-09-18 19:36 UTC
Labels: type: support request
