### ISSUE TITLE
logged-out out cart overwrites logged-in cart

### ISSUE THREAD

**Issue by HatiSchuh14** [woothemes/woocommerce#36599] opened 2023-01-25 11:34 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When I have items in the cart before logging in, they overwrite the accounts cart.

As an example:
I am logged in an there is 5 x Item1 in my accounts cart. 
I decide to add another. So I go to the shop site and add 1 x Item1. Now the cart contains 6 x Item1. 
This seems right to me.  
Now i log out and decide to add another 2 x item1, so I add them to the chart. During checkout I get asked to log in. I do that and now I expect the 2 x Item1 to be added to the 6 x Item1 that are in the cart of my account. 
But now there are only 2 x Item1, instead of 8.

### Expected behavior

When the items from the logged-out cart get merged into the logged-in cart, items that occur in both carts should be added up.

cart:
3 x Item1
1 x Item2

logged out
add 2 x Item1 to cart
log in

cart:
5 x Item1
1 x Item2

### Actual behavior

When the items from the logged-out cart get merged into the logged-in cart, the number of the items that occur in both carts are replaced by the logged-out cart.

cart:
3 x Item1
1 x Item2

logged out
add 2 x Item1 to cart
log in

cart:
2 x Item1 (should be 5)
1 x Item2

Note, that only the number of Item1 is affected

### Steps to reproduce

On a minimal site with just one kind of item to choose from:

**Logged in**
1. have some items in the cart
2. add item to the cart
3. go to checkout
4. go to cart

There should now be _one more_ item in the cart.

**Logged out**
1. have some items in the cart
6. log out
7. add item to the cart
8. go to checkout
9. login
10. go to cart

There should now be _one_ item in the cart, regardless of how many there have been before.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://shop.radiodatacenter.net
Site address (URL): https://shop.radiodatacenter.net
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.4.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.27
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 10.6.11-MariaDB-0ubuntu0.22.04.1
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: QCvscK4M_
Total Database Size: 7.49MB
Database Data Size: 5.68MB
Database Index Size: 1.81MB
QCvscK4M_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
QCvscK4M_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
QCvscK4M_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
QCvscK4M_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
QCvscK4M_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
QCvscK4M_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
QCvscK4M_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
QCvscK4M_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
QCvscK4M_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
QCvscK4M_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
QCvscK4M_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
QCvscK4M_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
QCvscK4M_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
QCvscK4M_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
QCvscK4M_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
QCvscK4M_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
QCvscK4M_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
QCvscK4M_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
QCvscK4M_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
QCvscK4M_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
QCvscK4M_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
QCvscK4M_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
QCvscK4M_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
QCvscK4M_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
QCvscK4M_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
QCvscK4M_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
QCvscK4M_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
QCvscK4M_options: Data: 4.03MB + Index: 0.06MB + Engine InnoDB
QCvscK4M_postmeta: Data: 0.11MB + Index: 0.14MB + Engine InnoDB
QCvscK4M_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
QCvscK4M_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
QCvscK4M_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
QCvscK4M_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
QCvscK4M_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
QCvscK4M_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
QCvscK4M_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
QCvscK4M_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
QCvscK4M_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
QCvscK4M_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
QCvscK4M_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
QCvscK4M_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
QCvscK4M_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
QCvscK4M_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
QCvscK4M_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
QCvscK4M_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
QCvscK4M_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
QCvscK4M_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
QCvscK4M_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
QCvscK4M_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
QCvscK4M_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
QCvscK4M_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
QCvscK4M_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
QCvscK4M_wpns_transactions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 3
customize_changeset: 8
elementor_library: 1
nav_menu_item: 4
page: 8
post: 2
product: 2
revision: 38
shop_order: 17
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Classic Widgets: by WordPress Contributors – 0.3
Elementor: by Elementor.com – 3.10.1
OAuth Single Sign On - SSO (OAuth client): by miniOrange – 98.4.7
WooCommerce Blocks: by Automattic – 9.4.0
WooCommerce Payments: by Automattic – 5.3.0
WooCommerce Shipping & Tax: by WooCommerce – 2.2.0 (update to version 2.2.1 is available)
WooCommerce: by Automattic – 7.3.0
WP-Members: by Chad Butler – 3.4.6
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.9.6

### Inactive Plugins (10) ###

Akismet Anti-Spam: by Automattic – 5.0.2
Debug Bar: by wordpressdotorg – 1.1.4
Google Listings and Ads: by WooCommerce – 2.3.5
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 11.7.1
OAuth Single Sign On - SSO (OAuth Client): by miniOrange – 6.23.7
Ocean Extra: by OceanWP – 2.0.6
Query Monitor: by John Blackbourn – 3.11.1
WP Debugging: by Andy Fragen – 2.11.16
WP REST API - OAuth 1.0a Server: by WP REST API Team – 0.3.0

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Must Use Plugins (1) ###

Elementor Safe Mode: by Elementor.com – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-25 14:40:06 +00:00
Options: ✔
Notes: 55
Onboarding: completed

### WooCommerce Payments ###

Version: 5.3.0
Connected to WPCOM: Yes
Blog ID: 213408327
Account ID: acct_1MFfDx2EJCBGGxhK

### Action Scheduler ###

Canceled: 2
Oldest: 2023-01-03 13:07:00 +0000
Newest: 2023-01-04 08:11:34 +0000

Complete: 127
Oldest: 2022-12-26 06:00:06 +0000
Newest: 2023-01-25 07:06:53 +0000

Pending: 1
Oldest: 2023-01-26 07:06:46 +0000
Newest: 2023-01-26 07:06:46 +0000

### Status report information ###

Generated at: 2023-01-25 08:56:24 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment] 2023-01-30 12:58
Hi @HatiSchuh14,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using WooCommerce 7.3.0 version and WordPress 6.1.1 version.

Please find below the screencast for reference :

https://user-images.githubusercontent.com/94531721/215422833-f669cda3-9cb4-48e5-98d8-82506f00b0bd.mp4


Please provide us more detailed and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by HatiSchuh14** [comment] 2023-02-02 08:10
Hi there!  
In your screencast you had 3 x Beanie, 1 x Belt and 1 x Cap in your cart and then added a Longsleeve. To reproduce the bug you would have to log out and then add one of these three Items (Beany, Belt or Cap).  
For instance: when I would add 1 Beanie in your case here and then log in, there would be 1 x Beanie in the cart, not 4.

**Comment by vedanshujain** [comment] 2023-02-02 11:20
hey @HatiSchuh14 , thanks for the report. The behavior you are describing is actually expected, we don't want users to be presented with a different cart then the one they started with, especially during the checkout flow, just because they log in. Moreover many plugins and extensions rely on it, so changing it will cause issues for them too.

I am closing this issue for repo maintenance, but feel free to comment back if you disagree and we can reopen the issue and discuss further.

**Closed as completed by vedanshujain** 2023-02-02 11:20 UTC
Labels: Bug, status: won't fix, Cart, status: reproduction, plugin: woocommerce, type: community contribution

**Comment by HatiSchuh14** [comment] 2023-02-06 07:07
Alright. No, I have no problem with that, if it is the expected behavior. It just seemed a little bit off to me.  
Cheers!
