### ISSUE TITLE
State field in checkout - not populating as expected

### ISSUE THREAD

**Issue by cnicpon** [woothemes/woocommerce#32009] opened 2022-03-02 06:07 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

State field on the checkout page does not behave consistent with other forms on most websites. If you type F expecting to get Florida, you actually get California. Or if you type W expecting to get West Virginia, you get Delaware. This is not what people expect. Further, if you type an abbreviation, that doesn't work either. if you type GA, you don't get Georgia.

### Expected behavior

see above

### Actual behavior

see above

### Steps to reproduce

see above

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://brio.academy
Site address (URL): https://brio.academy
WC Version: 6.2.1
REST API Version: ✔ 6.2.1
WC Blocks Version: ✔ 6.7.3
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.1.0
Log Directory Writable: ✔
WP Version: ❌ 5.8.3 - There is a newer version of WordPress available (5.9.1)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Flywheel/5.1.0
PHP Version: 7.4.28
PHP Post Max Size: 300 MB
PHP Time Limit: 180
PHP Max Input Vars: 15000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.7.36-google
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.2.1
WC Database Prefix: wp_nojprt1q5z_
Total Database Size: 163.27MB
Database Data Size: 154.88MB
Database Index Size: 8.39MB
wp_nojprt1q5z_woocommerce_sessions: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_nojprt1q5z_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_nojprt1q5z_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_nojprt1q5z_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_actionscheduler_actions: Data: 0.34MB + Index: 0.56MB + Engine InnoDB
wp_nojprt1q5z_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_actionscheduler_logs: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_nojprt1q5z_afwc_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_afwc_commission_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_afwc_hits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_afwc_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_afwc_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_nojprt1q5z_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_comments: Data: 0.22MB + Index: 0.28MB + Engine InnoDB
wp_nojprt1q5z_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_fbv_attachment_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_gamipress_logs: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_nojprt1q5z_gamipress_logs_meta: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_gamipress_user_earnings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_gamipress_user_earnings_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_gf_entry_meta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_nojprt1q5z_gf_entry_notes: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_gf_form_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_lifterlms_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_lifterlms_events: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_lifterlms_events_open_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_lifterlms_notifications: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_nojprt1q5z_lifterlms_product_to_voucher: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_lifterlms_quiz_attempts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_lifterlms_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_lifterlms_user_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_lifterlms_vouchers_codes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_lifterlms_voucher_code_redemptions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_lifterlms_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_mlw_qm_audit_trail: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_mlw_questions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_mlw_quizzes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_mlw_results: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_options: Data: 5.34MB + Index: 0.13MB + Engine InnoDB
wp_nojprt1q5z_postmeta: Data: 139.02MB + Index: 3.95MB + Engine InnoDB
wp_nojprt1q5z_posts: Data: 5.22MB + Index: 0.44MB + Engine InnoDB
wp_nojprt1q5z_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_nojprt1q5z_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_nojprt1q5z_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_nojprt1q5z_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_usermeta: Data: 0.33MB + Index: 0.17MB + Engine InnoDB
wp_nojprt1q5z_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_nojprt1q5z_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_nojprt1q5z_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_nojprt1q5z_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_nojprt1q5z_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nojprt1q5z_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_yoast_indexable: Data: 0.45MB + Index: 0.36MB + Engine InnoDB
wp_nojprt1q5z_yoast_indexable_hierarchy: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_nojprt1q5z_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nojprt1q5z_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nojprt1q5z_yoast_seo_links: Data: 0.20MB + Index: 0.14MB + Engine InnoDB
wp_nojprt1q5z_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 10
acf-field-group: 4
attachment: 248
course: 29
custom_css: 1
custom-product-type: 1
customize_changeset: 5
fl-builder-template: 45
fl-theme-layout: 10
forum: 3
instructors: 21
lesson: 268
llms_access_plan: 19
llms_coupon: 2
llms_form: 3
llms_order: 2
llms_question: 7
llms_quiz: 4
nav_menu_item: 20
oembed_cache: 28
page: 43
points-award: 2
points-type: 1
post: 5
product: 140
revision: 1407
section: 35
shop_coupon: 26
shop_order: 242
shop_subscription: 37
topic: 2
wc_membership_plan: 4
wc_user_membership: 81
wp_block: 3
yaymail_template: 11

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

Gravity Forms: by Gravity Forms – 2.5.16
Advanced Custom Fields: by Delicious Brains – 5.12
Affiliate For WooCommerce: by StoreApps – 3.13.0
Astra Pro: by Brainstorm Force – 3.6.5
Beaver Builder Plugin (Pro Version): by The Beaver Builder Team – 2.5.2.1
Beaver Themer: by The Beaver Builder Team – 1.4.0.2
Ultimate Addons for Beaver Builder: by Brainstorm Force – 1.34.4
PowerPack for Beaver Builder: by IdeaBox Creations – 2.21.2
Z-Index Add On for Beaver Builder: by SiteSpot Dev – 1.0.2
Code Snippets: by Code Snippets Pro – 2.14.3
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.2.2
Custom Post Type UI: by WebDevStudios – 1.10.2
FileBird Lite: by Ninja Team – 4.9.8
GamiPress - WooCommerce Points Gateway: by GamiPress – 1.1.3
GamiPress - WooCommerce integration: by GamiPress – 1.3.6
GamiPress: by GamiPress – 2.3.0
Gravity Forms Quiz Add-On: by Gravity Forms – 3.8
Gravity Forms Survey Add-On: by Gravity Forms – 3.7
Heartbeat Control by WP Rocket: by WP Rocket – 2.0
LifterLMS Gravity Forms: by LifterLMS – 2.1.2
LifterLMS WooCommerce: by Team LifterLMS – 2.2.1
LifterLMS Stripe Payment Gateway: by LifterLMS – 5.4.0
LifterLMS: by LifterLMS – 5.10.0
Payment Gateways per Products for WooCommerce: by WPWhale – 1.6.4
Redirection: by John Godley – 5.2.3
Tangible Tweaks for Gamipress: by Team Tangible – 0.0.1
WooCommerce Stripe Gateway: by WooCommerce – 6.2.0
WooCommerce Memberships: by SkyVerge – 1.22.11
WooCommerce Subscriptions: by WooCommerce – 4.0.2
WooCommerce: by Automattic – 6.2.1
WooPack for Beaver Builder: by Team IdeaBox - Beaver Addons – 1.4.5
Yoast SEO: by Team Yoast – 18.2
YayMail - WooCommerce Email Customizer: by YayCommerce – 2.8.3

### Dropin Plugins (1) ###

db-error.php: db-error.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: course (course)
courseenroll (courseenroll)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #370 - /shop/
Cart: #371 - /cart/
Checkout: #372 - /checkout/
My account: ❌ Page does not contain the [woocommerce_my_account] shortcode.
Terms and conditions: #996 - /terms-of-use/

### Theme ###

Name: Astra
Version: 3.7.7
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Memberships ###

Restriction mode:: Hide content only
Public content:: Pages: 1 item
Excluded from discounts:: –
Membership plans:: 4
Membership Access:: Members: 25Access method: User account registrationAccess length: Unlimited Subscription: No
Unlimited Lifetime Membership:: Members: 32Access method: Product(s) purchaseAccess length: Unlimited Subscription: OptionalInstallment plan: Optional
Essential Membership Plan:: Members: 9Access method: Product(s) purchaseAccess length: Unlimited Subscription: YesInstallment plan: No
Basic Membership Plan:: Members: 13Access method: Product(s) purchaseAccess length: Unlimited Subscription: YesInstallment plan: No

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ❌ Staging
Subscriptions Live URL: https://brio.flywheelsites.com
Subscription Statuses: trash: 1
wc-active: 27
wc-on-hold: 2
wc-cancelled: 7

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Georgia

### Subscriptions by Payment Gateway ###

Stripe: trash: 1
wc-active: 21
wc-cancelled: 6
wc-on-hold: 2

### Payment Gateway Support ###

Credits: products
refunds

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

### Action Scheduler ###

Complete: 348
Oldest: 2021-12-20 20:09:49 -0500
Newest: 2022-01-18 15:56:21 -0500

Pending: 646
Oldest: -0001-11-29 19:03:58 -0456
Newest: 2023-02-20 19:51:55 -0500

Failed: 1
Oldest: –
Newest: –

Canceled: 567
Oldest: -0001-11-29 19:03:58 -0456
Newest: -0001-11-29 19:03:58 -0456

### Status report information ###

Generated at: 2022-03-02 00:49:51 -05:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment] 2022-03-09 21:05
Hello @cnicpon, 

Thanks for taking your time for reporting it.

This is the expected behavior for [Select2](https://select2.org/), since it provides contextual search and not only a exactly match, making better for accessibility as well. I understand that you may not like how it behaves, but it's possible to customize it using JavaScript or removing it completely using this PHP snippet:

```php
add_action(
    'wp_enqueue_scripts',
    function() {
        if ( function_exists( 'is_checkout' ) && is_checkout() ) {
            wp_dequeue_style( 'select2' );
            wp_dequeue_script( 'selectWoo');
        }
    }
);
```

I'll leave this ticket open for a further triage of the core team since I think is a nice idea to make the Country and State codes searchable as well.

--- 

Note for Proton:

Select2 use contextual search and that's why makes a few more matches, and it's possible to customize or disable almost all behaviors in Select2 or to complete remove from checkout using a PHP snippet.

But could be nice to also make all Country and State codes searchable as well, of course it could cause to show more results to show up because the contextual search will bring those codes while search only with two letters.

**Comment by mikejolley** [comment] 2023-10-25 11:00
I tested this against the new experience in cart and checkout blocks (since this is our focus now) and noted the following.

_If you type F expecting to get Florida, you actually get California._ 

![Screenshot 2023-10-25 at 11 56 47](https://github.com/woocommerce/woocommerce/assets/90977/9b9abcde-2bbc-4127-8331-6843b776cc29)

Fixed, Florida is top result.

_Or if you type W expecting to get West Virginia, you get Delaware._

![Screenshot 2023-10-25 at 11 57 45](https://github.com/woocommerce/woocommerce/assets/90977/f6b33329-3407-4c8c-bea0-03cc14e20aba)

Fixed, one of the top results.

_Further, if you type an abbreviation, that doesn't work either. if you type GA, you don't get Georgia._

This one does not match. Georgia does not contain "GA". This could only be solved by including "GA" in the text/state name. I think given that the list clearly contains state names rather than abbreviations, and given that "G" will bring up "Georgia" as the top result, this does not need addressing.

You can read more about the new blocks here: https://woocommerce.com/document/cart-checkout-blocks-support-status/

Thank you, marking this as closed.

**Closed as completed by mikejolley** 2023-10-25 11:00 UTC
Labels: Bug, Enhancement, Checkout, plugin: woocommerce, Rubik
