### ISSUE TITLE
Issues when creating a manual order in WooCommerce

### ISSUE THREAD

**Issue by weronikasiuda** [woothemes/woocommerce#31997] opened 2022-02-28 14:27 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When an order is created manually in WooCommerce, clicking Add Item => Add Shipping does not actually load set shipping rates. The dropdown menu offers a couple of options - Local Pickup, Table Rates (if enabled), etc but the cost is always set to 0 and needs to be calculated by site administrator.

### Expected behavior

When a flat rate is set to $8 (example), clicking "Flat rate" from dropdown menu should add $8 shipping cost to the order.

### Actual behavior

Shipping cost is always set to 0 and needs to be calculated by the admin.

### Steps to reproduce

1. Go to WooCommerce => Settings and add shipping rates.
2. WooCommerce => Add order
3. Add item => add shipping cost

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.rfwp.com
Site address (URL): https://www.rfwp.com
WC Version: 6.2.1
REST API Version: ✔ 6.2.1
WC Blocks Version: ✔ 6.7.3
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.1.0
Log Directory Writable: ✔
WP Version: ❌ 5.9 - There is a newer version of WordPress available (5.9.1)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.26
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.36-39-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.2.1
WC Database Prefix: wp_
Total Database Size: 86.72MB
Database Data Size: 59.26MB
Database Index Size: 27.46MB
wp_woocommerce_sessions: Data: 5.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.20MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 3.52MB + Index: 2.95MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.02MB + Index: 2.03MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.02MB + Index: 0.61MB + Engine InnoDB
wp_cgit_postman_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cgit_watchman_audits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cgit_watchman_audit_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cgit_watchman_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cgit_watchman_mutes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.23MB + Index: 0.30MB + Engine InnoDB
wp_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fbv_attachment_folder: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mclean_refs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mclean_scan: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 9.02MB + Index: 0.44MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.38MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.33MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 20.31MB + Index: 13.52MB + Engine InnoDB
wp_posts: Data: 6.06MB + Index: 0.78MB + Engine InnoDB
wp_rtg_attachments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 1.31MB + Index: 0.38MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 2.19MB + Index: 0.72MB + Engine InnoDB
wp_users: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.19MB + Index: 0.34MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.23MB + Index: 0.30MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.14MB + Index: 0.27MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 1.45MB + Index: 1.97MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcan_filter_sessions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Data: 2.52MB + Index: 1.25MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_yoast_prominent_words: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.14MB + Index: 0.09MB + Engine InnoDB

### Post Type Counts ###

attachment: 2139
book_author: 179
course_instructor: 21
event: 6
nav_menu_item: 93
page: 121
post: 94
product: 1074
revision: 628
shop_coupon: 1
shop_order: 293
shop_order_refund: 6
yith_wcan_preset: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (39) ###

ManageWP - Worker: by GoDaddy – 4.9.13
Query Monitor: by John Blackbourn – 3.8.2
Advanced Custom Fields PRO: by Delicious Brains – 5.11.4
CAPTCHA 4WP: by WP White Security – 7.0.4
Akismet Anti-Spam: by Automattic – 4.2.2
Campaign Monitor for WooCommerce: by Campaign Monitor – 1.4.8
Castlegate IT WP ACF Events: by Castlegate IT – 1.7.3
Castlegate IT WP ACF Unique ID: by Castlegate IT – 1.0.0
Castlegate IT WP Admin Notifications: by Castlegate – 1.0.2
Castlegate IT WP Breadcrumb: by Castlegate IT – 3.2.1
Castlegate IT WP Cookie Consent: by Castlegate IT – 2.3.2
Castlegate IT WP SEO Headings: by Castlegate IT – 1.0.0
Castlegate IT WP Site Manager: by Castlegate IT – 1.0.0
Castlegate IT WP Socialize: by Castlegate IT – 2.2.1
Castlegate IT WP Watchman: by Castlegate IT – 1.10.1
Classic Editor: by WordPress Contributors – 1.6.2
Cloudflare: by Cloudflare
Inc. – 4.7.0

DearPDF Pro: by DearHive – 1.1.75
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.4
Enable Media Replace: by ShortPixel – 3.6.3
FileBird: by Ninja Team – 4.9.9.1
MonsterInsights - eCommerce Addon: by MonsterInsights Team – 8.3.1
MonsterInsights Pro: by MonsterInsights – 8.3.4
Mailgun: by Mailgun – 1.7.9
Non-Purchasable WooCommerce Products: by Guy Primavera – 1.4
WooCommerce Dynamic Pricing: by Element Stark – 3.1.27
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.2.12
WooCommerce Stripe Gateway: by WooCommerce – 6.2.0
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.24
WooCommerce PDF Invoices & Packing Slips: by WP Overnight – 2.13.1
WooCommerce Product Bundles: by WooCommerce – 6.14.0
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.36
WooCommerce: by Automattic – 6.2.1
Yoast SEO Premium: by Team Yoast – 18.0
Yoast SEO: by Team Yoast – 18.2
WP 2FA - Two-factor authentication for WordPress: by WP White Security – 2.1.0
YITH WooCommerce Ajax Product Filter Premium: by YITH – 4.7.0
YITH WooCommerce Ajax Search Premium: by YITH – 1.15.0
YITH WooCommerce Wishlist Premium: by YITH – 3.6.0

### Inactive Plugins (1) ###

Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Must Use Plugins (7) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
ManageWP - Worker Loader: by GoDaddy – 1.0.0
WPE ElasticPress Autosuggest Logger: by WP Engine – 1.0.0
WP Engine Cache Plugin: by WP Engine – 1.0.5
WP Engine Seamless Login Plugin: by WP Engine – 1.5.5
WP Engine Security Auditor: by wpengine – 1.0.10
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)
bundle (bundle)
course (course)

Taxonomies: Product Visibility: exclude-from-search (exclude-from-search)
exclude-from-catalog (exclude-from-catalog)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #237 - /bookstore/
Cart: #4613 - /cart/
Checkout: #4614 - /checkout/
My account: #4615 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Royal Fireworks Press
Version: 1.0.0
Author URL: https://www.castlegateit.co.uk/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: cgit-rfwp-v2/woocommerce/archive-product.php
cgit-rfwp-v2/woocommerce/cart/cross-sells.php
cgit-rfwp-v2/woocommerce/content-single-product.php
cgit-rfwp-v2/woocommerce/emails/admin-cancelled-order.php
cgit-rfwp-v2/woocommerce/emails/customer-invoice.php
cgit-rfwp-v2/woocommerce/emails/customer-new-account.php
cgit-rfwp-v2/woocommerce/emails/customer-on-hold-order.php
cgit-rfwp-v2/woocommerce/emails/customer-processing-order.php
cgit-rfwp-v2/woocommerce/emails/customer-refunded-order.php
cgit-rfwp-v2/woocommerce/emails/customer-reset-password.php
cgit-rfwp-v2/woocommerce/global/breadcrumb.php
cgit-rfwp-v2/woocommerce/myaccount/form-login.php
cgit-rfwp-v2/woocommerce/myaccount/form-lost-password.php
cgit-rfwp-v2/woocommerce/myaccount/form-reset-password.php
cgit-rfwp-v2/woocommerce/single-product/add-to-cart/grouped.php
cgit-rfwp-v2/woocommerce/single-product/meta.php
cgit-rfwp-v2/woocommerce/single-product/price.php
cgit-rfwp-v2/woocommerce/single-product/product-image.php
cgit-rfwp-v2/woocommerce/single-product/product-thumbnails.php
cgit-rfwp-v2/woocommerce/single-product/rating.php
cgit-rfwp-v2/woocommerce/single-product/related.php
cgit-rfwp-v2/woocommerce/single-product/sale-flash.php
cgit-rfwp-v2/woocommerce/single-product/share.php
cgit-rfwp-v2/woocommerce/single-product/short-description.php
cgit-rfwp-v2/woocommerce/single-product/tabs/tabs.php
cgit-rfwp-v2/woocommerce/single-product/title.php
cgit-rfwp-v2/woocommerce/single-product/up-sells.php
cgit-rfwp-v2/woocommerce/single-product.php

### Product Bundles ###

Database Version: 6.14.0
Loopback Test: ✔
Template Overrides: cgit-rfwp-v2/woocommerce/single-product/add-to-cart/bundle.php
cgit-rfwp-v2/woocommerce/single-product/bundled-item-image.php

### Action Scheduler ###

Complete: 3,939
Oldest: 2022-01-28 14:33:38 +0000
Newest: 2022-02-28 13:58:51 +0000

### Status report information ###

Generated at: 2022-02-28 09:26:22 -05:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment] 2022-03-08 22:43
@weronikasiuda Hello, thanks for reporting it.

By default is only possible to calculate shipping automatically in the cart and checkout pages only, not possible to calculate in the admin pages.

I'm closing since this is the expected behavior for orders in the admin. If you like you can [open a feature request](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=type%3A+enhancement%2Cstatus%3A+awaiting+triage&template=2-enhancement.yml&title=%5BEnhancement%5D%3A+) to include this feature in future release.
Thanks

**Closed as completed by claudiosanches** 2022-03-08 22:43 UTC
Labels: Bug, Order Management, Shipping
