### ISSUE TITLE
HPOS - Refund amount is missing in Woo API order refunds response payload and in data received via Webhooks if HPOS is enabled

### ISSUE THREAD

**Issue by m-mikelkevicius** [woothemes/woocommerce#39215] opened 2023-07-13 11:27 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The following info is missing in the response payload from Woo API GET `wp-json/wc/v3 /orders/<orderid>refund` if an order is refunded while HPOS is enabled: 
"amount": "0.00",
"refunded_by": 0,

The same scenario goes for data received via Webhooks.

If HPOS is disabled, everything works - values come correct and on time.

### Expected behavior

Refunds response values  when **HPOS enabled** via woo API GET `wp-json/wc/v3 /orders/<orderid>refund`
 
 "amount": "40.50", (expected amount while according to goods price on test shop)
  "refunded_by": 1,

### Actual behavior

Refunds response values  when **HPOS disabled** via woo API GET `wp-json/wc/v3 /orders/<orderid>refund`

"amount": "0.00",
"refunded_by": 0,

### Steps to reproduce

1. Create completed order;
2. Refund order;
3. Get refund data via Woo API GET `wp-json/wc/v3 /orders/<orderid>refund`
4. "amount" is 0.00
5. "refunded_by" is 0

### WordPress Environment

[SystemStatusReport_woo-e2e-test.omni-woo-test.com_2023-07-13T11-26-58.txt](https://github.com/woocommerce/woocommerce/files/12038819/SystemStatusReport_woo-e2e-test.omni-woo-test.com_2023-07-13T11-26-58.txt)

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment] 2023-07-19 22:00
@m-mikelkevicius I can only partially reproduce this. If I do a partial or refund on an order while HPOS is enabled, I see the same `refunded_by` value that you do, `0` (i.e. no user ID is present). However, I am seeing the correct value for `amount`. If I switch the data storage setting to "WordPress post tables", I still see the correct `amount` and now `refunded_by` is showing the correct user ID.

Can you provide a bit more detail about your settings/environment where you're seeing an empty `amount` as well?

**Comment by m-mikelkevicius** [comment] 2023-07-21 13:55
Hi @coreymckrill , I have tried to reproduce once again on another shop, where no additional plugins are activated, and I could reproduce it:
After placing order I have refunded it while HPOS is enabled, and while not. After that, if I try to get refund data via woo API  wp-json/wc/v3/orders/<order_id>/refunds  just after I refunded it I get the different payload as you see below:

With HPOS
{
        "id": 1441,
        "date_created": "2023-07-21T13:40:09",
        "date_created_gmt": "2023-07-21T13:40:09",
        **"amount": "0.00",**
        "reason": "",
        **"refunded_by": 0,**
        "refunded_payment": false,....

Without HPOS:
{
        "id": 1443,
        "date_created": "2023-07-21T13:45:05",
        "date_created_gmt": "2023-07-21T13:45:05",
        **"amount": "55.00",**
        "reason": "",
        **"refunded_by": 1,**
        "refunded_payment": false,

If I try to get data for refunded order with HPOS after a few minutes the data then appears usually, but not always.

The main issue for us is that webhooks send data without mentioned properties because with HPOS there is this delay introduced.

**Comment by coreymckrill** [comment] 2023-07-27 20:18
I think this was partially fixed by #39219, which is not yet in a public release. That would explain why the `amount` field was missing data when testing in WC 7.8.2, but I was seeing correct data for it when I tested in trunk. However, the `refunded_by` field is still not working correctly. I've outlined the cause of that in #39444.

**Closed as completed** 2023-08-17 23:35 UTC
Labels: Bug, Order Management, type: community contribution
