### ISSUE TITLE
[Enhancement]: quantity plus minus button

### ISSUE THREAD

**Issue by CIPURTA** [woothemes/woocommerce#50919] opened 2024-08-23 12:35 UTC
### Describe the solution you'd like

quantity plus minus button in the product sheet, which are really unsightly, I know there are several plugins, but it should be a native thing of woommerce, putting it there properly is a very important thing that has been like this for years and no longer reflects the modern requirements of e-commerce sites, most people do not know the code, that's why you should fix it a little better, maybe put them more visible, a layout a little more modern and intuitive

### Describe alternatives you've considered

it is necessary to make it easier to insert the quantity of the product, make it a little more visible by default, it is very difficult to customize it with page builders,

**Comment by CIPURTA** [comment] 2024-08-23 12:45
it is obviously while you change quantity the price should already change

**Comment by jonathansadowski** [comment] 2024-08-23 18:12
Hi @CIPURTA,

Thanks for sharing your enhancement request. Would you mind sharing some more details? You mentioned an existing plugin that accomplishes what you want, perhaps could you either include the name of the plugin, or a screenshot that demonstrates your enhancement?

**Comment by CIPURTA** [comment] 2024-08-26 10:52
![Screenshot_20240824_061958_Chrome](https://github.com/user-attachments/assets/39da5488-2163-4184-98c8-0c4898dcab8d)
Quantity Plus Minus Button for WooCommerce by CodeAstrology

**Comment by mikejolley** [comment] 2024-08-27 14:00
This issue seems to be referring to products which use native number inputs:

![Screenshot 2024-08-27 at 14 59 06](https://github.com/user-attachments/assets/84c0b57b-b7b9-45eb-b45f-dba7d55941c6)

Cart and checkout blocks implement this style:

![Screenshot 2024-08-27 at 14 59 28](https://github.com/user-attachments/assets/6e53a5de-46a8-49e2-b161-23d4669e3c5d)

Perhaps they need unifying?

**Comment by CIPURTA** [comment] 2024-08-28 05:14
yes it would be perfect!!!! 😊

**Comment by Aljullu** [comment] 2024-09-02 15:14
Thanks for opening this issue, @CIPURTA! I'm going to close this issue as a duplicate of https://github.com/woocommerce/woocommerce/issues/42299, as I think they both refer to the same and https://github.com/woocommerce/woocommerce/issues/42299 received some activity, already. This way we can consolidate the discussion in one single place.

Please let me know if you think they are two different issues.

**Closed as not planned by Aljullu** 2024-09-02 15:14 UTC
Labels: Enhancement, Store Frontend, Product/Inventory Management, type: community contribution, Kirigami

**Comment by CIPURTA** [comment] 2024-09-03 08:50
Yes, I agree
