### ISSUE TITLE
"Thanks!" button after a database upgrade throws a JavaScript error and won't dismiss

### ISSUE THREAD

**Issue by zhongruige** [woothemes/woocommerce#32241] opened 2021-08-13 16:54 UTC
### Describe the bug

WooCommerce database update as done (after clicking "Thanks!") on the latest version. It throws an Uncaught (in promise) error.

### To Reproduce

* Create a site with a version of WooCommerce that will trigger a DB migration (I used 5.5) that is enabled and active
* Upload the latest 5.6 zip (RC-2 in this case)
* Run the Database update and wait for it to complete
* Refresh the page so the notice is updated to the done message and the `Thanks` button is available
* Click "Thanks!" and notice that nothing happens and it logs the error noted above into the console

### Actual behavior:

The database upgrade message can't be removed.

### Expected behavior

The database upgrade message can be acknowledged and removed.

### Desktop (please complete the following information):

* OS: macOS
* Browser Firefox
* Version 91.0

**Comment by moon0326** [comment] 2021-08-13 20:55
Thank you @zhongruige for taking the time to report the bug. 

Unfortunately, I wasn't able to reproduce it with a fresh installation of WooCommerce. 

This is my screencast: https://d.pr/v/WYYT8a

I think there must be a particular condition to prevent the banner from disappearing. I'll look into it further.

**Comment by octaedro** [comment] 2021-08-26 15:34
It seems like this is an [old issue](https://github.com/woocommerce/woocommerce-admin/issues/7264) that hasn't been solved. [This issue](https://github.com/woocommerce/woocommerce-admin/issues/7561), created recently, gathers more information about the context where the bug is happening.

**Comment by solstudioim** [comment] 2021-08-31 06:41
I have a user reporting the same issue in 30906156-HC, screenshot: https://d.pr/i/ss17a8

**Comment by acicovic** [comment] 2021-09-07 08:59
I also have this issue on a client site. Clicking on the button generates an error in the console.

**Comment by sparky672** [comment] 2021-09-16 21:03
Same here... actually have had this issue for a very long time, perhaps a year or more.  Up to 5.8.1 and surprised to see it's still a lingering problem.  Such a simple thing that needs to be bullet-proofed.   

I shouldn't have to make manual edits to the database to hide this nag every time.  One of the plugin developers over on the WordPress forum stated that if you don't click the button within 24 hours, then the nag persists forever.  Seriously?  He knows the cause and you can't fix this?

Not a big confidence booster when these simple things go on month after month until more than a year has passed... FWIW, I am a paying customer of WC products.

**Comment by richsadams** [comment] 2021-09-16 21:22
Agreed, should be fixed by now. This issue is posted on numerous sites and numerous threads. It's a well-known bug. 

The nag persisted even if I updated within a few hours. I've been having to manually correct it for far too long.

**Comment by sparky672** [comment] 2021-09-16 21:25
And there are so many open and closed bug reports on this I don't even know where I am supposed to post.

**Comment by jacoswan** [comment] 2021-09-27 12:44
Another instance of this (not being able to dismiss the thanks) [reported here](https://wordpress.org/support/topic/database-update-is-completed-notice-keeps-reappearing-2/).

**Comment by bozzmedia** [comment] 2021-09-28 01:05
Just encountered this persistent issue on recent upgrade to WC . Possibly related console error:

> 
> Uncaught (in promise) Error: 
>     qr https://www.redacted.com/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/data/index.js?ver=2.6.5:2
>     Redux 31

**Comment by s-binder** [comment] 2021-10-09 10:01
I have the same error as @bozzmedia. A workaround is to disable the plugin gutenberg. Now you can accept the message without an error. 
**Edit: no, the message appears afterwards again. So, no workaround.**

**Comment by sparky672** [comment] 2021-10-09 13:29
> I have the same error as @bozzmedia. A workaround is to disable the plugin gutenberg. Now you can accept the message without an error.
> **Edit: no, the message appears afterwards again. So, no workaround.**

I don’t even have that plug-in so that’s not it.

**Comment by AashikP** [comment] 2021-10-27 08:20
Another report in 4406802-zen

**Comment by louwie17** [comment] 2021-12-01 15:30
I just tried again and couldn't reproduce it, it does seem like the error lies with our call to `triggerNoteAction`.
If someone does get this again, please have a look at the note action request in the network panel and see if it returns a 404 and if it shows any errors.
The request would look something like this: `/wc-analytics/admin/notes/<note_id>/action/<action_id>`

**Comment by bozzmedia** [comment] 2021-12-04 01:09
Just tried it again now, this console error pops up on click:

> Uncaught (in promise) Error: 
>     Rn https://redacted.com/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/data/index.js?ver=2.8.0:2
>     Redux 31
>     A https://redacted.com/wp-includes/js/dist/data.min.js?ver=a9e98fe3ad76884fe7909ba8348395b7:2
>     L https://redacted.com/wp-includes/js/dist/data.min.js?ver=a9e98fe3ad76884fe7909ba8348395b7:2
>     f https://redacted.com/wp-includes/js/dist/data.min.js?ver=a9e98fe3ad76884fe7909ba8348395b7:2
>     Ne https://redacted.com/wp-includes/js/dist/data.min.js?ver=a9e98fe3ad76884fe7909ba8348395b7:2
>     onClick https://redacted.com/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/chunks/store-alerts.js?ver=2.8.0:1
>     ki https://redacted.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:176
>     ji https://redacted.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:13
>     mi https://redacted.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:13
>     lf https://redacted.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:13
>     wi https://redacted.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:187
>     Kd https://redacted.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:32
>     pc https://redacted.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:32
>     Wf https://redacted.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:34
>     <anonymous> https://redacted.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236
>     uf https://redacted.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:15
>     Qd https://redacted.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:42
>     sc https://redacted.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
>     unstable_runWithPriority https://redacted.com/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25
>     Da https://redacted.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
>     <anonymous> https://redacted.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:236
>     Ei https://redacted.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:41
> index.js:2:53305
> 

No 404's present in the Network panel.

**Comment by becdetat** [comment] 2022-02-15 06:33
Hi @jacob-sewell , I see you've assigned yourself to this ticket. Are you still working on it?

**Comment by jacob-sewell** [comment] 2022-02-15 18:26
> Hi @jacob-sewell , I see you've assigned yourself to this ticket. Are you still working on it?

I am, @becdetat, though I have intentionally let it fallow for a bit, and probably shouldn't have left it in the In Progress pipeline for the past week.

**Comment by becdetat** [comment] 2022-02-16 02:45
That's ok :-) sometimes it's ok to have something on the backburner. I just occasionally check on the status of various tickets so I know how we're travelling overall.

**Comment by jacob-sewell** [comment] 2022-02-27 17:29
I'm taking myself off of this because I haven't been able to reproduce the original issue and my fallback plan, which was to provide some kind of fallback that would make the upgrade complete note expire after some amount of time, would need to be implemented in the [woocommerce repository](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php).

This issue might be easier to tackle after the repository merge.

**Comment by thelogicwizards** [comment] 2022-06-07 22:10
5277736-zen is affected by this issue, also.

**Comment by gotyou** [comment] 2022-06-14 15:43
Same issue as above, with the thanks button.  In addition, none of the layered nav filters work unless i go into each product and then resave the product.  the Attributes filter then seems to be fine, but still getting persistent thanks messages

Thanks


Mark

**Comment by ilyasfoo** [comment] 2022-06-16 07:09
Hi, @gotyou!

I've tested upgrading to WooCommerce 6.6.0 from WooCommerce 6.0.1 and the "Thanks" message disappeared after the first time I clicked on it.

May I know when you click on the button, did any error pop out anywhere? There are generally two places you can look for errors:
1. In the browser's console if it's a JavaScript error
2. In `wp-content/debug.log` if it's a PHP error, but you may need to [turn on debugging](https://wordpress.org/support/article/debugging-in-wordpress/).

I'm suspecting it could be a PHP error. If there are any, would you mind sharing those errors here (but please remove any sensitive information)? That would be a lot of help.

Thanks!

**Comment by chihsuan** [comment] 2024-09-06 06:59
Closing this issue as it I couldn't to reproduce the issue with latest woocommerce. Free free to reopen if anyone else is still facing the issue.

**Closed as completed by chihsuan** 2024-09-06 06:59 UTC
Labels: Bug, plugin: woocommerce, Wayfinding
