### ISSUE TITLE
Programmatically deleting a product does not remove the product from wp_wc_product_meta_lookup

### ISSUE THREAD

**Issue by codecraftscraic** [woothemes/woocommerce#32560] opened 2022-04-11 13:53 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When trying to remove a test product programmatically with the provided woo functions the test product was not removed from `wp_wc_product_meta_lookup` when using the provided functions like so. 

```
$data_store = WC_Data_Store::load( 'product' );
$data_store->delete( $product, [ 'force_delete' => true ] );
```

We did some digging to figure out why it wasn't even returning the primary key for the meta lookup table, and in `vendor/wpackagist-plugin/woocommerce/includes/data-stores/class-wc-data-store-wp.php` line 584 `get_primary_key_for_lookup_table` returns an empty string without performing any action to try and return the primary key.

```
/**
* Get primary key name for lookup table.
*
* @since 3.6.0
* @param string $table Lookup table name.
* @return string
*/
protected function get_primary_key_for_lookup_table( $table ) {
    return '';
}
```

### Expected behavior

When deleting a product, all of the related product data should be removed as well.

### Actual behavior

Product is deleted from `wp_posts` but not from `wp_wc_product_meta_lookup`.

### Steps to reproduce

Programmatically create a product.

```
$product = new WC_Product();
$product->set_status( 'publish' );
$product->set_name( 'Testing Product' );
$product->set_short_description( 'An example product.' );
$product->set_description( 'This is a placeholder product.' );
$product->set_regular_price( '1.00' );
$product->set_price( '1.00' );
$product->set_stock_status( 'instock' );
$product->set_stock_quantity( 5 );
$product->set_catalog_visibility( 'hidden' );

$product_id = $product->save();

$this->getOption()->set( 'product_id', $product_id )->save();

return $product;
```

Note that product has been created and placed in both `wp_posts` and `wp_wc_product_meta_lookup`. Attempt to programmatically delete the product.

```
$data_store = WC_Data_Store::load( 'product' );
$data_store->delete( $product, [ 'force_delete' => true ] );
```

See that the product is removed from `wp_posts` but _not_ `wp_wc_product_meta_lookup`.

### WordPress Environment

Not sure this will actually be relevant since the issue is within the code and how it returns programmatically.

`
### WordPress Environment ###

WordPress address (URL): http://one.wordpress.test
Site address (URL): http://one.wordpress.test
WC Version: 6.3.1
REST API Version: ✔ 6.3.1
WC Blocks Version: ✔ 6.9.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.2.1
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.21.6
PHP Version: 7.4.27
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.13-MariaDB-1:10.5.13+maria~focal
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.3.1
WC Database Prefix: wp_
Total Database Size: 12.26MB
Database Data Size: 9.40MB
Database Index Size: 2.86MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpstg0_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpstg0_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_options: Data: 5.47MB + Index: 0.03MB + Engine InnoDB
wpstg0_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg0_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpstg0_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg0_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpstg0_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg0_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg0_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.03MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 1
product: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

WooCommerce: by Automattic – 6.3.1
WP STAGING: by WP-STAGING – 2.9.8

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.2.2
Disable Cart Fragments: by Optimocha – 2.0
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

fatal-error-handler.php: fatal-error-handler.php

### Must Use Plugins (3) ###

Jenny Test Plugin: by Jenny R. –
Nexcess Managed Apps (Development): by Nexcess –
WP STAGING Optimizer: by René Hermenau – 1.5.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Two
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 97
Oldest: 2022-03-11 18:39:58 +0000
Newest: 2022-04-11 13:50:44 +0000

Pending: 1
Oldest: 2022-04-11 13:50:56 +0000
Newest: 2022-04-11 13:50:56 +0000

### Status report information ###

Generated at: 2022-04-11 13:51:26 +00:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by jorgeatorres** [comment] 2022-08-08 18:29
Hi @codecraftscraic,

Thanks for reaching out and for such great description of the issue.
We tried running the code you shared but couldn't reproduce the problem. Data from the meta lookup was correctly removed as soon as the product was.

While you're correct that the default implementation of `get_primary_key_for_lookup_table()` returns an empty string, the specific instance of the product data store that gets invoked when a product is deleted refers to the correct column. See https://github.com/woocommerce/woocommerce/blob/fbb6bd1c53a7676b308b79a9051d475dd0e64c4c/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php#L2105-L2110.

The code that deals with removal of all product-related data [has a check](https://github.com/woocommerce/woocommerce/blob/fbb6bd1c53a7676b308b79a9051d475dd0e64c4c/plugins/woocommerce/includes/class-wc-post-data.php#L305) that makes sure the user doing the removal has the "delete_posts" permission. Could it be that you're running the code as a user without the required permissions? If so, you'd have other problems too with product-related data (such as variations, etc.). This was the only way we found to reproduce the issue.

Given we were not able to replicate, I'm closing the issue, but feel free to re-open if the above didn't help or I missed something.

**Closed as completed by jorgeatorres** 2022-08-08 18:29 UTC
Labels: Bug, status: can't reproduce, Data Structure/CRUD/Backend Processing, plugin: woocommerce
