### ISSUE TITLE
Quantity increase & decrease buttons

### ISSUE THREAD

**Issue by bukawebagency** [woothemes/woocommerce#39402] opened 2023-07-25 10:41 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I have two issues with product increase/decrease buttons,

**Firstly,** There is no max limit warning displayed on the quantity area.

Product page image: https://prnt.sc/mVGNIDQzeMRn

Related Product,

https://p02ybvjswy-staging.onrocket.site/product/premium-locking-ottoman-bed-lift-up-mechanism/

**Secondly**, 

If the product only has 1 limit. There is not quantity option on the related product page.

Product page image: https://prnt.sc/KeHW5TNeR2ZQ

Related Product,

https://p02ybvjswy-staging.onrocket.site/product/stabilus-audi-tt-tailgate-struts-855879/

### Expected behavior

All products should show quantity area (for increase/decrease) and if the visitor on the max limit of product quantity, there should be a display warning.

### Actual behavior

There is no warning display (when you try one more add quantity while already max limit of product quantity),

And no quantity area at the product if which has 1 limit

### Steps to reproduce

Go to the product page.
Increase product quantity as max. (put first 9999 and check max quantity)
And try one more quantity - On this step you should be able to see the issue display about there is no more limit.

But there is no displaying any warning.

example product

-----

Go to the product page (which stock has only 1)
You'll see there is not increase-descrease buttons.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://p02ybvjswy-staging.onrocket.site
Site address (URL): https://p02ybvjswy-staging.onrocket.site
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 100 MB
PHP Time Limit: 600
PHP Max Input Vars: 100000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 8.0.34
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: wp_
Total Database Size: 1521.39MB
Database Data Size: 1048.10MB
Database Index Size: 473.29MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 7.52MB + Index: 2.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 67.61MB + Index: 48.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.17MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 31.56MB + Index: 30.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 21.56MB + Index: 18.06MB + Engine InnoDB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_aws_index: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_ca_cart_abandonment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 1.52MB + Index: 0.61MB + Engine InnoDB
wp_comments: Data: 41.58MB + Index: 33.09MB + Engine InnoDB
wp_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_duplicator_pro_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.11MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.20MB + Index: 0.09MB + Engine InnoDB
wp_et_bloom_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ewwwio_images: Data: 1.52MB + Index: 0.59MB + Engine InnoDB
wp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_formmaker: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_formmaker_backup: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_formmaker_blocked: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_formmaker_query: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_formmaker_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_formmaker_submits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_formmaker_themes: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_formmaker_views: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_frmt_form_entry: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_frmt_form_entry_meta: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
wp_frmt_form_views: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_jet_post_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_taxonomies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_field_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_object_meta: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_upgrades: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 11.50MB + Index: 1.20MB + Engine InnoDB
wp_postmeta: Data: 280.83MB + Index: 273.80MB + Engine InnoDB
wp_posts: Data: 41.56MB + Index: 13.06MB + Engine InnoDB
wp_ps_exclude: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ps_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ps_posts: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_ps_product_sku: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sip_aenwc_email_chain: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sip_aenwc_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smartgoogleadwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_smuzform_entry: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smuzform_entry_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_termmeta: Data: 0.13MB + Index: 0.17MB + Engine InnoDB
wp_terms: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_usermeta: Data: 13.52MB + Index: 16.03MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 0.61MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 4.52MB + Index: 4.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 5.52MB + Index: 8.06MB + Engine InnoDB
wp_wc_order_stats: Data: 5.52MB + Index: 5.55MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.45MB + Index: 0.75MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpf_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpf_meta_data: Data: 1.52MB + Index: 6.52MB + Engine InnoDB
wp_wpf_meta_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpf_meta_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpf_meta_values_bk: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpf_modules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpf_modules_type: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpf_usage_stat: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_entries: Data: 4.52MB + Index: 0.13MB + Engine InnoDB
wp_wpforms_entry_fields: Data: 3.52MB + Index: 1.33MB + Engine InnoDB
wp_wpforms_entry_meta: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_circles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_rectangles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 478.52MB + Index: 0.00MB + Engine InnoDB
wp_wpr_rocket_cache: Data: 1.52MB + Index: 1.31MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_xoo_wl_list: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_xoo_wl_list_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yith_wcan_filter_sessions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yith_wcps_shippings: Data: 0.42MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 4.52MB + Index: 1.08MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.41MB + Index: 0.66MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_yoast_prominent_words: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_seo_links: Data: 1.52MB + Index: 0.78MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpp_yoast_indexable: Data: 3.52MB + Index: 1.27MB + Engine InnoDB

### Post Type Counts ###

a_e_n_shop: 1
attachment: 9194
auto-listing: 1
custom_css: 11
customize_changeset: 1
cwginstocknotifier: 143
elementor_font: 1
elementor_library: 90
elementor_snippet: 6
et_body_layout: 2
et_pb_layout: 11
et_template: 3
et_theme_builder: 1
feedback: 52
fmemailverification: 1
forminator_forms: 1
jet-engine: 1
mobile: 1
mts_notification_bar: 1
nav_menu_item: 24
nf_sub: 541
page: 381
pf_contact: 4
post: 1
postman_sent_mail: 250
product: 3329
product_variation: 425
revision: 4463
shop_order: 40907
shop_order_refund: 1955
smuzform: 1
testimonial: 4
wp_global_styles: 1
wpcf7_contact_form: 1
wpcode: 3
wpforms: 2
yith_wcan_preset: 1
yith_wcps_type: 1
yith-wcet-etemplate: 1
ywar_reviews: 2
ywdpd_discount: 1
ywtm_tab: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.9.0

### Inactive Plugins (51) ###

Ajax Search Lite: by Ernest Marcinko – 4.11.2
Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Astra Bulk Edit: by Brainstorm Force – 1.2.6
Astra Customizer Reset: by Brainstorm Force – 1.0.6
Astra Pro: by Brainstorm Force – 4.1.2
Astra Widgets: by Brainstorm Force – 1.2.12
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: by codewoogeek – 4.0.0
Code Snippets: by Code Snippets Pro – 3.4.2
Contact Form 7: by Takayuki Miyoshi – 5.7.7
CTX Feed: by WebAppick – 5.4.32
Custom Adobe Fonts (Typekit): by Brainstorm Force – 1.0.18
Custom Fonts: by Brainstorm Force – 2.0.2
Customizer Search: by Brainstorm Force – 1.1.6
Custom Order Numbers for WooCommerce: by Tyche Softwares – 1.5.0
Elementor: by Elementor.com – 3.14.1
Elementor Header & Footer Builder: by Brainstorm Force
Nikhil Chavan – 1.6.14

Elementor Pro: by Elementor.com – 3.14.1
Extra Product Options & Add-Ons for WooCommerce: by ThemeComplete – 6.3.2
Get a Quote Button for WooCommerce: by wpbean – 1.3.0
GTM4WP: by Thomas Geiger – 1.16.2
Import / Export Customizer Settings: by Brainstorm Force – 1.0.7
JetEngine: by Crocoblock – 3.1.0
Pixel Manager for WooCommerce: by SweetCode – 1.32.5
Product Feed ELITE for WooCommerce: by AdTribes.io – 3.6.3
Product Filter by WBW: by WBW – 2.4.0
Qty Increment Buttons for WooCommerce: by taisho – 2.7.5
Redirection: by John Godley – 5.3.10
Related Products for WooCommerce: by WebToffee – 1.4.9
Sidebar Manager: by Brainstorm Force – 1.1.8
SIP Advanced Email Notifications for WC Free: by ShopitPress – 1.0.4
Termly | GDPR/CCPA Cookie Consent Banner: by Termly – 3.0.3
Ultimate Addons for Elementor: by Brainstorm Force – 1.36.17
Use Google Libraries: by Jason Penney – 1.6.2.3
User Menus: by Code Atlantic – 1.3.2
WooCommerce Blocks: by Automattic – 10.7.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.8.3
WooCommerce PayPal Payments: by WooCommerce – 2.2.0
WooCommerce Stripe Gateway: by WooCommerce – 7.4.1
WooCommerce Vehicle Parts Finder - Make/Model/Year/Engine/Category/Keyword: by The WP Instinct Team – 3.4
WPForms: by WPForms – 1.8.2.2
WPForms Lead Forms: by WPForms – 1.2.0
WP Mail Logging: by WP Mail Logging Team – 1.12.0
WP Mail SMTP: by WP Mail SMTP – 3.8.2
WP Rocket: by WP Media – 3.14.1
WP Rocket | Redirect HTTP to HTTPS: by WP Rocket Support Team –
XML Sitemap Generator for Google: by Auctollo – 4.1.11
YITH Product Shipping for WooCommerce Premium: by YITH – 1.0.37
YITH WooCommerce Ajax Product Filter Premium: by YITH – 4.0.2
YITH WooCommerce Bulk Product Editing Premium: by YITH – 1.2.31
Yoast SEO: by Team Yoast – 20.12
Yoast SEO Premium: by Team Yoast – 20.11

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (2) ###

CDN Cache Plugin: by  – 1.1.3
ET Support Center :: Must-Use Plugins Autoloader: by Elegant Themes –

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: ❌ Page not set
Basket: #97 - /cart/
Checkout: #98 - /checkout/
My account: #99 - /my-account/
Terms and conditions: #55222 - /terms-conditions/

### Theme ###

Name: Astra Child
Version: 1.0.0
Author URL: http://wpastra.com/about/
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 4.1.6
Parent Theme Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-25 14:49:45 +01:00
Options: ✔
Notes: 129
Onboarding: completed

### Action Scheduler ###

Complete: 68,170
Oldest: 2023-06-13 13:14:59 +0100
Newest: 2023-07-25 11:21:57 +0100

Failed: 18,035
Oldest: 2023-03-21 10:59:48 +0000
Newest: 2023-07-25 11:14:06 +0100

Pending: 3
Oldest: 2023-07-26 10:33:44 +0100
Newest: 2023-07-28 11:38:27 +0100

### Status report information ###

Generated at: 2023-07-25 11:31:41 +01:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by kshirodpatel** [comment] 2023-07-25 11:03
@bukawebagency I think it's a valid condition that woocommerce hides quantity when there is only a single item available. There is no sense to show quantity input in that case.

**Comment by nerrad** [comment] 2023-10-26 19:35
Hi @bukawebagency 

As @kshirodpatel noted, the expected behaviour in WooCommerce for a product configured to limit quantities of a product to 1 is to hide the quantity selector. This is working as expected.

I'm not sure what you are referring to with the first issue you mentioned because WooCommerce core does not ship with the ability to specific minimum and maximum values. You could be experiencing something specific to your theme (or possibly Elementor/Divi since I see you have those in use on your site as well).

I'm closing this issue because there is currently nothing actionable but if you have any more information that might help us understand the issue better it could be reopened if necessary.

**Closed as completed by nerrad** 2023-10-26 19:35 UTC
Labels: Bug, Enhancement, Cart, type: community contribution, Kirigami
