### ISSUE TITLE
[EPIC ]Tests: add e2e tests around the new product management form.

### ISSUE THREAD

**Issue by AnnaMag** [woothemes/woocommerce#36596] opened 2023-01-25 10:36 UTC
1. [ ] Turn on/off the new editing experience: 
       - activate via WooCommerce > Settings and confirm it is active on the Products > Add New tab
       - deactivate via "use the classic editor" menu option, and confirm the action.

2. [ ] Create a simple product
3. [ ] Product editing

**Comment by AnnaMag** [comment] 2023-01-25 10:41
The Epic is open for editing cc @mattsherman 

I believe we should aim to tackle the first tests in Cycle 32.

**Comment by mattsherman** [comment] 2023-01-25 16:11
Dropping this -- it is a duplicate of https://github.com/woocommerce/woocommerce/issues/36588, which was opened last night. 😄

I've added the enable/disable e2e test detail -- we didn't have that in #36588 yet.

**Closed as completed by mattsherman** 2023-01-25 16:11 UTC
Labels: Enhancement

**Comment by AnnaMag** [comment] 2023-01-25 18:09
Thanks @mattsherman! 

I "should have searched" first :)

**Comment by jonathansadowski** [comment] 2023-02-01 19:51
Moving this from `7.5` to `7.5.0` for the reasons discussed [here](https://github.com/woocommerce/woocommerce/issues/36330#issuecomment-1412632891).
