### ISSUE TITLE
Enable the delivery price calculator on the cart page not working with block cart page

### ISSUE THREAD

**Issue by larsdittinger** [woothemes/woocommerce#51110] opened 2024-09-03 11:25 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The "Enable the delivery price calculator" button on the WooCommerce cart page is not working when using the block cart page. Clicking the button does not hide or show the delivery price calculator as expected.

![cart](https://github.com/user-attachments/assets/aedb000a-d938-4f6d-9e8f-2623dc4c4023)
![settings](https://github.com/user-attachments/assets/4e00e9f4-5842-4f45-bb75-ca93d5108a26)

### Expected behavior

When clicking the button to enable or disable the delivery price calculator on the cart page, it should hide or display the calculator accordingly.

### Actual behavior

Clicking the button has no effect. The delivery price calculator remains visible or invisible, regardless of the button's state.

### Steps to reproduce

Go to the WooCommerce cart page using the block cart.
Click on the "Enable the delivery price calculator" button.
Scroll down to see that the delivery price calculator does not hide or show as expected.
No change is observed, indicating the button is not functioning.

### WordPress Environment

WordPress environment
--
WordPress address (URL): |   | https://ethia.dmtest.cz
Site address (URL): |   | https://ethia.dmtest.cz
WooCommerce version: |   | 9.2.3
WooCommerce Legacy REST API package: |   | The Legacy REST API plugin is not installed on this site.
Action Scheduler package: |   | 3.8.1 /var/www/virtual/ethia.dmtest.cz/www/public/wp-content/plugins/woocommerce/packages/action-scheduler
Log directory writable: |   | /var/www/virtual/ethia.dmtest.cz/www/public/wp-content/uploads/wc-logs/
WordPress version: |   | 6.6.1
WordPress multisite: |   | –
WordPress memory limit: |   | 512 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by senadir** [comment] 2024-09-03 12:08
Hey @larsdittinger, I'm not able to reproduce this on WooCommerce 9.3 and 9.2.3
Note that the calculator option should be enabled, the screenshot you shared shows it as disabled

<img width="1064" alt="image" src="https://github.com/user-attachments/assets/eadd9669-cbcb-4d8d-9725-7cc6ae6da9fa">

<img width="409" alt="image" src="https://github.com/user-attachments/assets/11b8e0db-ddeb-4a32-87dd-84b5dedb91f2">

<img width="397" alt="image" src="https://github.com/user-attachments/assets/873553ba-07e6-4bec-927d-071f12e3506e">

**Comment by larsdittinger** [comment] 2024-09-03 19:00
Thank you for your response and help. I'm trying to hide the shipping cost so that it isn't visible in the cart at all. This happens every time a user is logged in and has a saved delivery address from a previous order. None of the options in the settings will hide the cost calculation in the cart.

**Comment by mikejolley** [comment] 2024-09-16 11:42
The toggle option for shipping calculator disables the address form. New customers won't see options there because they have not provided an address.

Existing customers, or those who have already entered an address on checkout, will see the options there and this is required **because if the shipping section was hidden, the total at the bottom would be incorrect**.

If you want to just hide the checkboxes with the rates you can do that with custom CSS. But the total will still include the chosen shipping method cost.

I'm closing this because the shipping calculator toggle does function as intended.

**Closed as completed by mikejolley** 2024-09-16 11:42 UTC
Labels: Bug, Cart, needs: triage feedback, type: community contribution, Rubik, block: cart
