### ISSUE TITLE
Fix unnecessary JS script loading on the frontend related to Order Attribution Feature.

### ISSUE THREAD

**Issue by nerrad** [woothemes/woocommerce#43829] opened 2024-01-19 19:24 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

This [support forum thread](https://wordpress.org/support/topic/more-than-39-js-files-are-loaded-on-version-8-5-1/) reports the loading of an additional 39 scripts beginning with WooCommerce 8.5/.1. On initial review, it looks like it may have been introduced [via a dependency on the `wc-blocks-checkout` and `wp-data` scripts](https://github.com/woocommerce/woocommerce/blob/7f2fd37fad64c890a51293a49661d1d166309c32/plugins/woocommerce/src/Internal/Orders/OrderAttributionController.php#L231) in the new `wc-order-attribution` feature. If that is enqueued in every page load that is definitely, the source for the extra scripts and should be rectified.

### Expected behavior

WooCommerce should not be introducing a significant payload increase unnecessarily on every page load.

### Actual behavior

Significant payload increase is present.

### Steps to reproduce

Install and activate WooCommerce 8.5 or 8.5.1 with the Order Attribution feature active (it is active by default).

### WordPress Environment

Doesn't matter.

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by nerrad** [comment] 2024-01-19 19:37
In my testing, when I deactivate the Order Attribution feature, there are 3 less JS files loaded on the home page. This also aligns with how many scripts I see loaded on the frontend with WC 8.4.0 active (58 WC 8.4.0 and 58 with WC 8.5 and Order Attribution feature deactivate). It appears that some of the loaded scripts are lazy-loaded and non-blocking related to the mini-cart block. 

I haven't debugged much further than that (i.e. I would want to know if Order Attribution is changing _how_ the scripts are loaded since Mini-Cart and Order Attribution share some dependencies).

However, the important distinction is that if a store does _not_ utilize the Mini-Cart block, the script count increase would be significantly more between versions.

**Comment by lkraav** [comment] 2024-01-22 11:10
Duplicate of https://github.com/woocommerce/woocommerce/issues/43743 maybe?

**Comment by Aljullu** [comment] 2024-01-22 13:52
> Duplicate of https://github.com/woocommerce/woocommerce/issues/43743 maybe?

Yes, it seems to be the same or, at least, similar. Thanks for pointing it out, @lkraav! I just left a comment in that issue pointing to this one.

**Closed as completed** 2024-01-24 17:58 UTC
Labels: Bug, Order Management, Ventures, impact: high

**Comment by MKV-Rob** [comment] 2024-02-01 18:26
Sorry I am using this topic but this issue is not only with JS. The CSS in WC is currently chaotic as well - lot of same styles across multiple files.

**For example:**
WC loads "wc-blocks-style" but the same styles are in the "wc-blocks-packages-style".

**Then on Cart page:**
WC loads "wc-blocks-packages-style" but same styles are included in:
- "wc-blocks-style-cart"
- "wc-blocks-style-all-products"
- "wc-blocks-style-mini-cart"

**Etc.**

It's tiresome to customize/optimize...

**Comment by Aljullu** [comment] 2024-02-02 07:37
@MKV-Rob I would recommend opening a new issue for visibility, given that it is a different issue than what was reported here. Add ideally providing more details on which specific CSS rulesets are duplicate.

Having said that, it's expected that some styles will be repeated across stylesheets, the reason is that we intentionally made each block have its own stylesheet. This has the drawback that some styles might end up being repeated across stylesheets, but it provides the benefit that CSS files are much smaller than one single CSS file for all blocks. That's specially beneficial for sites or pages which use few WC Blocks (ie: a page where only the Mini-Cart block is displayed).

That doesn't mean there aren't places where it could be optimized further. But at the same time, there is no perfect solution because each approach has its own tradeoffs.

**Comment by loulemos** [comment] 2024-02-13 10:52
"However, the important distinction is that if a store does not utilize the Mini-Cart block, the script count increase would be significantly more between versions."

This needs a fix. It's making the woocommerce backend noticeably slower than the previous version, even with order attribution off—Which should've never been released and automatically activated without the consent of the shop owners, I'm putting out fires today because of this haphazard decision.

**Comment by nerrad** [comment] 2024-02-13 11:15
Hi @loulemos, this issue was fixed in #43857.  The issue you are describing with your backend being noticeably slower could be a different issue (appears like it might be related to #44345).
