### ISSUE TITLE
HPOS - "Screen Options" admin button missing in edit order page

### ISSUE THREAD

**Issue by fvcmedia** [woothemes/woocommerce#39877] opened 2023-08-24 07:14 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

After enabling HPOS as orders storage, the option to enable/disable widgets on the single order edit page is missing.
"Screen Options" shows fine on all orders page, but does not show up when editing a single order.

### Expected behavior

"Screen Options" button should show up on edit order page.

### Actual behavior

"Screen Options" is missing on single edit order page.

### Steps to reproduce

1. Enable HPOS
2. Go to a single order edit page
3. Notice "Screen Options" button is missing

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://staging.protect.com
Site address (URL): https://staging.protect.com
WC Version: 8.0.2
REST API Version: ✔ 8.0.2
WC Blocks Version: ✔ 10.6.5
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: da_DK
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.29
PHP Post Max Size: 225 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.3.38-MariaDB-0ubuntu0.20.04.1
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.2
WC Database Prefix: wp_
Total Database Size: 3403.06MB
Database Data Size: 2761.44MB
Database Index Size: 641.62MB
-----

### Post Type Counts ###

attachment: 7546
custom_css: 3
custom_order_status: 1
nav_menu_item: 322
nf_sub: 2241
oembed_cache: 115
page: 54
post: 74
product: 2729
product_variation: 30251
revision: 5490
shop_coupon: 221
shop_order: 22958
shop_order_refund: 2080
sizeguide: 2
tile_template: 1
vc_grid_item: 1
woovouchercodes: 167
woovouchers: 6
woovoupartredeem: 114
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

Advanced Access Manager: by Vasyl Martyniuk <vasyl@vasyltech.com> – 6.9.14
Advanced Cron Manager: by BracketSpace – 2.5.2
Advanced Custom Fields PRO: by WP Engine – 6.2.0
Bambora Online ePay: by Bambora Online – 5.5.0
Classic Editor: by WordPress Contributors – 1.6.3
Contact Form 7: by Takayuki Miyoshi – 5.8
Custom Order Status for WooCommerce: by Tyche Softwares – 2.3.0
Customizer Export/Import: by The Beaver Builder Team – 0.9.6
Disable Comments: by WPDeveloper – 2.4.4
DRF Portfolio Management: by Drfuri – 1.0.1
GTM4WP: by Thomas Geiger – 1.18.1
Dynamic Widgets: by Qurl – 1.5.16
Envato Market: by Envato – 2.0.10
WPBakery Page Builder: by Michael M - WPBakery.com – 6.6.0
Kirki Customizer Framework: by Themeum – 5.0.0
Maintenance Mode: by Lukas Juhas – 2.4.4
Loco Translate: by Tim Whitlock – 2.6.4
Meta Box: by MetaBox.io – 5.7.5
Shipmondo til WooCommerce: by Shipmondo – 4.2.0
Slider Revolution: by ThemePunch – 6.4.6
Sober Addons: by UIX Themes – 1.4.1
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.7.9
Unero WPBakery Page Builder Addons: by DrFuri – 1.1.8
Variation Swatches for WooCommerce: by AOVUP – 2.2.0
CTX Feed: by WebAppick – 5.4.33
WooCommerce Additional Variation Images: by WooCommerce – 2.3.2
WooCommerce Brands: by WooCommerce – 1.6.56
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.6.2
PDF Invoices & Packing Slips for WooCommerce - Professional: by WP Overnight – 2.14.4
WooCommerce Google Product Feed: by Ademti Software Ltd. – 10.10.5
WooCommerce: by Automattic – 8.0.2
Yoast SEO: by Team Yoast – 21.0
WP Mail SMTP: by WP Mail SMTP – 3.8.2
Smush Pro: by WPMU DEV – 3.14.2
WPMU DEV Dashboard: by WPMU DEV – 4.11.19
WP Overnight Sidekick: by WP Overnight – 2.5.1
YITH WooCommerce Wishlist: by YITH – 3.24.0

### Inactive Plugins (5) ###

Cloudflare: by Cloudflare
Inc. – 4.12.2

Facebook for WooCommerce: by Facebook – 3.0.32
Mailchimp for WooCommerce: by Mailchimp – 3.2
Query Monitor: by John Blackbourn – 3.13.1
W3 Total Cache: by BoldGrid – 2.4.1

### Must Use Plugins (1) ###

register-theme-directory.php: by  –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: DKK (kr.)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### WC Pages ###

Shop base: #5 - /webshop/
Cart: #6 - /kurv/
Checkout: #7 - /kasse/
My account: #8 - /min-profil/
Terms and conditions: #16380 - /handelsbetingelser/

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-25 05:23:00 +02:00
Options: ✔
Notes: 49
Onboarding: completed

### Action Scheduler ###

Complete: 10
Oldest: 2023-08-18 05:11:45 +0200
Newest: 2023-08-24 07:20:20 +0200

### Status report information ###

Generated at: 2023-08-24 09:08:33 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment] 2023-09-11 17:19
@fvcmedia This looks like it has been fixed in `trunk`. Are you still seeing this issue in the latest RC?

**Comment by shameemreza** [comment] 2023-09-13 15:33
Another report zd-6791895

**Comment by brownleather** [comment] 2023-09-20 04:22
On version 8.1.1, the screen options are present but do not seem to save.

**Comment by jorgeatorres** [comment] 2023-10-10 10:18
Duplicate of #34490.

**Closed as not planned by jorgeatorres** 2023-10-10 10:18 UTC
Labels: Bug, type: community contribution
