### ISSUE TITLE
Payments Welcome Screen needs updating

### ISSUE THREAD

**Issue by rogermattic** [woothemes/woocommerce#33602] opened 2022-06-24 17:35 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Current version of the Payments Welcome screen is missing elements and isn't aligned with the latest design. 

### Expected behavior

The design and elements should be updated as in the [design in Figma](https://www.figma.com/file/e428PXC0QyEwYqtX48lLq0/%5BWCPay%5D-Positioning-and-Conversion?node-id=12830%3A122180)

### Actual behavior

Wrong version comparing to the design
<img width="1250" alt="Screenshot 2022-06-24 at 18 31 05" src="https://user-images.githubusercontent.com/94967682/175949920-884fa8ae-2741-4588-bbd0-d9efe12491c7.png">

### Steps to reproduce

1. Onboard to WooCommerce from a WCPay eligible country **BUT** during onboarding opt out from installing WCPay
2. Go to the Payments Overview (from the main nav)

### WordPress Environment

WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by chihsuan** [comment] 2022-06-30 03:59
Possibly using the same components in #33598

**Comment by chihsuan** [comment] 2022-07-04 03:58
> 1. Onboard to WooCommerce from a WCPay eligible country BUT during onboarding opt out from installing WCPay
> 2. Go to the Payments Overview (from the main nav)

Hey @rogermattic I was not able to reproduce it with the given instructions. AFAIK, the payment welcome experiment has been disabled so the payment menu is not displayed. Do we still need to update it?

**Comment by ilyasfoo** [comment] 2022-07-05 05:38
Hi @rogermattic, similar to https://github.com/woocommerce/woocommerce/issues/33623, I believe the screenshot you're showing is a UI coming from the WCPay plugin. 

> Go to the Payments Overview (from the main nav)

This menu item should no longer be available since the experiment has ended, unless we're missing something. Do let us know if you can confirm that WCPay wasn't active and you still have that menu. Thanks!

**Comment by rogermattic** [comment] 2022-07-05 20:37
Hey @chihsuan @ilyasfoo, I just double-checked and the menu item doesn't show up indeed. The screenshot that I attached was taken around 2 weeks ago, so I guess the experiment was still running?

In this case we don't need that Payments item in the navigation -  that's correct

Do you know what's the result of the experiment? Is this possible to align the design of the Payments hero (on Set up Payments) with the design that was used in the experiment?

**Comment by ilyasfoo** [comment] 2022-07-06 02:53
> Do you know what's the result of the experiment?

@rogermattic Sure! This was the result paJDYF-1Yz-p2#comment-10831

>  Is this possible to align the design of the Payments hero (on Set up Payments) with the design that was used in the experiment?

I'm not sure I understand what you meant here, I believe the new design should be the one in the figma e428PXC0QyEwYqtX48lLq0-fi-12830%3A122180 correct? 

This was the experiment design:

![image](https://user-images.githubusercontent.com/3747241/177457962-3437d7c8-e764-4492-b50e-5364ce6d0bfb.png)

**Comment by rogermattic** [comment] 2022-07-07 13:48
Hey @ilyasfoo 

> This was the result paJDYF-1Yz-p2#comment-10831
Would you mind posting a full link (sorry, I'm not sure where this is supposed to go) 

> I'm not sure I understand what you meant here, I believe the new design should be the one in the figma e428PXC0QyEwYqtX48lLq0-fi-12830%3A122180 correct?
Please, can you post an actual link - when I tried pasting `e428PXC0QyEwYqtX48lLq0-fi-12830%3A122180` into figma URL, it didn't work. 

I don't recognise the view from the screenshot you attached, not sure what experiment that was.

The new design which I personally meant was this one that I included in the description: The design and elements should be updated as in the [design in Figma](https://www.figma.com/file/e428PXC0QyEwYqtX48lLq0/%5BWCPay%5D-Positioning-and-Conversion?node-id=12830%3A122180)

**Comment by ilyasfoo** [comment] 2022-07-08 11:27
@rogermattic The experiment I was referring to is pbxNRc-1cv-p2

Anyway, since the screen isn't handled by us, it's similar to the other issue https://github.com/woocommerce/woocommerce/issues/33623

**Comment by chihsuan** [comment] 2022-07-14 03:08
Closing this since this screen is not created by WooCommerce Core. More details in https://github.com/woocommerce/woocommerce/issues/33623

**Closed as completed by chihsuan** 2022-07-14 03:08 UTC
Labels: Bug, needs: author feedback, Payments, plugin: woocommerce
