### ISSUE TITLE
Frontend login broken when WP installed in a subdirectory

### ISSUE THREAD

**Issue by MarcGuay** [woothemes/woocommerce#43541] opened 2024-01-11 22:37 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When WordPress core is installed in a subdirectory, rather than the root, you can no longer login via the frontend (e.g. `woocommerce_my_account` shortcode form).  This bug appeared in 8.5.0 (tested with 8.4.0 and it's fine).  The problem seems to be related to the `LOGGED_IN_COOKIE`.  In 8.4.0 you get 2 cookies installed, one at `COOKIEPATH` (for me, '/') and one at `SITECOOKIEPATH` (for me, '/wp/').  However in 8.5.0 only the `SITECOOKIEPATH` cookie is installed and so you can log into the backend but not the frontend.

### Expected behavior

I expect to be logged in and shown the account page.

### Actual behavior

Login form is displayed

### Steps to reproduce

1. Install WordPress in a subdirectory (https://wordpress.org/documentation/article/giving-wordpress-its-own-directory/#method-ii-with-url-change)
2. Install and activate Woocommerce 8.5.0
3. Create a page with the `woocommerce_my_account` shortcode on it.
4. Try to login.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://cm.marcguay.ca/wp
Site address (URL): https://cm.marcguay.ca
WC Version: 8.5.0
REST API Version: ✔ 8.5.0
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Ubuntu)
PHP Version: 7.4.33
PHP Post Max Size: 32 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.42-0ubuntu0.18.04.1
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.0
WC Database Prefix: wp_
Total Database Size: 114.27MB
Database Data Size: 67.17MB
Database Index Size: 47.10MB
wp_woocommerce_sessions: Data: 0.16MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 4.52MB + Index: 4.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 4.52MB + Index: 3.80MB + Engine InnoDB
wp_ewwwio_images: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_ewwwio_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.14MB + Index: 0.08MB + Engine InnoDB
wp_postexpirator_debug: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 19.55MB + Index: 24.06MB + Engine InnoDB
wp_posts: Data: 18.52MB + Index: 2.39MB + Engine InnoDB
wp_ppfuture_actions_args: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 10.52MB + Index: 10.03MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 0.80MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_wc_order_stats: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBlockedIPLog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBlocks7: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfConfig: Data: 0.45MB + Index: 0.01MB + Engine MyISAM
wp_wfCrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfFileChanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfFileMods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfHits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfHoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfIssues: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_wfKnownFileList: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLiveTrafficHuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLocs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLogins: Data: 0.20MB + Index: 0.04MB + Engine MyISAM
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfNotifications: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wfPendingIssues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfStatus: Data: 0.09MB + Index: 0.03MB + Engine MyISAM
wp_wfTrafficRates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcaf_affiliates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcaf_clicks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yith_wcaf_commissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_yith_wcaf_commission_notes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcaf_payments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcaf_payment_commission: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yith_wcaf_payment_notes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcaf_rate_rulemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yith_wcaf_rate_rules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 7
acf-field-group: 1
amn_mi-lite: 3
attachment: 58
course: 58
nav_menu_item: 2
page: 7
post: 2
product: 57
revision: 667
shop_coupon: 6
shop_order: 6722
shop_order_refund: 154
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 8.5.0

### Inactive Plugins (23) ###

Advanced Custom Fields PRO: by WP Engine – 6.2.4
Autoptimize: by Frank Goossens (futtta) – 3.1.10
CDN Enabler: by KeyCDN – 2.0.6
ConvertKit for WooCommerce: by ConvertKit – 1.7.1
Custom Post Type UI: by WebDevStudios – 1.15.1
Email Templates: by wpexpertsio – 1.4.3
EWWW Image Optimizer: by Exactly WWW – 7.2.3
Export Users to CSV: by Matt Cromwell – 1.1.1
Facebook for WooCommerce: by Facebook – 3.1.9
GTM4WP: by Thomas Geiger – 1.19.1
LiteSpeed Cache: by LiteSpeed Technologies – 6.0.0.1
Order Export & Order Import for WooCommerce: by WebToffee – 2.4.6
Pay For Post with WooCommerce: by Pramadillo – 3.1.17
Post Duplicator: by Metaphor Creations – 2.32
PublishPress Future: by PublishPress – 3.1.7
User Role Editor: by Vladimir Garagulya – 4.64.1
WooCommerce - PayU Latam Gateway: by Code is everywhere - Jairo Ivan Rondon Mejia – 1.2.3
WooCommerce PayU Latam Payment Gateway: by PayU Latam – 2.0
WooCommerce PayU Latam Payment Gateway: by PayU Latam – 2.0
Wordfence Security: by Wordfence – 7.11.1
WP-SCSS: by Connect Think – 4.0.2
WP Migrate Lite: by WP Engine – 2.6.9
YITH WooCommerce Affiliates: by YITH – 3.2.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: COP ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: #6 - /pago/
My account: #7 - /
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /home/marc/webdev/cm/public_html/wp-content/plugins/woocommerce/templates/notices/error.php
/home/marc/webdev/cm/public_html/wp-content/plugins/woocommerce/templates/notices/notice.php
/home/marc/webdev/cm/public_html/wp-content/plugins/woocommerce/templates/notices/success.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-12 16:53:45 -05:00
Options: ✔
Notes: 159
Onboarding: completed

### Action Scheduler ###

Complete: 30
Oldest: 2023-12-14 22:12:55 +0000
Newest: 2024-01-11 21:13:58 +0000

Pending: 2
Oldest: 2024-01-11 22:37:44 +0000
Newest: 2024-01-12 21:13:58 +0000

Failed: 6
Oldest: 2023-02-27 15:43:45 +0000
Newest: 2023-06-07 13:44:58 +0000

### Status report information ###

Generated at: 2024-01-11 17:36:46 -05:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by codepuncher** [comment] 2024-01-12 07:12
This was fixed in https://github.com/woocommerce/woocommerce/pull/43504

**Comment by nerrad** [comment] 2024-01-12 18:58
Duplicate of #43463 and as noted by @codepuncher has been fixed in #43504 (which will be released with WC 8.5.1 coming [next week](https://developer.woo.com/2024/01/11/update-on-the-woocommerce-8-5-known-issue/).

**Closed as completed by nerrad** 2024-01-12 18:58 UTC
Labels: Bug, Shopper Account/Management, type: community contribution
