### ISSUE TITLE
Chosen shipping disappeared after registration

### ISSUE THREAD

**Issue by diegosomar** [woothemes/woocommerce#30610] opened 2021-08-31 00:30 UTC
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
A guest user select a product, add to cart and in the cart page, calculate and choose shipping method.
Then, before checkout, the guest user goes to MY ACCOUNT page, creates an account and the previous selected shipping has gone. The customer must inform address and choose shipping again. This is not a good experience when the flow is:
Product -> cart (choose shipping) -> register before checkout in my account -> checkout.

With the above flow, after register the user is redirected to checkout without chosen shipping.

**Expected behavior**
The guest chosen shipping remains after login/register.

**Actual behavior**
The previous calculated and chosen shipping has gone after register; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
I have a fresh woocommerce install to test. Only with 2 plugins:
- WooCommerce
-  Correios (Brazilian shipping method)

The theme is Storefront without customizations.

1. Go to [product page](http://wc-bug-test.web2206.uni5.net/wordpress/produto/tshirt/) and click COMPRAR (buy in portuguese);
2. Click in VER CARRINHO (go to cart in pt);
3. Click in CALCULAR ENTREGA (calculate shipping in pt)
4. Shipping data form: Brasil / Rio de Janeiro / Rio de Janeiro / 22011-040 / click in ATUALIZAR (update in pt)
5. Select PAC (is a Brazilian shipping)
6. Before checkout, go to [MINHA CONTA](http://wc-bug-test.web2206.uni5.net/wordpress/minha-conta/) (my account in pt) and in CADASTRE-SE (register in pt) form, create an account (put any data).
7. Go to [cart](http://wc-bug-test.web2206.uni5.net/wordpress/carrinho/) again (or to checkout) and see the chosen shipping has gone.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```

### WordPress Environment ###

WordPress address (URL): http://wc-bug-test.web2206.uni5.net/wordpress
Site address (URL): http://wc-bug-test.web2206.uni5.net/wordpress
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: ❌ 13 MB - Nós recomendamos configurar pelo menos 64MB de memória. Mais informações: Acrescentando memória alocada para o PHP
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.8
PHP Post Max Size: 100 MB
PHP Time Limit: 240
PHP Max Input Vars: 10000
cURL Version: 7.74.0
OpenSSL/1.0.1e-fips

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.32-MariaDB-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: wcdt_
Tamanho total do banco de dados: 8.41MB
Tamanho dos dados do banco de dados: 5.86MB
Tamanho do índice do banco de dado: 2.55MB
wcdt_woocommerce_sessions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_woocommerce_api_keys: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wcdt_woocommerce_order_items: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_woocommerce_order_itemmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_woocommerce_tax_rates: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wcdt_woocommerce_tax_rate_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_woocommerce_shipping_zones: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_woocommerce_payment_tokens: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_woocommerce_log: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_actionscheduler_actions: Dados: 0.02MB + Índex: 0.13MB + mecanismo InnoDB
wcdt_actionscheduler_claims: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_actionscheduler_groups: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_actionscheduler_logs: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_commentmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_comments: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wcdt_gla_budget_recommendations: Dados: 0.22MB + Índex: 0.14MB + mecanismo InnoDB
wcdt_gla_merchant_issues: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_gla_shipping_rates: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_gla_shipping_times: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_links: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailchimp_carts: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_mailchimp_jobs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_mailpoet_custom_fields: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_dynamic_segment_filters: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_feature_flags: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_forms: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_mailpoet_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_mailpoet_mapping_to_external_entities: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_newsletters: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_mailpoet_newsletter_links: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wcdt_mailpoet_newsletter_option: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_newsletter_option_fields: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_newsletter_posts: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_newsletter_segment: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_newsletter_templates: Dados: 2.52MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_mailpoet_scheduled_tasks: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_mailpoet_scheduled_task_subscribers: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_segments: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_mailpoet_sending_queues: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_mailpoet_settings: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_statistics_clicks: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wcdt_mailpoet_statistics_forms: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_statistics_newsletters: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_mailpoet_statistics_opens: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wcdt_mailpoet_statistics_unsubscribes: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wcdt_mailpoet_statistics_woocommerce_purchases: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wcdt_mailpoet_stats_notifications: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_mailpoet_subscribers: Dados: 0.02MB + Índex: 0.13MB + mecanismo InnoDB
wcdt_mailpoet_subscriber_custom_field: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_subscriber_ips: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_subscriber_segment: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_mailpoet_user_agents: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_user_flags: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_options: Dados: 1.47MB + Índex: 0.06MB + mecanismo InnoDB
wcdt_postmeta: Dados: 0.06MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_posts: Dados: 0.06MB + Índex: 0.06MB + mecanismo InnoDB
wcdt_termmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_terms: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_term_relationships: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_term_taxonomy: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_usermeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_users: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wcdt_wc_admin_notes: Dados: 0.05MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_wc_admin_note_actions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_wc_category_lookup: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_wc_customer_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_wc_download_log: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_wc_order_coupon_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_wc_order_product_lookup: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wcdt_wc_order_stats: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wcdt_wc_order_tax_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_wc_product_meta_lookup: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wcdt_wc_reserved_stock: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_wc_tax_rate_classes: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_wc_webhooks: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB

### Post Type Counts ###

attachment: 17
customize_changeset: 2
mailpoet_page: 1
page: 9
post: 2
product: 12
revision: 2

### Security ###

Secure connection (HTTPS): ❌
					Sua loja não está usando HTTPS. Saiba mais sobre HTTPS e certificados SSL.
Hide errors from visitors: ✔

### Active Plugins (2) ###

Claudio Sanches - Correios for WooCommerce: por Claudio Sanches – 3.8.0
WooCommerce: por Automattic – 5.6.0

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base da loja: #6 - /loja/
Carrinho: #7 - /carrinho/
Finalizar compra: #8 - /finalizar-compra/
Minha conta: #9 - /minha-conta/
Termos e condições: ❌ Página não definida

### Theme ###

Name: Storefront
Version: 3.8.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – Recomendamos você utilizar um tema filho no caso de você estiver personalizando o WooCommerce em um tema ascendente. Veja como criar um tema filho
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Concluído: 27
Oldest: 2021-08-30 21:08:16 -0300
Newest: 2021-08-30 21:04:59 -0300


### Status report information ###

Generated at: 2021-08-30 21:29:18 -03:00
```
</details>

**Comment by rodelgc** [comment] 2021-09-01 11:02
Hi @diegosomar,

Thank you for raising the issue. I tried reproducing the bug, but without the Correios plugin, since this repository is only intended for core functionalities of WooCommerce. I couldn't reproduce the bug. I was able to see the same shipping option that I selected before I registered.

Here's the screenshot of my checkout page before creating an account. Notice that I selected "Flat rate" as the shipping option (the default was Free Shipping):
<img width="1497" alt="Screen Shot 2021-09-01 at 6 53 52 PM" src="https://user-images.githubusercontent.com/4509348/131660057-8d7b8e89-cb36-4e5a-b0e6-957cf2261297.png">

And then I went to My Account page, created a new account, and went back to the Checkout page, as you can see below. Notice that "Flat rate" was still selected when I went back to the Checkout page.
<img width="1497" alt="Screen Shot 2021-09-01 at 6 55 46 PM" src="https://user-images.githubusercontent.com/4509348/131660279-988b167c-9081-4f2a-843a-52bdc2c43542.png">

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 
﻿
The issue you are having seems to be caused by the 3rd party plugin Correios. 
﻿
Please contact the author of the plugin directly for further help.

I'm closing this issue for the meantime. Feel free to leave a comment to reopen this issue in case I missed anything.

**Comment by diegosomar** [comment] 2021-09-03 01:00
Hello @rodelgc tks your answer.
I removed the plugin WooCommerce Correios. Now, I have only 1 plugin, WooCommerce and the problem is still here.
You cannot reproduce the issue because you have no entered an address with zipcode.

See below my environment with only WooCommerce plugin:

1. Go to [product page](http://wc-bug-test.web2206.uni5.net/wordpress/produto/tshirt/) and click COMPRAR (buy in portuguese);
2. Click in VER CARRINHO (go to cart in pt);
3. Click in CALCULAR ENTREGA (calculate shipping in pt)
4. Shipping data form: Brasil / Rio de Janeiro / Rio de Janeiro / 22011-040 / click in ATUALIZAR (update in pt)
5. Select TAXA FIXA (flat rate in pt)
6. Before checkout, go to [MINHA CONTA](http://wc-bug-test.web2206.uni5.net/wordpress/minha-conta/) (my account in pt) and in CADASTRE-SE (register in pt) form, create an account (put any data).
7. Go to [cart](http://wc-bug-test.web2206.uni5.net/wordpress/carrinho/) again (or to checkout) and see the chosen shipping has gone.

In my tests, after register, the customer address in session is removed, which causes the problem.
I cannot locate the code that remove the address from session database.

In your environment, do a test adding a product to cart, calculate shipping entering an address and a zipcode, select the last shipping, go to my account, create one and return to cart, refreshing the page.

Below, my updated details, which shows only WooCommerce plugins installed.

<details>

```
### WordPress Environment ###

WordPress address (URL): http://wc-bug-test.web2206.uni5.net/wordpress
Site address (URL): http://wc-bug-test.web2206.uni5.net/wordpress
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: ❌ 13 MB - Nós recomendamos configurar pelo menos 64MB de memória. Mais informações: Acrescentando memória alocada para o PHP
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.8
PHP Post Max Size: 100 MB
PHP Time Limit: 240
PHP Max Input Vars: 10000
cURL Version: 7.74.0
OpenSSL/1.0.1e-fips

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.32-MariaDB-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: wcdt_
Tamanho total do banco de dados: 7.94MB
Tamanho dos dados do banco de dados: 5.42MB
Tamanho do índice do banco de dado: 2.52MB
wcdt_woocommerce_sessions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_woocommerce_api_keys: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wcdt_woocommerce_order_items: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_woocommerce_order_itemmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_woocommerce_tax_rates: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wcdt_woocommerce_tax_rate_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_woocommerce_shipping_zones: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_woocommerce_payment_tokens: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_woocommerce_log: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_actionscheduler_actions: Dados: 0.02MB + Índex: 0.13MB + mecanismo InnoDB
wcdt_actionscheduler_claims: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_actionscheduler_groups: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_actionscheduler_logs: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_commentmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_comments: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wcdt_gla_budget_recommendations: Dados: 0.22MB + Índex: 0.14MB + mecanismo InnoDB
wcdt_gla_merchant_issues: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_gla_shipping_rates: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_gla_shipping_times: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_links: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailchimp_carts: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_mailchimp_jobs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_mailpoet_custom_fields: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_dynamic_segment_filters: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_feature_flags: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_forms: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_mailpoet_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_mailpoet_mapping_to_external_entities: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_newsletters: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_mailpoet_newsletter_links: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wcdt_mailpoet_newsletter_option: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_newsletter_option_fields: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_newsletter_posts: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_newsletter_segment: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_newsletter_templates: Dados: 2.52MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_mailpoet_scheduled_tasks: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_mailpoet_scheduled_task_subscribers: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_segments: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_mailpoet_sending_queues: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_mailpoet_settings: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_statistics_clicks: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wcdt_mailpoet_statistics_forms: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_statistics_newsletters: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_mailpoet_statistics_opens: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wcdt_mailpoet_statistics_unsubscribes: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wcdt_mailpoet_statistics_woocommerce_purchases: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wcdt_mailpoet_stats_notifications: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_mailpoet_subscribers: Dados: 0.02MB + Índex: 0.13MB + mecanismo InnoDB
wcdt_mailpoet_subscriber_custom_field: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_subscriber_ips: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_subscriber_segment: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_mailpoet_user_agents: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_mailpoet_user_flags: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_options: Dados: 1.03MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_postmeta: Dados: 0.06MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_posts: Dados: 0.06MB + Índex: 0.06MB + mecanismo InnoDB
wcdt_termmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_terms: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_term_relationships: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_term_taxonomy: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_usermeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_users: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wcdt_wc_admin_notes: Dados: 0.05MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_wc_admin_note_actions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_wc_category_lookup: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_wc_customer_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_wc_download_log: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_wc_order_coupon_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_wc_order_product_lookup: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wcdt_wc_order_stats: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wcdt_wc_order_tax_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wcdt_wc_product_meta_lookup: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wcdt_wc_reserved_stock: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wcdt_wc_tax_rate_classes: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wcdt_wc_webhooks: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB

### Post Type Counts ###

attachment: 17
customize_changeset: 2
mailpoet_page: 1
page: 9
post: 2
product: 12
revision: 2

### Security ###

Secure connection (HTTPS): ❌
					Sua loja não está usando HTTPS. Saiba mais sobre HTTPS e certificados SSL.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: por Automattic – 5.6.0

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base da loja: #6 - /loja/
Carrinho: #7 - /carrinho/
Finalizar compra: #8 - /finalizar-compra/
Minha conta: #9 - /minha-conta/
Termos e condições: ❌ Página não definida

### Theme ###

Name: Storefront
Version: 3.8.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – Recomendamos você utilizar um tema filho no caso de você estiver personalizando o WooCommerce em um tema ascendente. Veja como criar um tema filho
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Concluído: 32
Oldest: 2021-08-30 21:08:16 -0300
Newest: 2021-09-02 21:47:08 -0300


### Status report information ###

Generated at: 2021-09-02 21:55:06 -03:00
```
</details>

**Comment by diegosomar** [comment] 2021-09-07 13:13
Hello @rodelgc, can you reopen this issue, please?
As I described above, it's a core issue.
Tks.

**Comment by rodelgc** [comment] 2021-09-08 09:24
Hi @diegosomar,

Thank you very much for the clarification, and apologies for the delay in my response. I'll reopen this issue and will try to reproduce the issue again on our end. 

Stay tuned for updates!

**Comment by vinodglobalstep** [comment] 2021-09-08 15:13
Hi @diegosomar ,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end using WooCommerce 5.6 version.

Checkout page before creating an account:
![#30610_1](https://user-images.githubusercontent.com/46351294/132536152-755fef4a-dcbf-4f6f-8559-07d9bb9945a1.png)

Checkout page after creating new account:
![#30610_2](https://user-images.githubusercontent.com/46351294/132536313-e53cfad1-e046-4a23-8433-3a4e1dd7f5a0.png)

Please provide us with more details about the issue which may help us to evaluate it further.

**Comment by diegosomar** [comment] 2021-09-15 12:09
Hello @vinodglobalstep, tks your answer.
I can't understand... I tested in many installations. In my local and in a vanilla WC installation (online test above).
Perhaps there's some configuration which cause the problem.
I will study and test a bit more. A think the issue can be closed for now.
If I figure out a way to reproduce, can I ask to reopen?

**Comment by simplysaru** [comment] 2021-09-26 15:19
Hi @diegosomar ,
﻿
As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Closed as completed by simplysaru** 2021-09-26 15:19 UTC
Labels: Bug, needs: triage feedback
