### ISSUE TITLE
Link not working on woocommerce.com, 404 not found for "free trial extensions"

### ISSUE THREAD

**Issue by nabtron** [woothemes/woocommerce#30917] opened 2021-10-11 02:34 UTC
Steps to produce the error:

1. Goto https://woocommerce.com/contact-us/
2. select "I have a question about a specific extension or theme I’d like to purchase."
3. Select "Want to try a WooCommerce.com extension?"
4. and you land on a 404 page.

![Screenshot 2021-10-11 at 7 33 33 AM](https://user-images.githubusercontent.com/9471128/136725279-d72d30fe-e0bb-451d-90b9-e60b9a7afcb3.png)

![Screenshot 2021-10-11 at 7 34 02 AM](https://user-images.githubusercontent.com/9471128/136725299-26c04ba2-4267-4bc6-9e22-dfb8179e5526.png)

**Comment by juliaamosova** [comment] 2021-10-12 14:37
Hi @nabtron,

Thank you for reporting the issue. It is on the woocommerce.com side of things which is not a part of this repository. It is being developed in another repository which is private. 

I created a bug report on your behalf in the correct (private) repository so that the right team could take a look further. 

Because the issue is not related to the WooCommerce plugin itself, I am going to close it. However, please rest assured that the woocommerce.com team will take care of it further.

**Closed as completed by juliaamosova** 2021-10-12 14:37 UTC
