### ISSUE TITLE
Alignment issue in leaderboard ellipsis menu item

### ISSUE THREAD

**Issue by rmorse** [woothemes/woocommerce#32186] opened 2022-02-01 12:47 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In latest version - 6.1.1

Analytics -> Leaderboards -> Ellipsis Menu -> Rows per table

Alignment looks incorrect:
![image](https://user-images.githubusercontent.com/853547/151970109-34b68e3b-617b-434e-b574-4df590c47cef.png)

### Expected behavior

There is margin on the left/right to match the other menu items

### Actual behavior

...

### Steps to reproduce

1. Head to Analytics
2. Leaderboard
3. Open the Ellipsis Menu
4. Check the **Rows per table** setting

### WordPress Environment

WP 5.9 (latest) / Chrome / Windows 10 / WooCommerce - 6.1.1

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rmorse** [comment] 2022-02-01 12:49
** I know this is a tiny issue, I see little things like this quite often - is worth me opening reports for everything I see when developing or are little things like this not worth it (/will be picked up anyway) ?

**Comment by ObliviousHarmony** [comment] 2022-02-10 19:55
Hi @rmorse,

Thank you for reporting the issue. WooCommerce Admin is being developed in another repository: http://github.com/woocommerce/woocommerce-admin. 

I am going to move your bug report there so that the right team could take a look further.

**Comment by rjchow** [comment] 2022-02-21 05:46
Hi @rmorse, thank you for reporting this issue! We certainly appreciate such reports as it helps us to maintain a high level of consistency and polish in our UI. 

I can confirm that this is an issue, and will assign a priority for it.

For team reference it looks like a `<MenuItem>` is supposed to wrap the `<SelectControl>` at https://github.com/woocommerce/woocommerce-admin/blob/7ee23b3ee6d3409b1e73f9b3ad04050f9cc43e51/client/dashboard/leaderboards/index.js#L125

**Comment by AnnaMag** [comment] 2022-05-23 13:13
It seems that it is the _section title_ frame that is misaligned wrt to the side margins (given the top frame). _Rows per table_ has misaligned header.
I'd appreciate a confidence check. Thanks! /cc @jarekmorawski 

Edit: is this the layout design?

<img width="212" alt="Screenshot 2022-05-23 at 16 41 54" src="https://user-images.githubusercontent.com/13561163/169847287-a0d20808-84f3-4913-8f1e-0bbc44faceb5.png">

**Comment by jarekmorawski** [comment] 2022-05-23 14:55
> Edit: is this the layout design?

Yes, that's perfect. Thanks!

**Comment by joshuatf** [comment] 2022-05-30 16:51
This is fixed by https://github.com/woocommerce/woocommerce/pull/33163.

**Closed as completed by joshuatf** 2022-05-30 16:51 UTC
Labels: Bug, Good First Issue, plugin: woocommerce, Reports/Analytics
