### ISSUE TITLE
Tax Report not being received by email

### ISSUE THREAD

**Issue by lynnjat7** [woothemes/woocommerce#49759] opened 2024-07-22 15:16 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

With WooCommerce version 9.1.2, the Analytics > Taxes report always says "your taxes report will be emailed to you" when clicking the "download" button, even for very short reports.

However, the email is not sent or received.

When downloading the CSV file directly via FTP, the taxes report:
* does not have a header row
* is blank for tax rates that have been removed or deleted, even though these rates still appear correctly in the report shown directly on the dashboard

Ticket - 8450169-zen

We thought this was tied to the pull request here:
https://github.com/woocommerce/woocommerce/pull/49562

However, this pull request seems to be specifically for paginated reports. We have been able to reproduce this behaviour for a simple tax report of only 10 lines that does not require pagination.

### Expected behavior

For such a short tax report, the CSV file should be immediately downloadable. However, even if it is not downloadable, the email should be sent (it is not being sent at all according to WP Mail Logging).

In addition, the downloaded report should have a header row and should show tax rates for deleted tax rates as this information is still available on the report on the dashboard.

### Actual behavior

Tax report cannot be immediately downloaded, and is not sent by email.

Tax report is missing a header row and critical information.

### Steps to reproduce

1. Set up a few tax rates.
2. Make a few sample purchases where various tax rates apply.
3. Remove one of the tax rates.
4. Generate a tax report under Analytics > Taxes --> you should see that the removed tax rate is still listed by name
5. click to download the report --> you should see the message "your taxes report will be emailed to you" even for a very short report
6. check WP Mail Logging and verify the report was not emailed
7. FTP into the site and go to wp-content/uploads/woocommerce_uploads/reports to manually download the report
8. see that the report is missing the name of the tax rate that was removed, as well as a header row

### WordPress Environment

This is from my test site, were I was able to duplicate this:

`
### WordPress Environment ###

WordPress address (URL): https://numberone.mystagingwebsite.com
Site address (URL): https://numberone.mystagingwebsite.com
WC Version: 9.1.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.6
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.2.21
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.4.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.1.2
WC Database Prefix: wp_
Total Database Size: 189.36MB
Database Data Size: 136.92MB
Database Index Size: 52.44MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.16MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.91MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 30.05MB + Index: 18.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 11.02MB + Index: 9.03MB + Engine InnoDB
wp_afwc_campaigns: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_afwc_commission_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_hits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_afwc_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.22MB + Index: 0.33MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 1.52MB + Index: 0.86MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ce4wp_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 3.52MB + Index: 1.44MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.03MB + Index: 0.11MB + Engine InnoDB
wp_postmeta: Data: 7.52MB + Index: 8.80MB + Engine InnoDB
wp_posts: Data: 1.50MB + Index: 0.38MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.39MB + Index: 0.59MB + Engine InnoDB
wp_wc_orders_meta: Data: 2.52MB + Index: 6.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.27MB + Index: 0.44MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.20MB + Index: 0.14MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_generator_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_flat_rate_boxes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 68.56MB + Index: 0.00MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable: Data: 0.17MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 195
aw_workflow: 11
enr_email_template: 1
global_product_addon: 2
mailpoet_page: 1
nav_menu_item: 6
page: 18
post: 3
prl_engine: 2
product: 167
product_variation: 179
revision: 58
shop_coupon: 6
shop_order: 1086
shop_order_refund: 5
shop_subscription: 71
wc-donation: 2
wcpf_item: 10
wcpf_project: 3
wc_membership_plan: 5
wc_user_membership: 12
wp_global_styles: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (43) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.7.22
AutomateWoo: by WooCommerce – 6.0.29
Code Snippets: by Code Snippets Pro – 3.6.5.1
Debug Bar: by wordpressdotorg – 1.1.6
Donation For Woocommerce: by wpexpertsio – 3.6.2
Facebook for WooCommerce: by Facebook – 3.2.5
Google Listings and Ads: by WooCommerce – 2.7.6
Jetpack: by Automattic – 13.7-a.3
Loco Translate: by Tim Whitlock – 2.6.11
Meks Quick Plugin Disabler: by Meks – 1.0
Redirection: by John Godley – 5.4.2
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.24.4

User Switching: by John Blackbourn & contributors – 1.7.3
WooCommerce.com Update Manager: by Automattic – 1.0.3
Woo All Products For Subscriptions: by Woo – 5.0.7
Woo Composite Products: by Woo – 9.1.0
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.5.1
WooCommerce Distance Rate Shipping: by WooCommerce – 1.5.0
Woo Gift Cards: by Woo – 1.17.0
Google Analytics for WooCommerce: by WooCommerce – 2.1.5
WooCommerce Memberships: by SkyVerge – 1.26.7
WooCommerce Name Your Price: by Kathy Darling – 3.5.13
WooPayments: by WooCommerce – 7.9.2
WooCommerce Pre-Orders: by WooCommerce – 2.1.2
Woo Product Add-ons: by Woo – 6.9.0
Woo Product Bundles: by Woo – 7.2.1
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.71
Product Filters for WooCommerce: by WooCommerce – 1.4.31
Woo Product Recommendations: by Woo – 3.0.11
WooCommerce Shipping & Tax: by WooCommerce – 2.6.2
WooCommerce Shipment Tracking: by WooCommerce – 2.5.0
WooCommerce UPS Shipping: by WooCommerce – 3.7.0
WooCommerce - ShipStation Integration: by WooCommerce – 4.4.4
WooCommerce Subscriptions: by WooCommerce – 6.5.0
WooCommerce Table Rate Shipping: by WooCommerce – 3.3.0
WooCommerce Variation Swatches and Photos: by Element Stark – 3.1.10
WooCommerce: by Automattic – 9.1.2
Yoast SEO: by Team Yoast – 23.0
WP Crontrol: by John Blackbourn – 1.17.0
WP File Manager: by mndpsingh287 – 7.2.9
WP Mail Logging: by WP Mail Logging Team – 1.12.0
WP phpMyAdmin: by Puvox.software – 5.2.1.13

### Inactive Plugins (13) ###

Advanced Custom Fields: by WP Engine – 6.3.1
Advanced Product Fields for WooCommerce: by StudioWombat – 1.6.8
Affiliate For WooCommerce: by StoreApps – 7.3.0 (update to version 8.0.2 is available)
Cart Upsell for WooCommerce: by SKROTRON – 1.0.8
Custom Post Type UI: by WebDevStudios – 1.17.0
Discounts for WooCommerce Subscriptions: by Meow Crew – 2.4.1 (update to version 3.1.1 is available)
Enhancer for WooCommerce Subscriptions: by Flintop – 4.2.0
Extra Fees for WooCommerce: by Flintop – 5.9.0
MailPoet: by MailPoet – 4.52.0
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.11.0 (update to version 3.12.0 is available)
WooCommerce Flat Rate Box Shipping: by WooCommerce – 2.2.5 (update to version 2.2.6 is available)
WooCommerce Quick View: by Themesquad – 1.7.0 (update to version 1.8.1 is available)
WooCommerce Subscriptions Gifting: by WooCommerce – 2.7.0

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
visible (visible)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 6 MB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #7 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #8 - /my-account/
Terms and conditions: #767 - /terms-and-conditions/

### Theme ###

Name: Storefront
Version: 4.3.0 (update to version 4.6.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 7.9.2
Connected to WPCOM: Yes
WPCOM Blog ID: 210717503
Account ID: acct_1Ljq8PFtdYohmYFC
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Not eligible
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Memberships ###

Restriction mode:: Hide content only
Public content:: –
Excluded from discounts:: –
Membership plans:: 5
White Text Membership:: Members: 0Access method: Product(s) purchaseAccess length: Unlimited Subscription: No
Free Membership:: Members: 3Access method: Manual assignment onlyAccess length: Unlimited Subscription: No
Basic membership:: Members: 1Access method: Product(s) purchaseAccess length: Specific length (60 days)Subscription: No
Fruit Basket Delivery:: Members: 4Access method: Product(s) purchaseAccess length: Unlimited Subscription: YesInstallment plan: No No access-granting products are purchasable
VIP Membership:: Members: 4Access method: Product(s) purchaseAccess length: Specific length (6 months)Subscription: YesInstallment plan: No

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://numberone.mystagingwebsite.com
Subscriptions-core Library Version: 7.3.0
Subscription Statuses: wc-active: 42
wc-cancelled: 8
wc-expired: 8
wc-on-hold: 10
wc-pending: 2
wc-pending-cancel: 1

WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — New York

### Subscriptions by Payment Gateway ###

Check payments: wc-on-hold: 1
WooPayments: wc-active: 40
wc-cancelled: 8
wc-expired: 8
wc-on-hold: 6
wc-pending-cancel: 1

### Payment Gateway Support ###

WooPayments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

Check payments: products
Cash on delivery: products

### Composite Products ###

Database Version: 9.1.0
Loopback Test: ✔
Template Overrides: –

### Gift Cards ###

Database Version: 1.17.0
Loopback Test: ✔
Task Queueing Test: ✔

### Product Bundles ###

Database Version: 7.2.1
Loopback Test: ✔
Template Overrides: –

### Name Your Price ###

Version: 
Database Version: 
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-22 19:51:29 -04:00
Options: ✔
Notes: 168
Onboarding: completed

### All Products for Woo Subscriptions ###

Template Overrides: –

### WooCommerce Customer/Order/Coupon Export ###

Automated exports: 1
Custom formats: 1
Next export: Not scheduled

### Action Scheduler ###

Canceled: 46
Oldest: 2024-06-22 09:51:33 -0400
Newest: 2024-07-22 11:04:58 -0400

Complete: 42,252
Oldest: 2024-06-21 11:18:19 -0400
Newest: 2024-07-22 11:15:34 -0400

Failed: 223
Oldest: 2022-10-18 12:07:43 -0400
Newest: 2024-07-17 13:38:38 -0400

Pending: 66
Oldest: 2024-07-22 11:17:34 -0400
Newest: 2025-07-22 04:00:00 -0400

### Product Recommendations ###

Database Version: 3.0.11
Loopback Test: –
Task Queueing Test: ✔
Page Cache Test: –

### Status report information ###

Generated at: 2024-07-22 11:16:19 -04:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ldr2273** [comment] 2024-07-23 20:16
Another case in: 8505248-zen

**Comment by rareheron** [comment] 2024-07-23 21:31
I also have this issue and need a fix or a workaround absolutely as soon as possible.

**Comment by Saggre** [comment] 2024-07-29 08:52
I've experienced a similar bug for at least a year due to the `email_report_download_link` action not being rescheduled and being run immediately, while the report is still being generated. The email will be completely discarded due to its completion being less than 100%.

**Comment by Saggre** [comment] 2024-07-29 08:54
Here, `$percent_complete` will be less than 100:

https://github.com/woocommerce/woocommerce/blob/df4bd38297da4cabb3581d86489c0217f39366d7/plugins/woocommerce/src/Admin/ReportExporter.php#L199-L213

**Comment by Saggre** [comment] 2024-07-29 13:07
@lynnjat7 @rareheron This PR may fix the mailing issue: https://github.com/woocommerce/woocommerce/pull/50082
Depending if it's due to the same issue or not.

**Comment by tomalec** [comment] 2024-09-14 15:03
I was not able to reproduce the issue by solely removing the taxes, but I was able to reproduce it by changing the tax rate. Here is the fix for that scenario 
https://github.com/woocommerce/woocommerce/pull/51270

**Comment by tomalec** [comment] 2024-09-14 16:24
For the missing tax names in the generated file, I made another fix at https://github.com/woocommerce/woocommerce/pull/51395

**Comment by tomalec** [comment] 2024-09-29 19:29
I'm closing the issue as fixed with https://github.com/woocommerce/woocommerce/pull/51270 & https://github.com/woocommerce/woocommerce/pull/51395. If the issues is still there for you with [the latest nightly](https://github.com/woocommerce/woocommerce/releases/tag/nightly) build, please feel free to reopen, providing details.

**Closed as completed by tomalec** 2024-09-29 19:29 UTC
Labels: Bug, Reports/Analytics
