### ISSUE TITLE
Woocommerce error when viewing and downloading packing slips

### ISSUE THREAD

**Issue by GTABrews** [woothemes/woocommerce#30853] opened 2021-09-30 15:51 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I receive an error when trying to view and download packing slips. 

**Expected behavior**
I expect to view the packing slip when I click on the icon. I also expect to be able to donwload the selected packing slips into a .zip file.

**Actual behavior**
I receive an error when clicking on a single packing slip - in appears to include some error code.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'Orders'
2. Click on 'View Packing Slip Icon' on the right hand side of any order
3. See error

**Screenshots**
See attached

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): https://www.gtabrews.ca
Site address (URL): https://www.gtabrews.ca
WC Version: 5.7.1
REST API Version: ✔ 5.7.1
WC Blocks Version: ✔ 6.0.2
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.6.5
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.24
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1l-fips

SUHOSIN Installed: –
MySQL Version: 5.7.32-35-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: wp_rcqv_
Total Database Size: 84.20MB
Database Data Size: 61.00MB
Database Index Size: 23.20MB
wp_rcqv_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_rcqv_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rcqv_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rcqv_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rcqv_woocommerce_order_items: Data: 0.34MB + Index: 0.11MB + Engine InnoDB
wp_rcqv_woocommerce_order_itemmeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_rcqv_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rcqv_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rcqv_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rcqv_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rcqv_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rcqv_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rcqv_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rcqv_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rcqv_actionscheduler_actions: Data: 2.02MB + Index: 1.06MB + Engine InnoDB
wp_rcqv_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rcqv_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rcqv_actionscheduler_logs: Data: 0.34MB + Index: 0.27MB + Engine InnoDB
wp_rcqv_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_rcqv_comments: Data: 0.96MB + Index: 0.37MB + Engine MyISAM
wp_rcqv_ewwwio_images: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_rcqv_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rcqv_mepr_events: Data: 2.52MB + Index: 6.58MB + Engine InnoDB
wp_rcqv_mepr_jobs: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_rcqv_mepr_members: Data: 0.13MB + Index: 0.27MB + Engine InnoDB
wp_rcqv_mepr_rule_access_conditions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rcqv_mepr_subscriptions: Data: 0.14MB + Index: 0.33MB + Engine InnoDB
wp_rcqv_mepr_subscription_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rcqv_mepr_tax_rates: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_rcqv_mepr_tax_rate_locations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rcqv_mepr_transactions: Data: 0.47MB + Index: 1.77MB + Engine InnoDB
wp_rcqv_mepr_transaction_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rcqv_options: Data: 3.74MB + Index: 0.53MB + Engine MyISAM
wp_rcqv_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rcqv_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rcqv_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rcqv_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rcqv_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rcqv_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rcqv_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rcqv_postmeta: Data: 7.32MB + Index: 3.64MB + Engine MyISAM
wp_rcqv_posts: Data: 27.51MB + Index: 0.68MB + Engine MyISAM
wp_rcqv_redirection_404: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rcqv_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rcqv_redirection_items: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_rcqv_redirection_logs: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_rcqv_termmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_rcqv_terms: Data: 0.01MB + Index: 0.05MB + Engine MyISAM
wp_rcqv_term_relationships: Data: 0.09MB + Index: 0.19MB + Engine MyISAM
wp_rcqv_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp_rcqv_usermeta: Data: 1.61MB + Index: 0.98MB + Engine MyISAM
wp_rcqv_users: Data: 0.09MB + Index: 0.11MB + Engine MyISAM
wp_rcqv_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_rcqv_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rcqv_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rcqv_wc_customer_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_rcqv_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rcqv_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rcqv_wc_order_product_lookup: Data: 0.25MB + Index: 0.28MB + Engine InnoDB
wp_rcqv_wc_order_stats: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_rcqv_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rcqv_wc_product_meta_lookup: Data: 0.13MB + Index: 0.20MB + Engine InnoDB
wp_rcqv_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rcqv_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rcqv_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rcqv_wfBlockedIPLog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rcqv_wfBlocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rcqv_wfConfig: Data: 2.43MB + Index: 0.02MB + Engine MyISAM
wp_rcqv_wfCrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rcqv_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rcqv_wfFileMods: Data: 2.50MB + Index: 0.51MB + Engine MyISAM
wp_rcqv_wfHits: Data: 1.29MB + Index: 0.35MB + Engine MyISAM
wp_rcqv_wfHoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rcqv_wfIssues: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_rcqv_wfKnownFileList: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_rcqv_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rcqv_wfLocs: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_rcqv_wfLogins: Data: 0.43MB + Index: 0.08MB + Engine MyISAM
wp_rcqv_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rcqv_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rcqv_wfNotifications: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_rcqv_wfPendingIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rcqv_wfReverseCache: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_rcqv_wfSNIPCache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rcqv_wfStatus: Data: 0.12MB + Index: 0.05MB + Engine MyISAM
wp_rcqv_wfTrafficRates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rcqv_wfu_dbxqueue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rcqv_wfu_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rcqv_wfu_userdata: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rcqv_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rcqv_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1170
calendar: 1
customize_changeset: 1
custom_css: 1
memberpresscoupon: 1
memberpressproduct: 4
memberpressrule: 5
mp-reminder: 2
nav_menu_item: 54
page: 67
post: 271
product: 316
product_variation: 388
revision: 3132
safecss: 1
shop_order: 1354
shop_order_refund: 291
tablepress_table: 3
wp_block: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

VaultPress: by Automattic – 2.1.4
Akismet Anti-Spam: by Automattic – 4.1.12
BAW Login/Logout menu: by Juliobox – 1.3.3
BeerXML Shortcode: by Derek Springer – 0.7.1
Booster Plus for WooCommerce: by Algoritmika Ltd – 4.7.1
Compact Audio Player: by Tips and Tricks HQ – 1.9.6
Display Posts: by Bill Erickson – 3.0.2
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.1.2
Easy Table of Contents: by Steven A. Zahm – 2.0.17
XML-Upload-Allow: by  –
Jetpack: by Automattic – 10.1
Collapse-O-Matic: by twinpictures
baden03 – 1.7.13

MCE Table Buttons: by Jake Goldman
10up
Oomph – 3.3

MemberPress MailChimp 3.0: by Caseproof
LLC – 1.2.2

MemberPress WooCommerce: by Caseproof
LLC – 1.0.5

MemberPress Business (Legacy): by Caseproof
LLC – 1.9.23

Public Post Preview: by Dominik Schilling – 2.9.3
SiteGround Optimizer: by SiteGround – 5.9.7
TablePress Extension: DataTables ColumnFilterWidgets: by Tobias Bäthge – 1.7
TablePress Extension: PHP in tables: by Tobias Bäthge – 1.0
TablePress: by Tobias Bäthge – 1.14
Theme Authenticity Checker (TAC): by builtBackwards – 1.5.3
Use Google Libraries: by Jason Penney – 1.6.2.3
WooCommerce Blocks: by Automattic – 6.0.2
Advanced Order Export For WooCommerce: by AlgolPlus – 3.1.9
WooCommerce Admin: by WooCommerce – 2.6.5
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce Stripe Gateway: by WooCommerce – 5.5.0
Booster for WooCommerce: by Pluggabl LLC – 5.4.7
WooCommerce Max Quantity: by Isabel Castillo – 1.5.2
WooCommerce Shipping & Tax: by WooCommerce – 1.25.18
WooCommerce: by Automattic – 5.7.1
Wordfence Security: by Wordfence – 7.5.5
Wordpress File Upload: by Nickolas Bossinas – 4.15.0

### Inactive Plugins (8) ###

EWWW Image Optimizer: by Exactly WWW – 6.2.4
Fullwidth Page Templates: by Brainstorm Force – 1.1.1
PayPal Donations: by Tips and Tricks HQ
Johan Steen – 1.9.7

Redirection: by John Godley – 5.1.3
Rocket Maintenance Mode & Coming Soon Page Builder: by wpexpertsio – 4.2
Theme File Duplicator: by Jon Schwab – 1.3
WooCommerce Grid / List toggle: by jameskoster – 1.2.1
WP Super Cache: by Automattic – 1.7.4

### Dropin Plugins (1) ###

install.php: install.php

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #1457 - /shop/
Cart: #1458 - /cart/
Checkout: #1459 - /checkout/
My account: #1460 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Thirteen
Version: 3.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2,438
Oldest: 2021-08-31 12:48:15 -0400
Newest: 2021-09-30 11:28:19 -0400

Pending: 4
Oldest: 2021-09-30 12:25:53 -0400
Newest: 2021-10-07 06:25:01 -0400

### Status report information ###

Generated at: 2021-09-30 11:50:34 -04:00
`
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>
![Error](https://user-images.githubusercontent.com/91685849/135488703-c203993d-27be-4206-bf5e-342b3fe2319b.png)

**Comment by tammullen** [comment] 2021-09-30 22:20
Hi @GTABrews 

> Click on 'View Packing Slip Icon' on the right hand side of any order

This is not part of WooCommerce core and is likely coming from an additional plugin you have installed.

Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Please contact the author of the plugin directly for further help.

**Closed as completed by tammullen** 2021-09-30 22:20 UTC
Labels: Bug
