### ISSUE TITLE
[Enhancement]: Including WooCommerce Blocks aggregated changelog or highlights in the WooCommece release notes 

### ISSUE THREAD

**Issue by asafm7** [woothemes/woocommerce#39785] opened 2023-08-17 12:41 UTC
### Describe the solution you'd like

WooCommerce releases included references to several WooCommerce Blocks versions' changelogs. They are sometimes not chronically ordered, or bundled together. 

![image](https://github.com/woocommerce/woocommerce/assets/14274769/24f2d1a8-8b67-4804-ac72-b1a65c3bb169)

The multiple changelogs, and the way they are ordered, make it challenging to keep track of important changes and new opportunities.

Could this be improved? 

### Describe alternatives you've considered

Aggregate WooCommerce Blocks changes, or include highlights.

**Comment by juliaamosova** [comment] 2024-02-02 21:15
Hi @asafm7! Thank you for opening this issue and my apologies for the long reply here. 

With [WooCommerce Blocks being merged to Core](https://developer.woo.com/2023/12/11/the-woo-blocks-merge-to-the-monorepo-is-complete-along-with-monorepo-tool-enhancements/) in December 2023, all blocks related PRs are being submitted and merged directly to the monorepo/Core with the [changelog containing all PRs (blocks and Core) in one place starting 8.5 release](https://github.com/woocommerce/woocommerce/blob/trunk/changelog.txt). 

With the above said, the issue is no longer relevant so I will close it. Please feel free to comment further and feel free to reopen in case you think I missed something.

**Closed as completed by juliaamosova** 2024-02-02 21:15 UTC
Labels: Enhancement, Task (new), focus: monorepo infrastructure, type: community contribution, focus: release

**Comment by asafm7** [comment] 2024-02-03 15:03
That's great @juliaamosova. Thank you!
