### ISSUE TITLE
Is there a missing argument in do_action('woocommerce_new_order') when this one is triggered by the API?

### ISSUE THREAD

**Issue by danielcivit** [woothemes/woocommerce#31529] opened 2021-12-30 13:59 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We have a plugin who register an action hook "woocommerce_new_order", which works fine when the action is triggered by the application. But when the action is triggered by an API call fails. 

**It seems the action is passing different arguments when the order is created by the application:** 

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php#L173

**But when the action is triggered by orders created via API second argument '$order' is missing:** 

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/legacy/api/v2/class-wc-api-orders.php#L465

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/legacy/api/v3/class-wc-api-orders.php#L505

We believe this could be a bug; or at least something not documented properly. 
Is also true is possible fetch the order with the order_id, and fix any issue. We understand that, however, why is only passing one argument.  

### Expected behavior

When woocommerce_new_order action is triggered via API, will pass the same arguments

### Actual behavior

When woocommerce_new_order action is triggered via API, is only passing order_id argument

### Steps to reproduce

1. Install and activate any plugin which register an action like the following: 

`add_action( 'woocommerce_new_order', 'callback_action_woocommerce_new_order', 10, 2 ); `

```
function callback_action_woocommerce_new_order($order_id, $order) {
// do something with the arguments
}
```

2. Trigger an order via API. Second argument is missed. 

### WordPress Environment

I think this is not required on this case. You can reproduce this issue in a clean Wordpress - WooCommerce environment.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by zhongruige** [comment] 2021-12-30 20:20
Hi @Daniel-MultiSafepay,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

To test this, I installed the [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin so I could manually add in the action and the function that gets called. I tested this with the following:

* A fresh install of WooCommerce 6.0.0
* WordPress 5.8.2
* PHP 7.4

I added the following snippet, and used the WC logger to see if the second argument was being passed in:

```php
add_action( 'woocommerce_new_order', 'callback_action_woocommerce_new_order', 1, 2 ); 

function callback_action_woocommerce_new_order($order_id, $order) {
	// Load the WooCommerce Logger
	$logger = wc_get_logger();
    
	// Log the arguments passed in to the function
	$logger->info( wc_print_r( $order_id, true ), array( 'source' => 'testing-arguments' ) );
	$logger->info( wc_print_r( $order, true ), array( 'source' => 'testing-arguments' ) );
}
```

Then, I proceeded to make the following API call to place a new order:

```
POST {base_url}/wp-json/wc/v3/orders

{
  "payment_method": "bacs",
  "payment_method_title": "Direct Bank Transfer",
  "set_paid": false,
  "billing": {
    "first_name": "John",
    "last_name": "Doe",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US",
    "phone": "(555) 555-5555"
  },
  "shipping": {
    "first_name": "John",
    "last_name": "Doe",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US"
  }
}
```

I then proceeded to check the logs under `WooCommerce > Status > Logs` for the `testing-arguments` log. There I saw both the order ID and the order object data outputted:

<img width="819" alt="Screen Shot 2021-12-30 at 13 15 46" src="https://user-images.githubusercontent.com/71906536/147785265-68813e8a-c26b-4d3d-8eea-2752b28c819a.png">

I made sure this matched the API response as well:

<img width="368" alt="Screen Shot 2021-12-30 at 13 15 32" src="https://user-images.githubusercontent.com/71906536/147785256-ad3b5cf6-75a3-49a2-80b7-b37fc16d2cf6.png">

Please let me know if I missed anything in the steps above, if there's another plugin I should check with, or if there's some more details about the issue that can help further evaluate what may be happening.

Thank you!

**Comment by danielcivit** [comment] 2021-12-31 12:01
Hello @zhongruige.

First at all, thank you for your time and your reply. 

Sorry to say, but I realize I was in the wrong track investigating this issue, and now I realize "modern" API calls are using this class:
- https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-orders-controller.php

And not any of the referred by me in my previous message, which are "legacy" classes and I think are not being used in "modern" API calls.

- https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/legacy/api/v2/class-wc-api-orders.php#L465
- https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/legacy/api/v3/class-wc-api-orders.php#L505

==== 

However in these cases there is a missing argument.  Please consider the same procedure but change the API call endpoint using the following details and you will find the error: 

```
POST: {base_url}/wc-api/v3/orders

{
  "order": {
    "payment_details": {
      "method_id": "bacs",
      "method_title": "Direct Bank Transfer",
      "paid": true
    },
    "billing_address": {
      "first_name": "John",
      "last_name": "Doe",
      "address_1": "969 Market",
      "address_2": "",
      "city": "San Francisco",
      "state": "CA",
      "postcode": "94103",
      "country": "US",
      "email": "john.doe@example.com",
      "phone": "(555) 555-5555"
    },
    "shipping_address": {
      "first_name": "John",
      "last_name": "Doe",
      "address_1": "969 Market",
      "address_2": "",
      "city": "San Francisco",
      "state": "CA",
      "postcode": "94103",
      "country": "US"
    },
    "customer_id": 1,
    "line_items": [],
    "shipping_lines": [
      {
        "method_id": "flat_rate",
        "method_title": "Flat Rate",
        "total": "10.00"
      }
    ]
  }
}
```


====

In any case, like I said, I was in the wrong track and I am able to understand now my problem is not related with WooCommerce; since this plugin is using "modern" API calls.

I leave to your consideration if you want to close this issue, or if change something in the referred legacy classes is something that you or WooCommerce team still want to do.  If I understand correctly that part of the code already is in "end of life" status, and is out of support. 


Thanks again.

**Comment by zhongruige** [comment] 2022-01-03 22:25
Thank you for the reply @Daniel-MultiSafepay! I am adding the `needs developer feedback` label to this issue so that the Core team could take a look and provide some more insight.

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment] 2022-01-07 15:08
@Daniel-MultiSafepay yup looks like a param is missing there. I am marking this as a bug but this API is actually deprecated in favor of the newer ones, so it would be a low priority. that said, i would encourage you to switch to modern ones, and if possible send in a pr as well given that you have already identified the fix.

**Comment by peterfabian** [comment] 2023-03-30 12:48
Since this relates to the legacy API, we don't support it anymore and it is way past its end of life. Thanks for reporting the issue anyway!

**Closed as completed by peterfabian** 2023-03-30 12:48 UTC
Labels: Bug, Good First Issue, REST/Store API/Webhooks, plugin: woocommerce
