### ISSUE TITLE
Cannot set images for product gallery

### ISSUE THREAD

**Issue by trajche** [woothemes/woocommerce#7498] opened 2015-02-19 15:43 UTC
In file:
meta-boxes-product.min.js
`<img src="'+attachment.sizes.thumbnail.url+'" />`
attachment.sizes.thumbnail.url
does not pull an image.

More info:
https://support.woothemes.com/hc/communities/public/questions/202241475-Cannot-set-images-for-product-gallery/

### WordPress Environment ###

Home URL: x
Site URL: x
WC Version: 2.3.4
WC Database Version: 2.3.4
Log Directory Writable: ✔ x
WP Version: 4.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: nginx 1.4.6
PHP Version: 5.5.9-1(ubuntu4.5)
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.40
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Server Locale ###

decimal_point: .
thousands_sep: N/A
mon_decimal_point: N/A
mon_thousands_sep: N/A

### Settings ###

API Enabled: ✔
Taxes Enabled: –
Shipping Enabled: ✔
Force SSL: –
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### WC Pages ###

Shop Base: #5 - /shop/
Cart: #6 - /varukorg/
Checkout: #7 - /kassa/
My Account: #8 - /mitt-konto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Custom Theme
Version: 1.0
Author URL: http://tj.mk
Child Theme: ✕ – If you're modifying WooCommerce or a parent theme you didn't build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: modemani/woocommerce/archive-product.php
modemani/woocommerce/content-product.php
modemani/woocommerce/emails/customer-completed-order.php
modemani/woocommerce/emails/customer-invoice.php
modemani/woocommerce/emails/customer-new-account.php
modemani/woocommerce/emails/customer-note.php
modemani/woocommerce/emails/customer-processing-order.php
modemani/woocommerce/emails/customer-reset-password.php
modemani/woocommerce/single-product/add-to-cart/variable.php
modemani/woocommerce/single-product/short-description.php
modemani/woocommerce/single-product/title.php
modemani/woocommerce/single-product.php

**Comment by mikejolley** [comment] 2015-02-19 15:49
Dupe of https://github.com/woothemes/woocommerce/issues/7491

**Closed by mikejolley** 2015-02-19 15:49 UTC
