### ISSUE TITLE
[Setup Wizard] - If setup wizard is abandoned part way through, progress is forgotten (data still saved)

### ISSUE THREAD

**Issue by lanej0** [woothemes/woocommerce#32229] opened 2021-10-11 23:38 UTC
### Describe the bug
When working through the Setup Wizard, if you're interrupted and have to return later (maybe your browser crashes, or you have a power failure, or just get distracted and close the window!), your progress is forgotten and you're returned to the first step of the Setup Wizard.

Your address data is pre-populated, however your response to the Usage Tracking modal is forgotten if you answered No.  If you answered Yes, you are not presented with the modal again

### To Reproduce

1. Go to /wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=store-details
2. Complete the required address information
3. Click Continue
4. Click "No" for allowing tracking usage
5. Close your browser
6. Open a new window, go to the Wordpress Admin (/wp-admin) and click on "WooCommerce" on the left
7. Click on Continue

### Actual behavior:
You are directed back into the setup wizard, but starting at step 1.  You can still click forward to step 2, 3, 4, or 5 (assuming you had gotten that far previously).  Additionally, the modal to allow usage tracking is displayed again.  If you answer "Yes" the first time through, you are not shown the dialog again

### Expected behavior
Ideally, you'd pick up where you left off.  If you made it to Product Types, you should start at Product Types when resuming the Setup Wizard.

There should be consistent behavior for both options in usage tracking.  Either save the response for both yes and no, or don't save the response at all until the wizard has been completed.

### Desktop (please complete the following information):

* OS: MacOS
* Browser: Chrome, Safari
* Version: 94, 15.1

**Comment by lanej0** [comment] 2021-10-13 23:16
Just noting that this is still present in 5.8.

**Comment by octaedro** [comment] 2021-10-28 17:18
Thank you @lanej0 for reporting this problem. I can reproduce it.

**Comment by joshuatf** [comment] 2022-01-27 22:17
Just noting that this logic makes sense if the profiler is incomplete, but if they've completed until the last step, we would want to begin at store details again since it's possible to revisit the setup wizard after completion.

Going to keep this issue open since it could prove useful in helping users set up stores more quickly.

**Comment by chihsuan** [comment] 2023-05-04 05:39
Closing this since we're going to replace the current OBW.

**Closed as completed by chihsuan** 2023-05-04 05:39 UTC
Labels: Bug, Enhancement, plugin: woocommerce, Onboarding
