### ISSUE TITLE
List all the products with attribute using WooCommerce REST API

### ISSUE THREAD

**Issue by faiz-rizvi** [woothemes/woocommerce#30467] opened 2021-08-10 13:38 UTC
I want to send an HTTP GET request to get all the products with a specific attribute using WooCommerce REST API. I am following [this](https://woocommerce.github.io/woocommerce-rest-api-docs/?shell#list-all-products) WooCommerce document.

I have successfully limited the result with below properties:
/wp-json/wc/v3/products?per_page=20&page=2
/wp-json/wc/v3/products?category=745

However, I am trying to get a product with attribute, but it is not working:
/wp-json/wc/v3/products?attribute=pa_brand&attribute_term=899

I have checked, and my attribute name (**pa_brand**) & term_id/tag_id (**899**) both are correct.

Thanks in advance.

**Comment by juliaamosova** [comment] 2021-08-13 21:03
Hi @rfa786,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end using WooCommerce 5.5.2. 

>However, I am trying to get a product with attribute, but it is not working:
/wp-json/wc/v3/products?attribute=pa_brand&attribute_term=899

The request is the correct one. Below is my test showing that it works and returns results:

![black](https://user-images.githubusercontent.com/19143190/129418155-e824c800-33bb-4692-8c29-ba31d6ea6e1a.png)

![black2](https://user-images.githubusercontent.com/19143190/129418164-d0452de7-f1d8-4b92-92d9-7afde4842500.png)

If the values of your parameters are indeed correct as you say, I can recommend testing the site for a theme and plugins conflict. 

To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by rrennick** [comment] 2023-10-31 18:48
Closing for lck of feedback.

**Closed as completed by rrennick** 2023-10-31 18:48 UTC
Labels: status: can't reproduce, REST/Store API/Webhooks, plugin: woocommerce
