### ISSUE TITLE
Uploading a product via the REST API with a client library fails and creates a broken product

### ISSUE THREAD

**Issue by Monniasza** [woothemes/woocommerce#40832] opened 2023-10-17 16:50 UTC
Related to https://github.com/woocommerce/wc-api-php/issues/340
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When a new product is added via the Automattic\WooCommerce\Client library, the WordPress encounters a fatal error, and the library receives an invalid response:
```

Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Error: <p>W witrynie wystąpił błąd krytyczny.</p><p><a href="https://wordpress.org/documentation/article/faq-troubleshooting/">Dowiedz się więcej o rozwiązywaniu problemów z WordPressem.</a></p> [internal_server_error] in C:\Users\oskar\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php:383 Stack trace: #0 C:\Users\oskar\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php(419): Automattic\WooCommerce\HttpClient\HttpClient->lookForErrors(Object(stdClass)) #1 C:\Users\oskar\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php(455): Automattic\WooCommerce\HttpClient\HttpClient->processResponse() #2 C:\Users\oskar\vendor\automattic\woocommerce\src\WooCommerce\Client.php(56): Automattic\WooCommerce\HttpClient\HttpClient->request('products', 'POST', Array) #3 C:\xampp\htdocs\konrad\wp-content\plugins\product-importer-plugin\insert-test.php(27): Automattic\WooCommerce\Client->post('products', Array) #4 {main} thrown in C:\Users\oskar\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php on line 383
```
The API credentials are correct, otherwise, an error would be different.
The screenshot clearly shows that a product is broken:
![image](https://github.com/woocommerce/woocommerce/assets/37037712/2509d8ad-2cf6-4ee7-9bfb-22ce003709f9)
![image](https://github.com/woocommerce/woocommerce/assets/37037712/95c0fde4-50bf-407c-841b-45afeee6b88b)
Below it is an example of a working product:
![image](https://github.com/woocommerce/woocommerce/assets/37037712/fca5f244-c455-4940-8cfa-3e11a48ce315)

### Expected behavior

A product appears on the store page with the provided parameters 

### Actual behavior

The WooCommerce API returns an invalid response and causes a fatal error, and a broken product appears in the admin menu, but not the product listing. Additionally, the displayed product count is higher by 1 than actual count of working products

### Steps to reproduce

Create a PHP script and visit it with the browser. Replace the autoload and API configs:
```php
<?php
	//Include the WooCommerce API Client in Your PHP File
	require_once '\vendor\autoload.php'; // Replace with the path to your vendor/autoload.php
	// Include PHPExcel
	use PhpOffice\PhpSpreadsheet\IOFactory;
	use Automattic\WooCommerce\Client;
	// WooCommerce API credentials
	$api_url = 'http://example.com/'; // Your store's URL
	$api_key = 'ck_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'; // Replace with your API key
	$api_secret = 'cs_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'; // Replace with your API secret

	// Initialize the WooCommerce API client with your credentials
	$woocommerce = new Automattic\WooCommerce\Client($api_url, $api_key, $api_secret, ['version' => 'wc/v3']);
	
	// Define WooCommerce product data
	$product_data = [
		'name' => 'DebugTestProduct', // Product name without SKU
		'type' => 'simple',
		'regular_price' => '123',
		'description' => '',
		'short_description' => '',
		'stock_quantity' => 12,
		'sku' => 'PR123', // Product SKU (product number)
	];

	// Add the product to WooCommerce
	$new_product = $woocommerce->post('products', $product_data);

	// Check for errors or handle success as needed
	if (is_wp_error($new_product)) {
		echo 'Error importing product: ' . $new_product->get_error_message() . '<br>';
	} else {
		echo 'Product imported successfully: ' . $new_product->name . '<br>';
	}
?>
```

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): http://localhost/konrad
Site address (URL): http://localhost/konrad
WC Version: 8.2.1
REST API Version: ✔ 8.2.1
WC Blocks Version: ✔ 11.1.2
Action Scheduler Version: ✔ 3.6.3
Log Directory Writable: ✔
WP Version: 6.3.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: pl_PL
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.56 (Win64) OpenSSL/1.1.1t PHP/8.2.4
PHP Version: 8.2.4
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.85.0
OpenSSL/3.0.8

SUHOSIN Installed: –
MySQL Version: 10.4.28-MariaDB
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Twój serwer nie ma włączonej obsługi SoapClient - niektóre bramki płatności
które używają SOAP mogą nie działać poprawnie.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.1
WC Database Prefix: wp_
Całkowity rozmiar bazy danych: 11.48MB
Rozmiar bazy danych: 7.92MB
Rozmiar indeksu bazy danych: 3.56MB
wp_woocommerce_sessions: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_woocommerce_api_keys: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_attribute_taxonomies: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_woocommerce_downloadable_product_permissions: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wp_woocommerce_order_items: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_woocommerce_order_itemmeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_tax_rates: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wp_woocommerce_tax_rate_locations: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_shipping_zones: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_woocommerce_shipping_zone_locations: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_shipping_zone_methods: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_woocommerce_payment_tokens: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_woocommerce_payment_tokenmeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_log: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_actionscheduler_actions: Dane: 0.13MB + Indeks: 0.11MB + Silnik InnoDB
wp_actionscheduler_claims: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_actionscheduler_groups: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_actionscheduler_logs: Dane: 0.11MB + Indeks: 0.03MB + Silnik InnoDB
wp_commentmeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_comments: Dane: 0.02MB + Indeks: 0.09MB + Silnik InnoDB
wp_gla_attribute_mapping_rules: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_gla_budget_recommendations: Dane: 0.20MB + Indeks: 0.11MB + Silnik InnoDB
wp_gla_merchant_issues: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_gla_shipping_rates: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_gla_shipping_times: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_gutenaforms: Dane: 0.03MB + Indeks: 0.02MB + Silnik InnoDB
wp_gutenaforms_entries: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_gutenaforms_field_value: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_gutenaforms_meta: Dane: 0.02MB + Indeks: 0.05MB + Silnik InnoDB
wp_links: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_automations: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_mailpoet_automation_runs: Dane: 0.02MB + Indeks: 0.08MB + Silnik InnoDB
wp_mailpoet_automation_run_logs: Dane: 0.02MB + Indeks: 0.05MB + Silnik InnoDB
wp_mailpoet_automation_run_subjects: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_mailpoet_automation_triggers: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_mailpoet_automation_versions: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_custom_fields: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_dynamic_segment_filters: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_feature_flags: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_forms: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_mailpoet_log: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_mailpoet_migrations: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_newsletters: Dane: 0.02MB + Indeks: 0.05MB + Silnik InnoDB
wp_mailpoet_newsletter_links: Dane: 0.02MB + Indeks: 0.05MB + Silnik InnoDB
wp_mailpoet_newsletter_option: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_newsletter_option_fields: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_newsletter_posts: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_newsletter_segment: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_newsletter_templates: Dane: 2.52MB + Indeks: 0.00MB + Silnik InnoDB
wp_mailpoet_scheduled_tasks: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_mailpoet_scheduled_task_subscribers: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_segments: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_mailpoet_sending_queues: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_mailpoet_settings: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_statistics_bounces: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_mailpoet_statistics_clicks: Dane: 0.02MB + Indeks: 0.05MB + Silnik InnoDB
wp_mailpoet_statistics_forms: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_statistics_newsletters: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_mailpoet_statistics_opens: Dane: 0.02MB + Indeks: 0.08MB + Silnik InnoDB
wp_mailpoet_statistics_unsubscribes: Dane: 0.02MB + Indeks: 0.05MB + Silnik InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Dane: 0.02MB + Indeks: 0.08MB + Silnik InnoDB
wp_mailpoet_stats_notifications: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_mailpoet_subscribers: Dane: 0.02MB + Indeks: 0.23MB + Silnik InnoDB
wp_mailpoet_subscriber_custom_field: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_subscriber_ips: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_subscriber_segment: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_mailpoet_subscriber_tag: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_mailpoet_tags: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_user_agents: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_mailpoet_user_flags: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_options: Dane: 1.36MB + Indeks: 0.06MB + Silnik InnoDB
wp_postmeta: Dane: 0.06MB + Indeks: 0.03MB + Silnik InnoDB
wp_posts: Dane: 1.52MB + Indeks: 0.06MB + Silnik InnoDB
wp_termmeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_terms: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_term_relationships: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_term_taxonomy: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_usermeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_users: Dane: 0.02MB + Indeks: 0.05MB + Silnik InnoDB
wp_wc_admin_notes: Dane: 0.05MB + Indeks: 0.00MB + Silnik InnoDB
wp_wc_admin_note_actions: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_wc_category_lookup: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_wc_customer_lookup: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_wc_download_log: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_wc_orders: Dane: 0.02MB + Indeks: 0.11MB + Silnik InnoDB
wp_wc_orders_meta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_wc_order_addresses: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wp_wc_order_coupon_lookup: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_wc_order_operational_data: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_wc_order_product_lookup: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wp_wc_order_stats: Dane: 0.02MB + Indeks: 0.05MB + Silnik InnoDB
wp_wc_order_tax_lookup: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_wc_product_attributes_lookup: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_wc_product_download_directories: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_wc_product_meta_lookup: Dane: 0.02MB + Indeks: 0.09MB + Silnik InnoDB
wp_wc_rate_limits: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_wc_reserved_stock: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_wc_tax_rate_classes: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_wc_webhooks: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_wsal_metadata: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_wsal_occurrences: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_yoast_indexable: Dane: 0.02MB + Indeks: 0.09MB + Silnik InnoDB
wp_yoast_indexable_hierarchy: Dane: 0.02MB + Indeks: 0.05MB + Silnik InnoDB
wp_yoast_migrations: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_yoast_primary_term: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_yoast_seo_links: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB

### Post Type Counts ###

attachment: 31
custom_css: 1
customize_changeset: 3
mailpoet_page: 1
page: 13
post: 2
product: 2
revision: 74
sp_lc_shortcodes: 1
sp_logo_carousel: 24
wp_block: 1
wp_global_styles: 1
wp_navigation: 1
wp_template: 4
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ❌
					Twój sklep nie używa protokołu HTTPS. Dowiedz się więcej o HTTPS i certyfikatach SSL.
Hide errors from visitors: ❌Komunikaty o błędach nie powinny być widoczne dla użytkowników.

### Active Plugins (2) ###

Product Importer: przez Your Name – 1.0
WooCommerce: przez Automattic – 8.2.1

### Inactive Plugins (15) ###

Akismet Anti-spam: Spam Protection: przez Automattic - Anti-spam Team – 5.3
B Carousel Block: przez bPlugins LLC – 1.0.2
Google Listings and Ads: przez WooCommerce – 2.5.9
Gutena Forms - Contact Forms Block: przez ExpressTech – 1.1.4
Hello Dolly: przez Matt Mullenweg – 1.7.2
Jetpack: przez Automattic – 12.7
MailPoet: przez MailPoet – 4.32.0
Pinterest for WooCommerce: przez WooCommerce – 1.3.11
SVG Support: przez Benbodhi – 2.5.5
WooCommerce Payments: przez Automattic – 6.6.0
WP Activity Log: przez WP White Security – 4.5.3
WP Activity Log for WooCommerce: przez Melapress – 1.5.2
WP Map Block: przez Academy LMS – 1.4.8
WP Responsive Menu: przez MagniGenie – 3.1.8
Yoast SEO: przez Team Yoast – 21.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: PLN (zł)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Strona sklepu: #154 - /index.php/sklep/
Koszyk: #155 - /index.php/koszyk/
Zamówienie: #156 - /index.php/zamowienie/
Moje konto: #157 - /index.php/moje-konto/
Regulamin: ❌ Strona nie ustawiona

### Theme ###

Name: Twenty Twenty-Three
Version: 1.2
Author URL: https://pl.wordpress.org
Child Theme: ❌ – Jeśli modyfikujesz WooCommerce lub motyw nadrzędny
którego nie jesteś autorem
polecamy używanie motywu potomnego. Zobacz: Jak tworzyć motywy potomne

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-10-18 09:10:04 +02:00
Options: ✔
Notes: 63
Onboarding: completed

### Action Scheduler ###

Zakończ: 225
Oldest: 2023-10-16 11:10:55 +0200
Newest: 2023-10-17 18:45:24 +0200

Oczekujące: 5
Oldest: 2023-10-17 18:46:25 +0200
Newest: 2023-10-18 11:14:30 +0200

Niepowodzenie: 12
Oldest: 2023-10-16 11:20:20 +0200
Newest: 2023-10-17 18:45:24 +0200

### Status report information ###

Generated at: 2023-10-17 18:45:39 +02:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment] 2023-10-18 14:54
@Monniasza I'll close this issue as a duplicate of the one you created for the rest client. The issue you are experiencing is most likely related to a configuration conflict or similar between the rest client and your local development configuration.

**Closed as completed by rrennick** 2023-10-18 14:54 UTC
Labels: Bug, type: community contribution
