### ISSUE TITLE
Product bulk edit changes attribute value

### ISSUE THREAD

**Issue by ronnyadsetts** [woothemes/woocommerce#31276] opened 2021-11-22 17:54 UTC
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ x ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

When using bulk edit on products, even on a single product, the value of a global attribute is changed if the failure mode criteria are met (described below).

**Expected behavior**

Bulk editing products should leave attributes untouched.

**Actual behavior**

Bulk editing a product that has a global attribute of "Second-hand grade" set to "MINT-" has the attribute value changed to "MINT".

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a product attribute "Second-hand grade" with terms: UNUSED, MINT, EXC++, EXC+, EXC, VG, VG-, NEW, MINT-
2. Create a product with the attribute "Second-hand grade" set to "MINT-" and publish
3. Bulk edit the product and change something, eg., add a tag
4. The "Second-hand grade" is now set to "MINT"

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): https://v4dzbz9lcpv.c.updraftclone.com
Site address (URL): https://v4dzbz9lcpv.c.updraftclone.com
WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.1.0
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.8.0
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 350 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
PHP Version: 7.3.33
PHP Post Max Size: 25 MB
PHP Time Limit: 90
PHP Max Input Vars: 3000
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.22-MariaDB
Max Upload Size: 25 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: wp_
Total Database Size: 369.55MB
Database Data Size: 199.26MB
Database Index Size: 170.29MB
wp_woocommerce_sessions: Data: 19.55MB + Index: 0.36MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.31MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 7.52MB + Index: 7.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_abandoned_cart_aelia_currency: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 4.52MB + Index: 4.80MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_ac_abandoned_cart_history: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
wp_ac_atc_rules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ac_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_guest_abandoned_cart_history: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_ac_link_clicked_email: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_ac_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_notifications_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ac_opened_emails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_ac_sent_history: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_ac_statistics: Data: 1.52MB + Index: 0.16MB + Engine InnoDB
wp_ac_tiny_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_cart_abandonment: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 7.52MB + Index: 9.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mgmlp_csv_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mgmlp_folders: Data: 0.23MB + Index: 0.00MB + Engine InnoDB
wp_mgmlp_import_folders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mgmlp_thumbnails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mgmlp_userrole_permissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 12.44MB + Index: 0.48MB + Engine InnoDB
wp_postmeta: Data: 42.58MB + Index: 38.16MB + Engine InnoDB
wp_posts: Data: 10.52MB + Index: 3.81MB + Engine InnoDB
wp_redirection_404: Data: 0.42MB + Index: 0.20MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sfa_abandoned_carts: Data: 7.52MB + Index: 0.00MB + Engine InnoDB
wp_sib_model_contact: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.16MB + Index: 0.23MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_usermeta: Data: 7.52MB + Index: 8.03MB + Engine InnoDB
wp_users: Data: 0.39MB + Index: 0.34MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.41MB + Index: 0.31MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 1.52MB + Index: 0.69MB + Engine InnoDB
wp_wc_order_stats: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.20MB + Index: 0.19MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.41MB + Index: 0.70MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wsal_metadata: Data: 50.58MB + Index: 75.30MB + Engine InnoDB
wp_wsal_occurrences: Data: 4.52MB + Index: 9.03MB + Engine InnoDB
wp_wsal_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 6.52MB + Index: 4.30MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.22MB + Index: 0.33MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.17MB + Index: 0.16MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.36MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 5143
custom_css: 1
customize_changeset: 1
mgmlp_media_folder: 636
nav_menu_item: 6
oembed_cache: 1
page: 7
popup: 2
popup_theme: 9
post: 7
product: 2507
revision: 854
shop_coupon: 96
shop_order: 4436
shop_order_refund: 285
wc_order_status: 11

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Admin: by WooCommerce – 2.8.0
WooCommerce: by Automattic – 5.9.0

### Inactive Plugins (35) ###

Abandoned Cart Pro for WooCommerce: by Tyche Softwares – 8.13.0
Abandoned Cart Reports For WooCommerce: by Small Fish Analytics – 2.6.2
Akismet Anti-Spam: by Automattic – 4.2.1
Cookie Notice: by dFactory – 1.2.48
Custom Taxonomy Order: by Marcel Pol – 3.3.0
Facebook for WooCommerce: by Facebook – 2.6.7
Facebook for WordPress: by Facebook – 3.0.6
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 7.2.1
Limit Login Attempts Reloaded: by Limit Login Attempts Reloaded – 2.23.2
Loco Translate: by Tim Whitlock – 2.5.5
Media Library Folders Pro For WordPress: by Max Foundry – 7.0.5
Media Library Folders Pro for WordPress Reset: by Max Foundry – 7.0.5
Popup Maker: by Popup Maker – 1.16.2
Post Expirator: by PublishPress – 2.6.2
Preview E-mails for WooCommerce: by Digamber Pradhan – 2.0.1
Product GTIN (EAN, UPC, ISBN) for WooCommerce: by Emanuela Castorina – 1.1.1
PublishPress Capabilities: by PublishPress – 2.3
Quick Featured Images: by Kybernetik Services – 13.5.7
Redirection: by John Godley – 5.1.3
Restricted Site Access: by Jake Goldman
10up
Oomph – 7.2.0

Search By SKU - for Woocommerce: by Unroll Digital – 0.8.0
Sendinblue - WooCommerce Email Marketing: by Sendinblue – 2.0.32
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.16.63.25

WooCommerce Anti Fraud: by OPMC Australia Pty Ltd – 4.0
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.13
WooCommerce Global Payments HPP: by SkyVerge – 3.0.1
WooCommerce Order Status Manager: by SkyVerge – 1.13.2 (update to version 1.13.3 is available)
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce Pixel Manager: by woopt – 1.11.7
WooCommerce Product Bundles: by SomewhereWarm – 6.12.7
WooCommerce Waitlist: by Neil Pie – 2.3.2
WP Activity Log: by WP White Security – 4.3.3.1
WP Security Audit Log (Premium): by WP White Security – 3.5.1.1
WP Updates Notifier: by Scott Cariss – 1.6.0
Yoast SEO: by Team Yoast – 17.5

### Must Use Plugins (2) ###

Facebook Pixel GDPR Consent Checker: by Ronny Adsetts
Amazing Internet Ltd –

Find Products Failing Quality Control: by Orignally by Shane Gowland
Modifed and extended by Ronny Adsetts –

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #8 - /
Basket: #9 - /basket/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.4
Author URL: https://en-gb.wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 10,354
Oldest: 2021-10-24 11:50:49 +0100
Newest: 2021-11-22 17:44:42 +0000

Pending: 3
Oldest: 2021-11-22 17:55:24 +0000
Newest: 2021-11-22 18:40:24 +0000

### Status report information ###

Generated at: 2021-11-22 17:52:31 +00:00
`
</details>

**Comment by ronnyadsetts** [comment] 2021-11-26 12:12
Let me know if there's anything I can do to help with this.

**Comment by swatipawarGS** [comment] 2021-11-26 13:51
Hi @ronnyadsetts ,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using WooCommerce 5.9.0 version.

Please find below screencast for reference :

https://user-images.githubusercontent.com/94531721/143556865-4c95cc09-503e-42c6-addc-eabc2e648725.mp4



Please provide us more detailed steps and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by ronnyadsetts** [comment] 2021-11-26 14:35
Thanks @swatipawarGS. The only difference I can see in your test was we are not using the attribute as a variant. I'll try to reproduce in a new Wordpress instance.

**Comment by ronnyadsetts** [comment] 2021-11-26 15:54
@swatipawarGS I've verified this with a new install, a single *simple* product and a global attribute.

Attaching an export of the product used for testing. Maybe that would help reproduce it?

[wc-product-export-26-11-2021-1637941821734.csv](https://github.com/woocommerce/woocommerce/files/7609725/wc-product-export-26-11-2021-1637941821734.csv)

**Comment by swatipawarGS** [comment] 2021-11-29 15:17
Hi @ronnyadsetts ,

Thank you for the updated information. We are able reproduce the issue using the provided CSV on our end with WooCommerce 5.9.0 version.

Please find below screencast for reference :


https://user-images.githubusercontent.com/94531721/143830461-4ab3f749-ad3f-4d10-ab22-2767bf7fe1d4.mp4

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by ronnyadsetts** [comment] 2021-11-29 16:17
@swatipawarGS Thanks for confirming.

**Comment by ronnyadsetts** [comment] 2021-11-30 14:15
@rodelgc This has been reproduced independently by @swatipawarGS.

**Comment by ronnyadsetts** [comment] 2021-12-06 10:29
I'm not overly familiar with the Woo codebase but if someone has pointers on where to start in locating the bug, I'm happy to dig in and see if I can produce a patch to fix the issue as this is affecting a production website. Thanks.

**Comment by peterfabian** [comment] 2021-12-13 09:40
Hey @ronnyadsetts . Appreciate the report and your willingness to take a stab at fixing it. I wasn't able to reproduce locally when I tried it quickly now, but a good place to start looking for the issue is the [bulk_edit_save function](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/admin/class-wc-admin-post-types.php#L456).

**Comment by ronnyadsetts** [comment] 2021-12-13 10:19
@peterfabian Thanks for the pointer - I'll have a look see what I can find.

In terms of reproducing, I've previous attached a product export to the issue which should help. It's only an issue with simple products and only effects that exact global attribute value. I suspect something to do with the fact that one attribute value is a substring of another and/or that the affected value ends in a hyphen. It's an odd one at any rate.

**Comment by rrennick** [comment] 2023-10-25 19:27
I'll close this as I  could not reproduce this either with the latest version of WooCommerce.

**Closed as completed by rrennick** 2023-10-25 19:27 UTC
Labels: Bug, status: can't reproduce, Product/Inventory Management, plugin: woocommerce
