### ISSUE TITLE
CSS specificity

### ISSUE THREAD

**Issue by hogash** [woothemes/woocommerce#9055] opened 2015-09-05 16:38 UTC
Hey guys, first of all thank you so much for WooCommerce!! 
This is more of a feature request i think.

Are there any plans on rewriting the css into a BEM/SMACSS style or better said reducing the nesting of the selectors? This would probably mean classes everywhere but there are lots of advantages and benefits of refactoring the CSS.

Another question is, in case i would decide to PR this (assuming it's well done), would you consider accepting it?

PS: Here's a very interesting video of @csswizardry ITCSS arhitecture which i personally love it https://youtu.be/1OKZOV-iLj4?t=432 .

**Comment by jameskoster** [comment] 2015-09-07 14:59
This is something I've thought about quite a bit in the past. But in my experience it can be difficult to adopt these approaches in WordPress projects because a lot of their ideals are in conflict with constraints we find forced into. For example;

* We _must_ be specific with our selectors to avoid conflicts with other plugins / themes (frontend and backend).
* Now that classes are in the markup, we _cannot_ really change or remove them without breaking backwards compatibility.

These are two big-ticket items and if we cannot address them it makes me question whether the rest is worth it.

If you've looked through the CSS and have some specific ideas then please share them. The CSS can definitely be improved (a lot of it hasn't changed much since version 1). Let's discuss this before writing any code :-)

**Comment by hogash** [comment] 2015-09-10 08:33
Hey James,

Thanks for letting me know and for considering this! I agree completely that it can be difficult, especially in terms of backwards compatibility.

What i would suggest/propose is:

- Every existing class, in order to maintain a strong compatibility, probably should stay the same, but deprecated (until 3.0 series maybe?)

- New classes should be added for each tag. This probably means classes everywhere, also definitely prefixed.

- a guide and of WooCommerce Styling Guide should be created, for both internal use and external developers use. For example i've seen Trello's guide recently - https://gist.github.com/bobbygrace/9e961e8982f42eb91b80 .

For example i would suggest something like this:
```css

Instead of:

.woocommerce ul.products li.product, 
.woocommerce-page ul.products li.product {}
.woocommerce ul.products li.product a {}

Maybe something like this:

/* Body classes */
/* i saw there are other simple .woocommerce classes inside the dom */
.woo-body {} 
/* as it is now, this class added when WooCommerce's elements are loaded */
.woo-page-body {} 

/* List classes - isolated */
.woo-product-list {}
.woo-product-list-item {} /* 3rd level list item class */
.woo-product-list-item.woo--modifier {} /* modifier always in presence of class  */

/* component inside list item, non-dependent of list-item */
.woo-product-link {}
.woo-product-image {}
.woo-product-image-secondary {}
.woo-product-price {}
.woo-product-rating {}
/* etc. */

```

Such structure could avoid too much nesting and specificity. This is a rough example, i think i could prepare a much better proposal, also with multiple scenarios in mind.

PS: Definitely discussion before writing code :D

**Comment by jameskoster** [comment] 2015-09-10 10:26
I would love to do something like this. But the fact is, as soon as we remove the old classes peoples sites are going to break. And even though it will be because theme authors haven't updated their themes, we'll still get the blame.

Unfortunately, as this is only of any real benefit to developers, we can't really justify the change to angry customers either.

We're having a team meetup later in the month, I'll be sure to bring this up for discussion at some point then :-)

cc @mikejolley @mattyza

**Comment by jameskoster** [comment] 2015-10-01 15:04
The general consensus seems to be to add the standardised classes and leave the 'old' ones in place until 3.0 or so.

I'm not sure we'll get to this for 2.5, but at least we now have a plan :-)

**Comment by claudiosmweb** [comment] 2015-12-02 15:47
Better leave it for WooCommerce 3.0.

**Comment by Einkoro** [comment] 2016-01-14 02:09
In addition to more specific and consistent classes/IDs I would suggest that the jQuery/JS should be decoupled further from the markup structure in checkout,js, address-i8ln,js, country-select.js and etc at the same time. Currently there are many selectors relying upon specific parent and child nodes rather than targeting an ID or class. As it is now its very difficult to use Foundation for Sites or Semantic UI front end frameworks in themes with WooCommerce due to the HTML structure required in SUI and to a somewhat lesser extent Foundation. Specifically the structure of the checkout fields and their form validation. At this point I maintain a custom version of each of the front end scripts which is a lot of extra effort to maintain in addition to overriding nearly every WC template and the functions used to build the checkout fields.

I would be open to providing suggestions based on the changes I've had to make to use various frameworks or even providing a pull request to decouple it further. Should this be a separate issue?

**Comment by jameskoster** [comment] 2016-01-14 11:32
@Einkoro separate issue. PR's always welcome.

**Comment by JosefJezek** [comment] 2016-02-11 13:07
SUIT CSS is better...
https://suitcss.github.io

**Comment by jameskoster** [comment] 2016-02-11 14:47
@JosefJezek  Better than what? Care to elaborate?

**Comment by jchck** [comment] 2016-02-19 14:25
I would love to see the CSS improved. At a bare minimum, have a consistent class naming convention and remove all ID's.

I understand the concerns surrounding updating class structure and backwards compatibility however I do believe things need to be wrangled in a bit. The further down the road this gets pushed, the larger the issue will grow.

**Comment by jchck** [comment] 2016-02-19 14:27
Regarding backwards compatibility, what about a switch in settings to enqueue the current, old style sheet or updated stylesheet flowing SUIT/BEM/whatever.

**Comment by jameskoster** [comment] 2016-02-19 17:03
@jchck, the issue isn't the CSS as much as it is the markup itself. If you start removing classes / IDs you pretty much guarantee that third party themes / plugins are going to break.

I think our plan to leave the current classes as they are, but add new, standardised ones ASAP is a solid one. Then remove the old ones in version 3.0.

**Comment by hogash** [comment] 2016-02-20 13:32
@jameskoster wanted to reply a while back but since it's scheduled for 3.0 i thought we shouldn't hurry. I'm definitely into getting started working, however not sure how to start or when.

Here's my ideas of what i'd recommend for these CSS improvements:
1) Keep all existing ID's and classes intact in the markup. This will ensure nothing breaks. Also due to building a low specificity selectors, any user customisations will surely override the built-in CSS.
2) Add extra classes to every single tag in the markup. Class names should be relevant to component. WooCommerce as file templating system is pretty great so there's already a relevancy to components.
3) CSS selectors can now be totally reconstructed with low specificity and not cascading-dependent. I would expect 99% of the existing websites shouldn't be affected by these changes.
3.1) Start with global styles, continue with components (with media queries, not separately), while at the end  maximum/high specificity selectors with !important flags.
3.2) Avoid sharing same CSS. Even if there are multiple components doing pretty much the same thing, if they're built for different purposes, they should have separate CSS, even with the compromise of having duplicate code. This should avoid breaking other parts and mostly sticking to it's basic purpose.
3.3) BEM / SUIT CSS naming conventions. They have a lot in common and they both seem future proof and easy to maintain.
3.4) Everything `.woocommerce-` prefixed. Eg: `.woocommerce-Component {}`.
3.5) Nesting up to maximum 3 levels. There might be some who knows what exceptions, but highly unnecessary.

Any corrections, tips, ideas and suggestions are more than welcome. The purpose of this CSS improvement is to have a stable, future-proof, easy to maintain, low-specific, optimised CSS code.

**Comment by jameskoster** [comment] 2016-02-22 09:51
@hogash That sounds like a good outline and is pretty much what I had in mind. I'm not sure we need to add a class to literally every single tag but there are some things that should probably be more targetable, we should review that as we go.

We can do this in the next major release. 3.0 is when we'd _remove_ the old classes - if we're feeling brave xD

So yeah, step 1 imo is to work through all of the WooCommerce markup and add classes with names that follow the chosen standard (I agree with the `.woocommerce-` prefix). Step 2 is to refactor core CSS to use the new classes. Step 3, which happens much later is removing the defunct classes.

**Comment by addedlovely** [comment] 2016-03-12 16:34
Regarding backwards compatibility, when we are building bespoke themes we often find ourselves overriding core templates to just change a CSS class, it would be great to address this at the same time.

Would it be feasible to have inline CSS classes generated from a function, which could then be overwritten in functions.php of a theme. The function could be passed the expected class name e.g. 'col-set', which could then be overridden by the theme function in functions.php, with no need to edit the template.

When it comes to making css class name changes in core,  if the function is passed an old class name, you can map it to new class. Additionally themes could declare support for the new CSS classes with 'add_theme_support'. 

@jameskoster have another suggestion, for the list. We have also run into issues where JS functionality is tied to class names (Stripe plugin for example). It would be great to migrate to data attribute selectors in JS ( e.g. data-wc-checkout-form), freeing functionality from any future CSS name changes. Re. 3.4 isn't wc- the prefix?

**Comment by jameskoster** [comment] 2016-03-14 14:33
> when we are building bespoke themes we often find ourselves overriding core templates to just change a CSS class, it would be great to address this at the same time.

Why do you find yourself needing to do that? I can't really think of a good reason. Why don't you just use the class that already exists? You're potentially opening yourself up to a whole world of pain by doing this and I'd strongly advise against doing so.

**Comment by addedlovely** [comment] 2016-03-14 14:51
@jameskoster Maybe a touch simplified (we'll also change HTML, but most of that can be filtered / hooked). We build completely bespoke WooCommerce sites with heavily customised views. We also use a consistent grid system on most jobs (https://gridsetapp.com/) which requires it's own CSS classes for various responsive breakpoints.  Updating the WooCommerce templates isn't too much of a burden, given the majority of changes are CSS classes, but yes isn't ideal. 

Take content-single-product.php for example, it loads the `.product` class via post_class, which can be filtered (great!). But further down the template `.summary` is hard coded.

**Comment by jameskoster** [comment] 2016-03-14 17:31
@addedlovely Ah, I thought that might be the case. I'm not convinced that's a great reason though. I use a grid system in [Storefront](https://github.com/woothemes/storefront) ([Susy](http://susy.oddbird.net/)) and simply using a css preprocessor solves that problem. I'm pretty sure gridset has a sass and a less export option. I believe this is a better approach than applying a bunch of additional, non-contextual classes to your markup and overwriting template files. 

Obviously that's up to you, but I think it's unrealistic to expect the app you're working with to support all possible development practises. If you choose to continue this approach then yeah, overwriting template files is your only option I'm afraid.

**Comment by jameskoster** [comment] 2016-03-15 13:36
Just dropping this here; https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md 

Feels like a good convention to follow for when we get around to this, and for any new classes we add in the mean time.

**Comment by jameskoster** [comment] 2016-04-11 23:01
Closing this in favor of https://github.com/woothemes/woocommerce/issues/10674

**Closed by jameskoster** 2016-04-11 23:01 UTC
Labels: Needs Reporter Feedback, Theming
