### ISSUE TITLE
Define Main Product Category

### ISSUE THREAD

**Issue by ibzh56** [woothemes/woocommerce#30937] opened 2021-10-13 07:05 UTC
Hello,

I have many products on my website, I would like to be able to mass edit the main categories of my products via a CSV import.
Do you have a concrete solution to be able to do it quickly without doing it by hand.

Looking forward to a positive response, thank you

**Comment by rodelgc** [comment] 2021-10-15 10:13
Hi @ibzh56,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
﻿
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
﻿
- You may take a look at our [Importing Products](https://docs.woocommerce.com/document/product-csv-import-suite-importing-products/) documentation to see if it helps.
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
﻿
I am closing this issue for now as it seems to be a support request and not a bug.

**Closed as completed by rodelgc** 2021-10-15 10:13 UTC
Labels: type: support request
