### ISSUE TITLE
Editing a template produces a JS console error.

### ISSUE THREAD

**Issue by wavvves** [woothemes/woocommerce#42036] opened 2023-12-04 16:41 UTC
## Describe the bug

Editing a template produces a JS console error.

## To reproduce

1. Enable a blocks theme and go to Appearance > Editor > Templates > select any template (eg: Page: Cart)
2. Observe the following console error

<img width="914" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/17236129/ce398fc8-41c0-4519-90ed-ff56a7415947">

## Expected behavior

No console errors.

**Comment by mikejolley** [comment] 2023-12-13 16:11
Replicated but could not find the cause.

**Comment by Aljullu** [comment] 2024-01-08 13:40
This was fixed in https://github.com/woocommerce/woocommerce/pull/43221. The scripts related to the Command Palette were including some unnecessary dependencies, which were causing the error to appear.

**Closed as completed by Aljullu** 2024-01-08 13:40 UTC
Labels: Bug, Rubik, Blocks/Patterns/Templates
