### ISSUE TITLE
Update date completed for orders

### ISSUE THREAD

**Issue by fisoi** [woothemes/woocommerce#34877] opened 2022-09-29 07:51 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When updating an order with the PUT endpoint (/wp-json/wc/v3/orders/<id>), we try sending:
    "date_completed": null,
    "date_completed_gmt": null,
But the values don’t update to null. 
We also send “status" : "pending” in the same request and the status changes.

### Expected behavior

The values of the fields date_completed and date_completed_ gmt should change to null.

### Actual behavior

The values of the fields date_completed and date_completed_ gmt stay the same.

### Steps to reproduce

Send a PUT request to (/wp-json/wc/v3/orders/<id> on a comleted order. The request contains the following data:
{ 
"status" : "pending", 
"date_completed" : null, 
"date_completed_gmt": null 
}

### WordPress Environment

We don't have a system status report

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Konamiman** [comment] 2022-09-30 14:46
Hi @fisoi, thanks for your report. The behavior you are experiencing is by design, as the `date_completed` and `date_completed_gmt` are read-only (this is documented in [the WooCommerce REST API reference](https://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties)). I'm closing this for now, but please feel free to reach out if you have further questions or suggestions.

**Closed as not planned by Konamiman** 2022-09-30 14:46 UTC
Labels: Bug, REST/Store API/Webhooks, plugin: woocommerce
