### ISSUE TITLE
Cart and Checkout Blocks - Incompatible with "WooCommerce Bookings - Subject to Confirmation" payment option with Stripe

### ISSUE THREAD

**Issue by thisissandip** [woothemes/woocommerce#42381] opened 2023-05-02 10:20 UTC
## Describe the bug

Cart and Checkout Blocks display an error with the "WooCommerce Bookings - Subject to Confirmation" payment method when [Stripe](https://woocommerce.com/products/stripe/?aff=10486&cid=1131038) -  credit card/payment request buttons is active

## To reproduce

1. Install and active WooCommerce Bookings and [Stripe](https://woocommerce.com/products/stripe/?aff=10486&cid=1131038)
2. Set the Cart and Checkout Block pages as default pages 
3. Enable Stripe - Credit Card or Payment request buttons (Apple Pay/Google Pay)
4. Create a bookable product using [WooCommerce Bookings](https://woocommerce.com/products/woocommerce-bookings/?aff=10486&cid=1131038)
5. Set the booking product to "require confirmation" 

![k1sqc5.png](https://user-images.githubusercontent.com/69596988/235639892-3383e8e3-2d22-4935-af23-f65c1b19adb0.png)

6. Add the booking product to the cart and go to checkout
7. See the error

![ANihgm.png](https://user-images.githubusercontent.com/69596988/235640911-68acffe0-7322-4a75-925e-b24dda1a4027.png)

## Expected behavior

Enabling Stripe credit card/payment request buttons along with the "WooCommerce Bookings - Subject to Confirmation" payment option should not result in errors

**Comment by thisissandip** [comment] 2023-05-02 10:20
6239694-zen

**Comment by opr** [comment] 2023-05-05 16:23
Hi @thisissandip I was able to reproduce this, but not _exactly_ - sometimes it works, sometimes it doesn't work, depending on which browser I use and whether I'm logged in or not, it also seems to be a different error to what you get.

Either way this is definitely an issue, I will move this to our "Needs lead triage" column to get some further prioritisation on this, and also mention it in my porter handoff to the next porter. Thanks!

**Comment by ralucaStan** [comment] 2023-08-03 14:48
I say we move this to the next cycle, at least determining where the issues is located. cc @pmcpinto

**Comment by pmcpinto** [comment] 2023-08-04 06:36
> I say we move this to the next cycle, at least determining where the issues is located. cc @pmcpinto

+1 it would be helpful to identify the source of the problem

**Comment by mikejolley** [comment] 2024-07-25 15:16
I've retested this with Bookings 2.1.5 and Stripe 8.5.2 and found that it correctly displayed the "Check booking availability" gateway and nothing else using:

- Logged in account
- Guest customer
- Safari browser
- Arc (Chrome) browser

Given the issue said about a missing `.card` variable it seems like this would have been something on the Stripe side which has since been patched. I will close this issue out but if anyone can still replicate this issue and I've missed something please let me know.

**Closed as completed by mikejolley** 2024-07-25 15:16 UTC
Labels: Bug, Checkout, Rubik, block: checkout
