### ISSUE TITLE
Product list filtering by attribute and attribute_term not working on woocommerce rest api

### ISSUE THREAD

**Issue by mfissehaye** [woothemes/woocommerce#30654] opened 2021-09-08 05:31 UTC
woocommerce version: 5.5.2
wordpress version: 5.8

I posted this on the woocommerce-rest-api repo [here](https://github.com/woocommerce/woocommerce-rest-api/issues/270), but didn't get any response yet, so I am posting it again here.

Sending request to the api endpoint wp-json/wc/v3/products?attribute=Brand&attribute_term=55 returns all products including those that don't have the given attribute and attribute_term. What am I missing?

**Comment by tammullen** [comment] 2021-09-11 13:29
Hi {username},

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a custom code related question. Due to the number of bug reports being submitted, we are prioritizing work on them and are not able to attend to custom code questions. 

The best place to get help further is in the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) in the `#developers` channel. 
Or - Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-rest-api/) to see if the solutions listed there apply to your case;


If you confirm the bug, please open a new issue and provide us with clear steps to reproduce it.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.

**Closed as completed by tammullen** 2021-09-11 13:29 UTC
Labels: type: support request
