### ISSUE TITLE
'wc-enhanced-select' items disappear on mouse-over in WC 8.1 (as opposed to WC 8.0.3)

### ISSUE THREAD

**Issue by RobertoDonPedro** [woothemes/woocommerce#40151] opened 2023-09-13 18:44 UTC
### Describe the bug

`'class'    => 'wc-enhanced-select'` does not display the option items (drop-down list) as expected in **WC 8.1** with custom classes derived from WC_Settings_API:

**The items in the drop-down list disappear on mouse over.**

But exactly the same works with WC 8.0.3 and lower. 

It appears that neither `wc-enhanced-select.js` nor the way it is loaded, nor `abstract-wc-settings-api.php` has been changed between WC 8.1 and WC 8.0.3.

Any ideas what has changed between these two version in this regard or where to look further?

### Expected behavior

Display of all option items in the dropdown list on admin pages

### Actual behavior

The option items disappear on mouse over.

### WordPress Environment

Latest

**Comment by RobertoDonPedro** [comment] 2023-09-14 09:00
Update: If I copy the `admin.css` file from WC 8.0.3 to WC 8.1 then it works as expected. Currently trying to figure out which tags in the admin.css file make the difference....

**Comment by RobertoDonPedro** [comment] 2023-09-14 12:07
Just figured out the **solution**:

The issue is this line in admin.css file of WC 8.1: 
`.wp-admin.wc-wp-version-gte-53 .select2-container--default .select2-results__option--highlighted[data-selected]{background-color:var(--wp-admin-theme-color)}`

We can override it with:
.`wp-admin.wc-wp-version-gte-53 .select2-container--default .select2-results__option--highlighted[data-selected]{background-color:#0073aa !important;color:#fff !important;}`

Then it works again :)

**Comment by lsinger** [comment] 2023-09-14 14:03
This sounds like a regression that we should look to reproduce and solve.

**Comment by lukerahl** [comment] 2023-09-16 20:24
The issue is that the css variable --wp-admin-theme-color isn't defined anywhere.

**Comment by lsinger** [comment] 2023-09-18 11:49
That's a variable defined by the Gutenberg project -- the block editor. WooCommerce relies on that being present. Have you removed the block editor, by any chance? @RobertoDonPedro

**Comment by RobertoDonPedro** [comment] 2023-09-18 12:26
No @lsinger , I've used a complete fresh setup. Created new database, installed WP, activated and updated WooCommerce, tested my Plugin.

**Comment by lukerahl** [comment] 2023-09-18 14:32
I'm using the block editor on multiple sites and it's the same issue on all of them with that variable not being defined. Perhaps woocommerce should add a default value to the var function so that everything still displays correctly when it doesn't exist.

**Comment by rrennick** [comment] 2023-09-19 20:54
I'm still seeing this definition in `assets/client/admin/onboarding/style.css` when building `trunk`.

**Comment by ospiotr** [comment] 2023-09-23 13:05
I am able to replicate this issue using `woocommerce_admin_features` filter.
After applying this filter, the `--wp-admin-theme-color` CSS variable is missing.

- WooCommerce 8.1.1
- WordPress 6.3.1
- PHP 8.1.23

**Steps to replicate:**
1. Use a clean installation of WooCommerce
2. Add the following filter to functions.php file:
```
		add_filter('woocommerce_admin_features', function (array $features): array {
			$features = [];
			return $features;
		}, 90);
```
3. Go to WooCommerce settings
4. Use the Country field Select2 dropdown
5. You will notice items disappearing on hover

![woo81_select2](https://github.com/woocommerce/woocommerce/assets/27012265/d8eab204-720d-46b0-b10e-dfdea137e7ba)

**Comment by lumpysimon** [comment] 2023-11-03 11:41
I'm experiencing this issue too, it's affecting plugins that use Select2, e.g. 'Storewide Sale' and 'Free Gifts for WooCommerce'. It makes selecting items extremely difficult/confusing.

**Comment by chihsuan** [comment] 2024-01-19 07:32
I couldn't reproduce this issue with a fresh site using the latest WooCommerce.

It looks like this has been fixed by https://github.com/woocommerce/woocommerce/pull/40586

I'm going to close this. Feel free to reopen it if you're still facing the issue. Thanks!

**Closed as completed by chihsuan** 2024-01-19 07:32 UTC
Labels: Bug, Store Frontend, type: regression, type: community contribution
