### ISSUE TITLE
Inbox 2.0 click Tracks not working properly

### ISSUE THREAD

**Issue by pmcpinto** [woothemes/woocommerce#32205] opened 2021-12-22 17:18 UTC
### Describe the bug
The Tracks event tied to the inbox message click is not working properly

### To Reproduce
1. Create a new store with WC 6.1 beta installed
2. Enable event tracking
3. On the home screen scroll down to the inbox notifications
4. Click on the title or CTA
5. See that we're not firing wcadmin_inbox_action_click

### Actual behavior:
It's firing wcadmin_inbox_panel_view several times

### Expected behavior
It should fire wcadmin_inbox_action_click

**Comment by pmcpinto** [comment] 2021-12-22 17:19
@ilyasfoo @moon0326 can you check and fix this? We need to fix this on time for WC 6.1. Without the Tracks fix it will not be possible to measure the impact of the Inbox changes. 
Also, it would be great to check if the other Inbox events are working properly. They seem to be working fine, but it's good to double-check. Thanks!

**Comment by moon0326** [comment] 2021-12-22 19:30
Thank you for catching it @pmcpinto. We can definitely work on it to include in for WC 6.1.

I wasn't able to find any info on `wcadmin_inbox_action_click` in Inbox 2.0 [epic](https://github.com/woocommerce/woocommerce-admin/issues/7241) 

Do we need any properties for `wcadmin_inbox_action_click` such as clicked note title?

**Comment by pmcpinto** [comment] 2021-12-27 10:25
> I wasn't able to find any info on wcadmin_inbox_action_click in Inbox 2.0 epic

@moon0326 @ilyasfoo I think Elizabeth forgot to mention that we wanted to keep the existing Tracks events.

> Do we need any properties for wcadmin_inbox_action_click such as clicked note title?

Yes. We should keep the event props that we currently have in this event: note_name, note_content, screen, etc.

Let me know if you have additional questions. Thanks!

**Comment by pmcpinto** [comment] 2022-01-21 14:37
@moon0326 @ilyasfoo is it possible to check if the event is working properly? There's a drop in the number of wcadmin_inbox_action_click after the 6.1 release and getting the same issue as before: when I click in a message: no wcadmin_inbox_action_click and lots of wcadmin_inbox_panel_view

**Comment by pmcpinto** [comment] 2022-01-21 14:44
If there's something wrong, it needs to be fixed on time to be included in 6.2

**Comment by ilyasfoo** [comment] 2022-01-24 01:26
Apologies @pmcpinto, it seems this PR wasn't cherry-picked into 6.1. I totally missed checking it.

The fix is already in WCA3.1 and will be included in 6.2.

**Comment by pmcpinto** [comment] 2022-01-25 11:30
Thanks for the heads up. I'll test 6.2 RC1 to check if everything is working properly

**Comment by pmcpinto** [comment] 2022-02-22 12:58
@ilyasfoo @moon0326 is it possible to double-check if this fix is working fine? I'm checking the data and the total number of unique clicks remained almost the same after this fix was released, and it's still way below the numbers we were getting before the bug. On the other hand, the total number of counts clicks has increased and it's around the same level we were betting before the bug, which is very strange. I can send the Tracks links through Slack if necessary.

**Comment by ilyasfoo** [comment] 2022-02-23 06:14
@pmcpinto This is odd indeed. I've re-tested 6.2 and confirmed that `wcadmin_inbox_action_click` track was recorded on clicking both the note's title and note's action. I've seen my own track in Tracks Live. Is it possible that because the mouse changes to "finger" on hovering the note body, but clicking doesn't do anything, maybe misleading and cause users to think that the note isn't working?

> On the other hand, the total number of counts clicks has increased and it's around the same level we were betting before the bug, which is very strange. I can send the Tracks links through Slack if necessary.

Yes please, we'll need to dig deeper to investigate.

**Comment by ilyasfoo** [comment] 2022-03-23 09:36
For posterity, the last discussion on this was that the issue wasn't a track error. The cause may have been user behaviour changes. We're addressing the issue through https://github.com/woocommerce/woocommerce-admin/pull/8394 and https://github.com/woocommerce/woocommerce-admin/pull/8411.

I think it's safe to close this issue.

**Closed as completed by ilyasfoo** 2022-03-23 09:36 UTC
Labels: Bug, plugin: woocommerce
