### ISSUE TITLE
Black screen error in the Site Editor while opening Block Inserter sidebar or trying to search

### ISSUE THREAD

**Issue by veljkho** [woothemes/woocommerce#52699] opened 2024-11-11 10:55 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

There's a black screen error in the site editor when for e.g. adding a new template and trying to add some block via block inserter.
Issue is not reproducible with 9.4 but with 9.5-dev build, latest trunk as of writing this.

### Expected behavior

Block Inserter sidebar is shown and the user can search for the blocks to add via block inserter popup

### Actual behavior

Black screen with an error (check below what error), please check [this GIF ](https://d.pr/i/Pd0FAv)

### Steps to reproduce

1. Enable a classic theme (like Storefront theme).
2. Go to Appearance > Patterns.
3. Click to add a new pattern.
4. Click the Blue Icon to show the blocks sidebar.
5. Observe the issue.
6. Additionally check scenario of clicking a block inserter and searching for a block e.g. Cart

### What's inside copied error?

<details><summary>Copied error message</summary>

```
Ye@https://wc-testing.qawp.net/wp-includes/js/dist/blocks.min.js?ver=8474af4b6260126fa879:12:99320
Tr@https://wc-testing.qawp.net/wp-includes/js/dist/blocks.min.js?ver=8474af4b6260126fa879:19:4518
Cr/<@https://wc-testing.qawp.net/wp-includes/js/dist/blocks.min.js?ver=8474af4b6260126fa879:19:4710
Cr@https://wc-testing.qawp.net/wp-includes/js/dist/blocks.min.js?ver=8474af4b6260126fa879:19:4618
Cr/<@https://wc-testing.qawp.net/wp-includes/js/dist/blocks.min.js?ver=8474af4b6260126fa879:19:4717
Cr@https://wc-testing.qawp.net/wp-includes/js/dist/blocks.min.js?ver=8474af4b6260126fa879:19:4618
hS</d<@https://wc-testing.qawp.net/wp-includes/js/dist/block-editor.min.js?ver=dc2875dbcee52519979b:21:513084
useMemo@https://wc-testing.qawp.net/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:66621
287/t.useMemo@https://wc-testing.qawp.net/wp-includes/js/dist/vendor/react.min.js?ver=18.3.1:2:6087
hS<@https://wc-testing.qawp.net/wp-includes/js/dist/block-editor.min.js?ver=dc2875dbcee52519979b:21:512991
hu@https://wc-testing.qawp.net/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:60308
_o@https://wc-testing.qawp.net/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:74386
xo@https://wc-testing.qawp.net/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:73594
So@https://wc-testing.qawp.net/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:73199
xi@https://wc-testing.qawp.net/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:122921
bs@https://wc-testing.qawp.net/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:108751
vs@https://wc-testing.qawp.net/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:108679
gs@https://wc-testing.qawp.net/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:108540
as@https://wc-testing.qawp.net/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:105347
is@https://wc-testing.qawp.net/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:105736
Hl@https://wc-testing.qawp.net/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:46663
cs@https://wc-testing.qawp.net/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:106185
551/n.flushSync@https://wc-testing.qawp.net/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:127772
xe/</<@https://wc-testing.qawp.net/wp-includes/js/dist/compose.min.js?ver=85f0708cd2e6b26addeb:9:31281
o@https://wc-testing.qawp.net/wp-includes/js/dist/priority-queue.min.js?ver=9c21c957c7e50ffdbf48:2:3056
```
</details>

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.5.0-dev
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7-RC4
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.59 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1f
PHP Version: 8.2.18
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.11.7-MariaDB-1:10.11.7+maria~ubu2004
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 71
elementor_library: 1
mailpoet_page: 1
nav_menu_item: 17
page: 29
post: 12
product: 345
product_variation: 1402
revision: 22
shop_coupon: 5
shop_order: 280
shop_order_placehold: 6
wp_block: 4
wp_global_styles: 4
wp_navigation: 1
wp_template: 3
wp_template_part: 2
wpcf7_contact_form: 1
yaymail_template: 11

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Beta Tester: by WooCommerce – 2.3.2
WooCommerce: by Automattic – 9.5.0-dev

### Inactive Plugins (34) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
AutomateWoo: by WooCommerce – 6.1.0
Code Snippets: by Code Snippets Pro – 3.6.5.1
Contact Form 7: by Takayuki Miyoshi – 6.0
Facebook for WooCommerce: by Facebook – 3.3.0
Generate Child Theme: by Catch Plugins – 2.1
Germanized for WooCommerce: by vendidero – 3.18.4
Google for WooCommerce: by WooCommerce – 2.8.6
Gutenberg: by Gutenberg Team – 19.6.1
InstaWP Connect: by InstaWP Team – 0.1.0.64
Jetpack: by Automattic – 14.0
MailPoet: by MailPoet – 5.3.6
MailPoet Premium: by MailPoet – 5.2.0
One Stop Shop for WooCommerce: by vendidero – 1.6.2
Tax Exempt for WooCommerce: by Addify – 1.7.1 (update to version 1.8.1 is available)
Theme Activator API: by Veljko Vujanovic – 1.0
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Admin Test Helper: by WooCommerce – 0.7.6
WooCommerce Brands: by WooCommerce – 1.7.6 (update to version 1.7.7 is available)
WooCommerce Distance Rate Shipping: by WooCommerce – 1.4.0 (update to version 1.5.1 is available)
WooCommerce FedEx Shipping: by WooCommerce – 3.9.1 (update to version 4.1.2 is available)
WooCommerce Memberships: by SkyVerge – 1.23.0 (update to version 1.26.9 is available)
WooCommerce Shipping & Tax: by WooCommerce – 2.8.3
WooCommerce Smooth Generator: by Automattic – 1.1.0
WooCommerce Taxamo: by OPMC Australia Pty Ltd – 1.4.2
WooCommerce UPS Shipping: by WooCommerce – 3.5.8 (update to version 3.7.3 is available)
WooCommerce USPS Shipping: by WooCommerce – 4.8.2 (update to version 5.0.1 is available)
Woo Gift Cards: by Woo – 1.16.10 (update to version 2.1.0 is available)
WooPayments: by WooCommerce – 8.4.0
Woo Subscriptions: by WooCommerce – 5.6.0 (update to version 6.8.0 is available)
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.6.1
YayMail - WooCommerce Email Customizer: by YayCommerce – 3.5.6
YayMail Addon for AutomateWoo: by YayCommerce – 2.2.1
Yoast SEO: by Team Yoast – 23.8

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 91 KB

### WC Pages ###

Shop base: #19 - /shop/
Cart: #20 - /cart/ -  Contains the woocommerce/cart block
Checkout: #21 - /checkout/ -  Contains the woocommerce/checkout block
My account: #22 - /my-account/
Terms and conditions: #933 - /terms/

### Theme ###

Name: Storefront
Version: 4.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout
beta-tester-slotfill-examples

Daily Cron: ✔ Next scheduled: 2024-11-12 09:16:28 +00:00
Options: ✔
Notes: 87
Onboarding: completed

### Action Scheduler ###

Complete: 141
Oldest: 2024-10-12 13:25:29 +0000
Newest: 2024-11-11 10:43:04 +0000

Failed: 6,453
Oldest: 2024-02-28 08:04:43 +0000
Newest: 2024-11-11 10:40:44 +0000

Pending: 1
Oldest: 2024-11-11 15:40:50 +0000
Newest: 2024-11-11 15:40:50 +0000


### Status report information ###

Generated at: 2024-11-11 10:55:00 +00:00
```
</details>

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by gigitux** [comment] 2024-11-19 13:51
Thanks for opening the issue! I'm not able to replicate the issue, can you check again with a recent build?

https://github.com/user-attachments/assets/42f87131-0b62-4240-9dc2-f7d028c996aa

**Comment by veljkho** [comment] 2024-11-20 16:49
Hi @gigitux 
I was able to reproduce this on 9.5beta1 only, not with previous versions up to 9.3.3

**Comment by veljkho** [comment] 2024-11-20 16:55
@gigitux, it is also reproducible using the [latest nightly build](https://github.com/woocommerce/woocommerce/releases/download/nightly/woocommerce-trunk-nightly.zip).
I installed the Storefront theme, and I'm using WP 6.7. Please ensure the pattern has the `Synced` feature turned on while adding a new pattern. If you need a test site where I reproduced it, please get in touch with me.

**Comment by gigitux** [comment] 2024-11-20 17:05
Thanks for sharing a test site! I'm able to reproduce it! I'm going to update the reproduction steps 🙇

**Comment by nerrad** [comment] 2024-11-20 17:22
Does this only happen with the Storefront theme, or with _any_ classic theme?

**Comment by gigitux** [comment] 2024-11-20 17:25
> Does this only happen with the Storefront theme, or with _any_ classic theme?

Any classic theme.

Here is the error with the non-minified JavaScript:

```
blocks.js?ver=91512d3…:7944 Uncaught Error: Block type 'woocommerce/product-price' is not registered.
    at __experimentalSanitizeBlockAttributes (blocks.js?ver=91512d…19a818813c6:7944:11)
    at createBlock (blocks.js?ver=91512d…9a818813c6:10151:31)
    at blocks.js?ver=91512d…9a818813c6:10179:12
    at Array.map (<anonymous>)
    at createBlocksFromInnerBlocksTemplate (blocks.js?ver=91512d…9a818813c6:10176:32)
    at blocks.js?ver=91512d…9a818813c6:10179:42
    at Array.map (<anonymous>)
    at createBlocksFromInnerBlocksTemplate (blocks.js?ver=91512d…9a818813c6:10176:32)
    at block-editor.js?ver=…a85bb66f3:45766:233
    at mountMemo (react-dom.js?ver=18.3.1:16416:21)
```

**Comment by gigitux** [comment] 2024-11-20 17:43
It looks like that https://github.com/woocommerce/woocommerce/pull/52209 introduces the regression (cc @kmanijak). I will continue to investigate 👀

**Comment by kmanijak** [comment] 2024-11-21 11:07
We investigated the issue with @gigitux.

Short summary:
- the issue was there for some time already and it was raised for example here: https://github.com/woocommerce/woocommerce/issues/51138 and https://github.com/woocommerce/woocommerce/issues/46781 but it didn't crash the Editor
- when I exposed collections to the inserter in https://github.com/woocommerce/woocommerce/pull/52209, they use a `createBlocksFromInnerBlocksTemplate` method which internally has additional check for blocks and it throws an error when the block is not registered, hence the issue was "exposed" and crashed the Editor

Draft PR (I'll add tests soon): https://github.com/woocommerce/woocommerce/pull/53034

**Comment by kmanijak** [comment] 2024-11-25 14:15
Fixed in
- WooCommerce 9.5 - https://github.com/woocommerce/woocommerce/pull/53077
- `trunk` - https://github.com/woocommerce/woocommerce/pull/53108

**Comment by gigitux** [comment] 2024-12-11 15:34
We are going to reopen the issue because we noticed the same issue in the widget area. 

https://github.com/user-attachments/assets/c4f3b84c-6508-4d28-a81c-227749faca81


To reproduce this issue:
- Switch to a classic theme like Storefront
- Visit `wp-admin/widgets.php`
- Click on the + button and search "Product Collection"
- See the crash


The widget editor crashes when loading the Product Collection preview. If this block is frequently used and appears among the first visible blocks, the widget area crashes upon clicking the plus button.

**Comment by gigitux** [comment] 2024-12-11 17:36
[After some investigation](https://github.com/woocommerce/woocommerce/pull/53638), we discovered that this issue is not related to this issue. I created a dedicated issue #53639.

**Closed as completed by gigitux** 2024-12-11 17:36 UTC
Labels: Bug, needs: triage feedback, Kirigami, Blocks/Patterns/Templates
