### ISSUE TITLE
Sitemap URLs are showing 404

### ISSUE THREAD

**Issue by securevault** [woothemes/woocommerce#31423] opened 2021-12-11 16:17 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I tested it using twenty-twenty theme and activate only woocommerce.
I have more than 10k products.

the 404 only affect paginated sitemap after page 1. the first one is working fine.

https://xxx.xxx/wp-sitemap-posts-product-1.xml (OK)
https://xxx.xxx/wp-sitemap-posts-product-2.xml (404)
https://xxx.xxx/wp-sitemap-posts-product-3.xml (404)

the response header is 404. but it shows the sitemap correctly. But google and friends complain about it

### Expected behavior

should return 200 http status

### Actual behavior

return 404

### Steps to reproduce

1. install wordpress
2. install woocommerce
3. add more than 2000 products (or until it reach page 2 sitemap, you can see it in your wp-sitemap.xml)
4. go to https://yourdomain.com/wp-sitemap-posts-product-2.xml and see the response status in browser's developer tools

`
### WordPress Environment ###

WordPress address (URL): https://xxx.xxx.xxx
Site address (URL): https://xxx.xxx.xxx
WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.1.0
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.8.0
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.25
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.4-MariaDB-1:10.6.4+maria~focal
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: wp_
Total Database Size: 40.21MB
Database Data Size: 20.72MB
Database Index Size: 19.49MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.91MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 3.41MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 2.03MB + Engine InnoDB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_alm: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatorwp_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatorwp_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.45MB + Index: 0.55MB + Engine InnoDB
wp_debug_functions_time__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_digits_blocked_ip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ee_product_sync_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_emailTemplate: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_hurrytimer_evergreen: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jokuldb: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mclean_refs: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_mclean_scan: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.47MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 7.52MB + Index: 6.02MB + Engine InnoDB
wp_posts: Data: 3.52MB + Index: 1.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_social_users: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.23MB + Index: 0.30MB + Engine InnoDB
wp_terms: Data: 0.19MB + Index: 0.22MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.22MB + Index: 0.25MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wa_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wa_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcmp_shipping_zone_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_wc_comments_subscription: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.19MB + Index: 0.19MB + Engine InnoDB
wp_wc_order_stats: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_phrases: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_users_rated: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_users_voted: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_wishlist_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_wishlist_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpc_comments_subscription: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 3072
blocks: 7
custom_css: 2
customize_changeset: 6
dtwcbe_woo_library: 1
elementor_library: 1
helpie_faq: 2
hurrytimer_countdown: 1
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 24
oembed_cache: 2
page: 59
post: 2
product: 2211
product_variation: 3
revision: 43
shop_coupon: 1
shop_order: 957
shop_order_refund: 1
wa-order-numbers: 1
wbcr-snippets: 5
wcct_countdown: 1
wcpf_item: 4
wcpf_project: 1
wishlist: 1
wpdiscuz_form: 2
xxx_post_type: 5
xxxposttype: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 5.9.0

### Inactive Plugins (14) ###

Advanced Cron Manager: by BracketSpace – 2.4.1
Advanced Database Cleaner PRO: by Younes JFR. – 3.1.6
Debug This: by WPChill – 0.6.3
Loco Translate: by Tim Whitlock – 2.5.5
Media Cleaner: by Jordy Meow – 6.2.7
Query Monitor: by John Blackbourn – 3.7.1
Transients Manager: by Pippin Williamson – 1.8.1
TriPay Payment Gateway: by PT Trijaya Digital Grup – 3.2.0
WooCommerce Brands: by WooCommerce – 1.6.25
WooCommerce Points and Rewards: by WooCommerce – 1.7.2
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.46
WooCommerce Product Generator: by itthinx – 1.2.0
WooCommerce Shipment Tracking: by WooCommerce – 1.6.27
WP Mail SMTP: by WPForms – 3.2.1

### Dropin Plugins (1) ###

object-cache.php: object-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: IDR (Rp)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6045 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.3 (update to version 1.4 is available)
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,486
Oldest: 2021-11-12 16:24:05 +0000
Newest: 2021-12-12 14:02:19 +0000

Pending: 3
Oldest: 2021-12-12 14:03:19 +0000
Newest: 2021-12-14 09:20:30 +0000

### Status report information ###

Generated at: 2021-12-12 21:03:03 +07:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment] 2021-12-14 14:12
Hi @securevault ,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using WooCommerce 5.9.0 version . 

Please find below screenshots for reference :
Page 1 :

![#31423(page1)](https://user-images.githubusercontent.com/94531721/145998700-7eaf5751-5ac4-45e1-9dd0-fc07db59b446.jpg)

Page 2 : 
![#31423(page2)](https://user-images.githubusercontent.com/94531721/145998707-1a25a48f-b880-48fb-94de-a3aad69fce88.jpg)

Page 3 : 
![#31423(page3)](https://user-images.githubusercontent.com/94531721/145998709-87190caf-8adf-4ed5-91dd-4fb07f869f0c.jpg)

Please provide us more detailed and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by erikdemarco** [comment] 2021-12-15 03:43
Me too have the same problem. There's a bug report in WP with the same issue.

=> https://core.trac.wordpress.org/ticket/50910

Maybe is it related?

@swatipawarGS From your screenshot it seems like you not using native WP-sitemap settings. Because vanilla wp sitemap doesnt have images and last modified column in the sitemap. At least from what i reproduced. (see screenshot)

Here's my steps:
-) Clean Install WP 5.8.2 (use default theme twentytwenty one)
-) Install Woocommerce
-) Install "WooCommerce Product Generator by itthinx"
-) Generate 2500 products
-) Open 'yourdomain.com/wp-sitemap.xml'
-) Look for 'wp-sitemap-posts-product-2.xml' then click it
-) Dont be fooled by the appearance because it doesnt looks like 404 page. Open your web developer console to see the http status.

Here's the result:
**wp-sitemap-posts-product-1.xml (NORMAL)**
![Screenshot at 2021-12-15 10-40-00](https://user-images.githubusercontent.com/42645368/146119063-76f59136-cdcf-4b10-9916-c5b319b35f47.png)
**wp-sitemap-posts-product-2.xml (404, FIREFOX)**
![Screenshot at 2021-12-15 10-23-37](https://user-images.githubusercontent.com/42645368/146117872-33e38305-fe98-47fd-8522-0580d7ed688f.png)
**wp-sitemap-posts-product-2.xml (404, CHROME)**
![Screenshot at 2021-12-15 10-24-32](https://user-images.githubusercontent.com/42645368/146117878-7caa6e66-ddf6-4358-a7b9-c15c6c3cbb9f.png)




**Here's my system report:**
`
### WordPress Environment ###

WordPress address (URL): http://sand999.masuk.web.id/wp
Site address (URL): http://sand999.masuk.web.id/wp
WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.1.0
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.8.0
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.3.33
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.79.1
OpenSSL/1.1.1l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.41-MariaDB-log-cll-lve
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: wpes_
Total Database Size: 18.15MB
Database Data Size: 11.14MB
Database Index Size: 7.01MB
wpes_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpes_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpes_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpes_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpes_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpes_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpes_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpes_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpes_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpes_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpes_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpes_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpes_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpes_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpes_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wpes_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpes_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpes_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpes_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpes_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpes_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpes_options: Data: 2.47MB + Index: 0.03MB + Engine InnoDB
wpes_postmeta: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wpes_posts: Data: 2.52MB + Index: 0.78MB + Engine InnoDB
wpes_termmeta: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
wpes_terms: Data: 0.11MB + Index: 0.16MB + Engine InnoDB
wpes_term_relationships: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wpes_term_taxonomy: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
wpes_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpes_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpes_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpes_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpes_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpes_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpes_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpes_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpes_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpes_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpes_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpes_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpes_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpes_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpes_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2501
page: 7
post: 2
product: 2500

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Product Generator: by itthinx – 1.2.0
WooCommerce: by Automattic – 5.9.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.2.1
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2
Oldest: 2021-12-15 01:37:37 +0000
Newest: 2021-12-15 01:38:37 +0000


### Status report information ###

Generated at: 2021-12-15 03:44:44 +00:00
`

**Comment by swatipawarGS** [comment] 2021-12-15 14:42
Hi @erikdemarco ,

Thank you for the updated information. we are able reproduce the issue using the given updated information on our end with WooCommerce 5.9.0 version . 


Please find below screenshots for reference :

wp-sitemap-posts-product-1.xml: 

![#31423(page-1)](https://user-images.githubusercontent.com/94531721/146142099-e8533a74-b3c2-4310-82a0-6b64bb558e0f.jpg)

wp-sitemap-posts-product-2.xml (chrome) : 

![#31423(page-2)](https://user-images.githubusercontent.com/94531721/146142215-6ca8e89f-6a48-43e1-8c05-95f6f6d69b64.jpg)

wp-sitemap-posts-product-2.xml (Firefox) : 

![#31423(page-2(FireFox))](https://user-images.githubusercontent.com/94531721/146142213-6345e10a-25e6-4b8d-9d94-47725cbc7c02.jpg)


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by rodelgc** [comment] 2021-12-20 08:32
I'm able to reproduce the issue as well. I'm getting 404 on the 2nd products sitemap XML:
<img width="1268" alt="Screen Shot 2021-12-20 at 4 29 43 PM" src="https://user-images.githubusercontent.com/4509348/146736587-6de813cd-22df-4c66-a1af-0044642c1098.png">

**Comment by nicmare** [comment] 2022-02-08 11:05
same problem over here :-(
<img width="762" alt="image" src="https://user-images.githubusercontent.com/898582/152974983-c46ba9e1-c470-4ed6-b292-706a00da28a0.png">

**Comment by nicmare** [comment] 2022-02-19 11:21
fyi i bypassed the problem by merging all pages into one. google is fine with it.

```php
// weak fix to bypass 404 error for sitemap pages:
function return_sitemap_size($size, $object_type){
    return 10000;
}
add_filter( 'wp_sitemaps_max_urls', 'return_sitemap_size',10,2 );
```

**Comment by erikdemarco** [comment] 2022-07-19 09:04
The bug seems on this line:
https://github.com/WordPress/WordPress/blob/943e956379dd935ad6b401669a4c76526172f594/wp-includes/class-wp.php#L746

For some reason $set_404 is not set to false for paged > 1

Temporary fix here:
https://wp-kama.com/handbook/sitemap/bag-404-pagination

**Comment by rrennick** [comment] 2023-11-23 18:53
Closing this as addressed. Page 2 worked fine for me in the latest WC.

<img width="922" alt="Screenshot 2023-11-23 at 2 53 35 PM" src="https://github.com/woocommerce/woocommerce/assets/343847/9a0ef778-281e-4763-a6c5-a1c006610310">

**Closed as completed by rrennick** 2023-11-23 18:53 UTC
Labels: Bug, plugin: woocommerce

**Comment by phanduynam** [comment] 2025-09-18 07:39
@rrennick not done yet, still have this error
