### ISSUE TITLE
[GlobalStep] PHP Fatal error appears after updating the Woocommerce plugin to 9.5.0-rc.1 version when the "WooCommerce Beta Tester" plugin is installed and activated.

### ISSUE THREAD

**Issue by gglobalstep** [woothemes/woocommerce#53515] opened 2024-12-06 13:21 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

PHP Fatal error appears after updating the Woocommerce plugin to 9.5.0-rc.1 version when the "WooCommerce Beta Tester" plugin is installed and activated.

### Expected behavior

 Woocommerce plugin to 9.5.0-rc.1 version should be updated successfully without any error when the "WooCommerce Beta Tester" plugin is installed and activated.

### Actual behavior

PHP Fatal error appears after updating the Woocommerce plugin to 9.5.0-rc.1 version when the "WooCommerce Beta Tester" plugin is installed and activated.

### Steps to reproduce

1. Create a test site.
2. Install and activate the release Woocommerce version plugins.
3. Install and activate  WooCommerce Beta Tester plugin.
4. Go to WP-ADMIN -> Plugins & click on Upload Plugin to upload the testing package(i.e. WooCommerce 9.5.0-rc.1version).
5. Observe that, PHP Fatal error appears after updating the Woocommerce plugin to 9.5.0-rc.1 version when the "WooCommerce Beta Tester" plugin is installed and activated.

### Screenshot:
![Image](https://github.com/user-attachments/assets/786854d0-6449-49f2-9a4c-855370d5152d)

### WordPress Environment

Woocommerce Version: 9.5.0-rc.1
WordPress version: 6.7.1
PC:
Windows 10
Chrome (Version 131.0.6778.109)
Firefox (Version 133.0)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.5.0-rc.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.3.14
PHP Post Max Size: 2 GB
PHP Time Limit: 850
PHP Max Input Vars: 6144
cURL Version: 8.10.1
OpenSSL/3.0.15

SUHOSIN Installed: –
MySQL Version: 10.11.10-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
page: 7
post: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.5
Query Monitor: by John Blackbourn – 3.17.0
WooCommerce Beta Tester: by WooCommerce – 2.5.1
WooCommerce: by Automattic – 9.5.0-rc.1

### Inactive Plugins (0) ###


### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 3 KB

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/ -  Contains the woocommerce/cart block
Checkout: #7 - /checkout/ -  Contains the woocommerce/checkout block
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.3
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Block theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout
beta-tester-slotfill-examples

Daily Cron: ✔ Next scheduled: 2024-12-07 10:45:46 +00:00
Options: ✔
Notes: 58
Onboarding: -

### Action Scheduler ###

Complete: 4
Oldest: 2024-12-06 10:45:51 +0000
Newest: 2024-12-06 10:48:49 +0000

Failed: 1
Oldest: 2024-12-06 10:48:49 +0000
Newest: 2024-12-06 10:48:49 +0000

Pending: 1
Oldest: 2024-12-07 10:45:51 +0000
Newest: 2024-12-07 10:45:51 +0000


### Status report information ###

Generated at: 2024-12-06 13:22:55 +00:00
```
</details>

**Comment by chihsuan** [comment] 2024-12-11 00:38
This appears to be closely related to the autoloader issue we've identified in similar scenarios. The root cause involves late-stage callbacks during plugin updates leading to fatal errors due to class loading conflicts between versions.

Since this is essentially the same underlying problem. For now, I’ll close this ticket to consolidate our focus on resolving this more broadly in https://github.com/woocommerce/woocommerce/issues/52311.

**Closed as completed by chihsuan** 2024-12-11 00:38 UTC
Labels: Bug, plugin: woocommerce beta tester, focus: install-uninstall, type: fatal
