### ISSUE TITLE
Sold Individually fields

### ISSUE THREAD

**Issue by ALeeaa** [woothemes/woocommerce#36272] opened 2023-01-03 14:08 UTC
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I’ve found an issue on the recent versions of Woocommerce which displays the quantity input even though I checked the Sold Individually checkbox on the Inventory tab: https://snipboard.io/i1tDQS.jpg

### Expected behavior

Quantity field should be hidden if Sold Individually option is enabled

### Actual behavior

The quantity field is showing which is confusing as customers do not understand why they can’t hit + and change it to 2 or 3???

### Steps to reproduce

1.) Woocommerce edit product
2.) enable "Sold Individually" checkbox.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://stagingbif.wpengine.com
Site address (URL): https://stagingbif.wpengine.com
WC Version: 7.2.2
REST API Version: ✔ 7.2.2
WC Blocks Version: ✔ 8.9.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: ❌ 6.0.3 - There is a newer version of WordPress available (6.1.1)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.25
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.39-42-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.0
WC Database Prefix: wp_
Total Database Size: 139.30MB
Database Data Size: 122.42MB
Database Index Size: 16.88MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_itsec_bans: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_dashboard_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_itsec_logs: Data: 19.52MB + Index: 0.80MB + Engine InnoDB
wp_itsec_mutexes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_itsec_user_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_itsec_webauthn_credentials: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_webauthn_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 5.52MB + Index: 0.08MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 18.55MB + Index: 10.03MB + Engine InnoDB
wp_posts: Data: 2.52MB + Index: 0.73MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stock_log: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.13MB + Index: 0.17MB + Engine InnoDB
wp_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.22MB + Index: 0.16MB + Engine InnoDB
wp_term_taxonomy: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.17MB + Index: 0.20MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.28MB + Index: 0.48MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpml_mails: Data: 68.52MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Data: 3.52MB + Index: 1.33MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.11MB + Index: 0.20MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_yoast_prominent_words: Data: 0.13MB + Index: 0.30MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.45MB + Index: 0.30MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.09MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1680
custom-css-js: 1
ic_mega_menu: 3
itsec-dash-card: 8
itsec-dashboard: 1
mc4wp-form: 2
nav_menu_item: 62
oembed_cache: 2
page: 22
post: 6
product: 616
product_variation: 1163
revision: 26
shop_order: 19
testimonials: 3
woocommerce-lookbook: 5
wpcf7_contact_form: 1
wpcode: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 7.2.2

### Inactive Plugins (30) ###

Asset CleanUp: Page Speed Booster: by Gabe Livan – 1.3.8.9
Autoptimize: by Frank Goossens (futtta) – 3.1.3
Classic Editor: by WordPress Contributors – 1.6.2
Classic Widgets: by WordPress Contributors – 0.3
Contact Form 7: by Takayuki Miyoshi – 5.6.4
Duplicate Page: by mndpsingh287 – 4.4.9
Insight Core: by InsightStudio – 1.6.7.6
Invisible reCaptcha: by Mihai Chelaru – 1.2.3
iThemes Security Pro: by iThemes – 7.2.3
LookBook for WooCommerce: by VillaTheme – 1.0.9
ManageWP - Worker: by GoDaddy – 4.9.15
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.11
Microsoft Advertising Universal Event Tracking (UET): by Microsoft Corporation – 1.0.4
Query Monitor: by John Blackbourn – 3.10.1
Redirection: by John Godley – 5.3.4
Sequential Order Numbers for WooCommerce: by WebToffee – 1.4.8
Simple Custom CSS and JS: by SilkyPress.com – 3.41
Site Kit by Google: by Google – 1.88.0
Slider Revolution: by ThemePunch – 6.4.8
Sticky Menu (or Anything!) on Scroll: by WebFactory Ltd – 2.32
Stock Manager for WooCommerce: by StoreApps – 2.9.0
Template Library and Redux Framework: by Extendify – 4.3.19
Variation Swatches for WooCommerce: by Emran Ahmed – 2.0.11
Woocomerce Brands Pro: by Proword – 4.5.0
WP Accessibility Helper: by Alex Volkov – 0.6.2.4
WPBakery Page Builder: by Michael M - WPBakery.com – 6.9.0
WPCode Lite: by WPCode – 2.0.4.4
WP Mail Logging: by Wysija – 1.10.4
Yoast SEO: by Team Yoast – 19.10
Yoast SEO Premium: by Team Yoast – 19.5

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Must Use Plugins (5) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
WP Engine Cache Plugin: by WP Engine – 1.1.0
WP Engine Seamless Login Plugin: by WP Engine – 1.6.0
WP Engine Security Auditor: by wpengine – 1.0.10
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
exclude-from-search (exclude-from-search-2)
featured (featured-2)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #147 - /shop/
Cart: #149 - /shopping-cart/
Checkout: #151 - /checkout/
My account: #161 - /my-account/
Terms and conditions: #3267 - /warranty-returns/

### Theme ###

Name: Twenty Twenty-One
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-03 14:51:08 -04:00
Options: ✔
Notes: 9
Onboarding: completed

### Action Scheduler ###

Complete: 106
Oldest: 2022-11-30 02:30:37 +0000
Newest: 2023-01-03 14:07:21 +0000

Pending: 1
Oldest: 2023-01-04 14:00:59 +0000
Newest: 2023-01-04 14:00:59 +0000

### Status report information ###

Generated at: 2023-01-03 10:07:29 -04:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment] 2023-01-04 13:25
Hi @ALeeaa,
Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the  WooCommerce 7.2.2 version and WordPress 6.1.1 version. 

Please find below the screenshots for reference :

![#36272(checkobox)](https://user-images.githubusercontent.com/94531721/210496655-0ac535e2-e93a-40e5-be77-b4966db4a20d.jpg)
![#36272(product page)](https://user-images.githubusercontent.com/94531721/210496660-ceb6d0c4-5cbb-41b5-9f99-aadc41bddd6d.jpg)


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by barryhughes** [comment] 2023-01-09 19:09
Duplicate of https://github.com/woocommerce/woocommerce/issues/36007.

**Closed as completed by barryhughes** 2023-01-09 19:09 UTC
Labels: Bug, Cart, status: reproduction, plugin: woocommerce
