### ISSUE TITLE
RINs can't be styled

### ISSUE THREAD

**Issue by leonardola** [woothemes/woocommerce#38049] opened 2023-04-28 14:51 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

While testing RINs up I found ou they don't respect the styling of the message

This is how it was supposed to look like(notice the bold parts)
<img width="701" alt="Screenshot 2023-04-28 at 11 47 52 AM" src="https://user-images.githubusercontent.com/6342964/235179705-2e4381dc-ca02-41e6-9111-916f0c21e8ce.png">

This is how it actually looks like
![image (1)](https://user-images.githubusercontent.com/6342964/235179783-86e3fe2d-6c83-4e27-9f3f-4d08b2a6453b.png)

This happens both for `info` and `update` style RINs

### Steps to reproduce

- Create an RIN with a message that contains styling
- Check how the RIN shows up in the merchant /wp-admin area

### WordPress Environment

WooCommerce 7.6.1
Wordpress 6.2

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by octaedro** [comment] 2023-05-11 14:44
Thank you @leonardola for reporting this.

The missing bold in the title is because the inbox note was read.
![Screen Capture on 2023-05-05 at 14-12-28](https://user-images.githubusercontent.com/1314156/236523618-10aba975-fa4c-4d84-851e-d1ce0e61750a.gif)

Regarding the highlighted text I see we're using the tag `b` instead of `strong`, this is why the text is not bold.

![screenshot-user-images githubusercontent com-2023 05 11-11_33_59](https://github.com/woocommerce/woocommerce/assets/1314156/73adf29f-660c-4ab9-b59f-ed6517a9bb46)

There are two different `Dismiss` buttons in the image you shared, and that shouldn't happen. I couldn't reproduce that on my end.

**Comment by leonardola** [comment] 2023-05-11 17:25
Don't worry about the two dismiss buttons. I added one manually as a regular button because I was testing the other type of RIN and it does not have one.

Do you know the list of tags that are allowed for RINs?

**Comment by octaedro** [comment] 2023-05-11 17:54
@leonardola Another detail is the note length. The current `WooPay is back` note's body length is 357, but the [maximum is 320](https://github.com/Automattic/woocommerce.com/pull/12680).
So we won't be able to replace the `b` tags with `strong`.

> Do you know the list of tags that are allowed for RINs?

I'm not sure about the allowed tags, I can take a look at them later, but as far as I know, the system will strip the tags `b`, `i`, `iframe`, `script`. You can find more documentation [here](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/src/Admin/RemoteInboxNotifications/README.md).

**Comment by leonardola** [comment] 2023-05-15 16:19
> So we won't be able to replace the b tags with strong.

Shouldn't we ignore the html tags length as they will not show up?

**Comment by octaedro** [comment] 2023-05-16 19:38
> Shouldn't we ignore the html tags length as they will not show up?

@leonardola Yeah, it makes sense to ignore the HTML tags. I think there is a comment related to this, [here](https://github.com/Automattic/woocommerce.com/pull/12680/files#r820683420).

**Comment by octaedro** [comment] 2023-05-17 15:50
I will close this issue and open a [new one on WC.com](https://github.com/Automattic/woocommerce.com/issues/17032) to fix the HTML tags problem.

**Closed as completed by octaedro** 2023-05-17 15:50 UTC
Labels: Bug, plugin: woocommerce, Wayfinding
