### ISSUE TITLE
[PHP 8.3] array_sum(): Addition is not supported on type string

### ISSUE THREAD

**Issue by Chouby** [woothemes/woocommerce#40660] opened 2023-10-09 20:19 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When running WooCommerce with the development version of PHP 8.3, I get the error
```
array_sum(): Addition is not supported on type string
 /home/runner/work/polylang-wc/polylang-wc/tmp/woocommerce/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:2102
```

### Expected behavior

No error

### Actual behavior

-

### Steps to reproduce

1. Create a simple product
2. Check your error logs

The bug is due to the returned value of `get_post_meta()` call in https://github.com/woocommerce/woocommerce/blob/8.2.0-rc.2/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php#L2088
It returns an empty string by default, when no rating has been created.
See also https://wiki.php.net/rfc/saner-array-sum-product

### WordPress Environment

WP 6.4 (nightly)
WC 8.3 (trunk)
PHP 8.3 (dev)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tamarw** [comment] 2023-12-27 02:10
Sorry, not so familiar with Github bug tracking best practices. Is this closed because it is merged with another issue or because it was fixed? I can confirm it is not fixed and I tried the latest beta as well. I see it's high priority but that was 2 months ago; what's the typical turnaround for a high priority bugfix?

TIA and apologies if I posted wrong. 

I actually wrote a thread [here](https://wordpress.org/support/topic/php-warning-array_sum-addition-is-not-supported/) related to the issue until I found this and rolled back to PHP 8.2 which solved the issue.

**Comment by jorgeatorres** [comment] 2023-12-27 09:05
Hi @tamarw!

The original issue (i.e. this one) was fixed in WC 8.3, but now I see in the thread you've linked that this is a new one (i.e. it relates to a different part of the code). I'm re-opening this issue to investigate. Thanks for bringing this to our attention! 🙇

**Comment by jorgeatorres** [comment] 2023-12-27 09:06
We should probably review all `array_sum()` instances, as there's at least one more case of this error being triggered:

> [26-Dec-2023 22:54:22 UTC] PHP Warning: array_sum(): Addition is not supported on type string in /home/public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version1/class-wc-rest-orders-v1-controller.php on line 271

**Comment by tofuSCHNITZEL** [comment] 2024-01-04 00:06
yes I get:
` array_sum(): Addition is not supported on type string in \www\wp-content\plugins\woocommerce\includes\class-wc-order-item-product.php on line 158`
on the Order overview page

**Comment by giannisgx89** [comment] 2024-03-18 07:23
Same exact issue as well with latest version of WC and PHP 8.3

**Comment by webdados** [comment] 2024-03-29 11:17
With WooCommerce 8.8.0-beta.1 and PHP 8.3:

```
PHP Warning:  array_sum(): Addition is not supported on type string in ...plugins/woocommerce/includes/class-wc-order-item-product.php on line 175
PHP Warning:  array_sum(): Addition is not supported on type string in ...plugins/woocommerce/includes/class-wc-order-item-product.php on line 182
PHP Warning:  array_sum(): Addition is not supported on type string in ...plugins/woocommerce/includes/class-wc-order-item-product.php on line 183
PHP Warning:  array_sum(): Addition is not supported on type string in ...plugins/woocommerce/includes/class-wc-order-item-shipping.php on line 147
```

**Comment by Marian-Kechlibar** [comment] 2024-04-21 17:52
I concur: 
PHP Warning:  array_sum(): Addition is not supported on type string in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-order-item-product.php on line 174

**Comment by helgatheviking** [comment] 2024-05-08 12:24
Seeing this as well in `class-wc-order-item-product.php` It looks like it can be resolved if you changes [these lines](https://github.com/woocommerce/woocommerce/blob/9ad1321c66822bac312c66a9c3da68176266bf36/plugins/woocommerce/includes/class-wc-order-item-product.php#L169-L177) to 

```
if ( ! empty( $raw_tax_data['total'] ) && ! empty( $raw_tax_data['subtotal'] ) ) {
	$tax_data['subtotal'] = array_map( function( $tax ) {
		return floatval( wc_format_decimal( $tax ) );
	}, $raw_tax_data['subtotal'] );
	$tax_data['total']    = array_map( function( $tax ) {
		return floatval( wc_format_decimal( $tax ) );
	}, $raw_tax_data['total'] );

	// Subtotal cannot be less than total!
	if ( array_sum( $tax_data['subtotal'] ) < array_sum( $tax_data['total'] ) ) {
		$tax_data['subtotal'] = $tax_data['total'];
	}
}
```

But I couldn't tell you the ramifications of converting taxes from the current strings to floats... especially with different currencies.

**Comment by coreymckrill** [comment] 2024-05-17 22:28
In #47595 I have a solution that should avoid changing the types.

**Closed as completed** 2024-05-20 08:10 UTC
Labels: Bug, Data Structure/CRUD/Backend Processing, REST/Store API/Webhooks, type: community contribution, type: compatibility
